### ISSUE TITLE
More informative error messages when Selenium or Java missing are needed

### ISSUE THREAD

**Issue by mgol** [angular/protractor#1017]
When user is missing Selenium/Chromedriver, running the tests results in the following:

```
/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/lib/driverProviders/local.js:42
        throw new Error('Could not find chromedriver at ' +
              ^
Error: Could not find chromedriver at /Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/selenium/chromedriver.exe
    at LocalDriverProvider.addDefaultBinaryLocs_ (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/lib/driverProviders/local.js:42:15)
    at LocalDriverProvider.setupEnv (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/lib/driverProviders/local.js:59:8)
    at Runner.run (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/lib/runner.js:206:31)
    at Object.init (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/lib/launcher.js:136:12)
    at Object.<anonymous> (/Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/protractor/lib/cli.js:129:23)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
>> 
Fatal error: protractor exited with code: 1
```

which doesn't directly say what command to invoke.

If they're missing Java, it's way worse; Protractor errors in some random file with no mention of Java at all. The Selenium error is easier to circumvent, one can add the command:

```
./node_modules/.bin/webdriver-manager update
```

to the build process so it's always run; installing Java usually requires system-specific operations so it cannot be automated so easily.

IMO Protractor should check for Java existence before executing any code using it and should give an informative error message when it's not installed.

The Java error has already bitten a fresh coworker that tried to fire up the project & all tests and it didn't immediately occur to me he's missing Java.

**Comment by cnishina** [comment]
Conf file:
```
exports.config = {
  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'chrome'
  },

  // Framework to use. Jasmine is recommended.
  framework: 'jasmine',

  // Spec patterns are relative to the current working directory when
  // protractor is called.
  specs: ['example_spec.js'],

  // Options to be passed to Jasmine.
  jasmineNodeOpts: {
    defaultTimeoutInterval: 30000
  }
};
```

When selenium standalone server is not present:

```
./bin/protractor example/conf.js
[01:25:03] E/local - Error code: 135
[01:25:03] E/local - Error message: No selenium server jar found at the specified location (/Users/cnishina/src/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar). Check that the version number is up to date.
[01:25:03] E/local - Error: No selenium server jar found at the specified location (/Users/cnishina/src/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar). Check that the version number is up to date.
    at BrowserError.Error (native)
    at BrowserError.IError [as constructor] (/Users/cnishina/src/protractor/built/exitCodes.js:13:23)
    at BrowserError.ProtractorError [as constructor] (/Users/cnishina/src/protractor/built/exitCodes.js:21:28)
    at new BrowserError (/Users/cnishina/src/protractor/built/exitCodes.js:67:23)
    at Local.addDefaultBinaryLocs_ (/Users/cnishina/src/protractor/built/driverProviders/local.js:44:19)
    at Local.setupEnv (/Users/cnishina/src/protractor/built/driverProviders/local.js:74:14)
    at Runner.run (/Users/cnishina/src/protractor/built/runner.js:274:37)
    at TaskRunner.run (/Users/cnishina/src/protractor/built/taskRunner.js:116:27)
    at createNextTaskRunner (/Users/cnishina/src/protractor/built/launcher.js:228:28)
    at /Users/cnishina/src/protractor/built/launcher.js:253:13
[01:25:03] E/launcher - Process exited with error code 135
```

When selenium standalone is present and chromedriver is not present:

```
./bin/protractor example/conf.js
[01:25:30] E/local - Error code: 135
[01:25:30] E/local - Error message: Could not find chromedriver at /Users/cnishina/src/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25
[01:25:30] E/local - Error: Could not find chromedriver at /Users/cnishina/src/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25
    at BrowserError.Error (native)
    at BrowserError.IError [as constructor] (/Users/cnishina/src/protractor/built/exitCodes.js:13:23)
    at BrowserError.ProtractorError [as constructor] (/Users/cnishina/src/protractor/built/exitCodes.js:21:28)
    at new BrowserError (/Users/cnishina/src/protractor/built/exitCodes.js:67:23)
    at Local.addDefaultBinaryLocs_ (/Users/cnishina/src/protractor/built/driverProviders/local.js:60:27)
    at Local.setupEnv (/Users/cnishina/src/protractor/built/driverProviders/local.js:74:14)
    at Runner.run (/Users/cnishina/src/protractor/built/runner.js:274:37)
    at TaskRunner.run (/Users/cnishina/src/protractor/built/taskRunner.js:116:27)
    at createNextTaskRunner (/Users/cnishina/src/protractor/built/launcher.js:228:28)
    at /Users/cnishina/src/protractor/built/launcher.js:253:13
[01:25:30] E/launcher - Process exited with error code 135
```

The error message currently does not tell the user to run `webdriver-manager update`.

**Comment by cnishina** [comment]
New message: 

> Could not find chromedriver at /Users/cnishina/src/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25. Run 'webdriver-manager update' to download binaries.
