### ISSUE TITLE
issue with the webdriver-manager start

### ISSUE THREAD

**Issue by ghost** [angular/protractor#1067]
when I run webdriver-manager start, after an update which processes successfully, I get this error:

```
C:\Program Files\nodejs\node_modules\webdriver-manager\lib\index.js:243
  console.log('seleniumProcess.pid: ' + seleniumProcess.pid);
                                        ^
ReferenceError: seleniumProcess is not defined
    at WebdriverManager.start (C:\Program Files\nodejs\node_modules\webdriver-ma
nager\lib\index.js:243:41)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\webdriver-manage
r\bin\webdriver-manager:59:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

I'm trying to run this on a 64bit windows 7 machine, running node v0.10.29 and Java SE runtime environment build 1.8.0_05-513. Do I need to install some separate selenium dependency for windows? Seems obvious and common, but I tried to google this but I found no one with the same error.

**Comment by jabbink** [comment]
FYI: Had the same on Windows.

Turns out `cmd` wasn't in my `PATH`.

**Comment by RajMondaz** [comment]
when I run webdriver-manager start, after an update which processes successfully, I get this error:

C:\Users\Developer>webdriver-manager start
seleniumProcess.pid: undefined
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by gbmhunter** [comment]
jabbink's comment fixed the issue for me on Windows.

**Comment by mona9301** [comment]
Getting same error on my desktop on Windows 7 enterprise. Could u please provide the better solution for this?
C:\Users\E0360862>webdriver-manager start
selenium.pid: undefined
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn cmd ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

Thanks.

**Comment by ntoungILL** [comment]
If jabbink's solution didn't work, add "C:\Windows\System32\" to your PATHs. On windows, right-click My Computer -> Properties -> Advanced system settings -> Environment Variables -> Edit... PATH and add "C:\Windows\System32\" to the end (with a semi-colon separating each variable).

**Comment by phanect** [comment]
@mona9301's issue also happens on Linux. (Kubuntu 14.04)
I found I didn't install Java. I installed it and the issue is fixed.

I think `webdriver-manager` should show error message that `java` is not installed or not under `PATH`.
@juliemr Can you reopen this?

**Comment by anoopmd** [comment]
jabbink's comment fixed the issue for me on Windows.
If you do not have administrative priviliges to change your path variable, you can do this in your command line

> SET PATH=%PATH%;C:\Windows\System32

**Comment by mona9301** [comment]
Thanks all for your good response.. This issue is resolved.

**Comment by saikishore12** [comment]
Thanks all,It even solved my issue

**Comment by trivedishrey** [comment]
Hi,

I am getting following error after giving command webdriver-manager start.

seleniumProcess.pid: 4236
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/gr
id/selenium/GridLauncher : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: org.openqa.grid.selenium.GridLauncher. Program wi
ll exit.
Selenium Standalone has exited with code 1

**Comment by jayantabms** [comment]
i used this approach and it solve my issue thanks .for the post  "C:\Windows\System32\" to your PATHs. On windows, right-click My Computer -> Properties -> Advanced system settings -> Environment Variables -> Edit... PATH and add "C:\Windows\System32\" to the end (with a semi-colon separating each variable)

**Comment by h-rueda** [comment]
I reproduced this error today when trying to install protractor and then start the webdriver-manager in Fedora

**Comment by h-rueda** [comment]
I got it. I was missing java-sdk :)

**Comment by shrikantbiradar3449** [comment]
I tried adding C:\Windows\System32 in my PATH and also my jdk is there in the PATH as well..
but still I am getting the same error when I execute the command 
C:\Users\neejaga>**webdriver-manager start**
**events.js:160
      throw er; // Unhandled 'error' event**
      ^

Error: connect ETIMEDOUT 172.217.23.176:443
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

**Comment by faissrizz** [comment]
W/start - Selenium Standalone server encountered an error: Error: spawn cmd ENOENT

**Comment by adubbaka2017** [comment]
This issue got resolved by setting the System Variables.
SET PATH=C:\Windows\System32

Also set the environment variables Path to JDK

**Comment by faissrizz** [comment]
Thank you

**Comment by harikrishna126** [comment]
@adubbaka2017 It worked!!, Thanks...!
