### ISSUE TITLE
ECONNREFUSED after server shutdown with grunt-protractor-runner

### ISSUE THREAD

**Issue by DavidTanner** [angular/protractor#1123]
Using version 1.0.0 I get an error message that the connection was refused.  This is similiar to issue #85.  I found someone had similiar issues in http://stackoverflow.com/questions/21382962/when-running-protractor-with-phantomjs-browser-only-able-to-run-tests-once and changed my version to 0.24.2 and the issue went away.  

Session deleted: Going to shut down the Selenium server
Shutting down Selenium server: http://127.0.0.1:4444
Shut down Selenium server: http://127.0.0.1:4444 (OKOK)

node_modules/protractor/node_modules/selenium-webdriver/http/index.js:136
      callback(new Error(message));
               ^
Error: ECONNREFUSED connect ECONNREFUSED
    at ClientRequest.<anonymous> (node_modules/protractor/node_modules/selenium-webdriver/http/index.js:136:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:415:13)
==== async task ====
WebDriver.quit()

**Comment by spikeybill** [comment]
please reference https://github.com/teerapap/grunt-protractor-runner/issues/99 and https://github.com/teerapap/grunt-protractor-runner/issues/100 I managed to resolve this

**Comment by skjoshi** [comment]
If any one has got the solution to this problem, please provide the details. I am facing same issue on mac osx. 

Running "protractor:webdriver" (protractor) task
Using the selenium server at http://localhost/wd/hub
[launcher] Running 1 instances of WebDriver
ERROR - Unable to start a WebDriver session.

/Users/sjoshi/Documents/SJWorkspace/GDAClientAutomationTest/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145
      callback(new Error(message));
               ^
Error: ECONNREFUSED connect ECONNREFUSED
    at ClientRequest.<anonymous> (/Users/sjoshi/Documents/SJWorkspace/GDAClientAutomationTest/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145:16)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1552:9)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/Users/sjoshi/Documents/SJWorkspace/GDAClientAutomationTest/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:149:22)
    at Function.webdriver.WebDriver.createSession (/Users/sjoshi/Documents/SJWorkspace/GDAClientAutomationTest/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:123:30)
    at Builder.build (/Users/sjoshi/Documents/SJWorkspace/GDAClientAutomationTest/node_modules/protractor/node_modules/selenium-webdriver/builder.js:294:22)
    at DriverProvider.getNewDriver (/Users/sjoshi/Documents/SJWorkspace/GDAClientAutomationTest/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at Runner.createBrowser (/Users/sjoshi/Documents/SJWorkspace/GDAClientAutomationTest/node_modules/protractor/lib/runner.js:180:37)
    at /Users/sjoshi/Documents/SJWorkspace/GDAClientAutomationTest/node_modules/protractor/lib/runner.js:257:21
    at _fulfilled (/Users/sjoshi/Documents/SJWorkspace/GDAClientAutomationTest/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/Users/sjoshi/Documents/SJWorkspace/GDAClientAutomationTest/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/Users/sjoshi/Documents/SJWorkspace/GDAClientAutomationTest/node_modules/protractor/node_modules/q/q.js:759:13)
[launcher] Process exited with error code 1


Also if there are any specific versions that are compatible and works for you, please specify them.

**Comment by juliemr** [comment]
Looks like this is resolved. Closing.
