### ISSUE TITLE
ScriptTimeoutError: asynchronous script timeout: result was not received in 0 seconds

### ISSUE THREAD

**Issue by wakandan** [angular/protractor#117]
I'm getting this error occasionally, making all previously-passed tests failed. I saw this code `driver.manage().timeouts().setScriptTimeout(5, TimeUnit.SECONDS);` from 

http://stackoverflow.com/questions/11646586/unable-to-execute-selenium-asynchronous-script

but I don't know how to run something like that from my protractor test. How should I proceed with this?

**Comment by rakslalsangi** [comment]
@juliemr , I used SetScriptTimeout for AngularJS busy processing in Selenium c# ( in my framework ) to handle the timeout exception , now selenium 3.2.0 giving warning as " ITimeouts.SetScriptTimeout(TimeSpan) is obsolete " and saying "Please set the AsynchronousJavaScript property instead " . Please help me in this scenario how to 
solve this warning .

"

**Comment by collintob** [comment]
@juliemr , I've placed my browser.driver.manage().timeouts().setScriptTimeout in my beforeEach, but the timeout is not respected in the test. Here's example code that counts down 15 seconds, with a supposed 10 second timeout. The test counts down all of the way through 15 seconds without stopping/timing out. Can you advise?

`var baseFuncs = require("../../pages/ams.base.po.js");\

describe('quick test - smoke 1', function () {
    beforeEach(function () {
        browser.driver.manage().timeouts().setScriptTimeout(10000);
        baseFuncs.getBasePage("foo1");
    });

    it('foo - bar1', function () {
        baseFuncs.countDown(15000);
    });

    afterEach(function () {
        console.log("done with 1");
    });

});`

**Comment by harin10** [comment]
I am getting a similar error could you please help me out. I tried the above options but I still see the issue.

[18:00:34] E/plugins -          ScriptTimeoutError: asynchronous script timeout: result was not received in 60 seconds
                  (Session info: chrome=66.0.3359.139)
                  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 6.1.7601 SP1 x86_64)
                    at Object.checkLegacyResponse (X:\projects\Protractor\COSTCO_APP\node_modules\selenium-webdriver\lib\error.js:546:15)
                    at parseHttpResponse (X:\projects\Protractor\COSTCO_APP\node_modules\selenium-webdriver\lib\http.js:509:13)
                    at doSend.then.response (X:\projects\Protractor\COSTCO_APP\node_modules\selenium-webdriver\lib\http.js:441:30)
                    at process._tickCallback (internal/process/next_tick.js:109:7)
                From: Task: WebDriver.executeScript()
                    at Driver.schedule (X:\projects\Protractor\COSTCO_APP\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
                    at Driver.executeAsyncScript (X:\projects\Protractor\COSTCO_APP\node_modules\selenium-webdriver\lib\webdriver.js:891:17)
                    at run (X:\projects\Protractor\COSTCO_APP\node_modules\protractor\built\browser.js:59:33)
                    at ProtractorBrowser.to.(anonymous function) [as executeAsyncScript] (X:\projects\Protractor\COSTCO_APP\node_modules\protractor\built\browser.js:67:16)
                    at Object.waitForPromise (X:\projects\Protractor\COSTCO_APP\node_modules\protractor-xhr-only-plugin\index.js:60:10)
                    at resolver (X:\projects\Protractor\COSTCO_APP\node_modules\protractor\built\plugins.js:194:51)
                    at new ManagedPromise (X:\projects\Protractor\COSTCO_APP\node_modules\selenium-webdriver\lib\promise.js:1077:7)
                    at Plugins.safeCallPluginFun (X:\projects\Protractor\COSTCO_APP\node_modules\protractor\built\plugins.js:210:20)
                    at promises.pluginObjs.filter.map.pluginObj (X:\projects\Protractor\COSTCO_APP\node_modules\protractor\built\plugins.js:219:40)
                    at Array.map (native)
