### ISSUE TITLE
Protractor unable to load urls in ios-driver with wrapDriver

### ISSUE THREAD

**Issue by lrvick** [angular/protractor#121]
Protractor current release seems unable to open urls in ios-driver with protractor.wrapDriver().get() however regular webdriver..Builder().get() works as expected

### Open chrome browser via regular selenium-standalone-server and loads URL as expected

```javascript
var driver = new webdriver.Builder().
    usingServer('http://localhost:4443/wd/hub').
    withCapabilities(webdriver.Capabilities.chrome()).build();
driver.manage().timeouts().setScriptTimeout(20000);
var ptor = protractor.wrapDriver(driver);
ptor.get('http://www.angularjs.org');
```

### Open Safari browser on iPhone emulator via ios-driver server and loads URL as expected

```javascript
capabilities = webdriver.Capabilities.iphone()
capabilities['language'] = 'en';
capabilities['simulator'] = true;
var driver = new webdriver.Builder().
    usingServer('http://localhost:4444/wd/hub').
    withCapabilities(capabilities).build();
driver.get('http://www.angularjs.org');
```

### Should open Safari browser on iPhone emulator via ios-driver server and load URL 

```javascript
capabilities = webdriver.Capabilities.iphone()
capabilities['language'] = 'en';
capabilities['simulator'] = true;
var driver = new webdriver.Builder().
    usingServer('http://localhost:4444/wd/hub').
    withCapabilities(capabilities).build();
driver.manage().timeouts().setScriptTimeout(20000);
var ptor = protractor.wrapDriver(driver);
ptor.get('http://www.angularjs.org');
```

... but it dies with following traceback:

```
/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/promise.js:1542
      throw error;
            ^
UnknownError: undefined
    at new bot.Error (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/atoms/error.js:109:18)
    at Object.bot.response.checkResponse (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/atoms/response.js:103:11)
    at /Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:275:20
    at /Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/goog/base.js:1178:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/promise.js:1438:20)
    at notify (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/promise.js:328:12)
    at notifyAll (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/promise.js:297:7)
    at fulfill (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/promise.js:402:7)
    at /Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/promise.js:1305:10
    at /Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/goog/base.js:1178:15
==== async task ====
WebDriver.manage().timeouts().setScriptTimeout(20000)
    at webdriver.WebDriver.schedule (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:266:15)
    at webdriver.WebDriver.Timeouts.setScriptTimeout (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1148:23)
    at Object.<anonymous> (/Users/default/Sources/protractorTesting/test/spec/iosSpec.js:20:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

shell returned 8/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/promise.js:1542
      throw error;
            ^
UnknownError: undefined
    at new bot.Error (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/atoms/error.js:109:18)
    at Object.bot.response.checkResponse (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/atoms/response.js:103:11)
    at /Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:275:20
    at /Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/goog/base.js:1178:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/promise.js:1438:20)
    at notify (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/promise.js:328:12)
    at notifyAll (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/promise.js:297:7)
    at fulfill (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/promise.js:402:7)
    at /Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/promise.js:1305:10
    at /Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/goog/base.js:1178:15
==== async task ====
WebDriver.manage().timeouts().setScriptTimeout(20000)
    at webdriver.WebDriver.schedule (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:266:15)
    at webdriver.WebDriver.Timeouts.setScriptTimeout (/Users/default/Sources/protractorTesting/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1148:23)
    at Object.<anonymous> (/Users/default/Sources/protractorTesting/test/spec/iosSpec.js:20:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

shell returned 8
```

**Comment by juliemr** [comment]
This can now be closed.
