### ISSUE TITLE
Running a test with multiple browsers causes "Error: Server has not been started."

### ISSUE THREAD

**Issue by mitchhentges** [angular/protractor#1221]
When running my tests, I have noticed that I am getting peculiar "Server has not been started" errors when testing with multiple browsers. I am using Windows 7 64bit with Node version `v0.10.26`.

I've narrowed this down to a  minimal test case. The config file is:
```javascript
exports.config = {

    seleniumPort: null,
    seleniumArgs: [],

    specs: [
        '../spec-e2e/**/*.spec.js'
    ],

    chromeOnly: false,

    multiCapabilities: [
        {
            'browserName': 'chrome'
        },
        {
            'browserName': 'firefox'
        },
        {
            'browserName': 'internet explorer'
        }
    ],

    suites: {
        testsuite: '../spec-e2e/roles.spec.js'
    },

    baseUrl: 'http://google.ca',
    allScriptsTimeout: 10000,

    jasmineNodeOpts: {
        onComplete: null,
        isVerbose: false,
        showColors: true,
        includeStackTrace: true
    }
};
```
The only spec (the roles spec specified above) is simply:
```javascript
describe('Settings-Administration-Roles', function() {
    it('is dependent on the Users page for user/membership addition', function() {
        expect(1).toBeGreaterThan(0);
    });
});
```
Now, this _doesn't_ happen every time that Protractor is run: only about every 3-10 times or so. Thus, I built a script for reproducing this:
```batch
@echo off
set /a index=0
setlocal ENABLEDELAYEDEXPANSION
:start
	set /a index=index+1
	call node_modules\.bin\protractor config\spec-e2e.js --suite testsuite >> StrangeErrorTest%index%.txt
goto start
```

One of the failed logs looks like:
```
[launcher] Running 3 instances of WebDriver

------------------------------------
[chrome #1] PID: 8580
[0m
[chrome #1] Specs: C:\Users\mhentges\Documents\Navistream\webclient\spec-e2e\roles.spec.js
[0m
[chrome #1] 
[0m
[chrome #1] Starting selenium standalone server...[0m
[chrome #1] Selenium standalone server started at http://10.1.1.111:50285/wd/hub[0m
[chrome #1] 
[0m
[chrome #1] C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1643
[0m
[chrome #1]       throw error;
[0m
[chrome #1]             ^
[0m
[chrome #1] Error: Server has not been started.
[0m
[chrome #1]     at Error (<anonymous>)
[0m
[chrome #1]     at SeleniumServer.DriverService.address (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\remote\index.js:138:9)
[0m
[chrome #1]     at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\lib\driverProviders\local.js:80:18
[0m
[chrome #1]     at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1243:15
[0m
[chrome #1]     at webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1539:20)
[0m
[chrome #1]     at notify (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:362:12)
[0m
[chrome #1]     at notifyAll (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:331:7)
[0m
[chrome #1]     at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1243:15
[0m
[chrome #1]     at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1243:15
[0m
[chrome #1]     at webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1539:20)
[0m
[chrome #1]     at notify (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:362:12)
[0m
[chrome #1]     at notifyAll (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:331:7)
[0m
[chrome #1]     at resolve (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:309:7)
[0m
[chrome #1]     at fulfill (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:429:5)
[0m
[chrome #1]     at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1243:15
[0m
[chrome #1]     at webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1539:20)
[0m
[chrome #1]     at notify (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:362:12)
[0m
[chrome #1]     at notifyAll (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:331:7)
[0m
[chrome #1]     at resolve (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:309:7)
[0m
[chrome #1]     at fulfill (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:429:5)
[0m
[chrome #1]     at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1243:15
[0m
[chrome #1]     at webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1539:20)
[0m
[chrome #1]     at notify (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:362:12)
[0m
[chrome #1]     at notifyAll (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:331:7)
[0m
[chrome #1]     at resolve (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:309:7)
[0m
[chrome #1]     at fulfill (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:429:5)
[0m
[chrome #1]     at Object.webdriver.promise.asap (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:671:5)
[0m
[chrome #1]     at webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1550:25)
[0m
[chrome #1]     at notify (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:362:12)
[0m
[chrome #1]     at notifyAll (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:331:7)
[0m
[chrome #1]     at resolve (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:309:7)
[0m
[chrome #1]     at fulfill (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:429:5)
[0m
[chrome #1]     at onResponse (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\http\util.js:83:28)
[0m
[chrome #1]     at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\http\util.js:48:5
[0m
[chrome #1]     at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\http\http.js:96:5
[0m
[chrome #1]     at IncomingMessage.<anonymous> (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:122:7)
[0m
[chrome #1]     at IncomingMessage.EventEmitter.emit (events.js:117:20)
[0m
[chrome #1]     at _stream_readable.js:920:16
[0m
[chrome #1]     at process._tickCallback (node.js:415:13)
[0m

[launcher] Runner Process Exited With Error Code: 8
[launcher] 3 instance(s) of WebDriver still running
.
------------------------------------
[internet explorer #3] PID: 6448
[0m
[internet explorer #3] Specs: C:\Users\mhentges\Documents\Navistream\webclient\spec-e2e\roles.spec.js
[0m
[internet explorer #3] 
[0m
[internet explorer #3] Starting selenium standalone server...[0m
[internet explorer #3] Selenium standalone server started at http://10.1.1.111:57601/wd/hub[0m
[internet explorer #3] [32m.[0m
.
------------------------------------
[firefox #2] PID: 5788
[0m
[firefox #2] Specs: C:\Users\mhentges\Documents\Navistream\webclient\spec-e2e\roles.spec.js
[0m
[firefox #2] 
[0m
[firefox #2] Starting selenium standalone server...[0m
[firefox #2] Selenium standalone server started at http://10.1.1.111:50285/wd/hub[0m
[firefox #2] [32m.[0m

------------------------------------
[0m
[firefox #2] [0m
[firefox #2] Finished in 0.03 seconds[0m
[firefox #2] [32m1 test, 1 assertion, 0 failures[0m
[firefox #2] [0m[0m
[firefox #2] Shutting down selenium standalone server.[0m

[launcher] 1 instance(s) of WebDriver still running

------------------------------------
[0m
[internet explorer #3] [0m
[internet explorer #3] Finished in 0.03 seconds[0m
[internet explorer #3] [32m1 test, 1 assertion, 0 failures[0m
[internet explorer #3] [0m[0m
[internet explorer #3] Shutting down selenium standalone server.[0m

[launcher] 1 instance(s) of WebDriver still running
[launcher] chrome #1 passed
[launcher] firefox #2 passed
[launcher] internet explorer #3 passed
```

**Comment by hankduan** [comment]
Can you clarify if you are still seeing this behavior? I cannot reproduce it no matter how many runs I try.

**Comment by mitchhentges** [comment]
Sweet, yeah, I ran my configuration 100 times, but I cannot reproduce it. Good accidental fix, I guess ;)
