### ISSUE TITLE
Protractor 1.1.0: IE fails with "Unable to get browser" error on start

### ISSUE THREAD

**Issue by mitchhentges** [angular/protractor#1223]
After updating to Protractor 1.1.0, IE will no longer start.
The config file that I am using is:

``` javascript
exports.config = {

    seleniumPort: 4444,
    seleniumArgs: [],

    specs: [
        '../spec-e2e/**/*.spec.js'
    ],

    chromeOnly: false,
    multiCapabilities: [
        /*{
            'browserName': 'chrome'
        },
        {
            'browserName': 'firefox'
        },*/
        {
            'browserName': 'internet explorer'
        }
    ],

    suites: {
        testing:        '../spec-e2e/roles.spec.js'
    },

    baseUrl: 'http://localhost:8000',

    onPrepare: function() {
        browser.get("/#/login");
    },

    allScriptsTimeout: 500000,
    jasmineNodeOpts: {
        onComplete: null,
        isVerbose: true,
        showColors: true,
        includeStackTrace: true,
        defaultTimeoutInterval: 1000000
    }
};
```

Running protractor with IE as a browser causes the following output:

```
Starting selenium standalone server...
Selenium standalone server started at http://10.1.1.111:4444/wd/hub

C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:109
  var template = new Error(this.message);
                 ^
NoSuchWindowError: Unable to get browser (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:03'
System info: host: 'ARROW005175', ip: '10.1.1.111', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_65'
Session ID: f0413653-cb02-4961-a56d-332bcafed444
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=11, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, handlesAlerts=true, initialBrowserUrl=http://localhost:27189/, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
    at new bot.Error (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:109:18)
    at Object.bot.response.checkResponse (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\response.js:106:9)
    at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:277:20
    at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1243:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1539:20)
    at notify (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:362:12)
    at notifyAll (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:331:7)
    at resolve (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:309:7)
    at fulfill (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:429:5)
    at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1406:10
    at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1243:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1539:20)
    at notify (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:362:12)
    at notifyAll (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:331:7)
    at resolve (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:309:7)
    at fulfill (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:429:5)
    at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1243:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1539:20)
    at notify (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:362:12)
    at notifyAll (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:331:7)
    at resolve (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:309:7)
    at fulfill (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:429:5)
    at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:617:49
    at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\http\http.js:96:5
    at IncomingMessage.<anonymous> (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:122:7)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
==== async task ====
WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:268:15)
    at webdriver.WebDriver.executeScript (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:404:15)
    at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\lib\protractor.js:1034:24
    at webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1539:20)
    at pollCondition [as _onTimeout] (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1305:12)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
==== async task ====
Timed out waiting for page to load after 10000ms
    at webdriver.promise.ControlFlow.wait (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1296:15)
    at webdriver.WebDriver.wait (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:543:21)
    at Protractor.get (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\lib\protractor.js:1033:15)
    at get (C:\Users\mhentges\Documents\Navistream\webclient\spec-e2e\app\app\LoginPage.po.js:7:17)
    at exports.config.onPrepare (C:\Users\mhentges\Documents\Navistream\webclient\config\spec-e2e.js:97:14)
    at Runner.runFilenamesOrFns_ (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\lib\runner.js:68:20)
    at Runner.runTestPreparers (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\lib\runner.js:101:15)
    at Object.exports.run (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\lib\frameworks\jasmine.js:38:10)
    at driverprovider_.setupEnv.then.then.then.testResult (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\lib\runner.js:266:28)
    at _fulfilled (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\q\q.js:797:54)
    at self.promiseDispatch.done (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\q\q.js:826:30)
    at Promise.promise.promiseDispatch (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\q\q.js:759:13)
    at C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\q\q.js:573:44
    at flush (C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\node_modules\q\q.js:108:17)
    at process._tickCallback (node.js:415:13)
```

The webdriver executable also provides a whole lot of information:

```
seleniumProcess.pid: 4768
Aug 22, 2014 8:22:55 AM org.openqa.grid.selenium.GridLauncher main
INFO: Launching a standalone server
Setting system property webdriver.chrome.driver to C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\selenium\chromedriver.exe
Setting system property webdriver.ie.driver to C:\Users\mhentges\Documents\Navistream\webclient\node_modules\protractor\selenium\IEDriverServer.exe
08:22:55.255 INFO - Java: Oracle Corporation 24.65-b04
08:22:55.255 INFO - OS: Windows 7 6.1 amd64
08:22:55.265 INFO - v2.42.2, with Core v2.42.2. Built from revision 6a6995d
08:22:55.355 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
08:22:55.355 INFO - Version Jetty/5.1.x
08:22:55.355 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
08:22:55.355 INFO - Started HttpContext[/selenium-server,/selenium-server]
08:22:55.355 INFO - Started HttpContext[/,/]
08:22:55.425 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@7516a69b
08:22:55.425 INFO - Started HttpContext[/wd,/wd]
08:22:55.425 INFO - Started SocketListener on 0.0.0.0:4444
08:22:55.425 INFO - Started org.openqa.jetty.jetty.Server@2db45934
08:22:58.786 INFO - Executing: [new session: Capabilities [{count=1, browserName=internet explorer}]])
08:22:58.796 INFO - Creating a new session for Capabilities [{count=1, browserName=internet explorer}]
Started InternetExplorerDriver server (64-bit)
2.42.0.0
Listening on port 6076
08:23:01.716 INFO - Done: [new session: Capabilities [{count=1, browserName=internet explorer}]]
08:23:01.726 INFO - Executing: [set script timeoutt: 500000])
08:23:01.736 INFO - Done: [set script timeoutt: 500000]
08:23:01.746 INFO - Executing: [maximise window])
08:23:01.756 INFO - Done: [maximise window]
08:23:01.776 INFO - Executing: [get: data:text/html,<html></html>])
08:23:01.816 INFO - Done: [get: data:text/html,<html></html>]
08:23:01.836 INFO - Executing: [execute script: window.name = "NG_DEFER_BOOTSTRAP!" + window.name;window.location.replace("http://localhost:8000/#/login");, []])
08:23:01.886 INFO - Done: [execute script: window.name = "NG_DEFER_BOOTSTRAP!" + window.name;window.location.replace("http://localhost:8000/#/login");, []]
08:23:01.916 INFO - Executing: [execute script: return window.location.href;, []])
08:23:02.316 WARN - Exception thrown
org.openqa.selenium.NoSuchWindowException: Unable to get browser (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10 milliseconds
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:03'
System info: host: 'ARROW005175', ip: '10.1.1.111', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_65'
Session ID: ce626086-1871-442c-a39e-2424fafeeada
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=11, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, handlesAlerts=true, initialBrowserUrl=http://localhost:6076/, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:508)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
    at com.sun.proxy.$Proxy3.executeScript(Unknown Source)
    at org.openqa.selenium.support.events.EventFiringWebDriver.executeScript(EventFiringWebDriver.java:213)
    at org.openqa.selenium.remote.server.handler.ExecuteScript.call(ExecuteScript.java:55)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:169)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
08:23:02.316 WARN - Exception: Unable to get browser (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10 milliseconds
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:03'
System info: host: 'ARROW005175', ip: '10.1.1.111', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_65'
Session ID: ce626086-1871-442c-a39e-2424fafeeada
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=11, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, handlesAlerts=true, initialBrowserUrl=http://localhost:6076/, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
Attempting to shut down selenium nicely
08:23:05.436 INFO - Checking Resource aliases
08:23:05.446 INFO - Command request: shutDownSeleniumServer[, ] on session null
08:23:05.446 INFO - Shutdown command received
08:23:05.446 INFO - initiating shutdown
08:23:05.446 INFO - Got result: OK on session null
Selenium Standalone has exited with code 0
```

**Comment by RickChihu** [comment]
"On IE 7 or higher on Windows Vista or Windows 7, you must set the Protected Mode settings for each zone to be the same value. The value can be on or off, as long as it is the same for every zone. To set the Protected Mode settings, choose "Internet Options..." from the Tools menu, and click on the Security tab. For each zone, there will be a check box at the bottom of the tab labeled "Enable Protected Mode"." Uncheck all boxes
https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver
