### ISSUE TITLE
Is there a way to specify a proxy server in the Config?

### ISSUE THREAD

**Issue by sheldonhall** [angular/protractor#124]

**Comment by jonniespratley** [comment]
This needs to be re-opened, here at GE Software, setting the http_proxy and https_proxy in the configuration still does not allow Protractor to send Saucelabs the final exit code of the test results, making Saucelabs fail the test due to inactivity.

**Comment by hankduan** [comment]
@jonniespratley does `protractor config --proxy=http://user:password@proxy_url:port` not work for you?

**Comment by chitwant82** [comment]
If I use Sauce labs sauce-connect script, before running scripts I am able to run localhost url on Sauce lab machine

Successful case Logs:

23:48:48.669 INFO - Launching a standalone server
Setting system property webdriver.firefox.logfile to c:\log\firefox.log
Setting system property webdriver.server.session.timeout to 0
Setting system property http.proxyHost to maki79213.miso
Setting system property http.proxyPort to 33128
Setting system property http.nonProxyHosts to "localhost|127.0.0.1"
Setting system property https.proxyHost to maki79213.miso
Setting system property https.proxyPort to 33128
Setting system property https.nonProxyHosts to "localhost|127.0.0.1"
23:48:48.887 INFO - Java: Oracle Corporation 25.65-b01
23:48:48.887 INFO - OS: Windows Server 2008 R2 6.1 x86
23:48:48.908 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
23:48:49.153 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4443/wd/hub
23:48:49.155 INFO - Version Jetty/5.1.x
23:48:49.158 INFO - Started HttpContext[/selenium-server,/selenium-server]
23:48:49.254 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@c6a292
23:48:49.254 INFO - Started HttpContext[/wd,/wd]
23:48:49.254 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
23:48:49.254 INFO - Started HttpContext[/,/]
23:48:49.260 INFO - Started SocketListener on 0.0.0.0:4443
23:48:49.260 INFO - Started org.openqa.jetty.jetty.Server@11bc7ed
23:48:49.791 INFO - Executing: [new session: Capabilities [{proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/pac.js, proxyType=PAC}, count=1, webdriver.remote.quietExceptions=true, browserName=firefox}]])
23:48:49.828 INFO - Creating a new session for Capabilities [{proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/pac.js, proxyType=PAC}, count=1, webdriver.remote.quietExceptions=true, browserName=firefox}]
23:48:53.236 INFO - Done: [new session: Capabilities [{proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/pac.js, proxyType=PAC}, count=1, webdriver.remote.quietExceptions=true, browserName=firefox}]]

However, I use 'grunt-sauce-connect-launcher' which successfully launches a tunnel, but localhost url does not get accessible on Sauce lab machine

Failure case logs:

3:41:30.415 INFO - Launching a standalone server
Setting system property webdriver.firefox.logfile to c:\log\firefox.log
Setting system property webdriver.server.session.timeout to 0
23:41:30.556 INFO - Java: Oracle Corporation 25.65-b01
23:41:30.556 INFO - OS: Windows Server 2008 R2 6.1 x86
23:41:30.578 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
23:41:30.918 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4443/wd/hub
23:41:30.920 INFO - Version Jetty/5.1.x
23:41:30.923 INFO - Started HttpContext[/selenium-server,/selenium-server]
23:41:31.027 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@c6a292
23:41:31.027 INFO - Started HttpContext[/wd,/wd]
23:41:31.027 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
23:41:31.027 INFO - Started HttpContext[/,/]
23:41:31.034 INFO - Started SocketListener on 0.0.0.0:4443
23:41:31.034 INFO - Started org.openqa.jetty.jetty.Server@11bc7ed
23:41:31.648 INFO - Executing: [new session: Capabilities [{proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/pac.js, proxyType=PAC}, count=1, webdriver.remote.quietExceptions=true, browserName=firefox}]])
23:41:31.685 INFO - Creating a new session for Capabilities [{proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/pac.js, proxyType=PAC}, count=1, webdriver.remote.quietExceptions=true, browserName=firefox}]
23:41:35.067 INFO - Done: [new session: Capabilities [{proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/pac.js, proxyType=PAC}, count=1, webdriver.remote.quietExceptions=true, browserName=firefox}]]

Haven't been able to successfully configure proxy from protractor conf or 'grunt-sauce-connect-launcher' config

capabilities: {
        //username: process.env.SAUCE_USERNAME,
        //accessKey: process.env.SAUCE_ACCESS_KEY,
        proxy: {
          proxyType: 'manual',
          httpProxy: 'http://*.miso:33128',
          httpsProxy: 'http://*.miso:33128'
          //proxyAutoconfigUrl: 'http://127.0.0.1:19876/pac.js',
          //proxyType: 'PAC'
        },
        browserName: 'firefox',
        version: '37.0',
        platform: 'Windows 7',
    },

**Comment by bitecoder** [comment]
I tried running protractor test on sauce lab but it getting ETIMEDOUT error. I am behind corporate firewall and I have configured proxy in protractor config file and environment variable. Configuration doesn't seems to work. Below is the error I am getting

Error: ETIMEDOUT connect ETIMEDOUT 151.444.33.22:80
    at ClientRequest.<anonymous> (/Users/user123/Desktop/Sample/example-sandbox/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:174:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/Users/user123/Desktop/Sample/example-sandbox/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/Users/user123/Desktop/Sample/example-sandbox/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at [object Object].Builder.build (/Users/user123/Desktop/Sample/example-sandbox/node_modules/protractor/node_modules/selenium-webdriver/builder.js:445:22)
    at [object Object].DriverProvider.getNewDriver (/Users/user123/Desktop/Sample/example-sandbox/node_modules/protractor/lib/driverProviders/driverProvider.js:42:27)
    at [object Object].Runner.createBrowser (/Users/user123/Desktop/Sample/example-sandbox/node_modules/protractor/lib/runner.js:190:37)
    at /Users/user123/Desktop/Sample/example-sandbox/node_modules/protractor/lib/runner.js:280:21
    at _fulfilled (/Users/user123/Desktop/Sample/example-sandbox/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/user123/Desktop/Sample/example-sandbox/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/user123/Desktop/Sample/example-sandbox/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/user123/Desktop/Sample/example-sandbox/node_modules/protractor/node_modules/q/q.js:556:49
[launcher] Process exited with error code 1

**Comment by doomsbuster** [comment]
I am receiving similar errors. I am behind a corporate proxy and am not able to submit a test to browserstack.
```
/Users/Documents/coding/sublime/simpleboilerplate/node_modules/selenium-webdriver/lib/promise.js:654
    throw error;
    ^

Error: ETIMEDOUT connect ETIMEDOUT 208.52.180.201:80
    at ClientRequest.<anonymous> (/Users/Documents/coding/sublime/simpleboilerplate/node_modules/selenium-webdriver/http/index.js:381:15)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/Documents/coding/sublime/simpleboilerplate/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Builder.build (/Users/Documents/coding/sublime/simpleboilerplate/node_modules/selenium-webdriver/builder.js:458:24)
    at Object.<anonymous> (/Users/Documents/coding/sublime/simpleboilerplate/bs.js:13:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
From: Task: WebDriver.navigate().to(http://www.google.com)
    at WebDriver.schedule (/Users/Documents/coding/sublime/simpleboilerplate/node_modules/selenium-webdriver/lib/webdriver.js:377:17)
    at Navigation.to (/Users/Documents/coding/sublime/simpleboilerplate/node_modules/selenium-webdriver/lib/webdriver.js:1027:25)
    at WebDriver.get (/Users/Documents/coding/sublime/simpleboilerplate/node_modules/selenium-webdriver/lib/webdriver.js:795:28)
    at Object.<anonymous> (/Users/Documents/coding/sublime/simpleboilerplate/bs.js:15:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
```

**Comment by gregjacobs** [comment]
What finally worked for us to get out of our corporate proxy and over to perfecto mobile's selenium server was using the `webDriverProxy` config:

```js
exports.config = {
	framework: 'jasmine',
	seleniumAddress: 'https://yourCloudName.perfectomobile.com/nexperience/perfectomobile/wd/hub',
	
	webDriverProxy: 'http://your.proxy.here:8080',
	
	capabilities: { ... },
	specs: ['myspec.js']
};
```

**Comment by s-adachi2016** [comment]
I added your code for proxy setting and modify following:

```
var Http = require('http');
 
var req = Http.request({
    host: 'proxy host name',
    // proxy IP
    port: 8080,
    // proxy port
    method: 'GET',
    path: 'http://devexpress.github.io/testcafe/' // full URL as path
}, function (res) {
    res.on('data', function (data) {
        console.log(data.toString());
    });
});
 
req.end();
```
Program successed.

**Comment by kiran3675** [comment]
I am working behind the corporate proxy tried adding this code in conf.js
'proxy': {
  'proxyType': 'manual',
  'httpProxy': 'user:password@proxy.blah.co.uk:8080'
  'sslProxy': 'user:password@proxy.blah.co.uk:8080'
} 


it was working fine but the application execution time has increased which results failing, Yes I can increase the default time but I dont want my application to take longer time to run.
Can anyone help me to fix this.

Thanks in advance.

**Comment by jlin412** [comment]
@gregjacobs I am using webDriverProxy with perfecto as well.  It was working for me for awhile back.   After upgrading to 4.x or 5.x, I couldn't get it to work anymore.  Does it still work for you after upgrade?

**Comment by deli6z** [comment]
None of the proxy options from https://github.com/angular/protractor/blob/master/lib/config.ts work for me. Anybody had luck configuring proxy in v5 ?

**Comment by Xotabu4** [comment]
@deli6z 
Established BrowserMob proxy and protractor with these capabilities - works fine
```json
  capabilities: {
    'browserName': 'chrome',
    'args': ['disable-web-security'],
    'proxy': {
      'proxyType': 'manual',
      'httpProxy': '10.179.70.127:10801',
      'sslProxy': '10.179.70.127:10801',
      "autodetect": 'false'

    }
}
```

**Comment by luker2** [comment]
@gregjacobs I need to specify a username/password for our proxy used on the `webDriverProxy` property. Do you know how?

**Comment by gregjacobs** [comment]
@luker2 Unfortunately I'm not exactly sure, but does `webDriverProxy: 'http://username:password@your.proxy.here:8080'` not work? (where `8080` is your proxy's port?)

**Comment by luker2** [comment]
@gregjacobs yes, I hadn't followed up yet but that's what ended up working!

For others, I also had to url encode the username:password part to escape special characters...

```
webDriverProxy: `http://${encodeURIComponent(username)}:${encodeURIComponent(password)}@your.proxy.here:8080`
```

**Comment by gregjacobs** [comment]
@luker2 Awesome, glad to hear you got it working! And thanks for posting that piece about uri encoding the username and password - good catch!
