### ISSUE TITLE
configuration is not working 

### ISSUE THREAD

**Issue by calystoramesh** [angular/protractor#14]
I am new to angular JS testing , I  followed you instruction for setup the protractor with sample.  While on execute the testcases I getting a error  

C:\Documents and Settings\sweet\Application Data\npm\node_modules\protractor\bin>protractor e:\protractor_workspace\protractor-master\example\protractorConf.js
Using the selenium server at http://localhost:4444/wd/hub
FF

Failures:

  1) angularjs homepage should greet using binding
   Message:
     TypeError: Cannot call method 'get' of undefined
   Stacktrace:

I changed  browser name and path only in "protractorConf.js".

  capabilities: {
    'browserName': 'firefox'
  },

  // Options to be passed to Jasmine-node.
  jasmineNodeOpts: {
    // Spec folders are relative to the current working directly when
    // protractor is called. This can be folders or files.
    specFolders: ['e:/protractor_workspace/protractor-master/example/onProtractor.js'],
    isVerbose: false,
    showColors: true,
    includeStackTrace: true
  }
};

let me know I made any mistake ?

**Comment by calvinKG** [comment]
HI, 

Am experiencing the same problem. 

var template = new Error(this.message);
                 ^
UnknownError: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
    at new bot.Error (c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:108:18)
    at Object.bot.response.checkResponse (c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\response.js:109:9)
    at c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:160:24
    at [object Object].promise.Promise.goog.defineClass.invokeCallback_ (c:/Users/qxl5048/AppData/Roaming/npm/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (c:/Users/qxl5048/AppData/Roaming/npm/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (c:/Users/qxl5048/AppData/Roaming/npm/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15)
    at process._tickCallback (node.js:401:9)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:131:30)
    at [object Object].Builder.build (c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\builder.js:445:22)
    at [object Object].DriverProvider.getNewDriver (c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\lib\driverProviders\driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\lib\runner.js:186:37)
    at c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\lib\runner.js:276:21
    at _fulfilled (c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:797:54)
    at self.promiseDispatch.done (c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:826:30)
    at Promise.promise.promiseDispatch (c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:759:13)
    at c:\Users\qxl5048\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:525:49
[launcher] Process exited with error code 1
