### ISSUE TITLE
Sauce Labs:  ECONNREFUSED with corporate proxy

### ISSUE THREAD

**Issue by clintonbuie** [angular/protractor#1426]
Hi,

I've attempted to run Protractor with my sauce credentials, but unfortunately, I'm not able to connect through my corporate proxy.

conf.js:

exports.config = {
  //seleniumAddress: 'https://gego:ff82602e-4e98-4386-99b1-bb46ac7130d5@ondemand.saucelabs.com:80/wd/hub',
  sauceUser: process.env.SAUCE_USERNAME,
  sauceKey: process.env.SAUCE_ACCESS_KEY,
  specs: ['spec.js'],
    capabilities: {
      'browserName': 'chrome',
      'proxy': {  
             'proxyType': 'manual',
             'httpProxy': 'http://proxy-src.research.ge.com:8080',
       }
    }
}

Error message:

Using SauceLabs selenium server at http://ondemand.saucelabs.com:80/wd/hub

/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:136
      callback(new Error(message));
               ^
Error: ECONNREFUSED connect ECONNREFUSED
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:136:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:49)
    at Function.webdriver.WebDriver.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:111:30)
    at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:106:20)
    at SauceDriverProvider.getDriver (/usr/local/lib/node_modules/protractor/lib/driverProviders/sauce.js:102:53)
    at /usr/local/lib/node_modules/protractor/lib/runner.js:241:41
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:759:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:573:44

Any ideas on what could be causing this error?

**Comment by bitecoder** [comment]
Proxy still doesn't seems to work.
