### ISSUE TITLE
Can't find element with protractor API after login

### ISSUE THREAD

**Issue by ffesseler** [angular/protractor#143]
I'm getting a weird behaviour when trying to locate an element after a login.

I can see on my browser that the login is successfull and that the app display the homepage. However, when I'm trying to access an element on that page, the test fails.
The thing is, if I use the Webdriver API instead of protractor, the element is found.

```
it('should redirect to home page when logged', function() {
      var username = ptor.findElement(protractor.By.input('user.name'));
      username.clear();
      username.sendKeys('admin');

      var password = ptor.findElement(protractor.By.input('user.password'));
      password.clear();
      password.sendKeys('admin');

      var submitButton = ptor.findElement(protractor.By.css('.loginbutton'));
      submitButton.click();


//      ptor.driver.findElement(protractor.By.css('.logout-button')).click();//works
      ptor.findElement(protractor.By.css('.logout-button')).click();//doesnt work

    });
```

**Comment by kotvertolet** [comment]
I have a similar issue, there is an element that can be found by css and xpath locators in chrome:
http://prntscr.com/ck5t70
http://prntscr.com/ck5tqb
but it doesn't work with protractor:
```
this.ui.contactsList = $(by.xpath("//div[@class='list-group ng-scope']"));
this.ui.contactsList = $("div.list-group");
```
Output:

> NoSuchElementError: No element found using locator: By(xpath, //div[@class='list-group ng-scope'])
> NoSuchElementError: No element found using locator: By(css selector, div.list-group)

**Comment by suneelyadava** [comment]
Hi there,

I am facing same issue after logging into the application, the element is not identified.

[11:53:47] W/driverProviders - Using driver provider directConnect, but also found extra driver provider parameter(s): seleniumAddress
[11:53:47] I/launcher - Running 1 instances of WebDriver
[11:53:47] I/direct - Using ChromeDriver directly...
Hello
Started
F

Failures:
1) it should pass it should validate
  Message:
    Failed: script timeout: result was not received in 11 seconds
      (Session info: chrome=74.0.3729.169)
      (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Mac OS X 10.14.3 x86_64)
  Stack:
    ScriptTimeoutError: script timeout: result was not received in 11 seconds
      (Session info: chrome=74.0.3729.169)
      (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Mac OS X 10.14.3 x86_64)
        at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
        at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30
        at processTicksAndRejections (internal/process/task_queues.js:89:5)
    From: Task: Protractor.waitForAngular() - Locator: By(css selector, .\.kuiSize)
        at Driver.schedule (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
        at ProtractorBrowser.executeAsyncScript_ (/usr/local/lib/node_modules/protractor/built/browser.js:425:28)
        at /usr/local/lib/node_modules/protractor/built/browser.js:456:33
        at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1376:14)
        at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2927:27
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
        at processTicksAndRejections (internal/process/task_queues.js:89:5)Error
        at ElementArrayFinder.applyAction_ (/usr/local/lib/node_modules/protractor/built/element.js:459:27)
        at ElementArrayFinder.<computed> [as isDisplayed] (/usr/local/lib/node_modules/protractor/built/element.js:91:29)
        at ElementFinder.<computed> [as isDisplayed] (/usr/local/lib/node_modules/protractor/built/element.js:831:22)
        at UserContext.<anonymous> (/usr/local/lib/ProDemo/test.js:18:69)
        at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1077:7)
        at ControlFlow.promise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2505:12)
        at schedulerExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    From: Task: Run it("it should validate") in control flow
        at UserContext.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/usr/local/lib/ProDemo/test.js:6:5)
        at Object.<anonymous> (/usr/local/lib/ProDemo/test.js:5:1)
        at Module._compile (internal/modules/cjs/loader.js:774:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
        at Module.load (internal/modules/cjs/loader.js:641:32)
        at Function.Module._load (internal/modules/cjs/loader.js:556:12)

1 spec, 1 failure
Finished in 18.421 seconds

[11:54:07] I/launcher - 0 instance(s) of WebDriver still running
[11:54:07] I/launcher - chrome #01 failed 1 test(s)
[11:54:07] I/launcher - overall: 1 failed spec(s)
[11:54:07] E/launcher - Process exited with error code 1
npm ERR! Test failed.  See above for more details.
suneels-MacBook-Pro:ProDemo suneelyadava$

**Comment by suneelyadava** [comment]
"use strict";
exports.__esModule = true;
var protractor_1 = require("protractor");
console.log("Hello");
describe("it should pass", function () {
    it("it should validate", function () {
        protractor_1.browser.get('https://35.160.167.233:32666/logon');
        protractor_1.browser.manage().window().maximize();
        protractor_1.element(protractor_1.by.xpath('html/body/hzn-root/hzn-logon/div/hzn-enter-username/section/kui-input-box/form/kui-input/div/input')).sendKeys('admin');
        protractor_1.element(protractor_1.by.name('username')).click();
        protractor_1.element(protractor_1.by.tagName('input')).isElementPresent(protractor_1.by.tagName('name'));
        protractor_1.element(protractor_1.by.tagName('input')).sendKeys('admin');
        protractor_1.element(protractor_1.by.name('password')).click(); //Complete Login
        //browser.refresh();
        //element(by.className('time-zone')).click()
        //element(by.xpath("//kui-icon[@kuiicon='user-profile']")).click();
        protractor_1.element(protractor_1.By.id("Light")).click();
        protractor_1.element(protractor_1.By.className(".kuiSize")).isDisplayed();
        var a = true;
        expect(a).toBe(true);
    });
});

**Comment by suneelyadava** [comment]
Please help if someone has solved this.

**Comment by suneelyadava** [comment]
When I run same stuff with selenium, this works well using java
