### ISSUE TITLE
Timeout Problem Protractor with Selenium running on Ubuntu Linux 14.04 - Firefox 33 34

### ISSUE THREAD

**Issue by dukeatcoding** [angular/protractor#1613]
I have a test which is running fine when the Selenium Server is running on

Selenium 2.43 Windows 7 - Firefox 33 

When I run the same against an 

Selenium 2.43 running on Ubuntu 14.04 - Firefox 33 or Firefox 34, 

i run into a timeout.

Update: Chrome work fine though -  see also the referenced ticket

Test:

     it('Check Title',function(){
		       el = ptor.findElement(by.model('selected.parent.mediaImage.item0.metaData.title'));

		 el.getAttribute('value').then(function(data){
			expect(data).toBe('12800087');
			console.log(data);
	          }); 
		});

Log Message Protractor:
...Wait for Attribute
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
Protractor.waitForAngular()
    at [object Object].webdriver.WebDriver.schedule (/home/pom/Desktop/protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
    at [object Object].Protractor.executeAsyncScript_ (/home/pom/Desktop/protractor/node_modules/protractor/lib/protractor.js:1141:26)
    at [object Object].Protractor.waitForAngular (/home/pom/Desktop/protractor/node_modules/protractor/lib/protractor.js:1159:15)
    at [object Object].getWebElements (/home/pom/Desktop/protractor/node_modules/protractor/lib/protractor.js:191:21)
    at [object Object].getWebElements (/home/pom/Desktop/protractor/node_modules/protractor/lib/protractor.js:705:33)
    at [object Object].ElementArrayFinder.applyAction_ (/home/pom/Desktop/protractor/node_modules/protractor/lib/protractor.js:440:30)
    at [object Object].self.(anonymous function) [as getAttribute] (/home/pom/Desktop/protractor/node_modules/protractor/lib/protractor.js:135:21)
    at [object Object].self.(anonymous function) [as getAttribute] (/home/pom/Desktop/protractor/node_modules/protractor/lib/protractor.js:734:13)
    at [object Object].<anonymous> (/home/pom/Desktop/protractor/register.spec.js:77:7)

Log Message Selenium:

16:50:27.348 INFO - Executing: [execute async script: try { return (function (rootSelector, callback) {
  var el = document.querySelector(rootSelector);
  try {
    if (angular.getTestability) {
      angular.getTestability(el).whenStable(callback);
    } else {
      angular.element(el).injector().get('$browser').
          notifyWhenNoOutstandingRequests(callback);
    }
  } catch (e) {
    callback(e);
  }
}).apply(this, arguments); }
catch(e) { throw (e instanceof Error) ? e : new Error(e); }, [body]])

**Comment by TimeInvestor** [comment]
I am having same issue here.
Ubuntu: 14.04
protractor: 1.6.1
Firefox: 35

**Comment by dukeatcoding** [comment]
I try to bring in more info, right now i am experiencing even more problems with firefox

**Comment by juliemr** [comment]
Note that firefox 35 has a known issue, which the Selenium project has fixed but not yet released: https://github.com/angular/protractor/issues/1734

**Comment by dukeatcoding** [comment]
@juliemr thx julie also found the other issue a couple minutes ago ^^

**Comment by c0debreaker** [comment]
Hi folks,

I'm getting a timeout issue too. Here is the output while protractor was running. It contains the issues.
https://gist.github.com/c0debreaker/980b3e3636487894337c

My firefox version is 35.0.1. So here is what happens. When I execute protractor conf.js, it will fire up firefox and the location bar gets populated with the url we have on our spec.js file. Unfortunately, it won't display the page though I am not sure if it really requires the page to get loaded. It's just white screen. However, if I click Reload button on my firefox, the site's pages gets rendered quickly.

Here is the screenshot of Firefox failing to load the page when it's instructed by Protractor.
http://i.imgur.com/wkaSZ3W.png

Here is the output of webdriver-manager start
https://gist.github.com/c0debreaker/876fbaf7a0eb68007d63

**Comment by c0debreaker** [comment]
It's working fine now after downgrading my firefox to version 34.x.x

**Comment by dukeatcoding** [comment]
@c0debreaker note that my bug is also present in FF 33 and 34

Your problem is related to https://github.com/angular/protractor/issues/1734

**Comment by juliemr** [comment]
Can you confirm that this issue still exists when you increase the timeout?

**Comment by juliemr** [comment]
Closing this issue, since I haven't heard any updates that aren't about the #1734 issue which is now closed.
