### ISSUE TITLE
ElementFinder.prototype.isElementPresent kills my tests

### ISSUE THREAD

**Issue by mitchhentges** [angular/protractor#1658]
When I use the `isElementPresent()` function, Protractor surprises everyone with:
```
Failures:

  1) protractor should do things
   Message:
     [31mTypeError: Cannot read property 'findElementsOverride' of undefined[0m
   Stacktrace:
     TypeError: Cannot read property 'findElementsOverride' of undefined
    at C:\dev\ProtractorTest\node_modules\protractor\lib\protractor.js:195:42
    at Array.forEach (native)
    at C:\dev\ProtractorTest\node_modules\protractor\lib\protractor.js:194:29
    at C:\dev\ProtractorTest\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (C:\dev\ProtractorTest\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1654:20)
    at notify (C:\dev\ProtractorTest\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:465:12)
    at notifyAll (C:\dev\ProtractorTest\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:442:7)
    at resolve (C:\dev\ProtractorTest\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:420:7)
    at fulfill (C:\dev\ProtractorTest\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:535:5)
    at Object.webdriver.promise.asap (C:\dev\ProtractorTest\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:776:5)
==== async task ====
Asynchronous test function: it()
    at [object Object].<anonymous> (C:\dev\ProtractorTest\node_modules\protractor\node_modules\jasminewd\index.js:93:33)
    at [object Object].<anonymous> (C:\dev\ProtractorTest\node_modules\protractor\node_modules\minijasminenode\lib\async-callback.js:45:37)
    at [object Object].jasmine.Block.execute (C:\dev\ProtractorTest\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:1174:17)
    at [object Object].jasmine.Queue.next_ (C:\dev\ProtractorTest\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2209:31)
    at [object Object]._onTimeout (C:\dev\ProtractorTest\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2199:18)
Error
    at [object Object].<anonymous> (C:\dev\ProtractorTest\bap.spec.js:2:5)
    at [object Object].jasmine.Env.describe_ (C:\dev\ProtractorTest\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:913:21)
    at [object Object].jasmine.Env.describe (C:\dev\ProtractorTest\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:898:15)
    at describe (C:\dev\ProtractorTest\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:658:27)
    at Object.<anonymous> (C:\dev\ProtractorTest\bap.spec.js:1:63)
```
I would prefer "Merry Christmas", but I guess Protractor and I celebrate different holidays.

**To reproduce:**
1. Build a config file:
```
//spec-e2e.js
exports.config = {
    seleniumPort: 4444,
    seleniumArgs: [],
    specs: [
        './*.spec.js'
    ],

    directConnect: true,

    capabilities: {
        'browserName': 'chrome'
    },

    baseUrl: 'https://angularjs.org/',

    allScriptsTimeout: 1000000,

    jasmineNodeOpts: {
        onComplete: null,
        isVerbose: true,
        showColors: true,
        includeStackTrace: true,
        defaultTimeoutInterval: 1000000
    }
};
```

2. Build a spec:

```
//bap.spec.js
describe('protractor', function() {
    it('should do things', function() {
        browser.get('/');
        var body = element(by.tagName('body'));
        expect(body.isElementPresent()).toBeTruthy();
    });
});
```
3. Install protractor: `npm install protractor`
4. If you haven't installed protractor yet, you should do the previous step
5. Do the test: `node node_modules\.bin\protractor spec-e2e.js`
6. Realize that these reproduce steps had three "Step 1"s. Thanks MarkDown.

My tests are doing the exact opposite of this:
![tisbutascratch](https://cloud.githubusercontent.com/assets/7784737/5531588/62947546-89e2-11e4-81c0-87ac82a94e36.jpg)

**Comment by eddiemonge** [comment]
The documentation needs work then because it makes it sound like the difference between the two is that `isElementPresent` waits for angular to finish and `isPresent` doesn't.

**Comment by juliemr** [comment]
Agreed, the docs here are wrong.

**Comment by eddiemonge** [comment]
I was working on fixing the docs but got distracted because there seems to be a few bugs in it and the build/server process can be improved. maybe ill finish that later today and PR it

**Comment by eolognt** [comment]
Well, do `isPresent` wait for angular?

**Comment by hankduan** [comment]
Yes both wait for angular (unless `browser.ignoreSynchronization = true` is set)

See See https://github.com/angular/protractor/pull/2282

**Comment by hankduan** [comment]
closed with https://github.com/angular/protractor/commit/bc318383108687c6e59570ac61372e485d6e865a
