### ISSUE TITLE
mocha/chai-as-promised stack traces with isPresent

### ISSUE THREAD

**Issue by pschuegr** [angular/protractor#1674]
Using mocha and chai-as-promised; I'm seeing a difference in the stack traces between two tests which both use promises, and I'm having trouble understanding why.  If somebody could explain this to me it would be helpful.

Test 1:
````
  it('should show the form', function() {
    $('#tools-dropdown').click()
    .then(function() {
      $('#templates').click()
    })
    .then(function() {
      expect(browser.getTitle()).to.eventually.equal('is');
    });
  });
````

Fails with:

```
==== async task ====
  WebDriver.getTitle()
      at [object Object].webdriver.WebDriver.schedule (/Users/pschuegr/client/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
      at [object Object].webdriver.WebDriver.getTitle (/Users/pschuegr/client/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:745:15)
      at [object Object].to.(anonymous function) [as getTitle] (/Users/pschuegr/client/node_modules/protractor/lib/protractor.js:49:25)
      at /Users/pschuegr/client/e2e/administrator/template_list_test.js:25:22
      at /Users/pschuegr/client/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
      at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Users/pschuegr/client/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
      at notify (/Users/pschuegr/client/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
      at notifyAll (/Users/pschuegr/client/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
      at resolve (/Users/pschuegr/client/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
==== async task ====
      at Context.ret (/Users/pschuegr/client/node_modules/protractor/node_modules/selenium-webdriver/testing/index.js:119:12)
      at Test.Runnable.run (/Users/pschuegr/client/node_modules/protractor/node_modules/mocha/lib/runnable.js:216:15)
[snip]
```

but test 2:
````
  it('should show the form', function() {
    $('#tools-dropdown').click()
    .then(function() {
      $('#templates').click()
    })
    .then(function() {
      expect(browser.isElementPresent(by.css('table#template-list-system'))).to.eventually.be.true;
    });
  });
````

Fails with:
```
==== async task ====
      at Context.ret (/Users/pschuegr/client/node_modules/protractor/node_modules/selenium-webdriver/testing/index.js:119:12)
      at Test.Runnable.run (/Users/pschuegr/client/node_modules/protractor/node_modules/mocha/lib/runnable.js:216:15)
      at Runner.runTest (/Users/pschuegr/client/node_modules/protractor/node_modules/mocha/lib/runner.js:373:10)
      at /Users/pschuegr/client/node_modules/protractor/node_modules/mocha/lib/runner.js:451:12
      at next (/Users/pschuegr/client/node_modules/protractor/node_modules/mocha/lib/runner.js:298:14)
      at /Users/pschuegr/client/node_modules/protractor/node_modules/mocha/lib/runner.js:308:7
      at next (/Users/pschuegr/client/node_modules/protractor/node_modules/mocha/lib/runner.js:246:23)
      at /Users/pschuegr/client/node_modules/protractor/node_modules/mocha/lib/runner.js:270:7
      at done (/Users/pschuegr/client/node_modules/protractor/node_modules/mocha/lib/runnable.js:205:5)
```

Why is it that the first test has a stack which includes the location in my code, and the second one doesn't?  Any ideas or suggestions on things I could change?

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
