### ISSUE TITLE
Retry on "UnknownError: Chrome failed to start: crashed"

### ISSUE THREAD

**Issue by elgalu** [angular/protractor#1738]
I have a linux headless box running Jenkins - Protractor and from time to time, let's say 1 of every 50 runs selenium-webdriver reports Chrome crashed while starting.
It would be nice that the launcher retries launching Chrome to avoid CI false positives.

Stack trace:
```bash
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
ERROR - Unable to start a WebDriver session.

/home/jenkins/e2e/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.11.298611 (d1120fdf51badec2f7b63a96e19a58d4783de84d),platform=Linux 3.13.0-36-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.55 seconds
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'all1', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_65'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at new bot.Error (/home/jenkins/e2e/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/home/jenkins/e2e/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /home/jenkins/e2e/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:152:24
    at /home/jenkins/e2e/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/home/jenkins/e2e/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/home/jenkins/e2e/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/home/jenkins/e2e/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/home/jenkins/e2e/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at fulfill (/home/jenkins/e2e/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /home/jenkins/e2e/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/home/jenkins/e2e/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:149:22)
    at Function.webdriver.WebDriver.createSession (/home/jenkins/e2e/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:123:30)
    at Builder.build (/home/jenkins/e2e/node_modules/selenium-webdriver/builder.js:294:22)
    at DriverProvider.getNewDriver (/home/jenkins/e2e/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at Runner.createBrowser (/home/jenkins/e2e/node_modules/protractor/lib/runner.js:180:37)
    at /home/jenkins/e2e/node_modules/protractor/lib/runner.js:246:21
    at _fulfilled (/home/jenkins/e2e/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/home/jenkins/e2e/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/jenkins/e2e/node_modules/q/q.js:759:13)
[launcher] Process exited with error code 1
```

Protractor version: 1.6.0

**Comment by juliemr** [comment]
Could you open an feature request with [seleinum](https://code.google.com/p/selenium/issues/list) and link to it here?

**Comment by elgalu** [comment]
Sure! https://code.google.com/p/selenium/issues/detail?id=8409

**Comment by AxlRenner** [comment]
Hi, I have the same issue :)

**Comment by elgalu** [comment]
I sent to Selenium webdriver.js [PR #310](https://github.com/SeleniumHQ/selenium/pull/310) to start figuring out a retry based solution that's working on my current setup but needs some work.

**Comment by juliemr** [comment]
I think this is encapsulated by the other requests for ability to retry - let's close this specific one.
