### ISSUE TITLE
[getWebElement] cannot read property 'driver' of undefined

### ISSUE THREAD

**Issue by mitchhentges** [angular/protractor#1758]
I'd like to start by saying that this is _not_ reproducible under all machines.
Anyways, when running `getWebElement()` on an `ElementFinder` provided for a callback, Protractor can sometimes fail with the excuse:
```
TypeError: Cannot read property 'driver' of undefined
       Stacktrace:
         TypeError: Cannot read property 'driver' of undefined
        at /home/mitch/dev/vc/spec-e2e/protractorUtils.js:52:34
        at Array.forEach (native)
    ==== async task ====
    Asynchronous test function: it()
    Error
        at [object Object].<anonymous> (/home/mitch/dev/vc/spec-e2e/app/assets/Assets.spec.js:235:9)
        at [object Object].<anonymous> (/home/mitch/dev/vc/spec-e2e/app/assets/Assets.spec.js:226:5)
        at Object.<anonymous> (/home/mitch/dev/vc/spec-e2e/app/assets/Assets.spec.js:18:1)
        at require (module.js:380:17)
        at Function.promise (/home/mitch/dev/vc/node_modules/protractor/node_modules/q/q.js:650:9)
        at _fulfilled (/home/mitch/dev/vc/node_modules/protractor/node_modules/q/q.js:797:54)
        at self.promiseDispatch.done (/home/mitch/dev/vc/node_modules/protractor/node_modules/q/q.js:826:30)
        at Promise.promise.promiseDispatch (/home/mitch/dev/vc/node_modules/protractor/node_modules/q/q.js:759:13)
        at /home/mitch/dev/vc/node_modules/protractor/node_modules/q/q.js:525:49
        at flush (/home/mitch/dev/vc/node_modules/protractor/node_modules/q/q.js:108:17)
        at process._tickCallback (node.js:442:13)
```

__To reproduce (sometimes):__
1. `node protractor/bin/webdriver-manager start`
2. `node protractor/bin/elementExplorer <angularSiteURL>`
3. Make an `element.all` selection (even if only one element): `var elems = element.all(by.tagName('html'));
4. 
```js
elems.each(function(elem) {
    console.log(elem.getWebElement());
});
```
5. Error will be reported

A couple things to note:
- I was able to reproduce this on ElementaryOS Freya Beta 1 with Chrome 40 64bit and Node 0.10.35
- I was also able to reproduce this on Windows 7 SP1 with Chrome 40 and Node 0.10.36
- __I was not able to reproduce this on a different Windows 7 machine with Chrome 40 and Node 0.10.[35/36]__
- It was reproducible on Protractor `1.6.0`
- If I "get" a single element, immediately doing `getWebElement()`, it works:
```js
elems.get(0).getWebElement(); //works
```
- If I "get" a single element, but wrap it in a `then`, it fails:
```js
elems.get(0).then(function(elem) {
    console.log(elem.getWebElement()); //everybody dies
});
```
- If I call a doctor , nobody answers the phone

**Comment by mitchhentges** [comment]
My temporary solution is to refrain from `getWebElement()` in a `.each` or `.map` (etc) callback.
Doing:
```js
elems.count().then(function(count) {
    for (var i = 0; i < count; i++) {
        elems.get(i).getWebElement();
    }
});
```
is working okay.

**Comment by juliemr** [comment]
I believe this will be obsolete with the changes to webdriver's WebElements in the latest version. Closing, but please open a new issue if you are still having trouble.
