### ISSUE TITLE
Firefox Webdriver times out

### ISSUE THREAD

**Issue by gflarity** [angular/protractor#1782]
Hi, 
Originally I had selenium + firefox + protractor running perfectly.  But I recently reinstalled/upgraded my environment and now chrome still works, but firefox times out even on a just a browser.get('https://www.angularjs.org/'). No amount of reinstalling protractor seems to work, but my colleagues have no problems. 

I'm on a Mac running 10.9.5, i'm using boot2docker and the official selenium containers. Chrome works fine. And firefox used to work as well. 

Any ideas/suggestions? Here's the log

A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was:
Protractor.get(https://www.angularjs.org/) - get url
    at [object Object].webdriver.WebDriver.schedule (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
    at [object Object].Protractor.executeScript_ (/usr/local/lib/node_modules/protractor/lib/protractor.js:223:22)
    at /usr/local/lib/node_modules/protractor/lib/protractor.js:448:17
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:650:12
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at pollCondition (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1419:12)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1415:5
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
    at [object Object].wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

**Comment by gflarity** [comment]
I've gotten this to reproduce with without using docker at all. One thing I notice is that the url gets entered into firefox, but never gets loaded. I hit enter and it loads but that doesn't help the tests.  I think there must be something that isn't removed during uninstall but have no idea how to debug it. Here's my spec and test:

// conf.js
exports.config = {
    specs: ['foo.js'],
    capabilities: {
        browserName: 'chrome'
    }
}

describe('login/logout tests', function() {
    it("should do something", function() {
        browser.get('http://juliemr.github.io/protractor-demo/');
        expect(browser.getTitle()).toEqual('Super Calculator');
    });
});

**Comment by hankduan** [comment]
Are you using firefox 35? See https://github.com/angular/protractor/issues/1734

**Comment by gflarity** [comment]
Thanks! Sounds like this it. Boy wish I found 1734 earlier :)
