### ISSUE TITLE
BeforeEach not executed for following specs if a Jasmine spec timed out.

### ISSUE THREAD

**Issue by bastijns-jeroen** [angular/protractor#1797]
#### Explanation

Currently we are having issues with asynchronous behavour in Protractor tests.

When an asynchronous beforeEach exceeds the default timeout interval, the first test (it-block) fails as expected and an error is thrown:
> A Jasmine spec timed out. Resetting the WebDriver Control Flow.

However the beforeEach isn't executed anymore before the second test is executed and we get the same error as with the first test. It seems to us that this is unwanted behaviour, it should be normal to execute the beforeEach before executing the second test.

The same applies for tests in other subsequent spec-files. The beforeEach isn't executed before executing tests and we get the same error as in the first failing test.

Is this a bug in Jasmine / Protractor?

I've included a code sample below which fails every time.

*Version of Protractor: protractor@1.6.1*
*Version of Jasmine in protractor 2.1*

##### Snippet of our Protractor configuration:
```javascript
{
   framework: 'jasmine2',

   // Options to be passed to Jasmine-node.
   jasmineNodeOpts : {
      showColors: true,
      defaultTimeoutInterval : 3000
   }
```

##### Specs
Spec-files are stored in the same folder (tests).

###### atest_spec.js:
```javascript
describe('atest', function() {
	
	beforeEach(function(done) {
		console.log('atest start beforeEach');
		setTimeout(function () {
			console.log('atest stop beforeEach');
			done();
		}, 2000)
	});
	
	it('atest test one', function() {
		console.log('atest test one started');
		expect('atest').toEqual('test one')
	});

	it('atest test two', function() {
		console.log('atest test two started');
		expect('atest').toEqual('test two')
	});
});
```

###### btest_spec.js:
```javascript
describe('btest', function() {
	
	beforeEach(function(done) {
		console.log('btest start beforeEach');
		setTimeout(function () {
			console.log('btest stop beforeEach');
			done();
		}, 4000)
	});
	
	it('btest test one', function() {
		console.log('btest test one started');
		expect('btest').toEqual('test one')
	});

	it('btest test two', function() {
		console.log('btest test two started');
		expect('btest').toEqual('test one')
	});
});
```

###### ctest_spec.js:
```javascript
describe('ctest', function() {
	
	beforeEach(function(done) {
		console.log('ctest start beforeEach');
		setTimeout(function () {
			console.log('ctest stop beforeEach');
			done();
		}, 2000)
	});
	
	it('ctest test one', function() {
		console.log('ctest test one started');
		expect('ctest').toEqual('test one')
	});

	it('ctest test two', function() {
		console.log('ctest test two started');
		expect('ctest').toEqual('test one')
	});
});
```

##### Console output
```
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
Started
atest start beforeEach
atest stop beforeEach
atest test one started
atest start beforeEach
atest stop beforeEach
atest test two started
btest start beforeEach
btest test one started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
unknown
btest stop beforeEach
btest test two started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
unknown
ctest test one started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
unknown
ctest test two started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
unknown

Failures:
1) atest atest test one
  Message:
[31m    Expected 'atest' to equal 'test one'.[0m
  Stack:
    Error: Failed expectation
        at Env.<anonymous> (tests/atest_spec.js:13:19)
        at node_modules/protractor/node_modules/jasminewd2/index.js:95:14
        at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
        at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
        at [object Object].wrapper [as _onTimeout] (timers.js:252:14)
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

2) atest atest test two
  Message:
[31m    Expected 'atest' to equal 'test two'.[0m
  Stack:
    Error: Failed expectation
        at Env.<anonymous> (tests/atest_spec.js:18:19)
        at node_modules/protractor/node_modules/jasminewd2/index.js:95:14
        at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
        at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
        at [object Object].wrapper [as _onTimeout] (timers.js:252:14)
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

3) btest btest test one
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
  Message:
[31m    Expected 'btest' to equal 'test one'.[0m
  Stack:
    Error: Failed expectation
        at Env.<anonymous> (tests/btest_spec.js:13:19)
        at node_modules/protractor/node_modules/jasminewd2/index.js:95:14
        at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
        at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
        at [object Object].wrapper [as _onTimeout] (timers.js:252:14)
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

4) btest btest test two
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
  Message:
[31m    Expected 'btest' to equal 'test one'.[0m
  Stack:
    Error: Failed expectation
        at Env.<anonymous> (tests/btest_spec.js:18:19)
        at node_modules/protractor/node_modules/jasminewd2/index.js:95:14
        at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
        at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
        at [object Object].wrapper [as _onTimeout] (timers.js:252:14)
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

5) ctest ctest test one
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
  Message:
[31m    Expected 'ctest' to equal 'test one'.[0m
  Stack:
    Error: Failed expectation
        at Env.<anonymous> (tests/ctest_spec.js:13:19)
        at node_modules/protractor/node_modules/jasminewd2/index.js:95:14
        at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
        at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
        at [object Object].wrapper [as _onTimeout] (timers.js:252:14)
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

6) ctest ctest test two
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
  Message:
[31m    Expected 'ctest' to equal 'test one'.[0m
  Stack:
    Error: Failed expectation
        at Env.<anonymous> (tests/ctest_spec.js:18:19)
        at node_modules/protractor/node_modules/jasminewd2/index.js:95:14
        at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
        at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
        at [object Object].wrapper [as _onTimeout] (timers.js:252:14)
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

6 specs, 6 failures
Finished in 17.291 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 6 test(s)
[launcher] overall: 6 failed spec(s)
[launcher] Process exited with error code 1
```

**Comment by hankduan** [comment]
This looks like a jasmine-specific error. Can you check if it's the same behavior if you run it directly with jasmine:

Instructions from their doc:
The releases (https://github.com/pivotal/jasmine/releases) page has links to download the standalone distribution, which contains everything you need to start running Jasmine. After downloading a particular version and unzipping, opening SpecRunner.html will run the included specs. You’ll note that both the source files and their respective specs are linked in the <head> of the SpecRunner.html. To start using Jasmine, replace the source/spec files with your own.

**Comment by bastijns-jeroen** [comment]
I adapted the expectations in the three tests above to always succeed. This improves the readability of the output as we just want to see the timeout failures of the asynchronous beforeEach.

##### Jasmine Standalone
Running the tests in Jasmine 2.1.1 Standalone did gave a correct output. The tests in *btest_spec.js* failed due to timeout of the beforeEach and beforeEach did execute before the second test started. Which wasn't the case in Protractor.

Screenshots of Jasmine 2.1.1 Standalone:

![screen shot 2015-02-11 at 10 26 36](https://cloud.githubusercontent.com/assets/4682089/6144540/f09db050-b1d8-11e4-94d6-a45f91a2bdac.png)

![screen shot 2015-02-11 at 10 27 03](https://cloud.githubusercontent.com/assets/4682089/6144543/fd813242-b1d8-11e4-9048-060816d92e4e.png)

Console log output:

```
atest_spec.js:6 atest start beforeEach
atest_spec.js:8 atest stop beforeEach
atest_spec.js:14 atest test one started
atest_spec.js:6 atest start beforeEach
atest_spec.js:8 atest stop beforeEach
atest_spec.js:19 atest test two started
btest_spec.js:4 btest start beforeEach
btest_spec.js:12 btest test one started
btest_spec.js:4 btest start beforeEach
btest_spec.js:6 btest stop beforeEach
btest_spec.js:17 btest test two started
ctest_spec.js:4 ctest start beforeEach
btest_spec.js:6 btest stop beforeEach
ctest_spec.js:6 ctest stop beforeEach
ctest_spec.js:12 ctest test one started
ctest_spec.js:4 ctest start beforeEach
ctest_spec.js:6 ctest stop beforeEach
ctest_spec.js:17 ctest test two started
```

##### Protractor

The same adapted tests run in Protractor with previous stated configuration gave the following result:

```
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
Started
atest start beforeEach
atest stop beforeEach
atest test one started
atest start beforeEach
atest stop beforeEach
atest test two started
btest start beforeEach
btest test one started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
unknown
btest stop beforeEach
btest test two started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
unknown
ctest test one started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
unknown
ctest test two started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
unknown

Failures:
1) btest btest test one
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

2) btest btest test two
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

3) ctest ctest test one
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

4) ctest ctest test two
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

6 specs, 4 failures
```

**Comment by juliemr** [comment]
What we know:

This is a problem with jasminewd2, not just Protractor.
The problem goes away (but other problems would appear), if we don't reset the control flow when a timeout occurs.

**Comment by biswajitsantra** [comment]
It's Working Fine................

describe('Protractor Demo App', function() {
    beforeEach(function() {
        browser.ignoreSynchronization = true;
        browser.get('/');
        browser.wait(function() {
            return element(by.id('j_username')).isPresent();
			loginButton.click();
        }, 15000);
        var username = browser.driver.findElement(By.id('j_username'));
        var password = browser.driver.findElement(By.id('j_password'));
        var loginButton = browser.driver.findElement(By.xpath('//form//input[@type="submit"]')).click();
        
        username.sendKeys(browser.params.login.user);
        password.sendKeys(browser.params.login.password);
    });
    it('should have a title', function() {
        expect(browser.getTitle()).toEqual('Title Name');
    });
});

**Comment by biswajitsantra** [comment]
It's Working Fine................

describe('Protractor Demo App', function() {
beforeEach(function() {
browser.ignoreSynchronization = true;
browser.get('/');
browser.wait(function() {
return element(by.id('j_username')).isPresent();
loginButton.click();
}, 15000);
var username = browser.driver.findElement(By.id('j_username'));
var password = browser.driver.findElement(By.id('j_password'));
var loginButton = browser.driver.findElement(By.xpath('//form//input[@type="submit"]'));

    username.sendKeys(browser.params.login.user);
    password.sendKeys(browser.params.login.password);
});
it('should have a title', function() {
    expect(browser.getTitle()).toEqual('Title Name');
});
});

**Comment by qualityshepherd** [comment]
I'm seeing this when running my all my scripts, but not a subset of them...

**Comment by pedrro** [comment]
Hey guys, did u have some fix to this timeout error? I'm already have this error, but only fail one test, I don't know what I have to do to fix this... This error only occurs sometimes, so, it's hard to debug to know what is happening. This is my class, and the test that fails is the first it. [protractor spec](https://github.com/ThoughtWorksInc/registrolivre/blob/master/src/test/resources/functional/tests/register-company-spec.js)

**Comment by juliemr** [comment]
I just retried the original problem, and it is now obsolete w/ protractor 3.

Test output:

```
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
Started
atest start beforeEach
atest stop beforeEach
atest test one started
Fatest start beforeEach
atest stop beforeEach
atest test two started
Fbtest start beforeEach
btest test one started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
Fbtest start beforeEach
btest stop beforeEach
btest test two started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
Fctest start beforeEach
btest stop beforeEach
ctest stop beforeEach
ctest test one started
Fctest start beforeEach
ctest stop beforeEach
ctest test two started
F

Failures:
1) atest atest test one
  Message:
    Expected 'atest' to equal 'test one'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/ralphj/repos/protractor/example/a_spec.js:13:25)
        at process._tickCallback (node.js:368:9)

2) atest atest test two
  Message:
    Expected 'atest' to equal 'test two'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/ralphj/repos/protractor/example/a_spec.js:18:25)
        at process._tickCallback (node.js:368:9)

3) btest btest test one
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Message:
    Expected 'btest' to equal 'test one'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/ralphj/repos/protractor/example/b_spec.js:13:25)

4) btest btest test two
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Message:
    Expected 'btest' to equal 'test two'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/ralphj/repos/protractor/example/b_spec.js:18:25)

5) ctest ctest test one
  Message:
    Expected 'ctest' to equal 'test one'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/ralphj/repos/protractor/example/c_spec.js:13:25)
        at process._tickCallback (node.js:368:9)

6) ctest ctest test two
  Message:
    Expected 'ctest' to equal 'test two'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/ralphj/repos/protractor/example/c_spec.js:18:25)
        at process._tickCallback (node.js:368:9)

6 specs, 6 failures
```

**Comment by sbose78** [comment]
Hi @juliemr , Has there been any resolution/workaround on this? 
Because I still see the issue .
