### ISSUE TITLE
Add error message to timeouts.md

### ISSUE THREAD

**Issue by ksmyth** [angular/protractor#1799]
I am getting this error on my slow CI machine. My tests work on my dev machine.

    A Jasmine spec timed out. Resetting the WebDriver Control Flow.
    The last active task was: 
    Protractor.waitForAngular()
        at [object Object].webdriver.WebDriver.schedule (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
        at [object Object].Protractor.executeAsyncScript_ (/usr/lib/node_modules/protractor/lib/protractor.js:247:26)
        at [object Object].Protractor.waitForAngular (/usr/lib/node_modules/protractor/lib/protractor.js:270:15)

I've read https://github.com/angular/protractor/blob/master/docs/timeouts.md but it is unclear to me which type of timeout this is: "Waiting for Angular" or "Spec Timeout"?

Would you please add this specific error message to timeouts.md?

**Comment by sjelin** [comment]
It's "Waiting for Angular"
