### ISSUE TITLE
ngHint spec/successConfig.js depends on non-existent "./environment.js"

### ISSUE THREAD

**Issue by tullmann** [angular/protractor#1810]
I'm trying to run `npm test` and see this failure:

```
running: node lib/cli.js plugins/timeline/spec/conf.js
>>> pass
running: node lib/cli.js plugins/ngHint/spec/successConfig.js
ERROR - failed loading configuration file plugins/ngHint/spec/successConfig.js

/home/tullmann/demeter/protractor/lib/configParser.js:195
    throw e;
          ^
Error: Cannot find module './environment.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/tullmann/demeter/protractor/plugins/ngHint/spec/successConfig.js:1:73)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
>>> fail: Error: expecting exit code: 0, actual: 8
```

Its pointing at this:
https://github.com/angular/protractor/blob/master/plugins/ngHint/spec/successConfig.js#L1

Its not clear if this directory should have its own "environment" file, or symlink the real one, or reference the real one (in `../../../spec/environment.js`).

(I had to disable "spec/multiConf.js" because my Firefox (v35) has the wont-talk-to-webdriver bug.  I don't think that should break this, but you never know ...)

**Comment by juliemr** [comment]
Fixed with 1.7.0
