### ISSUE TITLE
Empty feature file causes confusing error

### ISSUE THREAD

**Issue by BevanR** [angular/protractor#1829]
An empty `*.feature` file causes an error that does not relate clearly to the problem:

```
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
[launcher] Error: TypeError: Cannot call method 'convertScenarioOutlinesToScenarios' of undefined
    at Object.finish (.../node_modules/cucumber/lib/cucumber/ast/assembler.js:105:32)
    at Object.handleEof [as eof] (.../node_modules/cucumber/lib/cucumber/parser.js:70:20)
    at [object Object].Lexer.scan (.../node_modules/cucumber/node_modules/gherkin/lib/gherkin/lexer/en.js:1049:21)
    at Object.parse (.../node_modules/cucumber/lib/cucumber/parser.js:26:25)
    at Object.getFeatures (.../node_modules/cucumber/lib/cucumber/runtime.js:30:35)
    at Object.start (.../node_modules/cucumber/lib/cucumber/runtime.js:16:37)
    at .../node_modules/protractor/lib/frameworks/cucumber.js:135:15
    at Function.promise (.../node_modules/protractor/node_modules/q/q.js:650:9)
    at .../node_modules/protractor/lib/frameworks/cucumber.js:129:14
    at _fulfilled (.../node_modules/protractor/node_modules/q/q.js:797:54)
[launcher] Process exited with error code 100
```

This could be a bug in Cucumber JS.  I could not find an existing issue in either project's issue queue.

**Comment by juliemr** [comment]
Did you file a bug with cucumberJS? Could you link to it from here?

**Comment by BevanR** [comment]
I just tested in Cucumber JS, and confirmed it is an issue there: https://github.com/cucumber/cucumber-js/issues/306
