### ISSUE TITLE
Is it possible to pipe into protractor?

### ISSUE THREAD

**Issue by bcherny** [angular/protractor#1858]
I am browserifying my test files, and would like to pipe them into protractor instead of having to write to a temporary file, which is un-gulplike and un-nodelike. I tried piping the browserify output stream into protractor, but I keep getting errors:

```text
1) Exception loading: /Users/bcherny/Sites/webapp Error
   Message:
     Error: Cannot find module '/Users/bcherny/Sites/webapp'
   Stacktrace:
     Error: Cannot find module '/Users/bcherny/Sites/webapp'
    at require (module.js:380:17)
    at Function.promise (/Users/bcherny/Sites/webapp/node_modules/protractor/node_modules/q/q.js:650:9)
    at _fulfilled (/Users/bcherny/Sites/webapp/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/Users/bcherny/Sites/webapp/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/Users/bcherny/Sites/webapp/node_modules/protractor/node_modules/q/q.js:759:13)
    at /Users/bcherny/Sites/webapp/node_modules/protractor/node_modules/q/q.js:525:49
    at flush (/Users/bcherny/Sites/webapp/node_modules/protractor/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)
...
```

Here's the relevant excerpt from my gulpfile:

```coffee
gulp.task 'e2e', ->

  browserify
    entries: [
      'e2e/tests/one.js'
      'e2e/tests/two.js'
    ]
  .bundle()
  .on 'error', (_.partialRight error, 'Browserify')
  .pipe protractor
    configFile: 'protractor.conf.coffee'
  .on 'error', (_.partialRight error, 'Protractor')
```

When I use temporary files, everything works fine:

```coffee
gulp.task 'e2e', ['browserify-e2e'], ->

  gulp
    .src [
      "tmp/**/*.js"
    ]
    .pipe protractor
      configFile: 'protractor.conf.coffee'
    .on 'error', (_.partialRight error, 'Protractor')

gulp.task 'browserify-e2e', ->

  browserify
    entries: [
      'e2e/tests/one.js'
      'e2e/tests/two.js'
    ]
  .bundle()
  .on 'error', (_.partialRight error, 'Browserify')
  .pipe source 'test.js'
  .pipe do buffer
  .pipe gulp.dest "tmp/"
```

x/post https://github.com/mllrsohn/gulp-protractor/issues/57

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!

**Comment by bcherny** [comment]
Done, thanks for the heads up. For anyone that has this question the future, google groups post is here: https://groups.google.com/forum/?fromgroups#!topic/angular/Bb5NZSXdrXI
