### ISSUE TITLE
browser.getSession() method does not exist on IE11/Windows 7

### ISSUE THREAD

**Issue by gologox** [angular/protractor#1952]
I am using Protractor 1.6.1 and can use any internetexplorer driver version.
IE Version: 11.0.9600.16428
````
[launcher] Error: TypeError: Object internet explorer has no method 'getSession'
    at config.onComplete (/Users/Owen/Development/automation/test/angular_automation/configs/sauce/s_web_address.conf.js:38:13)
    at Object.jasmineNodeOpts.onComplete [as callback_] (/usr/local/lib/node_modules/protractor/lib/frameworks/jasmine.js:70:13)
    at Object.TerminalReporter.reportRunnerResults (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/reporter.js:70:31)
    at [object Object].jasmine.NestedResults.totalCount [as reportRunnerResults] (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:1901:39)
    at [object Object].jasmine.Runner.finishCallback (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2273:21)
    at [object Object].onComplete (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2257:10)
    at [object Object].jasmine.Queue.next_ (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2219:14)
    at onComplete (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2205:18)
    at [object Object].jasmine.Suite.finish (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2606:5)
    at [object Object].onComplete (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2650:10)
    at [object Object].jasmine.Queue.next_ (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2219:14)
    at onComplete (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2205:18)
    at [object Object].jasmine.Spec.finish (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2477:5)
    at [object Object].onComplete (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2504:10)
    at [object Object].jasmine.Queue.next_ (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2219:14)
    at [object Object]._onTimeout (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2199:18)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
[launcher] Process exited with error code 100
````

**Comment by juliemr** [comment]
We test against windows 11, so this is not a general issue. It looks like the cause of your problem is from `s_web_address.conf.js` - could you share that code?

Could you also try upgrading to the latest version of Protractor and see if you are still having issues?

**Comment by gologox** [comment]
```javascript
var config = {
  sauceUser: process.env.SAUCE_USER_NAME,
  sauceKey: process.env.SAUCE_API_KEY,
  specs: [
  '../../scripts/website/web_address/web_address.js'
  ],
  capabilities: {
    'browserName': browser,
    'platform': platform,
    'platformVersion': platformVersion,
    'version': version,
    'name': 'Web - My Account - Address Update',
    'tags': ['web', 'account', 'address', 'profile', 'update'],
    'passed': true,
    'screen-resolution': '1920x1200'
  },
  onPrepare: function() {
    require('jasmine-reporters');
    jasmine.getEnv().addReporter(new jasmine.JUnitXmlReporter('../../xmloutput', true, true));
    global.isAngularSite = function(flag){
      browser.ignoreSynchronization = !flag;
    };
  },
  onComplete: function(runner, log) {
    console.log('Automation Tests Complete.');
    browser.driver.getSession().then(function(session) {
      console.log("SauceOnDemandSessionID=" + session.getId() + " job-name=Web - My Account - Address Update");
    });
  },
  jasmineNodeOpts: {
    'defaultTimeoutInterval': 60000}
}
```

**Comment by gologox** [comment]
After further investigation, this actually may not be related to any specific browser, it seems to be happening to Chrome all of sudden. This may be related to SauceLabs Cloud instances. Just received this error:

```
[launcher] Error: TypeError: Object chrome has no method 'getSession'
    at config.onComplete (/Users/Owen/Development/automation/test/angular_automation/configs/sauce/s_web_profile_account.conf.js:38:13)
    at Object.jasmineNodeOpts.onComplete [as callback_] (/usr/local/lib/node_modules/protractor/lib/frameworks/jasmine.js:70:13)
    at Object.TerminalReporter.reportRunnerResults (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/reporter.js:70:31)
    at [object Object].jasmine.NestedResults.totalCount [as reportRunnerResults] (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:1901:39)
    at [object Object].jasmine.Runner.finishCallback (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2273:21)
    at [object Object].onComplete (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2257:10)
    at [object Object].jasmine.Queue.next_ (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2219:14)
    at onComplete (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2205:18)
    at [object Object].jasmine.Suite.finish (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2606:5)
    at [object Object].onComplete (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2650:10)
    at [object Object].jasmine.Queue.next_ (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2219:14)
    at onComplete (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2205:18)
    at [object Object].jasmine.Spec.finish (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2477:5)
    at [object Object].onComplete (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2504:10)
    at [object Object].jasmine.Queue.next_ (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2219:14)
    at [object Object]._onTimeout (/usr/local/lib/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2199:18)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
[launcher] Process exited with error code 100
```

**Comment by gologox** [comment]
I resolved this by moving the browser.getSession() method into the actual spec. This is not ideal, but luckily my current automation setup allows me to do so, since I only run one spec per conf file.

This should still be investigated, although it is probably a SauceLab issue with their instances.
