### ISSUE TITLE
Arbitrary results when sending TAB key

### ISSUE THREAD

**Issue by Bernhelm** [angular/protractor#1974]
Hi,

I've done a couple of tests that expect an element to be active when TAB Key is pressed.

The problem is that those tests return random results every time I launch them.

Given these functions:

    function enterInRoot() {
        browser.driver.get(browser.baseUrl + '#/es');
        browser.refresh();
        pageIsLoaded();
    }
    function pageIsLoaded() {
        browser.driver.wait(function() {
            return browser.driver.isElementPresent(by.css("button[name=loginButton]"));
        }, 10000);
    }
    function pressTabKey() {
        return browser.driver.switchTo().activeElement().then(function(elem){
            elem.sendKeys(protractor.Key.TAB);
        });
    }

And these specs:

    beforeEach(enterInRoot);
    it('should active passwordInput', function() {
        pressTabKey().then(function(){
            expect('fccPasswordInput').toEqual(browser.driver.switchTo().activeElement().getAttribute('name'));
        });
    });

    it('should active loginButton', function() {
        pressTabKey().then(function(){
            pressTabKey().then(function(){
                expect('loginButton').toEqual(browser.driver.switchTo().activeElement().getAttribute('name'));
            });
        });
    });

    it('should active languageSelect', function() {
        pressTabKey().then(function(){
            pressTabKey().then(function(){
                pressTabKey().then(function(){
                    expect('languageSelect').toEqual(browser.driver.switchTo().activeElement().getAttribute('name'));
                });
            });
        });
    });

Typically, I get this result (focusing on these tests)

    Using the selenium server at http://localhost:8920/wd/hub
    [launcher] Running 1 instances of WebDriver
    Started
    ...

    3 specs, 0 failures
    Finished in 2.62 seconds
    [launcher] 0 instance(s) of WebDriver still running
    [launcher] chrome #1 passed 

But sometimes I get this error:
 
    should active loginButton
      Message:
        Expected 'loginButton' to equal 'fccUsernameInput'.
      Stack:
        Error: Failed expectation
            at ~/Proyectos/vision/test/e2e/login/login.e2e.js:253:47
            at [object Object].promise.ControlFlow.runInFrame_ (~/Proyectos/vision/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
            at [object Object].promise.Callback_.goog.defineClass.notify (~/Proyectos/vision/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)
            at [object Object].promise.Promise.notify_ (~/Proyectos/vision/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)
            at Array.forEach (native)
            at Object.goog.array.forEach (~/Proyectos/vision/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/array/array.js:203:43)
            at [object Object].promise.Promise.notifyAll_ (~/Proyectos/vision/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:552:16)
            at [object Object].goog.async.run.processWorkQueue [as _onTimeout] (~/Proyectos/vision/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
            at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

    3 specs, 1 failure

My environment:

    Linux Ubuntu
    Xvfb :2 -screen 5 1920x1080x24
    express version: "4.11.2"
    grunt-protractor-runner version: "1.2.1"
    protractor version: "2.0.0"
    selenium version: "2.45.0"
    chromedriver version: "2.14"
    google-chrome version: "41.0.2272.101 (64-bit)"

**Comment by Bernhelm** [comment]
I think I've solved the problem.

It was related with a directive to auto-focus first element which has a timeout of 10ms.

I've changed $timeout for $evalAsync and now it's working properly.
