### ISSUE TITLE
Unable to reinstall

### ISSUE THREAD

**Issue by ot-brian-mackey** [angular/protractor#2021]
I uninstalled protractor:  `npm uninstall -g protractor`. Windows machine. Then I installed protractor to receive the following errors:

```
npm install -g protractor
\


> bufferutil@1.0.1 install C:\Users\bmackey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

|
C:\Users\bmackey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil {git}
{lamb} node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Command failed:
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:647:15)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:755:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:968:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:465:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\bmackey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
/


> utf-8-validate@1.0.1 install C:\Users\bmackey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

\
C:\Users\bmackey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate {git}
{lamb} node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Command failed:
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:647:15)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:755:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:968:11)
gyp ERR! stack     at Socket.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:465:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\bmackey\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.0.1
npm WARN optional dep failed, continuing utf-8-validate@1.0.1
C:\Users\bmackey\AppData\Roaming\npm\protractor -> C:\Users\bmackey\AppData\Roaming\npm\node_modules\protractor\bin\protractor
C:\Users\bmackey\AppData\Roaming\npm\webdriver-manager -> C:\Users\bmackey\AppData\Roaming\npm\node_modules\protractor\bin\webdriver-manager
protractor@2.0.0 C:\Users\bmackey\AppData\Roaming\npm\node_modules\protractor
├── jasminewd@1.1.0
├── jasminewd2@0.0.3
├── html-entities@1.1.2
├── saucelabs@0.1.1
├── q@1.0.0
├── minijasminenode@1.1.1
├── adm-zip@0.4.4
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── lodash@2.4.1
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── request@2.36.0 (json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, qs@0.6.6, oauth-sign@0.3.0, tunnel-agent@0.4.0, mime@1.2.11, tough-cookie@0.12.1, node-uuid@1.4.3, http-signature@0.10.1, hawk@1.0.0, form-data@0.1.4)
├── accessibility-developer-tools@2.6.0
├── jasmine@2.1.1 (jasmine-core@2.1.3)
├── source-map-support@0.2.10 (source-map@0.1.32)
└── selenium-webdriver@2.45.1 (tmp@0.0.24, rimraf@2.3.2, ws@0.7.1, xml2js@0.4.4)
```

**Comment by juliemr** [comment]
Consolidating this issues under https://github.com/angular/protractor/issues/2035
