### ISSUE TITLE
NullPointerException in MouseMoveToLocation.java

### ISSUE THREAD

**Issue by sixinli** [angular/protractor#2036]
Hi all,

I am on 2.45.0 and trying to use mouseMove(element) following the instructions. However, I am getting this error: 

16:11:32.331 INFO - Executing: [mousemove: unused false])
16:11:32.331 WARN - Exception thrown
java.lang.NullPointerException
	at org.openqa.selenium.remote.server.handler.interactions.MouseMoveToLocation.call(MouseMoveToLocation.java:52)
	at org.openqa.selenium.remote.server.handler.interactions.MouseMoveToLocation.call(MouseMoveToLocation.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16:11:32.332 WARN - Exception: null

I see that in :
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md 
it says "FIXED: Correct serialize target elements used in an action sequence." for 2.46.0-dev. I am wondering if there is the same issue? If so, can you point me to the issue for this? I am also wondering what's the milestone for 2.46.0 release in that case?

Thanks a ton!

**Comment by juliemr** [comment]
That sounds like the issue you mentioned. I don't know what the timeframe for 2.46.0 is, but we will update as soon as it is available!

**Comment by jeoffreybakker** [comment]
selenium-webdriver 2.46.1 is released two weeks ago and it seems to fix this issue.

**Comment by sixinli** [comment]
Thanks for the update! Will try to verify

**Comment by juliemr** [comment]
Should be fixed in 2.3.0 and higher.
