### ISSUE TITLE
Protractor error on shutdown after browser fork

### ISSUE THREAD

**Issue by kleinerroemer** [angular/protractor#2056]
If I do a `browser.forkNewDriverInstance()` protractor crashes while shuting down and leaves the forked window open. I'm using protractor 2.0 and latest chrome on windows 7. Could also be webdriver related since the error looks like:

```
Shutting down selenium standalone server.

C:\Users\ich\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
Error: ECONNREFUSED connect ECONNREFUSED
    at ClientRequest.<anonymous> (C:\Users\ich\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:145:16)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:272:9)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickCallback (node.js:355:11)
From: Task: WebDriver.quit()
    at [object Object].webdriver.WebDriver.schedule (C:\Users\ich\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:360:15)
    at [object Object].webdriver.WebDriver.quit (C:\Users\ich\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:443:21)
    at C:\Users\ich\AppData\Roaming\npm\node_modules\protractor\lib\driverProviders\driverProvider.js:59:14
    at [object Object].promise.ControlFlow.runInFrame_ (C:\Users\ich\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1877:20)
    at [object Object].promise.Callback_.goog.defineClass.notify (C:\Users\ich\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:2464:25)
    at [object Object].promise.Promise.notify_ (C:\Users\ich\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:563:12)
    at Array.forEach (native)
    at Object.goog.array.forEach (C:\Users\ich\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\array\array.js:203:43)
    at [object Object].promise.Promise.notifyAll_ (C:\Users\ich\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:552:16)
    at goog.async.run.processWorkQueue (C:\Users\ich\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:125:21)
[launcher] Process exited with error code 1
```

**Comment by hankduan** [comment]
1) Does the test run fine if you don't add `browser.forkNewDriverInstance()`?
2) Can you share the spec files so I can try to reproduce?

**Comment by kleinerroemer** [comment]
Yes, the tests run fine without forking.

Sorry, I can't share the whole specs, but here is my conf if that helps:

````
exports.config = {
	rootElement : "#my-app",
	specs : myTests,
	baseUrl : "http://localhost:8080",
	framework : "jasmine2",
	jasmineNodeOpts : {
		includeStackTrace : true,
		isVerbose : true,
		defaultTimeoutInterval : 180000
	},
	onPrepare : function() {
		browser.driver.manage().window().maximize();
		browser.params.browser1 = browser;
		browser.params.browser2 = browser.forkNewDriverInstance();
		browser.params.browser2.driver.manage().window().maximize();
	}
}
````

**Comment by kleinerroemer** [comment]
I'm very sorry, this was my fault!. I've recently changed my testsetup wich now doesn't start selenium server any more. When selenium server is running everything is working fine.

**Comment by juliemr** [comment]
Great!
