### ISSUE TITLE
Errors in npm test

### ISSUE THREAD

**Issue by BrodaNoel** [angular/protractor#2069]
Hi all!
A few minutes ago I created this (https://github.com/angular/protractor/issues/2068) issue that could be related to this new defect.

I'm running npm test and the most of test are failing.

```
noel.broda@CBA-D013 ~/Desktop/protractor (master)
$ npm test

> protractor@2.0.0 pretest c:\Users\noel.broda\Desktop\protractor
> jshint lib spec scripts


> protractor@2.0.0 test c:\Users\noel.broda\Desktop\protractor
> node scripts/test.js

running: node lib/cli.js spec/basicConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/multiConf.js
[launcher] Running 2 instances of WebDriver

------------------------------------
[firefox #2] PID: 12408
[firefox #2] Specs: c:\Users\noel.broda\Desktop\protractor\spec\basic\lib_spec.js
[firefox #2]
[firefox #2] Using the selenium server at http://localhost:4444/wd/hub
[firefox #2]
[firefox #2] c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
[firefox #2]       callback(new Error(message));
[firefox #2]                ^
>>> fail: Error: expecting exit code: 0, actual: 100
running: node lib/cli.js spec/altRootConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/onCleanUpAsyncReturnValueConf.js
>>> pass
running: node lib/cli.js spec/onCleanUpNoReturnValueConf.js
>>> pass
running: node lib/cli.js spec/onCleanUpSyncReturnValueConf.js
>>> pass
running: node lib/cli.js spec/onPrepareConf.js
>>> pass
running: node lib/cli.js spec/onPrepareFileConf.js
>>> pass
running: node lib/cli.js spec/onPreparePromiseConf.js
>>> pass
running: node lib/cli.js spec/onPreparePromiseFileConf.js
>>> pass
running: node lib/cli.js spec/mochaConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/cucumberConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/withLoginConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/suitesConf.js --suite okmany
>>> pass
running: node lib/cli.js spec/suitesConf.js --suite okspec
>>> pass
running: node lib/cli.js spec/suitesConf.js --suite okmany,okspec
>>> pass
running: node lib/cli.js spec/plugins/smokeConf.js
>>> pass
running: node lib/cli.js spec/plugins/multiPluginConf.js
>>> pass
running: node lib/cli.js spec/plugins/jasmine1PostTestConf.js
>>> pass
running: node lib/cli.js spec/plugins/jasmine2PostTestConf.js
>>> pass
running: node lib/cli.js spec/plugins/mochaPostTestConf.js
>>> pass
running: node lib/cli.js spec/plugins/cucumberPostTestConf.js
>>> pass
running: node lib/cli.js spec/interactionConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/directConnectConf.js
[launcher] Running 2 instances of WebDriver

------------------------------------
[chrome #1] PID: 5552
[chrome #1] Specs: c:\Users\noel.broda\Desktop\protractor\spec\directConnect\directconnect_spec.js
[chrome #1]
[chrome #1] Using ChromeDriver directly...

[launcher] Runner process exited unexpectedly with error code: 1
[launcher] 1 instance(s) of WebDriver still running

------------------------------------
>>> fail: Error: expecting exit code: 0, actual: 100
running: node lib/cli.js spec/restartBrowserBetweenTestsConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/getCapabilitiesConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/controlLockConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/customFramework.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node node_modules/.bin/jasmine JASMINE_CONFIG_PATH=scripts/unit_test.json

c:\Users\noel.broda\Desktop\protractor\node_modules\.bin\jasmine:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
>>> fail: Error: expecting exit code: 0, actual: 8
running: node scripts/interactive_tests/interactive_test.js

c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:126
                    throw e;
                          ^
Did not start interactive server in 10s. Server startup output:

c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:126

                    throw e;

                          ^

Error: No selenium server jar found at the specified location (c:\Users\noel.broda\Desktop\protractor\selenium\selenium-server-standalone-2.45.0.jar). Check
that the version number is up to date.

    at LocalDriverProvider.addDefaultBinaryLocs_ (c:\Users\noel.broda\Desktop\protractor\lib\driverProviders\local.js:37:11)

    at LocalDriverProvider.setupEnv (c:\Users\noel.broda\Desktop\protractor\lib\driverProviders\local.js:71:8)

    at Runner.run (c:\Users\noel.broda\Desktop\protractor\lib\runner.js:265:31)

    at c:\Users\noel.broda\Desktop\protractor\lib\launcher.js:168:21

    at _fulfilled (c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:797:54)

    at self.promiseDispatch.done (c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:826:30)

    at Promise.promise.promiseDispatch (c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:759:13)

    at c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:573:44

    at flush (c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:108:17)

    at process._tickCallback (node.js:419:13)


>>> fail: Error: expecting exit code: 0, actual: 8
running: node scripts/interactive_tests/with_base_url.js

c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:126
                    throw e;
                          ^
Did not start interactive server in 10s. Server startup output:

c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:126

                    throw e;

                          ^

Error: No selenium server jar found at the specified location (c:\Users\noel.broda\Desktop\protractor\selenium\selenium-server-standalone-2.45.0.jar). Check
that the version number is up to date.

    at LocalDriverProvider.addDefaultBinaryLocs_ (c:\Users\noel.broda\Desktop\protractor\lib\driverProviders\local.js:37:11)

    at LocalDriverProvider.setupEnv (c:\Users\noel.broda\Desktop\protractor\lib\driverProviders\local.js:71:8)

    at Runner.run (c:\Users\noel.broda\Desktop\protractor\lib\runner.js:265:31)

    at c:\Users\noel.broda\Desktop\protractor\lib\launcher.js:168:21

    at _fulfilled (c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:797:54)

    at self.promiseDispatch.done (c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:826:30)

    at Promise.promise.promiseDispatch (c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:759:13)

    at c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:573:44

    at flush (c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:108:17)

    at process._tickCallback (node.js:419:13)


>>> fail: Error: expecting exit code: 0, actual: 8
running: node node_modules/minijasminenode/bin/minijn plugins/timeline/spec/unit.js
>>> pass
running: node lib/cli.js plugins/timeline/spec/conf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js plugins/ngHint/spec/successConfig.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js plugins/accessibility/spec/successConfig.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js plugins/console/spec/consolePassConfig.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/errorTest/singleFailureConf.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429557432151.tmp'
running: node lib/cli.js spec/errorTest/timeoutConf.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429557433508.tmp'
running: node lib/cli.js spec/errorTest/afterLaunchChangesExitCodeConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 11, actual: 1
running: node lib/cli.js spec/errorTest/multiFailureConf.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429557436164.tmp'
running: node lib/cli.js spec/errorTest/shardedFailureConf.js
[launcher] Running 2 instances of WebDriver

------------------------------------
[chrome #1a] PID: 5500
[chrome #1a] Specs: c:\Users\noel.broda\Desktop\protractor\spec\errorTest\baseCase\single_failure_spec1.js
[chrome #1a]
[chrome #1a] Using the selenium server at http://localhost:4444/wd/hub
[chrome #1a]
[chrome #1a] c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
[chrome #1a]       callback(new Error(message));
[chrome #1a]                ^

[launcher] Runner process exited unexpectedly with error code: 1
[launcher] 1 instance(s) of WebDriver still running

------------------------------------
>>> fail: Error: expecting exit code: 1, actual: 100
running: node lib/cli.js spec/errorTest/mochaFailureConf.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429557438926.tmp'
running: node lib/cli.js spec/errorTest/pluginsFailingConf.js
>>> pass
running: node lib/cli.js plugins/ngHint/spec/failureConfig.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429557440906.tmp'
running: node lib/cli.js plugins/accessibility/spec/failureConfig.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429557442221.tmp'
running: node lib/cli.js plugins/console/spec/consoleFailConfig.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429557443540.tmp'
running: node lib/cli.js plugins/console/spec/consoleFailErrorConfig.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429557444889.tmp'
running: node lib/cli.js plugins/console/spec/consoleFailWarningConfig.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429557446254.tmp'
running: node lib/cli.js plugins/console/spec/consoleFailFilterConfig.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429557447631.tmp'
Summary: fail
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

noel.broda@CBA-D013 ~/Desktop/protractor (master)
$
```

**Comment by BrodaNoel** [comment]
After this, I execute:
`./bin/webdriver-manager update`
Because I was thinking that it's missing in the "How to contrib" in the README file.

I got this log:
```
noel.broda@CBA-D013 ~/Desktop/protractor (master)
$ ./bin/webdriver-manager update
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.14/chromedriver_win32.zip...
chromedriver_2.14.zip downloaded to c:\Users\noel.broda\Desktop\protractor\selenium\chromedriver_2.14.zip
selenium-server-standalone-2.45.0.jar downloaded to c:\Users\noel.broda\Desktop\protractor\selenium\selenium-server-standalone-2.45.0.jar
```
As you can see, the binary were downloaded and I run again `npm test` getting those error:

```
noel.broda@CBA-D013 ~/Desktop/protractor (master)
$ npm test

> protractor@2.0.0 pretest c:\Users\noel.broda\Desktop\protractor
> jshint lib spec scripts


> protractor@2.0.0 test c:\Users\noel.broda\Desktop\protractor
> node scripts/test.js

running: node lib/cli.js spec/basicConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/multiConf.js
[launcher] Running 2 instances of WebDriver

------------------------------------
[chrome #1] PID: 8164
[chrome #1] Specs: c:\Users\noel.broda\Desktop\protractor\spec\basic\lib_spec.js
[chrome #1]
[chrome #1] Using the selenium server at http://localhost:4444/wd/hub
[chrome #1]
[chrome #1] c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
[chrome #1]       callback(new Error(message));
[chrome #1]                ^
>>> fail: Error: expecting exit code: 0, actual: 100
running: node lib/cli.js spec/altRootConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/onCleanUpAsyncReturnValueConf.js
>>> pass
running: node lib/cli.js spec/onCleanUpNoReturnValueConf.js
>>> pass
running: node lib/cli.js spec/onCleanUpSyncReturnValueConf.js
>>> pass
running: node lib/cli.js spec/onPrepareConf.js
>>> pass
running: node lib/cli.js spec/onPrepareFileConf.js
>>> pass
running: node lib/cli.js spec/onPreparePromiseConf.js
>>> pass
running: node lib/cli.js spec/onPreparePromiseFileConf.js
>>> pass
running: node lib/cli.js spec/mochaConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/cucumberConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/withLoginConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/suitesConf.js --suite okmany
>>> pass
running: node lib/cli.js spec/suitesConf.js --suite okspec
>>> pass
running: node lib/cli.js spec/suitesConf.js --suite okmany,okspec
>>> pass
running: node lib/cli.js spec/plugins/smokeConf.js
>>> pass
running: node lib/cli.js spec/plugins/multiPluginConf.js
>>> pass
running: node lib/cli.js spec/plugins/jasmine1PostTestConf.js
>>> pass
running: node lib/cli.js spec/plugins/jasmine2PostTestConf.js
>>> pass
running: node lib/cli.js spec/plugins/mochaPostTestConf.js
>>> pass
running: node lib/cli.js spec/plugins/cucumberPostTestConf.js
>>> pass
running: node lib/cli.js spec/interactionConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/directConnectConf.js
[launcher] Running 2 instances of WebDriver

------------------------------------
[firefox #2] PID: 3672
[firefox #2] Specs: c:\Users\noel.broda\Desktop\protractor\spec\directConnect\directconnect_spec.js
[firefox #2]
[firefox #2] Using FirefoxDriver directly...
[firefox #2]
[firefox #2] c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1877
[firefox #2]       var result = fn();
[firefox #2]                    ^

[launcher] Runner process exited unexpectedly with error code: 1
[launcher] 1 instance(s) of WebDriver still running
F
------------------------------------
>>> fail: Error: expecting exit code: 0, actual: 100
running: node lib/cli.js spec/restartBrowserBetweenTestsConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/getCapabilitiesConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/controlLockConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/customFramework.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node node_modules/.bin/jasmine JASMINE_CONFIG_PATH=scripts/unit_test.json

c:\Users\noel.broda\Desktop\protractor\node_modules\.bin\jasmine:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
>>> fail: Error: expecting exit code: 0, actual: 8
running: node scripts/interactive_tests/interactive_test.js

c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:126
                    throw e;
                          ^
Command <"browser.get(\"http://localhost:8081\")"> did not receive a response in 10s.
>>> fail: Error: expecting exit code: 0, actual: 8
running: node scripts/interactive_tests/with_base_url.js

c:\Users\noel.broda\Desktop\protractor\node_modules\q\q.js:126
                    throw e;
                          ^
Did not start interactive server in 10s. Server startup output: Starting selenium standalone server...
Selenium standalone server started at http://10.208.235.234:4629/wd/hub
Starting debugger agent.


debugger listening on port 5858


>>> fail: Error: expecting exit code: 0, actual: 8
running: node node_modules/minijasminenode/bin/minijn plugins/timeline/spec/unit.js
>>> pass
running: node lib/cli.js plugins/timeline/spec/conf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js plugins/ngHint/spec/successConfig.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js plugins/accessibility/spec/successConfig.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js plugins/console/spec/consolePassConfig.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 0, actual: 1
running: node lib/cli.js spec/errorTest/singleFailureConf.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429558018054.tmp'
running: node lib/cli.js spec/errorTest/timeoutConf.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429558019392.tmp'
running: node lib/cli.js spec/errorTest/afterLaunchChangesExitCodeConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
      callback(new Error(message));
               ^
>>> fail: Error: expecting exit code: 11, actual: 1
running: node lib/cli.js spec/errorTest/multiFailureConf.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429558022006.tmp'
running: node lib/cli.js spec/errorTest/shardedFailureConf.js
[launcher] Running 2 instances of WebDriver

------------------------------------
[chrome #1b] PID: 5680
[chrome #1b] Specs: c:\Users\noel.broda\Desktop\protractor\spec\errorTest\baseCase\single_failure_spec2.js
[chrome #1b]
[chrome #1b] Using the selenium server at http://localhost:4444/wd/hub
[chrome #1b]
[chrome #1b] c:\Users\noel.broda\Desktop\protractor\node_modules\selenium-webdriver\http\index.js:145
[chrome #1b]       callback(new Error(message));
[chrome #1b]                ^

[launcher] Runner process exited unexpectedly with error code: 1
[launcher] 1 instance(s) of WebDriver still running

------------------------------------
>>> fail: Error: expecting exit code: 1, actual: 100
running: node lib/cli.js spec/errorTest/mochaFailureConf.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429558024754.tmp'
running: node lib/cli.js spec/errorTest/pluginsFailingConf.js
>>> pass
running: node lib/cli.js plugins/ngHint/spec/failureConfig.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429558026795.tmp'
running: node lib/cli.js plugins/accessibility/spec/failureConfig.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429558028116.tmp'
running: node lib/cli.js plugins/console/spec/consoleFailConfig.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429558029434.tmp'
running: node lib/cli.js plugins/console/spec/consoleFailErrorConfig.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429558030767.tmp'
running: node lib/cli.js plugins/console/spec/consoleFailWarningConfig.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429558032149.tmp'
running: node lib/cli.js plugins/console/spec/consoleFailFilterConfig.js
>>> fail: Error: ENOENT, no such file or directory 'c:\Users\noel.broda\Desktop\protractor\test_output_1429558033519.tmp'
Summary: fail
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

noel.broda@CBA-D013 ~/Desktop/protractor (master)
```

**Comment by BrodaNoel** [comment]
After fix the https://github.com/angular/protractor/issues/2068, I'm still getting the same errors

**Comment by juliemr** [comment]
It looks like maybe you don't have the test server running at all. Have you run `npm start` to start the test server before running the suite?

Do you have a selenium server running at localhost:4444?

**Comment by BrodaNoel** [comment]
Nop. I didn't and I haven't. Hehe.
I thought that npm test ran all the necessary things to test protracto.

Firma Automática:
Mail enviado desde mi teléfono móvil. Disculpe los errores y el formato.

**Comment by juliemr** [comment]
OK, then closing this as probably not an issue. Full instructions for how to run test are in https://github.com/angular/protractor/blob/master/CONTRIBUTING.md, under 'Testing your Changes'
