### ISSUE TITLE
intermittent "angular could not be found on the window"

### ISSUE THREAD

**Issue by Mellbourn** [angular/protractor#2078]
We have a large suite of protractor tests. They usually all work. However, intermittently we get the error "angular could not be found on the window", like this:

```JavaScript
   Message:                                                                                                                                           
     Error: Angular could not be found on the page http://localhost:57671/browser2rest.html#/2-2015/98/1017 : retries looking for angular exceeded                                                                                                                                                 
   Stacktrace:                                                                                                                                        
     Error: Angular could not be found on the page http://localhost:57671/browser2rest.html#/2-2015/98/1017 : retries looking for angular exceeded                                                                                                                                                 
    at C:\git\projectfoo\node_modules\protractor\lib\protractor.js:479:17                                                                
    at [object Object].promise.ControlFlow.runInFrame_ (C:\git\projectfoo\node_modules\selenium-webdriver\lib\webdriver\promise.js:1877:20)                                                                                                                                                    
    at [object Object].promise.Callback_.goog.defineClass.notify (C:\git\projectfoo\node_modules\selenium-webdriver\lib\webdriver\promise.js:2464:25)                                                                                                                                          
    at [object Object].promise.Promise.notify_ (C:\git\projectfoo\node_modules\selenium-webdriver\lib\webdriver\promise.js:563:12)       
    at Array.forEach (native)                                                                                                                         
    at Object.goog.array.forEach (C:\git\projectfoo\node_modules\selenium-webdriver\lib\goog\array\array.js:203:43)                      
    at [object Object].promise.Promise.notifyAll_ (C:\git\projectfoo\node_modules\selenium-webdriver\lib\webdriver\promise.js:552:16)    
    at goog.async.run.processWorkQueue (C:\git\projectfoo\node_modules\selenium-webdriver\lib\goog\async\run.js:125:21)                  
    at runMicrotasksCallback (node.js:337:7)                                                                                                          
    at process._tickCallback (node.js:355:11)                                                                                                         
From: Task: Asynchronous test function: beforeEach()                                                                                                  
    at [object Object].<anonymous> (C:\git\projectfoo\node_modules\protractor\node_modules\jasminewd\index.js:93:33)                     
    at [object Object].<anonymous> (C:\git\projectfoo\node_modules\protractor\node_modules\minijasminenode\lib\async-callback.js:45:37)  
    at [object Object].jasmine.Block.execute (C:\git\projectfoo\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js
```

It is different protractor tests that fail.
We are running protractor 2.0 on windows with chromedriver 1.14 and chrome 41.0.2272.118.

**Comment by juliemr** [comment]
See http://angular.github.io/protractor/#/timeouts for more information on this timeout.

Closing as a specific user question - if you think you have found a generic error, please open a new issue.
