### ISSUE TITLE
Getting the same stack trace for different errors

### ISSUE THREAD

**Issue by JonDuffy** [angular/protractor#2094]
I am using protractor to test an angularJS application.

Most of the errors I am getting are showing the same stack traces related to promises, when this is not where the actual error is occurring.

Is this a config / setup error?

For example, if I use an undefined function I get a stack trace that does not relate to the where the undefined function is called.

example stack trace:

   

> at /foo/bar/node_modules/gulp-protractor/node_modules/protractor/node_modules/jasminewd2/index.js:102:16

> at [object Object].promise.ControlFlow.runInFrame_ (/foo/bar/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
            
> at [object Object].promise.Callback_.goog.defineClass.notify (/foo/bar/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)

> at [object Object].promise.Promise.notify_ (/foo/bar/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12) `

Protractor version: 2.0.0
Jasmine version: 2.1.1 

Had anyone else had this?
Thanks in advance,

**Comment by JonDuffy** [comment]
This seems to be the same issue
https://github.com/angular/jasminewd/issues/15

**Comment by JonDuffy** [comment]
Issue seems to be fixed by upgrading jasmine to 2.2.1 from version 2.1.1
