### ISSUE TITLE
Timeouts with PhantomJS as the browser

### ISSUE THREAD

**Issue by Zensavona** [angular/protractor#2103]
Hi guys, I'm having some trouble getting PhantomJS to run (my tests run fine with Chrome). They seem to be timing out regardless of the actual test content. Could anyone shed some light on this? (is it a known issue?). Using protractor 1.8.0 / Gulp

I've done some reading online and have seen lots of PhantomJS issues but not this particular one...

Thanks!

````
[09:46:16] Starting 'e2e'...
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://10.0.0.4:53921/wd/hub
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was:
WebDriver.executeScript()
    at [object Object].webdriver.WebDriver.schedule (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
    at [object Object].webdriver.WebDriver.executeAsyncScript (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:582:15)
    at [object Object].to.(anonymous function) [as executeAsyncScript] (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/lib/protractor.js:62:25)
    at [object Object].loadAndWaitForAureliaPage (/Users/zensavona/softwaredev/projects/ducks/src/main/aurelia.protractor.js:22:18)
    at [object Object].<anonymous> (/Users/zensavona/softwaredev/projects/ducks/src/main/test/e2e/dist/demo.spec.js:14:13)
    at /Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/jasminewd/index.js:94:14
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
    at [object Object].wrapper [as _onTimeout] (timers.js:252:14)
FA Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was:
WebDriver.executeScript()
    at [object Object].webdriver.WebDriver.schedule (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
    at [object Object].webdriver.WebDriver.executeAsyncScript (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:582:15)
    at [object Object].to.(anonymous function) [as executeAsyncScript] (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/lib/protractor.js:62:25)
    at [object Object].loadAndWaitForAureliaPage (/Users/zensavona/softwaredev/projects/ducks/src/main/aurelia.protractor.js:22:18)
    at [object Object].<anonymous> (/Users/zensavona/softwaredev/projects/ducks/src/main/test/e2e/dist/demo.spec.js:14:13)
    at /Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/jasminewd/index.js:94:14
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
    at [object Object].wrapper [as _onTimeout] (timers.js:252:14)
FA Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was:
WebDriver.executeScript()
    at [object Object].webdriver.WebDriver.schedule (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
    at [object Object].webdriver.WebDriver.executeAsyncScript (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:582:15)
    at [object Object].to.(anonymous function) [as executeAsyncScript] (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/lib/protractor.js:62:25)
    at [object Object].loadAndWaitForAureliaPage (/Users/zensavona/softwaredev/projects/ducks/src/main/aurelia.protractor.js:22:18)
    at [object Object].<anonymous> (/Users/zensavona/softwaredev/projects/ducks/src/main/test/e2e/dist/demo.spec.js:14:13)
    at /Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/jasminewd/index.js:94:14
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
    at [object Object].wrapper [as _onTimeout] (timers.js:252:14)
F

Failures:

  1) skeleton app should load the login page
   Message:
     timeout: timed out after 30000 msec waiting for spec to complete
   Stacktrace:
     undefined

  2) skeleton app should display the login form
   Message:
     timeout: timed out after 30000 msec waiting for spec to complete
   Stacktrace:
     undefined

  3) skeleton app should log in with Oscar's credentials and show the customers page
   Message:
     timeout: timed out after 30000 msec waiting for spec to complete
   Stacktrace:
     undefined

Finished in 104.358 seconds
3 tests, 3 assertions, 3 failures


/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
ScriptTimeoutError: {"errorMessage":"Timed out waiting for asyncrhonous script result after 11002 ms","request":{"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"171","Content-Type":"application/json; charset=utf-8","Host":"localhost:23979","User-Agent":"Apache-HttpClient/4.3.6 (java 1.5)"},"httpVersion":"1.1","method":"POST","post":"{\"script\":\"var cb \\u003d arguments[arguments.length - 1];document.addEventListener(\\\"aurelia-composed\\\", function (e) {  cb(\\\"Aurelia App composed\\\")}, false);\",\"args\":[]}","url":"/execute_async","urlParsed":{"anchor":"","query":"","file":"execute_async","directory":"/","path":"/execute_async","relative":"/execute_async","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/execute_async","queryKey":{},"chunks":["execute_async"]},"urlOriginal":"/session/2b681a00-efd6-11e4-9526-9d624fbf7663/execute_async"}}
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'MacBook-Air.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.7.0_55'
Driver info: driver.version: unknown
    at new bot.Error (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:362:20
    at /Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at [object Object].fulfill (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1520:10
==== async task ====
WebDriver.executeScript()
    at [object Object].webdriver.WebDriver.schedule (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
    at [object Object].webdriver.WebDriver.executeAsyncScript (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:582:15)
    at [object Object].to.(anonymous function) [as executeAsyncScript] (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/lib/protractor.js:62:25)
    at [object Object].loadAndWaitForAureliaPage (/Users/zensavona/softwaredev/projects/ducks/src/main/aurelia.protractor.js:22:18)
    at [object Object].<anonymous> (/Users/zensavona/softwaredev/projects/ducks/src/main/test/e2e/dist/demo.spec.js:14:13)
    at /Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/jasminewd/index.js:94:14
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1518:8)
    at [object Object].wrapper [as _onTimeout] (timers.js:252:14)
==== async task ====
WebDriver.quit()
    at [object Object].webdriver.WebDriver.schedule (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
    at [object Object].webdriver.WebDriver.quit (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:418:21)
    at /Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/lib/driverProviders/driverProvider.js:59:14
    at /Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at [object Object].then (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:522:7)
    at [object Object].DriverProvider.quitDriver (/Users/zensavona/softwaredev/projects/ducks/src/main/node_modules/gulp-protractor/node_modules/protractor/lib/driverProviders/driverProvider.js:57:23)
    at Array.map (native)
[launcher] Process exited with error code 1

/Users/zensavona/softwaredev/projects/ducks/src/main/build/tasks/e2e.js:32
    .on('error', function(e) { throw e; });
                                     ^
Error: protractor exited with code 1
````

**Comment by hankduan** [comment]
No known issue comes to mind. Could it be your test is genuinely timing out? 
Can you try http://angular.github.io/protractor/#/tutorial#step-0-write-a-test and see if that times out?

**Comment by Zensavona** [comment]
Hi @hankduan - just tried that demo test and I get the same result for it (aimed at github) as I do for my local ones.

````
  7) Protractor Demo App should have a title
   Message:
     timeout: timed out after 30000 msec waiting for spec to complete
   Stacktrace:
     undefined
````

**Comment by hankduan** [comment]
The only thing I can think of is perhaps https://github.com/angular/protractor/issues/585?

Also, which step is it timing out?
Try to remove everything (including other tests) from your test file except for just this one simple test
```javascript
describe('Protractor Demo App', function() {
  it('should have a title', function() {
    browser.get('http://juliemr.github.io/protractor-demo/');
  });
});
```

Does this time out?

I've also changed the label to phantomjs, so that someone more experienced with phantomjs can chime in on this issue.

**Comment by hankduan** [comment]
Perhaps related to https://github.com/angular/protractor/issues/1901?

**Comment by Zensavona** [comment]
Thanks for your help @hankduan I've realised this is an issue with SystemJS creating errors in Phantom. Closing the issue as it's not related to Protractor.
