### ISSUE TITLE
Error: ECONNREFUSED connect ECONNREFUSED with latest chrome version

### ISSUE THREAD

**Issue by Kebabounette** [angular/protractor#2110]
Hello,

We have an issue with protractor 2.0 (it was the same with 1.8 but I've upgraded it and the same issue occurs).

Before each test session, we are making an installation of chrome by doing :+1: 
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
gdebi --n google-chrome-stable_current_amd64.deb

so, we use the lastest version of chrome.

Since chrome was updated (on may the 1rst), we have this issue.

Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
ERROR - Unable to start a WebDriver session.

/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145
      callback(new Error(message));
               ^
Error: ECONNREFUSED connect ECONNREFUSED
    at ClientRequest.<anonymous> (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:155:22)
    at Function.webdriver.WebDriver.createSession (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:129:30)
    at [object Object].Builder.build (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/builder.js:416:22)
    at [object Object].DriverProvider.getNewDriver (/root/jenkins/workspace/C3-E2E/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/root/jenkins/workspace/C3-E2E/node_modules/protractor/lib/runner.js:180:37)
    at /root/jenkins/workspace/C3-E2E/node_modules/protractor/lib/runner.js:257:21
    at _fulfilled (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/q/q.js:759:13)
    at /root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/q/q.js:573:44
[launcher] Process exited with error code 1

config is the following :+1: 
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    capabilities: {
        'browserName': 'chrome'
    },
    allScriptsTimeout: 400000,
    getPageTimeout: 90000,
    restartBrowserBetweenTests: true,
    specs: ['src/tests/**/*.js'],
    suites: {
        non_regression: [
            'src/tests/accueil/page_accueil.js',
            'src/tests/config/configuration/agences/6_enregistrement_modifications_agence.js',
            'src/tests/config/configuration/utilisateurs_licences/4b_activation_nouvel_utilisateur.js',
            'src/tests/contact/creation/8_lancement_seconde_recherche.js',
            'src/tests/contact/liste/1_liste_contacts.js',
            'src/tests/offre/creation/appartement_vente/5_verification_validation.js',
            'src/tests/offre/liste/1_liste_biens.js',
            'src/tests/offre/diffusion/1a_formulaire_depuis_grille.js',
            'src/tests/action_co/liste/1_liste_action_co.js',
            'src/tests/admin/echec_connexion.js'
        ],
        offre_mise_a_jour: 'src/tests/offre/mise_a_jour/**/*.js',
        offre_liste: 'src/tests/offre/liste/**/*.js',
        offre_diffusion: 'src/tests/offre/diffusion/**/*.js',
        offre_creation: 'src/tests/offre/creation/**/*.js',
        offre_consultation: 'src/tests/offre/consultation/**/*.js',
        document: 'src/tests/document/**/*.js',
        contact_liste: 'src/tests/contact/liste/**/*.js',
        contact_formulaire: ['src/tests/contact/consultation_contact_autre_societe/**/*.js',
            'src/tests/contact/creation/**/*.js',
            'src/tests/contact/modification/**/*.js'],
        connexion: ['src/tests/*.js',
            'src/tests/page_connexion_avec_animations/*.js'],
        config: 'src/tests/config/**/*.js',
        admin: 'src/tests/admin/**/*.js',
        action_co_proposition: 'src/tests/action_co/proposition/**/*.js',
        action_co_formulaire: 'src/tests/action_co/formulaire/**/*.js',
        action_co: ['src/tests/action_co/consultation/**/*.js',
            'src/tests/action_co/creation/**/*.js',
            'src/tests/action_co/liste/**/*.js',
            'src/tests/action_co/mise_a_jour/**/*.js'],
        accueil: 'src/tests/accueil/**/*.js'
    },
    framework: 'jasmine2',
    onPrepare: function () {
        var jasmineReporters = require('jasmine-reporters');
        jasmine.getEnv().addReporter(
            new jasmineReporters.JUnitXmlReporter({
                savePath: 'report',
                consolidateAll: true
            })
//            new jasmine.JUnitXmlReporter(
//
//                "report", true, true, 'report', false)
        );
        console.log('waiting for session...');
        return browser.driver.getSession().then(function () {
            console.log('...acquired.');
        });
    },
    jasmineNodeOpts: {
        showColors: true, // Use colors in the command line report.
        isVerbose: true, // List all tests in the console
        defaultTimeoutInterval: 500000,
        includeStackTrace: true,
        realtimeFailure: true
    }
};

Things are working correctly with firefox.

Versions we use are the following :+1: 
packages =
    protractor@2.0.0
    request@2.55.0
    phantomjs@1.9.16
    jasmine-reporters@2.0.6
    path@0.11.14

Do you have any idea of what happens ?

Thanks by advance.
Regards.

**Comment by Kebabounette** [comment]
Here are selenium output :

10:15:23.061 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome}]
Starting ChromeDriver 2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf) on port 18363
Only local connections are allowed.
[0,628][WARNING]: PAC support disabled because there is no system implementation
10:16:24.746 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'terebellum', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16-2-amd64', java.version: '1.7.0_65'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:175)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:111)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:88)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:109)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:57)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:110)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:172)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:201)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:163)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:129)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'terebellum', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16-2-amd64', java.version: '1.7.0_65'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:69)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:214)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
	... 9 more
Caused by: org.openqa.selenium.WebDriverException: chrome not reachable
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.16-2-amd64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.72 seconds
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'terebellum', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16-2-amd64', java.version: '1.7.0_65'
Driver info: org.openqa.selenium.chrome.ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:171)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:139)
	... 14 more
10:16:24.758 WARN - Exception: chrome not reachable
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.16-2-amd64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.72 seconds

May be it can helps :)

Regards.

**Comment by Kebabounette** [comment]
And for more information, the first real error is this one :

ERROR - Unable to start a WebDriver session.

/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: chrome not reachable
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.16-2-amd64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.72 seconds
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'terebellum', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16-2-amd64', java.version: '1.7.0_65'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at new bot.Error (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:158:24
    at [object Object].promise.ControlFlow.runInFrame_ (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
    at [object Object].promise.Callback_.goog.defineClass.notify (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)
    at [object Object].promise.Promise.notify_ (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)
    at Array.forEach (native)
    at Object.goog.array.forEach (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/array/array.js:203:43)
    at [object Object].promise.Promise.notifyAll_ (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:552:16)
    at [object Object].goog.async.run.processWorkQueue [as _onTimeout] (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:155:22)
    at Function.webdriver.WebDriver.createSession (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:129:30)
    at [object Object].Builder.build (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/selenium-webdriver/builder.js:416:22)
    at [object Object].DriverProvider.getNewDriver (/root/jenkins/workspace/C3-E2E/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/root/jenkins/workspace/C3-E2E/node_modules/protractor/lib/runner.js:180:37)
    at /root/jenkins/workspace/C3-E2E/node_modules/protractor/lib/runner.js:257:21
    at _fulfilled (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/q/q.js:759:13)
    at /root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/q/q.js:573:44
    at flush (/root/jenkins/workspace/C3-E2E/node_modules/protractor/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3

Sorry for the mistake.

Regards.

**Comment by sjelin** [comment]
Protractor runs fine against chrome v 42.  Must be a problem with your setup

https://github.com/angular/protractor/pull/2130
