### ISSUE TITLE
Timed out waiting in Chrome, Safari

### ISSUE THREAD

**Issue by mato75** [angular/protractor#2113]
The tests run, but nothing happens in browser, and because nothing happens in browser the test fail.

Chrome error:
 Timed out waiting for Protractor to synchronise with the page after 11 seconds

I think there is some issue with the initial $http request, but I don't understand why the tests are done executed, because $http request id done.

    describe('ADM login page', function () {
	beforeEach(function () {
		browser.get(browser.baseUrl + '/user/login/');
	});

	it('login', function () {
		$('div.e2e-adm-login-page').isPresent().then(function () {
			var username = element(by.css('div.e2e-adm-username-input input.Input-Holder')),
				password = element(by.css('div.e2e-adm-password-input input.Input-Holder')),
				btn = element(by.css('div.Login-ActionHolder a.Big-Action'));

			username.clear();
			password.clear();

			btn.click().then(function () {
				expect($('h4.Login-Error').isDisplayed()).toBeTruthy();
			});

			username.sendKeys('mj@dd.dd');
			password.sendKeys('1111');

			expect(username.getAttribute('value')).toBe('mj@dd.dd');
			expect(password.getAttribute('value')).toBe('1111');

			btn.click();
		});
	});
    });

protractor v2.0.0
selenium 2.45

**Comment by mato75** [comment]
what is the problem here, I cannot find the solution here, I set the allScriptsTimeout to 20000 and yet doesnt work. What is the issue here, that it doesnt work in Chrome and Safari??????

**Comment by mato75** [comment]
It looks like that the tests run before the UI is present, how do I fix this?

      allScriptsTimeout: 20000,
	getPageTimeout: 20000,
	jasmineNodeOpts: {
		onComplete: null,
		isVerbose: false,
		showColors: true,
		includeStackTrace: true,
		defaultTimeoutInterval: 30000
	}

**Comment by mato75** [comment]
Selenium Console:

     Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/nn/sv90mzls6hq0gt0yd6wggs080000gn/T/.org.chromium.Chromium.xwS0jN}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=42.0.2311.135, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.executeAsyncScript(RemoteWebDriver.java:526)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
	at com.sun.proxy.$Proxy1.executeAsyncScript(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.executeAsyncScript(EventFiringWebDriver.java:225)
	at org.openqa.selenium.remote.server.handler.ExecuteAsyncScript.call(ExecuteAsyncScript.java:55)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
18:34:30.804 WARN - Exception: asynchronous script timeout: result was not received in 11 seconds

**Comment by mato75** [comment]
???????

**Comment by am-karl** [comment]
I think there is a bug with Safari... https://github.com/angular/protractor/issues/2111

**Comment by sjelin** [comment]
I see nothing wrong with your protractor code.  Presumably the problem is that your webapp is crashing on chrome & safari.  You should open it up and take a look in the console for errors.

am-kerl's correct that we're looking at a potential problem with Safari, but since your having problems with chrome that is probably not what's going on in your case.

**Comment by mato75** [comment]
Test run in Chrome, but it is not pretty.

I have a API that is called on startup, and what I did now is this in every beforeEach:

                browser.get(browser.baseUrl + url);
		browser.ignoreSynchronization = true;

		browser.driver.sleep(5000);
		browser.waitForAngular();

But with this we disable synchronisation with angularjs $http and $timeouts. 

Is there a better solution?

**Comment by mato75** [comment]
Why is this issue closed??

**Comment by mato75** [comment]
this is my routing, it loads UI when API is OK, is this maybe a reason why I get timeout every time in chrome?

                               route.config.resolve = {
					message: function (UserInfo) {
						return UserInfo.promise();
					}
				};

**Comment by sjelin** [comment]
This issue is closed because it's not a protractor bug, but a problem with your specific code.  I'd suggest asking for help on github

**Comment by emna24** [comment]
I have the same issue when i run protractor script with appium, how did you solve it ?

**Comment by bmsoko** [comment]
Me too, I'm having the same problems with Ch and FF, it runs ok on FF but it does not on Ch. how can we tell if its the application? how can I tell de DEV that he needs to do something to correct that? 
Thanks!!
