### ISSUE TITLE
Error in running test in Angular step 3 tutorial

### ISSUE THREAD

**Issue by mainman** [angular/protractor#2168]
Hi
New to the Angular world, I do the tutorial (and the test). And when I run npm run protractor, I get this error :
```
Using ChromeDriver directly...
[launcher] Error: Could not find chromedriver at D:\web\angular-phonecat\node_modules\protractor\selenium\chromedriver.exe

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\web\angular-phonecat\npm-debug.log
```

And here is the npm-debug.log file :
```
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@2.9.1
3 info using node@v0.12.3
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info preprotractor angular-phonecat@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info protractor angular-phonecat@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-phonecat@0.0.0 Failed to exec protractor script
10 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid angular-phonecat@0.0.0
12 verbose cwd D:\web\angular-phonecat
13 error Windows_NT 6.1.7601
14 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
15 error node v0.12.3
16 error npm  v2.9.1
17 error code ELIFECYCLE
18 error angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
18 error Exit status 1
19 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
19 error This is most likely a problem with the angular-phonecat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     protractor test/protractor-conf.js
19 error You can get their info via:
19 error     npm owner ls angular-phonecat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

For info, in D:\web\angular-phonecat\node_modules\protractor\selenium\ there is chromedriver_2.10.zip & selenium-server-standalone-2.42.2.jar

Thanks for helping !
Renaud

**Comment by juliemr** [comment]
Have you done `npm run update-webdriver`, which the tutorial mentions is a prerequisite?

**Comment by mainman** [comment]
Yes, I have done it.

**Comment by juliemr** [comment]
Does chromedriver in fact exist at `D:\web\angular-phonecat\node_modules\protractor\selenium\chromedriver.exe`?

**Comment by mainman** [comment]
The file exists (as mentioned in my 1st post). But I tried to open it with 7zip, and the file seems corrupted... Don't know why.

**Comment by mainman** [comment]
As I "must" do this tutorial quickly, I downloaded the correct driver at ```http://chromedriver.storage.googleapis.com/index.html```
It solved the problem. But I don't know why the zip was corrupted, network problem perhaps...
Thanks @juliemr

**Comment by juliemr** [comment]
Sounds like could be fixed by https://github.com/angular/protractor/issues/1857.

Since the immediate issue is resolved, closing.

**Comment by mainman** [comment]
Thanks again. By the way, really love AngularJS & the test tools ! Great job.
