### ISSUE TITLE
Jasmine timeouts, 

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#2174]
IE9 inside VM virtual box, too slow, and test get timeout.

Stacktrace is

```
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
Protractor.waitForAngular()
    at [object Object].webdriver.WebDriver.schedule (/app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
    at [object Object].Protractor.executeAsyncScript_ (/app/node_modules/grunt-protractor-runner/node_modules/protractor/lib/protractor.js:1141:26)
    at [object Object].Protractor.waitForAngular (/app/node_modules/grunt-protractor-runner/node_modules/protractor/lib/protractor.js:1159:15)
    at [object Object].getWebElements (/app/node_modules/grunt-protractor-runner/node_modules/protractor/lib/protractor.js:191:21)
    at [object Object].getWebElements (/app/node_modules/grunt-protractor-runner/node_modules/protractor/lib/protractor.js:705:33)
    at [object Object].ElementArrayFinder.applyAction_ (/app/node_modules/grunt-protractor-runner/node_modules/protractor/lib/protractor.js:440:30)
    at [object Object].self.(anonymous function) [as isDisplayed] (/app/node_modules/grunt-protractor-runner/node_modules/protractor/lib/protractor.js:135:21)
    at [object Object].self.(anonymous function) [as isDisplayed] (/app/node_modules/grunt-protractor-runner/node_modules/protractor/lib/protractor.js:734:13)
    at /app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/until.js:272:
```

```
TypeError: Cannot call method 'split' of undefined
    at Object.SpecDisplay.filterStackTraces (/app/node_modules/jasmine-spec-reporter/src/spec-display.js:110:24)
    at Object.SpecDisplay.displayErrorMessages (/app/node_modules/jasmine-spec-reporter/src/spec-display.js:102:25)
    at Object.SpecDisplay.failed (/app/node_modules/jasmine-spec-reporter/src/spec-display.js:80:12)
    at Object.SpecReporter.reportSpecResults (/app/node_modules/jasmine-spec-reporter/src/jasmine-spec-reporter.js:85:20)
    at [object Object].jasmine.NestedResults.totalCount [as reportSpecResults] (/app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:1901:39)
    at [object Object].jasmine.Spec.finishCallback (/app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2470:21)
    at [object Object].jasmine.Spec.finish (/app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2475:8)
    at [object Object].onComplete (/app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2504:10)
    at [object Object].jasmine.Queue.next_ (/app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2219:14)
    at [object Object]._onTimeout (/app/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2199:18)
>> 
Fatal error: protractor exited with code: 1
```

**so frustrating** :(

**Comment by juliemr** [comment]
IE9 is not one of our supported browsers, and we don't test against it. See http://angular.github.io/protractor/#/browser-support for our policy. Do you see this error with other browsers?

**Comment by bitliner** [comment]
I dont remember if it happened in other browser.

Giovanni

On Thursday, May 21, 2015, Julie Ralph <notifications@github.com> wrote:

> IE9 is not one of our supported browsers, and we don't test against it.
> See http://angular.github.io/protractor/#/browser-support for our policy.
> Do you see this error with other browsers?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/protractor/issues/2174#issuecomment-104394208>
> .
>


-- 
*Giovanni Gaglione                            *

LinkedIn: http://lnkd.in/MyZGut
Telefono: +39 388 - 82.6666.2 / 0031-06.49.75.66.93 / 0031-06.11.06.22.17
Email: giovanni.gaglione@gmail.com
<giovanni.gaglione@gmail.com>Skype: bitliner

**Comment by juliemr** [comment]
Unfortunately, it's pretty hard to give any feedback on this then. It seems like  your second error is coming from `jasmine-spec-reporter`, so I can't really offer any feedback about that either.

I'm going to close this as non-actionable - please open up a new issue if you can reproduce in one of the supported browsers.

**Comment by bitliner** [comment]
@juliemr I need support for IE9. You could monetize from it, I would be eager to pay.

Do you know if there is any community that is already working on it?

Imagine that is full of companies around the world that are still using ie9 because of license issues.

**Comment by sjelin** [comment]
Sorry, Protractor isn't a profit center of Google, so offering to pay doesn't help.  That said, we're an open source project and generally want to make people happy!  So if you want to tackle this problem yourself, or find someone eager to tackle it, we'd be more than happy to merge in your changes.

**Comment by bitliner** [comment]
Thanks @sjelin . You want to make people happy, but you don't realize that you don't make them happy, lack of support makes people sad instead. Good luck with your project to make people happy ...haha
