### ISSUE TITLE
Detected a page unload event while running the tests in Safari

### ISSUE THREAD

**Issue by spatchamatla** [angular/protractor#2184]
protractor v 2.1.0,
Safari v8.0.6, 
MAC OS v10.10.3.

This issue is similar to  #85 and it still exists. Im seeing the below issue..
```
UnknownError: Detected a page unload event; script execution does not work across page loads. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.19 seconds
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'mac.local', ip: '<>, os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=8.0.6, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.executeAsyncScript(RemoteWebDriver.java:526)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
	at com.sun.proxy.$Proxy1.executeAsyncScript(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.executeAsyncScript(EventFiringWebDriver.java:225)
	at org.openqa.selenium.remote.server.handler.ExecuteAsyncScript.call(ExecuteAsyncScript.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sjelin** [comment]
Could you give some information about the app you're testing and the tests you're running?  Some code would be ideal.

**Comment by spatchamatla** [comment]
This happens when i clicked on LogOut button.
```
LogOutBtnElement.click().then(function(){
        logger.debug('Clicked on LogOutBtnElement and waiting for Login Page to Load');
         //wait for the LogOutBtnElement to be clickable
         browser.waitForAngular();
         expect(LogInBtnElement.isDisplayed()).toBeTruthy();
},function(err){
          //Log error
          logger.error('Error while Clicking on LogOut Element'+err);
});
```
I'm using safari extension v2.38.0 but couldn't run on safari with safari extension v2.45.0 since driver.get() wont navigate to another URL. Logged in issue #2111

**Comment by sjelin** [comment]
Does` LogOutBtn` trigger the browser to navigate?

**Comment by spatchamatla** [comment]
Yes it navigates to different page which doesn't have angular

**Comment by sjelin** [comment]
Ok, so the problem is that the page navigation is triggering a page unload event

**Comment by spatchamatla** [comment]
Protractor 2.1.0
Safari 8.0.6
Webdriver 2.45.0
OSX 10.10.3
Safari extension 2.45.0

Below is the mockup code which is able to recreate the above issue.
```
describe ('Test Safari with two URLs', function() {

    var defaultSyncStatus = browser.ignoreSynchronization;

    beforeEach(function(){
        //for non angular Pages
        browser.ignoreSynchronization = true;
        browser.get('http://www.google.com');
    });

    afterEach(function() {
    });

    it('test with apple.com', function () {
        browser.ignoreSynchronization = defaultSyncStatus;
        browser.get('http://www.apple.com');
    });
});
```
When it try to navigate to **http://www.apple.com**, it displays only about:blank and it times out with the above ScriptTimeoutError error

and here is the protractor config as well.
```

var browsers = {
    chrome:{
        name:'Chrome',
        browserName:'chrome',
        chromeOptions : {
            args: ['--lang=en','--window-size=1024,768']
        }
    },
    safari:{
        name:'Safari',
        browserName:'safari'
    },
    multiCapabilities: [{
        browserName: 'safari'
    }, {
        browserName: 'chrome',
        chromeOptions : {
            args: ['--lang=en','--window-size=1024,768']
        }
    }]

}
exports.config = {
    // The address of a running selenium server.
    seleniumAddress: 'http://127.0.0.1:4444/wd/hub',

    // Spec patterns are relative to the configuration file location passed to protractor
    // They may include glob patterns.
    specs: [
        '<path to scenario>'
    ],

    //asynchronous time out
    allScriptsTimeout: 30000,

    onPrepare: function() {
        //increase the script time outs
        browser.manage().timeouts().setScriptTimeout(30000);
    },

    //For Jasmine framework
    framework: 'jasmine',

    // Options to be passed to Jasmine-node.
    jasmineNodeOpts: {
        // Use colors in the command line report.
        showColors: true,
        //for StackTrace -- not for Jasmine 2
        includeStackTrace:true,
        //for Verbose -- not for Jasmine 2
        isVerbose:true,
        //for defaultTimeoutInterval
        // max time any test case can run
        defaultTimeoutInterval:300000
        //showTiming: true
    }
};

if(process.argv[3] === '--chrome'){
    exports.config.capabilities = browsers.chrome;
}else if(process.argv[3] === '--safari'){
    exports.config.capabilities = browsers.safari;
};
```

**Comment by swangful** [comment]
What if during the page navigation there is no page unload event?
