### ISSUE TITLE
UnknownError: no such session or how to handle Web-Driver level exceptions at global leve

### ISSUE THREAD

**Issue by singh-gurpreet** [angular/protractor#2303]
I am running Selenium Grid using many Nodes. For some reason one browser always throws following exception Majority is from Chrome only 1-2 cases from FireFox. If there is way to handle them at global level, i can re-scheduled for 2nd pass:

```
[chrome LINUX #4a] PID: 3672
[chrome LINUX #4a] Specs: C:\Hosting\ProtractorAutomation\test\spec\06-07-2015-00-00-03-4\TestQueue_100.js
[chrome LINUX #4a] 
[chrome LINUX #4a] Using the selenium server at http://*******:4444/wd/hub
[chrome LINUX #4a] VA-NB-9
[chrome LINUX #4a]   
[chrome LINUX #4a] [31m    Start test 100 - fail[0m
[chrome LINUX #4a] 
[chrome LINUX #4a] 
[chrome LINUX #4a] Failures:
[chrome LINUX #4a] 
[chrome LINUX #4a]   1) VA-NB-9 Start test 100
[chrome LINUX #4a]    Message:
[chrome LINUX #4a]      [31mUnknownError: no such session
[chrome LINUX #4a]   (Driver info: chromedriver=2.9.248304,platform=Linux 3.16.0-30-generic x86_64) (WARNING: The server did not provide any stacktrace information)
[chrome LINUX #4a] Command duration or timeout: 1.27 seconds
[chrome LINUX #4a] Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
[chrome LINUX #4a] System info: host: 'testadmin-VirtualBox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-30-generic', java.version: '1.7.0_79'
[chrome LINUX #4a] Session ID: 4e3b580a4ad9dafe7ac5679dbd4408d3
[chrome LINUX #4a] Driver info: org.openqa.selenium.chrome.ChromeDriver
[chrome LINUX #4a] Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.1gxZ2E}, rotatable=false, locationContextEnabled=true, version=43.0.2357.130, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}][0m
[chrome LINUX #4a]    Stacktrace:
[chrome LINUX #4a]      UnknownError: no such session
[chrome LINUX #4a]   (Driver info: chromedriver=2.9.248304,platform=Linux 3.16.0-30-generic x86_64) (WARNING: The server did not provide any stacktrace information)
[chrome LINUX #4a] Command duration or timeout: 1.27 seconds
[chrome LINUX #4a] Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
[chrome LINUX #4a] System info: host: 'testadmin-VirtualBox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-30-generic', java.version: '1.7.0_79'
[chrome LINUX #4a] Session ID: 4e3b580a4ad9dafe7ac5679dbd4408d3
[chrome LINUX #4a] Driver info: org.openqa.selenium.chrome.ChromeDriver
[chrome LINUX #4a] Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.1gxZ2E}, rotatable=false, locationContextEnabled=true, version=43.0.2357.130, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
[chrome LINUX #4a]     at new bot.Error (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:113:18)
[chrome LINUX #4a]     at Object.bot.response.checkResponse (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\response.js:106:9)
[chrome LINUX #4a]     at C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:20
[chrome LINUX #4a]     at C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1582:15
[chrome LINUX #4a]     at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1654:20)
[chrome LINUX #4a]     at notify (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:465:12)
[chrome LINUX #4a]     at notifyAll (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:442:7)
[chrome LINUX #4a]     at resolve (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:420:7)
[chrome LINUX #4a]     at [object Object].fulfill (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:535:5)
[chrome LINUX #4a]     at C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1520:10
[chrome LINUX #4a] ==== async task ====
[chrome LINUX #4a] WebElement.getText()
[chrome LINUX #4a]     at [object Object].webdriver.WebDriver.schedule (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:345:15)
[chrome LINUX #4a]     at [object Object].webdriver.WebElement.schedule_ (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:1727:23)
[chrome LINUX #4a]     at [object Object].webdriver.WebElement.getText (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:1975:15)
[chrome LINUX #4a]     at actionFn (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\lib\element.js:75:32)
[chrome LINUX #4a]     at C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\lib\element.js:394:17
[chrome LINUX #4a]     at Array.forEach (native)
[chrome LINUX #4a]     at C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\lib\element.js:393:9
[chrome LINUX #4a]     at C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1582:15
[chrome LINUX #4a]     at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1654:20)
[chrome LINUX #4a] ==== async task ====
[chrome LINUX #4a] Asynchronous test function: it()
[chrome LINUX #4a]     at [object Object].<anonymous> (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd\index.js:93:33)
[chrome LINUX #4a]     at [object Object].<anonymous> (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\async-callback.js:45:37)
[chrome LINUX #4a]     at [object Object].jasmine.Block.execute (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:1174:17)
[chrome LINUX #4a]     at [object Object].jasmine.Queue.next_ (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2209:31)
[chrome LINUX #4a]     at [object Object]._onTimeout (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2199:18)
[chrome LINUX #4a] Error
[chrome LINUX #4a]     at [object Object].ElementArrayFinder.applyAction_ (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\lib\element.js:390:21)
[chrome LINUX #4a]     at [object Object].self.(anonymous function) [as getText] (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\lib\element.js:77:19)
[chrome LINUX #4a]     at [object Object].selectOption [as setDropDown] (C:\Hosting\ProtractorAutomation\test\helpers\InputHelper.js:335:37)
[chrome LINUX #4a]     at [object Object].setInput (C:\Hosting\ProtractorAutomation\test\helpers\InputHelper.js:167:16)
[chrome LINUX #4a]     at [object Object].setLocator (C:\Hosting\ProtractorAutomation\test\helpers\InputHelper.js:68:17)
[chrome LINUX #4a]     at [object Object].<anonymous> (C:\Hosting\ProtractorAutomation\test\StandardTestCaseFlow.js:68:41)
[chrome LINUX #4a]     at C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd\index.js:94:14
[chrome LINUX #4a]     at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1654:20)
[chrome LINUX #4a]     at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1518:8)
[chrome LINUX #4a] Error
[chrome LINUX #4a]     at [object Object].<anonymous> (C:\Hosting\ProtractorAutomation\test\StandardTestCaseFlow.js:55:28)
[chrome LINUX #4a]     at [object Object].jasmine.Env.describe_ (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:913:21)
[chrome LINUX #4a]     at [object Object].jasmine.Env.describe (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:898:15)
[chrome LINUX #4a]     at describe (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:658:27)
[chrome LINUX #4a]     at [object Object].ExecuteTest (C:\Hosting\ProtractorAutomation\test\StandardTestCaseFlow.js:34:7)
[chrome LINUX #4a]     at [object Object].<anonymous> (C:\Hosting\ProtractorAutomation\test\spec\06-07-2015-00-00-03-4\TestQueue_100.js:4:24)
[chrome LINUX #4a]     at [object Object].jasmine.Env.describe_ (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:913:21)
[chrome LINUX #4a]     at [object Object].jasmine.Env.describe (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:898:15)
[chrome LINUX #4a]     at describe (C:\Users\TestAdmin\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:658:27)
[chrome LINUX #4a] 
[chrome LINUX #4a] Finished in 939.892 seconds
[chrome LINUX #4a] [31m1 test, 13 assertions, 1 failure
```

**Comment by sjelin** [comment]
Can you give me some information about the actual tests you're running?

**Comment by singh-gurpreet** [comment]
I can't share the script as we have written a data driven wrapper over Protractor that generate flow at run-time. But any case this is related to browser. After installing Chrome *.130 version it started working.
Thanks for your time @sjelin
