### ISSUE TITLE
Protractor prints lot of stack traces on start

### ISSUE THREAD

**Issue by madhavan020985** [angular/protractor#2357]
I started protractor with the conf file as, .https://github.com/madhavan020985/miscFiles/blob/master/conf.js#L6

It brings up the firefox window successfully but before doing it, it prints a lot of stack traces on my console as,

````javascript
*************protractor/node_modules/q/q.js*************************************
Trace
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:760:10)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:573:38
    at flush (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:108:11)
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
*************protractor/node_modules/q/q.js*************************************
Trace
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:760:10)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:573:38
    at flush (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:108:11)
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3
Selenium standalone server started at http://192.168.0.2:56544/wd/hub
*************protractor/node_modules/q/q.js*************************************
Trace
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:760:10)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:573:38
    at flush (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:108:11)
    at process._tickCallback (node.js:415:13)
````

Are they an indication of error on my side (or) can they be turned off?

**Comment by madhavan020985** [comment]
looks like, it is due to my local library changes... sorry for raising it...
