### ISSUE TITLE
Worked in 2.1, but exception in 2.2

### ISSUE THREAD

**Issue by Delagen** [angular/protractor#2456]
```
TypeError: Cannot read property 'onPageLoad' of undefined
  From: Task: <anonymous>
      at Context.initFn (..\index.js:18:12)
  From: Task: "before all" hook
```

```
var initFn = function() {
			browser.manage().deleteAllCookies();
			browser.get("/");
		};

		describe("task1", function() {
			before(initFn);
...
		});
```

**Comment by alanstott** [comment]
+1

Fatal error: Cannot call method 'onPageLoad' of undefined

**Comment by cletusw** [comment]
+1 I'm also getting this. Works on 2.1.0 but fails with 2.2.0. With more explicit promise handling I get a fuller stacktrace:

```
Cannot read property 'onPageLoad' of undefined
TypeError: Cannot read property 'onPageLoad' of undefined
    at --OMITTED ROOT--/node_modules/protractor/lib/protractor.js:606:25
    at [object Object].promise.ControlFlow.runInFrame_ (--OMITTED ROOT--/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
    at [object Object].promise.ControlFlow.runEventLoop_ (--OMITTED ROOT--/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1755:8)
    at [object Object].<anonymous> (--OMITTED ROOT--/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:2056:12)
    at goog.async.run.processWorkQueue (--OMITTED ROOT--/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
From: Task: <anonymous>
    at [object Object].Protractor.get (--OMITTED ROOT--/node_modules/protractor/lib/protractor.js:605:29)
    at --OMITTED ROOT--/jstest/ui/bootstrap.js:49:20
    at [object Object].promise.ControlFlow.runInFrame_ (--OMITTED ROOT--/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
    at [object Object].promise.Callback_.goog.defineClass.notify (--OMITTED ROOT--/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)
    at [object Object].promise.Promise.notify_ (--OMITTED ROOT--/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)
    at Array.forEach (native)
    at Object.goog.array.forEach (--OMITTED ROOT--/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/array/array.js:203:43)
    at [object Object].promise.Promise.notifyAll_ (--OMITTED ROOT--/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:552:16)
    at goog.async.run.processWorkQueue (--OMITTED ROOT--/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
    at runMicrotasksCallback (node.js:337:7)
  1) "before all" hook
```

where `--OMITTED--/jstest/ui/bootstrap.js:49:20` is:

```javascript
return browser.get('/noop');
```

**Comment by lyttlegy** [comment]
+1

**Comment by laukev7** [comment]
Getting this error as well:

TypeError: Cannot read property 'onPageLoad' of undefined
        at /home/kev/node_modules/protractor-cucumber/node_modules/protractor/lib/protractor.js:608:25
        at [object Object].promise.ControlFlow.runInFrame_ (/home/kev/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
        at [object Object].promise.ControlFlow.runEventLoop_ (/home/kev/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1729:8)
        at [object Object].eval (/home/kev/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2043:12)
        at goog.async.run.processWorkQueue (/home/kev/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
        at process._tickDomainCallback (node.js:399:9)

      From: Task: <anonymous>
        at [object Object].Protractor.get (/home/kev/node_modules/protractor-cucumber/node_modules/protractor/lib/protractor.js:605:29)
        at [object Object].Wanderlust.go (/home/kev/WebstormProjects/TestsForIreland/features/step_definitions/lib/Wanderlust.js:13:31)
        at World.<anonymous> (/home/kev/WebstormProjects/TestsForIreland/features/step_definitions/my_steps.js:29:27)
        at World.<anonymous> (/home/kev/WebstormProjects/TestsForIreland/features/step_definitions/my_steps.js:21:9)
        at doNTCallback0 (node.js:407:9)
        at process._tickDomainCallback (node.js:377:13)
        at Function.Module.runMain (module.js:477:11)
        at startup (node.js:117:18)
        at node.js:951:3

**Comment by aorylamballe** [comment]
+1

**Comment by laukev7** [comment]
I get this error when trying to return a promise to CucumberJS:

    this.Given(/^I am on the Wanderlust website$/, function() {
        return this.browser.get("http://mywanderlust.co/");
    });

which is supposed to support this feature:

https://github.com/cucumber/cucumber-js#promises

**Comment by juliemr** [comment]
This looks like it was due to changes in the plugins. We've started assuming that instances of Protractor have a `plugins_` property. This is a bug, and the fix will just be checking that it actually exists. See https://github.com/angular/protractor/blob/master/lib/protractor.js#L570

**Comment by juliemr** [comment]
FYI - @sjelin we should make sure that the Protractor class does not rely on the setup done in `runner.js`.

**Comment by cletusw** [comment]
1487e5abf69bc1540226502aacadc8b3b42b0092 didn't actually fix my problem. I was creating an instance of `Runner`, then calling `.createBrowser()` on it with no arguments, which was blindly replacing `this.plugins_` with `undefined`. Turns out I just needed to call `.createBrowser(Plugins({}))`. Would it maybe be better to allow `createBrowser()` to be called with no arguments?

**Comment by juliemr** [comment]
@cletusw the `Runner` is not guaranteed as a public API, so we may make breaking changes to it between versions without specifically noting them as breaking changes. 

That said - it looks like the internal documentation for the Runner did not get updated along with the plugins change, so we should at least fix that. https://github.com/angular/protractor/blob/master/lib/runner.js#L174 I also think it does make more sense for `createBrowser` to treat that parameter as optional.

**Comment by cletusw** [comment]
@juliemr I agree, what we're doing is pretty hacky. We'll start looking for a more official way to do it. Thanks!
