### ISSUE TITLE
Protractor not able to read geojson

### ISSUE THREAD

**Issue by mathilde-pellerin** [angular/protractor#2471]
Hi all,

For my e2e test, I have to load geojson file, which are just json files with a particular structure (http://geojson.org/).

It works well when I use .json extension:
```var dataToSend = require('../resources/Cheminee.json');```

but not when I use .geojson extension:
```var dataToSend = require('../resources/Cheminee.geojson');```
>   1) UF2 step 2 should add data from Cheminee.geojson file
   Message:
     Error: Cannot find module '../resources/Cheminee.geojson'
   Stacktrace:
     Error: Cannot find module '../resources/Cheminee.geojson'
    at require (module.js:384:17)
    at [object Object].<anonymous> (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\test\e2e\ctc\ctc_UF2.spec.js:22:20)
    at c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\node_modules\protractor\node_modules\jasminewd\index.js:94:14
    at [object Object].promise.ControlFlow.runInFrame_ (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1877:20)
    at [object Object].promise.ControlFlow.runEventLoop_ (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1755:8)
    at [object Object].<anonymous> (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:2056:12)
    at goog.async.run.processWorkQueue (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:125:21)
From: Task: Asynchronous test function: it()
    at [object Object].<anonymous> (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\node_modules\protractor\node_modules\jasminewd\index.js:93:33)
    at [object Object].<anonymous> (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\node_modules\protractor\node_modules\minijasminenode\lib\async-callback.js:45:37)
    at [object Object].jasmine.Block.execute (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:1174:17)
    at [object Object].jasmine.Queue.next_ (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2209:31)
    at [object Object]._onTimeout (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2199:18)
Error
    at [object Object].<anonymous> (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\test\e2e\ctc\ctc_UF2.spec.js:21:2)
    at [object Object].jasmine.Env.describe_ (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:913:21)
    at [object Object].jasmine.Env.describe (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:898:15)
    at describe (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:658:27)
    at Object.<anonymous> (c:\Users\guest875\Documents\work\projets\ValorX\workspace_frontend\valorX-common\test\e2e\ctc\ctc_UF2.spec.js:8:1)

It's odd because file is exactly the same, just extension changed.
Do you think that geojson support could be added to protractor ?

**Comment by juliemr** [comment]
I'm not familiar with geojson, but I don't know why Protractor would need to do anything special to support it. Protractor scripts are run using node.js, so anything that works with a normal node script should work. Your error looks like it's coming directly from node. Can you make sure that this works outside the context of Protractor?

**Comment by juliemr** [comment]
Closing stale issues. Please open a new issue if you feel there is still a general bug.
