### ISSUE TITLE
protractor and mocha 2.3.x: undefined error

### ISSUE THREAD

**Issue by tkurdyna** [angular/protractor#2480]
When running tests using framework mocha I am getting the following error al the time, tests work fine though.

[launcher] Error: TypeError: Cannot read property 'skip' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/testing/index.js:205:40)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Suite.<anonymous> (/usr/local/lib/node_modules/protractor/lib/frameworks/mocha.js:24:27)
    at Suite.emit (events.js:117:20)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:215:11
[launcher] Process exited with error code 100

I am aware of issue #1185, but I think it should work on latest protractor + mocha as well.

**Comment by juliemr** [comment]
We are now testing against mocha 2.3.3, and use `it.skip` in our tests.

If you believe there is still a problem, please open a new issue with a test case that shows the problem. Thanks!
