### ISSUE TITLE
Error running tests on protractor

### ISSUE THREAD

**Issue by olgakovb** [angular/protractor#2488]
I`m using protractor for running the tests. It fails in random order and not always, but 5 times from 6 it fails with similar stacktrace. Can somebody, please, help to unrstand this feature and find the place where problem starts to have possibility to look and maybeto fix?
here is a stacktrace. 
```
[FAILED]
UnknownError: unknown error: updateWindow is not defined
JavaScript stack:
ReferenceError: updateWindow is not defined
    at eval (eval at executeAsyncScript (unknown source), <anonymous>:2:9)
    at executeAsyncScript (<anonymous>:314:26)
    at apply.state (<anonymous>:330:29)
    at callFunction (<anonymous>:222:33)
    at apply.state (<anonymous>:232:23)
    at <anonymous>:233:3
    at Object.InjectedScript._evaluateOn (<anonymous>:904:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:837:34)
    at Object.InjectedScript.evaluate (<anonymous>:693:21)
  (Session info: chrome=45.0.2454.85)
  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 667 milliseconds
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=WIN8, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=scoped_dir7276_31813}, rotatable=false, locationContextEnabled=true, version=45.0.2454.85, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
    at new bot.Error (npm\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:113:18)
    at Object.bot.response.checkResponse (npm\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\response.js:106:9)
    at npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:377:20
    at [object Object].promise.ControlFlow.runInFrame_ (npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1877:20)
    at [object Object].promise.Callback_.goog.defineClass.notify (npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:2464:25)
    at [object Object].promise.Promise.notify_ (npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:563:12)
    at Array.forEach (native)
    at Object.goog.array.forEach (npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\array\array.js:203:43)
    at [object Object].promise.Promise.notifyAll_ (npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:552:16)
    at goog.async.run.processWorkQueue (npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:125:21)
From: Task: Asynchronous test function: it()
    at [object Object].<anonymous> (npm\node_modules\protractor\node_modules\jasminewd\index.js:93:33)
    at [object Object].<anonymous> (npm\node_modules\protractor\node_modules\minijasminenode\lib\async-callback.js:45:37)
    at [object Object].jasmine.Block.execute (npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:1174:17)
    at [object Object].jasmine.Queue.next_ (npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2209:31)
    at [object Object]._onTimeout (npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2199:18)
    at Timer.listOnTimeout (timers.js:119:15)==== async task ====
Error
    at [object Object].<anonymous> (loginSpec.js:3:5)
    at [object Object].jasmine.Env.describe_ (npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:913:21)
    at [object Object].jasmine.Env.describe (npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:898:15)
    at describe (npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:658:27)
    at Object.<anonymous> (loginSpec.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by olgakovb** [comment]
Hi again. Problem is connected to source code, so I guess that stackoverflow can not help me, but here is link to that post: http://stackoverflow.com/questions/32560126/error-running-tests-on-protractor-unknown-error-updatewindow-is-not-defined/32654103#32654103
