### ISSUE TITLE
TypeError when enabling jUnitXmlReporter in onPrepare

### ISSUE THREAD

**Issue by jeffhuys** [angular/protractor#2531]
I'm trying to get XML reports from protractor. I'm using the following code:

````
'use strict';

require('jasmine-reporters');

var paths = require('./.yo-rc.json')['generator-gulp-angular'].props.paths;

// An example configuration file.
exports.config = {
  // The address of a running selenium server.
  //seleniumAddress: 'http://localhost:4444/wd/hub',
  //seleniumServerJar: deprecated, this should be set on node_modules/protractor/config.json

  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'chrome'
  },
  
  baseUrl: 'http://localhost:3000',

  // Spec patterns are relative to the current working directly when
  // protractor is called.
  specs: ['src/**/*.spec.js'],

  // Options to be passed to Jasmine-node.
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    isVerbose: true
  },

  onPrepare: function() {
    jasmine.getEnv().addReporter(
      new jasmine.JUnitXmlReporter('xmloutput', true, true));
  }
};
````

It gives me this error:

````
Error: TypeError: undefined is not a function
    at exports.config.onPrepare (*myProject*/protractor.conf.js:33:7)
    at *myProject*/node_modules/gulp-protractor/node_modules/protractor/lib/util.js:56:41
    [etc...]
````

Am I doing something wrong here? I got the code for the `onPrepare` function from here: https://github.com/angular/protractor/blob/ba8220598708989e0f760a09d3787069abf4aaee/spec/junitOutputConf.js

**Comment by jeffhuys** [comment]
I needed to change the `require` to `var jasmineReporters = require('jasmine-reporters');`, as jasmine-reporters 2.x changed their naming scheme. 
Then, using `new jasmineReporters.JUnitXmlReporter('xmloutput', true, true)`, it works!
