### ISSUE TITLE
TypeError: Object #<Object> has no method 'parse'

### ISSUE THREAD

**Issue by Droogans** [angular/protractor#2590]
Bumping to protractor 2.5.0 this afternoon has caused [our Travis builds to fail](https://travis-ci.org/rackerlabs/encore-ui/builds/84151445#L2532).

```
$ ./node_modules/.bin/protractor
/home/travis/build/rackerlabs/encore-ui/node_modules/protractor/node_modules/q/q.js:126
                    throw e;
                          ^
TypeError: Object #<Object> has no method 'parse'
    at Function.ConfigParser.resolveFilePatterns (/home/travis/build/rackerlabs/encore-ui/node_modules/protractor/lib/configParser.js:102:29)
    at new TaskScheduler (/home/travis/build/rackerlabs/encore-ui/node_modules/protractor/lib/taskScheduler.js:31:31)
    at /home/travis/build/rackerlabs/encore-ui/node_modules/protractor/lib/launcher.js:180:21
    at _fulfilled (/home/travis/build/rackerlabs/encore-ui/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/home/travis/build/rackerlabs/encore-ui/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/travis/build/rackerlabs/encore-ui/node_modules/protractor/node_modules/q/q.js:759:13)
    at /home/travis/build/rackerlabs/encore-ui/node_modules/protractor/node_modules/q/q.js:573:44
    at flush (/home/travis/build/rackerlabs/encore-ui/node_modules/protractor/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:448:13)
    at Function.Module.runMain (module.js:499:11)
```

These run locally though! Very strange. We have Jenkins tests that run for internal projects that are experiencing the same failure. It may be something to do with Linux? I'm not quite sure as this is a very recent development.

**Comment by brandenbyers** [comment]
Are you sharding in Jenkins but not locally? That was our issue; still haven't figured out why.

**Comment by Droogans** [comment]
We run one instance of webdriver in the link to Travis above. This is also the case in our Jenkins tests.

**Comment by brandenbyers** [comment]
Are you using at least node 0.12? According to issue #2588, that is what is causing this error.

**Comment by Droogans** [comment]
Ah, thanks. I will close this issue then.
