### ISSUE TITLE
TypeError: "capsObject.toJSON" is not a function >=2.4.0

### ISSUE THREAD

**Issue by cyparu** [angular/protractor#2592]
I'm playing with Benchpress [demo](https://github.com/angular/benchpress-tree) that works just fine for Protractor < **2.4.0** but with higher versions (I've tested with **2.4.0** & **2.5.0**) I got this error:
<pre> 1) deep tree baseline should be fast!
  Message:
    Failed: TypeError: capsObject.toJSON is not a function
  Stack:
    Error: TypeError: capsObject.toJSON is not a function
        at proxyDone.fail (X:\perf-tests\benchpress-tree\node_modules\protractor\node_modules\jasminewd2\index.js:89:34)
        at promiseReactionJob (X:\perf-tests\benchpress-tree\node_modules\benchpress\index.js:8379:27)
        at Immediate._onImmediate (X:\perf-tests\benchpress-tree\node_modules\benchpress\index.js:8392:11)
    From: Task: Run it("should be fast!") in control flow
        at Object.<anonymous> (X:\perf-tests\benchpress-tree\node_modules\protractor\node_modules\jasminewd2\index.js:81:14)
        at attemptAsync (X:\perf-tests\benchpress-tree\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1819:24)
        at QueueRunner.run (X:\perf-tests\benchpress-tree\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1774:9)
        at X:\perf-tests\benchpress-tree\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1801:16
        at X:\perf-tests\benchpress-tree\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1745:9
        at X:\perf-tests\benchpress-tree\node_modules\protractor\node_modules\jasminewd2\index.js:18:5
        at Array.forEach (native)
    From asynchronous test:
    Error
        at Suite.<anonymous> (X:\perf-tests\benchpress-tree\tree_benchmark.spec.js:16:3)
        at addSpecsToSuite (X:\perf-tests\benchpress-tree\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:743:25)
        at Env.describe (X:\perf-tests\benchpress-tree\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:713:7)
        at jasmineInterface.describe (X:\perf-tests\benchpress-tree\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:3219:18)
        at Object.<anonymous> (X:\perf-tests\benchpress-tree\tree_benchmark.spec.js:15:1)
</pre>

**Comment by juliemr** [comment]
This is a documented change in the `selenium-webdriver` api. It's been fixed in https://github.com/angular/angular/commit/af1119063c315803cb268703f5301c3f6a8f6495

You should be able to fix it by linking with the `angular2` at master.

**Comment by cyparu** [comment]
Great! Hopefully the fix will be incorporated into the next Angular 2 release (**2.0.0-alpha.40**)
