### ISSUE TITLE
Protractor crashing on path.parse()

### ISSUE THREAD

**Issue by Burgov** [angular/protractor#2596]
```
/home/bart/workspace/epicuro-ui/node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:126
                    throw e;
                          ^
TypeError: Object #<Object> has no method 'parse'
    at Function.ConfigParser.resolveFilePatterns (/home/bart/workspace/epicuro-ui/node_modules/gulp-protractor/node_modules/protractor/lib/configParser.js:102:29)
    at new TaskScheduler (/home/bart/workspace/epicuro-ui/node_modules/gulp-protractor/node_modules/protractor/lib/taskScheduler.js:31:31)
    at /home/bart/workspace/epicuro-ui/node_modules/gulp-protractor/node_modules/protractor/lib/launcher.js:180:21
    at _fulfilled (/home/bart/workspace/epicuro-ui/node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/home/bart/workspace/epicuro-ui/node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/bart/workspace/epicuro-ui/node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:759:13)
    at /home/bart/workspace/epicuro-ui/node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:573:44
    at flush (/home/bart/workspace/epicuro-ui/node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)

/home/bart/workspace/epicuro-ui/gulpfile.js:459
            throw e;
                  ^
Error: protractor exited with code 8
```

Seems to be related to this change: https://github.com/angular/protractor/commit/d6aebbad6e9b191fef141472887637ee4318438e#diff-5e5e3eb8e4137fbd8fba49f71f579ac4R102

**Comment by NickTomlin** [comment]
This is covered in [2558](https://github.com/angular/protractor/issues/2588) and fixed in [2591](https://github.com/angular/protractor/pull/2591)

**Comment by Burgov** [comment]
great! i should've looked at the closed issues as well before creating this one
