### ISSUE TITLE
2.5 error for no method 'parse'

### ISSUE THREAD

**Issue by tonygresko** [angular/protractor#2597]
I just recently upgraded to 2.5.0 and when i try to run the tests i get an error:

TypeError: Object #<Object> has no method 'parse'
    at Function.ConfigParser.resolveFilePatterns (/usr/lib/node_modules/protractor/lib/configParser.js:102:29)
    at new TaskScheduler (/usr/lib/node_modules/protractor/lib/taskScheduler.js:31:31)
    at /usr/lib/node_modules/protractor/lib/launcher.js:180:21
    at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:759:13)
    at /usr/lib/node_modules/protractor/node_modules/q/q.js:573:44
    at flush (/usr/lib/node_modules/protractor/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)

**Comment by NickTomlin** [comment]
This is covered in [2558](https://github.com/angular/protractor/issues/2588) and fixed in [2591](https://github.com/angular/protractor/pull/2591). For a stopgap fix, you can downgrade your version of protractor.

**Comment by tonygresko** [comment]
Ok great thanks. Seems like i can also upgrade my node since i just checked and we are currently on 0.10 due to restrictions from other applications but seems we might be able to upgrade that now.

**Comment by juliemr** [comment]
Closing as dupe
