### ISSUE TITLE
"session not created exception from tab crashed"

### ISSUE THREAD

**Issue by chocochik92** [angular/protractor#2610]
I probably need to bring this up to Selenium also but I thought I'd ask here as well. I'm getting this error:
> SessionNotCreatedError: session not created exception from timeout: Timed out receiving message from renderer: 600.000

I am running protractor tests on Windows 8 Chrome. What happens is that a Chrome tab will open but won't load the url, and will open C:\Program Files(x86)\Google\Chrome\Application\chrome.exe shell window. Then nothing else happens and the test times out. Which makes sense that I get a timeout error. But I'm not sure why it isn't loading the website in the first place.

When I close the chrome tab I then get this message:

> SessionNotCreatedError: session not created exception from tab crashed`

I am up to date on both selenium standalone and chromedriver. The only thing I can think of is that Chrome was recently updated to 46.0.2490.71, but I don't have any problems on Windows 7 with this same version.

Here's the full log: 

    /Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
    var template = new Error(this.message);
                 ^
    SessionNotCreatedError: session not created exception 
    from tab crashed
    (Session info: chrome=46.0.2490.71)
    (Driver info: chromedriver=2.16.333243     (0bfa1d3575fc1044244f21ddb82bf870944ef961),platform=Windows NT 6.3 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 30.24 seconds
    Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
    System info: host: 'Win8Test', ip: '192.168.1.185', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_45'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    at new bot.Error     (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:158:24
    at [object Object].promise.ControlFlow.runInFrame_ (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
    at [object Object].promise.Callback_.goog.defineClass.notify (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)
    at [object Object].promise.Promise.notify_ (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)
    at Array.forEach (native)
    at Object.goog.array.forEach (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/array/array.js:203:43)
    at [object Object].promise.Promise.notifyAll_ (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:552:16)
    at goog.async.run.processWorkQueue (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
    From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:155:22)
    at Function.webdriver.WebDriver.createSession (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:129:30)
    at [object Object].Builder.build (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/selenium-webdriver/builder.js:416:22)
    at [object Object].DriverProvider.getNewDriver (/Users/awilliamson/projects/chewie/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/Users/awilliamson/projects/chewie/node_modules/protractor/lib/runner.js:180:37)
    at /Users/awilliamson/projects/chewie/node_modules/protractor/lib/runner.js:256:21
    at _fulfilled (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/q/q.js:759:13)
    at /Users/awilliamson/projects/chewie/node_modules/protractor/node_modules/q/q.js:525:49
    [launcher] Process exited with error code 1`

config.js

    exports.config = {
      multiCapabilities: [
        {
          'browserName': 'chrome',
          seleniumAddress: 'http://192.168.1.136:4444/wd/hub' // windows 7
        },
        {
          'browserName': 'chrome',
          seleniumAddress: 'http://192.168.1.185:4444/wd/hub' // windows 8
        },
      ],
      framework: 'jasmine2',
      suites: {...},
      jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 30000
      },
      params: {
        url: ...
      }
    },
    onPrepare: function () {
      global.dvr = browser.driver;
      global.siteUrl = browser.params.url;
      global.isAngularSite = function (flag) {
        browser.ignoreSynchronization = !flag;
      };
      dvr.manage().window().setPosition(0, 0);
      dvr.manage().window().setSize(1024, 768);
      browser.getCapabilities().then(function (cap) {
        browser.browserName = cap.caps_.browserName;
      });
      ...
    }

**Comment by sjelin** [comment]
Can I see your config file?

**Comment by JulienBier** [comment]
Same issue there. 
It was working with Chrome 45 but not with Chrome 46 (on Windows 8.1).

**Comment by chocochik92** [comment]
I added my config file

**Comment by sjelin** [comment]
@chocochik92 Could you run the following in node:

```js
var webdriver = require('selenium-webdriver');

var driver = new webdriver.Builder().
    usingServer('http://192.168.1.185:4444/wd/hub').
    withCapabilities({
      'browserName': 'chrome',
    }).build();

driver.get('http://www.google.com');

driver.quit();
```

This should test selenium directly.  If it works, it will open Google and then quit.

**Comment by chocochik92** [comment]
@sjelin still the same problem

**Comment by sjelin** [comment]
Ok, then it's definitely a problem with WebDriver and not with protractor.

**Comment by chocochik92** [comment]
I ended up solving this issue by upgrading to Chromedriver 2.19

**Comment by johanbove** [comment]
Took me a while to find this out. Thanks for posting!

Explanation for people who need to know how to upgrade to ChromeDriver: check the file (on Windows) and set the "chromedriver" property of the "config.json" file:

    %USERPROFILE%\AppData\Roaming\npm\node_modules\webdriver-manager\config.json

```
{
  "webdriverVersions": {
    "selenium": "2.46.0",
    "chromedriver": "2.20",
    "iedriver": "2.46.0",
    "chromedriver-nw": "0.12.2"
  }
}
```
