### ISSUE TITLE
Tests not working on Android

### ISSUE THREAD

**Issue by danielwagner** [angular/protractor#2617]
I'm trying to set up Protractor testing on Android as descibed here: https://github.com/angular/protractor/blob/master/docs/mobile-setup.md#setting-up-protractor-with-selendroid

Selendroid is started as a standalone server:
```
java -jar selendroid-standalone-0.16.0-with-dependencies.jar -app selendroid-test-app-0.16.0.apk
```

This is my Protractor config:

```
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['todo-spec.js'],
  capabilities: {
    browserName: 'android',
    model: 'Nexus 7'
  }
};
```

The test spec is the example from http://www.protractortest.org/

```
describe('angularjs homepage todo list', function() {
  it('should add a todo', function() {
    browser.get('https://angularjs.org');

    element(by.model('todoList.todoText')).sendKeys('write first protractor test');
    element(by.css('[value="add"]')).click();

    var todoList = element.all(by.repeater('todo in todoList.todos'));
    expect(todoList.count()).toEqual(3);
    expect(todoList.get(2).getText()).toEqual('write first protractor test');

    // You wrote your first test, cross it off the list
    todoList.get(2).element(by.css('input')).click();
    var completedAmount = element.all(by.css('.done-true'));
    expect(completedAmount.count()).toEqual(2);
  });
});
```

When Protractor is started, the emulator launches, the Selendroid WebView app opens and briefly displays the website, then the test errors out with a SelendroidException caused by a JavaScript error:
```
[$injector:modulerr] http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=p&p1=Error: [$injector:nomod] http://errors.angularjs.org/1.4.7/$injector/nomod?p0=p
    at Error (<anonymous>)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:6:416
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:24:186
    at a (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:23:252)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:23:495
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:37:427
    at m (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:7:322)
    at h (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:37:275)
    at fb (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:41:35)
    at d (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:19:463)
```

I also tried to execute the tests on a physical device (Samsung Galaxy Note 2) connected via USB, but the result is the same.

Is there anything wrong with my setup? What could be causing this error?

**Comment by sjelin** [comment]
Hi, GitHub issues are for feature requests and bug reports, not support.  Please ask questions like this on something like StackOverflow, as per our CONTRIBUTING.md
