### ISSUE TITLE
Firefox tests won't start after update to Firefox 41

### ISSUE THREAD

**Issue by ValentinH** [angular/protractor#2648]
Today, I had the excellent idea to upgrade the Firefox of my continuous integration stack. Now, I get the following output:
```shell
Using the selenium server at http://127.0.0.1:4444/wd/hub
[launcher] Running 1 instances of WebDriver

/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
72ce4c6-7e08-4474-a285-3208198ce6fd} to /usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}
1446131238599	addons.xpi	INFO	Mapping ubufox@ubuntu.com to /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com
1446131238600	addons.xpi	DEBUG	checkForChanges
1446131238600	addons.xpi	DEBUG	Loaded add-on state from prefs: {"app-profile":{"fxdriver@googlecode.com":{"d":"/tmp/anonymous8841327687889545832webdriver-profile/extensions/fxdriver@googlecode.com","e":true,"v":"2.44.0","st":1446131225000,"mt":1446131225000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"33.0","st":1413026563000,"mt":1413025780000}},"app-system-share":{"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com","e":false,"v":"3.0","st":1421413074000,"mt":1420839872000}}}
1446131238601	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1446131238605	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1446131238606	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"/tmp/anonymous8841327687889545832webdriver-profile/extensions/fxdriver@googlecode.com","e":true,"v":"2.44.0","st":1446131225000,"mt":1446131225000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"33.0","st":1413026563000,"mt":1413025780000}},"app-system-share":{"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com","e":false,"v":"3.0","st":1421413074000,"mt":1420839872000}}}
1446131238608	addons.xpi	DEBUG	No changes found
1446131238610	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1446131238611	addons.manager	DEBUG	Provider finished startup: XPIProvider
1446131238611	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1446131238611	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1446131238612	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1446131238612	addons.manager	DEBUG	Starting provider: GMPProvider
1446131238618	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1446131238618	addons.manager	DEBUG	Provider finished startup: GMPProvider
1446131238618	addons.manager	DEBUG	Starting provider: PluginProvider
1446131238618	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1446131238619	addons.manager	DEBUG	Provider finished startup: PluginProvider
1446131238619	addons.manager	DEBUG	Completed startup sequence
1446131238674	addons.xpi-utils	DEBUG	Starting async load of XPI database /tmp/anonymous8841327687889545832webdriver-profile/extensions.json
1446131238791	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1446131238791	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1446131238792	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1446131238890	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1446131238890	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1446131238891	addons.xpi-utils	DEBUG	Successfully read XPI database
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1446131238993	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1446131238993	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1446131238993	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
JavaScript error: file:///tmp/anonymous8841327687889545832webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11487: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]

    at new bot.Error (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
    at Object.bot.response.checkResponse (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)
    at /home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:160:24
    at [object Object].promise.ControlFlow.runInFrame_ (eval at <anonymous> (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1124:19), <anonymous>:1857:20)
    at [object Object].goog.defineClass.notify (eval at <anonymous> (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1124:19), <anonymous>:2448:25)
    at [object Object].promise.Promise.notify_ (eval at <anonymous> (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1124:19), <anonymous>:564:12)
    at Array.forEach (native)
    at [object Object].promise.Promise.notifyAll_ (eval at <anonymous> (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1124:19), <anonymous>:553:15)
    at [object Object].goog.async.run.processWorkQueue [as _onTimeout] (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at [object Object].Builder.build (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/selenium-webdriver/builder.js:445:22)
    at [object Object].DriverProvider.getNewDriver (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/lib/runner.js:182:37)
    at driverprovider_.setupEnv.then.then.then.frameworkPath (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/lib/runner.js:263:21)
    at _fulfilled (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/q/q.js:759:13)
    at /home/gitlab_ci_runner/gitlab-ci-runner/tmp/builds/project-3/frontend/tests/node_modules/protractor/node_modules/q/q.js:525:49
[launcher] Process exited with error code 1
```

This seems to be related to https://github.com/SeleniumHQ/selenium/issues/927 which was fixed in Selenium 2.48.0 .

Is there anybody who is succesfully running Protractor tests on Firefox 41?

**Comment by ValentinH** [comment]
Nevermind, it was a problem with my selenium-server which was not updated.
