### ISSUE TITLE
TypeError: Cannot read property 'addExpectationResult' of undefined

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#2659]
After I added `framework:'jasmine2'` to protractor configuration file - in order to support `beforeAll` method - it throws the following error:

```
TypeError: Cannot read property 'addExpectationResult' of undefined
    at Env.fail (/home/vagrant/.nvm/versions/node/v0.12.7/lib/node_modules/protractor/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:894:24)
    at Function.next.fail (/home/vagrant/.nvm/versions/node/v0.12.7/lib/node_modules/protractor/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1806:19)
    at /home/vagrant/.nvm/versions/node/v0.12.7/lib/node_modules/protractor/node_modules/jasminewd2/index.js:101:16
    at [object Object].promise.ControlFlow.runInFrame_ (/home/vagrant/.nvm/versions/node/v0.12.7/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
    at [object Object].goog.defineClass.notify (/home/vagrant/.nvm/versions/node/v0.12.7/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
    at [object Object].promise.Promise.notify_ (/home/vagrant/.nvm/versions/node/v0.12.7/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
    at Array.forEach (native)
    at [object Object].promise.Promise.notifyAll_ (/home/vagrant/.nvm/versions/node/v0.12.7/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
    at goog.async.run.processWorkQueue (/home/vagrant/.nvm/versions/node/v0.12.7/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
    at runMicrotasksCallback (node.js:337:7)
```

Protractor is version 2.5.1

**Comment by bitliner** [comment]
Found the error.

The first instruction for my test is a `beforeAll()`.

This was using an undefined module.

So jasmine was throwing an error, but the throwing was not completing because there is no expected result.

I found it out print the error message before the error message above.

**Comment by shruti-nayak** [comment]
Hi,
Even im facing the same problem when i run the scripts on 'Jenkins',could you say how did you resolve this issue? 

 TypeError: Cannot read property 'addExpectationResult' of undefined
      at Env.fail (C:\Projects\eics.qsg.tests.develop\source\EMCommand.WebSpaTest\node_modules\protractor\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:894:24)
      at Function.next.fail (C:\Projects\eics.qsg.tests.develop\source\EMCommand.WebSpaTest\node_modules\protractor\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1806:19)
      at C:\Projects\eics.qsg.tests.develop\source\EMCommand.WebSpaTest\node_modules\protractor\node_modules\jasminewd2\index.js:101:16
      at [object Object].promise.ControlFlow.runInFrame_ (C:/Projects/eics.qsg.tests.develop/source/EMCommand.WebSpaTest/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
      at [object Object].goog.defineClass.notify (C:/Projects/eics.qsg.tests.develop/source/EMCommand.WebSpaTest/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
      at [object Object].promise.Promise.notify_ (C:/Projects/eics.qsg.tests.develop/source/EMCommand.WebSpaTest/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
      at Array.forEach (native)
      at [object Object].promise.Promise.notifyAll_ (C:/Projects/eics.qsg.tests.develop/source/EMCommand.WebSpaTest/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
      at goog.async.run.processWorkQueue (C:\Projects\eics.qsg.tests.develop\source\EMCommand.WebSpaTest\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:130:15)
      at runMicrotasksCallback (node.js:337:7)

**Comment by shruti-nayak** [comment]
Hi ,
Im a beginner with protractor and typescript.Even im facing the same error when i run the scripts on 'Jenkins'.Could please say how did you solve this issue?below is the error:

 TypeError: Cannot read property 'addExpectationResult' of undefined
      at Env.fail (C:\Projects\eics.qsg.tests.develop\source\EMCommand.WebSpaTest\node_modules\protractor\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:894:24)
      at Function.next.fail (C:\Projects\eics.qsg.tests.develop\source\EMCommand.WebSpaTest\node_modules\protractor\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1806:19)
      at C:\Projects\eics.qsg.tests.develop\source\EMCommand.WebSpaTest\node_modules\protractor\node_modules\jasminewd2\index.js:101:16
      at [object Object].promise.ControlFlow.runInFrame_ (C:/Projects/eics.qsg.tests.develop/source/EMCommand.WebSpaTest/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
      at [object Object].goog.defineClass.notify (C:/Projects/eics.qsg.tests.develop/source/EMCommand.WebSpaTest/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
      at [object Object].promise.Promise.notify_ (C:/Projects/eics.qsg.tests.develop/source/EMCommand.WebSpaTest/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
      at Array.forEach (native)
      at [object Object].promise.Promise.notifyAll_ (C:/Projects/eics.qsg.tests.develop/source/EMCommand.WebSpaTest/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
      at goog.async.run.processWorkQueue (C:\Projects\eics.qsg.tests.develop\source\EMCommand.WebSpaTest\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:130:15)
      at runMicrotasksCallback (node.js:337:7)

**Comment by aleksievelizhanin** [comment]
I have the same issue. Is there any workaround?

**Comment by bitliner** [comment]
Are you sure the app does not have any error in console? Sometimes this error is caused by Angular that fails to bootstrap.

**Comment by aleksievelizhanin** [comment]
there is one exactly this error: 

Running "protractor:functionalSafari" (protractor) task
Verifying property protractor.functionalSafari exists in config...OK
File: [no files]
Options: keepAlive, noColor=false, debug=false, nodeBin="node", args={}, output=false, outputOptions={"flags":"w","defaultEncoding":"utf8","fd":null,"mode":"0o666","autoClose":true}, webdriverManagerUpdate=false, configFile="test/protractor.safari.conf.js"
Before Options: true, false, false, node, [object Object], [object Object]
opts.args: {}
AFTER
Spawn node with arguments: /Users/alekseivelizhanin/Projects/myproject/node_modules/protractor/bin/protractor test/protractor.safari.conf.js --verbose
Report destination:   screenshots/report.html
[11:21:28] I/local - Starting selenium standalone server...
[11:21:28] I/launcher - Running 1 instances of WebDriver
[WS] Catching upgrade event...
[11:21:29] I/local - Selenium standalone server started at http://x.x.x.x:51667/wd/hub
Started
[11:21:33] E/launcher - Cannot read property 'addExpectationResult' of undefined
[11:21:33] E/launcher - TypeError: Cannot read property 'addExpectationResult' of undefined
    at Env.fail (/Users/alekseivelizhanin/Projects/myproject/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:987:24)
    at Function.next.fail (/Users/alekseivelizhanin/Projects/myproject/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1903:19)
    at /Users/alekseivelizhanin/Projects/myproject/node_modules/jasminewd2/index.js:103:16
    at ManagedPromise.invokeCallback_ (/Users/alekseivelizhanin/Projects/myproject/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/Users/alekseivelizhanin/Projects/myproject/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/Users/alekseivelizhanin/Projects/myproject/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at /Users/alekseivelizhanin/Projects/aisti/prototool/node_modules/selenium-webdriver/lib/promise.js:2775:27
    at /Users/alekseivelizhanin/Projects/myproject/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:382:9)
[11:21:33] E/launcher - Process exited with error code 199
>> 
Warning: Tests failed, protractor exited with code: 199 Use --force to continue.

Aborted due to warnings.

**Comment by aleksievelizhanin** [comment]
The error is in the communication with safari browser via SeleniumDriver - it doesn't happen. I changed a little the failing code in jasmine.js to avoid stupid js error https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine.js#L1037-L1045 and now I see that all my functional tests are failing and angular app is started in the first Safary instance, but in the others there are just grey window. Although, there are no errors, nothing that can lead to the actual problem...

**Comment by aleksievelizhanin** [comment]
Finally, found the root of the problem - this is Safary 10 incompatibility with SeleniumDriver 4.x.x as described in https://github.com/angular/protractor/issues/3588 Cure is rollback to Safary 9
