### ISSUE TITLE
Protractor configuration with Grunt

### ISSUE THREAD

**Issue by mynameTT** [angular/protractor#2661]
**Hi, I am running Protractor with Grunt.**

<h2>protractor.config.js</h2>
```javascript
exports.config = {
  directConnect: true,
  seleniumAddress: 'http://localhost:4444/wd/hub',

  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: ['lang=en']
    }
  },
  framework: 'jasmine2',
  rootElement: 'html',
  specs: [

    '../spec/controllers/*.js'
  ],

  onPrepare: function() {
    browser.driver.manage().window().maximize();
    browser.get('http://localhost:9000/#/index.html');
  },
  allScriptsTimeout: 200000,

  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 600000
  }
}
```
<h2>gruntfile.js</h2>
```javascript
protractor: {
      options: {
        keepAlive: true,
        configFile: './test/e2e/config.js',
      },
      auto: {
        options: {
          keepAlive: true,
          args: {
            seleniumPort: 4444,
           baseUrl: 'http://localhost:9000/'
          }
        }
      }
    }
```

**when I execute protractor from grunt, getting below errors**

*<project-path>/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857
      var result = fn();
                   ^
Error: Angular could not be found on the page http://localhost:9000/#/index.html : retries looking for angular exceeded
    at <project-path>\node_modules\protractor\lib\protractor.js:649:17
    at [object Object].promise.ControlFlow.runInFrame_ (<project-path>/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
    at [object Object].goog.defineClass.notify (<project-path>/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
    at [object Object].promise.Promise.notify_ (<project-path>/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
    at Array.forEach (native)
    at [object Object].promise.Promise.notifyAll_ (<project-path>/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
    at goog.async.run.processWorkQueue (<project-path>\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:130:15)
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
[launcher] Process exited with error code 1*

**Comment by sjelin** [comment]
Please ask this kind of question on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor), as per our CONTRIBUTING.md
