### ISSUE TITLE
Console plugin fails with message  : Failure during teardown: Cannot read property 'failOnWarning' of undefined

### ISSUE THREAD

**Issue by dimaxweb** [angular/protractor#2667]
Hello,
Please find the stack trace and configuration bellow 
Failure during teardown:
```
Cannot read property 'failOnWarning' of undefined
		TypeError: Cannot read property 'failOnWarning' of undefined
		    at Function.ConsolePlugin.parseLog (C:\Projects\github\revisor\node_modules\protractor\plugins\console\index.js:86:30)
		    at [object Object].ConsolePlugin.teardown (C:\Projects\github\revisor\node_modules\protractor\plugins\console\index.js:121:24)
		    at safeCallPluginFun (c:\Users\dmitry.mogilko\AppData\Roaming\npm\node_modules\protractor\lib\plugins.js:188:37)
		    at c:\Users\dmitry.mogilko\AppData\Roaming\npm\node_modules\protractor\lib\plugins.js:223:23
		    at Array.forEach (native)
		    at [object Object].teardown (c:\Users\dmitry.mogilko\AppData\Roaming\npm\node_modules\protractor\lib\plugins.js:221:21)
		    at c:\Users\dmitry.mogilko\AppData\Roaming\npm\node_modules\protractor\lib\runner.js:340:20
		    at _fulfilled (c:\Users\dmitry.mogilko\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:797:54)
		    at self.promiseDispatch.done (c:\Users\dmitry.mogilko\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:826:30)
		    at Promise.promise.promiseDispatch (c:\Users\dmitry.mogilko\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:759:13)
```
Protractor configuration 
```js
/**
 * Created by Dmitry.Mogilko on 11/1/2015.
 */



exports.config = {
    "seleniumAddress ": "http://localhost:4444/wd/hub",
    "specs": ["test/logic/genericTest.spec.js"],
    "multiCapabilities": [
        {
            "browserName": "chrome"
        }

    ],
    "jasmineNodeOpts": {
        "showColors": true,
        "defaultTimeoutInterval": 300000
    },

    plugins: [{
        path: 'node_modules/protractor/plugins/console',
        failOnError:true,
        exclude: []
    }],


    "framework": "jasmine2"

}
```
It looks like something with config is undefined in plugin but it is hard for me to configure why ...
Thanks

**Comment by sjelin** [comment]
Could you run `protractor --version` and `./node_modules/protractor/bin/protractor --version` for me, and tell me what they say?

**Comment by dimaxweb** [comment]
Thanks for pointing to the problem , I have different versions of protractor installed globally and locally
protractor --version   : 2.5.1
./node_modules/protractor/bin/protractor --version  :2.1.0

Instaling 2.5.1 fixed the issue

**Comment by sjelin** [comment]
Yeah, plugins were in beta in 2.1 and 2.2 was a breaking change for the plugin API

**Comment by padmarajnidagundi** [comment]
@sjelin I have Version 5.4.1  protractor --version and ./node_modules/protractor/bin/protractor --version And I got " E/plugins - Failure during teardown: unknown error: Cannot read property 'collectIdRefs' of null"

Will you suggest me any solution.
