### ISSUE TITLE
 NoSuchElementError: No element found using locator: By.xpath

### ISSUE THREAD

**Issue by vinayk335194** [angular/protractor#2688]
i am newbie for protractor ,i could not execute element(by.xapth()) for a angular js app. please provide possible solution for this..i tried using browser.wait also but its acting in same way 

 browser.ignoreSynchronization = true; 
     browser.waitForAngular();
     element(by.xpath('/html/body/rc-app-template/header/div/div/div[3]/ul/li[2]/a')).click();

**Comment by vinayk335194** [comment]
Its working fine when I use same xpath with my selenium script ..

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by abhishekvats** [comment]
Hi,
Failures:
1) angularjs homepage todo list should add a todo
  Message:
    Failed: No element found using locator: By(css selector, .remind)
  Stack:
    NoSuchElementError: No element found using locator: By(css selector, .remind)
        at WebDriverError (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:5)
        at NoSuchElementError (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:168:5)
        at elementArrayFinder.getWebElements.then (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\lib\element.ts:851:17)
        at ManagedPromise.invokeCallback_ (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1366:14)
        at TaskQueue.execute_ (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
        at asyncRun (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2813:27)
        at C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)Error
        at ElementArrayFinder.applyAction_ (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\lib\element.ts:482:23)
        at ElementArrayFinder.(anonymous function) [as click] (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\lib\element.ts:96:21)
        at ElementFinder.(anonymous function) [as click] (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\lib\element.ts:873:14)
        at C:\Users\Mechlin Technologies\Desktop\Protractor\todo-spec.js:46:28
        at ManagedPromise.invokeCallback_ (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1366:14)
        at TaskQueue.execute_ (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
        at asyncRun (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2813:27)
        at C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From: Task: <anonymous>
        at pollCondition (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2101:19)
        at C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2097:7
        at new ManagedPromise (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1067:7)
        at ControlFlow.promise (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2396:12)
        at C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2096:22
        at TaskQueue.execute_ (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
        at asyncRun (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2813:27)
        at C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From: Task: <anonymous wait>
        at scheduleWait (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2094:20)
        at ControlFlow.wait (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2408:12)
        at thenableWebDriverProxy.wait (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:943:29)
        at run (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\lib\browser.ts:66:27)
        at ProtractorBrowser.to.(anonymous function) [as wait] (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\lib\browser.ts:74:12)
        at Object.<anonymous> (C:\Users\Mechlin Technologies\Desktop\Protractor\todo-spec.js:21:9)
        at C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:110:25
        at new ManagedPromise (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1067:7)
        at ControlFlow.promise (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2396:12)
        at schedulerExecute (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
    From: Task: Run it("should add a todo") in control flow
        at Object.<anonymous> (C:\Users\Mechlin Technologies\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    From asynchronous test:
    Error
        at Suite.<anonymous> (C:\Users\Mechlin Technologies\Desktop\Protractor\todo-spec.js:3:3)
        at Object.<anonymous> (C:\Users\Mechlin Technologies\Desktop\Protractor\todo-spec.js:2:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)

1 spec, 1 failure
Finished in 42.8 seconds

[17:32:49] I/launcher - 0 instance(s) of WebDriver still running
[17:32:49] I/launcher - chrome #01 failed 1 test(s)
[17:32:49] I/launcher - overall: 1 failed spec(s)
[17:32:49] E/launcher - Process exited with error code 1
