### ISSUE TITLE
issue with webdriver upgrade in Protractor 3.0 -- (undefined:1190     vlog(2, () => this + ' scheduling notifications', this);)

### ISSUE THREAD

**Issue by cstraynor** [angular/protractor#2726]
Upgraded to Protractor 3.0 and now I receive the below error every time the tests try to run.

> $ protractor

[launcher] Process exited with error code 1
undefined:1190
    vlog(2, () => this + ' scheduling notifications', this);
             ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/Users/christraynor/Documents/BitBucket/Angular2-seed/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/Users/christraynor/Documents/BitBucket/Angular2-seed/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /Users/christraynor/Documents/BitBucket/Angular2-seed/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Object.Context.closure.goog.retrieveAndExecModule_ (/Users/christraynor/Documents/BitBucket/Angular2-seed/node_modules/protractor/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/Users/christraynor/Documents/BitBucket/Angular2-seed/node_modules/protractor/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/Users/christraynor/Documents/BitBucket/Angular2-seed/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/Users/christraynor/Documents/BitBucket/Angular2-seed/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
npm ERR! Test failed.  See above for more details.

**Comment by sjelin** [comment]
Protractor 3.0 is only compatible with node 4.0+

**Comment by cstraynor** [comment]
Good to know. Thanks!
