### ISSUE TITLE
Bug: bug when started

### ISSUE THREAD

**Issue by marioidival** [angular/protractor#2731]
```
Waiting for test server and webdriver server to start
Starting selenium server
seleniumProcess.pid: 217
03:39:52.085 INFO - Launching a standalone Selenium Server
Setting system property webdriver.chrome.driver to /app/heroku/ruby/node-0.12.7/lib/node_modules/protractor/selenium/chromedriver
03:39:52.154 INFO - Java: Oracle Corporation 24.79-b02
03:39:52.157 INFO - OS: Linux 4.1.10-boot2docker amd64
03:39:52.182 INFO - v2.48.0, with Core v2.48.0. Built from revision 41bccdd
03:39:52.318 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match the current platform LINUX
03:39:52.327 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{platform=WINDOWS, browserName=MicrosoftEdge, version=}] does not match the current platform LINUX
03:39:52.330 INFO - Driver class not found: com.opera.core.systems.OperaDriver
03:39:52.331 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
03:39:52.445 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
03:39:52.447 INFO - Selenium Server is up and running
[launcher] Process exited with error code 1
undefined:1190
    vlog(2, () => this + ' scheduling notifications', this);
             ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/app/heroku/ruby/node-0.12.7/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/app/heroku/ruby/node-0.12.7/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /app/heroku/ruby/node-0.12.7/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Object.Context.closure.goog.retrieveAndExecModule_ (/app/heroku/ruby/node-0.12.7/lib/node_modules/protractor/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/app/heroku/ruby/node-0.12.7/lib/node_modules/protractor/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/app/heroku/ruby/node-0.12.7/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/app/heroku/ruby/node-0.12.7/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:900:14)

```

**Comment by tophercf** [comment]
Hi, I had a similar problem when running protractor with nodejs version 0.12.7. I tried installing a previous release of protractor (2.5.1) and the issue was resolved. Hope this helps!

**Comment by marioidival** [comment]
Also, I had configured my protractor.config.js file to use phantomjs, but is not used..

**Comment by craigsnyders** [comment]
selenium-webdriver needs to be started with the --harmony flag
https://github.com/SeleniumHQ/selenium/issues/1286

**Comment by NickTomlin** [comment]
Protractor `3.x.x` no longer supports node < 4.2

> BREAKING CHANGE: 1) Users will no longer be able to use node versions <4. 2)

You'll need to keep using the `2.x.x` version of protractor or upgrade the version of node you are using.

**Comment by yossi-shasho** [comment]
running `$ n stable` to update node solved it for me

**Comment by 61ue5peed** [comment]
Exactly what solved it for me to have protractor 3, Updated my 0.12 node to 5.4..

**Comment by SudheerDotNetDev** [comment]
Updating NodejS e helped me.

**Comment by MilknCookie** [comment]
I have this issue with : 
 node -v  = v5.7.0
protractor --version = 3.1.1

**Comment by 61ue5peed** [comment]
What yossi-shasho said have you tired that?

**Comment by MilknCookie** [comment]
i have the very last Version of node stable. It's a windows Server 2008 also.

**Comment by MilknCookie** [comment]
I found the problem and it was purely my bad. There was an old node.exe in the project. Deleting it made sure it was using the one.

**Comment by yossi-shasho** [comment]
@MilknCookie I can't seem to find it, where is it?

**Comment by MilknCookie** [comment]
@yossi-shasho It was probably drop by accident by me

**Comment by yossi-shasho** [comment]
@MilknCookie oh i though you meant that its in the `protractor` project itself
