### ISSUE TITLE
$("option").getText() does not remove leading and trailing whitespace

### ISSUE THREAD

**Issue by radek-holy** [angular/protractor#2759]
Reproducer:
protractor@3.0.0
```javascript
var url = "http://127.0.0.1/";
describe("", function () {
    it("", function () {
        browser.get(url);
        expect($("option").getText()).toEqual("test");
    });
});
```
```html
<!DOCTYPE html>
<html ng-app="plunker">

<head>
  <meta charset="utf-8" />
  <title>AngularJS Plunker</title>
  <script>
    document.write('<base href="' + document.location + '" />');
  </script>
  <script data-require="angular.js@1.4.x" src="https://code.angularjs.org/1.4.8/angular.js" data-semver="1.4.8"></script>
  <script src="app.js"></script>
</head>

<body ng-controller="MainCtrl">
  <select>
    <option> test </option>
  </select>
</body>

</html>
```
```javascript
var app = angular.module('plunker', []);
app.controller('MainCtrl', function($scope) {
});
```
Actual result:
```console
$ ./node_modules/.bin/protractor 
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.8.104:47480/wd/hub
Started
F

Failures:
1)  
  Message:
    Expected ' test ' to equal 'test'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/tmp/protractor/spec.js:6:39)
        at process._tickCallback (node.js:356:9)

1 spec, 1 failure
Finished in 4.334 seconds
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```
Expected result: the test passes
(I am not sure whether it is actually a bug in Selenium but since `getText` is documented as Protractor's API, I'm reporting it here.)

**Comment by juliemr** [comment]
You're right, this is not what selenium/webdriver should do according to the spec: http://www.w3.org/TR/webdriver/#getelementtext

You don't mention which browser you're seeing this error on, but it's probably an issue with that browser's webdriver implementation.

**Comment by radek-holy** [comment]
@juliemr, I'm seeing it on Chromium 46.0.2490.71 and 46.0.2490.86. You are right that it's specific to the browser, Firefox works fine.

**Comment by juliemr** [comment]
Thanks! I searched and there is an open issue with chromium: https://bugs.chromium.org/p/chromedriver/issues/detail?id=822&q=whitespace&colspec=ID%20Status%20Pri%20Owner%20Summary

Please follow along there!

**Comment by radek-holy** [comment]
Oh, I quickly skimmed through Selenium bugs but I forgot to take a look at Chromium bugs when it turned out that the bug is there. Sorry for that and thank you. I'll follow that.

**Comment by juliemr** [comment]
No problem, there's a lot of projects involved and stuff is hard to find.
