### ISSUE TITLE
Error when running protractor... node_modules/q/q.js:126

### ISSUE THREAD

**Issue by Narven** [angular/protractor#2775]
when running `protractor test/protractor/protractor-conf.js` i get:

```
[launcher] Process exited with error code 1

/usr/lib/node_modules/protractor/node_modules/q/q.js:126
                    throw e;
                          ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.Context.closure.goog.retrieveAndExecModule_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
    at Object.goog.writeScripts_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1323:16)
    at Object.goog.require (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:663:14)
```

on `Ubuntu 15.10` with `protractor 3.0.0` (latest) and `selenium 2.48` (latest), already cleared npm cache, instaled diferent versions of protractor.. but always the same thing. also checked permissions on node_modules folder.

any help? thanks

**Comment by Xotabu4** [comment]
@Narven could you please also share your config file?

**Comment by Narven** [comment]
```
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    directConnect: true,
    specs: [
        'spec/*-spec.js'
    ],
    baseUrl: 'http://localhost:9002',
    allScriptsTimeout: 100000,
    getPageTimeout: 1000000,
    seleniumPort: 4444,
    shardTestFiles: true,
    params: {
       config: {
           host: 'http://localhost:9002'
       }
    },
    multiCapabilities: [
        {
            'browserName': 'chrome'
        }
    ],
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 30000,
        isVerbose: true
    },

    framework: 'jasmine'
};
```

**Comment by NickTomlin** [comment]
A few questions: 
- What version of node are you running? 
- Are you able to successfully clone down and run the protractor [example] (https://github.com/angular/protractor/tree/master/example)?

**Comment by sgrant613** [comment]
Same issue here and also occurs on clone of repo....

**Comment by sgrant613** [comment]
An update to latest Node (4.2.3) fixed this for me

**Comment by NickTomlin** [comment]
What version of node were you using?

**Comment by Narven** [comment]
Currently i cannot say which version of npm im using, because im not in that machine right now.

im testing now on a mac with `npm --version 2.14.7` and it runs ok.

only tomorrow i can check which version of npm im running on ubuntu.

**Comment by Narven** [comment]
node --version is v4.2.1

**Comment by sjelin** [comment]
Can you run the  [example](https://github.com/angular/protractor/tree/master/example)?

**Comment by sgrant613** [comment]
I'm not 100 percent sure - is there anyway to look at an installed version history?  Or is there a way to rollback the dmg install?

**Comment by sgrant613** [comment]
Example is good now for me.

**Comment by sjelin** [comment]
@Narven what about you?  Can you run the example?

**Comment by sgrant613** [comment]
Found it  -  v0.10.20 installed on 10/17/13

**Comment by NickTomlin** [comment]
@sgrant613 Protractor 3 requires Node > 4 so this makes sense if you were previously using `v0.10.20`

@Narven it sounds like you might be experiencing a similar issue if it is working on your mac running node `4.x`

**Comment by Narven** [comment]
it seams that i was running an old old old old oldie old oldie version of nodejs `v0.10.37`. Updated it to `v4.2.3`. Protractor now works. thanks

**Comment by NickTomlin** [comment]
@Narven great, glad to hear it worked out. Would you mind closing the issue? Thanks!

**Comment by SaiUpadhyayula** [comment]
I am facing the same error, using the latest node version - v5.4.1 and npm version - 3.5.3


```
> [plm@siplmapp01 INT static]$ node_modules/grunt-cli/bin/grunt e2e-test
> >> Local Npm module "grunt-contrib-qunit" not found. Is it installed?
> 
> Running "protractor_webdriver:modules" (protractor_webdriver) task
> Starting Selenium server
> Shutting down Selenium server: http://localhost:4444
> Shut down Selenium server: http://localhost:4444 (OKOK)
> Restarting Selenium server
> Restarted Selenium server: http://127.0.0.1:4444
> 
> Running "protractor:modules" (protractor) task
> [launcher] Process exited with error code 1
> 
> /data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/q/q.js:155
>                 throw e;
>                       ^
> SyntaxError: Unexpected token )
>     at goog.loadModuleFromSource_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
>     at Object.goog.loadModule (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
>     at /data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
>     at Object.Context.closure.goog.retrieveAndExecModule_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/_base.js:135:8)
>     at <anonymous>:1:6
>     at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/_base.js:104:12)
>     at Object.goog.importScript_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
>     at Object.goog.importModule_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
>     at Object.goog.writeScripts_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:1323:16)
>     at Object.goog.require (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:663:14)
> >> /data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/q/q.js:155
> >>                 throw e;
> >>                       ^
> >> SyntaxError: Unexpected token )
> >>     at goog.loadModuleFromSource_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
> >>     at Object.goog.loadModule (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
> >>     at /data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
> >>     at Object.Context.closure.goog.retrieveAndExecModule_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/_base.js:135:8)
> >>     at <anonymous>:1:6
> >>     at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/_base.js:104:12)
> >>     at Object.goog.importScript_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
> >>     at Object.goog.importModule_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
> >>     at Object.goog.writeScripts_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:1323:16)
> >>     at Object.goog.require (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:663:14)
> Warning: Tests failed, protractor exited with code: 8 Use --force to continue.
> 
> Aborted due to warnings.
```

The protractor configuration file

```
var AllureReporter = require('jasmine-allure-reporter');
//var HTMLReporter = require('protractor-jasmine2-screenshot-reporter');

exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
//Specs to run individual tests.
    specs: ['../tests/unit/sandbox-spec.js'],
// To run tests as part of the suites.
    suites: {
        intro: ['../tests/unit/login-spec.js','../tests/unit/plm02TabChecks-spec.js','../tests/unit/sandbox-spec.js'],
        e2e: ['../tests/unit/checkBaseline-spec.js','../tests/unit/plm02-spec.js'],
        smoke: ['../tests/e2e/smoke-tests/baselineSchedule-spec.js','../tests/e2e/smoke-tests/validateBaseline-spec.js'],
        sandbox: ['../tests/e2e/smoke-tests/validateBaseline-spec.js']
    },

    capabilities: {
        'browserName': 'phantomjs',
        //For Server
        //'phantomjs.binary.path':'node_modules/phantomjs-prebuilt/bin/phantomjs'

        // For Local Use
        'phantomjs.binary.path':'C:/Users/taaupsa1/Downloads/phantomjs-2.1.1-windows/phantomjs-2.1.1-windows/bin/phantomjs.exe'
    },

    framework:'jasmine2',
    onPrepare: function() {
        // implicit and page load timeouts
        browser.manage().timeouts().pageLoadTimeout(40000);
        browser.manage().timeouts().implicitlyWait(25000);
        browser.manage().window().setSize(1600, 1000);
// for non-angular page
    browser.ignoreSynchronization = true;

//        jasmine.getEnv().addReporter(new HTMLReporter({
//            dest: '../screenshots',
//            filename: 'my-report.html'
//        }));
            
    jasmine.getEnv().addReporter(new AllureReporter({
      allureReport: {
        resultsDir: 'allure-results'
      }
    }));
    }
};
```

I am able to run this in my local machine but in my Build Server I am facing the error. I am using a local npm and node installation which was done through maven-front-end tools plugin.

Could any one help please?

**Comment by NickTomlin** [comment]
@SaiUpadhyayula are you sure you are actually running node 5.x? If you are still experiencing an issue please open a new one.
