### ISSUE TITLE
Can't run on ubuntu 14.04 , protactor version 3.0.0

### ISSUE THREAD

**Issue by noruya** [angular/protractor#2791]
[launcher] Process exited with error code 1

/usr/lib/node_modules/protractor/node_modules/q/q.js:126
                    throw e;
                          ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.Context.closure.goog.retrieveAndExecModule_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
    at Object.goog.writeScripts_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1323:16)
    at Object.goog.require (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:663:14)

**Comment by sjelin** [comment]
This sort of debugging/support question is much better suited for [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) (see our [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md)).  But in this case I think the issue is that Protractor 3.0 is only compatible with node 4+
