### ISSUE TITLE
Switching to frame failing with Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by bmsoko** [angular/protractor#2798]
Hello ALL!
I'm getting the error on version 3.0.0, I'm using Protractor + CucumberJS, I'm also using `gulp-protractor` and I had implemeted CucumberJS as custom, as per new changes.

```javascript
"error_message": "RangeError: Maximum call stack size exceeded\n    
at Object.goog.array.peek (/Users/brunosoko/Folder/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/array/array.js:68:15)\n    
at Object.promise.ControlFlow.goog.defineClass.goog.defineClass.promise.controlFlow (/Users/brunosoko/Folder/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2938:14)\n    
at promise.Promise.goog.defineClass.constructor (/Users/brunosoko/Folder/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1024:38)\n    
at new wrappedCtr (/Users/brunosoko/Folder/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:2468:26)\n    
at promise.Deferred.goog.defineClass.constructor (/Users/brunosoko/Folder/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1371:20)\n    
at new wrappedCtr (/Users/brunosoko/Folder/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:2468:26)\n    
at Object.promise.defer (/Users/brunosoko/Folder/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1501:10)\n    
at convertKeys (/Users/brunosoko/Folder/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:236:34)\n    
at convertValue (/Users/brunosoko/Folder/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:218:16)\n    
at /Users/brunosoko/Folder/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:252:32"
```
Here's what I'm doing on my test:

```javascript
    this.Then(/^I see the uploader is shown$/, function(done){
        //browser.wait(EC.visibilityOf(uploaderPage.btnFacebook));
        browser.switchTo().frame(uploaderPage.frame);
        browser.executeScript()
        expect(uploaderPage.container.isDisplayed()).to.eventually.be.true;
        expect(uploaderPage.btnFacebook.isDisplayed()).to.eventually.be.true;
        expect(uploaderPage.btnFlickr.isDisplayed()).to.eventually.be.true;
        expect(uploaderPage.btnHardDrive.isDisplayed()).to.eventually.be.true;
        expect(uploaderPage.btnInstagram.isDisplayed()).to.eventually.be.true;
        expect(uploaderPage.btnYouTube.isDisplayed()).to.eventually.be.true;
        uploaderPage.btnFacebook.click();
        done();
    });
```

And my `uploader.frame` looks like:
```javascript
this.frame                = $('#v1iframe');
```

Is this an issue with both versions? or is there something I'm doing wrong?

Thanks

**Comment by NickTomlin** [comment]
Is this still an issue?

I'd be happy to help debug but i'm not a cucumber user (or that familiar with cucumber). Would you mean creating a sample repo that we can collaborate on?

**Comment by juliemr** [comment]
Closing as stale.
