### ISSUE TITLE
Protractor 2.5.1     ReferenceError: testFn is not defined

### ISSUE THREAD

**Issue by formarfr** [angular/protractor#2799]
Hello, 

I recently upgraded to protractor 2.5.1 and all of my tests are now failing. I suspect it is something to do with Jasmine but I'm not sure how to fix. Any help would be appreciated, thank you in advance.
Here is the error I receive:

Should login successfully
  Message:
    ReferenceError: testFn is not defined
  Stack:
    ReferenceError: testFn is not defined
        at Object.<anonymous> (c:\GlobalSeedField\Gsfm_Web\EndToEnd.Tests\node_modules\jasminewd2\index.js:81:16)
        at attemptAsync (c:\GlobalSeedField\Gsfm_Web\EndToEnd.Tests\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1809:24)
        at QueueRunner.run (c:\GlobalSeedField\Gsfm_Web\EndToEnd.Tests\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1764:9)
        at QueueRunner.execute (c:\GlobalSeedField\Gsfm_Web\EndToEnd.Tests\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1753:10)
        at queueRunnerFactory (c:\GlobalSeedField\Gsfm_Web\EndToEnd.Tests\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:614:35)
        at Object.fn (c:\GlobalSeedField\Gsfm_Web\EndToEnd.Tests\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:2338:13)
        at attemptAsync (c:\GlobalSeedField\Gsfm_Web\EndToEnd.Tests\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1809:24)
        at QueueRunner.run (c:\GlobalSeedField\Gsfm_Web\EndToEnd.Tests\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1764:9)
        at QueueRunner.execute (c:\GlobalSeedField\Gsfm_Web\EndToEnd.Tests\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1753:10)
        at queueRunnerFactory (c:\GlobalSeedField\Gsfm_Web\EndToEnd.Tests\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:614:35)

Here is my test, however the browser never navigates to the baseUrl.

import {Login} from "./Login";

describe("Login", () => {

    beforeAll(() => {
        browser.get(browser.baseUrl);
    });

    it("Should login successfully", () => {
        Log.login(browser.params.login.username, browser.params.login.password);
        expect(browser.getLocationAbsUrl()).toBe("/");
    });
});

**Comment by NickTomlin** [comment]
Hi there!

Because your question is about debugging and usage, it is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by formarfr** [comment]
Thanks Nick, 

Closing here.  Link to posted StackOverflow question: https://stackoverflow.com/questions/34437943/protractor-2-5-1-referenceerror-testfn-is-not-defined
