### ISSUE TITLE
protractor not running

### ISSUE THREAD

**Issue by kishanmundha** [angular/protractor#2818]
We I run comannd `protractor conf.js` it return error

```
[launcher] Process exited with error code 1
undefined:1190
    vlog(2, () => this + ' scheduling notifications', this);
             ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (C:\Users\Mundha\AppData\Roaming\npm\node_modu
les\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1123:19)
    at Object.goog.loadModule (C:\Users\Mundha\AppData\Roaming\npm\node_modules\
protractor\node_modules\selenium-webdriver\lib\goog\base.js:1085:46)
    at C:\Users\Mundha\AppData\Roaming\npm\node_modules\protractor\node_modules\
selenium-webdriver\lib\webdriver\promise.js:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Object.Context.closure.goog.retrieveAndExecModule_ (C:\Users\Mundha\AppDa
ta\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\_base.js:
135:8)
    at <anonymous>:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (C:\Users\
Mundha\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriv
er\_base.js:104:12)
    at Object.goog.importScript_ (C:\Users\Mundha\AppData\Roaming\npm\node_modul
es\protractor\node_modules\selenium-webdriver\lib\goog\base.js:879:9)
    at Object.goog.importModule_ (C:\Users\Mundha\AppData\Roaming\npm\node_modul
es\protractor\node_modules\selenium-webdriver\lib\goog\base.js:900:14)
```

I am not able to run e2e testing using this tool

**Comment by NickTomlin** [comment]
What version of node are you running? 

Protractor `3.x` is [compatible with node 4+](https://github.com/angular/protractor#compatibility), this error is typically thrown when running protractor with a node version less than 4. You should either upgrade the version of node you are using or use protractor `2.5.x`.
