### ISSUE TITLE
Protractor doesn't support angular synchronization on iOS

### ISSUE THREAD

**Issue by barmy-tester** [angular/protractor#2840]
This issue is similar to https://github.com/angular/protractor/issues/1736

I cannot run my tests on iOS real device using appium and protractor. Tests fail each time with following errror: 'ERROR running appium command: Cannot assign to read only property X of true' where X is 'random' digit.
I've tried many configuration varieties, etc. and still got the same error.
The only workaround is to turn of synchronization by adding ignoreSynchronization=true to my tests. But with such workaround there is no point to use protractor anymore.

Here are instructions to integrate iOS with Safari, Appium and protractor:

- git clone appium
- intialize appium by running:
> ./reset.sh --ios --real-safari --profile '34e19aa1-xxxx-xxxx-xxxx-xxxxxxxxx' --verbose
- run webproxy:
> ./bin/ios-webkit-debug-proxy-launcher.js -cXXXXXXXXXXXXXXX -d
- start appium server:
> node lib/server/main.js -U XXXXXXXXXXXXXXXXXXXXXXXXXXX
- run test by executing:
> protractor test.conf.js

You can find test.conf.js, appium console output and protractor console output in attached.
I've also tried to run tests with selenium grid by registering iOS node and the result was the same

Versions:
- OSX El Capitan, 10.11.12
- Xcode 7.2
- Appium 1.4.16
- Protractor 3.0.0
- node 5.4.0
- npm 3.3.12
- DUT iOS version 9.2

If you need any additional information please let me know.

[appium_output.txt](https://github.com/angular/protractor/files/90297/appium_output.txt)
[protractor_output.txt](https://github.com/angular/protractor/files/90299/protractor_output.txt)
[test.conf.js.txt](https://github.com/angular/protractor/files/90300/test.conf.js.txt)

**Comment by juliemr** [comment]
Assigning to @sjelin - we're hoping to refresh mobile docs/setup soon.

**Comment by ivarcegeka** [comment]
I have the same problem. I have a simple cordova application and some simple tests. The tests work perfectly in the browser and on Android, but in iOS I get the error: 'Failed: ERROR running Appium command: Cannot assign to read only property '1' of true'. I will attach the protractor config and the test. 
I'm starting appium from the Appium.app. The only setting I changed from the default settings is that I checked 'use native instruments'.

Am I doing something wrong or is this a bug?

[protractor-ios.config.txt](https://github.com/angular/protractor/files/150796/protractor-ios.config.txt)
[uitest.spec.txt](https://github.com/angular/protractor/files/150801/uitest.spec.txt)
[appium_log.txt](https://github.com/angular/protractor/files/150808/appium_log.txt)
[protractor_log.txt](https://github.com/angular/protractor/files/150809/protractor_log.txt)

**Comment by wswebcreation** [comment]
Did you got this working on iOS simulator? 
We faced the same problem, but in our opinion it's more a Appium issue then a Protractor issue. It looks like the `returnedFromExecuteAtom` is forcing a 'stop for alerts'. `appium/lib/devices/ios/ios-controller.js:692`

We are looking into it further

**Comment by ivarcegeka** [comment]
Nope, not yet.

**Comment by ivarcegeka** [comment]
I upgraded my Appium version to 1.5 (from 1.4.13) and now I don't get those errors anymore. I get different errors though. It seems as if the click doesn't work, but that is a different problem.

**Comment by premkh9** [comment]
I am using Appium 1.4.13 and Xcode 7.2 but I am not able to execute any of my tests in IOS simulator. Issue persists in Sauce labs emulator as well

Job Details - https://saucelabs.com/beta/tests/f3bb551a0daf4f5d9d867b71e9b29657
multiCapabilities: [{
'browserName': 'Safari',
'appium-version': '1.4.13',
platformName: 'iOS',
platformVersion: '9.2',
deviceName: 'iPhone 6 Plus',
'name': 'Protractor Job',

**Comment by teddyhwang** [comment]
I'm wondering if this is the issue: https://discuss.appium.io/t/protractor-safari-tests-broken-on-ios-9/7354

**Comment by premkh9** [comment]
any resolution to resolve the issue

**Comment by sjelin** [comment]
Yeah, I'm working on it.  Hopefully I'll have something in next week, but we'll see.

**Comment by premkh9** [comment]
Hi Sjelin, Hope you are doing good ! Did you get a chance to look into the issue?

**Comment by sjelin** [comment]
I did!  I got wrapped up in other things though.  Hopefully before the end of this week I'll have something for you :smile:

**Comment by barmy-tester** [comment]
Any news?

**Comment by premkh9** [comment]
Hi Sjelin, any updates? Its really holding our IOS automation... Earliest fix on this would be much more appreciated !!

**Comment by luker2** [comment]
Our team is also looking for any update! The BrowserStack emulator seems to have the same issue as well.

**Comment by aluzardo** [comment]
We have the same problem. We were able to run test on iOS 8 but when we updated to iOS 9 the test don't run. 

Only run if `browser.ignoreSynchronization = true;`

**Comment by valburyakov** [comment]
I have the simillar issue when running protractor(v 4.0.8) tests on IOS 9.3 (either Emulator or Real device), Ionic2 Hybrid app with Angular2. In protractor.conf _useAllAngular2AppRoots: true_ 
After first load and clicking on submit button, appium hangs with message:
[RemoteDebugger] Received applicationSentData response
[RemoteDebugger] Got a blank data response from debugger

On Real device another behaviour, there is no hanging but some clicks on elements won't work.

[appium-log.txt](https://github.com/angular/protractor/files/486891/appium-log.txt)

**Comment by knreddy036** [comment]
Is anyone able to launch safari browser on real iOS devices with protractor

**Comment by sjelin** [comment]
Hey guys, sorry for the lack of updates.  I'm not entirely sure what I was talking about in https://github.com/angular/protractor/issues/2840#issuecomment-197036238 but support for iOS an mobile in general has improved a lot.  Maybe https://github.com/angular/protractor/pull/3326 will address your problems but probably not to be honest.  I'll see if I can dig into this next week.

**Comment by wswebcreation** [comment]
I currently use protractor and iOS Safari in 3 different combinations and it works:

- appium + iOS 10.2 simulator + Safari
- Saucelabs + iOS 10.2 simulator + Safari
- Perfecto + (iPhone 5C / iPhone 6S / iPhone 7) + Safari

The first 2 are simulators, Perfecto has physical devices

@sjelin, if you need help with this I can maybe help to debug it if there are problems

**Comment by sjelin** [comment]
@wswebcreation thanks for the offer!  I'll let you know

**Comment by luiscspinho** [comment]
Hello,
I just faced this problem. I'm trying to automate Safari with iOS 10.0.1 using Appium and Protractor.
I've everything working just fine if I do something like this:

```
browser.ignoreSynchronization = true;
browser.get('https://myAngularPage.com');
browser.wait(protractor.until.elementLocated(by.css('.class')), 5000);
element.click()
```

However, since I've an angular page I should not need to ignoreSync and wait for the element to be visible to click on him. I've this working on Android/Chrome without the ignoreSync and the wait until element located. However, if i don't add the ignoreSynch before the browser get, the website will be stuck on the bootstrap throwing the "angular never provided resumebootstrap" with just the "browser.get()" code on my test.

Is this the same issue that angular and iOS/Safari are not yet supported?

**Comment by sjelin** [comment]
It's still not fully supported, no.  Unfortunately, I was in charge of mobile support and I was just transferred to another team, so support may be a long time coming.  There are some good resources online though

**Comment by jlin412** [comment]
It's funny.  I have it worked in iOS but not in Android.  Just opposite of your problem.

**Comment by reppners** [comment]
Trying to get tests to run in mobile safari with Appium / iOS simulator / 10.3 but also getting `angular never provided resumeBootstrap`.

Safari 10.1 on macOS Sierra seems to be working with this workaround but would throw the same error otherwise.
```
// TODO workaround for https://github.com/angular/protractor/issues/4004
if (navigator.webdriver) {
    window.name = "NG_DEFER_BOOTSTRAP!" + window.name;
}
```

**Comment by FreshQa** [comment]
Any updates on this? Kind of embarrassing that not only all Safari 10 versions but also now Safari 11 has no resolve. I hated Apple since it came out in the 80's, to no surprise to me, Apple doesn't seem to offer the much needed support for their lame products.

**Comment by BorntraegerMarc** [comment]
@sjelin does this issue present itself only when combined with appium or also if the "normal" iOS safari driver is used?

**Comment by wswebcreation** [comment]
@BorntraegerMarc 

What do you exactly mean? the iOS safari driver is used by Appium (?)

**Comment by BorntraegerMarc** [comment]
@wswebcreation I mean writing protractor tests without appium 😄 just protractor tests for a angular website...

**Comment by FreshQa** [comment]
Safari 10.3 & 11.0 do not work with Protractor, however on Sierra macOS  running Safari 11.0.1 does. Just turn off synchronization right before your first browser.get call and immediately turn it back on following that first call, then you're good to go.

**Comment by wswebcreation** [comment]
@FreshQa 

Tnx for your answer / workaround, will also try it.

**Comment by first87** [comment]
Can anyone help me with the following error?
```
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ tsc -p e2e/tsconfig.e2e.json && protractor e2e/build/protractor.config.js
[06:26:44] W/driverProviders - Using driver provider hosted, but also found extra driver provider parameter(s): browserstackUser, browserstackKey
[06:26:44] I/launcher - Running 1 instances of WebDriver
[06:26:44] I/hosted - Using the selenium server at http://hub-cloud.browserstack.com/wd/hub
[06:27:00] W/runner - Ignoring unknown extra flags: target. This will be an error in future versions, please use --disableChecks flag to disable the  Protractor CLI flag checks.
...
Error: Error while running testForAngular: Unable to communicate to node
    at executeAsyncScript_.then (/home/workspace/project/node_modules/protractor/lib/browser.ts:945:27)
    at ManagedPromise.invokeCallback_ (/home/workspace/project/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/home/workspace/project/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/home/workspace/project/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/home/workspace/project/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /home/workspace/project/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)
[ERROR] Error: Error: Error while running testForAngular: Unable to communicate to node
    at /home/workspace/project/e2e/build/specs/home.spec.js:17:19
    at process._tickCallback (internal/process/next_tick.js:109:7)
[05:43:16] E/launcher - Process exited with error code 1
```
* Protractor: v5.1.2
* Protractor configuration: 
    ```
    seleniumAddress: 'http://hub-cloud.browserstack.com/wd/hub',
    baseUrl: 'http://localhost:5001',
    ...
    capabilities: {
        'name': 'Safari on iPhone',
        'device': 'iPhone 7 Plus',
        'realMobile': 'true',
        'os': 'ios',
        'os_version': '10.3',
        'browserName': 'iPhone',
        'browserstack.local': true,
        'browserstack.debug': true
    }
    ```

**Comment by swaraj10** [comment]
I am trying to run protractor test(ios-11, iPhoneX)in browserstack. I am getting "Error: Error while running testForAngular: Unable to communicate to node" error and some time i will get "Could not find Angular on page" but in fact this is angular application and i can run test on android and in all desktop browsers. my config file is below, when i used browser.ignoreSynchronization = 'true' before the browser.get() than the tests will pass on iOS 10.3 but as i am testing the angular application and i don't want to use it. Can you please help on this.   
        exports.config = {
        seleniumAddress: 'http://hub-cloud.browserstack.com/wd/hub',
         'commonCapabilities': {
               'browserstack.local': true,
               'browserstack.user': '............',
               'browserstack.key': '.............'
           },
         multiCapabilities: [
               {
                    'device': 'iPhone X',
                   'realMobile': 'true',
                   'os_version': '11.0',
                    browserName: 'safari'
                },
           ],

**Comment by evilaliv3** [comment]
Is this still an issue? Are there any know solution that can be configured inside protractor.conf.js ?

**Comment by evilaliv3** [comment]
Have anyone found a solution for this?
