### ISSUE TITLE
JSON data is not imported on IE 11 using protractor / jasmine

### ISSUE THREAD

**Issue by DK15** [angular/protractor#2843]
I am trying to execute a protractor test on IE 11 using jasmine 2 framework. Below is the test,

` ` `
   it('should show a spinner on sandboxes that are being created or deleted', function() {
    MockData.setHttpReturnStatus(mockSharesDataSource, '200_multiple_states');
    sandboxesPage.get();
    expect(element(sandboxesPage.rows.row(0)).element(sandboxesPage.spinner).isPresent())
    .toBeTruthy();     expect(element(sandboxesPage.rows.row(1)).element(sandboxesPage.spinner).isPresent()).
toBeTruthy();    expect(element(sandboxesPage.rows.row(2)).element(sandboxesPage.spinner).isPresent()).
toBeFalsy();
});
` ` `

Here is mockSharesDataSource JSON file block which I am expected to see,

` ` `
"200_multiple_states": {
    "httpReturnStatus": 200,
    "body": [
      {
        "id": "00000000-0000-0000-0000-000000000000",
        "name": "share1",
        "description": "Description of share1",
        "storageServerId": "storageServer1",
        "targetHosts": ["sandbox_server_1_1", "sandbox_server_2_1"],
        "state": "DELETION_IN_PROGRESS",
        "creationTime": 1427720150000,
        "expiryTime": 1427736150000,
        "shareLocation": {
          "type": "nfs",
          "path": "/share"
        },
        "workloadId": "1",
        "pointInTimeId": "1",
        "pointInTimeCreationTime": 7890123456,
        "storageServerRecordId": "rec1"
      },
` ` `

sandboxesPage has following,

` ` `module.exports = {
  alerts: element.all(by.css('alert-box>*')),
  sandboxRows: element.all(by.repeater('sandbox in dataset track by sandbox.id')),
  rows: by.repeater('sandbox in dataset track by sandbox.id'),
  spinner: by.className('fa-spinner'),
 get: function () {
    browser.get('#/sandboxes');
  }
};` ` `

I've configured the IE 11 as mentioned. *The error I am getting is*,  

```
SandboxesSuite should show a spinner on sandboxes that are being created or deleted
  - **Expected false to be truthy.**
      at Object.<anonymous> (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/test/protractor/sandbox/sandboxesSpec.js:474:91)
      at /home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/jasminewd2/index.js:96:23
      at new promise.Promise (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:368:5)
      at controlFlowExecute (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/jasminewd2/index.js:82:18)
      at [object Object].promise.ControlFlow.runInFrame_ (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
      at [object Object].promise.ControlFlow.runEventLoop_ (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1729:8)
      at [object Object].eval (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2043:12)
      at goog.async.run.processWorkQueue (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
      at runMicrotasksCallback (node.js:337:7)
  - **Expected false to be truthy.**
      at Object.<anonymous> (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/test/protractor/sandbox/sandboxesSpec.js:475:91)
      at /home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/jasminewd2/index.js:96:23
      at new promise.Promise (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:368:5)
      at controlFlowExecute (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/jasminewd2/index.js:82:18)
      at [object Object].promise.ControlFlow.runInFrame_ (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
      at [object Object].promise.ControlFlow.runEventLoop_ (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1729:8)
      at [object Object].eval (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2043:12)
      at goog.async.run.processWorkQueue (/home/vagrant/Perforce/darshan.kawar_darshan_8539/management/cloudconsole/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
      at runMicrotasksCallback (node.js:337:7)


Your reply / solution on this issue will be really helpful for me.
@juliemr, @elgalu, @sjelin

**Comment by elgalu** [comment]
Yeez pal, can you at least google "formatting code in github issue" ?
https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks

**Comment by DK15** [comment]
@elgalu : hope this helps.

**Comment by juliemr** [comment]
This isn't reproducible or actionable for us - it sounds like you're having an issue passing data in between your test files, not an issue with Protractor as a framework. Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
