### ISSUE TITLE
Clicking button for second time doesn't work in FireFox

### ISSUE THREAD

**Issue by zuzusik** [angular/protractor#2895]
MacOS X `10.11.3`
FF `44`, Protractor `3.0`.
Worked well with Protractor `2.x` and FF <= `32`
Works well with Protractor `3.0` and Chrome `48.0.2564.97` (64-bit)

Code: 
```javascript
it('check working of Pause/Resume state-actions button', function() {
  behaviors.flights.clickFirstFlightStateToggleButton();
  expect(behaviors.flights.getFirstFlightStateToggleButtonText()).toBe('Resume');
  behaviors.flights.clickFirstFlightStateToggleButton();
  expect(behaviors.flights.getFirstFlightStateToggleButtonText()).toBe('Pause');
});
```
```javascript
clickFirstFlightStateToggleButton: function() {
  return elements.flights.flightStateToggleButtons.get(0).click();
}
```
```javascript
getFirstFlightStateToggleButtonText: function() {
  return elements.flights.flightStateToggleButtons.get(0).getText();
}
```
```javascript
flightStateToggleButtons: element.all(By.css('.flight-controls-container .state-actions button'))
```
```html
<div class="state-actions" data-ng-if="startable()" data-ng-switch="flight.state | lowercase">
  <button data-ng-switch-when="running" data-ng-click="toggleFlight(false)" class="pause" target="_self">Pause</button>
  <button data-ng-switch-when="paused" class="action resume" data-ng-click="toggleFlight(true)" target="_self">Resume</button>
</div>
```

Fails with:
```
Failures:
1) Campaign Dashboard [DXUITC-144] check working of Pause/Resume state-actions button
  Message:
    Expected 'Resume' to be 'Pause'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/test/protractor/scenarios/campaign-dashboard.protractor.js:54:69)
        at process._tickCallback (node.js:368:9)
```

Workaround:
```javascript
clickFirstFlightStateToggleButton: function() {
  return elements.flights.flightStateToggleButtons.then(function(elements) {
    return browser.executeScript('arguments[0].click()', elements[0].getWebElement());
  });
}
```

**Comment by cnishina** [comment]
Without knowing the implementation of toggleFlight on ng-click, I tried to test out an example with both version 3.0.0 and v2.5.1:

html:
```
<ul class="items">
  <li style="display: None">First</li>
  <li>Second</li>
  <li>Third</li>
</ul>
```

test:
```
it("should have a list", function() {
  element.all(by.css('.items li')).then(function(items) {
    expect(items.length).toBe(3);
    expect(items[0].getText()).toBe('');
    expect(items[1].getText()).toBe('Second');
  });
});
```

If this does not answer your question, please ask them at [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor).
