### ISSUE TITLE
Calling .click() on element.all result doesn't work for all elements in FireFox

### ISSUE THREAD

**Issue by zuzusik** [angular/protractor#2896]
MacOS X `10.11.3`
FF `44`, Protractor `3.0`.
Worked well with Protractor `2.x` and FF <= `32`
Works well with Protractor `3.0` and Chrome `48.0.2564.97` (64-bit)

Code: 
```javascript
it('[DXUITC-76] verify collapse/expand at tactic level', function() {
  behaviors.flights.clickToggleTacticFlightsVisibilityButton();
  expect(behaviors.flights.isFlightPartsDisplayed().then(function(isPartsDisplayedArray) {
    return isPartsDisplayedArray.some(function(isPartDisplayedArray) {
      return isPartDisplayedArray.every(function(isPartDisplayed) {
        return !isPartDisplayed;
      });
    });
  })).toBe(true);
  behaviors.flights.clickToggleTacticFlightsVisibilityButton();
  expect(behaviors.flights.isFlightPartsDisplayed().then(function(isPartsDisplayedArray) {
    return isPartsDisplayedArray.some(function(isPartDisplayedArray) {
      return isPartDisplayedArray.every(function(isPartDisplayed) {
        return isPartDisplayed;
      });
    });
  })).toBe(true);
});
```
```javascript
clickToggleTacticFlightsVisibilityButton: function() {
  return  elements.flights.toggleTacticFlightsVisibilityButton.click();
}
```
```javascript
toggleTacticFlightsVisibilityButton: element.all(By.css('.tactic-table button.collapser'))
```
Fails with: 
```
2) Campaign Dashboard [DXUITC-76] verify collapse/expand at tactic level
  Message:
    Expected false to be true.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/test/protractor/scenarios/campaign-dashboard.protractor.js:65:9)
        at process._tickCallback (node.js:368:9)
  Message:
    Expected false to be true.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/test/protractor/scenarios/campaign-dashboard.protractor.js:73:9)
        at process._tickCallback (node.js:368:9)
```

Workaround:
```javascript
clickToggleTacticFlightsVisibilityButton: function() {
  return protractor.promise.map(elements.flights.toggleTacticFlightsVisibilityButton, function(elt) {
    return browser.executeScript('arguments[0].click()', elt.getWebElement());
  });
},
```

Notes: 
* clicking those buttons leads to vertical collapsing of quite big UI parts (it changes scroll position)
* when doing this with `element.all().click()` only first section is collapsed.
* also I noticed that with `element.all().click()` scroll position is being twitched - it seems like Protractor somehow tries to adjust it. And with `browser.executeScript` scroll position stays at the same place.

**Comment by cnishina** [comment]
This appears to be a duplicate to #2895.
