### ISSUE TITLE
This driver instance does not have a valid session ID

### ISSUE THREAD

**Issue by kleinerroemer** [angular/protractor#2899]
My tests pass fine on my windows machine but recently protractor crashes on startup on my fedora 23 machine (node version 0.10.36 over dnf install)

The Stack trace points to the `onPrepare` function in my config which spawns a new browser instance and calls `driver.manage().window().maximize()` on both browser instances.

I didn't find anything related on the net so I would be happy for some inputs.

**Comment by NickTomlin** [comment]
Can you provide us with a few more details: 

1. Your protractor config
2. An isolated test that reproduces the issue
3. The stacktrace from your error

Also, What version of Protractor are you using? Protractor `3.x` is not compatible with Node.

**Comment by kleinerroemer** [comment]
sry it took me so long to reply!

I'm using protractor 2.0.0 with node 0.10.36

ad 1: my base config looks like:
```
module.exports = {
    getConfig: function(url, testCases) {
        return {
            rootElement: "...",
            specs: testCases,
            baseUrl: url,
            seleniumAddress: 'http://localhost:4444/wd/hub',
            framework: "jasmine2",
            allScriptsTimeout: 20000,
            jasmineNodeOpts: {
                includeStackTrace: true,
                isVerbose: true,
                defaultTimeoutInterval: 180000,
                realtimeFailure: true
            },
            onPrepare: function() {
                browser.driver.manage().window().maximize();
                browser.params.browser1 = browser;
                browser.params.browser2 = browser.forkNewDriverInstance();
                browser.params.browser2.driver.manage().window().maximize();
                var failFast = require('jasmine-fail-fast');
                jasmine.getEnv().addReporter(failFast.init());
            }
        };
    }
};
``` 

ad 2: Test cases don't even run. Protractor crashes in the `onPrepare` function

ad 3: ```
/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:392
      throw new Error('This driver instance does not have a valid session ID ' +
            ^
Error: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
    at checkHasNotQuit (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:392:13)
    at flow.execute.then.value (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:365:5)
    at [object Object].promise.ControlFlow.runInFrame_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
    at [object Object].promise.ControlFlow.runEventLoop_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1755:8)
    at [object Object].<anonymous> (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:2056:12)
    at [object Object].goog.async.run.processWorkQueue [as _onTimeout] (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
From: Task: WebDriver.manage().window().maximize()
    at [object Object].webdriver.WebDriver.schedule (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:360:15)
    at [object Object].webdriver.WebDriver.Window.maximize (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1474:23)
    at onPrepare (path_to_base_test_cases/testcases.js:36:50)
    at /usr/lib/node_modules/protractor/lib/util.js:54:41
    at Function.promise (/usr/lib/node_modules/protractor/node_modules/q/q.js:650:9)
    at Object.exports.runFilenameOrFn_ (/usr/lib/node_modules/protractor/lib/util.js:44:12)
    at [object Object].Runner.runTestPreparer (/usr/lib/node_modules/protractor/lib/runner.js:76:17)
    at Object.exports.run (/usr/lib/node_modules/protractor/lib/frameworks/jasmine2.js:79:17)
    at /usr/lib/node_modules/protractor/lib/runner.js:326:35
    at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:797:54)
From: Task: WebDriver.manage().timeouts().setScriptTimeout(20000)
    at [object Object].webdriver.WebDriver.schedule (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:360:15)
    at [object Object].webdriver.WebDriver.Timeouts.setScriptTimeout (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1367:23)
    at [object Object].Runner.createBrowser (/usr/lib/node_modules/protractor/lib/runner.js:181:30)
    at /usr/lib/node_modules/protractor/lib/runner.js:257:21
    at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:759:13)
    at /usr/lib/node_modules/protractor/node_modules/q/q.js:573:44
    at flush (/usr/lib/node_modules/protractor/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)
```

**Comment by juliemr** [comment]
Closing as a non-general issue - we can't provide support for older versions of node and Protractor on all platforms.

**Comment by KaterynaGubar** [comment]
@juliemr I've faced same issue:

"after all" hook: codeceptjs.afterSuite:
     NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
      at session_.flow_.promise (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:847:16)
      at new ManagedPromise (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
      at ControlFlow.promise (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
      at promise.finally (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:846:34)
      at promise.then.error (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1684:12)
      at ManagedPromise.invokeCallback_ (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
      at TaskQueue.execute_ (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
      at TaskQueue.executeNext_ (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
      at asyncRun (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
      at C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
  From: Task: WebDriver.findElements(By(xpath, .//section[./@data-test = 'calendar']//li[./div[./span[@data-test='available']]][position()=1]))
      at thenableWebDriverProxy.schedule (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
      at thenableWebDriverProxy.findElements (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:1048:19)
      at ptor.waitForAngular.then (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\built\element.js:159:44)
      at ManagedPromise.invokeCallback_ (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
      at TaskQueue.execute_ (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
      at TaskQueue.executeNext_ (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
      at asyncRun (C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
      at C:\Users\Kateryna_Gubar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

CodeceptJS version: 1.4.4
NodeJS Version: 8.11.3
Operating System: Windows 10
Protractor: 5.3.2
