### ISSUE TITLE
Error Running Protractor - /node_modules/q/q.js:155 SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by SaiUpadhyayula** [angular/protractor#2945]
Related Issue - [#2775](https://github.com/angular/protractor/issues/2775#issuecomment-184726155)

I am facing below error when running protractor tests, using the latest node version - v5.4.1 and npm version - 3.5.3. I face this problem only on the Build Server(Red Hat Enterprise Linux Server 7.1) but not on my local machine.

I am using a local npm and node installation on server which was done through maven-front-end tools plugin.

```
[plm@siplmapp01 INT node]$ ./node --version
v5.4.1
[plm@siplmapp01 INT node]$ ./npm --version
3.5.3
```

```
> [plm@siplmapp01 INT static]$ node_modules/grunt-cli/bin/grunt e2e-test
> >> Local Npm module "grunt-contrib-qunit" not found. Is it installed?
> 
> Running "protractor_webdriver:modules" (protractor_webdriver) task
> Starting Selenium server
> Shutting down Selenium server: http://localhost:4444
> Shut down Selenium server: http://localhost:4444 (OKOK)
> Restarting Selenium server
> Restarted Selenium server: http://127.0.0.1:4444
> 
> Running "protractor:modules" (protractor) task
> [launcher] Process exited with error code 1
> 
> /data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/q/q.js:155
>                 throw e;
>                       ^
> SyntaxError: Unexpected token )
>     at goog.loadModuleFromSource_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
>     at Object.goog.loadModule (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
>     at /data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
>     at Object.Context.closure.goog.retrieveAndExecModule_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/_base.js:135:8)
>     at <anonymous>:1:6
>     at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/_base.js:104:12)
>     at Object.goog.importScript_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
>     at Object.goog.importModule_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
>     at Object.goog.writeScripts_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:1323:16)
>     at Object.goog.require (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:663:14)
> >> /data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/q/q.js:155
> >>                 throw e;
> >>                       ^
> >> SyntaxError: Unexpected token )
> >>     at goog.loadModuleFromSource_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
> >>     at Object.goog.loadModule (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
> >>     at /data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
> >>     at Object.Context.closure.goog.retrieveAndExecModule_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/_base.js:135:8)
> >>     at <anonymous>:1:6
> >>     at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/_base.js:104:12)
> >>     at Object.goog.importScript_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
> >>     at Object.goog.importModule_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
> >>     at Object.goog.writeScripts_ (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:1323:16)
> >>     at Object.goog.require (/data/apps/bamboo/atlassian-bamboo-5.9.7/xml-data/build-dir/PA-PUT-JOB1/src/main/resources/static/node_modules/selenium-webdriver/lib/goog/base.js:663:14)
> Warning: Tests failed, protractor exited with code: 8 Use --force to continue.
> 
> Aborted due to warnings.
```

The protractor configuration file

```
var AllureReporter = require('jasmine-allure-reporter');
//var HTMLReporter = require('protractor-jasmine2-screenshot-reporter');

exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
//Specs to run individual tests.
    specs: ['../tests/unit/sandbox-spec.js'],
// To run tests as part of the suites.
    suites: {
        intro: ['../tests/unit/login-spec.js','../tests/unit/plm02TabChecks-spec.js','../tests/unit/sandbox-spec.js'],
        e2e: ['../tests/unit/checkBaseline-spec.js','../tests/unit/plm02-spec.js'],
        smoke: ['../tests/e2e/smoke-tests/baselineSchedule-spec.js','../tests/e2e/smoke-tests/validateBaseline-spec.js'],
        sandbox: ['../tests/e2e/smoke-tests/validateBaseline-spec.js']
    },

    capabilities: {
        'browserName': 'phantomjs',
        //For Server
        //'phantomjs.binary.path':'node_modules/phantomjs-prebuilt/bin/phantomjs'

        // For Local Use
        'phantomjs.binary.path':'C:/Users/taaupsa1/Downloads/phantomjs-2.1.1-windows/phantomjs-2.1.1-windows/bin/phantomjs.exe'
    },

    framework:'jasmine2',
    onPrepare: function() {
        // implicit and page load timeouts
        browser.manage().timeouts().pageLoadTimeout(40000);
        browser.manage().timeouts().implicitlyWait(25000);
        browser.manage().window().setSize(1600, 1000);
// for non-angular page
    browser.ignoreSynchronization = true;

//        jasmine.getEnv().addReporter(new HTMLReporter({
//            dest: '../screenshots',
//            filename: 'my-report.html'
//        }));
            
    jasmine.getEnv().addReporter(new AllureReporter({
      allureReport: {
        resultsDir: 'allure-results'
      }
    }));
    }
};
```
Could any one help please?

**Comment by madhavan020985** [comment]
You must use protractor 2.X with older nodejs versions... since you said you are using node 5.x, you  must use protractor 3.x....

**Comment by SaiUpadhyayula** [comment]
I am using protractor 3.0.0

**Comment by NickTomlin** [comment]
Are you sure the version of node that the build server process runs is `5.x`? Can you run the  [example](https://github.com/angular/protractor/tree/master/example) successfully on the build server?

**Comment by SaiUpadhyayula** [comment]
Yes, I used a slightly modified version, by removing `directConnect: true,` and using phantomjs as the browser.Still getting the same error.

And yes I am pretty sure that I am running node 5.x, it is installed as part of the build process and is the only installation we have on the server.

**Comment by SaiUpadhyayula** [comment]
ah, yes. I see a global node installation in /usr/bin with version 0.10.x... that is the reason then. Thanks and closing the issue :)

**Comment by NickTomlin** [comment]
Glad you figured it out, thanks for closign!
