### ISSUE TITLE
Timed out waiting for the WebDriver server

### ISSUE THREAD

**Issue by jonu001** [angular/protractor#2977]
I am using phantomjs (I know not recommended) with protractor and sometimes it works, most times it does not. I am using the angular-seed project on centos6.

I can run once and get:

```
 npm run protractor

> angular-seed@0.0.0 preprotractor /var/www/html/angular-seed
> npm run update-webdriver


> angular-seed@0.0.0 preupdate-webdriver /var/www/html/angular-seed
> npm install


> angular-seed@0.0.0 postinstall /var/www/html/angular-seed
> bower install


> angular-seed@0.0.0 update-webdriver /var/www/html/angular-seed
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> angular-seed@0.0.0 protractor /var/www/html/angular-seed
> protractor e2e-tests/protractor.conf.js

Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://10.0.2.15:39884/wd/hub
...

Finished in 1.741 seconds
3 tests, 3 assertions, 0 failures
```

which is great... yet if I rerun without changing anything I get the following:

```
 npm run protractor

> angular-seed@0.0.0 preprotractor /var/www/html/angular-seed
> npm run update-webdriver


> angular-seed@0.0.0 preupdate-webdriver /var/www/html/angular-seed
> npm install


> angular-seed@0.0.0 postinstall /var/www/html/angular-seed
> bower install


> angular-seed@0.0.0 update-webdriver /var/www/html/angular-seed
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> angular-seed@0.0.0 protractor /var/www/html/angular-seed
> protractor e2e-tests/protractor.conf.js

Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
/var/www/html/angular-seed/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
  goog.global.setTimeout(function() { throw exception; }, 0);
                                            ^
Error: Timed out waiting for the WebDriver server at http://10.0.2.15:50625/wd/hub
    at Error (native)
    at onResponse (/var/www/html/angular-seed/node_modules/protractor/node_modules/selenium-webdriver/http/util.js:89:66)
    at /var/www/html/angular-seed/node_modules/protractor/node_modules/selenium-webdriver/http/util.js:44:21
    at /var/www/html/angular-seed/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/http/http.js:140:5
    at ClientRequest.<anonymous> (/var/www/html/angular-seed/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:172:7)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

npm ERR! Linux 2.6.32-573.7.1.el6.x86_64
npm ERR! argv "/home/username/.nvm/versions/node/v0.12.10/bin/node" "/home/username/.nvm/versions/node/v0.12.10/bin/npm" "run" "protractor"
npm ERR! node v0.12.10
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor e2e-tests/protractor.conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/angular-seed/npm-debug.log`
```

my protractor conf:

```js
exports.config = {
  allScriptsTimeout: 11000,

  specs: [
    '*.js'
  ],

  capabilities: {
    'browserName': 'phantomjs',
    /* 
     * Can be used to specify the phantomjs binary path.
     * This can generally be ommitted if you installed phantomjs globally.
     */
    'phantomjs.binary.path': require('phantomjs-prebuilt').path,

    /*
     * Command line args to pass to ghostdriver, phantomjs's browser driver.
     * See https://github.com/detro/ghostdriver#faq
     */
    'phantomjs.ghostdriver.cli.args': ['--loglevel=DEBUG'],
  },
  
  baseUrl: 'http://localhost:8000/app/',

  framework: 'jasmine',

  jasmineNodeOpts: {
    defaultTimeoutInterval: 30000
  }
};
```

Any ideas?

**Comment by sjelin** [comment]
We don't answer support questions on this issue tracker.  Please ask of StackOverflow or gitter.

That said, the error message indicates that there's no webdriver server running, and I never see a `webdriver-manager start`, so that's probably your problem
