### ISSUE TITLE
Webdriver npm dep inconsistent

### ISSUE THREAD

**Issue by willchen90** [angular/protractor#2981]
Bug report
---

- Node Version: `v5.6.0`
- Protractor Version: `v3.1.1`
- Browser(s): `Chrome`
- Operating System and Version `OS X 10.10`
- Error received:
```
> protractor test/config/protractor.js

[launcher] Process exited with error code 1
/Users/willchen/prep/goodwill/node_modules/q/q.js:155
                throw e;
                ^

Error: No selenium server jar found at the specified location (/Users/willchen/prep/goodwill/node_modules/protractor/selenium/selenium-server-standalone-2.51.0.jar). Check that the version number is up to date.
    at LocalDriverProvider.addDefaultBinaryLocs_ (/Users/willchen/prep/goodwill/node_modules/protractor/lib/driverProviders/local.js:37:11)
    at LocalDriverProvider.setupEnv (/Users/willchen/prep/goodwill/node_modules/protractor/lib/driverProviders/local.js:71:8)
    at Runner.run (/Users/willchen/prep/goodwill/node_modules/protractor/lib/runner.js:278:31)
    at TaskRunner.run (/Users/willchen/prep/goodwill/node_modules/protractor/lib/taskRunner.js:123:19)
    at createNextTaskRunner (/Users/willchen/prep/goodwill/node_modules/protractor/lib/launcher.js:216:20)
    at /Users/willchen/prep/goodwill/node_modules/protractor/lib/launcher.js:239:7
    at _fulfilled (/Users/willchen/prep/goodwill/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/willchen/prep/goodwill/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/willchen/prep/goodwill/node_modules/q/q.js:796:13)
    at /Users/willchen/prep/goodwill/node_modules/q/q.js:604:44
npm ERR! Test failed.  See above for more details.
```

After reading the changelog, I noticed the `config.json` has been updated to use v2.51 of selenium, however the `package.json` is still referring to the old version v2.48.2.

See: https://github.com/angular/protractor/blob/3.1.1/package.json#L16

**Comment by pedrro** [comment]
I'm getting a similar error when running protractor on snap-ci

```
/var/snap-ci/repo/node_modules/protractor/node_modules/q/q.js:155
                throw e;
                      ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/var/snap-ci/repo/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/var/snap-ci/repo/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /var/snap-ci/repo/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.Context.closure.goog.retrieveAndExecModule_ (/var/snap-ci/repo/node_modules/protractor/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/var/snap-ci/repo/node_modules/protractor/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/var/snap-ci/repo/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/var/snap-ci/repo/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
    at Object.goog.writeScripts_ (/var/snap-ci/repo/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1323:16)
    at Object.goog.require (/var/snap-ci/repo/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:663:14)


```

When i'm running local it's working well, the node version of local env is 3.3.9, someone has a solution for this error? This is my [package.json](https://github.com/pedrro/TodoList/blob/gh-pages/package.json)

**Comment by NickTomlin** [comment]
@willchen90 Have you run `webdriver-manager update`? This error is thrown when there's no selenium jar at the default `protractor/selenium/selenium-server-standalone-2.51.0.jar` not because the versions between `config.json` and `package.json` do not match. 

@sjelin I'm assuming this mismatch is fine because they both serve different purposes (`config.json` is consume by webdriver to grab a jar, `package.json` is used by protractor to wrap the selenium api). That said, Is something we should keep at the same version?

@pedrro 
Glad you fixed your issue, it sounds like it's the fact that protractor does not support node < 4.

**Comment by NickTomlin** [comment]
I haven't seen any action on this in a while going to go ahead and close because I believe this is because selenium is not available on the host machine.

@willchen90 if downloading selenium through webdriver manager or running selenium yourself (and configuring protractor to use that instance) does not work let me know and I will re-open. 

Thanks!
