### ISSUE TITLE
window.getAllAngularTestabilities is not a function

### ISSUE THREAD

**Issue by nvsoares** [angular/protractor#2991]
Hi.
I'm running the protractor with a demo test of protractor quick start and is always to give the error:
Failed: Error while waiting for Protractor to sync with the page: 
```
"window.getAllAngularTestabilities is not a function"
  Stack:
    Error: Failed: Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"
        at stack (C:\Users\nsoares.WINTOUCH\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1577:17)
        at buildExpectationResult (C:\Users\nsoares.WINTOUCH\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1547:14)
        at Spec.Env.expectationResultFactory (C:\Users\nsoares.WINTOUCH\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:638:18)
        at Spec.addExpectationResult (C:\Users\nsoares.WINTOUCH\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:330:34)
        at Env.fail (C:\Users\nsoares.WINTOUCH\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:987:25)
        at Function.next.fail (C:\Users\nsoares.WINTOUCH\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1903:19)
        at C:\Users\nsoares.WINTOUCH\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:101:16
```

**Here is my demo project:**
[protractor-demo.zip](https://github.com/angular/protractor/files/155092/protractor-demo.zip)

and here's other information:
- Node Version: `5.4.1`
- Protractor Version: `3.1.1`
- Browser(s): `chrome`
- Operating System and Version 'Windows 8.1 Enterprise x64'

**Comment by cnishina** [comment]
Was able to reproduce this on Windows 8.1 and also on OSX.

**Comment by cnishina** [comment]
The config looks wrong. The angular app that is under test is not an Angular 2 app. Also, there are several selenium configs that appear to be extra configurations. Removing useAllAngular2AppRoots, seleniumServerJar, seleniumPort, seleniumArgs appears to work. The final config looks like:

```
// Protrctor demo conf file
var ProtractorEnv = require('./protractor.env.js');

exports.config = {
    baseUrl: ProtractorEnv.baseUrl,
    restartBrowserBetweenTests: false,
 
    seleniumAddress: ProtractorEnv.seleniumAddress,
    capabilities: ProtractorEnv.capabilities,

    specs: [
        './**/*.spec.js'
    ],
  
    // Jasmine config
    framework: ProtractorEnv.framework
}
```

After I made those changes, the test worked.
