### ISSUE TITLE
Test spec/ng2/async_spec.js occasionally fails

### ISSUE THREAD

**Issue by cnishina** [angular/protractor#3000]
The test: "should wait for a series of periodic increments" has been failing occasionally on Travis and should be fixed. The test clicks the action button, waits, then clicks cancel.

The text for the value should be the same after 3 seconds. However, this is resulting in a timeout... or mismatch in values. Below is the failure for timing out.

```
[launcher] Running 1 instances of WebDriver
Started
....F
Failures:
1) async angular2 application long async spec should wait for a series of periodic increments
  Message:
    Failed: Wait timed out after 4388ms
  Stack:
    Error: Wait timed out after 4388ms
        at /home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2241:22
        at Promise.invokeCallback_ (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
        at /home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:364:9)
    From: Task: <anonymous wait>
        at ControlFlow.wait (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2229:17)
        at WebDriver.wait (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/webdriver.js:688:29)
        at [object Object].to.(anonymous function) [as wait] (/home/travis/build/angular/protractor/built/protractor.js:68:25)
```

**Comment by cnishina** [comment]
https://github.com/angular/protractor/blob/9144494a28dac5a0409de4c5384e933f2d2f8156/spec/ng2/async_spec.js#L58

**Comment by cnishina** [comment]
```
describe('long async spec', function() {
    var originalTimeout;
    beforeEach(function() {
      originalTimeout = jasmine.DEFAULT_TIMEOUT_INTERVAL;
      jasmine.DEFAULT_TIMEOUT_INTERVAL = 30000;
    });

    it('should wait for a series of periodic increments', function() {
      var timeout = $('#periodicIncrement');

      // Waits for the val to count 2.
      var EC = protractor.ExpectedConditions;

      timeout.$('.action').click();
      browser.ignoreSynchronization = true;
      browser.sleep(4000);
      timeout.$('.cancel').click();
      browser.ignoreSynchronization = false;

      var text = timeout.$('.val').getText();
      browser.sleep(4000);
      expect(timeout.$('.val').getText()).toEqual(text);
    });

    afterEach(function() {
      jasmine.DEFAULT_TIMEOUT_INTERVAL = originalTimeout;
    });
  });
```
Without using expected conditions, this could be a the proposed solution.

**Comment by juliemr** [comment]
This seems reasonable. Protractor should _not_ wait for anything scheduled with `setTimeout`. We should fix our test app to have one button that runs `setTimeout` outside of the Angular zone, and one that runs it inside the zone. We should verify that running outside the zone does not cause protractor to wait, and waiting for it inside the zone causes a timeout.

**Comment by juliemr** [comment]
Removing the bug label, since this isn't a bug in Protractor, but in our own test.

**Comment by cnishina** [comment]
Closing this item since it does not appear that this is still happening.
