### ISSUE TITLE
implement testForAngular Microsoft Edge webdriver

### ISSUE THREAD

**Issue by cnishina** [angular/protractor#3016]
feature request for implementation of testForAngular for Microsoft Edge.

configuration
```
exports.config = {
  // directConnect: true,
  seleniumAddress: 'http://localhost:17556',
  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'MicrosoftEdge'
  },

  // Framework to use. Jasmine is recommended.
  framework: 'jasmine',

  // Spec patterns are relative to the current working directory when
  // protractor is called.
  specs: ['example_spec.js'],

  // Options to be passed to Jasmine.
  jasmineNodeOpts: {
    defaultTimeoutInterval: 30000
  }
};
```

spec:
```
describe('angularjs homepage', function() {
  it('should greet the named user', function() {
    browser.get('http://www.angularjs.org');

    element(by.model('yourName')).sendKeys('Julie');

    var greeting = element(by.binding('yourName'));

    expect(greeting.getText()).toEqual('Hello Julie!');
  });
});
```

output:
```
C:\Users\IEUser\src\protractor>node bin/protractor example/conf.js
Using the selenium server at http://localhost:17556
[launcher] Running 1 instances of WebDriver
Started
F

Failures:
1) angularjs homepage should greet the named user
  Message:
    Failed: Error while running testForAngular: not implemented
  Stack:
    Error: Failed: Error while running testForAngular: not implemented
        at C:\Users\IEUser\src\protractor\node_modules\jasminewd2\index.js:101:16
        at Promise.invokeCallback_ (C:\Users\IEUser\src\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\Users\IEUser\src\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\Users\IEUser\src\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)

1 spec, 1 failure
Finished in 0.531 seconds
```

**Comment by juliemr** [comment]
Quick update - we discussed that this might be a problem with Edge not implementing the webdriver command EXECUTE_ASYNC_SCRIPT. Will investigate.

**Comment by cnishina** [comment]
Investigating a simple test for `browser.driver.executeAsyncScript`:

```
describe('async script', function() {
  it('should console output', function() {
    browser.driver.executeAsyncScript(
      'console.log("hello world");'
    );
  });
});
```

output:
```
E:\>node bin/protractor example/conf.js
Using the selenium server at http://localhost:17556
[launcher] Running 1 instances of WebDriver
Started
F

Failures:
1) async script should console output
  Message:
    Failed: not implemented
  Stack:
    WebDriverError: not implemented
        at WebDriverError (E:\node_modules\selenium-webdriver\error.js:26:26)
        at Object.checkLegacyResponse (E:\node_modules\selenium-webdriver\error.js:580:13)
        at E:\node_modules\selenium-webdriver\lib\webdriver.js:360:15
        at Promise.invokeCallback_ (E:\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (E:\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (E:\node_modules\selenium-webdriver\lib\promise.js:2773:21)
        at E:\node_modules\selenium-webdriver\lib\promise.js:2652:27
        at E:\node_modules\selenium-webdriver\lib\promise.js:639:7
        at process._tickCallback (node.js:406:9)
    From: Task: Run it("should console output") in control flow
        at Object.<anonymous> (E:\node_modules\jasminewd2\index.js:81:14)
    From asynchronous test:
    Error
        at Suite.<anonymous> (E:\example\example_spec.js:2:3)
        at Object.<anonymous> (E:\example\example_spec.js:1:1)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)

1 spec, 1 failure
Finished in 0.047 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] microsoft edge #01 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1

```

**Comment by juliemr** [comment]
According to https://dev.windows.com/en-us/microsoft-edge/platform/status/webdriver/details/ (not sure if this is the canonical source) support for `execute async script` is still "preview".

**Comment by manoj9788** [comment]
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md#v2520
Support for Edge. in V 2.52

**Comment by cnishina** [comment]
@manoj9788 Yes, that is why we upgraded to 2.52; however, the Edge driver does not support the execute async script yet.

**Comment by manoj9788** [comment]
Yep got it :) thanks.

**Comment by cnishina** [comment]
This appears to be working now with [release 10586 (version 2.10586)](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/). Example here:

https://github.com/cnishina/protractor-examples/tree/master/protractor/edge_spec

Also, added webdriver-manager support for edge: https://github.com/angular/webdriver-manager/pull/56
