### ISSUE TITLE
When using multiple instances of the browser with shardTestFile option I see server terminated error

### ISSUE THREAD

**Issue by adokania** [angular/protractor#3031]
I am seeing the following error when using shardTestFile with 2 instance of chrome.

conf.js:
```

capabilities: {
        'browserName': 'chrome',
        'shardTestFiles': true,
        'maxInstances': 2,
    },

```
Error:
```
----------------------
[chrome #1-4] PID: 74574
[chrome #1-4] Specs: /Users/Adity/Kensho/zentreefish/projects/zentreefish/app/tests/protractor_tests/score_study/event-analysis-test.js
[chrome #1-4]
[chrome #1-4] Starting selenium standalone server...
[chrome #1-4] /Users/Adity/Kensho/zentreefish/projects/zentreefish/app/tests/protractor_tests/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
[chrome #1-4]   goog.global.setTimeout(function() { throw exception; }, 0);
[chrome #1-4]                                       ^
[chrome #1-4] Error: Server terminated early with status 1
[chrome #1-4]     at Error (native)
[chrome #1-4]     at /Users/Adity/Kensho/zentreefish/projects/zentreefish/app/tests/protractor_tests/node_modules/selenium-webdriver/remote/index.js:204:18
[chrome #1-4]     at promise.ControlFlow.runInFrame_ (/Users/Adity/Kensho/zentreefish/projects/zentreefish/app/tests/protractor_tests/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
[chrome #1-4]     at goog.defineClass.notify (/Users/Adity/Kensho/zentreefish/projects/zentreefish/app/tests/protractor_tests/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
[chrome #1-4]     at promise.Promise.notify_ (/Users/Adity/Kensho/zentreefish/projects/zentreefish/app/tests/protractor_tests/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
[chrome #1-4]     at Array.forEach (native)
[chrome #1-4]     at promise.Promise.notifyAll_ (/Users/Adity/Kensho/zentreefish/projects/zentreefish/app/tests/protractor_tests/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
[chrome #1-4]     at goog.async.run.processWorkQueue (/Users/Adity/Kensho/zentreefish/projects/zentreefish/app/tests/protractor_tests/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
[chrome #1-4]     at process._tickCallback (node.js:402:9)
[launcher] Runner process exited unexpectedly with error code: 1
[launcher] 2 instance(s) of WebDriver still running
```

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
