### ISSUE TITLE
Chrome browser is not working  in version 3.2.0 when the server is started

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#3033]
OS: windows 7
protractor version:Version 3.2.0

```
    super(opt_error);
         ^
WebDriverError: chrome not reachable
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 61.25 seconds
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'NBLAP99', ip: '192.168.7.100', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at WebDriverError (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\error.js:27:10)
    at Object.checkLegacyResponse (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\error.js:580:13)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:64:13
    at Promise.invokeCallback_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
    at TaskQueue.execute_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
    at TaskQueue.executeNext_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2652:27
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (node.js:366:9)
From: Task: WebDriver.createSession()
    at acquireSession (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:62:22)
    at Function.createSession (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:295:12)
    at Builder.build (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\builder.js:458:24)
    at [object Object].DriverProvider.getNewDriver (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:42:27)
    at [object Object].Runner.createBrowser (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\built\runner.js:203:37)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\built\runner.js:293:21
    at _fulfilled (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
[launcher] Process exited with error code 1
```

**Comment by NickTomlin** [comment]
Can you provide some sample code and your config?

**Comment by vivekbrahmadandi** [comment]
its got fixed with the new version of webdriver

**Comment by YeruchamB** [comment]
I'm having the same problem and I'm pretty sure i have the latest WebDriver. Which version do you have now?

**Comment by cnishina** [comment]
The `webdriver-manager` version is tied to the protractor version. If you are having problems on Windows with version 3.2.1, get the latest version 3.2.2 with the hot fix.

After you update your protractor version, clean out your downloads with `webdriver-manager clean` and redownload the files `webdriver-manager update`.
