### ISSUE TITLE
Node require('protractor') fails since 3.2.0

### ISSUE THREAD

**Issue by EtienneMiret** [angular/protractor#3034]
Bug report
---

- Node Version: `5.9.0`
- Protractor Version: `3.2.0`
- Browser(s): `N/A`
- Operating System and Version `docker digitallyseamless/nodejs-bower-grunt:latest`
- A relevant example test

```js
var protractor = require('protractor');
```

- Output from running the test

```
    module.js:341
        throw err;
        ^
    Error: Cannot find module 'protractor'
        at Function.Module._resolveFilename (module.js:339:15)
        at Function.Module._load (module.js:290:25)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at Object.<anonymous> (/data/tmp/index.js:1:80)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Function.Module.runMain (module.js:447:10)
```

- Steps to reproduce the bug

$ npm install --save protractor@3.2.0
$ node index.js

**Comment by NickTomlin** [comment]
I can reproduce this son OSX using protractor `3.2.0`

**Comment by NickTomlin** [comment]
I think this is because are now publishing with the built protractor files in `built` instead of `lib` and the `main` key of package.json points to `lib/protractor`
