### ISSUE TITLE
WebDriver Error: this.getChromeWindowFromDocumentWindow(...). I get this error running through firefox.

### ISSUE THREAD

**Issue by Nikhil0538** [angular/protractor#3049]
I am using protractor 3.2, webdriver 2.52, chromedriver 2.21.
I see this error often times running test through "firefox", but when i start after a some time then it works fine but how is it related to "Chrome"? here is the error.
```
WebDriverError: this.getChromeWindowFromDocumentWindow(...) is undefined
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'KUMARNI3', ip: '16.77.96.116', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_31'
Driver info: driver.version: unknown
    at WebDriverError (C:\Users\nick\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\error.js:27:10)
    at Object.checkLegacyResponse (C:\Users\nick\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\error.js:580:13)
    at C:\Users\nick\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:360:15
    at Promise.invokeCallback_ (C:\Users\nick\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
    at TaskQueue.execute_ (C:\Users\nick\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
    at TaskQueue.executeNext_ (C:\Users\nick\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
    at C:\Users\nick\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2652:27
    at C:\Users\nick\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (node.js:356:9)
[launcher] Process exited with error code 1
```
I would be really happy to know the solution.

**Comment by cnishina** [comment]
You are not the only one with this issue: [Stackoverflow: getChromeWindowFromDocument](http://stackoverflow.com/questions/35029386/getting-org-openqa-selenium-webdriverexception-this-getchromewindowfromdocument). Check to see what version of Firefox you are using and upgrade to version 44.

**Comment by Nikhil0538** [comment]
I am using latest version of Firefox(45.0.1), I still see the same error often times. I feel it is more suitable question in "GitHub" than stackoverflow.

**Comment by cnishina** [comment]
Does your test work for Firefox version 44? We have seen some issues with Firefox version 45.

**Comment by cnishina** [comment]
@Nikhil0538 have you tried firefox 44?

**Comment by cnishina** [comment]
Closing this as a stale issue.
