### ISSUE TITLE
Protractor triggers selenium exception, exits immediately saying all tests passed

### ISSUE THREAD

**Issue by alindsay55661** [angular/protractor#3062]
Bug report
---

- Node Version: `4.2.4`
- Protractor Version: `3.1.1`
- Browser(s): `chrome (locally) / various sauce labs browsers`
- Operating System and Version `OSX 10.10.5`
- Your protractor configuration file

```javascript
exports.config = {

  seleniumAddress: 'http://localhost:4444/wd/hub',

  baseUrl: '',

  specs: [
    'test/e2e/sanity.js'
  ],
  exclude: [],

  framework: 'jasmine2',

  allScriptsTimeout: 110000,

  jasmineNodeOpts: {
    showTiming: true,
    showColors: true,
    isVerbose: false,
    includeStackTrace: false,
    defaultTimeoutInterval: 400000
  },

  capabilities: {
    'browserName': 'chrome',
    'tunnel-identifier': process.env.SAUCE_USER
  },

  onPrepare: function() {
    browser.ignoreSynchronization = true;
  },

   useAllAngular2AppRoots: true
};
```
- A relevant example test

```javascript
describe('angularjs homepage todo list', function() {
  it('should add a todo', function() {
    browser.get('https://angularjs.org');

    element(by.model('todoList.todoText')).sendKeys('write first protractor test');
    element(by.css('[value="add"]')).click();

    var todoList = element.all(by.repeater('todo in todoList.todos'));
    expect(todoList.count()).toEqual(3);
    expect(todoList.get(2).getText()).toEqual('write first protractor test');

    // You wrote your first test, cross it off the list
    todoList.get(2).element(by.css('input')).click();
    var completedAmount = element.all(by.css('.done-true'));
    expect(completedAmount.count()).toEqual(-2); // <--- "Almost passing"
  });
});
```
- Output from running the test
````
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started
.


1 spec, 0 failures
Finished in 0.015 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed
````

````
14:10:36.549 INFO - Executing: [new session: Capabilities [{tunnel-identifier=alindsay41, count=1, browserName=chrome}]])
14:10:36.556 INFO - Creating a new session for Capabilities [{tunnel-identifier=alindsay41, count=1, browserName=chrome}]
Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 28534
Only local connections are allowed.
14:10:37.454 INFO - Done: [new session: Capabilities [{tunnel-identifier=alindsay41, count=1, browserName=chrome}]]
14:10:37.467 INFO - Executing: [set script timeout: 110000])
14:10:37.471 INFO - Done: [set script timeout: 110000]
14:10:37.633 INFO - Executing: [delete session: a735687c-5a23-44f2-bf55-935277143fdd])
14:10:37.634 INFO - Executing: [get: https://angularjs.org/])
14:10:37.708 INFO - Done: [delete session: a735687c-5a23-44f2-bf55-935277143fdd]
14:10:38.855 WARN - Exception thrown
org.openqa.selenium.remote.SessionNotFoundException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'supports-MacBook-Pro-2.local', ip: '192.168.0.190', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_77'
Driver info: driver.version: EventFiringWebDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:134)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:316)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
	at com.sun.proxy.$Proxy1.get(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:163)
	at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:40)
	at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
14:10:38.858 WARN - Exception: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'supports-MacBook-Pro-2.local', ip: '192.168.0.190', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_77'
Driver info: driver.version: EventFiringWebDriver
````

- Steps to reproduce the bug

1. Use OSX 10.10.5
2. Start a local selenium server or connect to sauce labs remotely.
3. $ protractor conf.js

I have no idea what is happening here, protractor just appears to not be working. At one point the test did run successfully. I then tried to write a gulp task that starts the server and runs the test automatically. For this I tried the following gulp plugins:

gulp-protractor
gulp-angular-protractor

After this protractor would no longer work. I have uninstalled these node modules but protractor still exits prematurely. I am using a global install of protractor. Any help is greatly appreciated.

**Comment by alindsay55661** [comment]
Ok,

It looks like the issue was caused by gulp plugins which installed local versions of protractor. I did some additional checking and cleaned the following modules:

protractor
webdriver-manager

I then reinstalled protractor globally and updated the webdrivers. All is working again.
