### ISSUE TITLE
Internet Explorer version 11 having an issue while creating a second browser window

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#3065]
#IE 11 is giving this issue while running the tests. And more over I haven't started any server of webdriver-manager

A Jasmine spec timed out. Resetting the WebDriver Control Flow.
F

Failures:
1) Testing suite testing spec
  Message:
    Failed: Error while running testForAngular: Page reload detected during async script (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 2.00 seconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: host: 'NBLAP99', ip: '192.168.7.43', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
    Session ID: a4cb62a9-ad71-4c9b-a698-f3fbc2809e65
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBeha
viour=dismiss, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, initialBrowserUrl=http://localhost:7207/, handlesAlerts=true, ie.forceCreateProces
sApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
  Stack:
    Error: Failed: Error while running testForAngular: Page reload detected during async script (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 2.00 seconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: host: 'NBLAP99', ip: '192.168.7.43', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
    Session ID: a4cb62a9-ad71-4c9b-a698-f3fbc2809e65
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBeha
viour=dismiss, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, initialBrowserUrl=http://localhost:7207/, handlesAlerts=true, ie.forceCreateProces
sApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
        at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:101:16
        at Promise.invokeCallback_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)

1 spec, 1 failure
Finished in 14.578 seconds
Shutting down selenium standalone server.

C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:365
      onError(new Error(message));
              ^
Error: ECONNREFUSED connect ECONNREFUSED 192.168.7.43:54309
    at ClientRequest.<anonymous> (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:365:15)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
From: Task: WebDriver.quit()
    at WebDriver.schedule (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:344:17)
    at WebDriver.quit (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:419:23)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:67:16
    at Promise.invokeCallback_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
    at TaskQueue.execute_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
    at TaskQueue.executeNext_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2697:25
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (node.js:366:9)
[launcher] Process exited with error code 1

**Comment by vivekbrahmadandi** [comment]
Here is the code

browser.get(browser.baseUrl);
 browser2 = browser.forkNewDriverInstance();
 browser2.get(browser.baseUrl);

**Comment by sjelin** [comment]
Are you on the latest protractor/webdriver-manager version?  We had a hotfix to 3.2.2

**Comment by vivekbrahmadandi** [comment]
Yes, but it is not working, can you able to reproduce the issue

**Comment by cnishina** [comment]
Could you provide the `webdriver-manager start` logs? This might be still related to 3.2.1.

**Comment by vivekbrahmadandi** [comment]
C:\Users\vivekb>webdriver-manager start
seleniumProcess.pid: 5932
11:18:29.533 INFO - Launching a standalone Selenium Server
Setting system property webdriver.chrome.driver to C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\selenium\chromedriver_2.21.exe
11:18:29.743 INFO - Java: Oracle Corporation 24.71-b01
11:18:29.743 INFO - OS: Windows 7 6.1 amd64
11:18:29.763 INFO - v2.52.0, with Core v2.52.0. Built from revision 4c2593c
11:18:29.833 INFO - Driver class not found: com.opera.core.systems.OperaDriver
11:18:29.833 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
11:18:29.843 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{platform=MAC, browserName=safari, version=}] does not match the current platform VISTA
11:18:30.113 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
11:18:30.113 INFO - Selenium Server is up and running

**Comment by vivekbrahmadandi** [comment]
protractor devel-conf.js --suite=Test
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.7.50:63343/wd/hub
Started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
F
Failures:
1) Testing suite testing spec
  Message:
    Failed: Error while running testForAngular: Page reload detected during async script (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 1.26 seconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: host: 'NBLAP99', ip: '192.168.7.50', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
    Session ID: 578c3d5e-434e-4dad-b562-4b9391bfaf40
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAler
viour=dismiss, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, initialBrowserUrl=http://localhost:45041/, handlesAlerts=true, ie.forceCreate
ssApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
  Stack:
    Error: Failed: Error while running testForAngular: Page reload detected during async script (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 1.26 seconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: host: 'NBLAP99', ip: '192.168.7.50', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
    Session ID: 578c3d5e-434e-4dad-b562-4b9391bfaf40
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAler
viour=dismiss, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, initialBrowserUrl=http://localhost:45041/, handlesAlerts=true, ie.forceCreate
ssApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
        at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:101:16
        at Promise.invokeCallback_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)

1 spec, 1 failure
Finished in 7.707 seconds
Shutting down selenium standalone server.

C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:365
      onError(new Error(message));
              ^
Error: ECONNREFUSED connect ECONNREFUSED 192.168.7.50:63343
    at ClientRequest.<anonymous> (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:365:15)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
From: Task: WebDriver.quit()
    at WebDriver.schedule (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:344:17)
    at WebDriver.quit (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:419:23)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:67:16
    at Promise.invokeCallback_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
    at TaskQueue.execute_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
    at TaskQueue.executeNext_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2697:25
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (node.js:366:9)
[launcher] Process exited with error code 1

**Comment by vivekbrahmadandi** [comment]
exports.config = {
    baseUrl: 'https://devel-more.com',
    seleniumArgs: ['-Dwebdriver.ie.driver=D:\\IEDriverServer_Win32_2.52.0.exe'],
    suites: {
        Test: './specs/TestingSuite.js'
    },
    capabilities: {
        'browserName': 'internet explorer',
        'platform': 'ANY',
        'version': '11'
    },
    allScriptsTimeout: 95000,
    framework: 'jasmine2',
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 950000
    },
    onPrepare: function() {
        browser.driver.manage().window().maximize();
    }
};

**Comment by vivekbrahmadandi** [comment]
suite file

var AdminLoginPage = require('../pages/admin/LoginPage');
var AdminHomePage = require('../pages/admin/HomePage');
describe('Testing suite', function() {
    it('testing spec', function() {
        browser.get(browser.baseUrl);
        var homePage = new AdminHomePage();
        var loginPage = new AdminLoginPage();
        browser2 = browser.forkNewDriverInstance();
        browser2.get(browser.baseUrl);
    });
});

**Comment by vivekbrahmadandi** [comment]
my protractor version is  3.2.2

**Comment by vivekbrahmadandi** [comment]
**If I  uncomment the selenium address property in config file , it is giving some other issue.


D:\EOTARAutomation>protractor devel-conf.js --suite=Test
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\error.js:27
    super(opt_error);
         ^
WebDriverError: The path to the driver executable must be set by the webdriver.ie.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver. The latest version can be downloaded from http://s
elenium-release.storage.googleapis.com/index.html
    at WebDriverError (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\error.js:27:10)
    at Object.checkLegacyResponse (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\error.js:580:13)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:64:13
    at Promise.invokeCallback_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
    at TaskQueue.execute_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
    at TaskQueue.executeNext_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2652:27
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (node.js:366:9)
From: Task: WebDriver.createSession()
    at acquireSession (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:62:22)
    at Function.createSession (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:295:12)
    at Builder.build (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\builder.js:458:24)
    at [object Object].DriverProvider.getNewDriver (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:42:27)
    at [object Object].Runner.createBrowser (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\built\runner.js:203:37)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\built\runner.js:293:21
    at _fulfilled (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
[launcher] Process exited with error code 1**

**Comment by vivekbrahmadandi** [comment]
Can I know the update of this issue ?

**Comment by vivekbrahmadandi** [comment]
Can we able to reproduce this issue

**Comment by cnishina** [comment]
I cannot reproduce your issue. Here's something that will help you:

start webdriver-manager with internet explorer.
```
webdriver-manager start --ie32
```

spec.js
```
describe('angularjs homepage', function() {
  it('open two pages', function() {
    console.log(browser.baseUrl);
    browser.get(browser.baseUrl);
    browser.getCapabilities().then(function(capabilities) {
      // http://stackoverflow.com/questions/23872955/get-the-current-browser-name-in-protractor-test
      console.log(capabilities);
    });
    element(by.model('yourName')).sendKeys('Bar');
    var greeting = element(by.binding('yourName'));
    expect(greeting.getText()).toEqual('Hello Bar!');
    browser2 = browser.forkNewDriverInstance();
    console.log('two browsers?');

    browser2.get(browser.baseUrl);
    browser2.element(by.model('yourName')).sendKeys('Foo');
    var greeting = browser2.element(by.binding('yourName'));
    expect(greeting.getText()).toEqual('Hello Foo!');

    browser2.getCapabilities().then(function(capabilities) {;
      console.log(capabilities);
    });
    browser2.driver.sleep(10000);
  });
});

```

conf.js
```
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  capabilities: {
      browserName: 'internet explorer'
  },
  framework: 'jasmine',
  baseUrl: 'http://angularjs.org',
  specs: [ 'spec.js' ],
  jasmineNodeOpts: {
    defaultTimeoutInterval: 30000
  },
  onPrepare: function() {
    browser.driver.manage().window().maximize();
  }
}
```

this launches two browsers and inputs "Bar" into browser 1 and "Foo" into browser 2.

**Comment by vivekbrahmadandi** [comment]
It is working with your code, if i change the baseUrl to my project specific url .This is issue we are gettting.

Message:
  Failed: Error while running testForAngular: Page reload detected during async script (WARNING: The server did not provide any stacktrace information)
  Command duration or timeout: 1.81 seconds
  Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
  System info: host: 'NBLAP99', ip: '192.168.7.63', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
  Session ID: c313865e-1be5-45ac-a4e7-645c2a272c45
  Driver info: org.openqa.selenium.ie.InternetExplorerDriver
  Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false,
our=dismiss, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=true, requireWindowFocus=false,
pi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
Stack:
  Error: Failed: Error while running testForAngular: Page reload detected during async script (WARNING: The server did not provide any stacktrace information)
  Command duration or timeout: 1.81 seconds
  Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
  System info: host: 'NBLAP99', ip: '192.168.7.63', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
  Session ID: c313865e-1be5-45ac-a4e7-645c2a272c45
  Driver info: org.openqa.selenium.ie.InternetExplorerDriver
  Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false,
our=dismiss, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=true, requireWindowFocus=false,
pi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
      at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:101:16
      at Promise.invokeCallback_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
      at TaskQueue.execute_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
      at TaskQueue.executeNext_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)

**Comment by vivekbrahmadandi** [comment]
Firefox and chrome is working properly only the ie driver is giving issue , might be an issue from app side or else any other code I should handle for IE driver to get rid of the above issue

**Comment by cnishina** [comment]
If my sample works on your machine, then that means the functionality of forkNewDriverInstance works which means that this is not an issue with protractor. This might be an issue from your app side and from the stack trace it looks like there is a refresh happening: `Page reload detected during async script`

**Comment by vivekbrahmadandi** [comment]
@cnishina  I tried with protractor website and angular website. This are the urls which i have tested.

browser.baseUrl = 'https://angularjs.org/';
        browser.get(browser.baseUrl);
        browser2 = browser.forkNewDriverInstance();
        browser2.get(browser.baseUrl);

**Comment by RajEtamsetti** [comment]
@vivekbrahmadandi Did you get any final solution for this problem.. ? how did your issue resolved "WebDriverException: Message: Page reload detected during async script"
