### ISSUE TITLE
Configurate Protractor to ignore browser console errors

### ISSUE THREAD

**Issue by pj-infest** [angular/protractor#3073]
Hi.
I have a little problems with protractor, please help me to resolve it.
I try to write tests for web application, but there are some difficulties. When i use the web application I get some angular errors in browser console. It is not fatal errors, and they do not interfere for application execution.

But when I run Protractor test, it fail on the first of this browsers console errors.

Is there a way to configure Protractor test to carried out test scenarie and checked the scenarie  results, ignoring these browser console errors?

I also try to using protractor console plugin with with
       
```
failOnWarning: false,
failOnError: false, 
```

flags, but it does not help me.

here is my config file:

```
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['spec/authorization.js'],

    capabilities: {
        //'browserName': 'firefox'
        'browserName': 'chrome'
    },
    plugins: [{
        package: 'protractor-console-plugin',
        failOnWarning: false,
        failOnError: false,
        logWarnings: false
    }]
};
 
```

And it is my test file
```
var
    testingAdress = 'http://localhost:1340';

    describe('admin avtorization test', function(){
    beforeEach(function(){
        // should be called before each it block
    });

    it('should avtorizate as admin', function(){

        browser.get(testingAdress);

        expect(browser.getCurrentUrl()).toEqual('localhost:1340'+'/#!/');

        //element(by.linkText('Sign Up')).click();

        //expect(browser.getCurrentUrl()).toEqual(testingAdress + '/#!/signup');

        //element(by.id('myLink').click());
        //expect(browser.getCurrentUrl()).toEqual("http://myUrl.com");
    });

});
```

**Comment by sjelin** [comment]
What's the test output?

**Comment by pj-infest** [comment]
Here is logs from console

```
roman@rmk-pc:~/agroapp/test$ protractor conf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started
F

Failures:
1) admin avtorization test should avtorizate as admin
  Message:
    Failed: unknown error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
    Watchers fired in the last 5 iterations: []
    http://errors.angularjs.org/1.5.2/$rootScope/infdig?p0=10&p1=%5B%5D
      (Session info: chrome=49.0.2623.108)
      (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.2.0-34-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 506 milliseconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: host: 'rmk-pc', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-34-generic', java.version: '1.7.0_80'
    Session ID: 70733d9c5143e563f76bba58632d98dc
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.6v59V5, chromedriverVersion=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a)}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.108, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
  Stack:
    WebDriverError: unknown error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
    Watchers fired in the last 5 iterations: []
    http://errors.angularjs.org/1.5.2/$rootScope/infdig?p0=10&p1=%5B%5D
      (Session info: chrome=49.0.2623.108)
      (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.2.0-34-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 506 milliseconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: host: 'rmk-pc', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-34-generic', java.version: '1.7.0_80'
    Session ID: 70733d9c5143e563f76bba58632d98dc
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.6v59V5, chromedriverVersion=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a)}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.108, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
        at WebDriverError (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
        at Object.checkLegacyResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/error.js:580:13)
        at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:360:15
        at Promise.invokeCallback_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
        at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:369:9)
    From: Task: Run it("should avtorizate as admin") in control flow
        at Object.<anonymous> (/usr/lib/node_modules/protractor/node_modules/jasminewd2/index.js:81:14)
        at /usr/lib/node_modules/protractor/node_modules/jasminewd2/index.js:18:5
        at Promise.invokeCallback_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/home/roman/agroapp/test/spec/authorization.js:13:5)
        at Object.<anonymous> (/home/roman/agroapp/test/spec/authorization.js:8:5)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)

1 spec, 1 failure
Finished in 3.142 seconds
Warning from "protractor-console-plugin" plugin: SEVERE: http://localhost:1340/js/application.js 84237:24 Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.5.2/$rootScope/infdig?p0=10&p1=%5B%5D
    at http://localhost:1340/js/application.js:71011:12
    at Scope.$digest (http://localhost:1340/js/application.js:87720:19)
    at Scope.$apply (http://localhost:1340/js/application.js:87946:24)
    at bootstrapApply (http://localhost:1340/js/application.js:72656:15)
    at Object.invoke (http://localhost:1340/js/application.js:75568:19)
    at doBootstrap (http://localhost:1340/js/application.js:72654:14)
    at Object.angular.resumeBootstrap (http://localhost:1340/js/application.js:72682:12)
    at <anonymous>:248:41
    at callFunction (<anonymous>:237:33)
    at <anonymous>:247:23
Warning from "protractor-console-plugin" plugin: SEVERE: http://localhost:1340/js/application.js 84237:24 Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.5.2/$rootScope/infdig?p0=10&p1=%5B%5D
    at http://localhost:1340/js/application.js:71011:12
    at Scope.$digest (http://localhost:1340/js/application.js:87720:19)
    at Scope.$apply (http://localhost:1340/js/application.js:87946:24)
    at done (http://localhost:1340/js/application.js:82267:47)
    at completeRequest (http://localhost:1340/js/application.js:82465:7)
    at XMLHttpRequest.requestLoaded (http://localhost:1340/js/application.js:82406:9)
Warning from "protractor-console-plugin" plugin: SEVERE: http://localhost:1340/js/application.js 71011:12 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.5.2/$rootScope/infdig?p0=10&p1=%5B%5D
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #01 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
roman@rmk-pc:~/agroapp/test$ 

```

**Comment by juliemr** [comment]
The problem is not that you're getting the error logs, but that your javascript is actually failing. Protractor tries to execute some scripts on your page to do waiting logic and such, but if those fail, the test will fail. Your application's errors are causing our scripts to fail.

You could potentially get around this by setting `browser.ignoresynchronizaton = true` and never using `by.binding` or `by.model`, but I would really suggest looking into your application to fix those errors. Even if they're not causing problems now they're not a good sign :)
