### ISSUE TITLE
TypeError: Column must be greater than or equal to 0

### ISSUE THREAD

**Issue by klinki** [angular/protractor#3103]
Hi,

I have an issue with running protractor. It crashes with following error:

```
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
[launcher] Error: TypeError: Column must be greater than or equal to 0, got -62
    at SourceMapConsumer_findMapping [as _findMapping] (C:\Users\David\AppData\Roaming\npm\node_modules\protractor\node_modules\source-map\lib\source-map\source-map-consumer.js:281:15)
    at SourceMapConsumer_originalPositionFor [as originalPositionFor] (C:\Users\David\AppData\Roaming\npm\node_modules\protractor\node_modules\source-map\lib\source-map\source-map-consumer.js:310:26)
    at mapSourcePosition (C:\Users\David\AppData\Roaming\npm\node_modules\protractor\node_modules\source-map-support\source-map-support.js:188:42)
    at wrapCallSite (C:\Users\David\AppData\Roaming\npm\node_modules\protractor\node_modules\source-map-support\source-map-support.js:323:20)
    at C:\Users\David\AppData\Roaming\npm\node_modules\protractor\node_modules\source-map-support\source-map-support.js:358:26
    at Array.map (native)
    at Function.prepareStackTrace (C:\Users\David\AppData\Roaming\npm\node_modules\protractor\node_modules\source-map-support\source-map-support.js:357:24)
    at trackRejection (C:\Users\David\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:1066:32)
    at reject (C:\Users\David\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:1131:5)
    at deferred.reject (C:\Users\David\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:633:16)
[launcher] Process exited with error code 100 
```

(It seems I'm not the only one with this issue: https://github.com/mgechev/angular2-seed/issues/365)

Bug report
---

- Node Version: `5.2.0`
- Protractor Version: `3.3.2`
- Operating System and Version `Windows 10`

**Comment by juliemr** [comment]
From the other bug, potentially a node version issue...

**Comment by NickTomlin** [comment]
@klinki I haven't been able to replicate this on a Windows 10 box using Protractor `3.3.2`. Can you provide some more details, like your protractor config and a small example file so I can reproduce?

**Comment by klinki** [comment]
I updated node version and now it works fine. I also changed the config quite a lot, so I cannot provide failing configuration. Sorry :(

**Comment by NickTomlin** [comment]
Interesting. I'm going to go ahead and close this for now. Please feel free to add any details if you get more data.
