### ISSUE TITLE
Second Browser page loading is  not working in IE and where as it is working in chrome and firefox.

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#3113]
Started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
F

Failures:
1) Testing suite testing spec
  Message:
    Failed: Error while running testForAngular: Page reload detected during async script (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 1.16 seconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: host: 'NBLAP99', ip: '192.168.7.38', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
    Session ID: 3f9314d6-b441-493e-8ace-29bbaed27d1d
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=intern
viour=dismiss, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, initialBrowserUrl=
ssApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
  Stack:
    Error: Failed: Error while running testForAngular: Page reload detected during async script (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 1.16 seconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: host: 'NBLAP99', ip: '192.168.7.38', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
    Session ID: 3f9314d6-b441-493e-8ace-29bbaed27d1d
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=intern
viour=dismiss, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, initialBrowserUrl=
ssApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
        at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:101:16
        at Promise.invokeCallback_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)

1 spec, 1 failure
Finished in 6.812 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] internet explorer #01 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1

**Comment by vivekbrahmadandi** [comment]
Here is my code

   browser.baseUrl = "https://angular.github.io/protractor/#/";
        browser.get(browser.baseUrl);
        browser2 = browser.forkNewDriverInstance();
        browser2.get(browser.baseUrl);


when the url is loading in second page it is throwing the issue

**Comment by sallojusuresh** [comment]
@vivekbrahmadandi 
May be it's time out issues. Increase Jasmine Time out and run it

**Comment by vivekbrahmadandi** [comment]
I have tried with increasing , can you able to reproduce that in your local

**Comment by vivekbrahmadandi** [comment]
U mean to increae defaultTimeoutInterval

**Comment by vivekbrahmadandi** [comment]
org.openqa.selenium.WebDriverException: Page reload detected during async script (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.71 seconds
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'NBLAP99', ip: '192.168.7.38', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
Session ID: 267eedf5-5ee6-428c-a1b9-7feecc39bcfd
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviou
r=dismiss, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, initialBrowserUrl=http://localhost:47127/, handlesAlerts=true, ie.forceCreateProcessAp
i=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
        at org.openqa.selenium.remote.RemoteWebDriver.executeAsyncScript(RemoteWebDriver.java:598)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
        at com.sun.proxy.$Proxy1.executeAsyncScript(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver.executeAsyncScript(EventFiringWebDriver.java:229)
        at org.openqa.selenium.remote.server.handler.ExecuteAsyncScript.call(ExecuteAsyncScript.java:56)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
16:38:40.043 WARN - Exception: Page reload detected during async script (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.71 seconds

**Comment by cnishina** [comment]
This appears to be a duplicated support question for #3065

**Comment by cnishina** [comment]
Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
