### ISSUE TITLE
Test does not pass: Angular never provided resumeBootstrap

### ISSUE THREAD

**Issue by cnishina** [angular/protractor#3115]
Spec:
```
node built/cli.js spec/altRootConf.js
```

Log:
```
running: node built/cli.js spec/altRootConf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started
FF

Failures:
1) finding elements when ng-app is nested should find an element by binding
  Message:
    Failed: Angular could not be found on the page http://localhost:8081/ng1/alt_root_index.html#/form : angular never provided resumeBootstrap
  Stack:
    Error: Angular could not be found on the page http://localhost:8081/ng1/alt_root_index.html#/form : angular never provided resumeBootstrap
        at /media/sf_protractor/built/protractor.js:683:17
        at Promise.invokeCallback_ (/media/sf_protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/media/sf_protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/media/sf_protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /media/sf_protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
        at /media/sf_protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:406:9)
    From: Task: Run beforeEach in control flow
        at Object.<anonymous> (/media/sf_protractor/node_modules/jasminewd2/index.js:81:14)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/media/sf_protractor/spec/altRoot/findelements_spec.js:2:3)
        at Object.<anonymous> (/media/sf_protractor/spec/altRoot/findelements_spec.js:1:1)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)

2) finding elements when ng-app is nested should find elements outside of angular
  Message:
    Failed: Angular could not be found on the page http://localhost:8081/ng1/alt_root_index.html#/form : angular never provided resumeBootstrap
  Stack:
    Error: Angular could not be found on the page http://localhost:8081/ng1/alt_root_index.html#/form : angular never provided resumeBootstrap
        at /media/sf_protractor/built/protractor.js:683:17
        at Promise.invokeCallback_ (/media/sf_protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/media/sf_protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/media/sf_protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /media/sf_protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
        at /media/sf_protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:406:9)
    From: Task: Run beforeEach in control flow
        at Object.<anonymous> (/media/sf_protractor/node_modules/jasminewd2/index.js:81:14)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/media/sf_protractor/spec/altRoot/findelements_spec.js:2:3)
        at Object.<anonymous> (/media/sf_protractor/spec/altRoot/findelements_spec.js:1:1)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)

2 specs, 2 failures
Finished in 21.489 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chromeANY #01 failed 2 test(s)
[launcher] overall: 2 failed spec(s)
[launcher] Process exited with error code 1
>>> fail: Error: expecting exit code: 0, actual: 1
```

**Comment by scoch** [comment]
+1 this, rolling back to protractor 3.1.1 resolved this issue. Wasted days thinking it was a local vagrant issue.

**Comment by kflorian** [comment]
+1 Same issue here with version 3.2 2

**Comment by juliemr** [comment]
Probably due to https://github.com/angular/protractor/commit/d3bd1702040cde5b9d0a3c1578d0d8e16597224c, investigating further...

**Comment by juliemr** [comment]
Yup. So change https://github.com/angular/protractor/commit/d3bd1702040cde5b9d0a3c1578d0d8e16597224c broke `browser.get` for Angular applications older than version `1.2.24`. Although it would be great if folks could move off of older versions like this, we know this isn't always possible and we do support older Angular versions. I'll be rolling back that commit.
