### ISSUE TITLE
 Simple click and callback not working. Jasmine error?- Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

### ISSUE THREAD

**Issue by hugomosh** [angular/protractor#3130]
I try to run a simple request to the server.  The server reply and angular shows the message but the test freezes and i get the error below.

I am new in e2e (testing in general). Am I doing something wrong or it is a bug. 

```
protractor protractor-e2e.js 
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.0.115:54697/wd/hub
Started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
F

Failures:
1) Registration view should ask for a proper email "The email must be a valid email address."
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at tryOnTimeout (timers.js:224:11)
        at Timer.listOnTimeout (timers.js:198:5)

Ran 1 of 9 specs
1 spec, 1 failure
Finished in 27.718 seconds
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #01 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```

protractor --version
Version 3.2.2

```
    beforeEach(function() {
        browser.get('#/account/register');
    });
    fit('should ask for a proper email "The email must be a valid email address."', function function_name(argument) {
        var inputname = element(by.model('userData.name')).sendKeys(fulanito.name);
        var inputname = element(by.model('userData.last_name')).sendKeys(fulanito.last_name);
        var inputemail = element(by.model('userData.email')).sendKeys('fulanito@ara');
        var inputpassword = element(by.model('userData.password')).sendKeys(fulanito.password);
        var inputpassword_confirmation = element(by.model('userData.password_confirmation')).sendKeys(fulanito.password);
       
        element(by.css('button[type="submit"]')).click().then(function() {
            expect(element(by.css('body')).getText())
            .toContain('The email must be a valid email address.');
        });
    
    });
```

My config file

```
exports.config = {
    allScriptsTimeout: 99999, 
    // The address of a running selenium server.
    //seleniumAddress: 'http://localhost:4444/wd/hub',
    // Capabilities to be passed to the webdriver instance.
    capabilities: {
        'browserName': 'chrome'
    },
     onPrepare: function() {
        // you can also add properties to globals here
        global.host= 'http://localhost:9000/';
    },
    keepAlive: true, //intesive testing
    baseUrl: 'http://localhost:9000',
    //Stand alone: 9001 
    //baseUrl: 'http://localhost:9001',
    framework: 'jasmine',
    // Spec patterns are relative to the current working directly when
    // protractor is called.
    //specs: ['test/e2e/*.js'],
    specs: ['test/e2e/register-spec.js'],
    // Options to be passed to Jasmine-node.
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 25000, 
        isVerbose: true,
        includeStackTrace: true
    }
};
```

**Comment by mgiambalvo** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/ protractor) to get help.

That said, the benefit of protractor is that it waits for your application to finish processing the changes you make to it during a test. So your test could be like this:

```
element(by.css('button[type="submit"]')).click();
expect(element(by.css('body')).getText())
    .toContain('The email must be a valid email address.');
```

If you have further questions, please follow up either in gitter or stackoverflow. Thanks!

**Comment by hugomosh** [comment]
@mgiambalvo 
I asked here and not in stackOverflow because I get the Jasmine error in both way (the way you recommend also). 
I can see the page has already the alert but Protractor freeze either way. And give me the not so helpfull error. So IMHO or ignorance it is a bug.

**Comment by mgiambalvo** [comment]
Is there a chance you could share your application source? You mentioned an
alert. Is the text you're looking for ('The email must be a valid email
address.') in an alert box, as in window.alert()? If so, you'll need to
look for it in a different way, as described in this StackOverflow question
<http://stackoverflow.com/questions/19879631/protractor-get-text-of-an-alert>.
Hope this helps!

On Fri, Apr 15, 2016 at 9:45 AM, Hugo Mosh Cardoza <notifications@github.com

**Comment by hugomosh** [comment]
Turns out I was making an error, as explained in stackoverflow: http://stackoverflow.com/questions/36653107/why-i-get-this-error-in-protractor-of-jasmine-timeout-and-how-can-i-test-correct/36702452#36702452

Thank you
