### ISSUE TITLE
Failed: Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"

### ISSUE THREAD

**Issue by Shyam-Chen** [angular/protractor#3178]
```ts
// hello-world.ts
import { Component } from 'angular2/core';

@Component({
  selector: 'hello-world',
  template: `
    <button (click)="onClickMe()">Click Me</button>
    <p>{{ clickMessage }}</p>
  `
})
export class HelloWorldComponent {
  public clickMessage: string = '';

  onClickMe() {
    this.clickMessage = 'Hello Angular 2';
  }
}
```
```js
// hello-world.e2e.js
describe('Hello World', function() {
  beforeEach(function() {
    browser.get('http://localhost:9876/');
    browser.ignoreSynchronization = false;
  });
  it('should have a content', function() {
    element(by.css('hello-world')).click();
    expect(element(by.css('hello-world p')).getText()).toEqual('Hello Angular 2');
  });
});
```
```coffee
# protractor.conf.coffee
class Config
  @directConnect: true
  @specs: ['./src/**/*.e2e.js']
  @exclude: []
  @capabilities:
    browserName: 'chrome'
  @baseUrl: 'http://localhost:9876/'
  @onPrepare: ->
    SpecReporter = require 'jasmine-spec-reporter'
    jasmine.getEnv().addReporter new SpecReporter displayStacktrace: true
    browser.ignoreSynchronization = true
  @framework: 'jasmine2'
  @jasmineNodeOpts:
    isVerbose: false
    showColors: true
    includeStackTrace: false
  @useAllAngular2AppRoots: true

if process.env.TRAVIS
  Config.capabilities = browserName: 'firefox'

exports.config = Config
```
### ChromeDriver
```bash
# messages
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
Spec started
Started

  Hello World
    ✗ should have a content
      - Failed: Error while waiting for Protractor to sync with the page: "windo
w.getAllAngularTestabilities is not a function"
F
**************************************************
*                    Failures                    *
**************************************************

1) Hello World should have a content
  - Failed: Error while waiting for Protractor to sync with the page: "window.ge
tAllAngularTestabilities is not a function"

Executed 1 of 1 spec (1 FAILED) in 15 secs.


Failures:
1) Hello World should have a content
  Message:
    Failed: Error while waiting for Protractor to sync with the page: "window.ge
tAllAngularTestabilities is not a function"
  Stack:
    Error: Failed: Error while waiting for Protractor to sync with the page: "wi
ndow.getAllAngularTestabilities is not a function"
        at D:\Angular2TS-Starter-Kit\node_modules\jasminewd2\index.js:101:16
        at Promise.invokeCallback_ (D:\Angular2TS-Starter-Kit\node_modules\selen
ium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (D:\Angular2TS-Starter-Kit\node_modules\selenium-w
ebdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (D:\Angular2TS-Starter-Kit\node_modules\seleni
um-webdriver\lib\promise.js:2773:21)
        at D:\Angular2TS-Starter-Kit\node_modules\selenium-webdriver\lib\promise
.js:2652:27
        at D:\Angular2TS-Starter-Kit\node_modules\selenium-webdriver\lib\promise
.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)

1 spec, 1 failure
Finished in 15.345 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #01 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```
### FirefoxDriver
mgechev/angular2-seed#732
```bash
# messages
Using FirefoxDriver directly...
[launcher] Running 1 instances of WebDriver
Spec started
Started
  Hello World
    ✗ should have a content
      - Failed: Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"
F
**************************************************
*                    Failures                    *
**************************************************
1) Hello World should have a content
  - Failed: Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"
Executed 1 of 1 spec (1 FAILED) in 0.202 sec.
Failures:
1) Hello World should have a content
  Message:
    Failed: Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"
  Stack:
    Error: Failed: Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"
        at /home/travis/build/Shyam-Chen/Angular2TS-Starter-Kit/node_modules/jasminewd2/index.js:101:16
        at Promise.invokeCallback_ (/home/travis/build/Shyam-Chen/Angular2TS-Starter-Kit/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/home/travis/build/Shyam-Chen/Angular2TS-Starter-Kit/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/home/travis/build/Shyam-Chen/Angular2TS-Starter-Kit/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at asyncRun (/home/travis/build/Shyam-Chen/Angular2TS-Starter-Kit/node_modules/selenium-webdriver/lib/promise.js:2652:27)
        at /home/travis/build/Shyam-Chen/Angular2TS-Starter-Kit/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
1 spec, 1 failure
Finished in 0.205 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] firefox #01 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```

**Comment by MoPro01** [comment]
Hello. We are running into the same problem with Angular 2, protractor and Cucumber framework combination with `browser.ignoreSynchronization = false` and  `useAllAngular2AppRoots: true`

**Comment by Shyam-Chen** [comment]
version: rc.1 (OK)

**Comment by mkreis** [comment]
I receive the same error, both with Angular2 Beta 17 and Angular2 RC1 ... did anyone figure out how to fix this?

**Comment by mkreis** [comment]
...I think I found the cause for the error: There was the call of
`browser.driver.get('http://localhost:8000'); `
was incorrect/missing.

**Comment by MoPro01** [comment]
We are running end-2-end tests and in our particular case, the problem is caused by mixing Angular 1 and Angular 2 applications. I need to establish user session in Angular 1 page, and then transition to Angular 2 page. `useAllAngular2AppRoots: true` is not present in Angular 1 app, which is exactly what the error is about for me. I didn't figure out how to make this work yet.

**Comment by bringking** [comment]
@Shyam-Chen how did you resolve this issue? It still persists for us using NG2 RC1 in a hybrid environment with NG1 (1.5.3).

**Comment by Shyam-Chen** [comment]
@bringking I upgraded to rc.1 can be successful.

**Comment by shssoichiro** [comment]
I was running into this problem as well, on NG2 RC1, non-hybrid. For whatever reason, `rm -rf node_modules` and `npm install` fixed it. I think protractor was trying to use a chromedriver other than the one it was installing through webdriver-manager, and weird things were happening as a result. (Also make sure you don't manually add `selenium-webdriver` to your `package.json`)

**Comment by JT-Bruch** [comment]
@bringking Were you able to make this work?

**Comment by bringking** [comment]
@JT-Bruch I was not, but the Angular team is tracking the issue here - https://github.com/angular/angular/issues/9407 looks like they have a fix targeted for RC5

**Comment by edgarechm** [comment]
Funny how people close issues because they found the solution... BUT DON'T SHARE IT!!

Thanks for nothing!
