### ISSUE TITLE
Override jasmin's function, error when starting tests

### ISSUE THREAD

**Issue by alibabaih** [angular/protractor#3184]
Good day!
I've overridden jasmin's `it` function in the protractor `onPrepare`:

```
var originalIt = global.it;
        global.it = function () {


            function waitForSpinner() {

                element(by.css('.uil-element-loader-wrapper')).isPresent().then((el) => { //check if element on the page, if not don't wait at all

                    if(el) {
                        browser.wait(function () {
                            return element(by.css('.uil-element-loader-wrapper')).getAttribute('style').then((style) => {
                                if ((style.indexOf('block') > -1)) { //console.log('Spinner is here ' + (style.indexOf('block') > -1) + style);
                                    setTimeout(waitForSpinner, 100);
                                } else { //console.log('Spinner is gone');
                                    return true;
                                }
                            });
                        });
                    } else {
                        browser.wait(element(by.css('body')).isPresent());
                    }
                });

            }

            waitForSpinner();

            return originalIt.apply(this, arguments);
        };
```

but have some problem when starting tests:

```
[13:45:46] E/launcher - Process exited with error code 1

/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:654
    throw error;
    ^
Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
Trace: { [Error: protractor exited with code 1]
  message: 'protractor exited with code 1',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-protractor',
  __safety: { toString: [Function: bound ] } }
    at emitOne (events.js:82:20)
    at Stream.emit (events.js:169:7)
    at ChildProcess.<anonymous> (/node_modules/gulp-protractor/index.js:64:13)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
Although if run tests with commented waitForSpinner(); everything is ok.

**Comment by NickTomlin** [comment]
Hi there!

Because of it's usage/debugging nature, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
