### ISSUE TITLE
Feature Request - Take screenshot of a particular element (instead of the whole page)

### ISSUE THREAD

**Issue by ShobanaV** [angular/protractor#3215]
Hi,

Is there any way to take screenshot of a particular element (Eg. svg, canvas etc.) in protractor?

In my application, I need to compare graph with an expected graph. I want to take screenshot of that particular element inside which the graph is present.

**Comment by mgiambalvo** [comment]
This would require Webdriver support, so you might try suggesting it with them. Also, you can accomplish this today by taking a screenshot, finding the bounding box of the element you're interested in, then cropping the image. There are details in [this StackOverflow question](http://stackoverflow.com/questions/13832322/how-to-capture-the-screenshot-of-a-specific-element-rather-than-entire-page-usin).

**Comment by henrahmagix** [comment]
The documentation suggests that you can call `.takeScreenshot()` on an `ElementFinder`: http://www.protractortest.org/#/api?view=webdriver.WebElement.prototype.takeScreenshot

Should the `foo` element in that be changed to `browser`?

**Comment by mgiambalvo** [comment]
No, the doc is right, and you can sometimes take screenshots of elements that way. However, it isn't supported in all drivers, including the latest chrome driver (2.21). Taking a screenshot of the entire page and cropping is the only method that currently works for all browsers.

**Comment by wswebcreation** [comment]
@evilaliv3 
It is still not supported with 2.30

**Comment by noambenami** [comment]
Still doesn't seem to be supported in 2.40. Shame; taking a full screenshot and cropping is actually surprisingly fragile, as you have to deal with scrolling issues, and, obviously, extraordinarily resource intensive.

**Comment by djom20** [comment]
Still doesn't seem to be supported in 5.4.0. When I tried to take the screenshot with the element I got this error:

```
UnsupportedOperationError: unknown command: session/1a547bd881965dc13edfabd34458181a/element/0.6131010969813735-6/screenshot
    at WebDriverError (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/selenium-webdriver/lib/error.js:27:5)
    at UnsupportedOperationError (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/selenium-webdriver/lib/error.js:343:5)
    at parseHttpResponse (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/selenium-webdriver/lib/http.js:534:11)
    at doSend.then.response (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebElement.takeScreenshot(false)
    at Driver.schedule (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at WebElement.schedule_ (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
    at WebElement.takeScreenshot (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/selenium-webdriver/lib/webdriver.js:2379:17)
    at actionFn (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/protractor/built/element.js:89:44)
    at Array.map (native)
    at actionResults.getWebElements.then (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/protractor/built/element.js:461:65)
    at ManagedPromise.invokeCallback_ (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/selenium-webdriver/lib/promise.js:2927:27)Error
    at ElementArrayFinder.applyAction_ (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/protractor/built/element.js:459:27)
    at ElementArrayFinder.(anonymous function) [as takeScreenshot] (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/protractor/built/element.js:91:29)
    at ElementFinder.(anonymous function) [as takeScreenshot] (/Users/qadeveloper/Documents/projects/automatedsuites/node_modules/protractor/built/element.js:831:22)
    at Taker.answersDigitalSignatureQuestion (/Users/qadeveloper/Documents/projects/automatedsuites/support/helpers/taker.js:289:40)
    at Taker.answersQuestion (/Users/qadeveloper/Documents/projects/automatedsuites/support/helpers/taker.js:466:9)
    at World.(anonymous) (/Users/qadeveloper/Documents/projects/automatedsuites/step_definitions/questionnaire_steps/taking_questionnaire_steps/taker_answers_long_text_question_in_questionnaire_steps.js:12:9)
```

**Comment by djom20** [comment]
@heathkit Could you review if still isn't supported this feature?
