### ISSUE TITLE
browser.sendKeys() throws ENAMETOOLONG with long strings in FF v46

### ISSUE THREAD

**Issue by NSkelsey** [angular/protractor#3245]
## Bug report

It seems that within the firefox webdriver there is a bug when sending output to a text area. The same test works fine in Chrome locally and in Firefox on other non OSX machines. If you firmly believe this is not an issue with protractor, but with the Webdriver please point me to the place to report the issue :)
- Node Version: `v4.4.3`
- Protractor Version: `3.2.2`
- Browser(s): `Firefox v46.0.1`
- Operating System and Version `OSX 10.11.5`
- Your protractor configuration file: [linked here](https://github.com/globaleaks/GlobaLeaks/blob/devel/client/tests/end2end/protractor-coverage.config.js)
- A relevant example test: [test-receiver-first-login](https://github.com/globaleaks/GlobaLeaks/blob/devel/client/tests/end2end/test-receiver-first-login.js#L105-L111)
  ### Output from running the test:

The relevant output from protractor's failure on `element(by.model('preferences.pgp_key_public')).sendKeys(pgp_key);` seems to interpret a `textarea` as a file input:

``` bash
1) receiver first login should be able to load his/her public PGP key
  Message:
    Failed: ENAMETOOLONG: name too long, stat '-----BEGIN PGP PUBLIC KEY BLOCK-----
    Version: GnuPG v1
    mQINBFUlGs8BEAC8geW+vfaHNXJEbGKroFjgSywg1h8JBRB6XbDFoV2WWJKFlt51
    d0w6U5aj4N1Xx/xpa+qPEt/oYjEouXza0JuPo0SVHhzkozSrzMjQkziSsV9NXxtp
    3ioaat0MyOBQ1XAAn7tONCv8C7dpz+BrUXPrU+0Gh6+Q0nCR6wYtgj9ztzP4JdgW
    fiznLQe04Ah5MB+YJEndQi12HHPUzEedX32ylmfkdxWAJ8sd+YQKRFHPWUnt8tG4
    OOm1RORgW/P3oE1RN9VEqof2ekp+DMe5v7zWEPAWyxTKYEWaXw3p2Rv9v3cdGX3N
    t1HnA30Iqd3PeBGKwxdf/UKO5vjbzKJZcovKOdNdtvelZYWRBVZ347MEItz1mXYa
    YNrX2L2omQ0g8ujCWRnPQSCj7UEt5wTqJ2DSftrJTCbVxa8olUSz2iaQvoJIOxBW
    ZiwHqXc5SUdf2tuuFYmb4y/VifN5aShZKimf0KC0jwOWPVaF1EiEzMlYscvF4aDg
    DymPdb2y9+YUGW5a2dhRCCNx7g66hruN5Q0bZHfy+bkGUN+oixunPtmV7NAMIbzF
    pbpfkVwh+2wlwSA1zI6CL4WG8YIwQFBWq0Mfh29c3ejII0ja3A7XhYo3TzVy5Qjt
    KBSsEZRJJQ/i9hHdvNidPYi7AvdH1FQ2koKCMHdHxM1hvHZP9/2hh5UClQARAQAB
    tDVHaW92YW5uaSBQZWxsZXJhbm8gPGdpb3Zhbm5pLnBlbGxlcmFub0BldmlsYWxp
    djMub3JnPokCPgQTAQIAKAUCVSUazwIbAwUJA8JnAAYLCQgHAwIGFQgCCQoLBBYC
    AwECHgECF4AACgkQ9MvVvWeg8Yfwmg//WAisG7htbXnmK9stPcjpHaiHb/o031f5
    8SMlhhrAKWokMDHxkZFzMdRh4OIRkdBUOQt0gDG4xdWv5AulmsVn3PegWFzQchJQ
    IbXmdOw938iLSAustYYxVymglYWW8F6E/+yVU6JRfeAWcMzleoxpAE6NG7Mtv/U+
    tgGUpcMuTwXz8dAPphfoc0rteiNomeAkLmdtShE2rN6Wt6wW5JA40ClqhzagmVgR
    2bF3/4CRj1Bnjkxxza5Y5kPYHFKJWPFunJxgfQdqV8y3Y9ig09AJsmdCweK8h93T
    p6c36CR43y6sBuHxG3G+szl4TI/Hjr+/UOTtGah0ZkcYrZV52JiulBtvtbJdAZk8
    tIAwcMYjA9Xn0b5XY+zTdDRfZRO09lWBRahTCA7iBhz8LIWu6yn3YN2cVvFU4on5
    8y0dVLGtilnlWm/oPCMxCTXxxrW13lSKarHLOBlGF4LHcfN2JCzPXj+a9Z2socdD
    S9TVLJYDVd8pkUPDf0hPGr3HhCegDQU0+4kbAN7ltCJM32AKfxTjYHzjND7xbfJQ
    IV9GwQAWttkVgMC3LqeoGPa94okGwdW6LIlpfm90z5g8stjICedCVgZtCgP/aCnr
    OPV6OWLredhwlcgJSO76aO3l5eDyylLrQtdyjuA4yDHJ5Qnppk9ACFLcAYh9RaRp
    BT0R5OIB7rC5Ag0EVSUazwEQALZI8/7R4n2tRjayMgC/NOQhv38Hhlz1zmNgSU8s
    XoM04yMP1281DA3OfNoeS20cBrhzYXhFWkGuhxCY+T6Rv7YPKxc3pVr4cpz6IdCP
    1LBW49vQU8g1w67Op3sEHYDf9OpvjOySZz89BGrGffbbrSU4lyuIb0MgZVlvwePV
    UqtBOf1ydrhK+tPK0Um5q1sTxaL3odq2hDsgjQeu77nvptpsRlVODVACegdYA55m
    fo4yGh3zq/WSSjd21inmYRyZ9+hfasia1yAPXIQ56U4MYtC6rm1X+7me2xEPc+Eo
    IPYTYM7M3ssDLg15QH7wMiCBkNQzbWluZMBs/xP/4zEGB3cprit1Q7ZiXegowuZ+
    bgK9LExwPSMnNgu9BDkfkDo+/ATlAdc0CpbCvUHwQi0ogq599zcNMCzcgexJXAkp
    0if8OUoEf4I4/U6EMGsOyPsjlbBt++Iv7OTh0ZvViBSy8N+jW0cEVY1G2NpfKM2K
    UsPs6WevGOaBZ/Ipa0xngpkFexxjGV//DTKKk0WCSA7KHCe1bRYOXrwn3JmYsSDb
    EPmqT2xaOOCMMP8rPIA2ugA7+46IgrZIOKsxRwXJXhynD6gx60VlNzEvVACtNtXW
    VlTdMQqA9Fb/ZPq9ijx2W1UqFb4xBSVag0Lrz1enJBEcEPCTrJr7iEYg5nEmF4Ph
    yWHZABEBAAGJAiUEGAECAA8FAlUlGs8CGwwFCQPCZwAACgkQ9MvVvWeg8YelFhAA
    gPo1by0GoWXQ/CDPFJBeoMfsJWW912kzO9ERWhYLGaZFF9c40jwyye5VlNPPYvIc
    dwBYufZP3H5BUbko8tHobqsSn4OONqJq1+QfHRDJEOc2NbjFBH2OM9yGPgAuE5sM
    aV5uBFxZtmCrVaS3BmUg1ddkAB7DXZoWn6I0YTYDZ5ShTBjIM1LzFF552pIiG8HV
    9zcSMtAAYIt0sAYVcdrlMC6ndeBJlKXSujaRNy2yvLrMqGBcW9KdxXOlMk+oFOaM
    nyiYiqX4lgEQevzwhG9cW4HcbhWNrW4EE/qKndvjZapRqNu3BZrhxJ1LnCePgS6A
    QWeH1e3AN8wDrTRFsKmirTpvnL5SNxbnfbJj9sCf/1oDFYR3Uhu6hU+6ntEB0DiK
    5gRGeVlC5G/39HXxDwaIfngWIeHINI25za8ujn2NMleLDQstVw4Ku8KLOuFiQYrj
    0lZ3kRpG4qSri1uBM+JY2YS3xuY70ZQh8P2iXr1aQXIzdIBtss684ins+ktlmRq6
    BVYOztLuXzyxvxpotLbkTYWaDvdm81YMD/2IerGEND2TF5uEWSa/xGzjf3IGS3va
    iLSjzmFCQC28Mr/sA7y3w5Phf9Jd5JH7pta5X0VvGGIuwaegrj6tGPfBTNlO5wxG
    QrR0ZxqlZ0Ff1QXnRjFIc1FDjSQ9LEXw7qZ3VjBFBrY=
    =/2N2
    -----END PGP PUBLIC KEY BLOCK-----'
  Stack:
    Error: ENAMETOOLONG: name too long, stat '-----BEGIN PGP PUBLIC KEY BLOCK-----
    Version: GnuPG v1
    mQINBFUlGs8BEAC8geW+vfaHNXJEbGKroFjgSywg1h8JBRB6XbDFoV2WWJKFlt51
    d0w6U5aj4N1Xx/xpa+qPEt/oYjEouXza0JuPo0SVHhzkozSrzMjQkziSsV9NXxtp
    3ioaat0MyOBQ1XAAn7tONCv8C7dpz+BrUXPrU+0Gh6+Q0nCR6wYtgj9ztzP4JdgW
    fiznLQe04Ah5MB+YJEndQi12HHPUzEedX32ylmfkdxWAJ8sd+YQKRFHPWUnt8tG4
    OOm1RORgW/P3oE1RN9VEqof2ekp+DMe5v7zWEPAWyxTKYEWaXw3p2Rv9v3cdGX3N
    t1HnA30Iqd3PeBGKwxdf/UKO5vjbzKJZcovKOdNdtvelZYWRBVZ347MEItz1mXYa
    YNrX2L2omQ0g8ujCWRnPQSCj7UEt5wTqJ2DSftrJTCbVxa8olUSz2iaQvoJIOxBW
    fiznLQe04Ah5MB+YJEndQi12HHPUzEedX32ylmfkdxWAJ8sd+YQKRFHPWUnt8tG4
    OOm1RORgW/P3oE1RN9VEqof2ekp+DMe5v7zWEPAWyxTKYEWaXw3p2Rv9v3cdGX3N
    t1HnA30Iqd3PeBGKwxdf/UKO5vjbzKJZcovKOdNdtvelZYWRBVZ347MEItz1mXYa
    YNrX2L2omQ0g8ujCWRnPQSCj7UEt5wTqJ2DSftrJTCbVxa8olUSz2iaQvoJIOxBW
    ZiwHqXc5SUdf2tuuFYmb4y/VifN5aShZKimf0KC0jwOWPVaF1EiEzMlYscvF4aDg
    DymPdb2y9+YUGW5a2dhRCCNx7g66hruN5Q0bZHfy+bkGUN+oixunPtmV7NAMIbzF
    pbpfkVwh+2wlwSA1zI6CL4WG8YIwQFBWq0Mfh29c3ejII0ja3A7XhYo3TzVy5Qjt
    KBSsEZRJJQ/i9hHdvNidPYi7AvdH1FQ2koKCMHdHxM1hvHZP9/2hh5UClQARAQAB
    tDVHaW92YW5uaSBQZWxsZXJhbm8gPGdpb3Zhbm5pLnBlbGxlcmFub0BldmlsYWxp
    djMub3JnPokCPgQTAQIAKAUCVSUazwIbAwUJA8JnAAYLCQgHAwIGFQgCCQoLBBYC
    AwECHgECF4AACgkQ9MvVvWeg8Yfwmg//WAisG7htbXnmK9stPcjpHaiHb/o031f5
    8SMlhhrAKWokMDHxkZFzMdRh4OIRkdBUOQt0gDG4xdWv5AulmsVn3PegWFzQchJQ
    IbXmdOw938iLSAustYYxVymglYWW8F6E/+yVU6JRfeAWcMzleoxpAE6NG7Mtv/U+
    tgGUpcMuTwXz8dAPphfoc0rteiNomeAkLmdtShE2rN6Wt6wW5JA40ClqhzagmVgR
    2bF3/4CRj1Bnjkxxza5Y5kPYHFKJWPFunJxgfQdqV8y3Y9ig09AJsmdCweK8h93T
    p6c36CR43y6sBuHxG3G+szl4TI/Hjr+/UOTtGah0ZkcYrZV52JiulBtvtbJdAZk8
    tIAwcMYjA9Xn0b5XY+zTdDRfZRO09lWBRahTCA7iBhz8LIWu6yn3YN2cVvFU4on5
    8y0dVLGtilnlWm/oPCMxCTXxxrW13lSKarHLOBlGF4LHcfN2JCzPXj+a9Z2socdD
    S9TVLJYDVd8pkUPDf0hPGr3HhCegDQU0+4kbAN7ltCJM32AKfxTjYHzjND7xbfJQ
    IV9GwQAWttkVgMC3LqeoGPa94okGwdW6LIlpfm90z5g8stjICedCVgZtCgP/aCnr
    OPV6OWLredhwlcgJSO76aO3l5eDyylLrQtdyjuA4yDHJ5Qnppk9ACFLcAYh9RaRp
    BT0R5OIB7rC5Ag0EVSUazwEQALZI8/7R4n2tRjayMgC/NOQhv38Hhlz1zmNgSU8s
    XoM04yMP1281DA3OfNoeS20cBrhzYXhFWkGuhxCY+T6Rv7YPKxc3pVr4cpz6IdCP
    1LBW49vQU8g1w67Op3sEHYDf9OpvjOySZz89BGrGffbbrSU4lyuIb0MgZVlvwePV
    UqtBOf1ydrhK+tPK0Um5q1sTxaL3odq2hDsgjQeu77nvptpsRlVODVACegdYA55m
    fo4yGh3zq/WSSjd21inmYRyZ9+hfasia1yAPXIQ56U4MYtC6rm1X+7me2xEPc+Eo
    IPYTYM7M3ssDLg15QH7wMiCBkNQzbWluZMBs/xP/4zEGB3cprit1Q7ZiXegowuZ+
    bgK9LExwPSMnNgu9BDkfkDo+/ATlAdc0CpbCvUHwQi0ogq599zcNMCzcgexJXAkp
    0if8OUoEf4I4/U6EMGsOyPsjlbBt++Iv7OTh0ZvViBSy8N+jW0cEVY1G2NpfKM2K
    UsPs6WevGOaBZ/Ipa0xngpkFexxjGV//DTKKk0WCSA7KHCe1bRYOXrwn3JmYsSDb
    EPmqT2xaOOCMMP8rPIA2ugA7+46IgrZIOKsxRwXJXhynD6gx60VlNzEvVACtNtXW
    VlTdMQqA9Fb/ZPq9ijx2W1UqFb4xBSVag0Lrz1enJBEcEPCTrJr7iEYg5nEmF4Ph
    yWHZABEBAAGJAiUEGAECAA8FAlUlGs8CGwwFCQPCZwAACgkQ9MvVvWeg8YelFhAA
    gPo1by0GoWXQ/CDPFJBeoMfsJWW912kzO9ERWhYLGaZFF9c40jwyye5VlNPPYvIc
    dwBYufZP3H5BUbko8tHobqsSn4OONqJq1+QfHRDJEOc2NbjFBH2OM9yGPgAuE5sM
    aV5uBFxZtmCrVaS3BmUg1ddkAB7DXZoWn6I0YTYDZ5ShTBjIM1LzFF552pIiG8HV
    aV5uBFxZtmCrVaS3BmUg1ddkAB7DXZoWn6I0YTYDZ5ShTBjIM1LzFF552pIiG8HV                                                                
    9zcSMtAAYIt0sAYVcdrlMC6ndeBJlKXSujaRNy2yvLrMqGBcW9KdxXOlMk+oFOaM
    nyiYiqX4lgEQevzwhG9cW4HcbhWNrW4EE/qKndvjZapRqNu3BZrhxJ1LnCePgS6A
    QWeH1e3AN8wDrTRFsKmirTpvnL5SNxbnfbJj9sCf/1oDFYR3Uhu6hU+6ntEB0DiK
    5gRGeVlC5G/39HXxDwaIfngWIeHINI25za8ujn2NMleLDQstVw4Ku8KLOuFiQYrj
    0lZ3kRpG4qSri1uBM+JY2YS3xuY70ZQh8P2iXr1aQXIzdIBtss684ins+ktlmRq6
    BVYOztLuXzyxvxpotLbkTYWaDvdm81YMD/2IerGEND2TF5uEWSa/xGzjf3IGS3va
    iLSjzmFCQC28Mr/sA7y3w5Phf9Jd5JH7pta5X0VvGGIuwaegrj6tGPfBTNlO5wxG
    QrR0ZxqlZ0Ff1QXnRjFIc1FDjSQ9LEXw7qZ3VjBFBrY=
    =/2N2
    -----END PGP PUBLIC KEY BLOCK-----'
        at Error (native)
    From: Task: WebElement.sendKeys()
        at WebElement.sendKeys (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/webdri
ver.js:1885:31)
        at actionFn (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/built/element.js:76:30)
        at Array.map (native)
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/built/element.js:382:38
        at Promise.invokeCallback_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/pr
omise.js:1329:14)
        at TaskQueue.execute_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise
.js:2790:14)
        at TaskQueue.executeNext_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/pro
mise.js:2773:21)
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:369:9)
    Error
        at [object Object].ElementArrayFinder.applyAction_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/built/element.
js:380:21)
        at [object Object].ElementArrayFinder.(anonymous function) [as sendKeys] (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/pro
tractor/built/element.js:78:17)
        at [object Object].ElementFinder.(anonymous function) [as sendKeys] (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protract
or/built/element.js:708:7)
        at Object.<anonymous> (/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-receiver-first-login.js:108:53)
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/jasminewd2/index.js:96:23
        at new Promise (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:104
        at new Promise (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:104
3:7)
        at controlFlowExecute (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/jasminewd2/index.js:82:18)
        at TaskQueue.execute_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise
.js:2790:14)
        at TaskQueue.executeNext_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/pro
mise.js:2773:21)
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2697:25
    From: Task: Run it("should be able to load his/her public PGP key") in control flow
        at Object.<anonymous> (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/jasminewd2/index.js:81:14)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-receiver-first-login.js:105:3)
        at Object.<anonymous> (/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-receiver-first-login.js:55:1)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)

```

If sendKeys is commanded to insert the values character by character in a for loop a different but related error message is thrown (here's the full log):

```
Running "protractor:test" (protractor) task
DEBUG - Running with --troubleshoot
DEBUG - Protractor version: 3.2.2
DEBUG - Your base url for tests is http://127.0.0.1:8082/
DEBUG - Attempting to find the SeleniumServerJar in the default location used by webdriver-manager
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://10.13.17.35:64796/wd/hub
DEBUG - WebDriver session successfully started with capabilities Capabilities {
  'applicationCacheEnabled' => true,
  'rotatable' => false,
  'handlesAlerts' => true,
  'databaseEnabled' => true,
  'version' => '46.0.1',
  'platform' => 'MAC',
  'nativeEvents' => false,
  'acceptSslCerts' => true,
  'webdriver.remote.sessionid' => 'ebe83fdd-4dae-41fb-a724-85e1391d528e',
  'webStorageEnabled' => true,
  'locationContextEnabled' => true,
  'browserName' => 'firefox',
  'takesScreenshot' => true,
  'javascriptEnabled' => true,
  'cssSelectorsEnabled' => true }
DEBUG - Running with spec files /Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-init.js,/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-admin-perform-wizard.js,/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-admin-login.js,/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-admin-navigate-sections.js,/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-admin-configure-node.js,/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-admin-configure-mail.js,/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-admin-configure-advanced.js,/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-admin-users.js,/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-admin-contexts.js,/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-receiver-first-login.js,/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-globaleaks-process.js,/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-file-consistency.js
Started
F

Failures:
1) test file consistency Uploaded and encrypted files should match downloaded and decrypted files
  Message:
    Failed: Uploading directories is not supported: /
  Stack:
    TypeError: Uploading directories is not supported: /
        at TypeError (native)
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:356:15
        at Promise.invokeCallback_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2697:25
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    From: Task: WebElement.sendKeys()
        at WebElement.sendKeys (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:1885:31)
        at actionFn (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/built/element.js:76:30)
        at Array.map (native)
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/built/element.js:382:38
        at Promise.invokeCallback_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:369:9)
    Error
        at [object Object].ElementArrayFinder.applyAction_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/built/element.js:380:21)
        at [object Object].ElementArrayFinder.(anonymous function) [as sendKeys] (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/built/element.js:78:17)
        at [object Object].ElementFinder.(anonymous function) [as sendKeys] (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/built/element.js:708:7)
        at /Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/pages.js:48:18
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/built/element.js:663:16
        at Promise.invokeCallback_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
        at /Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    From: Task: Run fit("Uploaded and encrypted files should match downloaded and decrypted files") in control flow
        at Object.<anonymous> (/Users/nskelsey/projects/GlobaLeaks/client/node_modules/protractor/node_modules/jasminewd2/index.js:81:14)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-file-consistency.js:139:5)
        at Object.<anonymous> (/Users/nskelsey/projects/GlobaLeaks/client/tests/end2end/test-file-consistency.js:16:1)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)

Ran 1 of 40 specs
1 spec, 1 failure
Finished in 19.23 seconds
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] firefox #01 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```
### Steps to reproduce the bug:

A believe a simple mockup in OSX 10.11 with FF45 where a `<textarea>` with a large input to `sendKeys(largeString)` is used will generate the error.

For the second error replace the send_keys(pgp_key) with:

```
    for (var i = 0; i < largetString.length; i++) {
      var c = largeString[i];
      textAreaElem.sendKeys(c);
    }
```

**Comment by juliemr** [comment]
The sendKeys command just calls that API for FirefoxDriver, so yes, this is probably a webdriver issue :) Can you please report at https://github.com/SeleniumHQ/selenium/issues?

**Comment by NSkelsey** [comment]
Thanks! Reported in SeleniumHQ/selenium#2164.

**Comment by juliemr** [comment]
I'm going to go ahead and close this since the external bug is filed and I don't think it's providing much value to keep track of it in our repo as well.
