### ISSUE TITLE
Timeout expired waiting for async script in IE11 

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#3252]
Bug report
---

- Node Version: v4.2.0
- Protractor Version: v3.3.0
- Browser(s): Internet Explorer 11
- Operating System and Version :Windows 7  32 bit
- protractor configuration file:
conf.js
=======
exports.config = {
    baseUrl: 'https://eotar-devel.com/ui_topup/erecharge/aui',
    seleniumArgs: ['-Dwebdriver.ie.driver=C:\\Users\\vivekb\\AppData\\Roaming\\npm\\node_modules\\protractor\\selenium\\IEDriverServer_Win32_2.52.0.exe'],
    //seleniumAddress: 'http://localhost:4444/wd/hub',
    suites: {
        NDCreationAndReject: './specs/NDEnrollAndReject.js',
    },
    capabilities: {
        browserName: 'internet explorer'
    },
    allScriptsTimeout: 95000,
    framework: 'jasmine2',
    getPageTimeout: 50000,
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 950000 //950000
    },
    onPrepare: function() {
        browser.driver.manage().window().maximize();
    }
};

- **Output from running the test**
  Stack:
`ScriptTimeoutError: Timeout expired waiting for async script (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 95.09 seconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: host: 'NBLAP99', ip: '192.168.7.69', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
    Session ID: 24760ae1-04e5-4095-a47b-0a375dc9f60f
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=fal
viour=dismiss, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=fal
sApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
        at WebDriverError (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\error.js:27:10)
        at ScriptTimeoutError (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\error.js:280:10)
        at Object.checkLegacyResponse (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\error.js:580:13)
        at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:360:15
        at Promise.invokeCallback_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
        at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2652:27
        at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
        at process._tickCallback (node.js:366:9)
    From: Task: Run afterEach in control flow
        at Object.<anonymous> (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:81:14)
        at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:101:16
        at Promise.invokeCallback_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
    From asynchronous test:
    Error
        at Suite.<anonymous> (D:\EOTARAutomation\specs\NDEnrollAndApprove.js:4:5)
        at Object.<anonymous> (D:\EOTARAutomation\specs\NDEnrollAndApprove.js:1:1)
        at Module._compile (module.js:435:26)
        at Object.Module._extensions..js (module.js:442:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:311:12)`

**Comment by cnishina** [comment]
Please use markup for logs/configs. This is difficult to read.

There is not enough information: What version of IE driver are you using? What are you trying to do in your test? When your test fails, what does webdriver-manager logs show? Is it sending a bunch of waitForAngular via async execute?

Also, reading the description of this issue this might be a better Stackoverflow question because this appears to be a support question.

**Comment by vivekbrahmadandi** [comment]
IE 11 we are using. Webdriver logs shows the same error log which protractor cosnsole is showing

**Comment by vivekbrahmadandi** [comment]
http://stackoverflow.com/questions/37134505/how-to-get-rid-of-timeout-expired-waiting-for-async-script-on-ie11-browser-when/37134752?noredirect=1#comment61811166_37134752

**Comment by vivekbrahmadandi** [comment]
Any Update on this issue

**Comment by cnishina** [comment]
Unfortunately no. There is not enough information to reproduce this stack trace on the information provided. Please refer back to providing the correct information when opening a bug. And after reading this again, this does sound like a support issue and not a bug. Please read the issue template:

```
2. Make sure you are not asking a usage or debugging question.
```

Thanks.
