### ISSUE TITLE
Cannot read property 'timeout' of undefined when a describe() is nested directly inside another describe()

### ISSUE THREAD

**Issue by justinledouxweb** [angular/protractor#3262]
Hi there!

I have been writing dozens of Protractor tests for my current angular project and they all work.

I pasted tests to create a new set of tests, and noticed that if there is a describe nested directly inside another describe, I get a `Cannot read property 'timeout' of undefined error` and Protractor exits with code 100.

If I remove the nested `describe`, it works right away.

If there is an `it` before the nested `describe`, that works... so all of it seams extremely strange to me.

Here is the test and the error:

Code

```
/* eslint max-len: 0 */
/* eslint-env es6 */
'use strict';

var chai = require('chai');
var expect = chai.expect;
var chaiAsPromised = require('chai-as-promised');
var config = require('../../../../gulp/config');

chai.use(chaiAsPromised);

describe('Compléter la reception de l\'offre d\'acquisition', function describe() {
  var localhost = config.e2e.localhost;

  this.timeout(15000);

  describe('View mode:', function () {
    it('Should redirect the user to the /tableauoffre page when clicking on "Quitter"', function it() {
      browser.get('/tableauoffre');

      browser.waitForAngular()
        .then(function getFirstRow() {
          return element(by.id('table-0'))
            .all(by.css('tbody tr'))
            .get(0);
        })
        .then(function click(row) {
          return row
            .all(by.css('a'))
            .get(0)
            .click();
        })
        .then(function redirect() {
          return browser.getCurrentUrl();
        })
        .then(function click() {
          return element(by.id('quitter-btn'))
            .click();
        })
        .then(function url() {
          return browser.getCurrentUrl();
        })
        .then(function test(url) {
          expect(url).to.equal(`${localhost}/tableauoffre`);
        });
    });
  });
});
```

Error:

```
[11:21:24] Starting 'protractor'...
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
[launcher] Error: TypeError: Cannot read property 'timeout' of undefined
    at describe (/Users/[user-name]/Documents/banq/trunk/app/modules/views/assigner.offre/assigner.offre.e2e.js:15:7)
    at Suite.describe (/Users/[user-name]/Documents/banq/trunk/app/modules/views/assigner.offre/assigner.offre.e2e.js:21:3)
    at context.describe.context.context (/Users/[user-name]/Documents/banq/trunk/node_modules/mocha/lib/interfaces/bdd.js:47:10)
    at Object.<anonymous> (/Users/[user-name]/Documents/banq/trunk/app/modules/views/assigner.offre/assigner.offre.e2e.js:12:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
[launcher] Process exited with error code 100

/Users/[user-name]/Documents/banq/trunk/gulp/tasks/protractor.js:24
      throw err;
      ^
Error: protractor exited with code 100
    at ChildProcess.<anonymous> (/Users/[user-name]/Documents/banq/trunk/node_modules/gulp-protractor/index.js:63:27)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

Extra info:
- Node Version: `4.4.5`
- Protractor Version: `2.2.0`
- Browser(s): `Chrome`
- Operating System and Version `Mac OS X El Capitan 10.11.5`
- Your protractor configuration file
```
'use strict';

exports.config = {
  allScriptsTimeout: 11000,
  baseUrl: 'http://localhost:3000/',
  directConnect: true,
  capabilities: {
    browserName: 'chrome',
    platform: 'ANY'
  },
  framework: 'mocha',
  jasmineNodeOpts: {
    onComplete: null,
    isVerbose: false,
    showColors: true,
    includeStackTrace: true,
    defaultTimeoutInterval: 30000
  }
};
```

**Comment by cnishina** [comment]
At first glance it looks like this is the problem:

```
describe('Compléter la reception de l\'offre d\'acquisition', function describe() {
```

Describe has two parameters, a string and a callback function. Without trying your test out, it should probably look like:

```
describe('Compléter la reception de l\'offre d\'acquisition', function() {
```

Similarly for your it block:
```
it('Should redirect the user to the /tableauoffre page when clicking on "Quitter"', function it() {
```

should probably look like:
```
it('Should redirect the user to the /tableauoffre page when clicking on "Quitter"', function() {
```

**Comment by cnishina** [comment]
Maybe also use beforeAll or beforeEach.

```
describe(‘some cool feature’, function() {
  beforeEach(function() {
     // go to a url
  });
  it(‘should not be able to buy something’, function() {
  });

  describe(‘with credentials’, function() {
    beforeAll(function() {
      // login
    });
    afterAll(function() {
      // logout
    });
    it(‘should be able to buy something’, function() {
    });
});

```

I am closing this issue. This sounds like a support question and hopefully these suggestions help. If you have additional questions please use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor).

**Comment by cnishina** [comment]
Also you shouldn't have to call `waitForAngular`. This function is executed for you to synchronize interactions, finding elements, etc.

**Comment by justinledouxweb** [comment]
@cnishina , naming a callback function is best JavaScript practice and helps debugging big call stacks... it does not change a thing in how code is executed if you remove the callback name.

Also, beforeAll or beforeEach does not make it work.

It seams that putting an it() function before the nested describe() works, but not if there is only a nested describe().

**Comment by cnishina** [comment]
Well this depends, you defined a callback called "describe" then you are nesting the "describe" from the testing framework. I am surprised this is not causing an error.

```
❯ protractor conf_chrome.js 
[16:30:21] I/hosted -  Using the selenium server at http://localhost:4444/wd/hub
[16:30:21] I/launcher -  Running 1 instances of WebDriver
Started
F

Failures:
1) restart check encountered a declaration exception
  Message:
    RangeError: Maximum call stack size exceeded
  Stack:
    RangeError: Maximum call stack size exceeded
        at describe (/usr/local/google/home/cnishina/src/protractor-examples/protractor/config_spec/spec.js:1:44)
```
here's my spec using the nested describe named function
```
describe('restart check', function describe() {
  describe('some random describe', function describe2() {
  beforeEach(function beforeEach() {
    browser.get(browser.baseUrl);
  })
  it('should greet the user', function() {
    element(by.model('yourName')).sendKeys('Julie');
    var greeting = element(by.binding('yourName'));
    expect(greeting.getText()).toEqual('Hello Julie!');
  });
```

**Comment by justinledouxweb** [comment]
Huh... you are actually right... If I remove or change the name of my parent callback to something other than `describe`, I no longer get the error... I didn't know that it had an actual impact. I was always under the impression that it was a "hidden" name.

**Comment by dondrich** [comment]
Had the same issue, changing the parent callback name to something other than ```describe``` also solved it
