### ISSUE TITLE
/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108:18

### ISSUE THREAD

**Issue by premkh9** [angular/protractor#3273]
I tried to update `node_modules/protractor/bin/webdriver-manager update` and after that I am seeing this issue. Attached json file for reference 
[package.zip](https://github.com/angular/protractor/files/316818/package.zip)

```
Started by user premkumar_kashipathy
[EnvInject] - Loading node environment variables.
Building remotely on aws-slave-002-v2 (AWS) in workspace /opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA
Fetching changes from the remote Git repository
Fetching upstream changes from http://stash.chotel.com:8080/scm/qa/choice-hotels-js.git
 > /usr/bin/git --version # timeout=10
 > /usr/bin/git -c core.askpass=true fetch --tags --progress http://stash.chotel.com:8080/scm/qa/choice-hotels-js.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision bcd32531f9287ee1e65ca2c17e02d75f7b8c6cc8 (origin/US00000-HTMLReport)
 > /usr/bin/git config core.sparsecheckout # timeout=10
 > /usr/bin/git checkout -f bcd32531f9287ee1e65ca2c17e02d75f7b8c6cc8
Starting pre-build for Sauce Labs plugin
Finished pre-build for Sauce Labs plugin
[chcom-replatform-mobile-regression-QA] $ /bin/sh -xe /tmp/hudson1810712490951851814.sh
+ node_modules/protractor/bin/webdriver-manager update
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.51/selenium-server-standalone-2.51.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip...
chromedriver_2.21.zip downloaded to /opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/selenium/chromedriver_2.21.zip
selenium-server-standalone-2.51.0.jar downloaded to /opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/selenium/selenium-server-standalone-2.51.0.jar
[chcom-replatform-mobile-regression-QA] $ /bin/sh -xe /tmp/hudson7033233414110567757.sh
+ npm update
[chcom-replatform-mobile-regression-QA] $ /bin/sh -xe /tmp/hudson6358854987283602421.sh
+ node_modules/protractor/bin/protractor protractor --version
Version 3.1.0
[chcom-replatform-mobile-regression-QA] $ /bin/sh -xe /tmp/hudson1328158885301203669.sh
+ node_modules/protractor/bin/protractor src/test/resources/mobileQAEXT-conf.js '--baseUrl=https://replatformuat.choicehotels.com/?set_qa_mobile_env_cookie=true' --suite mobileGalleryComponent
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://10.224.247.131:37771/wd/hub
/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
UnknownError: null
    at new bot.Error (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
    at Object.bot.response.checkResponse (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)
    at /opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:160:24
    at [object Object].promise.Promise.goog.defineClass.invokeCallback_ (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:124:15)
    at process._tickCallback (node.js:356:9)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at [object Object].Builder.build (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/selenium-webdriver/builder.js:445:22)
    at [object Object].DriverProvider.getNewDriver (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/lib/driverProviders/driverProvider.js:42:27)
    at [object Object].Runner.createBrowser (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/lib/runner.js:190:37)
    at /opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/lib/runner.js:280:21
    at _fulfilled (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/q/q.js:796:13)
    at /opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/node_modules/protractor/node_modules/q/q.js:604:44
[launcher] Process exited with error code 1
Build step 'Execute shell' marked build as failure
Starting post-build for Sauce Labs plugin
Finished post-build for Sauce Labs plugin
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level /opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/target/screenshots to /opt/ci/jenkins/jobs/chcom-replatform-mobile-regression-QA/htmlreports/HTML_Report
ERROR: Specified HTML directory '/opt/ci/corporate/workspace/chcom-replatform-mobile-regression-QA/target/screenshots' does not exist.
Starting Sauce Labs test publisher
The Sauce OnDemand plugin is configured, but no session IDs were found in the test output.
Finished Sauce Labs test publisher
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE
```

**Comment by sjelin** [comment]
Not sure I understand.  You mean you *ran* `webdriver-manager update` or you updated `webdriver-manager`?

**Comment by premkh9** [comment]
As per the suggestion, https://github.com/angular/protractor/issues/3268  - I have removed webdriver-manager v10.0.4  from package.json file and ran ' webdriver-manager update ' to fix ' Error: No selenium server jar found at the specified location '. Now I am observing new error that is mentioned above. Let me know, if you need any additional information

**Comment by sjelin** [comment]
Can I see your config file?

**Comment by premkh9** [comment]
I have attached the same under attachment section. It was working without any issue till last friday and seeing issue from past 6 days

[mobileQAEXT-conf.zip](https://github.com/angular/protractor/files/318975/mobileQAEXT-conf.zip)

**Comment by sjelin** [comment]
Not sure I understand.  Where does `webdriver-manager start` get executed?

**Comment by premkh9** [comment]
we were not executing ' webdriver-manager start ' specifically in jenkins earlier, it was working earlier without starting webdriver-manager . Is their any way we can include that command in conf.js?
Please refer to console log details of success job which got executed last week without passing webdriver-manager start command in jenkins
[sucess.zip](https://github.com/angular/protractor/files/319053/sucess.zip)

**Comment by sjelin** [comment]
Are you trying to get a browser from sauce labs or webdriver manager?

**Comment by premkh9** [comment]
we are trying to get browser from sauce labs

**Comment by premkh9** [comment]
Hi Sjelin, I figured out the issue. It was happening bcoz sauce credentials were commented out in conf file. But still can you tell me, is there any way to run webdriver-manager start and protractor conf.js file in the same command prompt

**Comment by sjelin** [comment]
You could run it as a background process.  Glad you found your issue!

**Comment by premkh9** [comment]
Thanks Sjelin, please close this issue
