### ISSUE TITLE
Protractor click not working

### ISSUE THREAD

**Issue by DioNNiS** [angular/protractor#3277]
I'm using basic example of protractor from http://www.protractortest.org/ website (https://angularjs.org) todo app.

And I got an error:
```
inchen0l050415:protractor user1$ protractor conf.js
[11:04:20] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[11:04:20] I/launcher - Running 1 instances of WebDriver
Started
F

Failures:
1) angularjs homepage todo list should add a todo
  Message:
    Expected 2 to equal 3.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/user1/Documents/projects/_test/protractor/todo-spec.js:9:30)
        at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:96:23
        at new Promise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1043:7)
        at controlFlowExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:82:18)
        at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2697:25
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:369:9)
  Message:
    Failed: Index out of bound. Trying to access element at index: 2, but there are only 2 elements that match locator by.repeater("todo in todoList.todos")
  Stack:
    NoSuchElementError: Index out of bound. Trying to access element at index: 2, but there are only 2 elements that match locator by.repeater("todo in todoList.todos")
        at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
        at NoSuchElementError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/error.js:230:10)
        at /usr/local/lib/node_modules/protractor/built/element.js:248:27
        at Promise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:369:9)
    Error
        at ElementArrayFinder.applyAction_ (/usr/local/lib/node_modules/protractor/built/element.js:371:27)
        at ElementArrayFinder._this.(anonymous function) [as getText] (/usr/local/lib/node_modules/protractor/built/element.js:83:30)
        at ElementFinder._this.(anonymous function) [as getText] (/usr/local/lib/node_modules/protractor/built/element.js:685:22)
        at Object.<anonymous> (/Users/user1/Documents/projects/_test/protractor/todo-spec.js:10:28)
        at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:96:23
        at new Promise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1043:7)
        at controlFlowExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:82:18)
        at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2697:25
    From: Task: Run it("should add a todo") in control flow
        at Object.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:81:14)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/user1/Documents/projects/_test/protractor/todo-spec.js:2:3)
        at Object.<anonymous> (/Users/user1/Documents/projects/_test/protractor/todo-spec.js:1:1)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)

1 spec, 1 failure
Finished in 4.078 seconds
[11:04:25] I/launcher - 0 instance(s) of WebDriver still running
[11:04:25] I/launcher - chrome #01 failed 1 test(s)
[11:04:25] I/launcher - overall: 1 failed spec(s)
[11:04:25] E/launcher - Process exited with error code 1
inchen0l050415:protractor user1$ 
```

It looks like there is a problem with click function - it didn't work.
I tried other examples - same result - click not works.

My environment:
node -v - v4.4.5
protractor --version - Version 3.3.0
selenium standalone version 2.52.0
chromedriver version 2.21
OS: mac os 10.11.5

**Comment by NickTomlin** [comment]
I'm not able to replicate this with a similar setup. Could you post your full config and test files?

Thanks!

**Comment by DioNNiS** [comment]
Test:
```
describe('angularjs homepage todo list', function() {
  it('should add a todo', function() {
    browser.get('https://angularjs.org');

    element(by.model('todoList.todoText')).sendKeys('write first protractor test');
    element(by.css('[value="add"]')).click();

    var todoList = element.all(by.repeater('todo in todoList.todos'));
    expect(todoList.count()).toEqual(3);
    expect(todoList.get(2).getText()).toEqual('write first protractor test');

    // You wrote your first test, cross it off the list
    todoList.get(2).element(by.css('input')).click();
    var completedAmount = element.all(by.css('.done-true'));
    expect(completedAmount.count()).toEqual(2);
  });
});
```

Config:
```
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['todo-spec.js']
};
```

Run
`protractor conf.js`

**Comment by DioNNiS** [comment]
Tested on windows machine and it works. Looks like environment issues.
