### ISSUE TITLE
Unable to run protractor tests on headless chrome and firefox on ubuntu16 Vagrant

### ISSUE THREAD

**Issue by behlrattan** [angular/protractor#3292]
Bug report
---
**PS:** With same configuration tests run on my local OSX on real browser
- Node Version: `6.2.1`
- Protractor Version: `3.3.0`
- Browser(s): `Chrome (51.0.2704.103), Firefox (45.0.2) `
- Operating System and Version `Ubuntu 16.04 LTS`

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
**Protractor file:**
```
exports.config = {
    baseUrl: 'http://<qa.environment>',
    framework: 'jasmine',
    seleniumAddress: 'http://localhost:4444/wd/hub',
    jasmineNodeOpts: {
        showColors:true,
        defaultTimeoutInterval: 2500000
    },
     capabilities: {
    'browserName': 'firefox'  _(also tried with chrome)_
  },

    specs: ['administration/*-spec.js'],  //'signinandout/*-spec.js', 'homepage/*-spec.js',
    onPrepare: function(){
        //browser.driver.manage().window().setSize(1280, 1080);  
    //    browser.driver.manage().window().maximize();
        //var SpecReporter = require('jasmine-spec-reporter');
        // add jasmine spec reporter
        //jasmine.getEnv().addReporter(new SpecReporter({displayStacktrace: 'all'}));
//        jasmine.getEnv().addReporter(
//            new Jasmine2HtmlReporter({
//                savePath: './reports'
//            })
//        );
    }
}
```
++++++++++++++++++++++++**Error with Chrome**+++++++++++++++++++++++++++++++++++++++
**/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/error.js:27
    super(opt_error);
    ^
WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.21.371461** (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.4.0-21-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.23 seconds
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'ubuntu-1604-vbox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-21-generic', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at WebDriverError (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:5)
    at Object.checkLegacyResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/error.js:580:13)
    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:64:13
    at Promise.invokeCallback_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
    at TaskQueue.execute_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
    at TaskQueue.executeNext_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
    at asyncRun (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27)
    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at acquireSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:295:12)
    at Builder.build (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:458:24)
    at Hosted.DriverProvider.getNewDriver (/usr/lib/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
    at Runner.createBrowser (/usr/lib/node_modules/protractor/built/runner.js:182:43)
    at /usr/lib/node_modules/protractor/built/runner.js:255:30
    at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/lib/node_modules/protractor/node_modules/q/q.js:556:49

+++++++++++++++++++++++++++**Firefox Error**+++++++++++++++++++++++++++++++++++++++++++
/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/error.js:27
    super(opt_error);
    ^
WebDriverError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
Error: GDK_BACKEND does not match available displays

    at WebDriverError (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:5)
    at Object.checkLegacyResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/error.js:580:13)
    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:64:13
    at Promise.invokeCallback_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
    at TaskQueue.execute_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
    at TaskQueue.executeNext_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
    at asyncRun (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27)
    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at acquireSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:295:12)
    at Builder.build (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:458:24)
    at Hosted.DriverProvider.getNewDriver (/usr/lib/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
    at Runner.createBrowser (/usr/lib/node_modules/protractor/built/runner.js:182:43)
    at /usr/lib/node_modules/protractor/built/runner.js:255:30
    at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/lib/node_modules/protractor/node_modules/q/q.js:556:49

**Comment by cnishina** [comment]
Hi @behlrattan,

This appears to be a support type question and should be directed toward [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by cnishina** [comment]
I'm not sure of your setup, but do you have a desktop gui on your vagrant ubuntu box? My guess (with the information provided) is that there is no desktop and the browser cannot launch.

**Comment by behlrattan** [comment]
Yes its a non GUI ubuntu 16. I already posted this on stackOverflow 2 weeks [link](http://stackoverflow.com/questions/37692793/webdrivererror-unknown-error-chrome-failed-to-start-exited-abnormally) but didn't get any reply.
It could be a very small mistake which i am unable to figure out unfortunately.

**Comment by cnishina** [comment]
You need either a desktop GUI or an X server. See http://unix.stackexchange.com/questions/9107/how-can-i-run-firefox-on-linux-headlessly-i-e-without-requiring-libgtk-x11-2-0

**Comment by behlrattan** [comment]
Yes I been using XVFB already as it's mentioned in the stackoverlow link. I suspect this is XVFB related issue but what is it i have no clue.
