### ISSUE TITLE
Getting 'E/launcher - Error: TypeError: require(...).run is not a function' when trying to run my congi.js file

### ISSUE THREAD

**Issue by VenkatanarasimhanS** [angular/protractor#3445]
trying to setup protractor-cuucmber sample project using custom framework using protractor-jasmine-cucumber npm. getting below error on executing config.js file to generate the step definition for the my step in feature.

```
C:\Users\INDIRA\workspace\ProtractorCucumber\runner>protractor conf.js
[17:36:43] I/hosted - Using the selenium server at http://127.0.0.1:4444/wd/hub
[17:36:43] I/launcher - Running 1 instances of WebDriver
[17:36:47] E/launcher - Error: TypeError: require(...).run is not a function
    at C:\Users\INDIRA\AppData\Roaming\npm\node_modules\protractor\built\runner.js:324:43
    at _fulfilled (C:\Users\INDIRA\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\INDIRA\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\INDIRA\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\INDIRA\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\Users\INDIRA\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:137:13)
    at flush (C:\Users\INDIRA\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[17:36:47] E/launcher - Process exited with error code 100
```

my config file :+1: 

```
exports.config = {
  seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
  getPageTimeout: 60000,
  allScriptsTimeout: 500000,
  framework: 'custom',
  // path relative to the current config file
  frameworkPath: 'node_modules/protractor-jasmine-cucumber',
  //frameworkPath: require.resolve('protractor-cucumber-framework'),
  capabilities: {
    'browserName': 'chrome'
  },

  specs: [
    'feature/sampleFeature.feature'
  ],
   cucumberOpts: {
   require: '../stepdefinition/test.js',
   format: 'pretty',
   
   
  }
};
```
all 3 npm below are installed globally
Protractor version : 4.0.2
protractor-jasmine-cucumber version : 0.2.2
cucumber version : 1.2.1

**Comment by NickTomlin** [comment]
Hi there 😄 

This sounds like an issue with the path you are passing in `frameworkPath` (potentially because protractor-jasmine-cucumber is only installed globally? installing the module locally or using `require.resolve` _should_ fix this). 

In addition, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by VenkatanarasimhanS** [comment]
i tried both ways . i get same error

**Comment by VenkatanarasimhanS** [comment]
i request to reopen the issue

**Comment by igniteram** [comment]
@VenkatanarasimhanS `protractor-jasmine-cucumber` has been deprecated you could check out there github page https://github.com/DealerDotCom/protractor-jasmine-cucumber. This is certainly not an protractor's issue. Please raise it in their github repo. Thanks!

**Comment by VenkatanarasimhanS** [comment]
@igniteram Thanks, is there any way to use Cucumber with protractor . Thanks!
