### ISSUE TITLE
When i run webdriver-manager update i am getting the error.Followed the steps in http://www.protractortest.org/#/.I am trying to install and run for the first time.C:\Users\*****\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\lib\cmds\update.js:78         if (path.isAbsolute(options[Opt.OUT_DIR].getString())) {

### ISSUE THREAD

**Issue by protractor123a** [angular/protractor#3460]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing)
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Fill in the information that corresponds to your type of issue below
4. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue)

Bug report
---

- Node Version: ``
- Protractor Version: ``
- Browser(s): ``
- Operating System and Version ``
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by protractor123a** [comment]
TypeError: Object #<Object> has no method 'isAbsolute'
    at Program.update [as runMethod] (C:\Users\*****\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\lib\cmds\update.js:78:18)
    at Program.run (C:\Users\*****\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\lib\cli\programs.js:60:14)
    at Object.<anonymous> (C:\Users\\*****\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\lib\webdriver.js:26:38)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\*****\AppData\Roaming\npm\node_modules\protractor\bin\webdriver-manager:3:1)

**Comment by cnishina** [comment]
Per the issue template: "Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue)". Since there is not enough information, here is my guess:

You are probably receiving this error because you are on an older version of node. https://nodejs.org/api/path.html#path_path_isabsolute_path
