### ISSUE TITLE
npm run protrator Error!

### ISSUE THREAD

**Issue by Mrzzchao** [angular/protractor#3468]
**when i excute npm run protrator, Error!:**
```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "F:\\Software\\nodejs\\node.exe" "F:\\Software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protrator"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12

npm ERR! missing script: protrator
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\项目\public\angular-phonecat\npm-debug.log
```
**and this is the Error-log:**
```
0 info it worked if it ends with ok
1 verbose cli [ 'F:\\Software\\nodejs\\node.exe',
1 verbose cli   'F:\\Software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@2.14.12
3 info using node@v4.2.6
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info preprotractor angular-phonecat@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info protractor angular-phonecat@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-phonecat@0.0.0 Failed to exec protractor script
10 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (F:\Software\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at EventEmitter.emit (events.js:172:7)
10 verbose stack     at ChildProcess.<anonymous> (F:\Software\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at ChildProcess.emit (events.js:172:7)
10 verbose stack     at maybeClose (internal/child_process.js:821:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
11 verbose pkgid angular-phonecat@0.0.0
12 verbose cwd E:\项目\public\angular-phonecat\test
13 error Windows_NT 10.0.10586
14 error argv "F:\\Software\\nodejs\\node.exe" "F:\\Software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
15 error node v4.2.6
16 error npm  v2.14.12
17 error code ELIFECYCLE
18 error angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
18 error Exit status 1
19 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
19 error This is most likely a problem with the angular-phonecat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     protractor test/protractor-conf.js
19 error You can get their info via:
19 error     npm owner ls angular-phonecat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```
**hope get your answer!**

**Comment by cnishina** [comment]
I just grabbed the master branch from angular-phonecat and ran `npm run protractor`. I am unable to reproduce this issue. 

Could it be that you misspelled "protractor"? From the issue above:

```
npm ERR! missing script: protrator
```

If I run `npm run protrator` my debug log looks similar:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protrator' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
```

However, this is also mismatched with the error log below, where the following ran as `npm run protractor`

```
0 info it worked if it ends with ok
1 verbose cli [ 'F:\\Software\\nodejs\\node.exe',
1 verbose cli   'F:\\Software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
```

Since this is a support issue, please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
