### ISSUE TITLE
Unable to connect to chrome and firefox with protractor 4.0.4

### ISSUE THREAD

**Issue by sri85** [angular/protractor#3502]
Bug report
---

- Node Version: `v6.4.0`
- Protractor Version: `4.0.4`
- Browser(s): `chrome ,firefox`
- Selenium Version : `Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'`
- Operating System and Version `os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4'`
- Your protractor configuration file
```
exports.config = {
  framework: 'jasmine',
  seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
  specs: ['specs/spec.js'],
	capabilities: {
  	'browserName': 'chrome'
	}
}
```
- A relevant example test
```
describe('Protractor Demo App', function() {
  it('should have a title', function() {
    browser.get('http://juliemr.github.io/protractor-demo/');

    expect(browser.getTitle()).toEqual('Super Calculator');
  });
});

```
- Output from running the test
```
I/hosted - Using the selenium server at http://127.0.0.1:4444/wd/hub
[11:43:34] I/launcher - Running 1 instances of WebDriver
[11:43:38] E/launcher - session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.22.397929 (fb72fb249a903a0b1041ea71eb4c8b3fa0d9be5a),platform=Mac OS X 10.11.4 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 979 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'GoustoAminsMBP7.hyperoptic.com', ip: '192.168.1.194', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.chrome.ChromeDriver
[11:43:38] E/launcher - SessionNotCreatedError: session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.22.397929 (fb72fb249a903a0b1041ea71eb4c8b3fa0d9be5a),platform=Mac OS X 10.11.4 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 979 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'GoustoAminsMBP7.hyperoptic.com', ip: '192.168.1.194', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at SessionNotCreatedError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:308:5)
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:458:24)
    at Hosted.DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:190:43)
    at /usr/local/lib/node_modules/protractor/built/runner.js:264:30
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13)
[11:43:38] E/launcher - Process exited with error code 199

```
- Steps to reproduce the bug
1. Run the `conf.js` using `protractor conf.js`
- The URL you are running your tests against (if relevant)

In case of chrome , it fails to create the session , in case of firefox the session is created but no progress from there.

**Comment by sri85** [comment]
I tried running with protractor 3.x and it works perfectly fine .

**Comment by cnishina** [comment]
This is not reproducible. Similar closed issue: https://github.com/angular/protractor/issues/2610.

* operating system: OS X
* chrome version: 52.0.2743.116
* protractor version: 4.0.4
* selenium standalone server 2.53.1 and chromedriver 2.22
* node version 6

After doing some research online, this appears to not be a Protractor specific bug. 

Other debugging chrome logs that may or may not help:

```
webdriver-manager start --chrome_logs='<full-path-to.log>'
```

To remove old binaries:

```
webdriver-manager clean
webdriver-manager update
```
