### ISSUE TITLE
Error while waiting for Protractor to sync with the page: "[ng:test] with directive data-ng-controller="AppCtrl" for protractor 3.3.0

### ISSUE THREAD

**Issue by rohitkadam19** [angular/protractor#3503]
**- Node Version: `4.4.2`**
**- Protractor Version: `3.3.0`**
**- Browser(s): `Chrome 52`**
**- Operating System and Version `Ubuntu 16.04`**

**- protractor configuration file**
```
    exports.config = {
           seleniumPort: 4444,
           baseUrl: baseUrl,
           params: {
                      screen: {
                               width: screen[0],
                              height: screen[1]
                                },
           jasmineNodeOpts: {
                       showColors: true,
                      defaultTimeoutInterval: 3600000
          },

         framework: "jasmine2",
         onPrepare: '../utility/Preparation.js'
};
```

**- Output from running the test**

  ```
TypeError: Cannot assign to read only property 'stack' of Error while waiting for Protractor to sync with the page: "[ng:test] http://errors.angularjs.org/1.4.5/ng/test"
    at /home/apps/Projects/Troposphere/testing_repo/uat/troposphere/scripts/ui/node_modules/protractor/built/element.js:377:21
    at Promise.invokeCallback_ (/home/apps/Projects/Troposphere/testing_repo/uat/troposphere/scripts/ui/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
    at TaskQueue.execute_ (/home/apps/Projects/Troposphere/testing_repo/uat/troposphere/scripts/ui/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
    at TaskQueue.executeNext_ (/home/apps/Projects/Troposphere/testing_repo/uat/troposphere/scripts/ui/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
    at /home/apps/Projects/Troposphere/testing_repo/uat/troposphere/scripts/ui/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
    at /home/apps/Projects/Troposphere/testing_repo/uat/troposphere/scripts/ui/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:369:9)
[18:58:44] E/launcher - Process exited with error code 1
>> /home/apps/Projects/Troposphere/testing_repo/uat/troposphere/scripts/ui/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329
>>       return callbackFn(this.value_);
>>              ^
>> TypeError: Cannot assign to read only property 'stack' of Error while waiting for Protractor to sync with the page: "[ng:test] http://errors.angularjs.org/1.4.5/ng/test"
>>     at /home/apps/Projects/Troposphere/testing_repo/uat/troposphere/scripts/ui/node_modules/protractor/built/element.js:377:21
>>     at Promise.invokeCallback_ (/home/apps/Projects/Troposphere/testing_repo/uat/troposphere/scripts/ui/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
>>     at TaskQueue.execute_ (/home/apps/Projects/Troposphere/testing_repo/uat/troposphere/scripts/ui/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
>>     at TaskQueue.executeNext_ (/home/apps/Projects/Troposphere/testing_repo/uat/troposphere/scripts/ui/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
>>     at /home/apps/Projects/Troposphere/testing_repo/uat/troposphere/scripts/ui/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
>>     at /home/apps/Projects/Troposphere/testing_repo/uat/troposphere/scripts/ui/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
>>     at process._tickCallback (node.js:369:9)
Warning: Tests failed, protractor exited with code: 1 Use --force to continue.
```

**- Steps to reproduce the bug**
  My page does not have ng-app directive. It has 
      <body data-ng-controller="AppCtrl" class="ng-scope">
        ...
      </body>

**Comment by cnishina** [comment]
Duplicate issue: https://github.com/angular/protractor/issues/3363

This has already been addressed in the latest version of Protractor (4.0.4). Thanks!
