### ISSUE TITLE
Can't launch test after upgrade to 4.X

### ISSUE THREAD

**Issue by finspin** [angular/protractor#3591]
After upgrading to Protractor 4.0.9 from 3.3.0, launching tests results in the following error. Downgrading back to 3.3.0 fixes the issue.

    [15:20:12] I/launcher - Running 1 instances of WebDriver
        [15:20:12] E/launcher - EPROTO write EPROTO 140735146942464:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

    [15:20:12] E/launcher - Error: EPROTO write EPROTO 140735146942464:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:381:15)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at onwriteError (_stream_writable.js:312:10)
    at onwrite (_stream_writable.js:330:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:456:13)
    From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:458:24)
    at Hosted.DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:190:43)
    at /usr/local/lib/node_modules/protractor/built/runner.js:264:30
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13)
    [15:20:12] E/launcher - Process exited with error code 199

Node v4.5.0
NPM 2.15.9
Protractor 4.0.9
Angular 1.4.9
Mac OSX
Chrome
URL: https://github.com

**Spec:**

    it('upgrade test', function () {
        browser.get(browser.baseUrl);
    });

**Run spec:**

    protractor test-configs/barebone-config.js --specs=_sandbox/upgrade-test.js --seleniumAddress="https://localhost:4444/wd/hub" --browser="chrome" --baseUrl="https://github.com"

**Config file:**

    'use strict';

    var SpecReporter = require('jasmine-spec-reporter');

    exports.config = {

        allScriptsTimeout: 60000,

        getPageTimeout: 30000,

        jasmineNodeOpts: {
            showColors: true,
            defaultTimeoutInterval: 62000,
            print: function () {}
        },

        framework: 'jasmine2',
        
        onPrepare: function () {
            // Display detailed errors in the log
            jasmine.getEnv().addReporter(new SpecReporter({
                displayStacktrace: true
            }));
        } 
    };

**Comment by NickTomlin** [comment]
What version of selenium are you running? If you change ` --seleniumAddress="https://localhost:4444/wd/hub"` to ` --seleniumAddress="http://localhost:4444/wd/hub"` does it work?

**Comment by finspin** [comment]
Yes, changing to http worked, thanks! I had been changing baseUrl to http instead of seleniumAddress.

I'm running the latest selenium, 2.53.1.
