### ISSUE TITLE
Elementor does not running on protractor version 4.0.9

### ISSUE THREAD

**Issue by akbar-10p** [angular/protractor#3597]
I am getting this error when I execute command elementor https://any angular URL

Creating protractor configuration file
Starting protractor
Running command: [node C:\Users\akber\AppData\Roaming\npm\node_modules\elementor
\node_modules\protractor\built\cli.js --elementExplorer true --debuggerServerPor
t 6969 C:\Users\akber\AppData\Local\Temp\protractor-conf116823-9388-1x0wdop]
[17:55:17] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[17:55:19] I/protractor -
[17:55:19] I/protractor - ------- Element Explorer -------
[17:55:19] I/protractor - Starting WebDriver debugger in a child process. Elemen
t Explorer is still beta, please report issues at github.com/angular/protractor
[17:55:19] I/protractor -
[17:55:19] I/protractor - Type <tab> to see a list of locator strategies.
[17:55:19] I/protractor - Use the `list` helper function to find elements by str
ategy:
[17:55:19] I/protractor -   e.g., list(by.binding('')) gets all bindings.
[17:55:19] I/protractor -
Server listening on 127.0.0.1:6969
Done starting protractor
Starting elementor
Elementor is listening on http://localhost:13000
Getting page at: http://10.0.0.104/Portal/Lms/Lms/LMS_Dashboard#/training
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:907:11)
    at Socket._writeGeneric (net.js:697:26)
    at Socket._write (net.js:716:8)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at Socket.Writable.write (_stream_writable.js:214:11)
    at Socket.write (net.js:642:40)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)

**Comment by NickTomlin** [comment]
Hi there, 

Please raise an issue on the [elementor](https://github.com/andresdominguez/elementor) repository. 

If this turns out to be an issue with protractor core please open another issue that follows the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) template.

Thanks!
