### ISSUE TITLE
WebDriverError: unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by aboungnaseng857** [angular/protractor#3614]
Hi,

I use protractor with a standalone Selenium Server and chrome browser
It work fine when I use Windows windows 7 but for Linux Binary chrome cannot be found.

I specified the binary's path in attribute 'chromeDriver'  for : 

- **'./node_modules/webdriver-manager/selenium/chromedriver_2.22.exe'** (for Windows 7)** :+1: 
- **'./node_modules/webdriver-manager/selenium/chromedriver_2.22) (for Linux)** :-1: 

I create 2 task in my gulptask file, one for update webdriver, and the other one to launch my tests.
These tasks are launched synchronously when webdriver-update is finish I launch my tests.

`

    gulp.task('webdriver-update', webdriver_update);

    gulp.task('e2e-tests', function(done) {
        return gulp.src(["./protractor/*.js"])
            .pipe(protractor({
                configFile: "protractor.conf.js",
                args: ['--baseUrl', 'http://rfezffezdqsdqfez.com']
            }))
            .on('error', function(e) {
                throw e;
            });
    });

    gulp.task('protractor', function(done) {
        runSeq('webdriver-update', 'e2e-tests', done);
    });
`

When I launch my tasks on Linux WebDriver cannot find Chrome binary

Download and unzip a this location by the task webdriver-update:
**./node_modules/webdriver-manager/selenium/chromedriver_2.22linux64.zip**

Protractor configuration file.
**chromeDriver: './node_modules/webdriver-manager/selenium/chromedriver_2.22'**

The logs below :+1: 

> 
[15:50:08] Using gulpfile /builds/lcab/lcab/Gulpfile.js
[15:50:08] Starting 'protractor'...
[15:50:08] Starting 'webdriver-update'...
webdriver-manager: using local installed version 10.2.3
[15:50:08] I/update - selenium standalone: file exists /builds/lcab/lcab/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar
[15:50:08] I/update - selenium standalone: v2.53.1 up to date
[15:50:08] I/update - chromedriver: file exists /builds/lcab/lcab/node_modules/webdriver-manager/selenium/chromedriver_2.22linux64.zip
[15:50:08] I/update - chromedriver: unzipping chromedriver_2.22linux64.zip
[15:50:09] I/update - chromedriver: setting permissions to 0755 for /builds/lcab/lcab/node_modules/webdriver-manager/selenium/chromedriver_2.22
[15:50:09] I/update - chromedriver: v2.22 up to date
[15:50:09] Finished 'webdriver-update' after 698 ms
[15:50:09] Starting 'e2e-tests'...
[15:50:09] D/launcher - Running with --troubleshoot
[15:50:09] D/launcher - Protractor version: 4.0.9
[15:50:09] D/launcher - Your base url for tests is http://...
[15:50:09] I/direct - Using ChromeDriver directly...
[15:50:09] I/launcher - Running 1 instances of WebDriver
[15:50:09] E/launcher - unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.22.397932 (282ed7cf89cf0053b6542e0d0f039d4123bbb6ad),platform=Linux 4.7.0-coreos x86_64)
[15:50:09] E/launcher - WebDriverError: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.22.397932 (282ed7cf89cf0053b6542e0d0f039d4123bbb6ad),platform=Linux 4.7.0-coreos x86_64)
    at WebDriverError (/builds/lcab/lcab/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/builds/lcab/lcab/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/builds/lcab/lcab/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/builds/lcab/lcab/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/builds/lcab/lcab/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/builds/lcab/lcab/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/builds/lcab/lcab/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/builds/lcab/lcab/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /builds/lcab/lcab/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/builds/lcab/lcab/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Driver (/builds/lcab/lcab/node_modules/selenium-webdriver/chrome.js:778:38)
    at Direct.getNewDriver (/builds/lcab/lcab/node_modules/protractor/built/driverProviders/direct.js:68:26)
    at Runner.createBrowser (/builds/lcab/lcab/node_modules/protractor/built/runner.js:198:43)
    at /builds/lcab/lcab/node_modules/protractor/built/runner.js:277:30
    at _fulfilled (/builds/lcab/lcab/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/builds/lcab/lcab/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/builds/lcab/lcab/node_modules/q/q.js:796:13)
    at /builds/lcab/lcab/node_modules/q/q.js:556:49
    at runSingle (/builds/lcab/lcab/node_modules/q/q.js:137:13)
[15:50:09] E/launcher - Process exited with error code 199

/builds/lcab/lcab/app/Resources/gulpFiles/unitsTestingFront.js:52
                throw e;
                ^
Error: protractor exited with code 199
ERROR: Build failed: exit code 1`
> 

`

my protractor conf file

'
exports.config = {

    // If true, only chromedriver will be started, not a standalone selenium.
    // Tests for browsers other than chrome will not run.
    directConnect: true,

    // The file path to the selenium server jar ()
    seleniumServerJar: './node_modules/protractor/node_modules/webdriver-manager/selenium/*.jar',

    // Selenium standalone server started at
    seleniumAddress: 'http://localhost:4444/wd/hub',

    // Spec patterns are relative to the location of this config.
    /*    specs: ['C:/www/weblcab-cf/php/web_lcab/protractor/identification.test.js'],*/
    specs: ['./protractor/identification.test.js'],

    // The timeout in milliseconds for each script run on the browser. This should
    // be longer than the maximum time your application needs to stabilize between
    // tasks.
    allScriptsTimeout: 11000,

    // How long to wait for a page to load.
    getPageTimeout: 10000,

    chromeDriver: './node_modules/webdriver-manager/selenium/chromedriver_2.22',

    troubleshoot: true,

    // ---------------------------------------------------------------------------
    // ----- The test framework --------------------------------------------------
    // ---------------------------------------------------------------------------
    // Test framework to use. This may be one of:
    // jasmine, mocha or custom.
    //
    // When the framework is set to "custom" you'll need to additionally
    // set frameworkPath with the path relative to the config file or absolute
    //  framework: 'custom',
    //  frameworkPath: './frameworks/my_custom_jasmine.js',
    // See github.com/angular/protractor/blob/master/lib/frameworks/README.md
    // to comply with the interface details of your custom implementation.
    //
    // Jasmine is fully supported as test and assertion frameworks.
    // Mocha has limited support. You will need to include your
    // own assertion framework (such as Chai) if working with Mocha.
    framework: 'jasmine',

    // Options to be passed to jasmine.
    //
    // See https://github.com/jasmine/jasmine-npm/blob/master/lib/jasmine.js
    // for the exact options available.
    jasmineNodeOpts: {
        // If true, display spec names.
        isVerbose: true,
        // If true, print colors to the terminal.
        showColors: true,
        // If true, include stack traces in failures.
        includeStackTrace: true,
        // Default time to wait in ms before a test fails.
        defaultTimeoutInterval: 30000
    },

    // A callback function called once protractor is ready and available, and
    // before the specs are executed.
    // If multiple capabilities are being run, this will run once per
    // capability.
    // You can specify a file containing code to run by setting onPrepare to
    // the filename string.
    onPrepare: function() {
        // At this point, global variable 'protractor' object will be set up, and
        // globals from the test framework will be available. For example, if you
        // are using Jasmine, you can add a reporter with:
        //     jasmine.getEnv().addReporter(new jasmine.JUnitXmlReporter(
        //         'outputdir/', true, true));
        var width = 1380;
        var height = 1024;
        browser.driver.manage().window().setSize(width, height);
        global.EC = protractor.ExpectedConditions;
    }
};
'

I'v tried to install chromedriver in nodes modules and add the chrome binary path to chromedriver attribute but it work only on window and I also try to add this conf to protractor but it seem to be deprecated : 

`
capabilities {
  'browserName': 'chrome',
  'chromeOptions': {
    'extensions': ['pathToExtension']
  }
}
`

Help me please

**Comment by mgiambalvo** [comment]
Hi there!

Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks and good luck!
