### ISSUE TITLE
element is not a function

### ISSUE THREAD

**Issue by rbatllet** [angular/protractor#3633]
- Node Version: `6.7.0`
- Protractor Version: `4.0.9`
- Angular Version: `1.5.8`
- Browser(s): `Google Chrome`
- Operating System and Version `MacOS Sierra`
- Your protractor configuration file
```
'use strict';

(function() {
  exports.config = {
    framework: 'jasmine',
    capabilities: {
      browserName: 'chrome'
    },
    specs: ['e2e/*.spec.js'],
    baseUrl: 'http://localhost:8000/',
    allScriptsTimeout: 110000,
    getPageTimeout: 100000,
    jasmineNodeOpts: {
      showColors: true,
      defaultTimeoutInterval: 30000
    }
  };
})();
```
- A relevant example test
```
    it('Should go to create a diagram and go to the diagram create', () => {
      const options = element.all(by.css('#side-menu li a'));
      options.element(by.id('diagramCreate')).click();
      expect(browser.getLocationAbsUrl()).toContain('/diagrams/new');
    });
```
- Output from running the test
```
Failures:
1) Controller: DiagramListCtrl On Diagram List Should go to create a diagram and go to the diagram create
  Message:
    Failed: options.element is not a function
  Stack:
    TypeError: options.element is not a function
        at Object.it (/Users/user/develop/myApp/test/e2e/diagramList.spec.js:30:15)
        at /Users/user/develop/myApp/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/Users/user/develop/myApp/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/Users/user/develop/myApp/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/Users/user/develop/myApp/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/user/develop/myApp/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/user/develop/myApp/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /Users/user/develop/myApp/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: Run it("Should go to create a diagram and go to the diagram create") in control flow
        at Object.<anonymous> (/Users/user/develop/myApp/node_modules/jasminewd2/index.js:79:14)
    From asynchronous test: 
    Error
        at Suite.describe (/Users/user/develop/myApp/test/e2e/diagramList.spec.js:28:5)
        at Suite.describe (/Users/user/develop/myApp/test/e2e/diagramList.spec.js:9:3)
        at Object.<anonymous> (/Users/user/develop/myApp/test/e2e/diagramList.spec.js:3:1)
```
- Steps to reproduce the bug

It worked in the previous Protractor versions. Now, it stops working.

**Comment by cnishina** [comment]
For the current version: `element.all` returns a type of `ElementArrayFinder`  and does not have a function `element` (https://github.com/angular/protractor/blob/master/lib/element.ts#L99).  `element` returns a type of `ElementFinder` which has a function `element`. (https://github.com/angular/protractor/blob/master/lib/element.ts#L909).

Which version of Protractor was this originally working? I checked version 3.0.0 and `element` also does not exist on `ElementArrayFinder`

**Comment by rbatllet** [comment]
I've reimplemented my test of another way:

```
    it('Should go to create a diagram and go to the diagram create', () => {
      const options = element(by.id('side-menu'));
      options.element(by.css('li #diagramCreate')).click();
      expect(browser.getLocationAbsUrl()).toContain('/diagrams/new');
    });
```
Note: The Protractor 4.0.9 does not work on the last version of Firefox (unable to do: `browser.get('#/')`), and the Chrome support is extremely buggy (the specs fail randomly).

**Comment by Chuckv** [comment]
webdriver functions return promises.   You probably want something along the lines of 

    expect(browser.getLocationAbsURL()).to.eventually.contain('/diagrams/new')  

using .eventually to wait for the promise to return, crack it open and get the value inside.

**Comment by cnishina** [comment]
Closing this issue. @rbatllet your second iteration looks better. At the time of this writing, the latest version of Firefox does not work. We recommend 47.0.1.
