### ISSUE TITLE
Cannot execute tests on firefox and safari 10 on macOS Sierra version 10.12

### ISSUE THREAD

**Issue by IvanFan** [angular/protractor#3638]
I updated my mac to macOS Sierra version 10.12 and begin to use multiCapabilities for chrome, firefox and safari.
I'm using the latest version of protractor. 

The test only works for chrome.
For safari, I got:
```
[safari #21] [17:12:08] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[safari #21]
[safari #21] /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27
[safari #21]     super(opt_error);
[safari #21]          ^
[safari #21] WebDriverError: Failed to connect to SafariDriver after 10071 ms
[safari #21] Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
[safari #21] System info: host: 'Yifans-MacBook-Pro.local', ip: '192.168.1.209', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_25'
[safari #21] Driver info: driver.version: SafariDriver
[safari #21]     at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:10)
[safari #21]     at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
[safari #21]     at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
[safari #21]     at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11
[safari #21]     at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
[safari #21]     at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
[safari #21]     at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
[safari #21]     at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25
[safari #21]     at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
[safari #21]     at process._tickCallback (node.js:369:9)
[safari #21] From: Task: WebDriver.createSession()
[safari #21]     at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
[safari #21]     at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:458:24)
[safari #21]     at Hosted.DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
[safari #21]     at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:198:43)
[safari #21]     at /usr/local/lib/node_modules/protractor/built/runner.js:277:30
[safari #21]     at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
[safari #21]     at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
[safari #21]     at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
[safari #21]     at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
[safari #21]     at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13) 
```

For firefox, I got:

```
[firefox #01] [17:12:08] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[firefox #01]
[firefox #01] /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27
[firefox #01]     super(opt_error);
[firefox #01]          ^
[firefox #01] WebDriverError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
[firefox #01] dateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1476337838000,"updateDate":1476337838000,"applyBackgroundUpdates":1,"skinnable":true,"size":7140,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"49.0.1","maxVersion":"49.0.1"}],"targetPlatforms":[],"seen":true}
[firefox #01] 1476339129817	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
[firefox #01] 1476339129819	DeferredSave.extensions.json	DEBUG	Save changes
[firefox #01] 1476339129819	addons.xpi	DEBUG	Updating database with changes to installed add-ons
[firefox #01] 1476339129820	addons.xpi-utils	DEBUG	Updating add-on states
[firefox #01] 1476339129823	addons.xpi-utils	DEBUG	Writing add-ons list
[firefox #01] 1476339129825	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
[firefox #01] 1476339129826	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
[firefox #01] 1476339129827	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
[firefox #01] 1476339129827	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
[firefox #01] 1476339129828	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
[firefox #01] 1476339129829	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
[firefox #01] 1476339129832	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
[firefox #01] 1476339129833	addons.manager	DEBUG	Provider finished startup: XPIProvider
[firefox #01] 1476339129833	addons.manager	DEBUG	Starting provider: LightweightThemeManager
[firefox #01] 1476339129833	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
[firefox #01] 1476339129839	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
[firefox #01] 1476339129841	addons.manager	DEBUG	Starting provider: GMPProvider
[firefox #01] 1476339129863	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
[firefox #01] 1476339129864	addons.manager	DEBUG	Provider finished startup: GMPProvider
[firefox #01] 1476339129864	addons.manager	DEBUG	Starting provider: PluginProvider
[firefox #01] 1476339129865	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
[firefox #01] 1476339129865	addons.manager	DEBUG	Provider finished startup: PluginProvider
[firefox #01] 1476339129866	addons.manager	DEBUG	Completed startup sequence
[firefox #01] 1476339131410	addons.manager	DEBUG	Starting provider: <unnamed-provider>
[firefox #01] 1476339131410	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
[firefox #01] 1476339131411	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
[firefox #01] 1476339131637	DeferredSave.extensions.json	DEBUG	Write succeeded
[firefox #01] 1476339131637	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
[firefox #01] 1476339131638	DeferredSave.extensions.json	DEBUG	Starting timer
[firefox #01] 1476339131650	addons.repository	DEBUG	No addons.json found.
[firefox #01] 1476339131651	DeferredSave.addons.json	DEBUG	Save changes
[firefox #01] 1476339131656	DeferredSave.addons.json	DEBUG	Starting timer
[firefox #01] 1476339131736	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
[firefox #01] 1476339131738	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
[firefox #01] 1476339131739	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
[firefox #01] 1476339131746	DeferredSave.extensions.json	DEBUG	Starting write
[firefox #01] 1476339131758	DeferredSave.addons.json	DEBUG	Starting write
[firefox #01] 1476339131806	DeferredSave.extensions.json	DEBUG	Write succeeded
[firefox #01] 1476339131905	DeferredSave.addons.json	DEBUG	Write succeeded
[firefox #01]
[firefox #01]     at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:10)
[firefox #01]     at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
[firefox #01]     at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
[firefox #01]     at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11
[firefox #01]     at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
[firefox #01]     at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
[firefox #01]     at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
[firefox #01]     at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25
[firefox #01]     at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
[firefox #01]     at process._tickCallback (node.js:369:9)
[firefox #01] From: Task: WebDriver.createSession()
[firefox #01]     at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
[firefox #01]     at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:458:24)
[firefox #01]     at Hosted.DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
[firefox #01]     at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:198:43)
[firefox #01]     at /usr/local/lib/node_modules/protractor/built/runner.js:277:30
[firefox #01]     at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
[firefox #01]     at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
[firefox #01]     at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
[firefox #01]     at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
[firefox #01]     at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13)

```

**Comment by IvanFan** [comment]
node version 4.4.3

conf.js:
```

exports.config = {
  // The address of a running selenium server.
  seleniumAddress: 'http://localhost:4444/wd/hub',

  // Capabilities to be passed to the webdriver instance.
  multiCapabilities: [{
    browserName: 'firefox'
  }, {
    browserName: 'chrome'
  }, {
    browserName: 'safari'
  }],

  // multiCapabilities: [{
  //   browserName: 'chrome'
  // }],
  // Spec patterns are relative to the configuration file location passed
  // to protractor (in this example conf.js).
  // They may include glob patterns.
  specs: ['spec/ui/*Spec.js'],

  // Options to be passed to Jasmine-node.
  jasmineNodeOpts: {
    showColors: true // Use colors in the command line report.
  }

};
```

**Comment by mgiambalvo** [comment]
Safari 10 only supports testing with the new [safaridriver](https://webkit.org/blog/6900/webdriver-support-in-safari-10/) and is only supported in Selenium 3 or higher, which just released [today](https://seleniumhq.wordpress.com/2016/10/13/selenium-3-0-out-now/). Firefox is also changing their automation as part of the selenium 3.0 release. 

Unfortunately, we're in this kind of awkward place at the moment where the old drivers are broken and the new ones aren't quite ready (or, rather, were just released today). This will be fixed soon, once we upgrade to the new version of Selenium. Thanks for you patience!

**Comment by antonmitsev** [comment]
Hi guys,
I am facing this issue nowadays. Are there any news on that?
