### ISSUE TITLE
Element Explorer fails with SessionNotCreatedError

### ISSUE THREAD

**Issue by Xotabu4** [angular/protractor#3661]
Getting error on attempt to start elementExplorer. Seems like something with latest Chrome Browser changes. Browser starts for a second, but then fails very hard.

Bug report
---

- Node Version: `6.2.1`
- JAVA: `java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
`
- Webdriver-manager: `
[18:00:29] I/status - selenium standalone version available: 2.53.1 [default]
[18:00:29] I/status - chromedriver version available: 2.22 [default]
`
- Protractor Version: `4.0.9`
- Browser(s): `Chrome Version 54.0.2840.71 (64-bit)`
- Operating System and Version `Mac El Capitan`

- Output from running the test
```
akhotemskyi-mac:~ akhotemskyi$ protractor --elementExplorer
[17:49:20] I/local - Starting selenium standalone server...
[17:49:21] I/local - Selenium standalone server started at http://172.25.13.136:55263/wd/hub

/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27
    super(opt_error);
    ^
SessionNotCreatedError: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"1246.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.22.397929 (fb72fb249a903a0b1041ea71eb4c8b3fa0d9be5a),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 748 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'akhotemskyi-mac.lohika.com', ip: '172.25.13.136', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_65'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at SessionNotCreatedError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:308:5)
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:458:24)
    at Local.DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:198:43)
    at /usr/local/lib/node_modules/protractor/built/runner.js:277:30
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:604:44
    at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13)
```
- Steps to reproduce the bug
`protractor --elementExplorer`

![image](https://cloud.githubusercontent.com/assets/3033972/19691258/58c95ccc-9adc-11e6-93cd-ae7efffed47c.png)

**Comment by jlin412** [comment]
It looks like a defect with chrome 54 and chrome driver > 2.24.
Upgrade to chrome driver 2.24 should fix this issue.

**Comment by mgiambalvo** [comment]
Yup, please run `webdriver-manager update` to make sure you're on the latest chromedriver.
