### ISSUE TITLE
I am not able to use import in jasmine 2.0 spec, protractor 4.0.9 and typescript 2.0.3

### ISSUE THREAD

**Issue by pearljamik** [angular/protractor#3662]
Whenever I use import keyword in my ts spec, I get the following error:

`[17:05:52] E/launcher - Error: SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at C:\Users\gwk736\Gitlab\inform-locate-E2E-tests\node_modules\jasmine\lib\jasmine.js:84:5
    at Array.forEach (native)
    at Jasmine.loadSpecs (C:\Users\gwk736\Gitlab\inform-locate-E2E-tests\node_modules\jasmine\lib\jasmine.js:83:18)
[17:05:52] E/launcher - Process exited with error code 100`

And my spec is: 
```
`import {Config} from '../../common/config';
describe('User with valid credentials', () => {

  it('should be able to login to application', () => {
    Config.WAIT_FOR_ELEMENT_TIMEOUT;
    expect(true).toBe(true);

  });
});`
```

The thing is that without import , it passes. What am I missing? It worked in 4.0.3 and typescript 1.8.

---

- Node Version: ``
- Protractor Version: `4.0.9`
- Angular Version: ``
- Browser(s): `chrome`
- Operating System and Version ``
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by juliemr** [comment]
It looks like you are trying to run the TS directly without compiling it. Please check out how your build process is running, and open a new issue if there is a problem with the way Protractor is behaving.
