### ISSUE TITLE
Can't run tests on macOs 10.12.1

### ISSUE THREAD

**Issue by davoam** [angular/protractor#3672]
---

- Node Version: `v6.5.0`
- Protractor Version: `4.0.8`
- Angular Version: `1.5`
- Browser(s): `Chrome  54.0.2840.71 (64-bit)`
- Operating System and Version `macOS 10.12.1`
- Your protractor configuration file
```js
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['./*.spec.js'],
    chromeOnly: true,
    jasmineNodeOpts: {
        defaultTimeoutInterval: 30000
    },
    allScriptsTimeout: 25000
};
```
- A relevant example test
```js
it('button disabled enabled state and redirect', function() {
        browser.get(`https://${TEST_MACHINE_IP}:8457/#!/login`);
        var loginButton  = browser.driver.findElement(by.css('[type=submit]'));
        element(by.model('login.credentials.username')).sendKeys('admin');
        expect(loginButton.isEnabled()).toBe(false);
        element(by.model('login.credentials.password')).sendKeys('admin');
        expect(loginButton.isEnabled()).toBe(true);
        loginButton.click();
        expect(browser.getCurrentUrl()).toMatch(/\/#!\/list/);
    });
```
- Output from running the test
```
MacBook-Pro-David:protractor david$ protractor --troubleshoot
[14:43:27] D/launcher - Running with --troubleshoot
[14:43:27] D/launcher - Protractor version: 4.0.8
[14:43:27] D/launcher - Your base url for tests is undefined
[14:43:27] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[14:43:27] I/launcher - Running 1 instances of WebDriver
[14:43:29] D/runner - WebDriver session successfully started with capabilities Capabilities {
  'applicationCacheEnabled' => false,
  'rotatable' => false,
  'mobileEmulationEnabled' => false,
  'networkConnectionEnabled' => false,
  'chrome' => { chromedriverVersion: '2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1)',
  userDataDir: '/var/folders/4v/vfdbkd6x76v1l6d__whf4szr0000gn/T/.org.chromium.Chromium.uzv0cZ' },
  'takesHeapSnapshot' => true,
  'pageLoadStrategy' => 'normal',
  'databaseEnabled' => false,
  'handlesAlerts' => true,
  'hasTouchScreen' => false,
  'version' => '54.0.2840.71',
  'platform' => 'MAC',
  'browserConnectionEnabled' => false,
  'nativeEvents' => true,
  'acceptSslCerts' => true,
  'webdriver.remote.sessionid' => '4e919372-05ee-4b55-bf00-d3a204be7cb5',
  'locationContextEnabled' => true,
  'webStorageEnabled' => true,
  'browserName' => 'chrome',
  'takesScreenshot' => true,
  'javascriptEnabled' => true,
  'cssSelectorsEnabled' => true }
[14:43:29] D/runner - Running with spec files /Users/david/WebstormProjects/Fusion/clientSrc/fusion/protractor/dp.spec.js
Started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
F

Failures:
1) Data Protection page button disabled enabled state and redirect
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at tryOnTimeout (timers.js:232:11)
        at Timer.listOnTimeout (timers.js:202:5)

1 spec, 1 failure
Finished in 100.05 seconds
```
```
MacBook-Pro-David:~ david$ webdriver-manager start
[14:42:35] I/start - java -Dwebdriver.chrome.driver=/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25 -Dwebdriver.gecko.driver=/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.9.0 -jar /usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar
[14:42:35] I/start - seleniumProcess.pid: 17846
14:42:36.137 INFO - Launching a standalone Selenium Server
14:42:36.211 INFO - Java: Oracle Corporation 9-ea+140
14:42:36.212 INFO - OS: Mac OS X 10.12.1 x86_64
14:42:36.236 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
14:42:36.297 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
14:42:36.297 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
14:42:36.297 INFO - Driver class not found: com.opera.core.systems.OperaDriver
14:42:36.298 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
14:42:36.299 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
14:42:36.300 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
14:42:36.354 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
14:42:36.355 INFO - Selenium Server is up and running
14:42:39.600 INFO - Executing: [new session: Capabilities [{count=1, browserName=chrome}]])
14:42:39.612 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome}]
Starting ChromeDriver 2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1) on port 35341
Only local connections are allowed.
14:42:40.664 INFO - Done: [new session: Capabilities [{count=1, browserName=chrome}]]
14:42:40.680 INFO - Executing: [set script timeout: 11000])
14:42:40.686 INFO - Done: [set script timeout: 11000]
14:42:40.783 INFO - Executing: [delete session: 00199c53-eb4b-4638-af94-220da4347223])
14:42:40.858 INFO - Done: [delete session: 00199c53-eb4b-4638-af94-220da4347223]
14:43:02.814 INFO - Executing: [new session: Capabilities [{count=1, browserName=chrome}]])
14:43:02.816 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome}]
Starting ChromeDriver 2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1) on port 36785
Only local connections are allowed.
14:43:03.538 INFO - Done: [new session: Capabilities [{count=1, browserName=chrome}]]
14:43:03.550 INFO - Executing: [set script timeout: 11000])
14:43:03.553 INFO - Done: [set script timeout: 11000]
14:43:03.651 INFO - Executing: [get: data:text/html,<html></html>])
[0.859][SEVERE]: Bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":28898,065881}}
[0.859][SEVERE]: Bad inspector message: {"method":"Page.domContentEventFired","params":{"timestamp":28898,066301}}
[11.152][SEVERE]: Unable to receive message from renderer
14:43:14.012 INFO - Done: [get: data:text/html,<html></html>]
^C[14:43:17] I/start - Staying alive until the Selenium Standalone process exits
[14:43:17] I/start - Selenium Standalone has exited with code 130
MacBook-Pro-David:~ david$ clear

MacBook-Pro-David:~ david$ webdriver-manager start
[14:43:25] I/start - java -Dwebdriver.chrome.driver=/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25 -Dwebdriver.gecko.driver=/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.9.0 -jar /usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar
[14:43:25] I/start - seleniumProcess.pid: 17889
14:43:26.102 INFO - Launching a standalone Selenium Server
14:43:26.138 INFO - Java: Oracle Corporation 9-ea+140
14:43:26.138 INFO - OS: Mac OS X 10.12.1 x86_64
14:43:26.163 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
14:43:26.223 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
14:43:26.224 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
14:43:26.224 INFO - Driver class not found: com.opera.core.systems.OperaDriver
14:43:26.224 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
14:43:26.226 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
14:43:26.226 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
14:43:26.282 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
14:43:26.282 INFO - Selenium Server is up and running
14:43:28.010 INFO - Executing: [new session: Capabilities [{count=1, browserName=chrome}]])
14:43:28.022 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome}]
Starting ChromeDriver 2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1) on port 24621
Only local connections are allowed.
14:43:29.060 INFO - Done: [new session: Capabilities [{count=1, browserName=chrome}]]
14:43:29.076 INFO - Executing: [set script timeout: 11000])
14:43:29.082 INFO - Done: [set script timeout: 11000]
14:43:29.178 INFO - Executing: [get: data:text/html,<html></html>])
[0.946][SEVERE]: Bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":28923,586737}}
[0.946][SEVERE]: Bad inspector message: {"method":"Page.domContentEventFired","params":{"timestamp":28923,587042}}
14:45:09.230 INFO - Executing: [delete session: 4e919372-05ee-4b55-bf00-d3a204be7cb5])
```

- The URL you are running your tests against (if relevant)
191.168.56.101

When I run tests, chrome opens and hangs 
![image](https://cloud.githubusercontent.com/assets/9194866/19766018/347fdfc0-9c54-11e6-83b5-c90d623d0ca7.png)
Tried reinstalling selenium, protractor, latest version of protractor nothing helped

**Comment by Akaryatrh** [comment]
@davoam In my team we just had a similar issue that we resolve thanks to https://bugs.chromium.org/p/chromedriver/issues/detail?id=1552#c38

**Comment by davoam** [comment]
@Akaryatrh Thank you very much!!! I spent whole day trying to fix it

**Comment by Akaryatrh** [comment]
Np :) Still, it's not related to OS version while my collegues had the same problem with OSX 10.11. We're not really sure what brought this issue, maybe a webdriver update (we automatically update it before launching tests)
