### ISSUE TITLE
Webdriver-manager update is giving issue on windows7

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#3680]
After installing protractor, When i Try to run webdriver-manager update command giving error
here is the error  pasted below.

**[16:01:34] I/downloader - selenium standalone: downloading version 2.53.1
[16:01:34] I/downloader - curl -o C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium/selenium-server-standalone-2.53.1.jar https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalon
e-2.53.1.jar
[16:01:34] I/downloader - chromedriver: downloading version 2.25
[16:01:34] I/downloader - curl -o C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium/chromedriver_2.25win32.zip https://chromedriver.storage.googleapis.com/2.25/chromedriver_win32.zip
[16:01:34] I/downloader - geckodriver: downloading version v0.9.0
[16:01:34] I/downloader - curl -o C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium/geckodriver-v0.9.0-win64.zip https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-win6
4.zip
[16:01:40] I/update - chromedriver: unzipping C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.25win32.zip
fs.js:997
  return binding.chmod(pathModule._makeLong(path), modeNum(mode));
                 ^

Error: EPERM: operation not permitted, chmod 'C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver.exe'
    at Error (native)
    at Object.fs.chmodSync (fs.js:997:18)
    at Object.module.exports.recoursive.writeFileTo (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\adm-zip\util\utils.js:108:20)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\adm-zip\adm-zip.js:381:23
    at Array.forEach (native)
    at Object.extractAllTo (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\adm-zip\adm-zip.js:372:26)
    at unzip (C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\lib\cmds\update.js:192:13)
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\lib\cmds\update.js:160:17
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\lib\files\downloader.js:33:17
    at C:\Users\vivekb\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\lib\files\downloader.js:158:21**

**Comment by NickTomlin** [comment]
I think this issue is best handled at the [webdriver manager repository](https://github.com/angular/webdriver-manager). I'm going to close this issue here. 

When you open a new issue please include the version of webdriver manager you are using as well as any relevant system details. 

Thanks!
