### ISSUE TITLE
protractor --capabilities.version command line option error with version as integer type

### ISSUE THREAD

**Issue by jhnet3** [angular/protractor#3688]
Bug report

---
protractor `--capabilities.version=<VERSION>` parses version as integer type.  That gets error from Selenium WebDriver.  If you change version to string type, then the browser version works correctly, without error.

- Node Version: `4.6.0`
- Protractor Version: `4.0.9`
- Angular Version: `Not relevant`
- Browser(s): `chrome`
- Operating System and Version `Windows 7 x64`
- protractor configuration file
```js
exports.config = {
  capabilities: {
    'browserName': 'chrome',
    'version': '47',
  },
```

- A relevant example test
```bash
protractor --capabilities.version=51 protractor.conf.js
```
- Output from running the test
```
"C:\Program Files\nodejs\node.exe" .\node_modules\protractor\built\cli.js --capabilities.version=51 protractor.conf.js
[10:26:29] I/hosted - Using the selenium server at http://hub.example.com:4444/wd/hub
[10:26:29] I/launcher - Running 1 instances of WebDriver
[10:26:29] E/launcher - Error forwarding the new session null
[10:26:29] E/launcher - WebDriverError: Error forwarding the new session null
    at WebDriverError (c:\Users\username\my-project\node_modules\selenium-webdriver\lib\error.js:27:10)
    at Object.checkLegacyResponse (c:\Users\username\my-project\node_modules\selenium-webdriver\lib\error.js:639:15)
    at parseHttpResponse (c:\Users\username\my-project\node_modules\selenium-webdriver\http\index.js:538:13)
    at c:\Users\username\my-project\node_modules\selenium-webdriver\http\index.js:472:11
    at ManagedPromise.invokeCallback_ (c:\Users\username\my-project\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (c:\Users\username\my-project\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (c:\Users\username\my-project\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at c:\Users\username\my-project\node_modules\selenium-webdriver\lib\promise.js:2820:25
    at c:\Users\username\my-project\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (node.js:369:9)
From: Task: WebDriver.createSession()
    at Function.createSession (c:\Users\username\my-project\node_modules\selenium-webdriver\lib\webdriver.js:329:24)
    at Builder.build (c:\Users\username\my-project\node_modules\selenium-webdriver\builder.js:458:24)
    at Hosted.DriverProvider.getNewDriver (c:\Users\username\my-project\node_modules\protractor\built\driverProviders\driverProvider.js:37:33)
    at Runner.createBrowser (c:\Users\username\my-project\node_modules\protractor\built\runner.js:198:43)
    at c:\Users\username\my-project\node_modules\protractor\built\runner.js:277:30
    at _fulfilled (c:\Users\username\my-project\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (c:\Users\username\my-project\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (c:\Users\username\my-project\node_modules\q\q.js:796:13)
    at c:\Users\username\my-project\node_modules\q\q.js:556:49
    at runSingle (c:\Users\username\my-project\node_modules\q\q.js:137:13)
```

- Steps to reproduce the bug
```bash
protractor --capabilities.version=51 protractor.conf.js
```

If you insert this line after built\cli.js:77:
```js
// Convert int to string
if (argv.capabilities && argv.capabilities.version && Number.isInteger(argv.capabilities.version)) { argv.capabilities.version = argv.capabilities.version.toString(); }
```

Then the error does not happen, and it launches the correct browser version as specified.

- The URL you are running your tests against (if relevant): 
Not relevant

**Comment by NickTomlin** [comment]
Very interesting, thanks for bringing this up. So just to be clear, running protractor with the configuration file you've specified works, but when you override it via the cli it does not.

**Comment by NickTomlin** [comment]
I'm not able to reproduce this with the latest protractor and the example config. Going to go ahead and close for now.
