### ISSUE TITLE
webdriver-manager is broken !!!

### ISSUE THREAD

**Issue by MrMic** [angular/protractor#3700]
Hi,

I have installed protractor with: npm install -g protractor
on my Mac OSX Sierra.
and then run: webdriver-manager update
Here is the output:

/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cmds/update.js:85
        if (path.isAbsolute(options[Opt.OUT_DIR].getString())) {
                 ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at Program.update [as runMethod] (/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cmds/update.js:85:18)
    at Program.run (/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cli/programs.js:60:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/webdriver.js:25:38)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/protractor/bin/webdriver-manager:3:1)

Thanks for the reply.
Rgds,

**Comment by rahatarmanahmed** [comment]
What's your node version? `path.isAbsolute()` was added in v0.11.2. (Protractor supports node v4 and up)

**Comment by MrMic** [comment]
Yes indeed.
I found that my version was too old ...
Sorry for the noise.

CLOSED

Thx.
Rgds,
