### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by tommyz0123** [angular/protractor#3714]
Lately, we've been seen ETIMEDOUT errors.  We run protractor tests using a remote selenium grid.

`
Message:
    Failed: ETIMEDOUT connect ETIMEDOUT 10.14.237.94:4444
  Stack:
    Error: ETIMEDOUT connect ETIMEDOUT 10.14.237.94:4444
        at ClientRequest.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:381:15)
        at emitOne (events.js:77:13)
        at ClientRequest.emit (events.js:169:7)
        at Socket.socketErrorListener (_http_client.js:259:9)
        at emitOne (events.js:77:13)
        at Socket.emit (events.js:169:7)
        at emitErrorNT (net.js:1250:8)
        at doNTCallback2 (node.js:430:9)
        at process._tickCallback (node.js:344:17)
`

protractor version = Version 4.0.9
node version = v4.1.2
selenium = 2.53.1

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
