### ISSUE TITLE
E/launcher - Process exited with error code 199, a new tab opens up and gets closed immediately 

### ISSUE THREAD

**Issue by melanieannthomas** [angular/protractor#3748]
Hi there!
When protractor run command is given
A tab shows up and gets closed immediately then shows the following error.

[14:50:43] I/direct - Using ChromeDriver directly...
[14:50:43] I/launcher - Running 1 instances of WebDriver
[14:50:44] E/launcher - session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"9272.1","isDef
ault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.99)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 10.0.143
93 x86_64)
[14:50:44] E/launcher - SessionNotCreatedError: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"9272.1","isDef
ault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.99)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 10.0.143
93 x86_64)
    at WebDriverError (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdr
iver\lib\error.js:27:5)
    at SessionNotCreatedError (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\seleni
um-webdriver\lib\error.js:308:5)
    at Object.checkLegacyResponse (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\se
lenium-webdriver\lib\error.js:639:15)
    at parseHttpResponse (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-we
bdriver\http\index.js:538:13)
    at client_.send.then.response (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\se
lenium-webdriver\http\index.js:472:11)
    at ManagedPromise.invokeCallback_ (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_module
s\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-w
ebdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\seleni
um-webdriver\lib\promise.js:2896:21)
    at asyncRun (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\l
ib\promise.js:2820:25)
    at C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise
.js:639:7
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\seleni
um-webdriver\lib\webdriver.js:329:24)
    at Driver (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\chr
ome.js:778:38)
    at Direct.getNewDriver (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\
direct.js:68:26)
    at Runner.createBrowser (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\built\runner.js:198:4
3)
    at C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\built\runner.js:277:30
    at _fulfilled (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q
.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modul
es\q\q.js:796:13)
    at C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\Users\melaniet\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:137:13)
[14:50:44] E/launcher - Process exited with error code 199

Please help me in solving it....

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by planktonlex55** [comment]
+1. 
Am able to reproduce same error on Window 7.  
I got powershell3, scoop, openjdk installed and also changed the browser to firefox (Refered https://github.com/angular/protractor/issues/1424 ) and still jack squat. The new tab open on firefox, nothing happens and I get below dump.

Error log trail is below.

`
[13:13:51] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[13:13:51] I/launcher - Running 1 instances of WebDriver
[13:14:37] E/launcher - Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
criptFF.gif","icon64URL":null,"defaultLocale":{"name":"IDS_SS_NAME","description":null,"creator":"McAfee, Inc.","homepageURL":null},"visible":true,"active":fal
bled":true,"appDisabled":true,"descriptor":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","installDate":1475565878646,"updateDate":1475565878646,"
undUpdates":1,"bootstrap":false,"skinnable":false,"size":2625095,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryC
alse,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"1.5","maxVersion":"9.9"}],"tar
":[],"multiprocessCompatible":false,"signedState":0,"seen":true}
1480405432967   DeferredSave.extensions.json    DEBUG   Save changes
1480405432967   addons.xpi      DEBUG   Updating database with changes to installed add-ons
1480405432967   addons.xpi-utils        DEBUG   Updating add-on states
1480405432968   addons.xpi-utils        DEBUG   Writing add-ons list
1480405432976   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1480405432977   addons.xpi      DEBUG   Calling bootstrap method startup on aushelper@mozilla.org version 1.0
1480405432978   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1480405432979   addons.xpi      DEBUG   Calling bootstrap method startup on e10srollout@mozilla.org version 1.5
1480405432979   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1480405432980   addons.xpi      DEBUG   Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1480405432981   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1480405432981   addons.xpi      DEBUG   Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1480405432983   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1480405432983   addons.manager  DEBUG   Provider finished startup: XPIProvider
1480405432984   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1480405432984   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1480405432984   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1480405432984   addons.manager  DEBUG   Starting provider: GMPProvider
1480405432993   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1480405432993   addons.manager  DEBUG   Provider finished startup: GMPProvider
1480405432993   addons.manager  DEBUG   Starting provider: PluginProvider
1480405432993   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1480405432994   addons.manager  DEBUG   Provider finished startup: PluginProvider
1480405432994   addons.manager  DEBUG   Completed startup sequence
1480405433468   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1480405433468   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1480405433469   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1480405433682   DeferredSave.extensions.json    DEBUG   Write succeeded
1480405433682   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
1480405433682   DeferredSave.extensions.json    DEBUG   Starting timer
1480405433704   DeferredSave.extensions.json    DEBUG   Starting write
1480405433966   addons.repository       DEBUG   No addons.json found.
1480405433966   DeferredSave.addons.json        DEBUG   Save changes
1480405433969   DeferredSave.addons.json        DEBUG   Starting timer
1480405434011   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1480405434012   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1480405434012   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1480405434134   DeferredSave.addons.json        DEBUG   Starting write
1480405434359   DeferredSave.extensions.json    DEBUG   Write succeeded
1480405434411   DeferredSave.addons.json        DEBUG   Write succeeded

[13:14:37] E/launcher - WebDriverError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
criptFF.gif","icon64URL":null,"defaultLocale":{"name":"IDS_SS_NAME","description":null,"creator":"McAfee, Inc.","homepageURL":null},"visible":true,"active":fal
bled":true,"appDisabled":true,"descriptor":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","installDate":1475565878646,"updateDate":1475565878646,"
undUpdates":1,"bootstrap":false,"skinnable":false,"size":2625095,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryC
alse,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"1.5","maxVersion":"9.9"}],"tar
":[],"multiprocessCompatible":false,"signedState":0,"seen":true}
1480405432967   DeferredSave.extensions.json    DEBUG   Save changes
1480405432967   addons.xpi      DEBUG   Updating database with changes to installed add-ons
1480405432967   addons.xpi-utils        DEBUG   Updating add-on states
1480405432968   addons.xpi-utils        DEBUG   Writing add-ons list
1480405432976   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1480405432977   addons.xpi      DEBUG   Calling bootstrap method startup on aushelper@mozilla.org version 1.0
1480405432978   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1480405432979   addons.xpi      DEBUG   Calling bootstrap method startup on e10srollout@mozilla.org version 1.5
1480405432979   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1480405432980   addons.xpi      DEBUG   Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1480405432981   addons.xpi      DEBUG   Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1480405432981   addons.xpi      DEBUG   Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1480405432983   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1480405432983   addons.manager  DEBUG   Provider finished startup: XPIProvider
1480405432984   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1480405432984   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1480405432984   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1480405432984   addons.manager  DEBUG   Starting provider: GMPProvider
1480405432993   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1480405432993   addons.manager  DEBUG   Provider finished startup: GMPProvider
1480405432993   addons.manager  DEBUG   Starting provider: PluginProvider
1480405432993   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1480405432994   addons.manager  DEBUG   Provider finished startup: PluginProvider
1480405432994   addons.manager  DEBUG   Completed startup sequence
1480405433468   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1480405433468   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1480405433469   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1480405433682   DeferredSave.extensions.json    DEBUG   Write succeeded
1480405433682   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
1480405433682   DeferredSave.extensions.json    DEBUG   Starting timer
1480405433704   DeferredSave.extensions.json    DEBUG   Starting write
1480405433966   addons.repository       DEBUG   No addons.json found.
1480405433966   DeferredSave.addons.json        DEBUG   Save changes
1480405433969   DeferredSave.addons.json        DEBUG   Starting timer
1480405434011   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1480405434012   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1480405434012   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1480405434134   DeferredSave.addons.json        DEBUG   Starting write
1480405434359   DeferredSave.extensions.json    DEBUG   Write succeeded
1480405434411   DeferredSave.addons.json        DEBUG   Write succeeded

    at WebDriverError (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:5)
    at Object.checkLegacyResponse (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:639:15)
    at parseHttpResponse (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:538:13)
    at client_.send.then.response (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:472:11)
    at ManagedPromise.invokeCallback_ (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at asyncRun (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2820:25)
    at C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:329:24)
    at Builder.build (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\builder.js:458:24)
    at Hosted.DriverProvider.getNewDriver (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:37:33)
    at Runner.createBrowser (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\built\runner.js:197:43)
    at C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\built\runner.js:276:30
    at _fulfilled (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\Users\plankton\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:137:13)
[13:14:37] E/launcher - Process exited with error code 199
`
