### ISSUE TITLE
protractor not work

### ISSUE THREAD

**Issue by smff** [angular/protractor#3755]
node -v: v4.4.6
protractor: Version 4.0.11
browser: Chrome 54.0.2840.98
mac os x: 10.12.1
---
Got example from http://www.protractortest.org/. Creating to-do.spec.js and etc.
Run  webdriver-manager start
Run protractor conf.js

dima:protractor dima$ protractor conf.js
[18:18:38] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[18:18:38] I/launcher - Running 1 instances of WebDriver
[18:18:41] E/launcher - session not created exception
from unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":338691,247399}}
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.18 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'dima', ip: '10.0.8.56', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.7.0_71'
Driver info: org.openqa.selenium.chrome.ChromeDriver
[18:18:41] E/launcher - SessionNotCreatedError: session not created exception
from unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":338691,247399}}
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.18 seconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'dima', ip: '10.0.8.56', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.7.0_71'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at WebDriverError (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:10)
    at SessionNotCreatedError (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:308:10)
    at Object.checkLegacyResponse (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
    at /Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11
    at ManagedPromise.invokeCallback_ (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at /Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25
    at /Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Builder.build (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:458:24)
    at Hosted.DriverProvider.getNewDriver (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
    at Runner.createBrowser (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/built/runner.js:197:43)
    at /Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/built/runner.js:276:30
    at _fulfilled (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/Users/dima/.nvm/versions/node/v4.4.6/lib/node_modules/protractor/node_modules/q/q.js:137:13)
[18:18:41] E/launcher - Process exited with error code 199

**Comment by smff** [comment]
lol: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1552#c38
