### ISSUE TITLE
Can't evaluate Angular variables in forked browsers

### ISSUE THREAD

**Issue by mrcity** [angular/protractor#3764]
Hi, I can't get Protractor to evaluate variables scoped inside elements on other browser instances besides `browser` itself.  There is tabular data loaded up on the page through repeaters and it'd be nice to get to that data straight from the variable instead of having to crawl through the UI.

- Node Version: `4.4.7`
- Protractor Version: `4.0.11`
- Angular Version: `1.5.5`
- Browser(s): `Chrome 54`
- Operating System and Version `Mac OSX 10.11.6`
- Your protractor configuration file
(Highlights: using Marionette and Cucumber)

```
var prefix = 'src/test/javascript/'.replace(/[^/]+/g,'..');

exports.config = {
    seleniumServerJar: prefix + 'chat-client/chat-static-resources/node_modules/protractor/selenium/selenium-server-standalone-2.52.0.jar',
    chromeDriver: prefix + 'chat-client/chat-static-resources/node_modules/chromedriver/lib/chromedriver/chromedriver',
    allScriptsTimeout: 20000,

    suites: {
        chat: './e2e/chat/prepResponses.feature'
    },

    capabilities: {
        'browserName': 'chrome',
        'marionette': true
    },

    directConnect: true,

    framework: 'custom',
    frameworkPath: '../node_modules/protractor-cucumber-framework',
    cucumberOpts: {
        require: './e2e/**/*.js',
        format: 'progress'
    },

    onPrepare: function() {
        browser.driver.manage().window().setSize(1024, 800);
    }
};
```

- A relevant example test
```
this.When(/^we open a second browser and evaluate variables$/, {timeout: 5000}, function(next) {
    var secondBrowser = browser.forkNewDriverInstance();
    browser.get("/path/to/url");
    secondBrowser.get("/path/to/url");
    browser.element(by.id("messageHolder")).evaluate("vm").then(function (vm) {
        console.log("vm in browser: ", vm);
        secondBrowser.element(by.id("messageHolder")).evaluate("vm").then(function (vm) {
            console.log("vm in agentBrowser: ", vm);
            next();
        });
    });
});
```
- Output from running the test
```
vm in browser:  { email: 'custo@mer.com', name: 'Customer' }

[10:23:05] E/launcher - unknown error: Cannot read property '$eval' of undefined
(Session info: chrome=54.0.2840.87)
(Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)
[10:23:05] E/launcher - WebDriverError: unknown error: Cannot read property '$eval' of undefined
(Session info: chrome=54.0.2840.87)
(Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)
at WebDriverError (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:10)
at Object.checkLegacyResponse (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
at parseHttpResponse (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
at /MyApp/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11
at ManagedPromise.invokeCallback_ (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
at TaskQueue.execute_ (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
at TaskQueue.executeNext_ (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
at /MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25
at /MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
at process._tickCallback (node.js:369:9)
From: Task: WebDriver.executeScript()
at Driver.schedule (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:377:17)
at Driver.executeScript (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:526:16)
at evaluationFn (/MyApp/node_modules/protractor/built/element.js:597:40)
at Array.map (native)
at /MyApp/node_modules/protractor/built/element.js:399:69
at ManagedPromise.invokeCallback_ (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
at TaskQueue.execute_ (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
at TaskQueue.executeNext_ (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
at /MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2775:27
at /MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7Error
at ElementArrayFinder.applyAction_ (/MyApp/node_modules/protractor/built/element.js:397:27)
at ElementArrayFinder.evaluate (/MyApp/node_modules/protractor/built/element.js:599:21)
at ElementFinder.evaluate (/MyApp/node_modules/protractor/built/element.js:962:41)
at /MyApp/test/e2e/chat/prepResponses.js:30:66
at /MyApp/node_modules/protractor/built/element.js:697:32
at ManagedPromise.invokeCallback_ (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
at TaskQueue.execute_ (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
at TaskQueue.executeNext_ (/MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
at /MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2775:27
at /MyApp/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    [10:23:05] E/launcher - Process exited with error code 199
```
- Steps to reproduce the bug
Open up two browser instances (i.e. one more with browser.forkNewDriverInstance()).  Then, load up an Angular page into both instances, and try to evaluate one of the variables scoped to an element.  It works on the original browser instance but not the forked instance.

**Comment by cnishina** [comment]
This does not appear to be reproducible.

```
import { browser, by, element, ProtractorBrowser } from 'protractor';

describe('protractor testapp', function() {
  let browser2: ProtractorBrowser;

  beforeEach(() => {
    browser2 = browser.forkNewDriverInstance();
    browser.get('http://www.protractortest.org/testapp/ng1/#/form');
    browser2.get('http://www.protractortest.org/testapp/ng1/#/form');
  });

  it('should evaluate check.w after click', () => {
    element(by.model('check.w')).click();
    let checkw = element(by.id('letterlist')).evaluate('check.w').getText();
    expect(checkw).toEqual('w');

    let element2 = browser2.element;
    element2(by.model('check.w')).click();
    let checkw2 = element(by.id('letterlist')).evaluate('check.w').getText();
    expect(checkw2).toEqual('w');
  });
});

```

Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by mrcity** [comment]
Interesting.  I've played with your code snippet quite a bit and haven't gotten it to fail, even after adding in Cucumber & Chai.  I'll keep looking into the reason it's failing in my production test suite.  Thanks for the help.
