### ISSUE TITLE
Error: Angular could not be found on the page http://localhost:9999

### ISSUE THREAD

**Issue by sayedabdelgleel** [angular/protractor#384]
Shutting down selenium standalone server.

/media/Work/Projects/angularjs-seed-repo/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1542
      throw error;
            ^
Error: Angular could not be found on the page http://localhost:9999/# : retries looking for angular exceeded
    at assertAngularOnPage (/media/Work/Projects/angularjs-seed-repo/node_modules/protractor/lib/protractor.js:516:13)
    at /media/Work/Projects/angularjs-seed-repo/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1178:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/media/Work/Projects/angularjs-seed-repo/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1438:20)
    at notify (/media/Work/Projects/angularjs-seed-repo/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:328:12)
    at notifyAll (/media/Work/Projects/angularjs-seed-repo/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:297:7)
    at fulfill (/media/Work/Projects/angularjs-seed-repo/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:402:7)
    at Object.webdriver.promise.asap (/media/Work/Projects/angularjs-seed-repo/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:672:5)
    at webdriver.promise.ControlFlow.runInNewFrame_ (/media/Work/Projects/angularjs-seed-repo/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1449:25)
    at notify (/media/Work/Projects/angularjs-seed-repo/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:328:12)
    at notifyAll (/media/Work/Projects/angularjs-seed-repo/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:297:7)

**Comment by flexin777** [comment]
Hi! I have the same issue. Did you fixed it?

**Comment by bvsunil6686** [comment]
I also have the same issue. Did anyone got it fixed please ?

**Comment by flexin777** [comment]
Hello. That page did not contain Angular. Does your page contains angular?

**Comment by bvsunil6686** [comment]
Thanks I got it.
above error got fixed by adding browser.ignoreSynchronization = true;

**Comment by flexin777** [comment]
yes)
