### ISSUE TITLE
When angular cannot be found, the process exits and the remainder of the test suite is abandoned

### ISSUE THREAD

**Issue by massimocode** [angular/protractor#3885]
So I've been looking through a backlog of around 3000 runs of our E2E test suite and noticed that whenever an error is raised that angular can't be found (like if the target website is down altogether), then the process exits and no further tests are run. I would expect the rest of the tests to be attempted as well.

Any ideas? (stack trace below, happy to provide more info as necessary)

```
[20:01:42] E/launcher - Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
[20:01:42] E/launcher - Error: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
    at C:\BuildAgent\work\3dfb50560195375c\node_modules\protractor\built\browser.js:272:23
    at ManagedPromise.invokeCallback_ (C:\BuildAgent\work\3dfb50560195375c\node_modules\selenium-webdriver\lib\promise.js:1379:14)
    at TaskQueue.execute_ (C:\BuildAgent\work\3dfb50560195375c\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (C:\BuildAgent\work\3dfb50560195375c\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at asyncRun (C:\BuildAgent\work\3dfb50560195375c\node_modules\selenium-webdriver\lib\promise.js:2775:27)
    at C:\BuildAgent\work\3dfb50560195375c\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
[20:01:42] E/launcher - Process exited with error code 199
```

package.json
```json
{
  "name": "",
  "version": "0.0.0",
  "description": "",
  "main": "Gruntfile.js",
  "scripts": {
    "postinstall": "webdriver-manager update",
    "test": "grunt test",
    "e2etest": "grunt e2e_test",
    "lint-test": "node node_modules/tslint/bin/tslint -c protractor-tests/tslint.json protractor-tests/**/*.ts",
    "install": "npm run compile && npm run compile-sass && grunt ngtemplates",
    "compile": "node node_modules/typescript/bin/tsc -p protractor-tests/tsconfig.json",
    "compile-sass": "grunt sass"
  },
  "repository": {
    "type": "git"
  },
  "devDependencies": {
    "//": [
      "The @types/selenium-webdriver dependency is temporary and should not be needed.",
      "See http://stackoverflow.com/questions/41232228/running-npm-start-fails-due-to-error",
      "http://stackoverflow.com/questions/14221579/how-do-i-add-comments-to-package-json-for-npm-install"
    ],
    "@types/angular": "^1.5.20",
    "@types/angular-animate": "^1.5.5",
    "@types/angular-mocks": "0.0.0",
    "@types/jasmine": "^2.5.38",
    "@types/mssql": "^3.1.30",
    "@types/node": "0.0.2",
    "@types/request-promise": "^4.1.33",
    "@types/selenium-webdriver": "2.53.33",
    "eslint": "^3.11.1",
    "grunt": "~0.4.1",
    "grunt-angular-templates": "^1.1.0",
    "grunt-cli": "~0.1.13",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-iisexpress": "*",
    "grunt-protractor-runner": "^4.0.0",
    "grunt-sass": "^1.2.1",
    "jasmine-reporters": ">2.0.0",
    "mssql": "*",
    "promise-mysql": "^1.3.2",
    "protractor": "^4.0.11",
    "request-promise": "^4.1.1",
    "tslint": "^4.0.2",
    "typescript": "^2.1.1"
  },
  "author": " ",
  "license": "ISC",
  "dependencies": {}
}
```

protractor config
```typescript
import { specNameRecorder } from "./features/support/current-spec-helper";

export let config = {
    allScriptsTimeout: 30000,
    baseUrl: "http://localhost:9001",
    restartBrowserBetweenTests: true,
    framework: "jasmine2",
    specs: [
        "./**/*steps.js"
    ],
    capabilities: {
        browserName: "chrome",
        chromeOptions: {
            args: ["--test-type", "--no-sandbox"],
        },
        loggingPrefs: {
            browser: "ALL"
        },
        "proxy": {
            "proxyType": "manual",
            "httpProxy": "localhost:12543",
            "httpsProxy": "localhost:12543",
            "sslProxy": "localhost:12543"
        }
    },
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 5 * 60 * 1000
    },
    onPrepare: function () {
        // Set up Jasmine Reporters
        let reporters = require("jasmine-reporters");
        if (process.env.TEAMCITY_VERSION) {
            jasmine.getEnv().addReporter(new reporters.TeamCityReporter());
        } else {
            jasmine.getEnv().addReporter(new reporters.TerminalReporter({ verbosity: 3 }));
        }

        jasmine.getEnv().addReporter(specNameRecorder);
    }
};
```

**Comment by massimocode** [comment]
package.json
```json
{
  "name": "",
  "version": "0.0.0",
  "description": "",
  "main": "Gruntfile.js",
  "scripts": {
    "postinstall": "webdriver-manager update",
    "test": "grunt test",
    "e2etest": "grunt e2e_test",
    "lint-test": "node node_modules/tslint/bin/tslint -c protractor-tests/tslint.json protractor-tests/**/*.ts",
    "install": "npm run compile && npm run compile-sass && grunt ngtemplates",
    "compile": "node node_modules/typescript/bin/tsc -p protractor-tests/tsconfig.json",
    "compile-sass": "grunt sass"
  },
  "repository": {
    "type": "git"
  },
  "devDependencies": {
    "//": [
      "The @types/selenium-webdriver dependency is temporary and should not be needed.",
      "See http://stackoverflow.com/questions/41232228/running-npm-start-fails-due-to-error",
      "http://stackoverflow.com/questions/14221579/how-do-i-add-comments-to-package-json-for-npm-install"
    ],
    "@types/angular": "^1.5.20",
    "@types/angular-animate": "^1.5.5",
    "@types/angular-mocks": "0.0.0",
    "@types/jasmine": "^2.5.38",
    "@types/mssql": "^3.1.30",
    "@types/node": "0.0.2",
    "@types/request-promise": "^4.1.33",
    "@types/selenium-webdriver": "2.53.33",
    "eslint": "^3.11.1",
    "grunt": "~0.4.1",
    "grunt-angular-templates": "^1.1.0",
    "grunt-cli": "~0.1.13",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-iisexpress": "*",
    "grunt-protractor-runner": "^4.0.0",
    "grunt-sass": "^1.2.1",
    "jasmine-reporters": ">2.0.0",
    "mssql": "*",
    "promise-mysql": "^1.3.2",
    "protractor": "^4.0.11",
    "request-promise": "^4.1.1",
    "tslint": "^4.0.2",
    "typescript": "^2.1.1"
  },
  "author": " ",
  "license": "ISC",
  "dependencies": {}
}
```

**Comment by sjelin** [comment]
This is working as intended.  You should use [`ignoreSynchronization`](https://github.com/angular/protractor/blob/master/lib/browser.ts#L192) for non-angular pages.  If you have more support questions (i.e. not bug reports or feature requests), please ask them on stackoverflow so other people can benefit from your quesiton

**Comment by massimocode** [comment]
I'd like to open this ticket again. The reason is that we saw end to end tests failing today for the following reason:

1) Go to a website with Angular
2) Do some stuff
3) Go to another website with Angular
4) This other website was showing an error page which does not have Angular on it
5) The whole of our test suite exited without attempting the remaining tests

This kind of error should not tear down the whole node process. It should fail the test for the reason that window.angular is undefined, and then carry on fresh with the next test.
