### ISSUE TITLE
"Unexpected identifier 'hooks'" issue on Safari 9

### ISSUE THREAD

**Issue by mgiambalvo** [angular/protractor#3955]
Our Travis smoke tests (which have never been particularly reliable) are showing a bunch of failures on Safari 9 related to the new client-side scripts (https://github.com/angular/protractor/pull/3928). Here's an example of the failure from [this Travis run](https://travis-ci.org/angular/protractor/jobs/190819052):

```
[safari 9 #21] [01:48:01] I/sauce - Using SauceLabs selenium server at http://ondemand.saucelabs.com:80/wd/hub
[safari 9 #21] Started
[safari 9 #21] FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.F.FFFFFFFF
[safari 9 #21] 
[safari 9 #21] Failures:
[safari 9 #21] 1) locators by binding should find an element by binding
[safari 9 #21]   Message:
[safari 9 #21]     Failed: Unexpected identifier 'hooks' (WARNING: The server did not provide any stacktrace information)
[safari 9 #21]     Command duration or timeout: 74 milliseconds
[safari 9 #21]     Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
[safari 9 #21]     System info: host: 'itako61081.prod.miso', ip: '172.20.61.81', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_102'
[safari 9 #21]     Driver info: org.openqa.selenium.safari.SafariDriver
[safari 9 #21]     Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.1.2, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
[safari 9 #21]     Session ID: null
[safari 9 #21]   Stack:
[safari 9 #21]     WebDriverError: Unexpected identifier 'hooks' (WARNING: The server did not provide any stacktrace information)
[safari 9 #21]     Command duration or timeout: 74 milliseconds
[safari 9 #21]     Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
[safari 9 #21]     System info: host: 'itako61081.prod.miso', ip: '172.20.61.81', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_102'
[safari 9 #21]     Driver info: org.openqa.selenium.safari.SafariDriver
[safari 9 #21]     Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.1.2, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
[safari 9 #21]     Session ID: null
[safari 9 #21]         at WebDriverError (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
[safari 9 #21]         at Object.checkLegacyResponse (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
[safari 9 #21]         at parseHttpResponse (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
[safari 9 #21]         at doSend.then.response (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
[safari 9 #21]         at process._tickCallback (internal/process/next_tick.js:103:7)
[safari 9 #21]     From: Task: Protractor.waitForAngular() - Locator: by.binding("greeting")
[safari 9 #21]         at WebDriver.schedule (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
[safari 9 #21]         at ProtractorBrowser.executeAsyncScript_ (/home/travis/build/angular/protractor/lib/browser.ts:497:24)
[safari 9 #21]         at runWaitForAngularScript (/home/travis/build/angular/protractor/lib/browser.ts:527:21)
[safari 9 #21]         at ProtractorBrowser.waitForAngular (/home/travis/build/angular/protractor/lib/browser.ts:533:12)
[safari 9 #21]         at ElementArrayFinder.getWebElements (/home/travis/build/angular/protractor/lib/element.ts:160:21)
[safari 9 #21]         at ElementArrayFinder.getWebElements (/home/travis/build/angular/protractor/lib/element.ts:817:33)
[safari 9 #21]         at ElementArrayFinder.applyAction_ (/home/travis/build/angular/protractor/lib/element.ts:464:30)
[safari 9 #21]         at ElementArrayFinder.(anonymous function) [as getText] (/home/travis/build/angular/protractor/lib/element.ts:95:21)
[safari 9 #21]         at ElementFinder.(anonymous function) [as getText] (/home/travis/build/angular/protractor/lib/element.ts:841:14)
[safari 9 #21]         at Object.<anonymous> (/home/travis/build/angular/protractor/spec/basic/locators_spec.js:10:23)Error
[safari 9 #21]         at ElementArrayFinder.applyAction_ (/home/travis/build/angular/protractor/lib/element.ts:463:23)
[safari 9 #21]         at ElementArrayFinder.(anonymous function) [as getText] (/home/travis/build/angular/protractor/lib/element.ts:95:21)
[safari 9 #21]         at ElementFinder.(anonymous function) [as getText] (/home/travis/build/angular/protractor/lib/element.ts:841:14)
[safari 9 #21]         at Object.<anonymous> (/home/travis/build/angular/protractor/spec/basic/locators_spec.js:10:23)
[safari 9 #21]         at /home/travis/build/angular/protractor/node_modules/jasminewd2/index.js:102:25
[safari 9 #21]         at new ManagedPromise (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:1067:7)
[safari 9 #21]         at controlFlowExecute (/home/travis/build/angular/protractor/node_modules/jasminewd2/index.js:87:18)
[safari 9 #21]         at TaskQueue.execute_ (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
[safari 9 #21]         at TaskQueue.executeNext_ (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
[safari 9 #21]         at asyncRun (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2860:25)
[safari 9 #21]     From: Task: Run it("should find an element by binding") in control flow
[safari 9 #21]         at Object.<anonymous> (/home/travis/build/angular/protractor/node_modules/jasminewd2/index.js:86:14)
[safari 9 #21]         at /home/travis/build/angular/protractor/node_modules/jasminewd2/index.js:61:7
[safari 9 #21]         at ControlFlow.emit (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/events.js:62:21)
[safari 9 #21]         at ControlFlow.shutdown_ (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2565:10)
[safari 9 #21]         at shutdownTask_.MicroTask (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2490:53)
[safari 9 #21]         at MicroTask.asyncRun (/home/travis/build/angular/protractor/node_modules/selenium-webdriver/lib/promise.js:2619:9)
[safari 9 #21]     From asynchronous test: 
[safari 9 #21]     Error
[safari 9 #21]         at Suite.<anonymous> (/home/travis/build/angular/protractor/spec/basic/locators_spec.js:7:5)
[safari 9 #21]         at Suite.<anonymous> (/home/travis/build/angular/protractor/spec/basic/locators_spec.js:6:3)
[safari 9 #21]         at Object.<anonymous> (/home/travis/build/angular/protractor/spec/basic/locators_spec.js:1:1)
```

I suspect the problem is some kind of annoying inconsistency in Safari 9. Note that we use selenium version 2.44.0 for Safari 9, which might be related.

**Comment by mgiambalvo** [comment]
Fixed by #3963, Safari 9 doesn't support ES6 let statement.
