### ISSUE TITLE
Error: Found extra flags: intellijOriginalConfigFile 

### ISSUE THREAD

**Issue by pittgoose** [angular/protractor#3956]
Just upgraded to 5.0.0 and when I went to run my tests with WebStorm I got this error:
```
Error: Found extra flags: intellijOriginalConfigFile
    at Object.<anonymous> (C:\web-automation\node_modules\protractor\built\cli.js:172:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\web-automation\node_modules\protractor\bin\protractor:5:1)
    at Module._compile (module.js:570:32)
```
It seems that WebStorm is passing an unknown argument to Protractor and is therefore failing to run. This is not happening when I run from command line.
I guess I should probably open a bug to WebStorm too, but this should likely be handled here as well.

**Comment by NickTomlin** [comment]
I think this is best handled on the WebStorm side for now. I'm going to go ahead and close this issue . If the WebStorm investigation points to a bug in Protractor please feel free to open another issue with the details. 

Thanks! 😄

**Comment by benc** [comment]
I've filed a bug with JetBrains: https://youtrack.jetbrains.com/issue/WEB-25161
