### ISSUE TITLE
Protractor throws errors on unknown commandline flags.

### ISSUE THREAD

**Issue by krotscheck** [angular/protractor#3959]
Bug report
---
Breaking change introduced by https://github.com/angular/protractor/pull/3921 should be reverted.

Our project has implemented commandline flags (using yargs) that allow us to adjust the protractor.conf.js file to meet our environment needs. For example, we've implemented karma's `--browsers` flag to selectively filter our multiCapabilities list, so that devs can execute e2e tests against a specific browser without having to launch all the other ones.

- Node Version: `7.4`
- Protractor Version: `5.0.0`
- Angular Version: `2.2.4`
- Browser(s): `N/A`
- Operating System and Version `macOS Sierra`
- Your protractor configuration file:
```javascript:
{
  ...,
  multiCapabilities: util.buildMultiCapabilities(args.browsers),
  ...
}
```

- A relevant example test
```
protractor --browsers=Safari-10,Safari-9.1
```
- Output from running the test
```
Error: Found extra flags: browsers
    at Object.<anonymous> (~/ui/node_modules/protractor/built/cli.js:172:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~/ui/node_modules/protractor/bin/protractor:5:1)
    at Module._compile (module.js:571:32)
```
- Steps to reproduce the bug

1. Attempt to invoke protractor with a non-standard commandline flag or option.

**Comment by cnishina** [comment]
Please read the CHANGELOG. It says you should just send an additional flag `--disableChecks`
