### ISSUE TITLE
WebDriver Error Cannot use 'in' operator to search for 'String' in false

### ISSUE THREAD

**Issue by MihailSeykov** [angular/protractor#3962]
I have been using selenium webdriver with protractor for more than a year now and recently after updating to the newest versions of both protractor(5.0.0) and selenium-webdriver(3.0.1), i got an error that i have never encountered before. As stated in the title my error is - "WebDriver Error Cannot use 'in' operator to search for 'String' in false". I am doing everything in the code as always, but even my old tests which were working correctly and were used everyday, don't work now. The tests starts and navigate to the page correctly(which is the first step in the test), but everything after that fails no matter if it is only clicking, or typing. I submit this here, because i believe the error is from protractor, sorry if i am wrong and this is not the right place.

I tried searching everywhere, but did not find someone having the same problem as me, submitted a question on stackoverflow too, but no answer for more than 3 days now.I have all my tests at work failing for more than a week now. Please help.

Here is my code

The spec.ts file:
```
describe('102001 - External Payments - own portfolio; recurring - no end date', function () {

    var LoginPage = require('./Page/Login_Page/Login_page.js');
    var OverviewPage = require('./Page/Overview_Page/Overview_page.js');
    var BeleggenPage = require('./Page/Beleggen_Page/Beleggen_Page.js');
    var BepaalJeKennisprofielPage = require('./Page/BepaalJeKennisprofiel_Page/BepaalJeKennisprofiel_Page.js');
    var AcepteerDeVoorwaardenPage = require('./Page/AcepteerDeVoorwaarden_Page/AcepteerDeVoorwaarden_Page.js');
    var BepaalJeInlegPage = require('./Page/BepaalJeInleg_Page/BepaalJeInleg_Page.js');

    var date = new Date().getTime() / 1000;
    var uniqueIdentifier = date.toString();
.
    afterEach(function () {
        browser.driver.sleep(1000);
    });

    it('Should go to the login page', function () {
        browser.ignoreSynchronization = true;

        LoginPage.goToPage();

        browser.ignoreSynchronization = false;
    });

    it('Should hide the cookie bar', function () {

        LoginPage.hideCookieBar();

    });

    it('Should set username', function () {

        LoginPage.setUsername('mseykov');

    });

    it('Should set password', function () {

        LoginPage.setPassword('Welkom2015');

    });

    it('Should click login', function () {

        LoginPage.clickLogin();

    });

    it('Should click OK on the pop up', function () {

        LoginPage.closePopUp();

    });

});
```

The associated page file:

```
var LoginPage = function () {

    this.goToPage = function () {
        browser.get('https://k2-vat.virtual-affairs.nl');
    };

    this.hideCookieBar = function () {
        element(by.css('.cookies-bar-text>.btn-clean')).click();
    };

    this.setUsername = function (value) {
        element(by.id('safeName')).sendKeys(value);
    };

    this.setPassword = function (value) {
        element(by.id('Password')).sendKeys(value);
    };

    this.clickLogin = function () {
        element(by.css('button[type="submit"]')).click();
    };

    this.closePopUp = function () {
        element(by.css('.btn.btn-primary.btn-xs-block')).click();
    };
};
module.exports = new LoginPage();
```

And the config file:

```
var HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');

var reporter = new HtmlScreenshotReporter({
    dest: 'target/screenshots_chrome',
    filename: 'my-report.html'
});

exports.config = {
    framework: 'jasmine2',
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['spec.js'],
    capabilities: {
        browserName: 'chrome'
    },

    beforeLaunch: function () {
        return new Promise(function (resolve) {
            reporter.beforeLaunch(resolve);
        });
    },

    //multiCapabilities: [{
    //    'browserName': 'chrome'
    //}, {
    //    'browserName': 'firefox'
    //}],
    //capabilities: {
    //    browserName: 'phantomjs',
    //    'phantomjs.binary.path': require('phantomjs').path
    //},
    onPrepare: function () {
        jasmine.getEnv().addReporter(reporter);
        browser.driver.manage().window().maximize();

        //browser.manage().timeouts().pageLoadTimeout(10000);
        //browser.manage().timeouts().implicitlyWait(10000);
        //allScriptsTimeout: 10000;
        //getPageTimeout: 10000;
    },

    afterLaunch: function (exitCode) {
        return new Promise(function (resolve) {
            reporter.afterLaunch(resolve.bind(this, exitCode));
        });
    }
};
```

Full error message for first step:

```
Failures:
1) 101001 - Internal payment - own portfolio; not recurring - today (current to current account) Should set username
  Message:
    Failed: unknown error: Cannot use 'in' operator to search for 'String' in false
      (Session info: chrome=55.0.2883.87)
      (Driver info: chromedriver=2.26.436362 (5476ec6bf7ccbada1734a0cdec7d570bb042aa30),platform=Windows NT 10.0.10240 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 32 milliseconds
    Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
    System info: host: 'mseykov', ip: '10.10.9.80', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.26.436362 (5476ec6bf7ccbada1734a0cdec7d570bb042aa30), userDataDir=C:\Users\mseykov\AppData\Local\Temp\scoped_dir6988_30004}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=55.0.2883.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
    Session ID: 46d8538fb4a3edb4b58c8201bf8e4710
    *** Element info: {Using=css selector, value=*[id="safeName"]}
  Stack:
    WebDriverError: unknown error: Cannot use 'in' operator to search for 'String' in false
      (Session info: chrome=55.0.2883.87)
      (Driver info: chromedriver=2.26.436362 (5476ec6bf7ccbada1734a0cdec7d570bb042aa30),platform=Windows NT 10.0.10240 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 32 milliseconds
    Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
    System info: host: 'mseykov', ip: '10.10.9.80', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.26.436362 (5476ec6bf7ccbada1734a0cdec7d570bb042aa30), userDataDir=C:\Users\mseykov\AppData\Local\Temp\scoped_dir6988_30004}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=55.0.2883.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
    Session ID: 46d8538fb4a3edb4b58c8201bf8e4710
    *** Element info: {Using=css selector, value=*[id="safeName"]}
        at Object.checkLegacyResponse (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:639:15)
        at parseHttpResponse (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:538:13)
        at client_.send.then.response (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:472:11)
        at ManagedPromise.invokeCallback_ (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379:14)
        at TaskQueue.execute_ (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
        at TaskQueue.executeNext_ (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
        at asyncRun (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2820:25)
        at C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: WebDriver.findElements(By(css selector, *[id="safeName"]))
        at WebDriver.schedule (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:377:17)
        at WebDriver.findElements (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:926:22)
        at C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\built\element.js:173:44
        at ManagedPromise.invokeCallback_ (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379:14)
        at TaskQueue.execute_ (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
        at TaskQueue.executeNext_ (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
        at asyncRun (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2775:27)
        at C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)Error
        at ElementArrayFinder.applyAction_ (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\built\element.js:461:27)
        at ElementArrayFinder._this.(anonymous function) [as sendKeys] (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\built\element.js:103:30)
        at ElementFinder.(anonymous function) [as sendKeys] (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\built\element.js:829:22)
        at LoginPage.setUsername (D:\Knab\KnabInternalPayments\InternalPayments_OwnPortfolio_NotRecurring_Today\Page\Login_Page\Login_Page.ts:8:36)
        at Object.<anonymous> (D:\Knab\KnabInternalPayments\InternalPayments_OwnPortfolio_NotRecurring_Today\spec.ts:25:19)
        at C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:23
        at new ManagedPromise (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1082:7)
        at controlFlowExecute (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:80:18)
        at TaskQueue.execute_ (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
        at TaskQueue.executeNext_ (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    From: Task: Run it("Should set username") in control flow
        at Object.<anonymous> (C:\Users\mseykov\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:79:14)
    From asynchronous test:
    Error
        at Suite.<anonymous> (D:\Knab\KnabInternalPayments\InternalPayments_OwnPortfolio_NotRecurring_Today\spec.ts:23:5)
        at Object.<anonymous> (D:\Knab\KnabInternalPayments\InternalPayments_OwnPortfolio_NotRecurring_Today\spec.ts:1:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
```

**Comment by wswebcreation** [comment]
What's your node version?

**Comment by MihailSeykov** [comment]
My Node version is 7.4.0

**Comment by wswebcreation** [comment]
And if you use NVM to test with different versions of Node, do you still have the problem? 
(Gives a better view on the issue)

**Comment by MihailSeykov** [comment]
Yes, i have tried different versions of Node, but still have the same problem. Sorry for not including that at first. I don't know what more to include to give you a better view of the issue, so please tell me if you need more info on something.

**Comment by cnishina** [comment]
If by.id did not work it would be breaking out CI tests. https://github.com/angular/protractor/blob/master/spec/basic/elements_spec.js#L45

**Comment by mgiambalvo** [comment]
Could you try removing and reinstalling your node_modules directory? Also, seeing the output of `npm ls` for you project would be helpful.

**Comment by MihailSeykov** [comment]
Reinstalling node_modules directory did not help :( . Here is the output of npm ls for the project:

+-- protractor@3.3.0
| +-- adm-zip@0.4.7
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.1.1
| | +-- strip-ansi@3.0.1
| | `-- supports-color@2.0.0
| +-- glob@6.0.4
| | +-- inflight@1.0.6
| | | `-- wrappy@1.0.2
| | +-- inherits@2.0.3
| | +-- minimatch@3.0.3
| | | `-- brace-expansion@1.1.6
| | |   +-- balanced-match@0.4.2
| | |   `-- concat-map@0.0.1
| | +-- once@1.4.0
| | `-- path-is-absolute@1.0.1
| +-- jasmine@2.4.1
| | +-- exit@0.1.2
| | +-- glob@3.2.11
| | | `-- minimatch@0.3.0
| | |   +-- lru-cache@2.7.3
| | |   `-- sigmund@1.0.1
| | `-- jasmine-core@2.4.1
| +-- jasminewd2@0.0.9
| +-- optimist@0.6.1
| | +-- minimist@0.0.10
| | `-- wordwrap@0.0.3
| +-- q@1.4.1
| +-- request@2.67.0
| | +-- aws-sign2@0.6.0
| | +-- bl@1.0.3
| | | `-- readable-stream@2.0.6
| | |   +-- core-util-is@1.0.2
| | |   +-- isarray@1.0.0
| | |   +-- process-nextick-args@1.0.7
| | |   +-- string_decoder@0.10.31
| | |   `-- util-deprecate@1.0.2
| | +-- caseless@0.11.0
| | +-- combined-stream@1.0.5
| | | `-- delayed-stream@1.0.0
| | +-- extend@3.0.0
| | +-- forever-agent@0.6.1
| | +-- form-data@1.0.1
| | | `-- async@2.1.4
| | |   `-- lodash@4.17.4
| | +-- har-validator@2.0.6
| | | +-- commander@2.9.0
| | | | `-- graceful-readlink@1.0.1
| | | +-- is-my-json-valid@2.15.0
| | | | +-- generate-function@2.0.0
| | | | +-- generate-object-property@1.2.0
| | | | | `-- is-property@1.0.2
| | | | +-- jsonpointer@4.0.1
| | | | `-- xtend@4.0.1
| | | `-- pinkie-promise@2.0.1
| | |   `-- pinkie@2.0.4
| | +-- hawk@3.1.3
| | | +-- boom@2.10.1
| | | +-- cryptiles@2.0.5
| | | +-- hoek@2.16.3
| | | `-- sntp@1.0.9
| | +-- http-signature@1.1.1
| | | +-- assert-plus@0.2.0
| | | +-- jsprim@1.3.1
| | | | +-- extsprintf@1.0.2
| | | | +-- json-schema@0.2.3
| | | | `-- verror@1.3.6
| | | `-- sshpk@1.10.2
| | |   +-- asn1@0.2.3
| | |   +-- assert-plus@1.0.0
| | |   +-- bcrypt-pbkdf@1.0.0
| | |   +-- dashdash@1.14.1
| | |   | `-- assert-plus@1.0.0
| | |   +-- ecc-jsbn@0.1.1
| | |   +-- getpass@0.1.6
| | |   | `-- assert-plus@1.0.0
| | |   +-- jodid25519@1.0.2
| | |   +-- jsbn@0.1.0
| | |   `-- tweetnacl@0.14.5
| | +-- is-typedarray@1.0.0
| | +-- isstream@0.1.2
| | +-- json-stringify-safe@5.0.1
| | +-- mime-types@2.1.14
| | | `-- mime-db@1.26.0
| | +-- node-uuid@1.4.7
| | +-- oauth-sign@0.8.2
| | +-- qs@5.2.1
| | +-- stringstream@0.0.5
| | +-- tough-cookie@2.2.2
| | `-- tunnel-agent@0.4.3
| +-- saucelabs@1.0.1
| | `-- https-proxy-agent@1.0.0
| |   +-- agent-base@2.0.1
| |   | `-- semver@5.0.3
| |   `-- debug@2.6.0
| |     `-- ms@0.7.2
| +-- selenium-webdriver@2.52.0
| | +-- adm-zip@0.4.4
| | +-- tmp@0.0.24
| | +-- ws@1.1.1
| | | +-- options@0.0.6
| | | `-- ultron@1.0.2
| | `-- xml2js@0.4.4
| |   +-- sax@0.6.1
| |   `-- xmlbuilder@8.2.2
| `-- source-map-support@0.4.10
|   `-- source-map@0.5.6
`-- protractor-jasmine2-screenshot-reporter@0.3.2
  +-- hat@0.0.3
  +-- lodash@3.10.1
  +-- mkdirp@0.5.1
  | `-- minimist@0.0.8
  +-- rimraf@2.5.4
  | `-- glob@7.1.1
  |   `-- fs.realpath@1.0.0
  +-- string.prototype.startswith@0.2.0
  `-- uuid@2.0.3

**Comment by mgiambalvo** [comment]
According to that `npm ls`, you're using protractor@3.3.0 and selenium-webdriver@2.52.0. You might want to check your package.json and verify you're on the right Protractor version.

Also, I know this is confusing, but Protractor 5 supports the selenium-webdriver 3.0.1 _client_. We still require the 2.53.1 release of the selenium standalone server. Don't know if that relates to your issue, just mentioning it because it might be a problem.

This is sounding less like a Protractor bug and more like an environment/configuration problem. You might have better luck on StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

If you get an answer, please let us know! Thanks!
