### ISSUE TITLE
Problem running Protractor 5.0.0 on FireFox

### ISSUE THREAD

**Issue by IgalOre** [angular/protractor#3993]
Bug report
---

- Node Version: `6.9.1`
- Protractor Version: `5.0.0`
- Angular Version: `1.5.8`
- Browser(s): `Firefox`
- Operating System and Version `os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3'`
- Your protractor configuration file
```
exports.config = {
    // seleniumAddress: 'http://localhost:4444/wd/hub',
    seleniumServerJar: '../../node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.0.1.jar',
    // specs: ['**/*-spec.js'],
    specs: ['specs/sidebar-spec.js', 'specs/back_button-spec.js'],
    baseUrl: 'http://localhost:3000',
    directConnect: false,
    capabilities: {
        browserName: 'internet explorer'
    },
    jvmArgs: ['-Dwebdriver.firefox.bin=c:/Program Files (x86)/Mozilla Firefox/firefox.exe'],
    onPrepare: function() {
        'use strict';
        var reporters = require('jasmine-reporters');
        jasmine.getEnv().addReporter(new reporters.TeamCityReporter());
        var junitReporter = new reporters.JUnitXmlReporter({savePath: 'test/coverage/protractor/', filePrefix: 'UI-TEST-results'});
        jasmine.getEnv().addReporter(junitReporter);
    },
    debug:true
    // nodeDebug: true
};

```
- A relevant example test
- Output from running the test
```
C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets>.\node_modules\.bin\protractor test\protractor\protractor-ci.ff.conf.js --troubleshoot --browser=firefox
[14:25:35] D/launcher - Running with --troubleshoot
[14:25:35] D/launcher - Protractor version: 5.0.0
[14:25:35] D/launcher - Your base url for tests is http://localhost:3000
[14:25:35] I/local - Starting selenium standalone server...
[14:25:35] I/launcher - Running 1 instances of WebDriver
[14:25:37] I/local - Selenium standalone server started at http://172.16.204.148:52495/wd/hub
[14:25:37] E/launcher - Firefox option was set, but is not a FirefoxOption: {}
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'LUWS00474-01', ip: '172.16.204.148', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_74'
Driver info: driver.version: FirefoxDriver
[14:25:37] E/launcher - WebDriverError: Firefox option was set, but is not a FirefoxOption: {}
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'LUWS00474-01', ip: '172.16.204.148', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_74'
Driver info: driver.version: FirefoxDriver
    at WebDriverError (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\selenium-webdriver\lib\error.js:27:5)
    at Object.checkLegacyResponse (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\selenium-webdriver\lib\error.js:505:15)
    at parseHttpResponse (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\selenium-webdriver\lib\http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\selenium-webdriver\lib\webdriver.js:777:24)
    at Function.createSession (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\selenium-webdriver\firefox\index.js:640:55)
    at createDriver (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\selenium-webdriver\index.js:167:33)
    at Builder.build (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\selenium-webdriver\index.js:629:16)
    at Local.getNewDriver (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\protractor\lib\driverProviders\driverProvider.ts:57:29)
    at Runner.createBrowser (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\protractor\lib\runner.ts:187:39)
    at driverprovider_.setupEnv.then (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\protractor\lib\runner.ts:279:27)
    at _fulfilled (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Source\Git\ui-commons\ui_s6_11178\ui-widgets\node_modules\q\q.js:796:13)
[14:25:37] E/launcher - Process exited with error code 199

```
- Steps to reproduce the bug
Re-run protractor tests

I'm upgrading to Protractor 5.0.0, where yesterday with help of @mgiambalvo managed to run tests suite on IE. But on attempt to run same on FF there this error report.

On Internet i had found couple of references : [SeleniumHQ issue](https://github.com/seleniumhq/selenium/issues/3115) and the another one [SeleniumHQ issue](https://github.com/SeleniumHQ/selenium/issues/3055). First had been resolved by upgrading to selenium-webdriver 3.0.0-beta2 where for me version 3.0.1 is used. Second still open.

Any ideas ?

**Comment by mgiambalvo** [comment]
Please see https://github.com/angular/protractor/issues/3823.

The short version is that there's a bug in selenium standalone 3.0.1 that breaks support for Firefox. It's fixed, but hasn't been released. In the meantime, you can use 3.0.0-beta4. Firefox 50 might be flaky, but Firefox 51 (available as beta and due to be released this month) should work better.

**Comment by IgalOre** [comment]
I'm afraid to say @mgiambalvo that proposed solution to use selenium standalone 3.0.0-beta4 seems not be working :(
I set selenium standalone to 3.0.0-beta4 this seems to produce different kind of error:
```
[16:24:27] D/launcher - Running with --troubleshoot
[16:24:27] D/launcher - Protractor version: 5.0.0
[16:24:27] D/launcher - Your base url for tests is http://localhost:3000
[16:24:27] I/local - Starting selenium standalone server...
[16:24:27] I/launcher - Running 1 instances of WebDriver
[16:24:27] I/local - Selenium standalone server started at http://172.16.105.37:62875/wd/hub
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://172.16.105.37:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://172.16.105.37:3001
 --------------------------------------
[BS] Serving files from: demo
[16:24:39] E/launcher - Unable to create new remote session. desired capabilities = Capabilities [{count=1, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@44fa6589, browserName=firefox, moz:firefoxOptions={}}], required capabilities = Capabilities [{}]
Build info: version: '3.0.0-beta4', revision: '3169782', time: '2016-09-29 10:29:23 -0700'
System info: host: 'DevRegAppW01', ip: '172.16.105.37', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_77'
Driver info: driver.version: FirefoxDriver
[16:24:39] E/launcher - SessionNotCreatedError: Unable to create new remote session. desired capabilities = Capabilities [{count=1, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@44fa6589, browserName=firefox, moz:firefoxOptions={}}], required capabilities = Capabilities [{}]
Build info: version: '3.0.0-beta4', revision: '3169782', time: '2016-09-29 10:29:23 -0700'
System info: host: 'DevRegAppW01', ip: '172.16.105.37', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_77'
Driver info: driver.version: FirefoxDriver
    at WebDriverError (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:5)
    at SessionNotCreatedError (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:214:5)
    at Object.checkLegacyResponse (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:505:15)
    at parseHttpResponse (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:777:24)
    at Function.createSession (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js:640:55)
    at createDriver (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\index.js:167:33)
    at Builder.build (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\node_modules\selenium-webdriver\index.js:629:16)
    at Local.getNewDriver (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\lib\driverProviders\driverProvider.ts:57:29)
    at Runner.createBrowser (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\lib\runner.ts:187:39)
    at driverprovider_.setupEnv.then (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\protractor\lib\runner.ts:279:27)
    at _fulfilled (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\TeamCity\BuildAgent\work\659c5b7cede0b665\ui-widgets\node_modules\q\q.js:796:13)
[16:24:39] E/launcher - Process exited with error code 199
[16:24:39] Protractor run failed with code : 199
[16:24:39] Finished 'protractor-run' after 13 s
[16:24:39] Starting 'stop:demoServerForProtractor'...
[16:24:39] Finished 'stop:demoServerForProtractor' after 1.21 ms
```

On test running machine there FF 37.0.1.

If i set legacy flag ",marionette: false" in capabilities it produces even other error, something related that legacy driver can't be used.

New configuration file for Protractor are:
```
exports.config = {
    // seleniumAddress: 'http://localhost:4444/wd/hub',
    seleniumServerJar: '../../node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.0.0-beta4.jar',
    specs: ['**/*-spec.js'],
    // specs: ['specs/sidebar-spec.js', 'specs/back_button-spec.js'],
    baseUrl: 'http://localhost:3000',
    directConnect: false,
    capabilities: {
      browserName: 'firefox'
    },
    // jvmArgs: ['-Dwebdriver.firefox.bin=c:/Program Files (x86)/Mozilla Firefox/firefox.exe'],
    jvmArgs: ['-Dwebdriver.firefox.bin=c:/Program Files (x86)/Mozilla Firefox/firefox.exe',
        '-Dwebdriver.gecko.driver=./node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.13.0.exe'],
    onPrepare: function() {
        'use strict';
        var reporters = require('jasmine-reporters');
        jasmine.getEnv().addReporter(new reporters.TeamCityReporter());
        var junitReporter = new reporters.JUnitXmlReporter({savePath: 'test/coverage/protractor/', filePrefix: 'UI-TEST-results'});
        jasmine.getEnv().addReporter(junitReporter);
    },
    debug:true
    // nodeDebug: true
};
```
