### ISSUE TITLE
TypeScript users often have multiple `protractor` installations floating around

### ISSUE THREAD

**Issue by sjelin** [angular/protractor#4077]
We encourage typescript users to do something like:

```ts
import {browser, promise} from 'protractor';

...

browser.wait(promise.when(something));
```

The problem here is that often users will invoke their tests from a globally installed `protractor` package, but they'll import from a locally installed `protractor` package.  Because of the way we use [`registerGlobal` in index.ts](https://github.com/angular/protractor/blob/5.1.1/lib/index.ts#L40), we'll get `browser` from the global `protractor` package, but `promise` will still come from the local package.

This could be a problem in many ways.  For `promise` specifically, this is a problem because you many end up with inconsistent settings for `USE_PROMISE_MANAGER`.  This is alleviated slightly by <<<INSERT_PR_HERE>>>, but could still be a problem.

### Solution 1: Export more properties by reference

Export more of [the properties on the `Ptor` class](https://github.com/angular/protractor/blob/5.1.1/lib/ptor.ts#L37-L53) using `registerGlobal`.  This solves the problem of multiple instances in some cases, though it could make the problem even worse if:
* The global and local installations are on different versions
* The file importing `protractor` was never invoked by Protractor (and thus the global `protractor` instance has never been set)
* Properties other than the ones on the `Ptor` class have issues similar to the ones `promise` has.
* Someone in some other way makes the (totally reasonable) assumption that when they require/import Protractor, they're getting instances from their local installation, not the global installation.

### Solution 2: Breaking change - only export types from `index.ts`

We can use syntax like [`export type Runner = Runner`](https://github.com/angular/protractor/blob/master/lib/index.ts#L18) to export types without exporting the actual classes.  If we did this for everything, our compiled `index.js` would be empty but our compiled `index.d.ts` would still have the types people need.

This would force users to do a lot of
```ts
declare let protractor: Ptor; // Set globally by Protractor's runner
declare let browser: ProtractorBrowser; // Set globally by Protractor's runner
...
```
We could simplify this for our users by using [`declare global`](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html), though we'd really only be able to declare `protractor` since we don't know if someone is using the [`noGlobals`](https://github.com/angular/protractor/blob/5.1.1/lib/config.ts#L189) option until runtime.

Alternately, we could continue to export by reference things like `browser`, but stop exporting everything else (except types).

### Solution 3: Breaking change - throw error if multiple installations are detected

This would force users to `import` from the same Protractor installation they use to run their tests.  It may be difficult for users to point `import` to the Protractor installation which runs their tests, however.

### Solution 4: Magically make importing `protractor` redirect to the invoking `protractor` installation

In `runner.ts` we could do something like:
```ts
global.PROTRACTOR_EXPORTS_ = require('./index');
```
and then at the top of `index.ts` we could do something like:
```ts
if (global.PROTRACTOR_EXPORTS_) {
  module.exports = global.PROTRACTOR_EXPORTS_;
  return;
}
```

This could go wrong in a number of ways, and would be very difficult for our users to debug.

### Solution 5: Detect local installations and use those

Back in `cli.ts`, use `npm ls` to detect if there is a local Protractor installation.  If there is, use `npm run` to redirect to that installation.  There are a huge number of ways that this could go wrong, and I highly doubt this is the correct solution.

### Solution 6: Magic????

I'm not totally satisfied with any of the solutions thus far.  Though Solution 2 is probably least likely to cause unexpected bugs.

**Comment by ozkar007** [comment]
already did some searching, i'm spining my wheels here, cant find a solution for a similar error in my environment. when running protractor protractor.config.ts getting "syntaxerror" for the import in the protractor.config.ts file

e2e\configs>protractor protractor.config.ts
[14:40:52] E/configParser - Error code: 105
[14:40:52] E/configParser - Error message: failed loading configuration file protractor.config.ts
[14:40:52] E/configParser - C:\...\protractor\e2e\configs\protractor.config.ts:4
import { ProtractorBrowser, Config } from 'protractor';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at ConfigParser.addFileConfig (C:\Users\.....AppData\Roaming\npm\node_modules\protractor\built\configParser.js:123:26)
    at Object.initFn [as init] (C:\Users\...\AppData\Roaming\npm\node_modules\protractor\built\launcher.js:92:22)

**Comment by ozkar007** [comment]
fallowed the instructions from here https://github.com/angular/protractor/tree/master/exampleTypescript but cant getting to work in my environment, any help will be awesome

**Comment by wswebcreation** [comment]
@ozkar007

Just a check, which version of node are you using? 6.9 is the min.

**Comment by ozkar007** [comment]
by running node --version, got v6.10.0

**Comment by wswebcreation** [comment]
Ok, and you use the example project?

**Comment by ozkar007** [comment]
yes fallowing the protractor/exampleTypescript/ example, looking at the package.json why does reference the conf.js javascript file and not the typescript conf.ts file. Do we still need the conf.js file even if we plan to work on typescript.

{
  "name": "example-typescript",
  "version": "1.0.0",
  "description": "a typescript example",
  "author": "",
  "license": "MIT",
  "scripts": {
    "tsc": "tsc",
    "pretest": "npm run tsc",
    "test": "protractor tmp/conf.js"
  },
  "dependencies": {
    "@types/jasmine": "2.5.41",
    "@types/jasminewd2": "^2.0.0",
    "jasmine": "^2.4.1",
    "protractor": "file:../",
    "typescript": "~2.0.0"
  },
  "devDependencies": {
    "@types/jasminewd2": "^2.0.0"
  }
}

**Comment by ozkar007** [comment]
also tried running the example straight from node_modules\protractor\exampleTypescript>protractor conf.ts

still it does not like the import {Config} from 'protractor'; statement

**Comment by AkashSidhwani7** [comment]
After compiling typescript files to js files via command "npm runt tsc" (follow [this](https://github.com/angular/protractor/tree/master/exampleTypescript)) , a tmp folder is created in the project with all the js files. We need to run protractor.conf.js from that tmp folder. On running it, everything is working fine.

**Comment by sameeksha-sahib** [comment]
After compiling typescript files to js files via command "npm runt tsc" (follow [this](https://github.com/angular/protractor/tree/master/exampleTypescript)) , a tmp folder is created in the project with all the js files. We need to run protractor.conf.js from that tmp folder. On running it, everything is working fine.
