### ISSUE TITLE
Error Code 199 Protractor

### ISSUE THREAD

**Issue by UJURA** [angular/protractor#4106]
Below is my the error i see. I am new to protractor and i keep getting error 199. I am using Protractor version 5.1.1

PS C:\Users\a6mh1zz\Documents\visual studio 2015\projects\nodejsconsoleapp13\nodejsconsoleapp13> protractor conf.js
[14:49:24] I/launcher - Running 1 instances of WebDriver
[14:49:24] I/hosted - Using the selenium server at http://localhost:4444/wd/hud
[14:49:24] E/launcher - Unable to parse new session response: <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" media="all"/>
  <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" />
  <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script>
  <script src="/assets/displayhelpservlet.js" type="text/javascript"></script>
  <script type="text/javascript">
    var json = Object.freeze('{"version":"3.1.0","type":"Standalone","consoleLink":"/wd/hub"}');
  </script>
</head>
<body>

<div id="content">
  <div id="help-heading">
    <h1><span id="logo"></span></h1>
    <h2>Selenium <span class="se-type"></span>&nbsp;v.<span class="se-version"></span></h2>
  </div>

  <div id="content-body">
    <p>
      Whoops! The URL specified routes to this help page.
    </p>
    <p>
      For more information about Selenium <span class="se-type"></span> please see the
      <a class="se-docs">docs</a> and/or visit the <a class="se-wiki">wiki</a>.
      <span id="console-item">
        Or perhaps you are looking for the Selenium <span class="se-type"></span> <a class="se-console">console</a>.
      </span>
    </p>
    <p>
      Happy Testing!
    </p>
  </div>

  <div>
    <footer id="help-footer">
      Selenium is made possible through the efforts of our open source community, contributions from
      these <a href="https://github.com/SeleniumHQ/selenium/blob/master/AUTHORS">people</a>, and our
      <a href="http://www.seleniumhq.org/sponsors/">sponsors</a>.
   </footer>
  </div>
 </div>

</body>
</html>
[14:49:24] E/launcher - WebDriverError: Unable to parse new session response: <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" media="all"/>
  <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" />
  <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script>
  <script src="/assets/displayhelpservlet.js" type="text/javascript"></script>
  <script type="text/javascript">
    var json = Object.freeze('{"version":"3.1.0","type":"Standalone","consoleLink":"/wd/hub"}');
  </script>
</head>
<body>

<div id="content">
  <div id="help-heading">
    <h1><span id="logo"></span></h1>
    <h2>Selenium <span class="se-type"></span>&nbsp;v.<span class="se-version"></span></h2>
  </div>

  <div id="content-body">
    <p>
      Whoops! The URL specified routes to this help page.
    </p>
    <p>
      For more information about Selenium <span class="se-type"></span> please see the
      <a class="se-docs">docs</a> and/or visit the <a class="se-wiki">wiki</a>.
      <span id="console-item">
        Or perhaps you are looking for the Selenium <span class="se-type"></span> <a class="se-console">console</a>.
      </span>
    </p>
    <p>
      Happy Testing!
    </p>
  </div>

  <div>
    <footer id="help-footer">
      Selenium is made possible through the efforts of our open source community, contributions from
      these <a href="https://github.com/SeleniumHQ/selenium/blob/master/AUTHORS">people</a>, and our
      <a href="http://www.seleniumhq.org/sponsors/">sponsors</a>.
   </footer>
  </div>
 </div>

</body>
</html>
    at WebDriverError (C:\Users\a6mh1zz\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\
error.js:27:5)
    at doSend.then.response (C:\Users\a6mh1zz\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdrive
r\lib\http.js:445:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\a6mh1zz\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdri
ver\lib\webdriver.js:777:24)
    at Function.createSession (C:\Users\a6mh1zz\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdri
ver\chrome.js:709:29)
    at createDriver (C:\Users\a6mh1zz\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.
js:167:33)
    at Builder.build (C:\Users\a6mh1zz\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index
.js:623:16)
    at Hosted.getNewDriver (C:\Users\a6mh1zz\AppData\Roaming\npm\node_modules\protractor\lib\driverProviders\driverProvi
der.ts:60:29)
    at Runner.createBrowser (C:\Users\a6mh1zz\AppData\Roaming\npm\node_modules\protractor\lib\runner.ts:225:39)
    at q.then.then (C:\Users\a6mh1zz\AppData\Roaming\npm\node_modules\protractor\lib\runner.ts:391:27)
    at _fulfilled (C:\Users\a6mh1zz\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\a6mh1zz\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:3
0)
    at Promise.promise.promiseDispatch (C:\Users\a6mh1zz\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js
:796:13)
[14:49:24] E/launcher - Process exited with error code 199

Here is my conf.js file
//conf.js
exports.config = {
    framework: 'jasmine',
    seleniumAddress: 'http://localhost:4444/wd/hud',
    specs: ['spec.js']

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

Also, please properly format your test output and configuration file when posting on StackOverflow.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
