### ISSUE TITLE
Cannot read property 'findElement' of undefined

### ISSUE THREAD

**Issue by samsul-kabir** [angular/protractor#4116]
Hi there!

I am trying to read attribute for an element but it keeps returning an error. Not sure why. Any idea?

test script:
```
browser.driver.findElements(by.css('.row')).then(function(elem){
            elem[1].findElements(by.css('.col-4.col-12-sm')).then(function (elems) {
                console.log(elems.length);
                for(i=0; i<=elems.length; i++){
                    elems[i].findElement(by.tagName('a')).getAttribute("data-post-id").then(function(attr){
                        console.log(attr);
                    });
                }
            });
        });
```

error:

```
Failed: Cannot read property 'findElement' of undefined
  Stack:
    TypeError: Cannot read property 'findElement' of undefined
        at /Users/skabir/Documents/protractor-room5/test/homepage.js:17:29
        at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: Run it("displaying first element") in control flow
        at Object.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:86:14)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/skabir/Documents/protractor-room5/test/homepage.js:12:5)
        at Object.<anonymous> (/Users/skabir/Documents/protractor-room5/test/homepage.js:1:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
```

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
