### ISSUE TITLE
Unable to run my protractor test on android devices using appium

### ISSUE THREAD

**Issue by samsul-kabir** [angular/protractor#4127]
Hi there!

I am trying to run my protractor test on android devices using appium. It pops up the chrome browser on the devices and quit. Not sure what is the reason behind this. Any idea?

Configuration files:
```
exports.config = {
    seleniumAddress: 'http://localhost:4723/wd/hub',
    capabilities: {
        browserName: 'chrome',
        platformName: 'Android',
        platformVersion: '7.0',
        deviceName: 'ce10160a4445823514',
    },
onPrepare: function(){
        browser.ignoreSynchronization = true;
    },
specs: ['../test/nav.js'],
};

baseUrl = "http://www.thetestroom.com/";
sleep = 10*1000;
```

Test script:
```
describe('Load homepage', function () {
    it('Loading homepage', function () {
        browser.driver.get(baseUrl);
        browser.driver.sleep(sleep);
    });
});
```

Log:
```
09:43:56] I/hosted - Using the selenium server at http://localhost:4723/wd/hub
[09:43:56] I/launcher - Running 1 instances of WebDriver
[09:43:57] E/launcher - An unknown server-side error occurred while processing the command. Original error: Cannot read property 'forceStop' of undefined
[09:43:57] E/launcher - WebDriverError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'forceStop' of undefined
    at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:709:29)
    at createDriver (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:623:16)
    at Hosted.getNewDriver (/usr/local/lib/node_modules/protractor/lib/driverProviders/driverProvider.ts:57:29)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/lib/runner.ts:187:39)
    at driverprovider_.setupEnv.then (/usr/local/lib/node_modules/protractor/lib/runner.ts:279:27)
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
[09:43:57] E/launcher - Process exited with error code 199
trv2457:conf skabir$ protractor conf.js
[09:46:18] I/hosted - Using the selenium server at http://localhost:4723/wd/hub
[09:46:18] I/launcher - Running 1 instances of WebDriver
[09:46:31] E/runner - Unable to start a WebDriver session.
[09:46:33] E/launcher - Error: WebDriverError: no such session
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.12.3 x86_64)
    at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.manage().timeouts().setScriptTimeout(11000)
    at thenableWebDriverProxy.schedule (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at Timeouts._scheduleCommand (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:1500:25)
    at Timeouts.setScriptTimeout (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:1483:17)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/lib/runner.ts:215:49)
    at driverprovider_.setupEnv.then (/usr/local/lib/node_modules/protractor/lib/runner.ts:279:27)
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13)
[09:46:33] E/launcher - Process exited with error code 100

```

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
