### ISSUE TITLE
firefoxProfile / extension is not being loaded (without directConnect)

### ISSUE THREAD

**Issue by kevinmuller** [angular/protractor#4130]
Bug report
---

- Node Version: `7.6.0`
- Protractor Version: `5.1.1`
- Angular Version: `not applicable`
- Browser(s): `firefox 47.0.1` (note that firefox is loading the profile properly with other testing frameworks such as webdriverio)
- Operating System and Version `Debian, but not relevant since it's working fine in the same environment with other frameworks`
- Your protractor configuration file: https://github.com/mailvelope/mailvelope-selenium/blob/master/protractor/config/config-firefox.js
- A relevant example test: https://github.com/mailvelope/mailvelope-selenium/blob/master/protractor/tests/base/test.js

- Output from running the test:
Firefox starts and execute the test, but the xpi extension provided is not loaded. Also, it seems that the profile given with the prefs is not loaded either, since doing a about:config and checking the preferences doesn't show the preferences given (browser.startup.homepage).
It is not a firefox issue since I can load the extension without a problem when using other testing frameworks. 

- Steps to reproduce the bug
You can download this code: https://github.com/mailvelope/mailvelope-selenium
Then run it (after a npm install). You will notice that the firefox "mailvelope" extension is not loaded since the mailvelope icon doesn't appear in the toolbar.
To run the test: ./node_modules/protractor/bin/protractor ./protractor/config/config-firefox.js 

Thanks!

**Comment by NickTomlin** [comment]
I can reproduce this using the example repo you shared as well. I wonder if this has something to do with the firefox profile configuration. As I understand it WebdriverIO is using a similar approach to load the plugin. Have you tried a more recent version of Firefox?

**Comment by tamvo94** [comment]
Hi @NickTomlin 
I have the same issue:
https://github.com/SeleniumHQ/selenium/issues/3500
Can you quick investigate? 
Thanks.

**Comment by tamvo94** [comment]
Hi @kevinmuller,
I run your project without  directConnect: true, it show error:
```
Using the selenium server at http://localhost:4444/wd/hub
[13:07:13] E/launcher - Error code: 135
[13:07:13] E/launcher - Error message: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
[13:07:13] E/launcher - Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
    at ClientRequest.<anonymous> (D:\SAMPLE\mailvelope-selenium\node_modules\selenium-webdriver\http\index.js:238:15)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From: Task: WebDriver.createSession()
```

**Comment by tathanhphu** [comment]
Hi @NickTomlin,

It does not work on Firefox 52, protractor 5.1.1
Firefox browser is launched but extensions of predefined profile are not loaded (even method addExtension is called)
BTW: I wonder in https://github.com/mailvelope/mailvelope-selenium/blob/master/protractor/config/firefox-helper.js method getFirefoxProfile() is not called anywhere, could you please give some advice?

Thanks.
