### ISSUE TITLE
Cannot mousemove on canvas element in Firefox 51

### ISSUE THREAD

**Issue by tamvo94** [angular/protractor#4136]
I have a code to mouse move on canvas:

```
    let canvas = element(by.id(`canvas`)).getWebElement();
    return browser.actions()
      .mouseMove(canvas, {x: 100, y: 100})
      .mouseDown()
      .mouseMove(canvas,  {x: 200, y: 350})
      .mouseUp()
      .perform();

```
But have issue: 

```
Failed: POST /session/3bfcfe08-4464-4ac4-8dfb-bb7bd87e955e/moveto did not match a known command
      at WebDriverError (D:\e2e\node_modules\selenium-webdriver\lib\error.js:27:5)
      at UnknownCommandError (D:\e2e\node_modules\selenium-webdriver\lib\error.js:296:5)
      at Object.throwDecodedError (D:\e2e\node_modules\selenium-webdriver\lib\error.js:477:11)
      at parseHttpResponse (D:\e2e\node_modules\selenium-webdriver\lib\http.js:499:15)
      at doSend.then.response (D:\e2e\node_modules\selenium-webdriver\lib\http.js:440:13)
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: mouseMove
      at Driver.schedule (D:\e2e\node_modules\selenium-webdriver\lib\webdriver.js:816:17)
      at actions.map.action (D:\e2e\node_modules\selenium-webdriver\lib\actions.js:124:23)
      at Array.map (native)
      at D:\e2e\node_modules\selenium-webdriver\lib\actions.js:123:29
      at TaskQueue.execute_ (D:\e2e\node_modules\selenium-webdriver\lib\promise.js:2970:14)
      at TaskQueue.executeNext_ (D:\e2e\node_modules\selenium-webdriver\lib\promise.js:2953:27)
      at asyncRun (D:\e2e\node_modules\selenium-webdriver\lib\promise.js:2813:27)
      at D:\e2e\node_modules\selenium-webdriver\lib\promise.js:676:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: ActionSequence.perform
      at ActionSequence.perform (D:\e2e\node_modules\selenium-webdriver\lib\actions.js:122:33)
```
Bug report
---

- Node Version: `v6.9.5`
- Protractor Version: `5.1.1`
- Browser(s): `Firefox 51`
- Operating System and Version `Windown 10 64 bit`
- Your protractor configuration file
```
  browserName: 'firefox',
    marionette: true,
directConnect: true,
```
The same issue with safari 10.

**Comment by Xotabu4** [comment]
Not quite sure that driver devs finished this.

See 	/session/{sessionId}/actions in this table
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status

`moveto` is specified in w3c draft, but seems like not yet works. It is partially complete.

Looks like 3rd party bug with gekkodriver

**Comment by NickTomlin** [comment]
Thanks for tracking that down @Xotabu4 I think you are right. 

@tamvo94 this sounds like a great fit for a gecko driver issue. Would you be up for opening one in the [geckodriver queue](https://github.com/mozilla/geckodriver/issues)?

**Comment by tamvo94** [comment]
Thank @Xotabu4 and @NickTomlin
I posted this issue to  [geckodriver queue issue](https://github.com/mozilla/geckodriver/issues/516)

**Comment by NickTomlin** [comment]
Hmm, seems like this is more of an issue with selenium itself. If you are up for it, could you open an issue there? 

I think I'm going to go ahead and close this for now since there's nothing we can do. Thanks!
