### ISSUE TITLE
IEDriver not starting from Selenium Server when specifying webdriver.ie.driver via seleniumArgs

### ISSUE THREAD

**Issue by hudson-t** [angular/protractor#4137]
Hi,

There seems to be an issue with running Protractor Tests in IE11 when specifying the seleniumServerJar, seleniumPort & the IE webdriver location via seleniumArgs.

Here is what I have in my Protractor conf file:
```
seleniumServerJar: './node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.2.0.jar',
seleniumPort: 4444,
seleniumArgs: ["-Dwebdriver.ie.driver=C:/Projects/MyProject/ProtractorTests/node_modules/protractor/node_modules/webdriver-manager/selenium/IEDriverServer3.2.0.exe"],
capabilities: {
        browserName: 'internet explorer',
        platform: 'ANY',
        version: '11'
    },
```

**What I have done**
- webdriver-manager update --ie
- checked the path/filename passed in seleniumArgs
- ran the above settings with chrome and firefox specified in capabilities (minus seleniumArgs) and everything worked
- ran the above settings with chrome and firefox specified in capabilities (with seleniumArgs)  and it didn't work

**Problem**
When I run the tests I get the following error message:
```
[11:12:37] E/launcher - Error: Error: Server terminated early with status 1
    at __dirname.start.opt_timeoutMs.address_.Promise.resolve.then.resolveCommandLineFlags.then.earlyTermination.catch.e (c:\Projects\MyProject\ProtractorTests\node_modules\selenium-webdriver\remote\index.js:252:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[11:12:37] E/launcher - Process exited with error code 100
```
The issue seems to be with the argument, but I cannot understand what the problem is, others seem to have had success with this.

**What I am trying to achieve**
Simplicity for my team members running IE tests locally. I don't want to specify an environment PATH as all of my team will checkout to the same directory below C:/ so it would just be another setup step. Ideally I would have liked the path passed in seleniumArgs to be relative and not absolute but that is a nice to have until I get this working...

...any ideas?

-------------------------------------------------------
- Node Version: 7.5.0
- Protractor Version: 5.1.1
- Browser(s): Internet Explorere 11
- Operating System and Version Windows 7 (64bit)

**Comment by hudson-t** [comment]
Just added the below environment path and removed the argument specifying the path from seleniumArgs:
`C:\Projects\MyProject\ProtractorTests\node_modules\protractor\node_modules\webdriver-manager\selenium\IEDriverServer3.2.0.exe`

Same error as I heav already posted...

If I remove the path and run I get the error:
```
 [11:49:29] E/launcher - The path to the driver executable must be set by the webdriver.ie.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver. The latest version can be downloaded from http://selenium-release.storage.googleapis.com/index.html
[11:49:29] E/launcher - WebDriverError: The path to the driver executable must be set by the webdriver.ie.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver. The latest version can be downloaded from http://selenium-release.storage.googleapis.com/index.html
    at Object.checkLegacyResponse (c:\Projects\Unity\ProtractorTests\node_modules\selenium-webdriver\lib\error.js:505:15)
    at parseHttpResponse (c:\Projects\Unity\ProtractorTests\node_modules\selenium-webdriver\lib\http.js:509:13)
    at __dirname.execute.request.then.doSend.then.response (c:\Projects\Unity\ProtractorTests\node_modules\selenium-webdriver\lib\http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (c:\Projects\Unity\ProtractorTests\node_modules\selenium-webdriver\lib\webdriver.js:777:24)
    at createDriver (c:\Projects\Unity\ProtractorTests\node_modules\selenium-webdriver\index.js:167:33)
    at Builder.build (c:\Projects\Unity\ProtractorTests\node_modules\selenium-webdriver\index.js:632:14)
    at Local.getNewDriver (c:\Projects\Unity\ProtractorTests\node_modules\protractor\built\driverProviders\driverProvider.js:52:33)
    at Runner.createBrowser (c:\Projects\Unity\ProtractorTests\node_modules\protractor\built\runner.js:194:43)
    at events_1.EventEmitter.run.q.then.then (c:\Projects\Unity\ProtractorTests\node_modules\protractor\built\runner.js:338:29)
    at _fulfilled (c:\Projects\Unity\ProtractorTests\node_modules\q\q.js:834:54)
    at Promise.then.Q.nextTick.self.promiseDispatch.done (c:\Projects\Unity\ProtractorTests\node_modules\q\q.js:863:30)
    at Promise.__dirname.Promise.promise.promiseDispatch (c:\Projects\Unity\ProtractorTests\node_modules\q\q.js:796:13)
    at c:\Projects\Unity\ProtractorTests\node_modules\q\q.js:604:44
[11:49:29] E/launcher - Process exited with error code 199
```
So the real problem appears not to be with the argument (which clearly works as the driver seems to be getting picked up in both cases) but instead with just running the Protractor test via Selenium Standalone Server/IEDriver?

**Comment by NickTomlin** [comment]
This is a tricky one, and our documentation could be better about the support here. What you actually want is to supply `jvmArgs` to the [`localSeleniumStandAloneOpts` property of your config](https://github.com/angular/protractor/blob/master/lib/config.ts#L48-L67)

```
  localSeleniumStandaloneOpts: {
    jvmArgs: [
      '-Dwebdriver.ie.driver=<path-to-ie>'
    ]
  },

```

I'm going to go ahead and close this issue. Please direct further usage/debugging questions to StackOverflow. Thanks!

**Comment by hudson-t** [comment]
@NickTomlin - thanks for your help! Yeah, I think the documentation needs updating. I didn't consider for a second that I was passing the argument to the wrong place...

This has got me to the next stage now. Still not working but I am confident it's my local config and not Protractor! Off to StackOverflow I go.
