### ISSUE TITLE
Protractor is not running and stops with UnknownError: Session not started or terminated -- Can anyone help us?

### ISSUE THREAD

**Issue by varunbadri** [angular/protractor#4153]
[31m TC-73. Verify deploying package to multiple AD groups - fail [0m
 [31m TC-74. Verify Re deploying packages to the same multiple AD groups - fail [0m
 [31m TC-75. Verify the tenant admin can able to cancel the Re deployed Multiple package jobs - fail [0m
 [31m TC-76. Verify deploying Duplicate package to AD groups - fail [0m
 [31m TC-77. Verify Re deploying duplicate package to the AD groups - fail [0m
 [31m TC-78. Verify the tenant admin can able cancel the Re deploed duplicate package - fail [0m
 [31m TC-79. Verify the whether the Configuration Settings option has a value blank - fail [0m
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
unknown
 [31m TC-80. Verify whether tenant can able to select Blank space/value while in editing the duplicate package - fail [0m

D:\Jenkins\jobs\WT_Master_Jenkins_Email_Report_Regression_Feature\workspace\Source\<Confidential>\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:113
var template = new Error(this.message);
^
UnknownError: Session not started or terminated
at new bot.Error (D:\Jenkins\jobs\WT_Master_Jenkins_Email_Report_Regression_Feature\workspace\Source\<Confidential>\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:113:18)
at Object.bot.response.checkResponse (D:\Jenkins\jobs\WT_Master_Jenkins_Email_Report_Regression_Feature\workspace\<Confidential>\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\response.js:106:9)
at D:\Jenkins\jobs\WT_Master_Jenkins_Email_Report_Regression_Feature\workspace\Source\<Confidential>\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:20
at D:\Jenkins\jobs\WT_Master_Jenkins_Email_Report_Regression_Feature\workspace\Source\<Confidential>\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1582:15
at webdriver.promise.ControlFlow.runInNewFrame_ (D:\Jenkins\jobs\WT_Master_Jenkins_Email_Report_Regression_Feature\workspace\Source\<Confidential>\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1654:20)
at notify (D:\Jenkins\jobs\WT_Master_Jenkins_Email_Report_Regression_Feature\workspace\Source\<Confidential>\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:465:12)

**Comment by brendapessoa** [comment]
I'm also having problems.
Trying to install and have 503 status code.

npm install protractor -g
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! fetch failed https://registry.npmjs.org/@types/selenium-webdriver/-/selenium-webdriver-2.53.42.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/@types/selenium-webdriver/-/selenium-webdriver-2.53.42.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
