### ISSUE TITLE
Error: You may not use a custom command executor with the legacy FirefoxDriver

### ISSUE THREAD

**Issue by aalbul** [angular/protractor#4170]
Hi,

Currently i'm trying to migrate to Selenium 3 / Protractor 5.
I found that GeckoDriver is not acceptable in my case because currently (v0.15.0) it's not supporting actions and i use them pretty often in my tests. For sure, i can get rid of actions usage (somehow....) but i decided to go into another direction and use legacy drivers (by setting marionette: false)

I instantly faced this issue:

> [09:16:32] E/launcher - Error: Error: You may not use a custom command executor with the legacy FirefoxDriver
    at Function.createSession (/Users/aalbul/Documents/projects/xld-ci-explorer/node_modules/protractor/node_modules/selenium-webdriver/firefox/index.js:634:15)
    at createDriver (/Users/aalbul/Documents/projects/xld-ci-explorer/node_modules/protractor/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/Users/aalbul/Documents/projects/xld-ci-explorer/node_modules/protractor/node_modules/selenium-webdriver/index.js:629:16)
    at Local.getNewDriver (/Users/aalbul/Documents/projects/xld-ci-explorer/node_modules/protractor/built/driverProviders/driverProvider.js:52:33)
    at Runner.createBrowser (/Users/aalbul/Documents/projects/xld-ci-explorer/node_modules/protractor/built/runner.js:194:43)
    at q.then.then (/Users/aalbul/Documents/projects/xld-ci-explorer/node_modules/protractor/built/runner.js:338:29)
    at _fulfilled (/Users/aalbul/Documents/projects/xld-ci-explorer/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/aalbul/Documents/projects/xld-ci-explorer/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/aalbul/Documents/projects/xld-ci-explorer/node_modules/q/q.js:796:13)
    at /Users/aalbul/Documents/projects/xld-ci-explorer/node_modules/q/q.js:604:44
    at runSingle (/Users/aalbul/Documents/projects/xld-ci-explorer/node_modules/q/q.js:137:13)
    at flush (/Users/aalbul/Documents/projects/xld-ci-explorer/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

After analysing source code of selenium-webdriver firefox support + driverProvider i found that issue may potentially be caused by **driverProviders/driverProvider.js:25** (getBPUrl). It always returns URL and blocks us from using legacy drivers.

I'm not sure how to fix it and why "localhost" url is returned instead of undefined there, but i'm curious if it's a desired behaviour? Maybe i'm doing something wrong and there is an obvious way of using legacy drivers that i'm not aware of?

Any help appreciated.

**Comment by mgiambalvo** [comment]
getBPUrl() should only be called if you've set the --useBlockingProxy config flag. I'd be surprised if that was it.

What's your protractor config? directConnect won't work with legacy (ie, anything less than 51+) Firefox. Reading through the selenium code, I'm actually not sure how this is supposed to work. It [always creates an HTTP Executor](https://github.com/SeleniumHQ/selenium/blob/d943ee2950e25a2f4a3492058107cfd005d6f7fd/javascript/node/selenium-webdriver/index.js#L619), which causes the Firefox driver to [throw that exception](https://github.com/SeleniumHQ/selenium/blob/d943ee2950e25a2f4a3492058107cfd005d6f7fd/javascript/node/selenium-webdriver/firefox/index.js#L633) if marionette is disabled. I can just delete that bit from the firefox driver, but then when Firefox starts none of the automation runs.

It looks as though `marionette:false` doesn't work in Firefox 52+. If geckodriver 0.15.0 doesn't work for you, you might be stuck on Protractor 4 and pre-Selenium 3.0 for the time being, which would mean you're stuck with Firefox 47.

**Comment by smhc** [comment]
We're also hitting this problem.
Protractor 5.1.1, Firefox 45, marionette: false, directConnect: false, selenium 2.53.1.

Works fine with protractor 4.0.14.

**Comment by heathkit** [comment]
Because of the big change to Firefox's automation with Selenium 3.0, you need to update to the latest Firefox. Here's how it breaks down:

Firefox 47 or lower: use Protractor 4, Selenium 2.53
Firefox 48 - 51: Doesn't work :(
Firefox 52 or higher: use Protractor 5 and Selenium 3.x (whatever the latest is)

There's a known problem with directConnect for Firefox in the latest protractor, but using Selenium 3.x works.

**Comment by heathkit** [comment]
The directConnect issue is here: https://github.com/angular/protractor/issues/4253

**Comment by vinogradoff** [comment]
Still no clear, how the answer solves the problem.

The case is, we want to use Firefox ESR 52, but gecko driver is still under-developed to just stick to it. Legacy FirefoxDriver from Selenium could help. It should support both ESR 45 and ESR 52.

As far as I know, I can start java tests with Selenium 3.4.0 and ESR 52 without gecko.

How do I start it with protractor?
