### ISSUE TITLE
'Failed: Invalid locator' on attempt to chain calls with $('html').$('select')

### ISSUE THREAD

**Issue by Xotabu4** [angular/protractor#4235]
Bug report
---

- Node Version: `7.8`
- Protractor Version: `5.1.1`
- Angular Version: `1.x`
- Browser(s): `chrome`
- Operating System and Version `mac os`
- Your protractor configuration file (TS)
```
import { Config, ExpectedConditions, $ } from 'protractor'

let conf: Config = {
  directConnect: true,
  baseUrl: 'http://www.protractortest.org/testapp/ng1/#/form',
  specs: ['./experiment.js'],
}

exports.config = conf;
```
- A relevant example test
```
import { BaseFragment } from 'protractor-element-extend'
class Select extends BaseFragment {
    constructor(element) {
        super(element);
    }

    selectOption(text) {
        this.element(by.cssContainingText('option', text)).click();
    }

    getSelectedText() {
    	// NOTE: Apparently you can't use the shorthand element locators ($ and $$) with this package.
        return this.$('select').getAttribute('value')
            .then((index) => {
                return this.element(by.css(`option[value="${index}"]`)).getText();
            });
    }
}

describe('Verifying #10 bug with same objects', () => {
    it('with fragment', () => {
        browser.get('')
        let select_frag = new Select($('body'))
        let text = select_frag.getSelectedText()
        text.then(rtext => console.log('$$$$ got text', rtext))
    })
})
```

- Output from running the test
```
Message:
    Failed: Invalid locator
  Stack:
    TypeError: Invalid locator
        at Object.check [as checkedLocator] (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/by.js:267:9)
        at WebElement.findElements (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:1983:18)
        at /Users/cody/Projects/{...}/node_modules/protractor/built/element.js:184:46
        at Array.map (native)
        at /Users/cody/Projects/{...}/node_modules/protractor/built/element.js:181:65
        at ManagedPromise.invokeCallback_ (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    Error
        at ElementArrayFinder.applyAction_ (/Users/cody/Projects/{...}/node_modules/protractor/built/element.js:461:27)
        at ElementArrayFinder._this.(anonymous function) [as getAttribute] (/Users/cody/Projects/{...}/node_modules/protractor/built/element.js:103:30)
        at ElementFinder.(anonymous function) [as getAttribute] (/Users/cody/Projects/{...}/node_modules/protractor/built/element.js:829:22)
        at Select.getSelectedText (/Users/cody/Projects/{...}/e2e_tests/helper.js:50:33)
        at Object.it (/Users/cody/Projects/{...}/e2e_tests/test.spec.js:53:63)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasminewd2/index.js:110:25
        at new ManagedPromise (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    
    From: Task: Run it("Customer should be able to specify the campaign ends at a certain date/time") in control flow
        at Object.<anonymous> (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasminewd2/index.js:64:48
        at ControlFlow.emit (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/events.js:62:21)
        at ControlFlow.shutdown_ (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2565:10)
        at shutdownTask_.MicroTask (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2490:53)
        at MicroTask.asyncRun (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2619:9)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    
    From asynchronous test: 
    Error
        at Suite.describe (/Users/cody/Projects/{...}/e2e_tests/test.spec.js:43:9)
        at Suite.describe (/Users/cody/Projects/{...}/e2e_tests/test.spec.js:36:5)
        at Object.<anonymous> (/Users/cody/Projects/{...}/e2e_tests/test.spec.js:10:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasmine/lib/jasmine.js:87:5
        at Array.forEach (native)
        at Jasmine.loadSpecs (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasmine/lib/jasmine.js:86:18)
        at Jasmine.execute (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/jasmine/lib/jasmine.js:181:8)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/built/frameworks/jasmine.js:132:15
        at Function.promise (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:682:9)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/built/frameworks/jasmine.js:104:14
        at _fulfilled (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:834:54)
        at self.promiseDispatch.done (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:863:30)
        at Promise.promise.promiseDispatch (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:796:13)
        at /Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:556:49
        at runSingle (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:137:13)
        at flush (/Users/cody/.nvm/versions/node/v7.7.4/lib/node_modules/protractor/node_modules/q/q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:73:7)
        at process._tickCallback (internal/process/next_tick.js:104:9)
```

Sup guys! I got a bug report to my lib (https://github.com/Xotabu4/protractor-element-extend/issues/10)

I am able to see this error but not 100% of time. Basically error appears only when trying to chain element search with `this.$('select')` . My lib does not do any black magic - it just recreates ElementFinder with data from parameter - 
```
class BaseFragment extends protractor_1.ElementFinder {
    /**
     * Extend this class, to describe single custom fragment on your page
     *
     * @param {ElementFinder} elementFinder ElementFinder that you want to extend
     */
    constructor(elementFinder) {
        // Basically we are recreating ElementFinder again with same parameters
        super(elementFinder.browser_, elementFinder.elementArrayFinder_);
    }
}
```

This is pretty strange, and i want to ask you if you have any ideas why this might happen?

I will continue digging into code, but i would appreciate any feedback!

**Comment by cnishina** [comment]
So the error you are getting is because the `check` method in selenium-webdriver by.js is hitting the `Invalid Locator` error. https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/by.js#L275

Navigating through the Protractor code:

$ method = https://github.com/angular/protractor/blob/master/lib/element.ts#L1190
$ method is built and tied to the browser. https://github.com/angular/protractor/blob/master/lib/browser.ts#L361

If I were debugging this, I would add logging statements to by.js to figure out what is the instance of the locator parameter and possibly console log the locator.

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this. If it turns out there's an issue with Protractor here we'd welcome a pull request or another issue that links to this and requests a change in protractor? 

@Xotabu4 let me know if that isn't fair and I can re-open. Thanks! 😄
