### ISSUE TITLE
Phantom JS crashing issue

### ISSUE THREAD

**Issue by vikramgit1** [angular/protractor#4251]
Hi - Few scripts for automation using selenium were created for one of the Clients and works with Chrome so far no issues. Now the Client is moving the scripts in CI/CD pipeline and pushes our code to Cloud(AWS) and executes using Phantom JS  . We did add the configuration for Phantom JS but looks like it fails when executing it in suite , below are logs. Can any-one help on the same?  The phantom JS crashes and results shows that few failed and few got skipped . Please suggest

[INFO  - 2017-04-27T13:08:35.247Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
[Utils] [ERROR] [Error] java.lang.NullPointerException
  at utils.DataInputProvider.getUserProperties(DataInputProvider.java:173)
  at wrappers.PolaWrappers.getData(PolaWrappers.java:57)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:55)
  at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
  at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.j

**Comment by NickTomlin** [comment]
Unfortunately, PhantomJS is not officially supported; I will work to make sure that is more explicit in the README/Documentation.

In addition, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
