### ISSUE TITLE
Browser.pause throws error

### ISSUE THREAD

**Issue by shawon-barua** [angular/protractor#4252]
[11:12:59] I/protractor - Encountered browser.pause(), but debugger already attached.
events.js:160
      throw er; // Unhandled 'error' event

This error shows when executing test cases in CI.

Bug report
---

- Node Version: ``6.10.0
- Protractor Version: ``5.1.1
- Angular Version: ``
- Browser(s): ``Chrome
- Operating System and Version ``windows 10
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by heathkit** [comment]
Could you post an example repro? It looks like you have a test case with multiple browser.pause() calls.

**Comment by maciejtreder** [comment]
I don't know if @shawon-barua case is same, but on my end the problem is because of error thrown from `debuggerCommons.js`:

```
[12:53:00] I/protractor -
[12:53:00] I/protractor - Encountered browser.pause(). Attaching debugger...
[12:53:00] I/protractor -
[12:53:00] I/protractor - ------- WebDriver Debugger -------
[12:53:00] I/protractor - Starting WebDriver debugger in a child process. Pause is still beta, please report issues at github.com/angular/protractor
[12:53:00] I/protractor -
[12:53:00] I/protractor - press c to continue to the next webdriver command
[12:53:00] I/protractor - press ^D to detach debugger and resume code execution
[12:53:00] I/protractor -
module.js:487
    throw err;
    ^

Error: Cannot find module '_debugger'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/msobala/rapid-automation/src/test/ts/node_modules/protractor/built/debugger/debuggerCommons.js:1:82)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

```

**Comment by wswebcreation** [comment]
@maciejtreder 

Can you provide an example script / repo so we can check it?

**Comment by maciejtreder** [comment]
@wswebcreation I resolved my issue by downgrading node.js from 8+ to 6+. The problem was probably related to that protractor is calling `node debug` under the hood which is deprecated:

```
(node:75080) [DEP0068] DeprecationWarning: `node debug` is deprecated. Please use `node inspect` instead.
```

**Comment by marandageist** [comment]
Dupe of https://github.com/angular/protractor/issues/4307

**Comment by kshrestha99** [comment]
Any idea why this issue is still not resolved?
