### ISSUE TITLE
Protractor in debug mode is not responsive for commands

### ISSUE THREAD

**Issue by gmunumel** [angular/protractor#4255]
Hi there!

I'm running my simple app and while I run `browser.pause()` the console is not responsive for commands. My setup is following this [guide](https://angular.io/docs/ts/latest/guide/setup.html). Also tried `repl` but doesn't work. 

This is the output: 
```
[1] AppDir: ./
[1]   Suite: QuickStart E2E Tests
[1] [21:17:27] I/protractor -
[1] [21:17:27] I/protractor - Encountered browser.pause(). Attaching debugger...
[1] Starting debugger agent.
[1] (node:35261) DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
[1] Debugger listening on 127.0.0.1:5858
[1] ControlFlow::486
[1] | TaskQueue::176
[1] | | (pending) Task::175<Run beforeEach in control flow>
[1] | | | TaskQueue::179
[1] | | | | (pending) Task::228<Protractor.get(http://localhost:8080/) - test for angular>
[1] | | | | | TaskQueue::411
[1] | | | | | | (pending) Task::413<then>
[1] | | | | | | | TaskQueue::416
[1] | | | | | | | | (blocked) Task::418<then>
[1] | | | | | | Task::415<then>
[1] | | | | Task::230<then>
[1] | | | | Task::232<then>
[1] | | | | Task::234<<anonymous>>
[1] | | | | | Task: <anonymous>
[1] | | | |     at ProtractorBrowser.get (/Users/user/Documents/Code/angular2/quickstart-test/node_modules/protractor/built/browser.js:545:35)
[1] | | | |     at Object.<anonymous> (/Users/user/Documents/Code/angular2/quickstart-test/e2e/app.e2e-spec.ts:8:13)
[1] | | | |     at process._tickCallback (internal/process/next_tick.js:109:7)
[1] | | Task::178<then>
[1] | TaskQueue::428
[1] | | (pending) Task::427<Run it("should display: Hello Angular") in control flow>
[1] | | | TaskQueue::431
[1] | | | | (blocked) Task::437<<anonymous>>
[1] | | | | Task::441<then>
[1] | | | | Task::443<then>
[1] | | | | Task::445<then>
[1] | | | | Task::447<then>
[1] | | | | Task::449<catch>
[1] | | | | Task::451<Protractor.waitForAngular() - Locator: By(css selector, h1)>
[1] | | | | | Task: Protractor.waitForAngular() - Locator: By(css selector, h1)
...
[1] | | | | Task::453<then>
[1] | | | | Task::455<then>
[1] | | | | Task::457<then>
[1] | | | | Task::459<then>
[1] | | | | Task::461<then>
[1] | | | | Task::463<then>
[1] | | | | Task::466<then>
[1] | | | | Task::468<then>
[1] | | Task::430<then>
[1] | TaskQueue::484
[1] | | (pending) Task::477<then>
[1] | | | (active) TaskQueue::485
[1] wd-debug>
list
(doesn't do anything)
```

Bug report
---

- Node Version: `6.0.71`
- Protractor Version: `4.0.14`
- Angular Version: `4.0.3`
- Browser(s): `Google Chrome - Version 58.0.3029.81 (64-bit)`
- Operating System and Version `Mac OS X El Capitan - Version 10.11.6`
- Your protractor configuration file:
[Proctractor config file](https://pastebin.com/PH2Hpdy2)
- A relevant example test
```
import { browser, element, by } from 'protractor';

describe('QuickStart E2E Tests', function () {
  let expectedMsg = 'Hello Angular';
  beforeEach(function () {
    browser.get('');
  });

  it('should display: ' + expectedMsg, function () {
    browser.pause();
    expect(element(by.css('h1')).getText()).toEqual(expectedMsg);
  });
});
```
- Output from running the test
(Above)
- Steps to reproduce the bug
(Above)
- The URL you are running your tests against (if relevant):
...

Thanks for the help. 
Cheers.

**Comment by NickTomlin** [comment]
What URL does this actually resolve to? If you attempt to get an absolute url (e.g. `https://angular.io`) do you experience the same behavior?

**Comment by gmunumel** [comment]
The url is my localhost. I think shouldn´t be important in this case.
