### ISSUE TITLE
Cannot read property 'schedule' of undefined

### ISSUE THREAD

**Issue by tsclaus** [angular/protractor#4306]
Bug report
---

- Node Version: 6.9.5
- Protractor Version: 4.0.14
- Angular Version: 1.6.4
- Browser(s): Chrome Version 58.0.3029.110 (64-bit)
- Operating System and Version Mac OS Sierra 10.12.1
- Your protractor configuration file:
```
// Protractor configuration
// https://github.com/angular/protractor/blob/master/referenceConf.js

'use strict';

exports.config = {
  // The timeout for each script run on the browser. This should be longer
  // than the maximum time your application needs to stabilize between tasks.
  allScriptsTimeout: 120000,

  // A base URL for your application under test. Calls to protractor.get()
  // with relative paths will be prepended with this.
  baseUrl: 'https://localhost:' + (process.env.PORT || '9000'),

  // If true, only chromedriver will be started, not a standalone selenium.
  // Tests for browsers other than chrome will not run.
  // chromeOnly: true,

  // list of files / patterns to load in the browser
  specs: [
    'e2e/**/*.spec.js'
  ],

  // Patterns to exclude.
  exclude: [],

  // ----- Capabilities to be passed to the webdriver instance ----
  //
  // For a full list of available capabilities, see
  // https://code.google.com/p/selenium/wiki/DesiredCapabilities
  // and
  // https://code.google.com/p/selenium/source/browse/javascript/webdriver/capabilities.js
  capabilities: {
    'browserName':     'chrome',
    'chromeOptions':   {
      args:             ['--start-fullscreen']
    }
  },

  // ----- The test framework -----
  //
  // Jasmine and Cucumber are fully supported as a test and assertion framework.
  // Mocha has limited beta support. You will need to include your own
  // assertion framework if working with mocha.
  framework: 'jasmine',

  // ----- Options to be passed to minijasminenode -----
  //
  // See the full list at https://github.com/juliemr/minijasminenode
  jasmineNodeOpts: {
    defaultTimeoutInterval: 60000,
    print:                  function() {}
  },

  // Add a reporter for Protractor to format the output nicely.
  onPrepare:  function() {
    var SpecReporter = require('jasmine-spec-reporter');

    browser.driver.get(browser.baseUrl);

    jasmine.getEnv().addReporter(new SpecReporter({
      displayStacktrace:        'all',
      displaySuccessesSummary:  true
    }));

    if(!protractor.ElementArrayFinder.fromArray) {
      protractor.ElementArrayFinder.fromArray = function (arrayOfElementFinders) {
        var getWebElements = function () {
          var webElements = arrayOfElementFinders.map(function (ef) {
            return ef.getWebElement();
          })
          return protractor.promise.fulfilled(webElements);
        };
        
        return new protractor.ElementArrayFinder(protractor, getWebElements);
      };
    }
  }
};
```

- A relevant example test
```
describe('Filling correctly', function() {
    it('Should result in a valid form', function(done) {
      _.forEach(SignUpPage.formSteps, (formStep) => formStep.fill());

      BrowserHelper.asyncExpect([SignUpPage.form.isValid()], ['toBe'], [true], BrowserHelper.strictDone(done));
    })
  })
```

```
this.formSteps = [
    new FormStep(ElementArrayFinder.fromArray([this.form.firstName, this.form.lastName]), ['Tahsis', 'Claus']),
    new FormStep(this.form.email, 'omninox.*.omninox@spamgourmet.com'),
    new FormStep(ElementArrayFinder.fromArray([this.form.password, this.form.retypePassword]), ['#1password', '#1password']),
    new RadioFormStep([this.form.academicRole.teacher, this.form.academicRole.student], [this.form.academicRole.teacher])
  ]
```

```
function FormStep(inputElementArrayFinder, validInputs, invalidInputs) {
  if(inputElementArrayFinder instanceof ElementFinder) {
    inputElementArrayFinder = [inputElementArrayFinder];
  }

  if(inputElementArrayFinder instanceof Array) {
    inputElementArrayFinder = ElementArrayFinder.fromArray(inputElementArrayFinder);
  }

  if(_.isString(validInputs) || _.isNumber(validInputs)) {
    validInputs = [validInputs]
  }

  this.elements      = inputElementArrayFinder;
  this.validInputs   = validInputs;
  this.invalidInputs = invalidInputs;
}

FormStep.prototype.fill = function(inputKeys, maxLength) {
  if(!inputKeys) {
    inputKeys = this.validInputs;
  }

  if(maxLength) {
    inputKeys = _.slice(inputKeys, 0, maxLength);
  }

  return this.elements.each((inputElementFinder, index) => (index < inputKeys.length ? inputElementFinder.sendKeys : _.noop)(inputKeys[index]));
}

function RadioFormStep(inputElementArrayFinder, validInputs, invalidInputs) {
  if(validInputs instanceof ElementFinder) {
    validInputs = [validInputs];
  }

  if(validInputs instanceof Array) {
    validInputs = ElementArrayFinder.fromArray(validInputs);
  }

  FormStep.call(this, inputElementArrayFinder, validInputs, invalidInputs);
}

RadioFormStep.prototype.fill = function(radioButtons) {
  if(!radioButtons) {
    radioButtons = this.validInputs;
  }

  return this.elements.each(function(inputElementFinder) { BrowserHelper.isMatchingElement(inputElementFinder, radioButtons).then(function(isMatch) {
    if(isMatch) {
      inputElementFinder.click();
    }
  })});
}
```

```
BrowserHelper.prototype.isMatchingElement = function(elementFinder, elementArrayFinder) {
  var deferred = protractor.promise.defer(),
      isMatch  = false;

  elementArrayFinder.each(function(possibleMatch) {
    return elementFinder.equals(possibleMatch).then(function(elementMatches) {
      if(elementMatches) {
        isMatch = true;
      }
    })
  }).then(function() {
    deferred.fulfill(isMatch);
  })

  return deferred.promise;
}
```

- Output from running the test
```
Filling correctly
      ✗ Should result in a valid form
        - Failed: Cannot read property 'schedule' of undefined
            at /Users/thasisclaus/omnistack/node_modules/selenium-webdriver/lib/webdriver.js:1698:23
            at ManagedPromise.invokeCallback_ (/Users/thasisclaus/omnistack/node_modules/selenium-webdriver/lib/promise.js:1379:14)
            at TaskQueue.execute_ (/Users/thasisclaus/omnistack/node_modules/selenium-webdriver/lib/promise.js:2913:14)
            at TaskQueue.executeNext_ (/Users/thasisclaus/omnistack/node_modules/selenium-webdriver/lib/promise.js:2896:21)
            at asyncRun (/Users/thasisclaus/omnistack/node_modules/selenium-webdriver/lib/promise.js:2775:27)
            at /Users/thasisclaus/omnistack/node_modules/selenium-webdriver/lib/promise.js:639:7
            at process._tickCallback (internal/process/next_tick.js:103:7)
        From: Task: Run it("Should result in a valid form") in control flow
            at Object.<anonymous> (/Users/thasisclaus/omnistack/node_modules/jasminewd2/index.js:79:14)
            at /Users/thasisclaus/omnistack/node_modules/jasminewd2/index.js:16:5
            at ManagedPromise.invokeCallback_ (/Users/thasisclaus/omnistack/node_modules/selenium-webdriver/lib/promise.js:1379:14)
            at TaskQueue.execute_ (/Users/thasisclaus/omnistack/node_modules/selenium-webdriver/lib/promise.js:2913:14)
            at TaskQueue.executeNext_ (/Users/thasisclaus/omnistack/node_modules/selenium-webdriver/lib/promise.js:2896:21)
            at asyncRun (/Users/thasisclaus/omnistack/node_modules/selenium-webdriver/lib/promise.js:2775:27)
            at /Users/thasisclaus/omnistack/node_modules/selenium-webdriver/lib/promise.js:639:7
            at process._tickCallback (internal/process/next_tick.js:103:7)
        From asynchronous test: 
        Error
            at Suite.<anonymous> (/Users/thasisclaus/omnistack/e2e/signup/signup.spec.js:235:5)
            at Suite.<anonymous> (/Users/thasisclaus/omnistack/e2e/signup/signup.spec.js:234:3)
            at Object.<anonymous> (/Users/thasisclaus/omnistack/e2e/signup/signup.spec.js:12:1)
            at Module._compile (module.js:570:32)
            at Object.Module._extensions..js (module.js:579:10)
            at Module.load (module.js:487:32)
            at tryModuleLoad (module.js:446:12)
            at Function.Module._load (module.js:438:3)
            at Module.require (module.js:497:17)
            at require (internal/module.js:20:19)
            at Array.forEach (native)
```

- Steps to reproduce the bug
 I'm not sure where the bug is coming from but I believe it has something to do with the timing of `.each` since the promise it returns is independent of the iterator function needing to do async work. The bug is absolutely stemming from some logic with the RadioFormStep as commenting it out of the array causes the bug to stop appearing. The `isMatchingElement` function is almost certainly not the (sole) cause as testing it by itself in other files has 100% working behavior.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by tsclaus** [comment]
As far as I can tell I'm using your functions exactly as they're intended to be used and they're using the webdriver code incorrectly (or the webdriver code itself is working incorrectly). With that in mind shouldn't the protractor code base be updated to avoid this problem?
