### ISSUE TITLE
Could not able to perform npm install

### ISSUE THREAD

**Issue by sunilpatro1985** [angular/protractor#4314]
Below are the files I have
```
`conf.ts
import {Config} from 'protractor';

export let config: Config = {
  framework: 'jasmine',
  capabilities: {
    browserName: 'chrome'
  },
  specs: [ 'spec.js' ],
  seleniumAddress: 'http://localhost:4444/wd/hub',

  // You could set no globals to true to avoid jQuery '$' and protractor '$'
  // collisions on the global namespace.
  noGlobals: true
};`
```

```
`package.json
{
  "name": "example-typescript",
  "version": "1.0.0",
  "description": "a typescript example",
  "author": "",
  "license": "MIT",
  "scripts": {
    "tsc": "tsc",
    "pretest": "npm run tsc",
    "test": "C:/Users/u0146751/AppData/Roaming/npm/node_modules/protractor/bin/protractor tmp/conf.js",
   "debug": "node --inspect --debug-brk C:/Users/u0146751/AppData/Roaming/npm/node_modules/protractor/bin/protractor asyncAwait/conf.js"
  },
  "dependencies": {
    "@types/jasmine": "2.5.41",
    "@types/jasminewd2": "^2.0.0",
    "jasmine": "^2.4.1",
    "protractor": "C:/Users/u0146751/AppData/Roaming/npm/node_modules/protractor/bin/protractor",
    "typescript": "~2.0.0"
  },
  "devDependencies": {
    "@types/jasminewd2": "^2.0.0",
    "ts-node": "^3.0.2"
  }
}`
```

```
`spec.ts
import {browser, element, by, By, $, $$, ExpectedConditions} from 'protractor';

describe('protractor with typescript typings', () => {
  beforeEach(() => {
    browser.get('http://www.angularjs.org');
  });

  it('should greet the named user', () => {
    element(by.model('yourName')).sendKeys('Julie');
    let greeting = element(by.binding('yourName'));
    expect(greeting.getText()).toEqual('Hello Julie!');
  });

  it('should list todos', function() {
    let todoList = element.all(by.repeater('todo in todoList.todos'));
    expect(todoList.count()).toEqual(2);
    expect(todoList.get(1).getText()).toEqual('build an angular app');
  });
});`
```

```
`tsconfig.json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "inlineSourceMap": true,
    "declaration": false,
    "noImplicitAny": false,
    "outDir": "tmp"
  },
  "exclude": [
    "node_modules",
    "asyncAwait",
    "plugins.ts"
  ]
}`
```

When I am performing npm install, it throws error

```
C:\MyFiles\NewTechonologies\Protractor\TypeScript\Test>npm install
npm ERR! not a package C:\Users\u0146751\AppData\Roaming\npm\node_modules\protractor\bin\protractor
npm ERR! addLocal Could not install C:\Users\u0146751\AppData\Roaming\npm\node_modules\protractor\bin\protractor
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "
install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\u0146751\AppData\Local\Temp\npm-8952-eac08724\unpack-b2acb3b1\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\u0146751\AppData\Local\Temp\npm-8952-eac08724\unpac
k-b2acb3b1\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\u0146751\AppData\Local\Temp\npm-8952-eac08724\unpac
k-b2acb3b1\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\MyFiles\NewTechonologies\Protractor\TypeScript\Test\npm-debug.log
```

I have installed protractor, npm, jasmine globaly
Please guide if there is any setup needs to be done.

**Comment by NickTomlin** [comment]
If you look at the stack trace you will see 

```
not a package C:\Users\u0146751\AppData\Roaming\npm\node_modules\protractor\bin\protractor
```

This is because your package.json includes this as a dependency:

```
"protractor": "C:/Users/u0146751/AppData/Roaming/npm/node_modules/protractor/bin/protractor",
```

This is an invalid dependency declaration, you are saying that the module `protractor` exists at a path, but that path is actually just the `protractor` executable.

Please read the NPM documentation on declaring and installing dependencies. If you have additional issues please ask a question on StackOverflow. Thanks!

**Comment by sunilpatro1985** [comment]
When I am running npm test, getting error as 
```
import {browser, element, by, By, $, $$, ExpectedConditions} from 'protractor';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\MyFiles\NewTechonologies\Protractor\TypeScript\Test\node_modules\jasmine\lib\jasmine.js:93:5
[19:26:29] E/launcher - Process exited with error code 100
npm ERR! Test failed.  See above for more details.
```
May I know how to get rid of this error.

**Comment by NickTomlin** [comment]
Please ask unrelated usage or debugging questions on stackoverflow. I'm going to close this thread for now. Thanks!
