### ISSUE TITLE
ScriptTimeoutError: Timed out - From: Task: Protractor.waitForAngular() 

### ISSUE THREAD

**Issue by MythriManjunath** [angular/protractor#4348]
Hi!
I am trying to run basic end to end tests written using protractor. I always get this error. 

> ScriptTimeoutError: Timed out

I checked this link https://github.com/angular/protractor/blob/master/docs/timeouts.md and increased the default timeout, but still I get the same error. I am not able to figure out  from where this error pops out.  The browser loads the base Url, later it will not perform any action as mentioned in the test. The test is very simple , open the browser and click on the menu and verify if the URL is matched. 

- Node Version: `v7.5.0`
- Protractor Version: `5.1.2`
- Angular Version: `2.4.10`
- Browser(s): `firefox`
- Operating System and Version `Linux`
- typescript: `2.2.2`
- Your protractor configuration file
```
exports.config = {
  framework: 'jasmine2',    
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['test/e2e/menu.js'],
  capabilities: {
    'browserName': 'firefox', 
},
baseUrl: 'http://localhost:8100/#/',
//allScriptsTimeout: 360000, 
  jasmineNodeOpts: {
   showColors: true,
  // defaultTimeoutInterval: 360000
 },
//useAllAngular2AppRoots:true,
```

- A relevant example test
```
describe('menu check', function () {
   beforeEach(function () {
        browser.get('http://localhost:8100/#/');
      //browser.waitForAngular();
     // browser.driver.manage().timeouts().setScriptTimeout(60000);
   });
 
    it('Should route to the operationalView page from menu', function () {
       element.all(by.css('[href="#/operationalView"]')).click();
       expect(browser.getCurrentUrl()).toMatch('http://localhost:8100/#/operationalView');
    });
   
    it('Should route to the worldlview page from menu', function () {
        element(by.css('[href="#/worldView"]')).click();
        expect(browser.getCurrentUrl()).toMatch('http://localhost:8100/#/worldView');
    });
});
```
- Output from running the test
```
 Message:
    Failed: Timed out
    Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
    System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-81-generic', java.version: '1.8.0_121'
    Driver info: org.openqa.selenium.firefox.FirefoxDriver
    Capabilities [{moz:profile=/tmp/rust_mozprofile.VvfysmjJzM2Y, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0, platformVersion=4.4.0-81-generic, moz:processID=9113.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]
    Session ID: f1b698e2-0a60-43d6-89f5-aad2e4326516
  Stack:
    ScriptTimeoutError: Timed out
    Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
    System info: host: 'ubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-81-generic', java.version: '1.8.0_121'
    Driver info: org.openqa.selenium.firefox.FirefoxDriver
    Capabilities [{moz:profile=/tmp/rust_mozprofile.VvfysmjJzM2Y, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0, platformVersion=4.4.0-81-generic, moz:processID=9113.0, browserName=firefox, javascriptEnabled=true, platformName=linux}]
    Session ID: f1b698e2-0a60-43d6-89f5-aad2e4326516
        at Object.checkLegacyResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
        at parseHttpResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
        at doSend.then.response (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: Protractor.waitForAngular() - Locator: By(css selector, [href="#/operationalView"])
        at thenableWebDriverProxy.schedule (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
        at ProtractorBrowser.executeAsyncScript_ (/usr/lib/node_modules/protractor/lib/browser.ts:609:24)
        at angularAppRoot.then (/usr/lib/node_modules/protractor/lib/browser.ts:643:23)
        at ManagedPromise.invokeCallback_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1366:14)
        at TaskQueue.execute_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2813:27)
        at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:103:7)Error
        at ElementArrayFinder.applyAction_ (/usr/lib/node_modules/protractor/lib/element.ts:482:23)
        at ElementArrayFinder.(anonymous function) [as click] (/usr/lib/node_modules/protractor/lib/element.ts:96:21)
        at Object.<anonymous> (/home/ubuntu/git/idevops/Test/demoDashboardTest/test/e2e/menu.js:9:58)
        at /usr/lib/node_modules/protractor/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/usr/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2860:25)
    From: Task: Run it("Should route to the operationalView page from menu") in control flow
        at Object.<anonymous> (/usr/lib/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
        at /usr/lib/node_modules/protractor/node_modules/jasminewd2/index.js:64:48
        at ControlFlow.emit (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/events.js:62:21)
        at ControlFlow.shutdown_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2565:10)
        at shutdownTask_.MicroTask (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2490:53)
        at MicroTask.asyncRun (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2619:9)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/home/ubuntu/git/idevops/Test/demoDashboardTest/test/e2e/menu.js:8:5)
        at Object.<anonymous> (/home/ubuntu/git/idevops/Test/demoDashboardTest/test/e2e/menu.js:1:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
```

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

To give an answer on your problem. This is a scripting error. It looks like you are clicking on an `ElementArrayFinder`, see `element.all(by.css('[href="#/operationalView"]')).click();`, that's almost what is standing in your stacktrace `Error at Suite.<anonymous> (/home/ubuntu/git/idevops/Test/demoDashboardTest/test/e2e/menu.js:8:5)`. I think if you remove the `all` it should work. If not please post your question on SO and close this issue

Thanks!
