### ISSUE TITLE
How to run Autoit script using protractor

### ISSUE THREAD

**Issue by Hokrani** [angular/protractor#4368]
i'm trying to simulate an upload file with protractor i know that the protractor can't interact with OS window and i created an EXE file (with autoit), that takes focus and insert a file . when i'm testing manually everything working ok . when i try to write it in protractor i get error

This is my protractor code. 

```
const child = exec('C:\\Users\\Desktop\\FileUpload.exe', (error, stdout, stderr) => {
      if (error) {
                throw error;
            }
     console.log(stdout);
}

```
Below error is thrown :  

```

          at elementArrayFinder.getWebElements.then (C:\Users\workspac
e\SoftwarPkgManagement\client\node_modules\protractor\lib\element.ts:851:17)
          at ManagedPromise.invokeCallback_ (C:\Users\workspace\Softwa
rPkgManagement\client\node_modules\selenium-webdriver\lib\promise.js:1366:14)
          at TaskQueue.execute_ (C:\Users\workspace\SoftwarPkgManageme
nt\client\node_modules\selenium-webdriver\lib\promise.js:2970:14)
          at TaskQueue.executeNext_ (C:\Users\workspace\SoftwarPkgMana
gement\client\node_modules\selenium-webdriver\lib\promise.js:2953:27)
          at asyncRun (C:\Users\workspace\SoftwarPkgManagement\client\
node_modules\selenium-webdriver\lib\promise.js:2813:27)
          at C:\Users\workspace\SoftwarPkgManagement\client\node_modul
es\selenium-webdriver\lib\promise.js:676:7
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:169:7)Error
          at ElementArrayFinder.applyAction_ (C:\Users\workspace\Softw
arPkgManagement\client\node_modules\protractor\lib\element.ts:482:23)
          at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\2
12394218\workspace\SoftwarPkgManagement\client\node_modules\protractor\lib\eleme
nt.ts:96:21)
          at ElementFinder.(anonymous function).args [as click] (C:\Users\212394
218\workspace\SoftwarPkgManagement\client\node_modules\protractor\lib\element.ts
:873:14)
          at Object.<anonymous> (C:\Users\workspace\SoftwarPkgManageme
nt\client\e2e\RSvP_CreatePackage.ts:80:47)
          at new ManagedPromise (C:\Users\workspace\SoftwarPkgManageme
nt\client\node_modules\selenium-webdriver\lib\promise.js:1067:7)
          at ControlFlow.promise (C:\Users\workspace\SoftwarPkgManagem
ent\client\node_modules\selenium-webdriver\lib\promise.js:2396:12)
          at TaskQueue.execute_ (C:\Users\workspace\SoftwarPkgManageme
nt\client\node_modules\selenium-webdriver\lib\promise.js:2970:14)
          at TaskQueue.executeNext_ (C:\Users\workspace\SoftwarPkgMana
gement\client\node_modules\selenium-webdriver\lib\promise.js:2953:27)
          at asyncRun (C:\Users\workspace\SoftwarPkgManagement\client\
node_modules\selenium-webdriver\lib\promise.js:2860:25)
          at C:\Users\workspace\SoftwarPkgManagement\client\node_modul
es\selenium-webdriver\lib\promise.js:676:7
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:169:7)
      From: Task: Run it("Create package") in control flow
          at ControlFlow.emit (C:\Users\workspace\SoftwarPkgManagement
\client\node_modules\selenium-webdriver\lib\events.js:62:21)
          at ControlFlow.shutdown_ (C:\Users\workspace\SoftwarPkgManag
ement\client\node_modules\selenium-webdriver\lib\promise.js:2565:10)
          at shutdownTask_.MicroTask (C:\Users\workspace\SoftwarPkgMan
agement\client\node_modules\selenium-webdriver\lib\promise.js:2490:53)
          at MicroTask.asyncRun (C:\Users\workspace\SoftwarPkgManageme
nt\client\node_modules\selenium-webdriver\lib\promise.js:2619:9)
          at C:\Users\workspace\SoftwarPkgManagement\client\node_modul
es\selenium-webdriver\lib\promise.js:676:7
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:169:7)
      From asynchronous test:
      Error
          at Suite.<anonymous> (C:\Users\workspace\SoftwarPkgManagemen
t\client\e2e\RSvP_CreatePackage.ts:38:5)
          at Object.<anonymous> (C:\Users\workspace\SoftwarPkgManageme
nt\client\e2e\RSvP_CreatePackage.ts:6:1)
          at Module._compile (module.js:569:30)
          at Module.m._compile (C:\Users\workspace\SoftwarPkgManagemen
t\client\node_modules\ts-node\src\index.ts:406:23)
          at Module._extensions..js (module.js:580:10)
          at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\2
12394218\workspace\SoftwarPkgManagement\client\node_modules\ts-node\src\index.ts
:409:12)
          at Module.load (module.js:503:32)
          at tryModuleLoad (module.js:466:12)
          at Function.Module._load (module.js:458:3)
          at Module.require (module.js:513:17)
          at require (internal/module.js:11:18)
**************************************************

```

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README:


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!

**Comment by kommuswamy** [comment]
Has anyone opened the issue in Stackoverflow?
