### ISSUE TITLE
Exception thrown with Chrom on Ubantu VM.

### ISSUE THREAD

**Issue by nkpathrut** [angular/protractor#4440]
- Node Version: `8.1.1`
- Protractor Version: `5.1.2`
- Angular Version: not installed
- Browser(s): `Google Chrome Info: 59.0.3071.104, Driver info: chromedriver=2.31.488763`
- Operating System and Version `Linux 4.4.0-62-generic x86_64`
- protractor configuration file
```js
// conf.js
exports.config = {
  framework: 'jasmine',
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['spec.js']
}
```
- // spec.js
```js
describe('Protractor Demo App', function() {
  it('should have a title', function() {
    browser.get('http://juliemr.github.io/protractor-demo/');

    expect(browser.getTitle()).toEqual('Super Calculator');
  });
});
```
- Output from running the test on server console
```shell
va:637)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriv                             er.java:250)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriv                             er.java:236)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.jav                             a:137)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:184)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:148)
        ... 14 more
12:03:53.838 WARN - Exception: unknown error: Chrome failed to start: exited abn                             ormally
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5b                             a8),platform=Linux 4.4.0-62-generic x86_64) (WARNING: The server did not provide                              any stacktrace information)
Command duration or timeout: 60.06 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'test1sp117', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'am                             d64', os.version: '4.4.0-62-generic', java.version: '1.8.0_131'
Driver info: driver.version: ChromeDriver
^C[12:27:27] I/start - Staying alive until the Selenium Standalone process exits
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1016:11)
    at TCP.onread (net.js:609:25)
root@test1sp117:~# clear
root@test1sp117:~# webdriver-manager start
[12:27:33] I/start - java -Djava.security.egd=file:///dev/./urandom -Dwebdriver.chrome.driver=/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.31 -Dwebdriver.gecko.driver=/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.18.0 -jar /root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.4.0.jar -port 4444
[12:27:33] I/start - seleniumProcess.pid: 8916
12:27:33.736 INFO - Selenium build info: version: '3.4.0', revision: 'unknown'
12:27:33.738 INFO - Launching a standalone Selenium Server
2017-08-09 12:27:33.769:INFO::main: Logging initialized @534ms to org.seleniumhq.jetty9.util.log.StdErrLog
12:27:33.875 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
12:27:33.876 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
12:27:33.876 INFO - Driver class not found: com.opera.core.systems.OperaDriver
12:27:33.876 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
12:27:33.877 INFO - Driver class not found: com.opera.core.systems.OperaDriver
12:27:33.877 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
12:27:33.878 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
2017-08-09 12:27:33.985:INFO:osjs.Server:main: jetty-9.4.3.v20170317
2017-08-09 12:27:34.068:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@523884b2{/,null,AVAILABLE}
2017-08-09 12:27:34.103:INFO:osjs.AbstractConnector:main: Started ServerConnector@13deb50e{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-08-09 12:27:34.106:INFO:osjs.Server:main: Started @871ms
12:27:34.106 INFO - Selenium Server is up and running
12:27:54.479 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
12:27:54.544 INFO - Executing: [new session: Capabilities [{count=1, browserName=chrome}]])
12:27:54.645 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome}]
Starting ChromeDriver 2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8) on port 6027
Only local connections are allowed.
12:28:55.679 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'test1sp117', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-62-generic', java.version: '1.8.0_131'
Driver info: driver.version: unknown
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
        at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
        at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
        at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:131)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:36)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:190)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:222)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:184)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:150)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'test1sp117', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-62-generic', java.version: '1.8.0_131'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:110)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:96)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:102)
        ... 9 more
Caused by: org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 4.4.0-62-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.14 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'test1sp117', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-62-generic', java.version: '1.8.0_131'
Driver info: driver.version: ChromeDriver
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:184)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:148)
        ... 14 more
12:28:55.704 WARN - Exception: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 4.4.0-62-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.14 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'test1sp117', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-62-generic', java.version: '1.8.0_131'
Driver info: driver.version: ChromeDriver
```

-Output from running the test on directory console(where .conf.js, spec.js located & run as "protractor conf.js")
```shell
postgres 11302  7697  0 Jul19 ?        00:50:41 postgres: ambari ambari 127.0.0.
root     11664     1  0 Jul10 ?        02:09:34 java -jar /opt/jetty/jetty-distr
root     14509     1  0 Jul10 ?        02:14:38 java -jar /opt/jetty/jetty-distr
rabbitmq 16131     1  0 Jul10 ?        00:00:00 /bin/sh /usr/sbin/rabbitmq-serve
rabbitmq 16142 16131  0 Jul10 ?        00:00:00 /bin/sh -e /usr/lib/rabbitmq/bin
rabbitmq 16211     1  0 Jul10 ?        00:03:26 /usr/lib/erlang/erts-7.3/bin/epm
rabbitmq 16258 16142  0 Jul10 ?        05:21:13 /usr/lib/erlang/erts-7.3/bin/bea
rabbitmq 16373 16258  0 Jul10 ?        00:00:19 inet_gethost 4
rabbitmq 16374 16373  0 Jul10 ?        00:00:37 inet_gethost 4
root     17075     1  0 Jul10 ?        02:14:26 java -jar /opt/jetty/jetty-distr
postfix  17546  2058  0 Aug08 ?        00:00:00 qmgr -l -t unix -u
root     18468     1  0 Jul10 ?        02:14:21 java -jar /opt/jetty/jetty-distr
root     25146     2  0 06:25 ?        00:00:01 [kworker/0:0]
www-data 25163  1597  0 06:25 ?        00:00:45 /usr/sbin/apache2 -k start
www-data 25164  1597  0 06:25 ?        00:00:45 /usr/sbin/apache2 -k start
root     25494     1  0 Jul10 ?        00:00:00 /lib/systemd/systemd --user
root     25498 25494  0 Jul10 ?        00:00:00 (sd-pam)
uuidd    25726     1  0 Jul10 ?        00:00:00 /usr/sbin/uuidd --socket-activat
root     28037     2  0 08:37 ?        00:00:01 [kworker/1:0]
postfix  29966  2058  0 10:35 ?        00:00:00 pickup -l -t unix -u -c
root     30298  1342  0 10:56 ?        00:00:00 sshd: root@pts/0
root     30396 30298  0 10:57 pts/0    00:00:00 -bash
unbound  31331     1  0 Jul20 ?        00:00:04 /usr/sbin/unbound
root@test1sp117:~/protest# kill -9  7838
-bash: kill: (7838) - No such process
root@test1sp117:~/protest# kill -9  6724
root@test1sp117:~/protest# node -v
v8.1.1
root@test1sp117:~/protest# clear
root@test1sp117:~/protest# protractor conf.js
(node:8941) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[12:27:53] I/launcher - Running 1 instances of WebDriver
[12:27:54] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[12:28:55] E/launcher - unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 4.4.0-62-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.14 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'test1sp117', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-62-generic', java.version: '1.8.0_131'
Driver info: driver.version: ChromeDriver
[12:28:55] E/launcher - WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 4.4.0-62-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.14 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'test1sp117', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-62-generic', java.version: '1.8.0_131'
Driver info: driver.version: ChromeDriver
    at Object.checkLegacyResponse (/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:709:29)
    at createDriver (/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:623:16)
    at Hosted.getNewDriver (/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/root/.nvm/versions/node/v8.1.1/lib/node_modules/protractor/node_modules/q/q.js:796:13)
[12:28:55] E/launcher - Process exited with error code 199
root@test1sp117:~/protest#
```

- Steps to reproduce the bug
1. Run the "webdriver-manager start" on one session of VM via console

2.  Run the "protractor conf.js" command from conf.js file located directory using another session of VM via console.

Please Help how to resolve the issue? Ready to provide any other details of execution, if needed.

**Comment by nkpathrut** [comment]
I have tried with update as :+1:

webdriver-manager update --versions.chrome 2.24

It doesn't give the solution towards running correctly

**Comment by wswebcreation** [comment]
Hi @nkpathrut ,

Don't know if it's related and I don't have experience with Linux, but it's a rights issue. Please see this thread https://github.com/NickTomlin/protractor-flake/issues/54#issuecomment-309643992 by @qualityshepherd.

Hope it helps

**Comment by NickTomlin** [comment]
@nkpathrut It can be difficult to diagnose these errors. I've typically seen this when running on a container with misconfigured display settings or no proper display. You will typically need to use something like `Xvfb` alongside a browser driver.

Unfortunately, this is not on topic for the issue queue. I'd suggest asking a question on StackOverflow to get some help debugging.
