### ISSUE TITLE
Getting error "WebDriverError: Invalid timeout type specified: ms"

### ISSUE THREAD

**Issue by moinuddin14** [angular/protractor#4445]
Hi 

I have not made any changes to my tests but all of a sudden started seeing the below error on the console. 

[12:19:49] E/runner - Unable to start a WebDriver session.
[12:19:49] E/launcher - Error: WebDriverError: Invalid timeout type specified: ms

Bug report
---

- Node Version: v6.11.1
- Protractor Version: 5.1.2
- Angular Version: 
- Browser(s): IE
- Operating System and Version: Windows 8.1 Pro 64 bit OS

Unfortunately the entire code is inside vpn and cannot bring it outside VPN. Any help in this regard is appreciated.

**Comment by robertsmith2** [comment]
Same issue here

**Comment by moinuddin14** [comment]
@robertsmith2 Were you able to successfully run the tests earlier? I was able to, but all of a sudden i see this happening. I restarted my machine and clean installed at several places, but still see this happening. In the other VM machine that i have, i did not touch anything and the tests are running fine there. Not sure what could be the issue here.

**Comment by robertsmith2** [comment]
@moinuddin14 yeah IE was working a couple days ago. I upgraded from `5.1.1` to `5.1.2` only thing I can think of that changed

**Comment by moinuddin14** [comment]
@robertsmith2 I have verified with 5.0.0 and with IE driver its working fine. Looks like with 5.1.2 its broken somehow. Protractor team can you please look into this issue. Tried to find within protractor code base from where this error is originating from but couldn't find the trace of this error.

**Comment by moinuddin14** [comment]
It's working fine for me till 5.0.0, and with 5.1.1 as well 5.1.2 it's throwing the error "WebDriverError: Invalid timeout type specified: ms"

**Comment by bruderol** [comment]
same problem here :-(

**Comment by wswebcreation** [comment]
Need to dive into it more in detail, but these are the changes between 5.1.1 and 5.1.2

https://github.com/angular/protractor/compare/5.1.1...5.1.2

**Comment by ashlives** [comment]
Same issue here.
Node version: 6.11.1
Protractor version: 5.1.2

conf.js

```
exports.config = {
    framework: 'custom',
    seleniumAddress: 'http://localhost:4444/wd/hub',
    suites:{
        LanguageSelectionPopup: 'tests/*.feature'
    },
    restartBrowserBetweenTests: true,
    capabilities: {
        browserName: 'internet explorer'
    },
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 360000
    }
};
```

Error:

```
"C:\Program Files\nodejs\node.exe" "C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\bin\protractor" "C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3\plugins\JavaScriptLanguage\helpers\protractor-intellij\lib\protractor-intellij-config.js" "--intellijOriginalConfigFile=C:\Users\Lenovo G50-70\IdeaProjects\com.protractortest.myapp\conf.js"
[18:46:13] I/launcher - Running 1 instances of WebDriver
[18:46:13] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[18:46:25] E/runner - Unable to start a WebDriver session.
[18:46:25] E/launcher - Error: WebDriverError: Invalid timeout type specified: ms
Build info: version: '3.5.0', revision: '8def36e068', time: '2017-08-10T23:00:22.093Z'
System info: host: 'DESKTOP-9AVDLI7', ip: '192.168.2.100', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown
    at WebDriverError (C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:5)
    at Object.checkLegacyResponse (C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:505:15)
    at parseHttpResponse (C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.manage().timeouts().setScriptTimeout(11000)
    at WebDriver.schedule (C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:816:17)
    at Timeouts._scheduleCommand (C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:1500:25)
    at Timeouts.setScriptTimeout (C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:1483:17)
    at browser_.ready.browser_.ready.then.then (C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\lib\runner.ts:281:49)
    at ManagedPromise.invokeCallback_ (C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1366:14)
    at TaskQueue.execute_ (C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2813:27)
    at C:\Users\Lenovo G50-70\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)
[18:46:25] E/launcher - Process exited with error code 100

Process finished with exit code 100
Empty test suite.
```

**Comment by bruderol** [comment]
with protractor 5.0.0 it is working - the bug seems to be introduced with 5.1.0 (if I tested correctly)

**Comment by robertsmith2** [comment]
5.0.0 works for me locally hopefully works on release agent.

**Comment by bruderol** [comment]
Actually this must be somehow related to the selenium server being used for ie testing - I found out that it was once working for me with version 5.1.2 but with Selenium IEDriverServer Version 3.4.0 - and since that version changed to 3.5.0 it does not work anymore. I try now to install the older version of the server and hope that one is still gonna work with my IE version. 🙏

**Comment by robertsmith2** [comment]
I got mine working with IEDriver 2.53.1 good luck @bruderol

**Comment by ashlives** [comment]
@robertsmith2 you mean IEDriver 2.53.1 with Protractor: 5.1.2 worked? Or did you used 5.0.0 for this?

**Comment by Harish247** [comment]
I had the same problem in IE. I figured out that selenium standalone server and IE driver got updated to 3.5.0. Try to downgrade the standalone server and IE to 3.4.0. This worked for me.

**Comment by bruderol** [comment]
Just using `webdriver-manager update --ie --versions.standalone 3.4.0 --versions.ie 3.4.0` solved the issue for me.

**Comment by Roman150** [comment]
I had the same issue, but I managed it with this "webdriver-manager update --ie --versions.standalone 3.4.0 --versions.ie 3.4.0" command
protractor version 5.1.2.

**Comment by jbprat** [comment]
@bruderol, @Roman150 I tried your instruction, but when I run webdriver-manager start the logs start with this:

**Comment by wswebcreation** [comment]
Guys

See here https://github.com/angular/protractor/issues/4451#issuecomment-324120250

**Comment by jbprat** [comment]
@wswebcreation How would you pin the version for a specific webdriver? I have removed and uninstalled webdriver-manager and I cannot seem to downgrade IE driver.

**Comment by wswebcreation** [comment]
Will check later today, come back tonit

**Comment by Harish247** [comment]
@jbprat Try to start the webdriver manager with a specific version.

`webdriver-manager start --versions.standalone=3.4.0`

If we do not mention version webdriver will consider the latest version. I hope this will solve your issue.

**Comment by Roman150** [comment]
@jbprat, my logs was different from yours, your log starts with "java" ,check if java is present in classpath and  java -version command in console return version of your jdk, tomorrow i can write you version of all my environment and drivers , and then you can compare all

**Comment by wswebcreation** [comment]
@Harish247 

Tnx for your answer. 

@jbprat The docs that mention the reason why you need to start with a specific version can be found [here](https://github.com/angular/webdriver-manager/blob/master/docs/versions.md#start-command-setting-specific-versions)

**Comment by webdeveloperninja** [comment]
Thanks @Harish247 I did not know you could specify a version like that

**Comment by jbprat** [comment]
@wswebcreation @Roman150 @Harish247, Thank you for the details!

**Comment by jbprat** [comment]
What worked for me was:

**Comment by wswebcreation** [comment]
@jbprat,

Tnx tot the feedback

**Comment by agne-a-t** [comment]
Any news on this issue?

**Comment by saadEB** [comment]
I have the same issue with: selenium-server-standalone-3.6.0
Didn't try different versions yet. Is there a selenium & IE driver that works fine? 
with:
Node Version: v6.11.1
Protractor Version: 5.1.2

**Comment by ajklotz** [comment]
Still having this issue, is it expected of us to install a earlier version of the IE driver in order to keep 5.1.2, or does a later version of protractor solve this problem?

**Comment by raberana** [comment]
Still having this issue with IEDriver 3.8 and Protractor 5.3

**Comment by h0l0tn1k** [comment]
it works for me with version 3.0 x64 and below .

**Comment by AdvanceAutomation** [comment]
Any solution on this?

**Comment by GitSage** [comment]
I see this error consistently whenever I use SELENIUM_PROMISE_MANAGER: false with Internet Explorer. The same code works great in Chrome.

Node v.8.10.0
Protractor v.5.3.0
IEDriverServer v.3.11.1

**Comment by LilSebastian5000** [comment]
Has anybody figured out why IEDriverServer 3.11.1 doesn't work? 

Downgrading to IEDriverServer 3.4.0 does the trick for me, but I'd really like to use the latest to see if any bugs I've been facing have been fixed in the later webdriver versions.

**Comment by sorcalin0x11** [comment]
Any solution on this yet? Still stuck on 3.4.0 of IEDriverServer.exe
