### ISSUE TITLE
IE Driver session Terminates at Static point Protractor

### ISSUE THREAD

**Issue by Sabesna** [angular/protractor#4457]
Hi there!

We tried automating an Angular application in IE 11, but the driver session terminates at a static point all the time when try to execute.

We have mentioned the steps that i have tried and also the Possible combinations of Protractor Versions below,

    1. We used following different combination of versions 
        1. NPM(3.10.10, 5.3.0), 
        2. Node(6.11.0, 6.11.2), 
        3. Protractor(4.0.3, 4.0.9, 5.1.0, 5.1.2) 
    2. We used following methods 
        1. restart() 
        2. restartSync() 
        3. refresh() 
        4. waitForAngularEnabled() 
        5. angularAppRoot() 
        6. userAllAngular2AppRoots() 
        7. forkNewDriverInstance() 
    3. We tried to automation sample demo angularJS application, we were unable to reproduce this issue. 

I have also attached the LOG below,

```shell
[12:01:15] I/launcher - Running 1 instances of WebDriver
[12:01:15] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
Started
.FA Jasmine spec timed out. Resetting the WebDriver Control Flow.

Failures:
1) TestCase TC_URP_001 : Bell Branding-Intial operations Click And Validate CreateSubMenuItems and Select
  Message:
    Failed: Unable to get browser (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 13 milliseconds
    Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
    System info: host: 'DUCENIT-140', ip: '10.0.0.190', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', ja
va.version: '1.8.0_112'
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{se:ieOptions={browserAttachTimeout=0.0, ie.enableFullPageScreenshot=true, enablePersistentHover=true
, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=30
00.0, ie.useLegacyFileUploadDialogHandling=false, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior
=0.0, ie.browserCommandLineSwitches=, requireWindowFocus=false, initialBrowserUrl=http://localhost:24071/, ignoreProtec
tedModeSettings=false, enableElementCacheCleanup=true}, browserName=internet explorer, pageLoadStrategy=normal, javascr
iptEnabled=true, version=11, platform=WINDOWS, unexpectedAlertBehaviour=dismiss}]
    Session ID: 8e005f70-24d3-48c0-95cc-010da396b61e
```

Stack:
```shell
    NoSuchWindowError: Unable to get browser (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 13 milliseconds
    Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
    System info: host: 'DUCENIT-140', ip: '10.0.0.190', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', ja
va.version: '1.8.0_112'
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{se:ieOptions={browserAttachTimeout=0.0, ie.enableFullPageScreenshot=true, enablePersistentHover=true
, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=30
00.0, ie.useLegacyFileUploadDialogHandling=false, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior
=0.0, ie.browserCommandLineSwitches=, requireWindowFocus=false, initialBrowserUrl=http://localhost:24071/, ignoreProtec
tedModeSettings=false, enableElementCacheCleanup=true}, browserName=internet explorer, pageLoadStrategy=normal, javascr
iptEnabled=true, version=11, platform=WINDOWS, unexpectedAlertBehaviour=dismiss}]
    Session ID: 8e005f70-24d3-48c0-95cc-010da396b61e
        at WebDriverError (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdrive
r\lib\error.js:27:5)
        at NoSuchWindowError (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdr
iver\lib\error.js:192:5)
        at Object.checkLegacyResponse (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selen
ium-webdriver\lib\error.js:505:15)
        at parseHttpResponse (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdr
iver\lib\http.js:509:13)
        at doSend.then.response (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-we
bdriver\lib\http.js:440:13)
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From: Task: Protractor.waitForAngular() - Locator: By(css selector, *[id="newmenu"])
        at WebDriver.schedule (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webd
river\lib\webdriver.js:816:17)
        at ProtractorBrowser.executeAsyncScript_ (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\lib\bro
wser.ts:609:24)
        at angularAppRoot.then (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\lib\browser.ts:643:23)
        at ManagedPromise.invokeCallback_ (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\s
elenium-webdriver\lib\promise.js:1366:14)
        at TaskQueue.execute_ (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-
webdriver\lib\promise.js:2953:27)
        at asyncRun (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\
promise.js:2813:27)
        at C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js
:676:7Error
        at ElementArrayFinder.applyAction_ (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\lib\element.t
s:482:23)
        at ElementArrayFinder.(anonymous function) [as click] (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protr
actor\lib\element.ts:96:21)
        at ElementFinder.(anonymous function) [as click] (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor
\lib\element.ts:873:14)
        at Object.<anonymous> (C:\DUCEN\ECLIPSE_WS\IE\PivotWidgetSpec.js:42:14)
        at C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
        at new ManagedPromise (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webd
river\lib\promise.js:1067:7)
        at ControlFlow.promise (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-web
driver\lib\promise.js:2396:12)
        at schedulerExecute (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\inde
x.js:95:18)
        at TaskQueue.execute_ (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webd
river\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-
webdriver\lib\promise.js:2953:27)
    From: Task: Run it("Click And Validate CreateSubMenuItems and Select ") in control flow
        at Object.<anonymous> (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\in
dex.js:94:19)
From asynchronous test:
    Error
        at Suite.<anonymous> (C:\DUCEN\ECLIPSE_WS\IE\PivotWidgetSpec.js:38:4)
        at Object.<anonymous> (C:\DUCEN\ECLIPSE_WS\IE\PivotWidgetSpec.js:3:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)

2 specs, 1 failure
Finished in 8.215 seconds


[12:01:26] E/launcher - Unable to get browser (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 13 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DUCENIT-140', ip: '10.0.0.190', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.v
ersion: '1.8.0_112'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{se:ieOptions={browserAttachTimeout=0.0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie
.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000.0
, ie.useLegacyFileUploadDialogHandling=false, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0.0
, ie.browserCommandLineSwitches=, requireWindowFocus=false, initialBrowserUrl=http://localhost:24071/, ignoreProtectedM
odeSettings=false, enableElementCacheCleanup=true}, browserName=internet explorer, pageLoadStrategy=normal, javascriptE
nabled=true, version=11, platform=WINDOWS, unexpectedAlertBehaviour=dismiss}]
Session ID: 8e005f70-24d3-48c0-95cc-010da396b61e
[12:01:26] E/launcher - NoSuchWindowError: Unable to get browser (WARNING: The server did not provide any stacktrace in
formation)
Command duration or timeout: 13 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DUCENIT-140', ip: '10.0.0.190', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.v
ersion: '1.8.0_112'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{se:ieOptions={browserAttachTimeout=0.0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie
.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000.0
, ie.useLegacyFileUploadDialogHandling=false, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0.0
, ie.browserCommandLineSwitches=, requireWindowFocus=false, initialBrowserUrl=http://localhost:24071/, ignoreProtectedM
odeSettings=false, enableElementCacheCleanup=true}, browserName=internet explorer, pageLoadStrategy=normal, javascriptE
nabled=true, version=11, platform=WINDOWS, unexpectedAlertBehaviour=dismiss}]
Session ID: 8e005f70-24d3-48c0-95cc-010da396b61e
    at WebDriverError (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\li
b\error.js:27:5)
    at NoSuchWindowError (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver
\lib\error.js:192:5)
    at Object.checkLegacyResponse (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-
webdriver\lib\error.js:505:15)
    at parseHttpResponse (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver
\lib\http.js:509:13)
    at doSend.then.response (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdri
ver\lib\http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.takeScreenshot()
    at WebDriver.schedule (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdrive
r\lib\webdriver.js:816:17)
at WebDriver.takeScreenshot (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-we
bdriver\lib\webdriver.js:1092:17)
    at run (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\lib\browser.ts:66:27)
    at ProtractorBrowser.to.(anonymous function) [as takeScreenshot] (C:\Users\DucenIT1\AppData\Roaming\npm\node_module
s\protractor\lib\browser.ts:74:12)
    at Jasmine2HTMLReporter.self.specDone (C:\DUCEN\ECLIPSE_WS\IE\node_modules\protractor-jasmine2-html-reporter\index.
js:203:21)
    at dispatch (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-co
re\jasmine.js:4008:28)
    at ReportDispatcher.specDone (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-co
re\lib\jasmine-core\jasmine.js:3979:11)
    at Spec.specResultCallback [as resultCallback] (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_
modules\jasmine-core\lib\jasmine-core\jasmine.js:1062:18)
    at QueueRunner.complete [as onComplete] (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules
\jasmine-core\lib\jasmine-core\jasmine.js:482:12)
    at Immediate.<anonymous> (C:\Users\DucenIT1\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\l
ib\jasmine-core\jasmine.js:3893:12)
[12:01:26] E/launcher - Process exited with error code 199
```

Thanks in Advance

**Comment by wswebcreation** [comment]
Hi @Sabesna 

Is this still valid? What I think is strange that it works on the example project and not with your app. Do you see the IE browser window coming up?

**Comment by wswebcreation** [comment]
Going to close this now because it's inactive for a few weeks now
