### ISSUE TITLE
SyntaxError: Unexpected token import with protractor jasmine framework

### ISSUE THREAD

**Issue by zeeravi13** [angular/protractor#4519]
I am using protractor with jasmine framework but I am running my test through babel. I am getting an import error. Could someone please help to resolve it?

command to run my test: 
`babel-node node_modules/protractor/bin/protractor test/protractor.conf.js`

**Error I am getting:**
```
 server started at http://10.140.74.71:55729/wd/hub
[16:31:53] E/launcher - Error: /Users/kelaiyr/Documents/webdriveIO/test/e2e/specs/testSignIn.spec.js:1
(function (exports, require, module, __filename, __dirname) { import singIn from '../pages/testfile';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (/Users/kelaiyr/Documents/webdriveIO/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/kelaiyr/Documents/webdriveIO/node_modules/jasmine/lib/jasmine.js:93:5
    at Array.forEach (native)
    at Jasmine.loadSpecs (/Users/kelaiyr/Documents/webdriveIO/node_modules/jasmine/lib/jasmine.js:92:18)
    at Jasmine.execute (/Users/kelaiyr/Documents/webdriveIO/node_modules/jasmine/lib/jasmine.js:197:8)
    at /Users/kelaiyr/Documents/webdriveIO/node_modules/protractor/built/frameworks/jasmine.js:132:15
    at Function.promise (/Users/kelaiyr/Documents/webdriveIO/node_modules/protractor/node_modules/q/q.js:682:9)
    at /Users/kelaiyr/Documents/webdriveIO/node_modules/protractor/built/frameworks/jasmine.js:104:14
    at _fulfilled (/Users/kelaiyr/Documents/webdriveIO/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/kelaiyr/Documents/webdriveIO/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/kelaiyr/Documents/webdriveIO/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/kelaiyr/Documents/webdriveIO/node_modules/protractor/node_modules/q/q.js:604:44
    at runSingle (/Users/kelaiyr/Documents/webdriveIO/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/Users/kelaiyr/Documents/webdriveIO/node_modules/protractor/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    [16:31:54] E/launcher - Process exited with error code 100
```

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

By the way, it looks like you didn't configure it correctly. Babel didn't transpile the `import` here. Please check the docs / forum of Babel to fix it.


Thanks!
