### ISSUE TITLE
Issues with latest Selenium? Timed out waiting for driver server to start

### ISSUE THREAD

**Issue by Jag-MW** [angular/protractor#4529]
Hello,
On Oct 5 morning my tests were working fine and I could run tests with no issues, from the afternoon on the same day I am getting the error below.  I see the Selenium server has a new version and also the drivers.  Is it a known issue?  Any suggestions for a workaround is much appreciated.
Using Protractor: 5.1.2
Node: 6.11
Selenium: 3.60
------
webdriver-manager update && protractor test/e2e/protractor.conf.js -t dev -s local -f chrome_lg

[12:44:40] I/update - geckodriver: unzipping geckodriver-v0.19.0.tar.gz
[12:44:40] I/update - geckodriver: setting permissions to 0755 for /Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.19.0
[12:44:40] I/update - chromedriver: unzipping chromedriver_2.33.zip
[12:44:40] I/update - chromedriver: setting permissions to 0755 for /Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.33
[12:44:45] I/launcher - Running 1 instances of WebDriver
[12:44:45] I/local - Starting selenium standalone server...
[12:44:45] I/local - Selenium standalone server started at http://10.4.8.202:62550/wd/hub
[12:45:06] E/launcher - Timed out waiting for driver server to start.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'Jag-MW.local', ip: 'fe80:0:0:0:d7:76a0:4e13:b897%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_102'
Driver info: driver.version: unknown
[12:45:06] E/launcher - WebDriverError: Timed out waiting for driver server to start.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'Jag-MW.local', ip: 'fe80:0:0:0:d7:76a0:4e13:b897%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_102'
Driver info: driver.version: unknown
    at WebDriverError (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:709:29)
    at createDriver (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/protractor/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/protractor/node_modules/selenium-webdriver/index.js:623:16)
    at Local.getNewDriver (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/protractor/lib/driverProviders/driverProvider.ts:60:29)
    at Runner.createBrowser (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/q/q.js:796:13)
    at /Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/q/q.js:604:44
    at runSingle (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/q/q.js:137:13)
    at flush (/Users/jagannadhavootkur/source/fairhair-web-e2e/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[12:45:06] E/launcher - Process exited with error code 199

**Comment by Jag-MW** [comment]
Perhaps, it is not the right forum? I started seeing the same issue on IE 10 + Windows 7 on Saucelabs tests, not sure whether it is selenium or chrome driver issue or if Protractor needs to release a patch - Any suggestion is much appreciated
internet explorer 11 Windows 7 #31] 
[internet explorer 11 Windows 7 #31] /home/travis/build/*****/node_modules/selenium-webdriver/lib/error.js:27
[internet explorer 11 Windows 7 #31]     super(opt_error);
[internet explorer 11 Windows 7 #31]     ^
[internet explorer 11 Windows 7 #31] WebDriverError: JavaScript error (WARNING: The server did not provide any stacktrace information)
[internet explorer 11 Windows 7 #31] Command duration or timeout: 46 milliseconds
[internet explorer 11 Windows 7 #31] Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
[internet explorer 11 Windows 7 #31] System info: host: 'SAUCE-M5KOC5RP6', ip: '172.20.115.36', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
[internet explorer 11 Windows 7 #31] Driver info: org.openqa.selenium.ie.InternetExplorerDriver
[internet explorer 11 Windows 7 #31] Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=about:blank, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
[internet explorer 11 Windows 7 #31] Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXX573aa6c1
[internet explorer 11 Windows 7 #31]     at WebDriverError (/home/travis/build/*****/node_modules/selenium-webdriver/lib/error.js:27:5)
[internet explorer 11 Windows 7 #31]     at Object.checkLegacyResponse (/home/travis/build/*****/node_modules/selenium-webdriver/lib/error.js:505:15)
[internet explorer 11 Windows 7 #31]     at parseHttpResponse (/home/travis/build/*****/node_modules/selenium-webdriver/lib/http.js:509:13)
[internet explorer 11 Windows 7 #31]     at doSend.then.response (/home/travis/build/*****/node_modules/selenium-webdriver/lib/http.js:440:13)
[internet explorer 11 Windows 7 #31]     at process._tickCallback (internal/process/next_tick.js:109:7)
[internet explorer 11 Windows 7 #31] From: Task: Protractor.get(http://XXXXXXXXXXXXXXXX) - get url
[internet explorer 11 Windows 7 #31]     at WebDriver.schedule (/home/travis/build/*****/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
[internet explorer 11 Windows 7 #31]     at ProtractorBrowser.executeScriptWithDescription (/home/travis/build/*****/node_modules/protractor/lib/browser.ts:584:24)
[internet explorer 11 Windows 7 #31]     at driver.wait (/home/travis/build/*****/node_modules/protractor/lib/browser.ts:898:25)
[internet explorer 11 Windows 7 #31]     at /home/travis/build/*****/node_modules/selenium-webdriver/lib/webdriver.js:947:14
[internet explorer 11 Windows 7 #31]     at TaskQueue.execute_ (/home/travis/build/*****/node_modules/selenium-webdriver/lib/promise.js:2970:14)
[internet explorer 11 Windows 7 #31]     at TaskQueue.executeNext_ (/home/travis/build/*****/node_modules/selenium-webdriver/lib/promise.js:2953:27)
[internet explorer 11 Windows 7 #31]     at asyncRun (/home/travis/build/*****/node_modules/selenium-webdriver/lib/promise.js:2860:25)
[internet explorer 11 Windows 7 #31]     at /home/travis/build/*****/node_modules/selenium-webdriver/lib/promise.js:676:7
[internet explorer 11 Windows 7 #31]     at process._tickCallback (internal/process/next_tick.js:109:7)
