### ISSUE TITLE
Error when running tests with Internet Explorer

### ISSUE THREAD

**Issue by woahitsjc** [angular/protractor#4534]
- Node Version: `8.4.0`
- Protractor Version: `5.1.2`
- Browser(s): `Internet Explorer`
- Operating System and Version `Windows 10`
- Your protractor configuration file

```// An example configuration file.
exports.config = {

  seleniumAddress: 'http://localhost:4444/wd/hub',

  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'internet explorer'
  },

  // Framework to use. Jasmine is recommended.
  framework: 'jasmine',

  // Spec patterns are relative to the current working directory when
  // protractor is called.
  specs: ['loginProt.js'],
};
```

- A relevant example test

```
describe('Selenium Test Case', function() {
  it('should execute test case without errors', function() {
    var text, value, bool, source, url, title;
    var TestVars = {};
    browser.waitForAngularEnabled(false);
    browser.get("https://uat.backgroundchecking.com/app");
    element(by.css("#Email")).click();
    element(by.css("#Email")).sendKeys(username);
    element(by.css("#Password")).sendKeys(password);
    element(by.css("input[type=\"submit\"]")).click();
    text = element(by.css("#content > h2")).getText();
      expect(text).toContain("" + "Administrator Home Page");
  });
});
```

- Output from running the test

```[11:57:03] I/launcher - Running 1 instances of WebDriver
[11:57:03] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[11:57:06] E/runner - Unable to start a WebDriver session.
[11:57:06] E/launcher - Error: WebDriverError: Invalid timeout type specified: ms
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'NOJCW540', ip: '192.168.42.72', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (C:\ProgramData\nvm\v8.4.0\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:505:15)
    at parseHttpResponse (C:\ProgramData\nvm\v8.4.0\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\ProgramData\nvm\v8.4.0\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:440:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.manage().timeouts().setScriptTimeout(11000)
    at WebDriver.schedule (C:\ProgramData\nvm\v8.4.0\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:816:17)
    at Timeouts._scheduleCommand (C:\ProgramData\nvm\v8.4.0\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:1500:25)
    at Timeouts.setScriptTimeout (C:\ProgramData\nvm\v8.4.0\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:1483:17)
    at browser_.ready.browser_.ready.then.then (C:\ProgramData\nvm\v8.4.0\node_modules\protractor\lib\runner.ts:281:49)
    at ManagedPromise.invokeCallback_ (C:\ProgramData\nvm\v8.4.0\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1366:14)
    at TaskQueue.execute_ (C:\ProgramData\nvm\v8.4.0\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (C:\ProgramData\nvm\v8.4.0\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (C:\ProgramData\nvm\v8.4.0\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2813:27)
    at C:\ProgramData\nvm\v8.4.0\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
    at <anonymous>
[11:57:06] E/launcher - Process exited with error code 100
```

- Steps to reproduce the bug

`webdriver-manager update`
`webdriver - manager start`
`protractor conf.js`

**Comment by wswebcreation** [comment]
Hi @woahisjc

I've seen this issue before. It's filled here https://github.com/angular/protractor/issues/4445

Please read through the comments on how to "fix" the version so you have a "workaround". I hope it helps you

I'm going to close it for now so we track only one issue.
