### ISSUE TITLE
fail: Error: expecting exit code: 0, actual: 100

### ISSUE THREAD

**Issue by muthucse7** [angular/protractor#4541]
Hi All,

I'm new to the Protractor framework. When I am trying to run the test script am getting the below error message. Can anyone assist??? 

>>> fail: Error: expecting exit code: 0, actual: 100
running: node built/cli.js spec/built/noCFPluginConf.js
........(node:12472) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[23:04:07] I/launcher - Running 1 instances of WebDriver
[23:04:07] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[23:04:08] E/runner - Unable to start a WebDriver session.
(node:12472) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
(node:12472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[23:04:08] E/launcher - Error: Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
    at ClientRequest.<anonymous> (C:\protractor\protractorSample\node_modules\selenium-webdriver\http\index.js:238:15)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[23:04:08] E/launcher - Process exited with error code 100

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
