### ISSUE TITLE
Protractor bug report  - q library

### ISSUE THREAD

**Issue by ORESoftware** [angular/protractor#4573]
Bug report
---

- Node Version: ``
- Protractor Version: ``
- Angular Version: ``
- Browser(s): ``
- Operating System and Version ``
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

error:

```console

/Users/alexamil/.nvm/versions/node/v6.10.2/lib/node_modules/protractor/node_modules/q/q.js:155
                throw e;
                ^

TypeError: Cannot read property 'length' of undefined
    at Function.getSpecs (/Users/alexamil/.nvm/versions/node/v6.10.2/lib/node_modules/protractor/built/configParser.js:88:25)
    at new TaskScheduler (/Users/alexamil/.nvm/versions/node/v6.10.2/lib/node_modules/protractor/built/taskScheduler.js:34:100)
    at helper.runFilenameOrFn_.then.then.then (/Users/alexamil/.nvm/versions/node/v6.10.2/lib/node_modules/protractor/built/launcher.js:175:25)
    at _fulfilled (/Users/alexamil/.nvm/versions/node/v6.10.2/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/alexamil/.nvm/versions/node/v6.10.2/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/alexamil/.nvm/versions/node/v6.10.2/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/alexamil/.nvm/versions/node/v6.10.2/lib/node_modules/protractor/node_modules/q/q.js:604:44
    at runSingle (/Users/alexamil/.nvm/versions/node/v6.10.2/lib/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/Users/alexamil/.nvm/versions/node/v6.10.2/lib/node_modules/protractor/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
```

the error was generated by this script:

```bash
#!/usr/bin/env bash
search_dir="$(dirname "$0")";
project_root="${SUMAN_PROJECT_ROOT:-$(cd $(npm root) && cd .. && pwd)}"
export PROTRACTOR_TEST_PATHS=$(find ${search_dir} -name '*spec.js')
protractor "${project_root}/protractor.conf.js"
```

**Comment by ORESoftware** [comment]
This has to do with find returning a newline delimited string, so I put this in protractor.conf.js

```
let testPaths;
if(process.env.PROTRACTOR_TEST_PATHS){
  testPaths = String(process.env.PROTRACTOR_TEST_PATHS).split(/\s/g).map(function(s){
    return String(s).trim()
  })
  .filter(v => v);
}

...

specs : testPaths || []
```

now it works, but you should try to fix the bug anyway though?
