### ISSUE TITLE
Node 8.9.0 causes browser.pause() to error

### ISSUE THREAD

**Issue by millerick** [angular/protractor#4574]
Bug report
---

- Node Version: `8.9.0`
- Protractor Version: `5.2.0`
- Angular Version: `1.5.10`
- Browser(s): `chrome`
- Operating System and Version `OSX 10.12.6`
- Output from running the test
```
[17:25:16] I/protractor -
module.js:538
    throw err;
    ^

Error: Cannot find module '_debugger'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/lending/test/e2e/node_modules/protractor/built/debugger/debuggerCommons.js:1:82)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```
- Steps to reproduce the bug
  - Take an existing test and add `browser.pause()` within the test.
  - Observe the error message seen above while the test otherwise functions normally.

**Comment by wswebcreation** [comment]
Closing because double https://github.com/angular/protractor/issues/4307
