### ISSUE TITLE
Error while waiting for Protractor to sync with the page: "window.angular is undefined.

### ISSUE THREAD

**Issue by premiumwd** [angular/protractor#4611]
- Node Version: `6.11.1`
- Protractor Version: `5.1.2`
- Angular Version: `4.1.3`
- Browser(s): `Chrome`
- Operating System and Version `Windows 10 64-bit`
- Your protractor configuration file
```
// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

const { SpecReporter } = require('jasmine-spec-reporter');

exports.config = {
  rootElement: 'app',
  allScriptsTimeout: 11000,
  specs: [
    './e2e/**/*.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/#/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  onPrepare() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });

    return browser.getCapabilities().then(function(caps){
      const trx = require('jasmine-trx-reporter');

      var jasmineTrxConfig = {
        reportName: 'Protractor Test Suite',
        folder: '',
        outputFile: 'protractor.trx',
        groupSuitesIntoSingleFile: true
      }
      
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
    jasmine.getEnv().addReporter(new trx(jasmineTrxConfig));
    
    })}
};
```
- A relevant example test
```
import { browser, element, by } from 'protractor';

// MODULES
import { Buttons } from './applications.buttons.e2e-spec';
import { Grid } from './applications.grid.e2e-spec';

export class ApplicationsPage {
	navigateTo() {
		return browser.get('/');
	}
}

describe('Applications Page', () => {
	let page = new ApplicationsPage;
	let buttons = new Buttons;
	let grid = new Grid;

	beforeEach(() => {
		page.navigateTo();
	});

	it('should be able to navigate to applications page', () => {
		expect(browser.getTitle()).toEqual('App Manager - Applications');
	})
});
```

- Output from running the test
```
Applications Page
    × should be able to navigate to applications page
      - Error: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
          at runWaitForAngularScript.then (C:\Users\ChrisR\Source\Repos\App Manager\node_modules\protractor\lib\browser.ts:653:19)
          at ManagedPromise.invokeCallback_ (C:\Users\ChrisR\Source\Repos\App Manager\node_modules\selenium-webdriver\lib\promise.js:1366:14)
          at TaskQueue.execute_ (C:\Users\ChrisR\Source\Repos\App Manager\node_modules\selenium-webdriver\lib\promise.js:2970:14)
          at TaskQueue.executeNext_ (C:\Users\ChrisR\Source\Repos\App Manager\node_modules\selenium-webdriver\lib\promise.js:2953:27)
          at asyncRun (C:\Users\ChrisR\Source\Repos\App Manager\node_modules\selenium-webdriver\lib\promise.js:2813:27)
          at C:\Users\ChrisR\Source\Repos\App Manager\node_modules\selenium-webdriver\lib\promise.js:676:7
          at process._tickCallback (internal/process/next_tick.js:109:7)Error
          at ElementArrayFinder.applyAction_ (C:\Users\ChrisR\Source\Repos\App Manager\node_modules\protractor\lib\element.ts:482:23)
          at ElementArrayFinder.(anonymous function) [as click] (C:\Users\ChrisR\Source\Repos\App Manager\node_modules\protractor\lib\element.ts:96:21)
          at ElementFinder.(anonymous function) [as click] (C:\Users\ChrisR\Source\Repos\App Manager\node_modules\protractor\lib\element.ts:873:14)
          at Form.click (C:\Users\ChrisR\Source\Repos\App Manager\e2e\form\form.form.e2e-spec.ts:64:37)
          at Suite.<anonymous> (C:\Users\ChrisR\Source\Repos\App Manager\e2e\form\form.e2e-spec.ts:53:9)
          at Suite.<anonymous> (C:\Users\ChrisR\Source\Repos\App Manager\e2e\form\form.e2e-spec.ts:52:3)
          at Suite.<anonymous> (C:\Users\ChrisR\Source\Repos\App Manager\e2e\form\form.e2e-spec.ts:30:2)
      - Failed: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)
```

**Comment by Xotabu4** [comment]
@premiumwd Hi!

I might be that your app - `'http://localhost:4200/#/'` is not started actually, or application is not angular. Can you check what actually happens in browser and see if app is angular?

**Comment by premiumwd** [comment]
@Xotabu4  Application is actually angular cli as stated in ticket. So it is angular.

**Comment by premiumwd** [comment]
Issue:

rootelement: needs to be set in protractor.config to correct.
