### ISSUE TITLE
Not able to run command " sudo webdriver-manager update"

### ISSUE THREAD

**Issue by grvgb** [angular/protractor#4621]
Hi there!
I am getting this issue while running command "webdriver-manager update", the output on console is:
/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cli/logger.js:67
    info(...msgs) {
         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/built/lib/cli/index.js:9:10)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
---------------------------------------------------------------------------------------------------
I am new to protractor and really need help.

Bug report
---

- Node Version: ``
- Protractor Version: ``
- Angular Version: ``
- Browser(s): ``
- Operating System and Version ``
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by grvgb** [comment]
Issue got fixed just by updating node js version previously I was using V4.*.* then I updated to V9.2.0.
It worked
