### ISSUE TITLE
Dynamically changing USE_PROMISE_MANAGER fails with protractor

### ISSUE THREAD

**Issue by kenborge** [angular/protractor#4630]
Bug report
---
Selenium has a webdriver documention for how to start migrating towards using async/await as the promise manager is getting remove in the future. https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs
With large code bases it is very hard to rewrite all tests to the new flow at the same time. 
They outline multiple options for how to migrate where one being where **Option 3: Migrate to async/await** seems to be the most future proof. 

They show an example of how to start partially migrating your codebase to the new async flow by changing the USE_PROMISE_MANAGER variable in before and after function. But it does not seem like this works with protractor. I tried creating a brand new project from ```ng new``` and modified it to use the suggested method.

```javascript
promise.USE_PROMISE_MANAGER = false;

function legacySuite(name, fn) {
  describe(name, function() {
    before(() => promise.USE_PROMISE_MANAGER = true);
    after(() => promise.USE_PROMISE_MANAGER = false);

    fn();
  });
}

describe('Example', function() {
  legacySuite('legacy tests', function() {
    test.it('test 1', function() {
      // ...
    });
  });

  it('test 2', async function() {
    // ...
  });
});
```

### Information:
- Node Version: `8.9.2`
- Protractor Version: `5.2.2`
- Angular Version: `5.1.0`
- Browser(s): `chrome`
- Operating System and Version `MacOS Sierra 10.12.2`

- Your protractor configuration file
```javascript
// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

const { SpecReporter } = require('jasmine-spec-reporter');

exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    './e2e/**/*.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  onPrepare() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
  },
  SELENIUM_PROMISE_MANAGER: false
};

```
- A relevant example test
```typescript
import { browser, protractor, promise } from 'protractor';
describe('angular2-test App', () => {

    function legacySuite(name, fn) {
        describe(name, function () {
            beforeEach(() => protractor.promise.USE_PROMISE_MANAGER = true);
            beforeEach(() => protractor.promise.USE_PROMISE_MANAGER = false);

            fn();
        });
    }

    legacySuite('legacyTests', function () {
        it('should display welcome message', () => {
            browser.get('/');
        });
    });
});
```
- Output from running the test
```
(node:4630) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error while waiting for Protractor to sync with the page: "both angularJS testability and angular testability are undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
(node:4630) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The test passes regardless of what you write in the expect and it outputs the error above.

I also tried to do the inverse, not setting SELENIUM_PROMISE_MANAGER to false in the config file and instead doing protractor.promise.USE_PROMISE_MANAGER = false in the beforeEach for tests that are migrated to async.
Then protractor just hangs and  after the jasmine timeout gives the following error:
```
Error: TypeError: Unable to create a managed promise instance: the promise manager has been disabled by the SELENIUM_PROMISE_MANAGER environment variable: undefined
    at new ManagedPromise (/Users/kenborge/Code/angular2-test/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1030:13)
    at new Deferred (/Users/kenborge/Code/angular2-test/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1454:20)
    at new Task (/Users/kenborge/Code/angular2-test/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2778:5)
    at ManagedPromise.addCallback_ (/Users/kenborge/Code/angular2-test/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1335:14)
    at ManagedPromise.then (/Users/kenborge/Code/angular2-test/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1290:17)
    at Direct.quitDriver (/Users/kenborge/Code/angular2-test/node_modules/protractor/built/driverProviders/driverProvider.js:73:18)
    at selenium_webdriver_1.promise.all.drivers.map (/Users/kenborge/Code/angular2-test/node_modules/protractor/built/driverProviders/driverProvider.js:90:29)
    at Array.map (<anonymous>)
    at Function.quitDrivers (/Users/kenborge/Code/angular2-test/node_modules/protractor/built/driverProviders/driverProvider.js:89:26)
    at Direct.teardownEnv (/Users/kenborge/Code/angular2-test/node_modules/protractor/built/driverProviders/driverProvider.js:127:31)
    at driverprovider_.updateJob.then (/Users/kenborge/Code/angular2-test/node_modules/protractor/built/runner.js:423:49)
    at _fulfilled (/Users/kenborge/Code/angular2-test/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/kenborge/Code/angular2-test/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/kenborge/Code/angular2-test/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/kenborge/Code/angular2-test/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/Users/kenborge/Code/angular2-test/node_modules/protractor/node_modules/q/q.js:137:13)
```

**Comment by wswebcreation** [comment]
Hi @kenborge ,

This won't be supported by Protractor in the future because it will cost a lot of time and code to implement this. Because it's a temp solution it would be unwise to do it.

Advice is to use multiple configuration files, 1 in which you enable and 2 in which you disable it and specify the upgraded files to it.

@qiyigg , what's your opinion on this? If you agree can we close this issue?

**Comment by qiyigg** [comment]
@wswebcreation  Agree, I think we could close this issue right now.
