### ISSUE TITLE
Bad error message when using EC.stalenessoff

### ISSUE THREAD

**Issue by edi9999** [angular/protractor#4636]
Bug report
---

- Node Version: `8.8.1`
- Protractor Version: `5.2.2`
- Angular Version: `1.5.9`
- Browser(s): `Chrome --headless`
- Operating System and Version `Linux x86_64 / Fedora`
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

When I run 

    browser.wait(EC.stalenessOf(element(by.cssContainingText('a', undefined))), minute);

I get following error : 

```
Failure: Failed: unknown error: Cannot read property 'indexOf' of null
  (Session info: headless chrome=62.0.3202.75)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.14.5-300.fc27.x86_64 x86_64)
WebDriverError: unknown error: Cannot read property 'indexOf' of null
  (Session info: headless chrome=62.0.3202.75)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.14.5-300.fc27.x86_64 x86_64)
    at Object.checkLegacyResponse (/root/.npm-global/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/root/.npm-global/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/root/.npm-global/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

On version 5.2.0, this test passes.

I would expect to have an error here, since the selector is incorrect. But I would prefer to have a clear error message . This `Cannot read property 'indedOf' of null` made things complex to understand.

**Comment by alexdelude** [comment]
I'm getting this same error as well. Does anyone have a fix or workaround?

**Comment by edi9999** [comment]
It means that you have a type issue in your code somewhere (probably something is undefined but should be a  string ?)
