### ISSUE TITLE
Error 199 when trying to run e2e from JHipster

### ISSUE THREAD

**Issue by alvinlzg** [angular/protractor#4640]
Hi, 
I'm new to Protractor. I am following tutorial from JHipster from [here](http://gist.asciidoctor.org/?github-mraible/jhipster4-demo//README.adoc) 

I got stuck when i tried to run e2e based on the tutorial. I've tried to search everywhere but could not find anything. I've also tried to downgrade webdriver to 2.29 from 2.34, and then reverted to 2.34 again. No luck.

I did not change any of the default config file. My protractor.conf.js is still showing

```
   capabilities: {
        'browserName': 'chrome',
        'phantomjs.binary.path': require('phantomjs-prebuilt').path,
        'phantomjs.ghostdriver.cli.args': ['--loglevel=DEBUG']
    },

```
```
yarn e2e
yarn run v1.3.2
$ protractor src/test/javascript/protractor.conf.js
[13:40:19] W/configParser - pattern ./e2e/entities/*.spec.ts did not match any files.
[13:40:19] I/launcher - Running 1 instances of WebDriver
[13:40:19] I/direct - Using ChromeDriver directly...
[13:40:19] E/launcher - session not created exception
from disconnected: unable to connect to renderer
  (Session info: headless chrome=63.0.3239.108)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.13.2 x86_64)
[13:40:19] E/launcher - SessionNotCreatedError: session not created exception
from disconnected: unable to connect to renderer
  (Session info: headless chrome=63.0.3239.108)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.13.2 x86_64)
    at WebDriverError (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/selenium-webdriver/lib/error.js:27:5)
    at SessionNotCreatedError (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/selenium-webdriver/lib/error.js:214:5)
    at Object.checkLegacyResponse (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/selenium-webdriver/chrome.js:709:29)
    at Direct.getNewDriver (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/protractor/lib/driverProviders/direct.ts:90:25)
    at Runner.createBrowser (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/Users/alvinlzg/Documents/dev-personal/jhipster/blog/node_modules/protractor/node_modules/q/q.js:137:13)
[13:40:19] E/launcher - Process exited with error code 199
error Command failed with exit code 199.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any help is much appreciated. Thanks!

**Comment by MichaelRijsdijk** [comment]
It says that "pattern ./e2e/entities/*.spec.ts did not match any files."

If you check in your folder:
src/test/javascript/e2e/entities/

Are there any .spec.ts files? If so, is your config file located in folder:

src/test/javascript/

**Comment by alvinlzg** [comment]
yeap, in my src/test/javascript/e2e/entities, i have .spec.ts files for blog, entry and tag. 
in my src/test/javascript folder, i have karma.conf.js and protractor.conf.js

i've committed everything to a public repo - https://github.com/alvinlzg/blog

Please take a look. Thanks so much in advance.

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
