### ISSUE TITLE
events.js:163 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by rsmodake** [angular/protractor#4659]
- Node Version: `v7.10.0`
- Protractor Version: `5.2.2`
- Angular Version: ``
- Browser(s): ``
- Operating System and Version `Linux development 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Hi All,

I have installed protractor on my machine. When I fire below command,
webdriver-manager update
I get below error,

events.js:163
throw er; // Unhandled 'error' event
^

Error: tunneling socket could not be established, statusCode=407
at ClientRequest.onConnect (/usr/local/lib/node_modules/protractor/node_modules/tunnel-agent/index.js:166:19)
at Object.onceWrapper (events.js:293:19)
at emitThree (events.js:116:13)
at ClientRequest.emit (events.js:197:7)
at Socket.socketOnData (_http_client.js:443:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:191:7)
at readableAddChunk (_stream_readable.js:178:18)
at Socket.Readable.push (_stream_readable.js:136:10)
at TCP.onread (net.js:561:20)

I am using node version V7.10.0

Please help me to resolve the issue. My colleague is having same version, but he is not facing any issues.

**Comment by wswebcreation** [comment]
Hi @rsmodake 

Are you behind a proxy? Because the error implies it? If so you need to verify what your colleague did on his machine to get this working.

**Comment by postmeback** [comment]
I am also having the same kind of error....can anybody help ?

![image](https://user-images.githubusercontent.com/14862687/37643516-cb8c74fe-2c46-11e8-8c44-ae0963641657.png)
