### ISSUE TITLE
Protractor fails to run on Linux with Chrome 64.0

### ISSUE THREAD

**Issue by lizardeye** [angular/protractor#4696]
Protractor fails to run on a linux server with Chrome 64.0. Works fine on local Windows machine with the same Chrome version.

$google-chrome --version
Google Chrome 64.0.3282.140

$ npm -v
5.6.0

package.json defines the following versions:

```
  "devDependencies": {
     "protractor": "^5.3.0",
    "protractor-beautiful-reporter": "^1.1.1",
    "webdriver-manager": "^12.0.6",
  }

```

My protractor.conf,js

```
exports.config = {
  seleniumServerJar: './node_modules/webdriver-manager/selenium/selenium-server-standalone-3.9.0.jar',
   
  // Capabilities to be passed to the webdriver instance.
  capabilities: {
	browserName: 'chrome',
	chromeOptions:{
		args: ['--no-sandbox']
	}
  }
}
```

tried both with and without --no-sandbox option

As a result:

```
System info: host: 'myjenkins.host.ru', ip: '192.168.15.208', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-693.11.6.el7.x86_64', java.version: '1.8.0_152'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (/opt/jenkins/workspace/SBERNAL/SBERNAL-develop-deploy/Apps/gui/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/opt/jenkins/workspace/SBERNAL/SBERNAL-develop-deploy/Apps/gui/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/opt/jenkins/workspace/SBERNAL/SBERNAL-develop-deploy/Apps/gui/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/opt/jenkins/workspace/SBERNAL/SBERNAL-develop-deploy/Apps/gui/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/opt/jenkins/workspace/SBERNAL/SBERNAL-develop-deploy/Apps/gui/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (/opt/jenkins/workspace/SBERNAL/SBERNAL-develop-deploy/Apps/gui/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/opt/jenkins/workspace/SBERNAL/SBERNAL-develop-deploy/Apps/gui/node_modules/selenium-webdriver/index.js:626:16)
    at Local.getNewDriver (/opt/jenkins/workspace/SBERNAL/SBERNAL-develop-deploy/Apps/gui/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/opt/jenkins/workspace/SBERNAL/SBERNAL-develop-deploy/Apps/gui/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/opt/jenkins/workspace/SBERNAL/SBERNAL-develop-deploy/Apps/gui/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/opt/jenkins/workspace/SBERNAL/SBERNAL-develop-deploy/Apps/gui/node_modules/q/q.js:834:54)
```

**Comment by stefan-u-sevenval** [comment]
Experiencing the same Problem.
Protractor starts Chrome and goes to the correct route, however it does not interact with the app meaning no clicking or typing. Therefore, the test time out.

MacOS 10.13.3
Chrome 64.0.3282.167
WebDriver 3.0.8
Chromedriver 2.35
Protractor 5.3.0

**Comment by lizardeye** [comment]
My case turned out to be a Jenkins issue. Installing plugin https://wiki.jenkins.io/display/JENKINS/Xvfb+Plugin and Xvfb server (https://corpocrat.com/2008/08/19/how-to-install-xvfb-x11-server-in-linux-server/) solved the problem
