### ISSUE TITLE
Unable To Do Testing With Firefox Using Protractor 5.20 Onward When Proxy Configuration Is Specified

### ISSUE THREAD

**Issue by bhreinb** [angular/protractor#4707]
- Node Version: `8.4.0`
- Protractor Version: `5.3.0`
- Angular Version: `1.5.11`
- Browser(s): `Firefox59`
- Operating System and Version `Linux Centos7`
- A relevant example test
"proxy": {
	  proxyType: 'manual',
          httpProxy: '127.0.0.1:3128',
          sslProxy: '127.0.0.1:3128',
         ftpProxy: '127.0.0.1:3128',
}

Hi there,

Protractor 5.2.0 updated the dependency of the selenium-webdriver library to 3.6.0 (see change log here @ https://github.com/angular/protractor/blob/master/CHANGELOG.md). Given that dependency (namely selenium edition 3.6.0) that leaves me to use either geckoversion (v0.19.0 or v0.19.1 see https://github.com/mozilla/geckodriver/releases). 

```
Note that with geckodriver v0.19.0 the following versions are recommended:

Firefox 55.0 (and greater)
Selenium 3.5 (and greater)
```

Unfortunately geckoversion v0.19.0 changed how it handled proxy configuration and it was a breaking change. However, selenium-webdriver 3.6.0 doesn't have that fix but Selenium3.7.1 does have it

`
https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.7.1
https://github.com/seleniumhq/selenium/commit/81334994d9fdb3460fd6078cdfadb520e6a554ba
`

so I need protractor dependency updated to a later edition of selenium-webdriver than 3.6.0 because I'm unable to do any testing with Firefox 55 onward whenever I have to go through a proxy. I created an issue in geckodriver github repository here 

`https://github.com/mozilla/geckodriver/issues/1174`

but this was closed as this was identified as a protractor issue albeit from digging myself it seems protractor is using an old selenium-webdriver dependency. Thoughts?

**Comment by bhreinb** [comment]
Hi

is their any update on the above issue? This is very much still an issue for me unfortunately.

**Comment by rochan** [comment]
@bhreinb Try to change the proxyType value to 'MANUAL'

**Comment by prashanthparsi** [comment]
I am also having the same issue when trying to run my tests from docker container with firefox headless. I get the below error and tests are failing. How do I move forward?
   [32m✔ Before[39m # [90mtest/cucumber/stepDefinitions/hooks.ts:26[39m
       [31mUnexpectedAlertOpenError: Dismissed user prompt dialog: The proxy moz-proxy://<<hiding the proxy here>>:8181 is requesting a username and password. The site says: “ESDMZ”: [39m
       [31mBuild info: version: '4.0.0-alpha-1', revision: 'd1d3728cae', time: '2019-04-24T16:15:24'[39m
       [31mSystem info: host: 'd5b164780a26', ip: 'Unknown', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.162-94.72-default', java.version: '1.8.0_212'[39m
       [31mDriver info: driver.version: unknown[39m[90m[39m
       [90m    at Object.checkLegacyResponse (/usr/local/automation/node_modules/selenium-webdriver/lib/error.js:553:13)[39m
       [90m    at parseHttpResponse (/usr/local/automation/node_modules/selenium-webdriver/lib/http.js:509:13)[39m
       [90m    at doSend.then.response (/usr/local/automation/node_modules/selenium-webdriver/lib/http.js:441:30)[39m
