### ISSUE TITLE
Protractor right click is not working on IE 11, but works in chrome

### ISSUE THREAD

**Issue by poo13** [angular/protractor#4725]
Hi,

I want to right click on employee record so that context menu options get displayed and I need to pick an option from the context menu.

Following is the code snippet which I am using for right click on record:
var myxpath = "//*[text()='" + userID + "']/../*[text()='" + status + "']";
var ele = element(by.xpath(myxpath));
browser.actions().mouseMove(ele).perform();
browser.actions().click(protractor.Button.RIGHT).perform();

This code is working on Chrome browser but while executing the same code on Internet Explorer, right click is not working.

It gives the error as:
 Failed: Wait timed out after 30194ms
  Stack:
    TimeoutError: Wait timed out after 30194ms
        at C:\Users\gs-1614\Documents\SprintThree\yum_auto\node_modules\selenium-webdriver\lib\promise.js:2201:17
        at ManagedPromise.invokeCallback_ (C:\Users\gs-1614\Documents\SprintThree\yum_auto\node_modules\selenium-webdriver\lib\promise.js:1376:14)
        at TaskQueue.execute_ (C:\Users\gs-1614\Documents\SprintThree\yum_auto\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Users\gs-1614\Documents\SprintThree\yum_auto\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at asyncRun (C:\Users\gs-1614\Documents\SprintThree\yum_auto\node_modules\selenium-webdriver\lib\promise.js:2927:27)
        at C:\Users\gs-1614\Documents\SprintThree\yum_auto\node_modules\selenium-webdriver\lib\promise.js:668:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

Conf file:
exports.config = {
	seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
capabilities: {
	  'browserName': 'internet explorer',
}
},

Bug report
- Protractor Version: `3.10.0`
- Browser(s): `Internet Explorer` version: 11
- Operating System and Version `Windows 7`

So please help me out here. I am not able to perform right click so my so many test cases are failling.

**Comment by IgorSasovets** [comment]
Hi @poo13 ! I had the same issue with Firefox browser. Please take a look at [https://github.com/IgorSasovets/protractor-firefox-support](protractor-firefox-support) for possible solution. Test case example you can find in  [https://github.com/IgorSasovets/protractor-firefox-support/blob/master/tests/mouse-events-test.js](mouse-events-test.js) file.
