### ISSUE TITLE
JavaScript Error for Protractor Scripts on IE(Work fine in Chrome)

### ISSUE THREAD

**Issue by munna73** [angular/protractor#4729]
When I run my protractor scripts using IEDriver they fail stating Javascript errorsame script works fine on Chrome.
IEDriverServer_Win32_3.9.0, selenium-server-standalone-3.10.0.jar,Windows 7, IE11
/html/body/app-root/main/div/div/app-rule/div/tabset  - Failed: JavaScript error
          at WebDriverError (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:5)
          at JavascriptError (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:157:5)
          at Object.throwDecodedError (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:514:15)
          at parseHttpResponse (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:519:13)
          at doSend.then.response (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
          at process._tickCallback (internal/process/next_tick.js:109:7)
      From: Task: WebDriver.executeScript()
          at thenableWebDriverProxy.schedule (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
          at thenableWebDriverProxy.executeScript (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:878:16)
          at run (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\built\browser.js:59:33)
          at ProtractorBrowser.to.(anonymous function) [as executeScript] (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\built\browser.js:67:16)
          at utilities.highlightElement (c:\Users\ABC1234\git\udr-automation\udruiautomation\src\utils\utilities.js:59:24)
          at HomePage.navigateToDashBoard (c:\Users\ABC1234\git\udr-automation\udruiautomation\src\pages\HomePage.js:133:9)
          at UserContext.<anonymous> (c:\Users\ABC1234\git\udr-automation\udruiautomation\src\testspec\ListTests.js:106:12)
          at new ManagedPromise (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
          at ControlFlow.promise (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
      From: Task: Run it("Navigate to Conditions Tab,open existing phone list and Delete a record from phone list, Verify record is deleted by reopening the existing list") in control flow
          at ControlFlow.emit (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\events.js:62:21)
          at ControlFlow.shutdown_ (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2674:10)
          at shutdownTask_.MicroTask (C:\Users\ABC1234\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2599:53)

- Node Version: `3.10.10
- Protractor Version: `Version 5.3.0`
- Angular Version: ``
- Browser(s): `IE11`
- Operating System and Version Windows7``
- Your protractor configuration file
let SpecReporter = require('jasmine-spec-reporter').SpecReporter;
var browserLogs = require('protractor-browser-logs');
exports.config = {
    // Capabilities to be passed to the Webdriver instance.
    multiCapabilities: [
 
  /*   {
            browserName: 'chrome'
            //To run Headless test
            // 'chromeOptions': { 'args': ['no-sandbox', 'headless', 'disable-gpu'] }
        //      ,shardTestFiles: true,
         //  maxInstances:4 

        }, */
              {
              browserName: 'internet explorer',
              ensureCleanSession:'true',
              ignoreProtectedModeSettings: 'true',
          
              platform: 'ANY'
          },

    ],
    /*     capabilities: {
            loggingPrefs: {
                browser: 'ALL' // "OFF", "SEVERE", "WARNING", "INFO", "CONFIG", "FINE", "FINER", "FINEST", "ALL". 
            }
        }, */
    "scripts": {
        "test": "protractor --suite=smoke config.js --params.env.execenv=dev",
        "test": "protractor --suite=regression config.js --params.env.execenv=dev"

    },
    params: {
        env: {
            execenv: 'default'
        }
    },

    framework: 'jasmine2',
   seleniumAddress: 'http://1.15.6.7:4444/wd/hub',

    suites: {
        regother: '../src/testspec/RegressionTest.js',

    },

    // Options to be passed to Jasmine.
    jasmineNodeOpts: {
        showColors: true,
        silent: true,
        defaultTimeoutInterval: 60000,
        print: function () { }

    },
    onPrepare: function () {
        // If the application has a mix of angular and JS , below property is needed.
        browser.ignoreSynchronization = true;
        // Override the timeout for webdriver.
        browser.driver.manage().timeouts().implicitlyWait(30000);
        //Maximize window
        browser.driver.manage().window().maximize();

        //Using  Jasmine2 for HTML Reports
        var Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');
        jasmine.getEnv().addReporter(new Jasmine2HtmlReporter({
            fileName: 'UDRTestAutomationReport',
            savePath: '../reports/testreports',
            screenshotsFolder: 'images',
            takeScreenshots: true,
            takeScreenshotsOnlyOnFailures: false,
            screenshotOnExpectFailure: true,
            screenshotOnSpecFailure: true,
            clearFoldersBeforeTest: true,
            consolidateAll: true
        }));

        //Using  Jasmine2 for XML Output
        var jasmineReporters = require('jasmine-reporters');
        jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
            consolidateAll: true,
            savePath: '../reports/testresults',
            filePrefix: 'xmloutput'
        }));

        //Jasmins Spec reporter
        jasmine.getEnv().addReporter(new SpecReporter({
            spec: {
                displayStacktrace: true

            }, summary: {

                displayDuration: true

            }

        }));

        //Browser Logs Code

        logs = browserLogs(browser);

        /*    if  (global.logs)  {
               throw  new  Error('Oops, name is already reserved!');
           }
           global.logs  =  logs; */

        beforeEach(function () {
            logs.reset();
            logs = browserLogs(browser);
            logs.ignore(logs.DEBUG);
            logs.ignore(logs.INFO);
            logs.ignore(logs.WARNING);
            console.log("****************************************************************************************************************************************************************");
        });

        afterEach(function () {
            // return logs.verify();
        });

    }

};

**Comment by ChandraGowda** [comment]
@munna73 did you get solution for this, if so can you please share it here.

**Comment by sivachandran1982** [comment]
I am also facing the similar issue. My Script is working fine in firefox. But In IE, its launching the browser but it is stuck after that. Getting Webdrivererror : JavaScript error. 
Using Standalone - 2.53 & IE driver -3. It works perfect in Firefox.
Any one pls help on this ?
