### ISSUE TITLE
Unhandled Inspector Error: {"code":-32000,"message":"Cannot find context with specified id"}

### ISSUE THREAD

**Issue by kemsky** [angular/protractor#4751]
All chrome driver versions above 2.33 are working unstable, Chrome 65 no longer works with 2.33 so we run out of workarounds.

The following code randomly fails with unhandled error:
```typescript
        await browser.switchTo().frame(iframeElement);
        //randomly fails on this line: Spa_Source\tests\e2e\automation.ts:203:23
        await browser.wait(() => element(by.cssContainingText('div.trv-error-message', 'Done.')).isPresent(), defaultTimeout);
        await Automation.sleep(300);
```

Error stacktrace (this is error for 2.36 version, but latest versions fails with the same error):
```
[report #0 should render] Failed: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot find context with specified id"}
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36.540470 (e522d04694c7ebea4ba8821272dbef4f9b818c91),platform=Windows NT 6.3.9600 x86_64)
[17:09:31]	[report #0 should render] WebDriverError: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot find context with specified id"}
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36.540470 (e522d04694c7ebea4ba8821272dbef4f9b818c91),platform=Windows NT 6.3.9600 x86_64)
    at Object.checkLegacyResponse (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.executeScript()
    at Driver.schedule (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at Driver.executeScript (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\webdriver.js:878:16)
    at C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\by.js:191:35
    at call (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\webdriver.js:1068:28)
    at C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\webdriver.js:907:19
    at ManagedPromise.invokeCallback_ (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:668:7
From: Task: WebDriver.call(function)
    at Driver.call (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\webdriver.js:901:23)
    at Driver.findElementsInternal_ (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\webdriver.js:1068:17)
    at Driver.findElements (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\webdriver.js:1043:19)
    at Object.findElementsOverride (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\protractor\built\locators.js:384:31)
    at ptor.waitForAngular.then (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\protractor\built\element.js:156:40)
    at ManagedPromise.invokeCallback_ (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:668:7
From: Task: <anonymous>
    at Timeout.pollCondition [as _onTimeout] (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:2195:19)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
From: Task: <anonymous wait>
    at scheduleWait (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:2188:20)
    at ControlFlow.wait (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:2517:12)
    at Driver.wait (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\webdriver.js:934:29)
    at run (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\protractor\built\browser.js:59:33)
    at ProtractorBrowser.to.(anonymous function) [as wait] (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\protractor\built\browser.js:67:16)
    at Function.<anonymous> (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\Spa_Source\tests\e2e\automation.ts:203:23)
    at step (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\tslib\tslib.js:133:27)
    at Object.next (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\tslib\tslib.js:114:57)
    at fulfilled (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
From: Task: Run it("report #0 should render") in control flow
    at UserContext.<anonymous> (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
    at C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4264:13
    at C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4172:9
    at C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\jasminewd2\index.js:64:48
    at ControlFlow.emit (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\events.js:62:21)
    at ControlFlow.shutdown_ (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:2674:10)
    at shutdownTask_.MicroTask (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\selenium-webdriver\lib\promise.js:2599:53)
From asynchronous test: 
Error
    at _loop_1 (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\Spa_Source\tests\e2e\protractor.e2e.ts:99:9)
    at Suite.<anonymous> (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\Spa_Test\test_coverage\maps\tests\e2e\protractor.e2e.js:117:9)
    at addSpecsToSuite (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (C:\TeamCity\buildAgent\work\b25ee0c8828aa591\_______________.Web\Spa_Source\tests\e2e\protractor.e2e.ts:71:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
```

Protractor config file:
```typescript
import {build} from './build';
import {browser, Config} from 'protractor';
import * as fs from 'fs';

// abstract writing screen shot to a file
function writeScreenShot(data, filename)
{
    const stream = fs.createWriteStream(filename);
    stream.write(new Buffer(data, 'base64'));
    stream.end();
}

//max time 3 minutes
const timeout:number = 2 * 60 * 1000;

const headless = false;

const chrome = {
    'browserName': 'chrome',
    chromeOptions: {
        args: headless ? ['--headless', '--disable-gpu', '--window-size=1920,1080'] : []
    }
};

export const config:Config = {
    baseUrl          : 'http://' + build.host + ':' + build.port + '/',
    specs            : [build.resolvePath(build.config.coverage.dir, 'maps', 'tests/**/*.e2e.js')],
    directConnect    : true,
    exclude          : [],
    multiCapabilities: [chrome],
    allScriptsTimeout: timeout,  //waiting for asynchronous Angular tasks to finish
    getPageTimeout   : timeout,  //waiting for Angular on Page Load
    framework        : 'jasmine2',
    jasmineNodeOpts  : {
        isVerbose             : true,
        showColors            : true,
        includeStackTrace     : true,
        defaultTimeoutInterval: timeout //If a spec (an 'it' block) takes longer than the Jasmine timeout for any reason, it will fail.
    },

    //Tells Protractor to wait for any angular2 apps on the page instead of just the one matching `rootEl`.
    useAllAngular2AppRoots: true,

    onPrepare: () =>
    {
        //load custom matchers:
        require(build.resolvePath(build.config.coverage.dir, 'maps', 'setup.spec.js'));

        if(build.teamcity)
        {
            //teamcity reporter plugin:
            const jasmineReporters = require('jasmine-reporters');
            jasmine.getEnv().addReporter(new jasmineReporters.TeamCityReporter());
            console.log('Installed TeamCity reporter');
        }

        console.log('port', build.port);
        console.log('host', build.host);

        jasmine.getEnv().addReporter({
            specDone: result =>
            {
                const passed = result.failedExpectations.length === 0;

                if(!passed)
                {
                    browser.takeScreenshot().then(png =>
                    {
                        const dir = 'C:/Protractor/Screenshots/' + build.buildNumber;
                        build.mkdir(dir);
                        const filename = build.resolvePath(dir, result.description.replace(/\s+/g, '_') + '.png');
                        writeScreenShot(png, filename);
                        console.log(`##teamcity[message text='${'screenshot: ' + filename}']`);
                    });
                }
            }
        });
    }
};
```
Bug report
---

- Node Version: `v9.2.0`
- Protractor Version: `5.3.0`
- Angular Version: `6.0.0-rc.0`
- Browser(s): `Chrome 65`
- Operating System and Version `Windows Server 2012, VMware`

**Comment by kemsky** [comment]
Similar issue #4699

**Comment by vsravuri** [comment]
Could be related to https://bugs.chromium.org/p/chromedriver/issues/detail?id=2198&q=&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary

**Comment by kemsky** [comment]
> Fix will be in Chrome 67 - https://www.chromestatus.com/features/schedule
(Stable in 42 days ( May 29 ))

...
