### ISSUE TITLE
Unable to debug protractor tests with node --inspect-brk

### ISSUE THREAD

**Issue by lvsavova** [angular/protractor#4774]
I am getting the following error when debbuging protractor with node.js:

**node --inspect-brk node_modules/protractor/bin/protractor conf.js**

    _Waiting for the debugger to disconnect...
15:37:45] I/launcher - Running 1 instances of WebDriver
[15:37:45] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[15:37:45] I/BlockingProxy - Starting BlockingProxy with args: --fork,--seleniumAddress,http://localhost:4444/wd/hub,--logDir,bp-logs,--highlightDelay,80
[15:37:45] E/BlockingProxy - Starting inspector on 127.0.0.1:65281 failed: address already in use
[15:37:45] E/BlockingProxy - Exited with 12
[15:37:45] E/BlockingProxy - signal null
[15:37:45] E/launcher - Error: Error: BP exited with 12
    at ChildProcess.bpProcess.on.on.on (C:\.............)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[15:37:45] E/launcher - Process exited with error code 100_

It seems that blocking proxy receives the same debug port as the parent process and it fails. However, if I add --inspect=0, the debugging doesn;t fail, but no execution is started whatsoever.

- Node Version: `8.11.1`
- Protractor Version: `5.3.0`
- Angular Version: ``
- Browser(s): not relevant
- Operating System and Version `Windows 10`

**Comment by lvsavova** [comment]
https://github.com/angular/protractor/pull/4398 - This pull request fixes the issue (tested locally)
