### ISSUE TITLE
Multiple browser instances testing failed with chromeDriver 2.38 and directConnect

### ISSUE THREAD

**Issue by awarecan** [angular/protractor#4781]
Bug report
---

- Node Version: `8.11.1`
- Protractor Version: `latest`
- Angular Version: ``
- Browser(s): `Chrome 66.0.3359.117`, chromeDriver `2.38`
- Operating System and Version `Windows 7`
- Your protractor configuration file
change spec/directConnectConf.js as following to enable multiple browser instances
```
var env = require('./environment.js');

// A configuration file running a simple direct connect spec
exports.config = {

  directConnect: true,

  framework: 'jasmine',

  multiCapabilities: [{
    'browserName': 'chrome'
  }, {
    'browserName': 'chrome',
  }, {
    'browserName': 'chrome',
  }],

  baseUrl: env.baseUrl + '/ng1/',

  specs: ['directConnect/*_spec.js'],

  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000
  }
};
```

- A relevant example test
run default directConnect test as `bin/protractor spec/directConnectConf.js`

- Output from running the test
I got bunch of different errors, most of them likes
```
[12:34:40] I/testLogger - [chrome #21] PID: 18124
[chrome #21] Specs: O:\GitHub\awarecan\protractor\spec\directConnect\directconnect_spec.js
[chrome #21]
[chrome #21] (node:18124) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[chrome #21] [12:34:38] I/direct - Using ChromeDriver directly...
[chrome #21]
[chrome #21] O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\error.js:546
[chrome #21]         throw new ctor(message);
[chrome #21]               ^
[chrome #21] SessionNotCreatedError: session not created exception
[chrome #21] from disconnected: unable to connect to renderer
[chrome #21]   (Session info: chrome=66.0.3359.117)
[chrome #21]   (Driver info: chromedriver=2.38.551601 (edb21f07fc70e9027c746edd3201443e011a61ed),platform=Windows NT 6.1.7601 SP1 x86_64)
[chrome #21]     at Object.checkLegacyResponse (O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
[chrome #21]     at parseHttpResponse (O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
[chrome #21]     at doSend.then.response (O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
[chrome #21]     at <anonymous>
[chrome #21]     at process._tickCallback (internal/process/next_tick.js:188:7)
[chrome #21] From: Task: WebDriver.createSession()
[chrome #21]     at Function.createSession (O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
[chrome #21]     at Function.createSession (O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\chrome.js:762:15)
[chrome #21]     at Direct.getNewDriver (O:\GitHub\awarecan\protractor\lib\driverProviders\direct.ts:90:25)
[chrome #21]     at Runner.createBrowser (O:\GitHub\awarecan\protractor\lib\runner.ts:225:39)
[chrome #21]     at q.then.then (O:\GitHub\awarecan\protractor\lib\runner.ts:392:27)
[chrome #21]     at _fulfilled (O:\GitHub\awarecan\protractor\node_modules\q\q.js:834:54)
[chrome #21]     at self.promiseDispatch.done (O:\GitHub\awarecan\protractor\node_modules\q\q.js:863:30)
[chrome #21]     at Promise.promise.promiseDispatch (O:\GitHub\awarecan\protractor\node_modules\q\q.js:796:13)
[chrome #21]     at O:\GitHub\awarecan\protractor\node_modules\q\q.js:556:49
[chrome #21]     at runSingle (O:\GitHub\awarecan\protractor\node_modules\q\q.js:137:13)

[12:34:40] I/testLogger -

[12:34:40] E/launcher - Runner process exited unexpectedly with error code: 1
[12:34:40] I/launcher - 2 instance(s) of WebDriver still running
[12:34:40] I/testLogger -

```
Another example with different exception:
```
[12:34:21] I/testLogger - [chrome #01] PID: 17956
[chrome #01] Specs: O:\GitHub\awarecan\protractor\spec\directConnect\directconnect_spec.js
[chrome #01]
[chrome #01] (node:17956) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[chrome #01] [12:34:18] I/direct - Using ChromeDriver directly...
[chrome #01] Started
[chrome #01] F
[chrome #01]
[chrome #01] Failures:
[chrome #01] 1) direct connect should instantiate and run
[chrome #01]   Message:
[chrome #01]     Failed: unknown error: [ng:btstrpd] http://errors.angularjs.org/1.5.0/ng/btstrpd?p0=%26lt%3Bhtml%20lang%3D%22en%22%20ng-app%3D%22myApp%22%20class%3D%22ng-scope%22%26gt%3B
[chrome #01]       (Session info: chrome=66.0.3359.117)
[chrome #01]       (Driver info: chromedriver=2.38.551601 (edb21f07fc70e9027c746edd3201443e011a61ed),platform=Windows NT 6.1.7601 SP1 x86_64)
[chrome #01]   Stack:
[chrome #01]     WebDriverError: unknown error: [ng:btstrpd] http://errors.angularjs.org/1.5.0/ng/btstrpd?p0=%26lt%3Bhtml%20lang%3D%22en%22%20ng-app%3D%22myApp%22%20class%3D%22ng-scope%22%26gt%3B
[chrome #01]       (Session info: chrome=66.0.3359.117)
[chrome #01]       (Driver info: chromedriver=2.38.551601 (edb21f07fc70e9027c746edd3201443e011a61ed),platform=Windows NT 6.1.7601 SP1 x86_64)
[chrome #01]         at Object.checkLegacyResponse (O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
[chrome #01]         at parseHttpResponse (O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
[chrome #01]         at doSend.then.response (O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
[chrome #01]         at <anonymous>
[chrome #01]         at process._tickCallback (internal/process/next_tick.js:188:7)
[chrome #01]     From: Task: Protractor.get(http://localhost:8081/ng1/index.html#/form) - resume bootstrap
[chrome #01]         at Driver.schedule (O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
[chrome #01]         at ProtractorBrowser.executeScriptWithDescription (O:\GitHub\awarecan\protractor\lib\browser.ts:584:24)
[chrome #01]         at modulePromise.then (O:\GitHub\awarecan\protractor\lib\browser.ts:966:28)
[chrome #01]         at ManagedPromise.invokeCallback_ (O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
[chrome #01]         at TaskQueue.execute_ (O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
[chrome #01]         at TaskQueue.executeNext_ (O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
[chrome #01]         at asyncRun (O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
[chrome #01]         at O:\GitHub\awarecan\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
[chrome #01]         at <anonymous>
[chrome #01]         at process._tickCallback (internal/process/next_tick.js:188:7)
[chrome #01]     From: Task: Run it("should instantiate and run") in control flow
[chrome #01]         at UserContext.<anonymous> (O:\GitHub\awarecan\protractor\node_modules\jasminewd2\index.js:94:19)
[chrome #01]     From asynchronous test:
[chrome #01]     Error
[chrome #01]         at Suite.<anonymous> (O:\GitHub\awarecan\protractor\spec\directConnect\directconnect_spec.js:2:3)
[chrome #01]         at Object.<anonymous> (O:\GitHub\awarecan\protractor\spec\directConnect\directconnect_spec.js:1:63)
[chrome #01]         at Module._compile (module.js:652:30)
[chrome #01]         at Object.Module._extensions..js (module.js:663:10)
[chrome #01]         at Module.load (module.js:565:32)
[chrome #01]         at tryModuleLoad (module.js:505:12)
[chrome #01]
[chrome #01] 1 spec, 1 failure
[chrome #01] Finished in 0.849 seconds
[chrome #01]

```

- Steps to reproduce the bug
I can use `bin/webdriver-manager update --versions.chrome=2.37` to downgrade chromeDriver to 2.37 as workaround. There is no issue when I have only one browser instance.

This looks as duplicate with #4779 , but @ziXet indicated he has same issue even downgrade to 2.37. So I believe my case is more sticky with recently upgraded chromeDriver.

**Comment by awarecan** [comment]
To reproduce the issue, please use at lease 3 instances.

**Comment by awarecan** [comment]
Found ChromeDriver bug here: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2391

**Comment by awarecan** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2391 has been fixed. Download updated driver, problem resolved. This issue can be closed now.
