### ISSUE TITLE
No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "sand***@***.com" with a private key was found.

### ISSUE THREAD

**Issue by raulosandeep93** [angular/protractor#4783]
Hi All,

I'm trying to run my protractor script through Mac machine on iPad real device. I have started the server using webdriver-manager start which says

(node:5114) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[Appium] Welcome to Appium v1.6.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

But when I'm trying to run the script using protractor iOSConfig.ts it is throwing the error as

ICPL11611:~ sandeepraulo$ cd /Users/sandeepraulo/git/alldata_protractorpoc 
ICPL11611:alldata_protractorpoc sandeepraulo$ appium --chromedriver-executable /Users/sandeepraulo/Downloads/chromedriver 
[Appium] Welcome to Appium v1.7.2
[Appium] Non-default server args:
[Appium]   chromedriverExecutable: /Users/sandeepraulo/Downloads/chromedriver
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"","app":"/Users/sandeepraulo/Downloads/MyALLDATAiOS-QA-1.4.8.2544.ipa","deviceName":"iPad","udid":"046e4469d6cb14ff57e378599bd4b1d09390472b","platformName":"iOS","platformVersion":"11.2.6","autoWebview":true,"autoWebviewTimeout":10000,"autoAcceptAlerts":"true","xcodeOrgId":"sandeep.raulo@infostretch.com","xcodeSigningId":"iPhone Developer","bundleId":"com.allDataProtractorPOC","count":1}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"browserName":"","app":"/Users/sandeepraulo/Downloads/MyALLDATAiOS-QA-1.4.8.2544.ipa","deviceName":"iPad","udid":"046e4469d6cb14ff57e378599bd4b1d09390472b","platformName":"iOS","platformVersion":"11.2.6","autoWebview":true,"autoWebviewTimeout":10000,"autoAcceptAlerts":"true","xcodeOrgId":"sandeep.raulo@infostretch.com","xcodeSigningId":"iPhone Developer","bundleId":"com.allDataProtractorPOC","count":1},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1524203290697 (11:18:10 GMT+0530 (IST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.64.0) session
[Appium] Capabilities:
[Appium]   browserName: 
[Appium]   app: /Users/sandeepraulo/Downloads/MyALLDATAiOS-QA-1.4.8.2544.ipa
[Appium]   deviceName: iPad
[Appium]   udid: 046e4469d6cb14ff57e378599bd4b1d09390472b
[Appium]   platformName: iOS
[Appium]   platformVersion: 11.2.6
[Appium]   autoWebview: true
[Appium]   autoWebviewTimeout: 10000
[Appium]   autoAcceptAlerts: true
[Appium]   xcodeOrgId: sandeep.raulo@infostretch.com
[Appium]   xcodeSigningId: iPhone Developer
[Appium]   bundleId: com.allDataProtractorPOC
[Appium]   count: 1
[BaseDriver] Capability 'autoAcceptAlerts' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: autoWebviewTimeout, count.
[XCUITest] The capabilities 'autoAcceptAlerts' and 'autoDismissAlerts' do not work for XCUITest-based tests. Please adjust your alert handling accordingly.
[BaseDriver] Session created with session id: 1b29951e-c335-499e-876d-f9df97c6270b
[debug] [XCUITest] Current user: 'sandeepraulo'
[debug] [XCUITest] Current version of libimobiledevice: stable 1.2.0 (bottled), HEAD
[debug] [XCUITest] Xcode version set to '9.3' (tools v9.3.0.0.1.1521514116)
[debug] [XCUITest] iOS SDK Version set to '11.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1524203321506 (11:18:41 GMT+0530 (IST))
[debug] [XCUITest] Available devices: 046e4469d6cb14ff57e378599bd4b1d09390472b
[debug] [XCUITest] Creating iDevice object with udid '046e4469d6cb14ff57e378599bd4b1d09390472b'
[XCUITest] Determining device to run tests on: udid: '046e4469d6cb14ff57e378599bd4b1d09390472b', real device: true
[BaseDriver] Using local app '/Users/sandeepraulo/Downloads/MyALLDATAiOS-QA-1.4.8.2544.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[BaseDriver] Unzipping local app '/var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/T/2018320-693-1aqd19o.xbs6k/appium-app.zip'...
[debug] [BaseDriver] Unzipping /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/T/2018320-693-1aqd19o.xbs6k/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/T/2018320-693-1aqd19o.xbs6k/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/T/2018320-693-1aqd19o.xbs6k/Payload/MyALLDATAiOS.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1524203331806 (11:18:51 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/T/2018320-693-1aqd19o.xbs6k/Payload/MyALLDATAiOS.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [BaseDriver] Event 'resetStarted' logged at 1524203331807 (11:18:51 GMT+0530 (IST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1524203331809 (11:18:51 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[debug] [XCUITest] Crash reports root '/Users/sandeepraulo/Library/Logs/CrashReporter/MobileDevice/iPad' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1524203332640 (11:18:52 GMT+0530 (IST))
[XCUITest] Setting up real device
[debug] [XCUITest] Installing '/var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/T/2018320-693-1aqd19o.xbs6k/Payload/MyALLDATAiOS.app' on device with UUID '046e4469d6cb14ff57e378599bd4b1d09390472b'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1524203341912 (11:19:01 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1524203342196 (11:19:02 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*046e4469d6cb14ff57e378599bd4b1d09390472b, iproxy 8100' for the device 046e4469d6cb14ff57e378599bd4b1d09390472b...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*046e4469d6cb14ff57e378599bd4b1d09390472b' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Using Xcode 9.3, so fixing WDA codebase
[debug] [XCUITest] Generating xcode config file for orgId 'sandeep.raulo@infostretch.com' and signingId 'iPhone Developer'
[debug] [XCUITest] Writing xcode config file to /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/T/2018320-693-10h7j1e.x2tlh/appium-temp.xcconfig
[debug] [XCUITest] Using Xcode configuration file: '/var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/T/2018320-693-10h7j1e.x2tlh/appium-temp.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=046e4469d6cb14ff57e378599bd4b1d09390472b IPHONEOS_DEPLOYMENT_TARGET=11.2 -xcconfig /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/T/2018320-693-10h7j1e.x2tlh/appium-temp.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/hd/lfrrrq3d0pj4tzpc7c4nb3ww0000gp/T/com.apple.dt.XCTest/IDETestRunSession-FEF68B9B-C2F4-44BB-B11D-74E1E35B31AA/WebDriverAgentRunner-DF45FB1B-AC7D-4154-B485-2BFAFB2E4479/Session-WebDriverAgentRunner-2018-04-20_111920-cW0Kl1.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2018-04-20 11:19:30.291 xcodebuild[920:14416] Error Domain=com.apple.platform.iphoneos Code=-12 "Unable to launch com.apple.test.WebDriverAgentRunner-Runner" UserInfo={NSLocalizedDescription=Unable to launch com.apple.test.WebDriverAgentRunner-Runner}
[Xcode] 
[Xcode] 2018-04-20 11:19:30.291 xcodebuild[920:14416] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted, NSUnderlyingError=0x7fd69035d610 {Error Domain=com.apple.platform.iphoneos Code=-12 "Unable to launch com.apple.test.WebDriverAgentRunner-Runner" UserInfo={NSLocalizedDescription=Unable to launch com.apple.test.WebDriverAgentRunner-Runner}}}
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 
[Xcode]     No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "sand***@***.com" with a private key was found.
[Xcode]     Early unexpected exit, operation never finished bootstrapping - no restart will be attempted
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1524203370374 (11:19:30 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 919)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[HTTP] <-- POST /wd/hub/session 500 80617 ms - 470

**Comment by Varavarforvar** [comment]
omg

**Comment by Varavarforvar** [comment]
i,v resove it

**Comment by aryeharmon** [comment]
@Varavarforvar How? what wa the issue? i am having the same problem.

**Comment by thomasheijmans** [comment]
I'm guessing it should be fixable by choosing the correct SDK/environment variables
