### ISSUE TITLE
Update dependency on selenium-webdriver to 3.7.0 or newer

### ISSUE THREAD

**Issue by tbowmo** [angular/protractor#4792]
I have been seeing a lot of random errors like
```
- Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:62416
at ClientRequest.<anonymous> (C:\AzureAgentUI14\_work\4\s\src\Gandalf.Web\node_modules\selenium-webdriver\http\index.js:238:15)
at emitOne (events.js:116:13)
at ClientRequest.emit (events.js:211:7)
at Socket.socketErrorListener (_http_client.js:387:9)
at emitOne (events.js:116:13)
```

While exploring this error I found that it is selenium-webdriver that throws the error (as also noted in the error dump above). Protractor relies on selenium-webdriver@3.6.0.

However, in selenium-webdriver@3.7.0 they fixed this issue and implemented a more generic retry feature in case of any network issues with the webdriver socket.

Is there a possibility to update the dependencies on selenium-webdriver? As this would fix some of our problems with unstable tests.

**Comment by tbowmo** [comment]
ahh yes, I discovered that as well.. 

I solved it by using the patch-package npm package.. So we can apply a patch on our build agents on the fly, that forces selenium-webdriver to retry on the ECONNREFUSED error (as well as a couple of other errors).

**Comment by simonua** [comment]
@tbowmo, that sounds pretty interesting, and I may have a similar issue. Are you at liberty to share some of your solution, please? Thank you!

**Comment by simonua** [comment]
@tbowmo, that's awesome! Thanks a lot for the information! I'll give it a go.

Cheers,

Simon

**Comment by tbowmo** [comment]
@rafalf what parts of the patching process are you having issues with?

**Comment by rafalf** [comment]
@tbowmo I copied the file, modified package and added the script line and then .. tried to run yarn to patch but got errors. 
```

**Comment by rafalf** [comment]
```npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rafalfusik/.npm/_logs/2018-08-21T08_20_25_092Z-debug.log

{ status: 1,
  signal: null,
  output: 
   [ null,
     <Buffer 0a 3e 20 70 68 61 6e 74 6f 6d 6a 73 2d 70 72 65 62 75 69 6c 74 40 32 2e 31 2e 31 36 20 69 6e 73 74 61 6c 6c 20 2f 70 72 69 76 61 74 65 2f 76 61 72 2f ... >,
     <Buffer 6e 70 6d 20 57 41 52 4e 20 64 65 70 72 65 63 61 74 65 64 20 67 75 6c 70 2d 75 74 69 6c 40 33 2e 30 2e 38 3a 20 67 75 6c 70 2d 75 74 69 6c 20 69 73 20 ... > ],```

**Comment by rafalf** [comment]
```16191 info lifecycle protractor@5.4.0~prepublish: Failed to exec prepublish script
16192 verbose stack Error: protractor@5.4.0 prepublish: `gulp prepublish`
16192 verbose stack Exit status 1
16192 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
16192 verbose stack     at EventEmitter.emit (events.js:182:13)
16192 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
16192 verbose stack     at ChildProcess.emit (events.js:182:13)
16192 verbose stack     at maybeClose (internal/child_process.js:947:16)
16192 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
16193 verbose pkgid protractor@5.4.0
16194 verbose cwd /private/var/folders/vp/f4s9240s0wx2t0r91vpcqdkc0000gn/T/tmp-60871hvF7dbpUr4JB
16195 verbose Darwin 15.6.0
16196 verbose argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "i"
16197 verbose node v10.0.0
16198 verbose npm  v5.6.0
16199 error code ELIFECYCLE
16200 error errno 1
16201 error protractor@5.4.0 prepublish: `gulp prepublish`
16201 error Exit status 1
16202 error Failed at the protractor@5.4.0 prepublish script.
16202 error This is probably not a problem with npm. There is likely additional logging output above.
16203 verbose exit [ 1, true ]```

**Comment by tbowmo** [comment]
I can't really remember the exact steps that I did, but I believe that I forced it to use yarn (--use-yarn option), as that is our preferred package manager currently.

But install patch-package as per the description on their site, then update the files needed under selenium-webdriver, and then 

`yarn patch-package selenium-webdriver --use-yarn`

That should create a patch file for selenium...

**Comment by rene-leanix** [comment]
Thanks for pointing us to the fix in selenium-webdriver, @tbowmo! All that's needed is the line added in [this commit](https://github.com/SeleniumHQ/selenium/commit/c41f9ef2435328b3cd05a892769db6697ec5e9e2#diff-8aa92d9320f63615ec4b6cb0c5fca6ed).

(I also wasn't able to use patch-package (with npm) for this, as it failed on a post-install script.)

**Comment by tbowmo** [comment]
@rene-leanix
In our case we needed to add ECONNREFUSED to the retry list as well, as we got frequent issues with that on our azure CI agents.

**Comment by simonua** [comment]
@tbowmo, same has been true for my organization.

**Comment by rafalf** [comment]
@simonua @rene-leanix @tbowmo How did you update this file?
I am on 5.4 protractor and looking at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/http/.index.js 
and I dont have any of these functions:
shouldRetryRequest
isRetryableNetworkError

**Comment by tbowmo** [comment]
@rafalf I gave a recipe in reply no. 4 (if my calculations are right)

**Comment by rafalf** [comment]
this 3.6 index.js and there is no 276 line at all 
https://github.com/SeleniumHQ/selenium/blob/selenium-3.6.0/javascript/node/selenium-webdriver/http/index.js

so I have no idea how did you guy **add** one line 
can you elaborate 

@rene-leanix

**Comment by rene-leanix** [comment]
Yes, you're right, @rafalf. My apologies! I didn't realise that this whole block was added in the [transition from 3.6 to 3.7](https://github.com/SeleniumHQ/selenium/compare/selenium-3.6.0...selenium-3.7.0#diff-8aa92d9320f63615ec4b6cb0c5fca6edR279). So taking the [index.js from selenium-3.7.0](https://github.com/SeleniumHQ/selenium/blob/selenium-3.7.0/javascript/node/selenium-webdriver/http/index.js#L279) and adding`ECONNREFUSED` as suggested above is the only way forward for now, until Protractor updates the dependency.

**Comment by rafalf** [comment]
thanks
