### ISSUE TITLE
webdriver-manager start noclassdeffounderror

### ISSUE THREAD

**Issue by anupama0singh** [angular/protractor#4794]
Hi there!

**I am trying to start selenium webdriver after doing the installation of protractor by npm and update of webdriver but still while trying to start webdriver I am getting below error : 

Will really appreciate your help** 

**Error :** 
-MacBook-Pro:~ user$ webdriver-manager start
[22:09:58] I/start - java -Dwebdriver.chrome.driver=/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.38 -Dwebdriver.gecko.driver=/usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.20.1 -jar /usr/local/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.11.0.jar -port 4444
[22:09:58] I/start - seleniumProcess.pid: 1543
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableMap
	at org.openqa.grid.selenium.GridLauncherV3.buildLaunchers(GridLauncherV3.java:254)
	at org.openqa.grid.selenium.GridLauncherV3.<clinit>(GridLauncherV3.java:78)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableMap
	at java.net.URLClassLoader$1.run(URLClassLoader.java:370)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	... 8 more
 I/start - Selenium Standalone has exited with code 1

**Comment by IgorSasovets** [comment]
Also, take a look at: [javaError](https://stackoverflow.com/questions/18684202/java-lang-noclassdeffounderror-com-google-common-collect-maps-selenium), [selenium2 issue](https://stackoverflow.com/questions/9699997/selenium-2-webdriver-noclassdeffounderrors)

**Comment by anupama0singh** [comment]
Thank you :)  I will try the given soloutions after office and let you know how it goes.

**Comment by IgorSasovets** [comment]
My Java version:
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
And it works fine for me. So, you can try to reinstall required software.

**Comment by IgorSasovets** [comment]
I'm glad to hear that you solved this issue) Good luck)
