### ISSUE TITLE
Randomly getting error : WebDriverError: Timed out waiting for driver server to start

### ISSUE THREAD

**Issue by anupama0singh** [angular/protractor#4802]
Hi there!

I am trying to execute protractor test code after below steps : 
1. updated the selenium webdriver with - selenium-manager update
2. Started the server with - selenium-manager start .
3. Check localhost : http://localhost:4444/wd/hub/static/resource/hub.html  - and it is working  
![image](https://user-images.githubusercontent.com/37775359/39796593-001dc29a-5375-11e8-8a4c-5d659ce8da3c.png)

**But**  when I try to execute the protractor configuration file I randomly get error " WebDriverError: Timed out waiting for driver server to start".

And I do not get this error always , only 3/5 times run. can anybody tell me what could be the issue ?. 

Below is the logs of the run , you will find sometimes the test cases was executed and sometimes I got the error.

**first time out** 
D:\example\Protractor Learning>protractor protractorConf.js
(node:4780) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
**[09:48:35] I**/launcher - Running 1 instances of WebDriver
[09:48:35] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[09:48:55] E/launcher - **Timed out waiting for driver server to start.**
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'PUNITP119695L', ip: '192.168.1.102', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_151'
Driver info: driver.version: unknown
[09:48:55] E/launcher - WebDriverError: Timed out waiting for driver server to start.
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'PUNITP119695L', ip: '192.168.1.102', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_151'
Driver info: driver.version: unknown
 
**second time out** 
D:\example\Protractor Learning>protractor protractorConf.js
(node:7632) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
**[09:49:01] I**/launcher - Running 1 instances of WebDriver
[09:49:01] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[09:49:21] E/launcher - **Timed out waiting for driver server to start.**
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'PUNITP119695L', ip: '192.168.1.102', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_151'
Driver info: driver.version: unknown
[09:49:21] E/launcher - WebDriverError: Timed out waiting for driver server to start.
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'PUNITP119695L', ip: '192.168.1.102', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_151'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse 

third time code is executed mind it I haven't made any change or update anything 

D:\example\Protractor Learning>protractor protractorConf.js
(node:9544) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
**[09:49:27] I**/launcher - Running 1 instances of WebDriver
[09:49:27] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
Started
F

Failures:
1) test gmail encountered a declaration exception
  Message:
    ReferenceError: Objects is not defined
  Stack:
    ReferenceError: Objects is not defined
        at Suite.<anonymous> (D:\NAB\Protractor Learning\gmail.js:10:19)
        at Object.<anonymous> (D:\NAB\Protractor Learning\gmail.js:3:1)
        at Module._compile (module.js:635:30)
        at Object.Module._extensions..js (module.js:646:10)
        at Module.load (module.js:554:32)
        at tryModuleLoad (module.js:497:12)
        at Function.Module._load (module.js:489:3)

1 spec, 1 failure
Finished in 9.595 seconds

[09:49:54] I/launcher - 0 instance(s) of WebDriver still running
[09:49:54] I/launcher - chrome #01 failed 1 test(s)
[09:49:54] I/launcher - overall: 1 failed spec(s)
[09:49:54] E/launcher - Process exited with error code 1

fourth time I again get the tie out error 
D:\exammple\Protractor Learning>protractor protractorConf.js
(node:8500) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[09:52:08] I/launcher - Running 1 instances of WebDriver
[09:52:08] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
**[09:52:28]** E/launcher - **Timed out waiting for driver server to start.**
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'PUNITP119695L', ip: '192.168.1.102', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_151'
Driver info: driver.version: unknown
[09:52:28] E/launcher - WebDriverError: Timed out waiting for driver server to start.
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'PUNITP119695L', ip: '192.168.1.102', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_151'
Driver info: driver.version: unknown

**Comment by IgorSasovets** [comment]
Hi, @anupama0singh ! Please provide your config file and test example.
