### ISSUE TITLE
CircleCI build fail: WebDriverError: Failed to decode response from marionette

### ISSUE THREAD

**Issue by awarecan** [angular/protractor#4810]
CircleCI build fail

Bug report
---
I got two same test failure in [this build](https://circleci.com/gh/angular/protractor/1053), and the build before that. The error message showed as:

```
running: node built/cli.js spec/getCapabilitiesConf.js
.....[00:28:00] I/launcher - Running 1 instances of WebDriver
[00:28:00] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[00:28:03] E/launcher - Failed to decode response from marionette
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'box746.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-144-generic', java.version: '1.8.0_102'
Driver info: driver.version: unknown
remote stacktrace: 
[00:28:03] E/launcher - WebDriverError: Failed to decode response from marionette
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'box746.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-144-generic', java.version: '1.8.0_102'
Driver info: driver.version: unknown
remote stacktrace: 
    at WebDriverError (/home/ubuntu/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/home/ubuntu/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/ubuntu/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/ubuntu/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/ubuntu/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/home/ubuntu/protractor/node_modules/selenium-webdriver/firefox/index.js:521:41)
    at createDriver (/home/ubuntu/protractor/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/home/ubuntu/protractor/node_modules/selenium-webdriver/index.js:632:16)
    at Hosted.getNewDriver (/home/ubuntu/protractor/lib/driverProviders/driverProvider.ts:60:29)
    at Runner.createBrowser (/home/ubuntu/protractor/lib/runner.ts:225:39)
    at q.then.then (/home/ubuntu/protractor/lib/runner.ts:392:27)
    at _fulfilled (/home/ubuntu/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/ubuntu/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/ubuntu/protractor/node_modules/q/q.js:796:13)
[00:28:03] E/launcher - Process exited with error code 199

>>> fail: Error: expecting exit code: 0, actual: 199
```

I don't believe this failure associated with my changes. I won't be able to reproduce it on my Windows box, I may find a Ubuntu later to try on. Since Firefox 60.0 just released two days ago, is it possible a CircleCI or geckoDriver issue?

**Comment by qiyigg** [comment]
It might be a FF/gecko issue, I realized we had this issue several days ago, but I didn't have time to look into it yet. Any investigation or PR would be really appreciated.
