### ISSUE TITLE
Firefox 60 Not Working Getting Document Unloaded Errors

### ISSUE THREAD

**Issue by DarthOpto** [angular/protractor#4853]
Protractor does not appear to be working with Firefox 60.  I would like be able to run my tests across multiple browsers, but this is a major hindrance. 

- Node Version: `10.1.0`
- Protractor Version: `5.3.2`
- Browser(s): `Firefox 60`
- Operating System and Version `Mac 10.13.5`
- `Protractor config file`
```
// Protractor config
exports.config = {
    suites: {
        adminRoles: 'compiled/artemis/settings/adminAppRoles.scenario.js',
        adminUsers: 'compiled/artemis/settings/adminUsers.scenario.js',
        benchmarks: 'compiled/artemis/benchmarks/benchmark.scenario.js',
        claims: 'compiled/artemis/claims/claims.scenario.js',
        cohorts: 'compiled/artemis/cohorts/cohort.scenario.js',
        customBD: 'compiled/artemis/dimensions/*.scenario.js',
        exploreCreate: 'compiled/artemis/explorations/create.scenario.js',
        exploreInMeasureFilters: 'compiled/artemis/explorations/inMeasureFilters.scenario.js',
        exploreRead: 'compiled/artemis/explorations/read.scenario.js',
        exploreRegFilters: 'compiled/artemis/explorations/regularFilters.scenario.js',
        exploreUpdate: 'compiled/artemis/explorations/update.scenario.js',
        home: 'compiled/artemis/home/home.scenario.js',
        login: 'compiled/artemis/login/*.scenario.js',
        mgmtConsole: 'compiled/artemis/settings/mgmtConsoleSysDef.scenario.js',
        navigation: 'compiled/artemis/navigation/navigation.scenario.js',
        sharing: 'compiled/artemis/sharing/sharingTests.scenario.js',
        smoke: 'compiled/artemis/smokeTests/smokeTests.scenario.js',
        stories: 'compiled/artemis/story/story.scenario.js',
        visualizeCreate: 'compiled/artemis/visualize/visualizeCreate.scenario.js',
        visualizeRead: 'compiled/artemis/visualize/visualizeRead.scenario.js',
        visualizeUpdate: 'compiled/artemis/visualize/visualizeUpdate.scenario.js',
        vizInMeasureFilters: 'compiled/artemis/visualize/vizInMeasureFilters.scenario.js',
        vizRegFilters: 'compiled/artemis/visualize/vizRegularFilters.scenario.js',
        tritonLogin: 'compiled/triton/login/*.scenario.js',
        tritonCustomers: 'compiled/triton/customers/*.scenario.js',
        tritonDashboard: 'compiled/triton/dashboard/*.scenario.js'

    },
    baseUrl: baseUrl,

    directConnect: false,

    allScriptsTimeout: 25 * 1000,

    jasmineNodeOpts: {
        defaultTimeoutInterval: 90 * 1000
    },

    getPageTimeout: 120 * 1000,

    multiCapabilities: [
        {
            browserName: 'chrome',
            seleniumAddress: seleniumServer,
            platform: 'ANY',
            version: 'ANY',
            chromeOptions: {
                args: ['--no-sandbox', '--test-type=browser', '--lang=en', '--window-size=1680,1050'],
                prefs: {
                    'credentials_enable_service': false,
                    'profile': {
                        'password_manager_enabled': false
                    },
                    download: {
                        prompt_for_download: false,
                        directory_upgrade: true,
                        default_directory: 'C:\\downloads\\'
                    },
                },
            },
            loggingPrefs: { browser: 'SEVERE' }
        },

        {
            browserName: 'firefox',
            'moz:firefoxOptions': {
                args: ['--safe-mode'],
                binary: '/Applications/Firefox.app/Contents/MacOS/firefox',
            },
            marionette: true,
            seleniumAddress: seleniumServer,
        },  
    ],

    maxSessions: 1,

    framework: 'jasmine2',
    onPrepare: function() {
        //Set Up a JUnit XML Reporter - Makes a nice test results area and trend graph in Jenkins
        var jasmineReporters = require('jasmine-reporters');
        jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
            consolidateAll: true,
            savePath: 'report',
            filePrefix: 'xmloutput'
        }));

        //Setup screenshots
        jasmine.getEnv().addReporter(reporter);

        browser.get(browser.baseUrl);
    },

    // Setup the report before any tests start
    beforeLaunch: function() {
        return new Promise(function(resolve) {
            reporter.beforeLaunch(resolve);
        });
    },

    // Close the report after all tests finish
    afterLaunch: function(exitCode) {
        return new Promise(function(resolve) {
            reporter.afterLaunch(resolve.bind(this, exitCode));
        });
    },

};
```
- A relevant example test
```
describe('Smoke Tests', () => {
        beforeAll(() => {
            jasmine.DEFAULT_TIMEOUT_INTERVAL = 999999
            loginPage.login(user.email, user.password)
        })

        afterEach(() => {
            common.navigationOpenByClick().then(() => {
                navPage.navigateToApp(AppParams.apps.home.navLink)
            })
        })

        afterAll(() => {
            common.signOut()
        })

        it('Create a Cohort', () => {
            console.log('\n ### Creating a Cohort - Smoke Test ### \n')
            const cohort = {
                type: EntityType.Cohort,
                name: 'Cohort - Smoke Test',
                config: {
                    filters: CommonFilters.Filters.ageBins,
                },
            }
            cohorts.create(cohort)
            expect(listView.hasItem(cohort.name))
            listView.deleteItem(cohort.name)

        })
}
```
- Output from running the test
```
[firefox #11] 1) Smoke Tests Create a Cohort
[firefox #11]   Message:
[firefox #11]     Error: Error while running testForAngular: Document was unloaded
[firefox #11]     Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
[firefox #11]     System info: host: 'Curtiss-MacBook-Pro-2.local', ip: 'fe80:0:0:0:147a:4dee:ee9c:b07a%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '10.0.1'
[firefox #11]     Driver info: driver.version: unknown
[firefox #11]   Stack:
[firefox #11]     Error: Error while running testForAngular: Document was unloaded
[firefox #11]     Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
[firefox #11]     System info: host: 'Curtiss-MacBook-Pro-2.local', ip: 'fe80:0:0:0:147a:4dee:ee9c:b07a%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '10.0.1'
[firefox #11]     Driver info: driver.version: unknown
[firefox #11]         at executeAsyncScript_.then (/Users/csalisbury/src/helios/node_modules/protractor/built/browser.js:727:23)
[firefox #11]         at ManagedPromise.invokeCallback_ (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1376:14)
[firefox #11]         at TaskQueue.execute_ (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
[firefox #11]         at TaskQueue.executeNext_ (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
[firefox #11]         at asyncRun (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2927:27)
[firefox #11]         at /Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
[firefox #11]         at process._tickCallback (internal/process/next_tick.js:68:7)
[firefox #11]   Message:
[firefox #11]     Failed: Error while waiting for Protractor to sync with the page: "both angularJS testability and angular testability are undefined.  Thiscould be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
[firefox #11]   Stack:
[firefox #11]     Error: Error while waiting for Protractor to sync with the page: "both angularJS testability and angular testability are undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping. See http://git.io/v4gXM for details"
[firefox #11]         at runWaitForAngularScript.then (/Users/csalisbury/src/helios/node_modules/protractor/built/browser.js:463:23)
[firefox #11]         at ManagedPromise.invokeCallback_ (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1376:14)
[firefox #11]         at TaskQueue.execute_ (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
[firefox #11]         at TaskQueue.executeNext_ (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
[firefox #11]         at asyncRun (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2927:27)
[firefox #11]         at /Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
[firefox #11]         at process._tickCallback (internal/process/next_tick.js:68:7)
[firefox #11]     From: Task: Run fit("Create a Cohort") in control flow
[firefox #11]         at UserContext.<anonymous> (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
[firefox #11]     From asynchronous test:
[firefox #11]     Error
[firefox #11]         at Suite.<anonymous> (/Users/csalisbury/src/helios/compiled/artemis/smokeTests/smokeTests.scenario.js:190:9)
[firefox #11]         at /Users/csalisbury/src/helios/compiled/artemis/smokeTests/smokeTests.scenario.js:54:5
[firefox #11]         at Array.forEach (<anonymous>)
[firefox #11]         at Object.<anonymous> (/Users/csalisbury/src/helios/compiled/artemis/smokeTests/smokeTests.scenario.js:53:7)
[firefox #11]         at Module._compile (internal/modules/cjs/loader.js:678:30)
[firefox #11]         at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
[firefox #11]   Message:
[firefox #11]     Failed: Error while waiting for Protractor to sync with the page: "both angularJS testability and angular testability are undefined.  Thiscould be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
[firefox #11]   Stack:
[firefox #11]     Error: Error while waiting for Protractor to sync with the page: "both angularJS testability and angular testability are undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping. See http://git.io/v4gXM for details"
[firefox #11]         at runWaitForAngularScript.then (/Users/csalisbury/src/helios/node_modules/protractor/built/browser.js:463:23)
[firefox #11]         at ManagedPromise.invokeCallback_ (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1376:14)
[firefox #11]         at TaskQueue.execute_ (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
[firefox #11]         at TaskQueue.executeNext_ (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
[firefox #11]         at asyncRun (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2927:27)
[firefox #11]         at /Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
[firefox #11]         at process._tickCallback (internal/process/next_tick.js:68:7)Error
[firefox #11]         at ElementArrayFinder.applyAction_ (/Users/csalisbury/src/helios/node_modules/protractor/built/element.js:459:27)
[firefox #11]         at ElementArrayFinder.(anonymous function).args [as click] (/Users/csalisbury/src/helios/node_modules/protractor/built/element.js:91:29)
[firefox #11]         at ElementFinder.(anonymous function).args [as click] (/Users/csalisbury/src/helios/node_modules/protractor/built/element.js:831:22)
[firefox #11]         at CommonPageItems.navigationOpenByClick (/Users/csalisbury/src/helios/compiled/artemis/common-items/common.page.js:93:29)
[firefox #11]         at UserContext.<anonymous> (/Users/csalisbury/src/helios/compiled/artemis/smokeTests/smokeTests.scenario.js:101:20)
[firefox #11]         at /Users/csalisbury/src/helios/node_modules/protractor/node_modules/jasminewd2/index.js:112:25
[firefox #11]         at new ManagedPromise (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1077:7)
[firefox #11]         at ControlFlow.promise (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2505:12)
[firefox #11]         at schedulerExecute (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
[firefox #11]         at TaskQueue.execute_ (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
[firefox #11]     From: Task: Run afterEach in control flow
[firefox #11]         at UserContext.<anonymous> (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
[firefox #11]         at /Users/csalisbury/src/helios/node_modules/protractor/node_modules/jasminewd2/index.js:64:48
[firefox #11]         at ControlFlow.emit (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/events.js:62:21)
[firefox #11]         at ControlFlow.shutdown_ (/Users/csalisbury/src/helios/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2674:10)
[firefox #11]     From asynchronous test:
[firefox #11]     Error
[firefox #11]         at Suite.<anonymous> (/Users/csalisbury/src/helios/compiled/artemis/smokeTests/smokeTests.scenario.js:100:9)
[firefox #11]         at /Users/csalisbury/src/helios/compiled/artemis/smokeTests/smokeTests.scenario.js:54:5
[firefox #11]         at Array.forEach (<anonymous>)
[firefox #11]         at Object.<anonymous> (/Users/csalisbury/src/helios/compiled/artemis/smokeTests/smokeTests.scenario.js:53:7)
[firefox #11]         at Module._compile (internal/modules/cjs/loader.js:678:30)
[firefox #11]         at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
```

**Comment by DarthOpto** [comment]
Any thoughts here on what I am doing wrong? Obviously other people have this working, just wondering what the heck I am doing wrong with this.

**Comment by dsuren1** [comment]
I have a similar problem with Firefox 60. But the issue is with the firefox synchronization with the angular page. The application under test is angular 2.

Same configuration as above

```
Error while waiting for Protractor to sync with the page: "both angularJS testability and angular testability are undefined.  This could be either because this is a non-angular page or because
your test involves client-side navigation, which can interfere with Protractor's bootstrapping
```

And when I use browser.ignoreSynchronization=true;

`Error in browser instance firefox while taking the logs:POST`

**Comment by sri85** [comment]
For Firefox you will need to pass an additional flag `marionette:true` in the capabilities

**Comment by DarthOpto** [comment]
@sri85 I have tried that as well and it did not work.

**Comment by IgorSasovets** [comment]
Hi, @DarthOpto ! I will take a look at your issue and provide feedback or some suggestions. Protractor has problems when is used with Angular2+ apps (especially when app uses angular/material).

**Comment by DarthOpto** [comment]
Thank you @IgorSasovets

**Comment by IgorSasovets** [comment]
@DarthOpto , I ran your config on my Windows machine and at least two browsers work as expected (Chrome, Firefox).
Here are conf.js
```
// Configuration constants
var baseUrl = 'https://formetoknow.com/';

// Test report setup w/ screenshots
var HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');
var reporter = new HtmlScreenshotReporter({
    dest: 'report',
    filename: 'artemis-e2e-report.html'
});

var seleniumServer = process.env.IS_WINDOWS ?
    //'http://slc-dev-win-curtis2:4444/wd/hub' : 'http://slc-dev-curtis1:4444/wd/hub';
  'http://slc-dev-curtis1:4444/wd/hub' : 'http://127.0.0.1:4444/wd/hub';

 var browserCapabilities = [
    {
        browserName: 'chrome',
        seleniumAddress: seleniumServer,
        platform: 'ANY',
        version: 'ANY',
        chromeOptions: {
            args: ['--no-sandbox', '--test-type=browser', '--lang=en', '--window-size=1680,1050'],
            prefs: {
                'credentials_enable_service': false,
                'profile': {
                    'password_manager_enabled': false
                },
                download: {
                    prompt_for_download: false,
                    directory_upgrade: true,
                    default_directory: 'C:\\downloads\\'
                },
            },
        },
        loggingPrefs: { browser: 'SEVERE' }
    },
    {
        browserName: 'firefox',
        seleniumAddress: seleniumServer,
    },
    /*{
        browserName: 'internet explorer',
        platform: 'ANY',
        version: '11',
        // seleniumAddress: seleniumServer,
    },
    {
        browserName: 'MicrosoftEdge',
        seleniumAddress: seleniumServer,
    }*/
 ];

// Protractor config
exports.config = {
    baseUrl: baseUrl,
    directConnect: false,
    allScriptsTimeout: 25 * 1000,
    jasmineNodeOpts: {
        defaultTimeoutInterval: 90 * 1000
    },
    getPageTimeout: 120 * 1000,
	specs: ['spec.js'],

    multiCapabilities: browserCapabilities,

    maxSessions: 1,
    framework: 'jasmine2',
    onPrepare: function() {
        //Set Up a JUnit XML Reporter - Makes a nice test results area and trend graph in Jenkins
        var jasmineReporters = require('jasmine-reporters');
        jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
            consolidateAll: true,
            savePath: 'report',
            filePrefix: 'xmloutput'
        }));

        //Setup screenshots
        jasmine.getEnv().addReporter(reporter);
    },

    // Setup the report before any tests start
    beforeLaunch: function() {
        return new Promise(function(resolve) {
            reporter.beforeLaunch(resolve);
        });
    },

    // Close the report after all tests finish
    afterLaunch: function(exitCode) {
        return new Promise(function(resolve) {
            reporter.afterLaunch(resolve.bind(this, exitCode));
        });
    },

};
```
and spec.js
```
describe('Get type example', function()
{
    it('should get web app type', async function() {
        await browser.get('https://www.osianama.com/');
		await browser.sleep(5000);
		const script = `return document.querySelector('meta[name="og:type"]').content;`;
		const title = await browser.executeScript(script);
		expect(title).toEqual('website');
    });
});
```
Did you try to run it on other OS? My node version - `8.9.4`.

![image](https://user-images.githubusercontent.com/27974884/42780558-359f15ba-894c-11e8-87fa-d8a89fd6674a.png)

**Comment by IgorSasovets** [comment]
Please try my example and provide feedback.

**Comment by DarthOpto** [comment]
@IgorSasovets So the above may work with firefox, I found out yesterday that our site has an issue with firefox which is getting resolved. Once that has been fixed I will test again. 
Any thoughts on Edge and IE11?

**Comment by IgorSasovets** [comment]
I commented IE11 and Edge because I haven't these browser on my local machine. You can test it just by removing my comments. I can try it with IE 10 and provide feedback if needed.

**Comment by DarthOpto** [comment]
Same results for me no other browser except Chrome is working I have even been running it through SauceLabs now and get the same results.
