### ISSUE TITLE
Bug: WebDriverError: unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by luayala** [angular/protractor#4857]
Not able to run my tests, webdriver fails to complete.

+ Node Version: 8.5.0
+ NPM Versio: 5.3.0
+ Protractor Version: 5.3.2
+ Browser: Chrome
+ Operating System: Amozon Linux AMI
+ Chromedriver Version: 2.40
+ Selenium-Server-Standalone: 3.12.0
+ Geckodriver: 0.20.1

### Conf file 

```
exports.config = {
  seleniumServerJar: 'selenium-server.jar',
  specs: ['tests/**/*.js'],
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: ["--headless", "--disable-gpu", "--window-size=800,600"]
    }
  },
  params: {

  },

  onPrepare: function () {
    let jasmineReporters = require('jasmine-reporters');
    jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
      consolidateAll: false,
      savePath: 'results',
      filePrefix: ''
    }));
  },
  jasmineNodeOpts: {
    print: function () {}
  }
};

```

### Error Output

```
[15:28:37] I/launcher - Running 1 instances of WebDriver
[15:28:37] I/local - Starting selenium standalone server...
[15:28:37] I/local - Selenium standalone server started at http://10.0.0.192:41963/wd/hub
[15:29:38] E/launcher - unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.81-35.56.amzn1.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.05 seconds
Build info: version: '3.5.0', revision: '8def36e068', time: '2017-08-10T23:00:22.093Z'
System info: host: 'URL of the server', ip: 'ip address', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.81-35.56.amzn1.x86_64', java.version: '1.8.0_161'
Driver info: driver.version: unknown
[15:29:38] E/launcher - WebDriverError: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.81-35.56.amzn1.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.05 seconds
Build info: version: '3.5.0', revision: '8def36e068', time: '2017-08-10T23:00:22.093Z'
System info: host: 'url of server', ip: 'ip address', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.81-35.56.amzn1.x86_64', java.version: '1.8.0_161'
Driver info: driver.version: unknown
    at WebDriverError (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:626:16)
    at Local.getNewDriver (/usr/lib/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/usr/lib/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/usr/lib/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:796:13)
[15:29:38] E/launcher - Process exited with error code 199

```

**Comment by wyyd1999** [comment]
I am getting exactly same message "unknown error: DevToolsActivePort file doesn't exist" by following protractor step 0. any workaround please?

**Comment by luayala** [comment]
I figure it was a problem with my chrome, currently, I have chrome 67. you can downgrade or also install the necessary dependencies for chrome 67, I used this https://intoli.com/blog/installing-google-chrome-on-centos/

**Comment by greatspoke** [comment]
Hello I also have this error I use  in node js
 const webdriver = require('selenium-webdriver');
        const chrome = require('selenium-webdriver/chrome');
        const chromium = require('chromium');

In my console all good but when I upload my project to console.clever-cloud.com or heroku I received:

> { WebDriverError: unknown error: DevToolsActivePort file doesn't exist
> 2018-06-25T14:44:57+03:00 (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.17.2+ x86_64) 

Please help me ! Thank you
Regards
alex

**Comment by WesBunton** [comment]
Hi luayala, when you say 'you can downgrade or install dependencies', did this fix this issue for you?

**Comment by luayala** [comment]
installing the dependencies fixed my issue
