### ISSUE TITLE
E/launcher - unknown error: Chrome failed to start: crashed in headless mode

### ISSUE THREAD

**Issue by priyasam1986** [angular/protractor#4861]
Face the following error 
Google Chrome - 67.0
chromedriver - chromedriver_2.40
selenium standalone - selenium-server-standalone-3.12.0.jar
linux - CentOS Linux release 7.3
Protractor - 5.1.2
Nodejs - v6.14.2
config.ts
chrome: {
        seleniumAddress: 'http://localhost:4444/wd/hub',
        directConnect: true,
	browserName: 'chrome',
	chromeOptions:{
		args: ['--headless','--disable-gpu','--disable-dev-shm-usage','--no-sandbox','window-size=1024,768']
	}

10:37:07.923 [10:37:07] I/launcher - Running 1 instances of WebDriver
10:37:07.923 [10:37:07] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
10:38:09.409 [10:38:09] E/launcher - unknown error: Chrome failed to start: crashed
10:38:09.409   (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 3.10.0-514.26.2.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
10:38:09.409 Command duration or timeout: 60.39 seconds
10:38:09.409 Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
10:38:09.409 System info: host: 'sigmagoagt-po-a1p.sys.comcast.net', ip: '147.191.72.189', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.26.2.el7.x86_64', java.version: '1.8.0_40'
10:38:09.410 Driver info: driver.version: unknown
10:38:09.410 [10:38:09] E/launcher - WebDriverError: unknown error: Chrome failed to start: crashed
10:38:09.410   (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 3.10.0-514.26.2.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
10:38:09.410 Command duration or timeout: 60.39 seconds
10:38:09.410 Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
10:38:09.411 System info: host: 'sigmagoagt-po-a1p.sys.comcast.net', ip: '147.191.72.189', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.26.2.el7.x86_64', java.version: '1.8.0_40'
10:38:09.411 Driver info: driver.version: unknown
10:38:09.411     at WebDriverError (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/selenium-webdriver/lib/error.js:27:5)
10:38:09.411     at Object.checkLegacyResponse (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/selenium-webdriver/lib/error.js:505:15)
10:38:09.411     at parseHttpResponse (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/selenium-webdriver/lib/http.js:509:13)
10:38:09.412     at doSend.then.response (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/selenium-webdriver/lib/http.js:440:13)
10:38:09.412     at process._tickCallback (internal/process/next_tick.js:109:7)
10:38:09.412 From: Task: WebDriver.createSession()
10:38:09.412     at Function.createSession (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
10:38:09.412     at Function.createSession (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/selenium-webdriver/chrome.js:709:29)
10:38:09.412     at createDriver (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/selenium-webdriver/index.js:167:33)
10:38:09.412     at Builder.build (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/selenium-webdriver/index.js:623:16)
10:38:09.413     at Hosted.getNewDriver (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/protractor/lib/driverProviders/driverProvider.ts:60:29)
10:38:09.413     at Runner.createBrowser (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/protractor/lib/runner.ts:225:39)
10:38:09.413     at q.then.then (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/protractor/lib/runner.ts:391:27)
10:38:09.413     at _fulfilled (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/protractor/node_modules/q/q.js:834:54)
10:38:09.413     at self.promiseDispatch.done (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/protractor/node_modules/q/q.js:863:30)
10:38:09.413     at Promise.promise.promiseDispatch (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/protractor/node_modules/q/q.js:796:13)
10:38:09.414     at /app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/protractor/node_modules/q/q.js:556:49
10:38:09.414     at runSingle (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/protractor/node_modules/q/q.js:137:13)
10:38:09.414     at flush (/app/go-agent1/pipelines/UI-Automation-Testing/web/client-portal/node_modules/protractor/node_modules/q/q.js:125:13)
10:38:09.414     at _combinedTickCallback (internal/process/next_tick.js:73:7)
10:38:09.414     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by priyasam1986** [comment]
Uninstalling and re-installation of Chrome in centOS machine solved the issue. Followed installation procedure available in "https://intoli.com/blog/installing-google-chrome-on-centos/". Thank you.
