### ISSUE TITLE
E/launcher - session not created exception and it gets exited with error code 199

### ISSUE THREAD

**Issue by Dilip-Vaze** [angular/protractor#4865]
PS D:\VDSS_SDM_PROTRACTOR> protractor conf.js
(node:15140) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[14:42:43] I/launcher - Running 1 instances of WebDriver
[14:42:43] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[14:43:47] E/launcher - session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 62.60 seconds
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
System info: host: 'BANWOR488', ip: '10.20.3.184', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_102'
Driver info: driver.version: unknown
[14:43:47] E/launcher - SessionNotCreatedError: session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 62.60 seconds
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
System info: host: 'BANWOR488', ip: '10.20.3.184', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_102'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:761:15)
    at createDriver (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:626:16)
    at Hosted.getNewDriver (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
[14:43:47] E/launcher - Process exited with error code 199
PS D:\VDSS_SDM_PROTRACTOR>

**Comment by balintbabics** [comment]
The exact same problem here.

**Comment by IgorSasovets** [comment]
@dilipvaze , I ran test provided by you and it passed. Here is console output: 
![image](https://user-images.githubusercontent.com/27974884/42235947-051c49b6-7f02-11e8-9e38-585711a8b29d.png)

**Comment by dilipvaze** [comment]
@IgorSasovets 

Thank you for looking into. But the same fails for us. 
The above console of mine has all the details, did you tried on the same setup?
Because  here i tried  in different machine too no success i get the same error message.

@balintbabics 
Did you any solution?

Thanks & Regards,
Dilip Vaze

**Comment by balintbabics** [comment]
@dilipvaze 
Unfortunately not yet, and now it's a quite big issue for me.

**Comment by CrispusDH** [comment]
try to remove `seleniumAddress: 'http://localhost:4444/wd/hub',` and add instead `directConnect: true`

**Comment by IgorSasovets** [comment]
@dilipvaze , try `directConnect` option as @CrispusDH said. Also, please provide step by step command which you're using.

**Comment by dilipvaze** [comment]
@CrispusDH 
Tried with direct connect also didn't help i get the same issue as above.
@IgorSasovets 
Steps:
1. Installed npm version 5.6.0
2. installed protractor: 5.3.2
3. Webdriver-manager update 
4. Webdriver-manager start (to start selenium server) and then just executing the example file also i get the same error please find below the console message.

Microsoft Windows [Version 10.0.16299.248]
(c) 2017 Microsoft Corporation. All rights reserved.
C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\example>protractor conf.js
(node:16172) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[16:10:48] I/launcher - Running 1 instances of WebDriver
[16:10:48] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:49370/devtools/browser/3fcd6fbd-465b-4ef8-9da6-91fa577e7f6b
[16:11:53] E/launcher - session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.16299 x86_64)
[16:11:53] E/launcher - SessionNotCreatedError: session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.16299 x86_64)
    at Object.checkLegacyResponse (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:761:15)
    at Direct.getNewDriver (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\direct.js:77:33)
    at Runner.createBrowser (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:137:13)
[16:11:53] E/launcher - Process exited with error code 199

C:\Users\dva\AppData\Roaming\npm\node_modules\protractor\example>

Thanks & Regards,
Dilip Vaze

**Comment by balintbabics** [comment]
@IgorSasovets 

Unfortunately `directConnect: true` did not worked.

Installed and used versions:
 - `npm`: 6.1.0
 - `protractor`: 5.3.2
 - `selenium standalone`: 3.13.0
 - `chromedriver`: 2.40
 - `geckodriver`: v0.21.0

Steps:
 - `webdriver-manager update`
 - `webdriver-manager start`
 - in another CMD window, `protractor conf.js`
 - then fail with `error code 199`: ` E/launcher - Process exited with error code 199`

**Comment by IgorSasovets** [comment]
Flow that I used:
1. npm install protractor --save-dev
2. node node_modules\protractor\bin\webdriver-manager update
3. node node_modules\protractor\bin\webdriver-manager start
4. In other console window `node node_modules\protractor\bin\protractor conf.js`
Also, I would recommend you to run `npm cache clean --force` command before modules installation

**Comment by Galileo1** [comment]
I got the same issue today. Chromedriver website shows that chromedriver version 2.40 is the compatible chrome version 66-68. Any clue??
`E/launcher - SessionNotCreatedError: session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363),platform=Mac OS X 10.13.5 x86_64) (WARNING:The server did not provide any stacktrace information)
Command duration or timeout: 489 milliseconds
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
System info: host: 'xxxxx', ip: 'xx', os.name: 'Mac OS X', os.arch: 'x86_64',os.version: '10.13.5', java.version: '9.0.4'
Driver info: driver.version: unknown`

**Comment by zuzusik** [comment]
Had the same issue today, solved using this answer: https://stackoverflow.com/questions/46807596/webdrivererror-disconnected-unable-to-connect-to-renderer#comment90246515_49985242

**Comment by jjelev** [comment]
@zuzusik You are right.
Everyone please check your **/etc/hosts** file. I my **127.0.0.1** rule was being commented.

**Comment by karthikn1610** [comment]
I faced the same issue. Just install or update the protractor. If you still installed the protractor also Do the following steps, run the following in cmd prompt or PowerShell

```
npm install protractor -g 

npm install webdriver-manager -g
```
If you got the error as running in the background, check the running processor and close all the running processor and try.

After the above steps run the following

```
webdriver-manager update
webdriver-manager start
```

**Comment by iamzadi** [comment]
just update you protractor
follow these steps
1.webdriver-manager clean 

2.npm install protractor

3.npm install -g webdriver-manager 

4. webdriver-manager update

5.webdriver-manager update --ie

**Comment by Jinu-P** [comment]
[17:17:05] I/launcher - Running 1 instances of WebDriver
[17:17:05] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[17:17:06] E/launcher - Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'JINUPAPPACHAN', ip: '192.168.1.100', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: unknown
[17:17:06] E/launcher - SessionNotCreatedError: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'JINUPAPPACHAN', ip: '192.168.1.100', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'   
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (C:\Users\Jinu pappachan\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\Jinu pappachan\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13) 
    at C:\Users\Jinu pappachan\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\Jinu pappachan\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\Jinu pappachan\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:761:15)
    at createDriver (C:\Users\Jinu pappachan\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\Jinu pappachan\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:626:16)        
    at Hosted.getNewDriver (C:\Users\Jinu pappachan\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)    
    at Runner.createBrowser (C:\Users\Jinu pappachan\AppData\Roaming\npm\node_modules\protractor\built\runner.js:195:43)
    at C:\Users\Jinu pappachan\AppData\Roaming\npm\node_modules\protractor\built\runner.js:339:29
    at _fulfilled (C:\Users\Jinu pappachan\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at C:\Users\Jinu pappachan\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\Jinu pappachan\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
[17:17:06] E/launcher - Process exited with error code 199

**Comment by Jinu-P** [comment]
similar problem please help

**Comment by dev-it-new** [comment]
Same issue. Please help.
`Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'myhost', ip: 'myip', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '15.0.1'
Driver info: driver.version: unknown
[17:00:29] E/launcher - WebDriverError: Timed out waiting for driver server to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'myhost', ip: 'myip', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '15.0.1'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (my-project/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (my-project/node_modules/selenium-webdriver/lib/http.js:509:13)
    at my-project/node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()
    at Function.createSession (my-project/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (my-project/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (my-project/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (my-project/node_modules/selenium-webdriver/index.js:626:16)
    at Local.getNewDriver (my-project/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (my-project/node_modules/protractor/built/runner.js:195:43)
    at my-project/node_modules/protractor/built/runner.js:339:29
    at _fulfilled (my-project/node_modules/q/q.js:834:54)
    at my-project/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (my-project/node_modules/q/q.js:796:13)
[17:00:29] E/launcher - Process exited with error code 199`

**Comment by sergiman94** [comment]
same error here doing `ng e2e`

`
[17:13:53] E/launcher - spawn Unknown system error -86
[17:13:53] E/launcher - Error: spawn Unknown system error -86
    at ChildProcess.spawn (internal/child_process.js:403:11)
    at Object.spawn (child_process.js:553:9)
    at exec (/Users/sergiomanrique/Desktop/ALL/MANGO/Dev/Registration_v3/frontend_/node_modules/selenium-webdriver/io/exec.js:116:27)
    at /Users/sergiomanrique/Desktop/ALL/MANGO/Dev/Registration_v3/frontend_/node_modules/selenium-webdriver/remote/index.js:219:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/sergiomanrique/Desktop/ALL/MANGO/Dev/Registration_v3/frontend_/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/Users/sergiomanrique/Desktop/ALL/MANGO/Dev/Registration_v3/frontend_/node_modules/selenium-webdriver/chrome.js:761:15)
    at Direct.getNewDriver (/Users/sergiomanrique/Desktop/ALL/MANGO/Dev/Registration_v3/frontend_/node_modules/protractor/built/driverProviders/direct.js:77:33)
    at Runner.createBrowser (/Users/sergiomanrique/Desktop/ALL/MANGO/Dev/Registration_v3/frontend_/node_modules/protractor/built/runner.js:195:43)
    at /Users/sergiomanrique/Desktop/ALL/MANGO/Dev/Registration_v3/frontend_/node_modules/protractor/built/runner.js:339:29
    at _fulfilled (/Users/sergiomanrique/Desktop/ALL/MANGO/Dev/Registration_v3/frontend_/node_modules/protractor/node_modules/q/q.js:834:54)
    at /Users/sergiomanrique/Desktop/ALL/MANGO/Dev/Registration_v3/frontend_/node_modules/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Users/sergiomanrique/Desktop/ALL/MANGO/Dev/Registration_v3/frontend_/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/sergiomanrique/Desktop/ALL/MANGO/Dev/Registration_v3/frontend_/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/Users/sergiomanrique/Desktop/ALL/MANGO/Dev/Registration_v3/frontend_/node_modules/protractor/node_modules/q/q.js:137:13)
[17:13:53] E/launcher - Process exited with error code 199

`
