### ISSUE TITLE
Protractor hitting /timeouts/async_script end point which is not supported any longet

### ISSUE THREAD

**Issue by suryavir** [angular/protractor#4873]
- Node Version: ``
- Protractor Version: 4.0.11 and 5.3.0
- Angular Version: `4.1.2'
- Browser(s): `Firefox 60
- Operating System and Version RHEL 6.9
- Your protractor configuration file
import { browser, Config } from 'protractor';
import { EnvironmentProperties } from './protractor.environment';
import { Reporter } from './stepdefinitions/util/reporter';
const jsonReports = process.cwd() + '/reports/json';
const envParams = EnvironmentProperties.getEnvironmentParams(process.env.TEST_ENV);

export const config: Config = {

    //directConnect: true,
    seleniumAddress: 'http://127.0.0.1:4444/wd/hub',

    /*capabilities: {
        browserName: (process.env.TEST_BROWSER_NAME || 'internet explorer'),
        ignoreProtectedModeSettings: true
    },*/
    capabilities: {
        browserName: 'firefox',
        marionette: true,
        /*'moz:firefoxOptions': {
            args: [ '--safe-mode' ],
            log: {
                level: 'trace'
            }
        },*/
        //ignoreProtectedModeSettings: true,
        //jvmArgs: ['-Dwebdriver.gecko.driver=/export1/local_rdt/im-jenkins/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.21.0']
    },
    /*capabilities: {
        browserName: 'chrome',
        chromeOptions: {
            useAutomationExtension: false,
            //'--headless',
            //args: [  '--disable-gpu', '--start-maximized', '--disable-extensions', '--disable-useAutomationExtension', '--disable-plugins' ]    //'--window-size=800,600',
        }
    },*/

    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),

    params: envParams,
    baseUrl: envParams.baseUrl,

    specs: [
        '../../../e2e/features/login/Login.feature',
        //'../../../e2e/features/mifid/SearchMifid.feature'
        '../../../e2e/features/mifid/Create-Mifid.feature'
    ],

    onPrepare: () => {
        browser.ignoreSynchronization = true;
        //browser.manage().window().maximize();
        Reporter.createDirectory(jsonReports);
    },

    cucumberOpts: {
        compiler: 'ts:ts-node/register',
        format: 'json:./reports/json/cucumber_report.json',
        require: './stepdefinitions/*/*.js',
        strict: true,
        tags: '@TypeScriptScenario or @CucumberScenario or @ProtractorScenario',
    },

    onComplete: () => {
        Reporter.createHTMLReport();
    }
};

- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request

 am using protractor 4.0.11 and trying to run my e2e tests on a Linux box through a nightly jenkins job. I have XVFB plugin installed in Jenkins + run webdriver-start through jenkins job. Everything works perfectly till I reach the yarn e2e script which runs my protractor tests. A session gets created and firefox even opens up but it tries to POST to- /session/2ae59d92-fedc-49bb-b164-ac20c74a1c0e/timeouts/async_script did not match a known command.

Seems there is no end point as /session/xyz/timeouts/async_script hence the issue.

How do I solve this issue? Any help would be wonderful!

This is the jenkins Log-

$ tsc && cross-env TEST_ENV=int protractor dist/out-tsc/e2e/protractor.conf.js
[11:33:38] I/hosted - Using the selenium server at http://127.0.0.1:4444/wd/hub
[11:33:38] I/launcher - Running 1 instances of WebDriver
[11:33:41] E/runner - Unable to start a WebDriver session.
[11:33:42] E/launcher - Error: UnsupportedOperationError: POST /session/2ae59d92-fedc-49bb-b164-ac20c74a1c0e/timeouts/async_script did not match a known command
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
System info: host: 'vsie0u2243', ip: '169.28.27.254', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-696.16.1.el6.x86_64', java.version: '1.8.0_45'
Driver info: driver.version: unknown
at WebDriverError (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/error.js:27:5)
at UnsupportedOperationError (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/error.js:448:5)
at Object.checkLegacyResponse (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/error.js:639:15)
at parseHttpResponse (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/http/index.js:538:13)
at client_.send.then.response (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/http/index.js:472:11)
at ManagedPromise.invokeCallback_ (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/promise.js:1379:14)
at TaskQueue.execute_ (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/promise.js:2913:14)
at TaskQueue.executeNext_ (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/promise.js:2896:21)
at asyncRun (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/promise.js:2820:25)
at /export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/promise.js:639:7
From: Task: WebDriver.manage().timeouts().setScriptTimeout(11000)
at WebDriver.schedule (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/webdriver.js:377:17)
at Timeouts.setScriptTimeout (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/selenium-webdriver/lib/webdriver.js:1303:25)
at Runner.createBrowser (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/built/runner.js:218:53)
at /export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/built/runner.js:276:30
at _fulfilled (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/node_modules/q/q.js:834:54)
at self.promiseDispatch.done (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/node_modules/q/q.js:863:30)
at Promise.promise.promiseDispatch (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/node_modules/q/q.js:796:13)
at /export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/node_modules/q/q.js:556:49
at runSingle (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/node_modules/q/q.js:137:13)
at flush (/export1/local_rdt/im-jenkins/jenkins_home/jobs/im-gui2-e2e-tests/workspace/node_modules/protractor/node_modules/q/q.js:125:13)

This is the webdriver log-

11:14:05.129 INFO [SeleniumServer.boot] - Welcome to Selenium for Workgroups....
11:14:05.129 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
11:16:27.774 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: firefox, count: 1, moz:firefoxOptions: {args: [--safe-mode], log: {level: trace}}}
11:16:27.776 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1531131387801 geckodriver INFO geckodriver 0.21.0
1531131387805 geckodriver INFO Listening on 127.0.0.1:3067
1531131387990 mozrunner::runner INFO Running command: "/usr/bin/firefox" "-marionette" "--safe-mode" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.epfwZK9oGQqN"
1531131387991 geckodriver::marionette DEBUG Waiting 60s to connect to browser on 127.0.0.1:39675
1531131388228 addons.xpi WARN Can't get modified time of /usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi
1531131388361 addons.xpi-utils WARN addMetadata: Add-on aushelper@mozilla.org is invalid: [Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.isFile]" nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)" location: "JS frame :: resource://gre/modules/addons/XPIInstall.jsm :: loadManifestFromFile :: line 924" data: no] Stack trace: loadManifestFromFile()@resource://gre/modules/addons/XPIInstall.jsm:924
syncLoadManifestFromFile()@resource://gre/modules/addons/XPIProvider.jsm:938
addMetadata()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:1167
processFileChanges()@resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:1523
checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3302
startup()@resource://gre/modules/addons/XPIProvider.jsm:2194
callProvider()@resource://gre/modules/AddonManager.jsm:253
_startProvider()@resource://gre/modules/AddonManager.jsm:728
startup()@resource://gre/modules/AddonManager.jsm:892
startup()@resource://gre/modules/AddonManager.jsm:2976
observe()@jar:file:///usr/lib64/firefox/omni.ja!/components/addonManager.js:63
1531131388362 addons.xpi-utils WARN Could not uninstall invalid item from locked install location
1531131388552 Marionette DEBUG Received observer notification profile-after-change
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 84: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 84: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 93: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 93: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 102: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 102: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 68: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 68: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 79: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 79: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 79: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 88: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 23: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 23: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 23: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 23: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 23: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 23: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 23: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 23: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 39: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 39: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 39: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 39: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 39: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 39: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 39: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 39: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 39: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 56: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 56: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 56: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 56: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 56: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 56: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 56: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 56: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 56: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 56: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 66: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 66: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 66: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 75: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 75: Having multiple in isn't supported and may not work as expected
1531131388599 Marionette DEBUG Received observer notification command-line-startup
1531131388600 Marionette DEBUG Received observer notification nsPref:changed
1531131388663 Marionette DEBUG Received observer notification domwindowopened
1531131388732 Marionette DEBUG Safe mode detected, supressing dialog
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 84: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 84: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 93: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 93: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 102: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 102: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 33: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 59: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 68: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 68: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 79: Having multiple in isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 79: Having multiple

I have raised this issue with web driver and they have stated that 'Protractor doesn’t support the WebDriver standard correctly. I would suggest filing a bug against them, saying that the endpoint used for setting async script timeout needs to be updated to POST /session/{session id}/timeouts.'

Do let me know if this bug has already been fixed in any version of protractor/angular/webdriver/gecko etc which would fulfill me to get my e2e tests working on my jenkins box.

Thanks a lot!

**Comment by lotrgollum87** [comment]
i was running into this same issue. after updating to protractor@5.4.0 and selenium-webdriver@3.6.0 it went away. i would guess you're using an older version of selenium-webdriver.
