### ISSUE TITLE
WebDriver server randomly times out 

### ISSUE THREAD

**Issue by luayala** [angular/protractor#4875]
Hi there!

So I have been having there a weird error in which my build would fail after 100 - 200 builds but it happens very randomly after it goes back to normal like nothing had happened, it's an odd behavior. my test does not get marked as fail but the web driver times out which is very odd, I have the build run every two minutes and also autorotate the build after 20 days. 

Bug report
---

- Node Version: `8.5.0`
- Protractor Version: `5.3.2`
- Browser(s): `chrome`
- Operating System and Version `Amazon Linux `
- Chromedriver Version `2.40`
- Webdriver Manager `12.0.6`

### Conf File
```
exports.config = {
  seleniumServerJar: 'selenium-server.jar',
  specs: ['tests/**/*.js'],
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: ["--headless", "--disable-gpu", "--window-size=800,600"]
    }
  },
  params: {

  },

  onPrepare: function () {
    let jasmineReporters = require('jasmine-reporters');
    jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
      consolidateAll: false,
      savePath: 'results',
      filePrefix: ''
    }));
  },
  jasmineNodeOpts: {
    print: function () {}
  }
};
```

### Error Output 
```
[00:20:00] I/launcher - Running 1 instances of WebDriver
[00:20:00] I/local - Starting selenium standalone server...
[00:20:30] E/launcher - Error: Error: Timed out waiting for the WebDriver server at http://127.0.0.1:35816/wd/hub
    at Error (native)
    at onError (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/http/util.js:102:16)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[00:20:30] E/launcher - Process exited with error code 100
Build step 'Execute shell' marked build as failure
```

**Comment by bdbrown4** [comment]
Having the same issue still, any updates?

**Comment by tiagocpeixoto** [comment]
Having the same issue.

**Comment by luayala** [comment]
@bdbrown4  and @tiagocpeixoto no luck on this issue yet. sorry!

**Comment by Syslog2905** [comment]
I also have this issue randomly. Please fix, it's very annoying!
