### ISSUE TITLE
Protractor e2e | Element not clickable at point error | Angular Hybrid app

### ISSUE THREAD

**Issue by abhishek153** [angular/protractor#4876]
Hi There,
I have migrated our Angular JS app to Hybrid app. I am using Angular6/AngularJS (1.6) hybrid app. I am trying to run protractor e2e of the existing e2e tests for angular js pages. All test case are failing with the below reason.

button is not clickable at point (386, 20)

I am using Angular-Cli project. If I am trying to run this test individually they are passing. They fail when I am running in multiple tests together in a suite.

My protractor version : protractor": "^5.3.2
"webdriver-manager": "12.0.6",
"selenium-webdriver": "4.0.0-alpha.1",

I also tried with different version of protractor and selenium, but still got the same problem.  I also tried applying the fixes below. That is also working.
1)   
var elem = element(by.id('yourId'));
browser.actions().mouseMove(elem).click();
2) 
browser.waitForAngularEnabled(false);

Can you please help me on this issue?

 
Failed: unknown error: Element <button type="button" class="btn btn-default launch-dialog" ng-click="addReferenceTable()">...</button> is not clickable at point (386, 20). Other element would receive the click: <a class="dropdown-toggle" data-toggle="dropdown">...</a>
        (Session info: chrome=67.0.3396.99)
        (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.15063 x86_64)
        (Session info: chrome=67.0.3396.99)
        (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.15063 x86_64)
          at Object.checkLegacyResponse (\node_modules\selenium-webdriver\lib\error.js:546:15)
          at parseHttpResponse (\node_modules\selenium-webdriver\lib\http.js:509:13)
          at doSend.then.response (\node_modules\selenium-webdriver\lib\http.js:441:30)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
      From: Task: WebElement.click()
          at Driver.schedule (\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
          at WebElement.schedule_ (\node_modules\selenium-webdriver\lib\webdriver.js:2010:25)
          at WebElement.click (\node_modules\selenium-webdriver\lib\webdriver.js:2092:17)
          at actionFn (\node_modules\protractor\built\element.js:89:44)
          at Array.map (<anonymous>)
          at actionResults.getWebElements.then (\node_modules\protractor\built\element.js:461:65)
          at ManagedPromise.invokeCallback_ (\node_modules\selenium-webdriver\lib\promise.js:1376:14)
          at TaskQueue.execute_ (\node_modules\selenium-webdriver\lib\promise.js:3084:14)
          at TaskQueue.executeNext_ (\node_modules\selenium-webdriver\lib\promise.js:3067:27)
          at asyncRun (\node_modules\selenium-webdriver\lib\promise.js:2927:27)Error
          at ElementArrayFinder.applyAction_ (\node_modules\protractor\built\element.js:459:27)
          at ElementArrayFinder.(anonymous function).args [as click] (\node_modules\protractor\built\element.js:91:29)
          at ElementFinder.(anonymous function).args [as click] (\node_modules\protractor\built\element.js:831:22)
          at UserContext.<anonymous> (\e2e\*scenarios.js:28:10)
          at step (\e2e\*scenarios.js:31:23)
          at Object.next (\e2e\*scenarios.js:12:53)
          at \e2e\*scenarios.js:6:71
          at new Promise (<anonymous>)
          at __awaiter (\e2e\*scenarios.js:2:12)
          at UserContext.<anonymous> (\e2e\*scenarios.js:54:16)
      From: Task: Run it("should create named layer when default options are selected") in control flow
          at ControlFlow.emit (\node_modules\selenium-webdriver\lib\events.js:62:21)
          at ControlFlow.shutdown_ (\node_modules\selenium-webdriver\lib\promise.js:2674:10)
          at shutdownTask_.MicroTask (\node_modules\selenium-webdriver\lib\promise.js:2599:53)
      From asynchronous test:
      Error
          at Suite.<anonymous> (\e2e\*scenarios.js:21:3)
          at Object.<anonymous> (\e2e\*scenarios.js:10:1)
          at Module._compile (module.js:652:30)
          at Module.m._compile (\node_modules\ts-node\src\index.ts:400:23)
          at Module._extensions..js (module.js:663:10)

- Node Version: `8.11.3
- Protractor Version: `5.3.2`
- Angular Version: `6.0.4`
- AngularJS Version: `1.6.4`
- Browser(s): `Chrome, firefix`
- Operating System and Version `Windows 10`
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Thanks,
Abhishek

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by CrispusDH** [comment]
it is a question for `stackoverflow` instead of issue in protractor.
