### ISSUE TITLE
Button property with Input tag not working for macOS Sierra v10.13.2

### ISSUE THREAD

**Issue by techsayan01** [angular/protractor#4878]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing).
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Provide a minimally reduced test case. This makes it much more likely that your bug will be fixed. Protractor has a test Angular application available at `http://www.protractortest.org/testapp` which you can use for the reproducible test case.
4. Fill in the information that corresponds to your type of issue below.
5. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue.)

Bug report
---

- Node Version: `8.9.0`
- Protractor Version: `5.3.2`
- Angular Version: ``
- Browser(s): `Google Chrome`
- Operating System and Version `MacOS High Sierra v10.13.2`
- Your protractor configuration file
Default of any macOS. No change in the configuration file
- A relevant example test
Checking button property with on-click activity
- Output from running the test

**sh-3.2# protractor config.js** 
(node:87162) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[16:42:17] W/driverProviders - Using driver provider directConnect, but also found extra driver provider parameter(s): seleniumAddress
[16:42:17] I/launcher - Running 1 instances of WebDriver
[16:42:17] I/direct - Using ChromeDriver directly...
Started
F

Failures:
1) Protractor Demo App Test for Higher Student
  Message:
    Failed: No element found using locator: By(css selector, *[id="userpassword"])
  Stack:
    NoSuchElementError: No element found using locator: By(css selector, *[id="userpassword"])
        at elementArrayFinder.getWebElements.then (/usr/local/lib/node_modules/protractor/built/element.js:814:27)
        at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1376:14)
        at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2927:27)
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)Error
        at ElementArrayFinder.applyAction_ (/usr/local/lib/node_modules/protractor/built/element.js:459:27)
        at ElementArrayFinder.(anonymous function).args [as sendKeys] (/usr/local/lib/node_modules/protractor/built/element.js:91:29)
        at ElementFinder.(anonymous function).args [as sendKeys] (/usr/local/lib/node_modules/protractor/built/element.js:831:22)
        at UserContext.<anonymous> (/Library/WebServer/Documents/<application>/TestApp/spec.js:26:36)
        at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1077:7)
        at ControlFlow.promise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2505:12)
        at schedulerExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    From: Task: Run it("Test for Higher Student") in control flow
        at UserContext.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Library/WebServer/Documents/application/TestApp/spec.js:2:3)
        at Object.<anonymous> (/Library/WebServer/Documents/application/TestApp/spec.js:1:63)
        at Module._compile (module.js:635:30)
        at Object.Module._extensions..js (module.js:646:10)
        at Module.load (module.js:554:32)
        at tryModuleLoad (module.js:497:12)

- Steps to reproduce the bug
Check any button property with input tag. The input tag type = submit. The piece of code that I have written in working in windows system with an explicit npm install in the system.  
- The URL you are running your tests against (if relevant)
Not relevant.  I am not able to test the button behaviour no matter the website

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by IgorSasovets** [comment]
Hi, @techsayan01 ! Please provide your config file and test example.
