### ISSUE TITLE
'directConnect: true' has issues for Chrome Driver

### ISSUE THREAD

**Issue by CassieRyu** [angular/protractor#4887]
Could some please help take a look at below issue?
Here're my config files and error logs.

Config file, local.js
```
'use strict';

let config = require('./default').config;

config.capabilities = {
       browserName: 'chrome',
       chromeOptions: {
           'args': ['--start-maximized', 'disable-infobars', 'disable-gpu', 'incognito']
       }
     };

config.directConnect = true;

config.specs = ['../specs/*.spec.js'];

exports.config = config;
```
Command config
```
"local": "node_modules/.bin/protractor ./src/config/local.js --baseUrl=https://angularjs.org",
```
Command `npm run local`

error logs
```
> protractor_jasmine@1.0.0 local /Users/shanliu/Projects/protractor_jasmine
> protractor ./src/config/local.js --baseUrl=https://angularjs.org

(node:76217) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[18:04:22] W/driverProviders - Using driver provider directConnect, but also found extra driver provider parameter(s): seleniumAddress
[18:04:22] I/launcher - Running 1 instances of WebDriver
[18:04:22] I/direct - Using ChromeDriver directly...
[18:04:22] E/direct - Error code: 135
[18:04:22] E/direct - Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
[18:04:22] E/direct - Error: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
    at Direct.getNewDriver (/Users/shanliu/Projects/protractor_jasmine/node_modules/protractor/built/driverProviders/direct.js:63:31)
    at Runner.createBrowser (/Users/shanliu/Projects/protractor_jasmine/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/Users/shanliu/Projects/protractor_jasmine/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/Users/shanliu/Projects/protractor_jasmine/node_modules/q/q.js:834:54)
    at /Users/shanliu/Projects/protractor_jasmine/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Users/shanliu/Projects/protractor_jasmine/node_modules/q/q.js:796:13)
    at /Users/shanliu/Projects/protractor_jasmine/node_modules/q/q.js:556:49
    at runSingle (/Users/shanliu/Projects/protractor_jasmine/node_modules/q/q.js:137:13)
    at flush (/Users/shanliu/Projects/protractor_jasmine/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[18:04:22] E/launcher - Process exited with error code 135
npm ERR! code ELIFECYCLE
npm ERR! errno 135
npm ERR! protractor_jasmine@1.0.0 local: `protractor ./src/config/local.js --baseUrl=https://angularjs.org`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the protractor_jasmine@1.0.0 local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shanliu/.npm/_logs/2018-07-18T10_04_22_458Z-debug.log
------------------------------------------------------------
```

**Comment by IgorSasovets** [comment]
Hi, @CassieRyu ! Provide step by step command flow that you used.

**Comment by CassieRyu** [comment]
Hi, @IgorSasovets thanks for your reply.

Here's the commands I used to setup the framework:
```
$ npm install
$ npm install --save protractor
$ webdriver-manager update
$ webdriver-manager start

$ npm install --save-dev jasmine
$ npm install --save-dev jshint
$ npm install --save jasmine-fail-fast
```
After above process, webdriver status under project:
```
~/Projects/protractor_jasmine(master*) » webdriver-manager status                                                                                                        shanliu@twcn-33
[18:20:11] I/status - selenium standalone version available: 3.13.0 [last]
[18:20:11] I/status - chromedriver version available: 2.40 [last]
[18:20:11] I/status - geckodriver version available: v0.21.0 [last]
[18:20:11] I/status - android-sdk is not present
[18:20:11] I/status - appium is not present
------------------------------------------------------------
~/Projects/protractor_jasmine(master*) »       
```
Later I also run `$ webdriver-manager update` under `node_modules/.bin`
```
~/Projects/protractor_jasmine/node_modules/.bin(master*) » webdriver-manager status                                                                                      shanliu@twcn-33
[18:18:22] I/status - selenium standalone version available: 3.13.0 [last]
[18:18:22] I/status - chromedriver version available: 2.40 [last]
[18:18:22] I/status - geckodriver version available: v0.21.0 [last]
[18:18:22] I/status - android-sdk is not present
[18:18:22] I/status - appium is not present
------------------------------------------------------------
~/Projects/protractor_jasmine/node_modules/.bin(master*) »    
```
### **Scenario 1**
Then I use above command 
`$ npm run local`, which throws above error.
### **Scenario 2**
I tried using selenium address, run the server, and it's working:
config file
```
'use strict';

let config = require('./default').config;
config.seleniumAddress = 'http://localhost:4444/wd/hub/';
config.capabilities = {
    browserName: 'chrome',
    chromeOptions: {
        'args': ['--start-maximized', 'disable-infobars', 'disable-gpu', 'incognito', '--headless']
    },
    shardTestFiles: true,
    maxInstances: 1
};

config.specs = ['../specs/*.spec.js'];

exports.config = config;
```
Command config for ci file:
`"ci": "protractor ./src/config/ci.js --baseUrl=https://angularjs.org"`
command use:
`$ webdriver-manager start`
`$ npm run ci`

**Comment by IgorSasovets** [comment]
Try to run `node_modules/protractor/bin/webdriver-manager update` from project root folder.

**Comment by CassieRyu** [comment]
Hi @IgorSasovets  
It works after I run the command you provided!!
Thanks a lot!!!

**Comment by nishankkumar1994** [comment]
Please make sure to install
`npm install protractor`

Update web driver manager
`webdriver-manager update`

Run this command from your root
`node node_modules\protractor\bin\webdriver-manager update`

Now start up a server with:
`webdriver-manager start`

Also make sure that your protractor.conf.js file has below line
`// baseUrl: 'http://localhost:4200/',`
 ` seleniumAddress: 'http://localhost:4444/wd/hub/',`


Now run your e2e tests on different browesers
`ng e2e`
