### ISSUE TITLE
protractor and ngx-bootstrap.umd

### ISSUE THREAD

**Issue by mirkospagnol** [angular/protractor#4937]
Hi to all,

I had created an angular library with angular-cli v6 that include ngx-bootstrap 3.0.1 as a peerDependency
I have no problem running the app, but if I start protractor  I get the folloing error:
```
I/launcher - Running 1 instances of WebDriver
I/direct - Using ChromeDriver directly...
DevTools listening on ws://127.0.0.1:12281/devtools/browser/e174b42c-8db0-494a-aba0-4366d555a98b
E/launcher - Error: ReferenceError: window is not defined
at Object. (\node_modules\ngx-bootstrap\bundles\webpack:*ngx-bootstrap.umd*\webpack\universalModuleDefinition:10:2)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at \dist\sg-ng-core-components\bundles\sg-ng-core-components.umd.js:2:268
at Object. (\dist\sg-ng-core-components\bundles\sg-ng-core-components.umd.js:5:2)
```

It seems it is due to ngx-bootstrap.umd, but it work outside the e2e test. does anyone now ho to solve the problem ?

**Comment by paulotokimatu** [comment]
Hm, strange. I also use ngx-bootstrap 3.0.1 and can run Protractor without any issues.

Can you provide your `protractor.conf.js`and `tsconfig.e2e.json`?

**Comment by mirkospagnol** [comment]
Hi to all,

I solved this issue.
The error message is totally different from the reason of the error:
The problem was due to a reference to the /src folder, where I had put my the model of the entities.
So probably protractor was looking in the /dist folder ware is located the library I am developing.
If someone have the same error, don't hesitate to contact me
