### ISSUE TITLE
Impossible to catch errors

### ISSUE THREAD

**Issue by Kamshak** [angular/protractor#4943]
Bug report
---

- Node Version: `8.9.0`
- Protractor Version: `5.4.0`
- Angular Version: `5`
- Browser(s): `Chrome`
- Operating System and Version `Ubuntu x64`
- Your protractor configuration file
```ts
const tsNode = require('ts-node');
tsNode.register({
  compilerOptions: {
    noEmitHelpers: false
  }
});

const ports = require('../constants')
const helpers = require('../helpers');

let port;
helpers.hasProcessFlag('universal') ? port = ports.UNIVERSAL_PORT : port = ports.E2E_PORT;

let SpecReporter = require('jasmine-spec-reporter').SpecReporter;

const chromeBase = {
  'browserName': 'chrome',
  'chromeOptions': {
    'prefs': {
      'credentials_enable_service': false,
      'profile.default_content_setting_values.notifications': 2
    },
    'args': [/* "--headless", */ "--disable-gpu", "--window-size=800,600", "--no-sandbox", "--disable-extensions", ]
  }
};

exports.config = {
  skipSourceMapSupport: true,
  baseUrl: process.env.E2E_URL || `http://localhost:${port}/`,
  specs: [
    helpers.root('e2e/**/**.e2e.ts'),
    helpers.root('e2e/**/*.e2e.ts'),
    helpers.root('src/**/**.e2e.ts'),
    helpers.root('src/**/*.e2e.ts')
  ],
  exclude: [],

  framework: 'jasmine2',
  SELENIUM_PROMISE_MANAGER: false,

  allScriptsTimeout: 110000,
  onPrepare: function () {
    browser.ignoreSynchronization = true;
    jasmine.getEnv().addReporter(new SpecReporter({
      displayFailuresSummary: true,
      displayFailuredSpec: true,
      displaySuiteNumber: true,
      displaySpecDuration: true
    }));
  },

  jasmineNodeOpts: {
    showTiming: true,
    showColors: true,
    isVerbose: false,
    includeStackTrace: false,
    defaultTimeoutInterval: 400000
  },
  
  /**
   * Angular 2 configuration
   *
   * useAllAngular2AppRoots: tells Protractor to wait for any angular2 apps on the page instead of just the one matching
   * `rootEl`
   */
  useAllAngular2AppRoots: true,

    multiCapabilities: [
      chromeBase,
    ],
    directConnect: true,
}
```
- A relevant example test

``` ts
describe('My Test', () => {
      it('should be possible to catch errors', async () => {
        const errorElem = element(by.css('.alert-danger'));
        const result = await browser.wait(until.or(
          until.visibilityOf(element(by.cssContainingText('.modal-title', 'Success'))),
          until.visibilityOf(errorElem)
        ));

        let isError;
        try {
          isError = await errorElem.isDisplayed().catch(e => {});
        } catch(e) { }
        expect(isError).toBeFalsy(await errorElem.getText());
    }
})
```
- Output from running the test
```
(node:7839) UnhandledPromiseRejectionWarning: NoSuchElementError: No element found using locator: By(css selector, .alert-danger)
warning.js:18
    at elementArrayFinder.getWebElements.then (/home/valentin/frantz2/node_modules/protractor/built/element.js:814:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)Error
    at ElementArrayFinder.applyAction_ (/home/valentin/frantz2/node_modules/protractor/built/element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as isDisplayed] (/home/valentin/frantz2/node_modules/protractor/built/element.js:91:29)
    at ElementFinder.(anonymous function).args [as isDisplayed] (/home/valentin/frantz2/node_modules/protractor/built/element.js:831:22)
    at Object.<anonymous> (/home/valentin/frantz2/e2e/fb-signup.e2e.ts:58:5)
    at step (/home/valentin/frantz2/e2e/fb-signup.e2e.ts:32:23)
    at Object.next (/home/valentin/frantz2/e2e/fb-signup.e2e.ts:13:53)
    at fulfilled (/home/valentin/frantz2/e2e/fb-signup.e2e.ts:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:7839) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
warning.js:18
(node:7839) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
warning.js:18
  Login
configuration-parser.js:48
configuration-parser.js:48
    My Test
configuration-parser.js:48
      ✗ should be possible to catch errors
configuration-parser.js:48
        - Failed: No element found using locator: By(css selector, .alert-danger)
``` 

- Steps to reproduce the bug
```
run the test
```
- The URL you are running your tests against (if relevant)

**Comment by Kamshak** [comment]
Yeah, my fault, sorry...
