### ISSUE TITLE
Protractor failed on start if use Object's extension

### ISSUE THREAD

**Issue by StanislavKharchenko** [angular/protractor#4980]
Hi there!

I'm trying to use extension of Object which could be imported inside protractor tests or page-object.
The simple object extension is:

Object.prototype.someMethod = function() {
// To Do
}

When this code imported to test case or page-object, on attempt to run protractor I have the following failure:

```
Failed: Missing required parameter: sessionId
```

If object's extension removed then all is ok.
This problem is not related to implementation of extension. Protractor fails even if such extension is empty.

Bug report
---

- Node Version: `8.11.1`
- Protractor Version: `5.4.1`
- Angular Version: `6.1.6`
- Browser(s): `Chrome`
- Operating System and Version `Windows 10`
- Protractor config:

```
exports.config = {
    framework: 'jasmine',
    multiCapabilities: [
        {'browserName': 'chrome'}
    ],

    allScriptsTimeout: 30000,

    capabilities: {
        acceptInsecureCerts: true
    },

    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 30000
    },

    specs: [
        "testCase.js"
    ],

    directConnect: true,
    useAllAngular2AppRoots: true,
    SELENIUM_PROMISE_MANAGER: false,

    onPrepare: async function() {
        await browser.get('http://localhost:4200');
    }
};
```

- A relevant example test:

```
Object.prototype.someMethod = function() {
    return {someNewProperty: "SomeNewValue"};
};

describe('Simple test case', () => {
    it('Step-1', async() => {
        await AdminPage.auth();
    });

    it('Step-2', async() => {
		await AdminPage.logOut();
    });
});
```

- Output from running the test:

```
Failures:
1) Simple test case Step-1
  Message:
    Failed: Missing required parameter: sessionId
  Stack:
    InvalidArgumentError: Missing required parameter: sessionId
        at buildPath (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:567:15)
        at toHttpRequest (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:368:16)
        at buildRequest (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:355:12)
        at Executor.execute (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:434:19)
        at C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:813:25
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)Error
        at ElementArrayFinder.applyAction_ (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
        at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
        at ElementFinder.(anonymous function).args [as click] (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
        at UserContext.it (D:\Sources\phl\web-client\testCase.js:16:24)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
    From asynchronous test:
    Error
        at Suite.describe (D:\Sources\phl\web-client\testCase.js:14:5)
        at Object.<anonymous> (D:\Sources\phl\web-client\testCase.js:13:1)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
```

```
[14:43:40] E/launcher - Error: TypeError: this.assertions[specName].filter is not a function
    at Plugins.getResults (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\built\plugins.js:141:43)
    at q.then.then.then.then.then.then.then (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\built\runner.js:418:60)
    at _fulfilled (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:137:13)
    at flush (C:\Users\skha\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[14:43:40] E/launcher - Process exited with error code 100
```

- Steps to reproduce the bug:

1. Add new object's extension using "Object.prototype" to code with test or page-object;
2. Run protractor.

**Comment by JamesHennigan** [comment]
Anyone found a work around for this?
