### ISSUE TITLE
E/launcher - unknown error: Chrome failed to start: crashed

### ISSUE THREAD

**Issue by deepres** [angular/protractor#4991]
Bug report
---

- Node Version: `v11.0.0`
- Protractor Version: `5.4.1`
- Angular Version: `6`
- Browser(s): `Chrome Version 68.0.3440.75 (Official Build) (64-bit)`
- Operating System and Version `Windows 7 Pro Service Pack 1`
- Your protractor configuration file
[conf.js.txt](https://github.com/angular/protractor/files/2542434/conf.js.txt)

- A relevant example test
[todo-spec.js.txt](https://github.com/angular/protractor/files/2542435/todo-spec.js.txt)

- Output from running the test
λ protractor conf.js
[13:44:50] I/launcher - Running 1 instances of WebDriver
[13:44:50] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[13:44:53] E/launcher - unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 939 milliseconds
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
System info: host: 'xxx', ip: 'xxx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_171'
Driver info: driver.version: unknown
[13:44:53] E/launcher - WebDriverError: unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 939 milliseconds
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
System info: host: 'xxx', ip: 'xxx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_171'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:761:15)
    at createDriver (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\index.js:626:16)
    at Hosted.getNewDriver (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\q\q.js:834:54)
    at C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\q\q.js:796:13)

- Output from webdriver-manager start
λ webdriver-manager.cmd start
[13:44:34] I/start - java -Dwebdriver.chrome.driver=C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.43.exe -Dwebdriver.gecko.driver=C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodriver-v0.23.0.exe -jar C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.141.0.jar -port 4444
[13:44:34] I/start - seleniumProcess.pid: 3520
13:44:34.895 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.0, revision: 2ecb7d9a
13:44:35.020 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
2018-11-02 13:44:35.118:INFO::main: Logging initialized @469ms to org.seleniumhq.jetty9.util.log.StdErrLog
13:44:35.433 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
13:44:35.678 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
13:44:51.155 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "count": 1
}
13:44:51.157 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a) on port 34121
Only local connections are allowed.

- Steps to reproduce the bug

install protractor
`npm install -g protractor`
update webdriver-manager (behind corporate proxy)
`webdriver-manager update --ignore_ssl --proxy http://proxy.corp.domain.com:10139`
start webdriver-manager
`webdriver-manager start`

- What is happening
When I run tutorial test from protractor website new tab in Chrom opens up with the url filled with `data:,` value. In the content pane there is blank page with a banner 'Chrome is being controlled by automated test software`
Nothing more happens. I got the crash report. 
When i go to the `http://localhost:4444/wd/hub/static/resource/hub.html` url i see no session and I am not able to create new session with chrome. 

With "create session" action chrome opens new tab, but then on the WebDriver hub page I see:

Unable to create new session.

UnknownError: unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 762 milliseconds
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
System info: host: 'xxx', ip: '157.xxx.xxx.xx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_171'
Driver info: driver.version: unknown

I am able to open Firefox session.

**Comment by deepres** [comment]
[todo-spec.js.txt](https://github.com/angular/protractor/files/2542495/todo-spec.js.txt)
correct version of the todo-spec.js file

**Comment by IgorSasovets** [comment]
Hi, @deepres ! You need to update your Chrome browser. Chromedriver 2.43 [supports](http://chromedriver.chromium.org/downloads) v.69-71.

**Comment by deepres** [comment]
Hi @IgorSasovets , thanks for the tip. Since in my current setup I cannot upgrade Chrome, i downgraded web driver to 2.42, run the server:
λ `webdriver-manager.cmd start  --versions.chrome 2.42`

and got  the same error message:

λ protractor.cmd conf.js
[10:53:48] I/launcher - Running 1 instances of WebDriver
[10:53:48] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[10:53:50] E/launcher - unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.04 seconds
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
System info: host: 'xxx', ip: 'xxx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_171'
Driver info: driver.version: unknown
[10:53:50] E/launcher - WebDriverError: unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.04 seconds
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
System info: host: 'xxx', ip: 'xxx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_171'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:761:15)
    at createDriver (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\selenium-webdriver\index.js:626:16)
    at Hosted.getNewDriver (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\q\q.js:834:54)
    at C:\Users\xxxi\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\xxx\scoop\persist\nodejs\bin\node_modules\protractor\node_modules\q\q.js:796:13)
[10:53:50] E/launcher - Process exited with error code 199

**Comment by IgorSasovets** [comment]
I ran your config file on Windows 7 SP1, node `v.11.0.0` and didn't get errors. Take a look at this issues:
https://github.com/heroku/heroku-buildpack-google-chrome/issues/46
https://github.com/timgrossmann/InstaPy/issues/2362
https://github.com/angular/protractor/issues/4850
Also, I used next commands from the root project folder:
```
node node_modules\protractor\bin\webdriver-manager update
node node_modules\protractor\bin\webdriver-manager start
```
and then in another terminal window
```
node node_modules\protractor\bin\protractor conf.js
```
