### ISSUE TITLE
protractor hangs when accessing elementFinder in async / await

### ISSUE THREAD

**Issue by jkristia** [angular/protractor#5045]
- Node Version: `v8.9.1`
- Protractor Version: `~5.4.0`
- Angular Version: `^6.1.2`
- Browser(s): `Chrome`
- Operating System and Version `Windows 10`

I have a problem where protractor will hang and give a 30s timeout error whenever I try to access any elements. This happens if I enable signalR, or if any http requests are made while the test is running.

The option to prevent the hang is to set 
		browser.ignoreSynchronization = true;

I tried to add the workaround described in this issue (comment from Oct17 2017), but with no luck
https://github.com/angular/protractor/issues/2227

This is the error I see on a 

```
		let elm = element(by.tagName(tagname));
		if (await elm.isPresent()) {
			...
		}
		...

```

```
{ ScriptTimeoutError: script timeout: result was not received in 30 seconds
  (Session info: chrome=70.0.3538.102)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.14393 x86_64)
    at Object.checkLegacyResponse (C:\my-app\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\my-app\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\my-app\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: Protractor.waitForAngular() - Locator: By(css selector, back-to-home)
    at Driver.schedule (C:\my-app\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at ProtractorBrowser.executeAsyncScript_ (C:\my-app\node_modules\protractor\built\browser.js:425:28)
    at angularAppRoot.then (C:\my-app\node_modules\protractor\built\browser.js:456:33)
    at ManagedPromise.invokeCallback_ (C:\my-app\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\my-app\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\my-app\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\my-app\node_modules\selenium-webdriver\lib\promise.js:2927:27)
    at C:\my-app\node_modules\selenium-webdriver\lib\promise.js:668:7
    at <anonymous> name: 'ScriptTimeoutError', remoteStacktrace: '' }
```

**Comment by cnishina** [comment]
Are you using the `SELENIUM_PROMISE_MANAGER: false,` in your configuration file?

**Comment by jkristia** [comment]
No, I'm using the default config.
Should I add this in onPrepare ?
`promise.USE_PROMISE_MANAGER = false
`as described here ? https://stackoverflow.com/questions/46213650/protractor-disable-selenium-promise-manager-in-one-suite

```
let SpecReporter = require('jasmine-spec-reporter').SpecReporter;

exports.config = {
	allScriptsTimeout: 30000,
	specs: [
		'./e2e/**/*.e2e-spec.ts'
	],
	capabilities: {
		'browserName': 'chrome'
	},
	directConnect: true,
	baseUrl: 'http://localhost:4200/',
	framework: 'jasmine',
	jasmineNodeOpts: {
		showColors: true,
		defaultTimeoutInterval: 60000,
		print: function () { }
	},
	useAllAngular2AppRoots: true,
	beforeLaunch: function () {
		require('ts-node').register({
			project: 'e2e'
		});
	},
	onPrepare: function () {
		jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
	},
	logLevel: 'DEBUG'
};

```

**Comment by cnishina** [comment]
I would also use the `waitForAngularEnabled` method instead of `ignoreSynchronization` property. For the next version of Protractor, we are probably going to remove `ignoreSynchronization`.

Also in your config:

```
exports.config = {
  SELENIUM_PROMISE_MANAGER: false,
  ...
}
```

**Comment by cnishina** [comment]
This has been open for a couple of months with no author response. Closing this issue.
