### ISSUE TITLE
Firefox on Jenkins node

### ISSUE THREAD

**Issue by vinodkpasi** [angular/protractor#5078]
I am trying to run protractor script in firefox browser on Jenkins node which is LINUX environment. I am getting below error.

14:57:25] I/launcher - Running 1 instances of WebDriver
[14:57:25] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[14:57:25] E/launcher - Process unexpectedly closed with status 1
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'long-qa-jenkins-slave5', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-134-generic', java.version: '1.8.0_181'
Driver info: driver.version: unknown
remote stacktrace: 
[14:57:25] E/launcher - WebDriverError: Process unexpectedly closed with status 1
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'long-qa-jenkins-slave5', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-134-generic', java.version: '1.8.0_181'
**Driver info: driver.version: unknown**
remote stacktrace: 
    at Object.checkLegacyResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/firefox/index.js:521:41)
    at createDriver (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:632:16)
    at Hosted.getNewDriver (/usr/lib/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/usr/lib/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/usr/lib/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:796:13)
[14:57:25] E/launcher - Process exited with error code 199

**Comment by cnishina** [comment]
This doesn't seem like a Protractor issue. This should probably be asked on StackOverflow. I'll give you some thoughts:

So you are launching Firefox. When you star the selenium server are you launching it with geckodriver? (You might be asking to start a Firefox in your capabilities and you might have not launched the server with geckodriver).  Are you using Xvfb? Does this work on the Chrome browser with ChromeDriver (If this works, then it might be something to do with the version of Firefox / geckodriver you are using).

I imagine its the first or second item because the client is exiting with an error code of 1 due to a thrown error it is not handling. Protractor then handles this at error code 199 which is some unknown error.

I also wrote a short blog post about getting Jenkins to run in CI. https://medium.com/@cnishina/protractor-in-ci-jenkins-6f5fd3fc06ee

I would (again) ask this question in [StackOverflow](http://stackoverflow.com/questions/tagged/protractor) if the above doesn't help.

Thank you!
