### ISSUE TITLE
Protractor install issue in cmd when the command "npm install -g protractor" is executed in Remote machine 

### ISSUE THREAD

**Issue by krishnaasundaram** [angular/protractor#5079]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'protractor' ]
2 info using npm@6.4.1
3 info using node@v11.3.0
4 verbose npm-session 1c7c0c8e0f48b584
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for protractor@latest request to https://registry.npmjs.org/protractor failed, reason: connect ETIMEDOUT 104.16.25.35:443
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 133543ms
10 verbose type system
11 verbose stack FetchError: request to https://registry.npmjs.org/protractor failed, reason: connect ETIMEDOUT 104.16.25.35:443
11 verbose stack     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
11 verbose stack     at ClientRequest.emit (events.js:182:13)
11 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:399:9)
11 verbose stack     at TLSSocket.emit (events.js:182:13)
11 verbose stack     at emitErrorNT (internal/streams/destroy.js:82:8)
11 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
11 verbose stack     at process.internalTickCallback (internal/process/next_tick.js:72:19)
12 verbose cwd C:\Users\pras.chandrasekaran
13 verbose Windows_NT 10.0.17134
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
15 verbose node v11.3.0
16 verbose npm  v6.4.1
17 error code ETIMEDOUT
18 error errno ETIMEDOUT
19 error network request to https://registry.npmjs.org/protractor failed, reason: connect ETIMEDOUT 104.16.25.35:443
20 error network This is a problem related to network connectivity.
20 error network In most cases you are behind a proxy or have bad network settings.
20 error network
20 error network If you are behind a proxy, please make sure that the
20 error network 'proxy' config is set properly.  See: 'npm help config'
21 verbose exit [ 1, true ]

Tried updating and clear cache of NPM still no progress .Need help guys :)

**Comment by devoto13** [comment]
@krishnaasundaram have you read the error message you posted in the issue? In particular lines starting from 20?

**Comment by krishnarajan119** [comment]
It seems like you have intermittent network failure. Check error from 17th line. It says timed out for network request

**Comment by cnishina** [comment]
I agree this is a network issue and not Protractor. Closing this. Thanks for everyone's responses.
