### ISSUE TITLE
E/launcher - Error: ReferenceError: window is not defined when running the protractor.conf.js file

### ISSUE THREAD

**Issue by GhadeerHaddad90** [angular/protractor#5096]
Hi there!

I am facing an issue while performing end to end testing with Protractor using Angular 5.

I am getting error E/launcher - Error: ReferenceError: window is not defined when running the protractor.conf.js file with error code 100 
protractor version: 5.4.1

Bug report
---

 E/launcher - Error: ReferenceError: window is not defined
    at C:\Users\Ghadeer.Haddad\Documents\g2g-us-web\node_modules\leaflet\src\core\Util.js:217:24
    at version (C:\Users\Ghadeer.Haddad\Documents\g2g-us-web\node_modules\leaflet\dist\leaflet-src.js:7:65)
    at Object.<anonymous> (C:\Users\Ghadeer.Haddad\Documents\g2g-us-web\node_modules\leaflet\dist\leaflet-src.js:10:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
[16:12:30] E/launcher - Process exited with error code 100

Feature Request
---
steps to issue the bug: 
protractor protractor.conf.js

**Comment by cnishina** [comment]
I am not sure. I have no context of how window is used or what's going on. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
