### ISSUE TITLE
browser.debugger() is not working

### ISSUE THREAD

**Issue by srghma** [angular/protractor#5099]
Bug report
---

- Node Version: `v10.14.2`
- Protractor Version: `5.4.1`
- Angular Version: `NO ANGULAR`
- Browser(s): `chrome`
- Operating System and Version `linux in docker container elgalu/selenium`
- Your protractor configuration file

```
exports.config = {
  framework: "jasmine2",
  baseUrl: process.env.APP_URL,
  seleniumAddress: process.env.HUB_URL,
  specs: ["src/specs/**/*.js"],
  capabilities: {
    browserName: "chrome",

    // https://stackoverflow.com/questions/32740900/webdriverio-selenium-pass-command-line-arguments-into-chrome-from-config-js-file
    chromeOptions: {
      args: [
        // disable chrome's wakiness
        '--disable-infobars',
        '--disable-extensions',

        // allow http
        '--disable-web-security',

        // other
        '--lang=en',
        '--no-default-browser-check',
        '--no-sandbox',

        // not working
        // '--start-maximized',

        // TODO: headless https://medium.com/@mannyluvstacos/using-headless-chrome-for-your-selenium-tests-with-webdriverio-ce99b09d564
      ],
      prefs: {
        // disable chrome's annoying password manager
        'profile.password_manager_enabled': false,
        'credentials_enable_service': false,
        'password_manager_enabled': false,

        download: {
          default_directory:   process.env.REMOTE_DOWNLOAD_DIR,
          prompt_for_download: false,
          directory_upgrade:   true,
          extensions_to_open:  '',
        },
        plugins: {
          plugins_disabled: ['Chrome PDF Viewer'], // disable viewing pdf files after download
        },
      },
    },
  },
  onPrepare: function () {
    browser.ignoreSynchronization = true

    // because --start-maximized arg is not working
    browser.driver.manage().window().maximize()

    // patch require function to run babel before loading files
    require("@babel/register")

    // fix regeneratorRuntime is not defined
    require("@babel/polyfill")
  }
}
```

- A relevant example test

```
describe('test', () => {
  it('test', () => {
    browser.get('/login');

    browser.debugger()

    const title = browser.getTitle()
    expect(title).toBe('protractor should not reach here, but it does')
  })
})
````

- Output from running the test

```
/app # npm run test:debug

> @myapp/feature-tests@1.0.0 test:debug /app
> protractor --troubleshoot debug conf.js

[12:13:19] D/launcher - Running with --troubleshoot
[12:13:19] D/launcher - Protractor version: 5.4.1
[12:13:19] D/launcher - Your base url for tests is http://client:3000
Debugger listening on ws://127.0.0.1:9229/67ed86c0-8644-47ef-806a-04d0066c9b05
For help, see: https://nodejs.org/en/docs/inspector
[12:13:19] I/launcher - Running 1 instances of WebDriver
(node:346) [DEP0068] DeprecationWarning: `node debug` is deprecated. Please use `node inspect` instead.
connecting to localhost:5858 ....[12:13:20] I/hosted - Using the selenium server at http://hub:4444/wd/hub
.[12:13:20] D/runner - WebDriver session successfully started with capabilities Capabilities {
  map_:
   Map {
     'acceptInsecureCerts' => false,
     'acceptSslCerts' => false,
     'applicationCacheEnabled' => false,
     'browserConnectionEnabled' => false,
     'browserName' => 'chrome',
     'chrome' => { chromedriverVersion: '2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d)',
       userDataDir: '/tmp/.org.chromium.Chromium.a6f89G' },
     'cssSelectorsEnabled' => true,
     'databaseEnabled' => false,
     'goog:chromeOptions' => { debuggerAddress: 'localhost:34939' },
     'handlesAlerts' => true,
     'hasTouchScreen' => false,
     'javascriptEnabled' => true,
     'locationContextEnabled' => true,
     'mobileEmulationEnabled' => false,
     'nativeEvents' => true,
     'networkConnectionEnabled' => false,
     'pageLoadStrategy' => 'normal',
     'platform' => 'Linux',
     'rotatable' => false,
     'setWindowRect' => true,
     'takesHeapSnapshot' => true,
     'takesScreenshot' => true,
     'unexpectedAlertBehaviour' => '',
     'version' => '70.0.3538.67',
     'webStorageEnabled' => true,
     'webdriver.remote.sessionid' => 'dc3cedf11521158029877fa73faf6b85' } }
[12:13:20] D/runner - Running with spec files /app/src/specs/login.test.js
.Started
..F

Failures:
1) test test
  Message:
    Expected 'MYAPP' to be 'protractor should not reach here, but it does'.
  Stack:
    Error: Failed expectation
        at UserContext.toBe (/app/src/specs/login.test.js:8:19)
        at /app/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/app/node_modules/selenium-webdriver/lib/promise.js:1077:7)
        at ControlFlow.promise (/app/node_modules/selenium-webdriver/lib/promise.js:2505:12)
        at schedulerExecute (/app/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/app/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/app/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/app/node_modules/selenium-webdriver/lib/promise.js:2927:27)
        at /app/node_modules/selenium-webdriver/lib/promise.js:668:7

1 spec, 1 failure
Finished in 1.106 seconds

[12:13:22] I/launcher - 0 instance(s) of WebDriver still running
[12:13:22] I/launcher - chrome #01 failed 1 test(s)
[12:13:22] I/launcher - overall: 1 failed spec(s)
[12:13:22] E/launcher - Process exited with error code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @myapp/feature-tests@1.0.0 test:debug: `protractor --troubleshoot debug conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @myapp/feature-tests@1.0.0 test:debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-18T12_13_22_321Z-debug.log
```

- Steps to reproduce the bug

1. add `browser.debugger()`
2. `protractor debug conf.js`

Expected:
- shows repl

Actual: 
- shows warning `DeprecationWarning: `node debug` is deprecated. Please use `node inspect` instead`
- doesnt run repl
- completes test without running repl

**Comment by cnishina** [comment]
Well, I'm not surprised this is not working. The repl and debugger were very experimental and will go away (deprecated due to control flow) in the next release of Protractor. I would check out our ng-conf vid where we discuss deubgging using `node --inspect-brk ./node_modules/.bin/protractor`. https://www.youtube.com/watch?v=6aPfHrSl0Qk&t=976s

Closing this as won't fix.

**Comment by srghma** [comment]
Thankyou @cnishina 

Was able to setup development environment where I can execute selenium actions in chrome devtools (interactively)

1. write example test with debugger breakpoint in the middle

```js
const faker = require('faker')

describe('login', function() {
  this.timeout(30 * 1000)

  describe("when user doesn't exist", () => {
    it.only('should not login', async () => {
      await browser.get(`/login`)

      // debugger breakpoints

      // I'm using `await $('div').getText();` command to force selenium evaluate promise.

      // More about how promises are evaluated in chrome devtools here
      // https://stackoverflow.com/questions/53852917/how-to-run-asynchronous-code-in-chrome-devtools-when-script-execution-is-paused

      // use F8 in chrome devtools to execute `await $('div').getText();` and stop on next `debugger` breakpoint
      // use ctrl-[ and ctrl-] to switch between panels in chrome devtools

      debugger; await $('div').getText();debugger; await $('div').getText();debugger; await $('div').getText();debugger; await $('div').getText();debugger; await $('div').getText();debugger; await $('div').getText();debugger; await $('div').getText();debugger; await $('div').getText();debugger; await $('div').getText();debugger; await $('div').getText();debugger; await $('div').getText();debugger; await $('div').getText();debugger; await $('div').getText();

      await $('#gb-email').sendKeys('foo@mail.com')
    })
  })
})

```
2. run protractor in inspect mode

```
"test:debug": "node --inspect-brk=0.0.0.0:9229 ./node_modules/.bin/protractor ./config.js",
```

3. go to chrome://inspect/#devices and click inspect link to launch chrome devtools

![2018-12-27-20 30 29-screenshot](https://user-images.githubusercontent.com/7573215/50490902-366b3800-0a18-11e9-9f0f-1ad73619e460.png)


4. press f8 to continue test and stop on first breakpoint 

![2018-12-27-20 31 37-screenshot](https://user-images.githubusercontent.com/7573215/50490933-5995e780-0a18-11e9-8891-d437a666be13.png)

5. now you can execute selenium commands interactively in console

![2018-12-27-20 31 52-screenshot](https://user-images.githubusercontent.com/7573215/50490945-70d4d500-0a18-11e9-8cd0-89c6343fc8a6.png)
![2018-12-27-20 31 54-screenshot](https://user-images.githubusercontent.com/7573215/50490949-77fbe300-0a18-11e9-89e8-523b3b41c3ad.png)


6. press f8 to continue execution (promises can't be evaluated when thread is paused), `await $('div').getText();` will force selenium to execute statement (selenium promises are veird type of promises, for example even `await(new Promise((resolve) => { setTimeout(() => { resolve('dummy'); }, 0); }))` doesnt force selenium to execute statement`)


7. PROFIT

![2018-12-27-20 32 11-screenshot](https://user-images.githubusercontent.com/7573215/50491007-c27d5f80-0a18-11e9-9779-30aa4474dcec.png)


______________________________

BONUS

config.js
```js
exports.config = {
  framework: "mocha",
  baseUrl: process.env.APP_URL,
  seleniumAddress: process.env.HUB_URL,
  specs: ["src/specs/**/*.js"],
  capabilities: {
    browserName: "chrome",

    // https://stackoverflow.com/questions/32740900/webdriverio-selenium-pass-command-line-arguments-into-chrome-from-config-js-file
    chromeOptions: {
      args: [
        // disable chrome's wakiness
        'disable-infobars',
        'disable-extensions',

        // allow http
        'disable-web-security',

        // other
        'lang=en',
        'no-default-browser-check',
        'no-sandbox',

        // not working
        // 'start-maximized',
      ],
      prefs: {
        // disable chrome's annoying password manager
        'profile.password_manager_enabled': false,
        'credentials_enable_service': false,
        'password_manager_enabled': false,

        download: {
          default_directory:   process.env.REMOTE_DOWNLOAD_DIR,
          prompt_for_download: false,
          directory_upgrade:   true,
          extensions_to_open:  '',
        },
        plugins: {
          plugins_disabled: ['Chrome PDF Viewer'], // disable viewing pdf files after download
        },
      },
    },
  },
  onPrepare: function () {
    browser.ignoreSynchronization = true

    // because --start-maximized arg is not working
    browser.driver.manage().window().maximize()

    // patch require function to run babel before loading files
    require("@babel/register")

    // fix regeneratorRuntime is not defined
    // require("@babel/polyfill")
  },
  mochaOpts: {
    enableTimeouts: false,
    file: ['./src/hooks/index.js'],
  },
  allScriptsTimout: 15000,
}
```
