### ISSUE TITLE
The 'files' list in config file 'tsconfig.json' is empty. Error is coming

### ISSUE THREAD

**Issue by yashwp** [angular/protractor#5117]
I've got a large scale angular 5.2 application in which I now want to implement e2e tests using the protractor. But when I'm running `ng e2e -s false` command. it is throwing an error as follows:

```[15:58:11] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
The 'files' list in config file 'tsconfig.json' is empty. (18002)
    at load (F:\Commutatus\yop-v3\node_modules\ts-node\src\index.ts:159:13)
    at service (F:\Commutatus\yop-v3\node_modules\ts-node\src\index.ts:285:32)
    at shouldIgnore (F:\Commutatus\yop-v3\node_modules\ts-node\src\index.ts:293:21)
    at Object.require.extensions.(anonymous function) [as .ts] (F:\Commutatus\yop-v3\node_modules\ts-node\src\index.ts:302:11)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at F:\Commutatus\yop-v3\node_modules\protractor\node_modules\jasmine\lib\jasmine.js:84:5
[15:58:11] E/launcher - Process exited with error code 100```

Here is my `tsconfig.json`

```{
  "compileOnSave": false,
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc-e2e",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}
```
Also, I have opened this [question ](https://stackoverflow.com/questions/54072781/protractor-the-files-list-in-config-file-tsconfig-json-is-empty-18002)on stackoverflow, but no luck with the solution provided. Can you guys tell me how do I fix this?

**Comment by cnishina** [comment]
Since this does appear to be a support question, I am going to close it.

**Comment by yashwp** [comment]
@cnishina If you are gonna close this instead of helping, then whom I'm gonna ask?

P.S. `-s false` means don't serve the application in `ng e2e`, an the application is already being served
