### ISSUE TITLE
waitForAngular() not working on angularJS -> angular hybrid app

### ISSUE THREAD

**Issue by bdirito** [angular/protractor#5137]
Bug report
---

- Node Version: `v10.13.0`
- Protractor Version: `5.4.2`
- Angular Version: `1.6.10 & 6.0.1`
- Browser(s): `chrome 70.0.3538.77`
- Operating System and Version `Ubuntu 18.04.1 LTS`
- Your protractor configuration file
```
require('ts-node').register({compilerOptions: {module: "commonjs"}});
exports.config = require('./protractor.umini.conf.ts').config
```
```
import { Config } from 'protractor'

export let config: Config = {
    specs: ['ultramini.e2e.ts'],
    framework: 'jasmine'
};
```
- A relevant example test
```
import { browser } from 'protractor'

describe('waitForAngular', () => {
    it('should be able to waitForAngular on a hybrid app', async () => {
        browser.waitForAngularEnabled(false)
        await browser.get(`https://bdirito-tmp-station.locutionresponder.com/#!/welcome`)
        // dont event try to do anything w/o a nice long loading session
        await new Promise(resolve => setTimeout(resolve, 10 * 1000))
        browser.waitForAngularEnabled(true)
        await browser.waitForAngular()
        console.log('SUCCESS')
    })
})
```
- Output from running the test
```
$ protractor
[16:06:11] I/launcher - Running 1 instances of WebDriver
[16:06:11] I/local - Starting selenium standalone server...
[16:06:12] I/local - Selenium standalone server started at http://192.168.192.49:58194/wd/hub
Started
F

Failures:
1) waitForAngular should be able to waitForAngular on a hybrid app
  Message:
    Failed: script timeout: result was not received in 11 seconds
      (Session info: chrome=70.0.3538.77)
      (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-44-generic x86_64)
  Stack:
    ScriptTimeoutError: script timeout: result was not received in 11 seconds
      (Session info: chrome=70.0.3538.77)
      (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-44-generic x86_64)
        at Object.checkLegacyResponse (/home/bdirito/dev/locution/responder/node_modules/selenium-webdriver/lib/error.js:546:15)
        at parseHttpResponse (/home/bdirito/dev/locution/responder/node_modules/selenium-webdriver/lib/http.js:509:13)
        at doSend.then.response (/home/bdirito/dev/locution/responder/node_modules/selenium-webdriver/lib/http.js:441:30)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    From: Task: Protractor.waitForAngular()
```
- Steps to reproduce the bug

The test fails when running browser.waitForAngular(). The very odd thing is that I can take protractor's `clientsidescripts.js` and copy paste it into the browser and *that* works. See https://gist.github.com/bdirito/209b6fc32cd23b86b1a7e7f2ac197ff2 for clientsidescripts.js (i snipped off the end of the file as there are not references to exports in the browser & added in a `functions.waitForAngular(document, () => console.log('yes it works'))` )

Copypasting the gist into the browser will call callback & you should see 'yes it works' on the console.

- The URL you are running your tests against (if relevant)

https://bdirito-tmp-station.locutionresponder.com

May or may not be related to #5125. We however *are* using upgradeModule. I also tried pr 5131 as a possible fix to this - it doesnt fix it.

**Comment by bdirito** [comment]
After digging into the guts of both protractor & angular ive figured it out. It turns out that there was an angular macrotask that was pending (read ngZone wrapped setInterval).

Running the tests manually in fact was NOT working. The callback was indeed triggering however thats because it was actually *erroring*. `document` is not actually a valid first argument for `waitForAngular()`. The default argument when run normally is `''` (empty string). In the case of an error the callback is invoked with the error string. It might have been nicer to stick to node style duel callbacks but I imagine at this point a single callback is embedded into the design.

As feedback It might be nice if `waitForAngular()` explicitly called out macrotasks at the end of its timeout that would have been helpful. Along with angular making it easier to actually check what macrotasks are currently running ... 

For now im closing the ticket

**Comment by bdirito** [comment]
https://stackoverflow.com/questions/48627074/how-to-track-which-async-tasks-protractor-is-waiting-on
