### ISSUE TITLE
Scripts fail with reason Failed: timeout

### ISSUE THREAD

**Issue by dhee0807** [angular/protractor#5152]
Hi there!

I have around 150 Test scenarios in different feature files, that run every day. All the scenarios run perfectly some days but sometimes, we are seeing Failed: timeout with out any specific reason.

Below is the Protractor config file.

```
exports.config = {
      //seleniumAddress: 'http://localhost:4444/wd/hub',

      specs: ['./features/login_test.js', './features/login_errors_test.js', './features/settings_test.js'],
      framework: 'jasmine2',
      capabilities: {
        browserName: 'chrome',
      },

      jasmineNodeOpts: {
        defaultTimeoutInterval: 6000000
     },
}
```

Below is the error seen after few scenarios passed, from here all the scripts do fail.

> Failed: timeout   (Session info: headless chrome=71.0.3578.98)   (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.13.6 x86_64)

stdout:
TimeoutError: timeout
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.13.6 x86_64)
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.navigate().to(https://myurl.com)

Any help would be appreciated to handle the above!

Bug report
---

- Node Version: `8.12.0`
- Browser(s): `Chrome`
- Operating System and Version `Windows 8.1 and Mac OS X 10`

**Comment by dhee0807** [comment]
@juliemr , can you pls look into this and help me out!

**Comment by IgorSasovets** [comment]
Hi, @dhee0807 ! Could you please provide test example? It seems that there could be issue with tests suites.

**Comment by dhee0807** [comment]
Hi, @IgorSasovets , we use hiptest framework.

Below is my spec file
`describe('Login', function () {
  beforeEach(function () {
    this.actionwords = Object.create(require('./actionwords.js').Actionwords);
  });

  it('LOGN_01 Verify if the login option present is settings (uid:1)', function () {
  
    this.actionwords.iLaunchTheApplication();
    // Given I am not Logged in and I am on Home page
    this.actionwords.iAmNotLoggedInAndIAmOnHomePage();
    // When I navigate to Settings option
    this.actionwords.iNavigateToSettingsOption();
    // When I select the "Settings_HomePage"
    this.actionwords.iSelectTheP1("Settings_HomePage");
    // Then I should see the "LoginButton_SettingsPage"
    this.actionwords.iShouldSeeTheP1("LoginButton_SettingsPage");
  });
});`

Below is the actionword.js:
`exports.Actionwords = {
  loc: Object.create(require('../common/locators.js').locators),
  commonfunc: Object.create(require('../common/commonfunctions.js').commonfunc),
  
  iLaunchTheBTSportApplication: function() {
    browser.get('https://****app.com');
    browser.manage().window().maximize();
    browser.executeScript('window.sessionStorage.clear();');
    browser.executeScript('window.localStorage.clear();');
    browser.manage().deleteAllCookies();
    browser.refresh();
    //this.iSwitchTheEnvToStub();
   
    browser.wait(EC.presenceOf(this.loc['Menu']), 3000, 'Home page not loaded yet');
    if (this.loc['Menu].isPresent()) {
      this.loc['Menu'].getAttribute('class').then(activeClass => {
        if (activeClass.includes('focus')) {
          this.commonfunc.pressKey('Down');
          browser.wait(EC.visibilityOf(this.loc['LoginToWatch']), 3000, 'CTA not visible');
        }
      });
    }
  },`

These are sample files and we follow the same template for all specs and every actionword is implemented in actionword.js

Thanks,
Dheeraj

**Comment by IgorSasovets** [comment]
@dhee0807 , try move `this.actionwords.iLaunchTheApplication();` function call to the `beforeEach` hook.

**Comment by IgorSasovets** [comment]
Also, try to run [these](https://github.com/IgorSasovets/protractor-long-load-bug) tests and provide feedback about the results.

**Comment by dhee0807** [comment]
@IgorSasovets , 

> @dhee0807 , try move `this.actionwords.iLaunchTheApplication();` function call to the `beforeEach` hook.

Hi @IgorSasovets , we intentionally kept iLaunchTheApplication in every step as per our requirements as we clear cookies and launch in each test case. 
Secondly as a work around I have added browser.refresh() in the same iLaunchTheApplication function to avoid the url blank. 

Also I have seen the same tests you provided and I have implemented the same way!

Thanks and appreciate for your time! Will comment further on my runs as currently no refresh issue.

Dheeraj G
