### ISSUE TITLE
E/launcher - Unable to create new service: InternetExplorerDriverService

### ISSUE THREAD

**Issue by praveenngp15** [angular/protractor#5180]
I am getting the below error

> protractor outputjs/conf.js

[09:17:28] I/launcher - Running 1 instances of WebDriver
[09:17:28] I/local - Starting selenium standalone server...
[09:17:30] I/local - Selenium standalone server started at http://192.168.43.69:50504/wd/hub
[09:17:31] E/launcher - Unable to create new service: InternetExplorerDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-S5DALSR', ip: '192.168.43.69', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: unknown
[09:17:31] E/launcher - SessionNotCreatedError: Unable to create new service: InternetExplorerDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-S5DALSR', ip: '192.168.43.69', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (C:\Users\Praveen\Desktop\Protractor e2e\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\Praveen\Desktop\Protractor e2e\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\Praveen\Desktop\Protractor e2e\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\Praveen\Desktop\Protractor e2e\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at createDriver (C:\Users\Praveen\Desktop\Protractor e2e\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\Praveen\Desktop\Protractor e2e\node_modules\selenium-webdriver\index.js:635:14)
    at Local.getNewDriver (C:\Users\Praveen\Desktop\Protractor e2e\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\Praveen\Desktop\Protractor e2e\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Users\Praveen\Desktop\Protractor e2e\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Users\Praveen\Desktop\Protractor e2e\node_modules\q\q.js:834:54)
    at C:\Users\Praveen\Desktop\Protractor e2e\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\Praveen\Desktop\Protractor e2e\node_modules\q\q.js:796:13)
    at C:\Users\Praveen\Desktop\Protractor e2e\node_modules\q\q.js:604:44
[09:17:31] E/launcher - Process exited with error code 199
npm ERR! code ELIFECYCLE
npm ERR! errno 199
npm ERR! protractor-e2e@1.0.0 test: `protractor outputjs/conf.js`
npm ERR! Exit status 199
npm ERR!
npm ERR! Failed at the protractor-e2e@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Praveen\AppData\Roaming\npm-cache\_logs\2019-03-20T16_17_31_280Z-debug.log

**conf.js**
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.config = {
    seleniumServerJar:'../node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar',
    chromeDriver:'../node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.46.exe',
    IEDriverServer: '../node_modules/protractor/node_modules/webdriver-manager/selenium/IEDriverServer.exe',
    //directConnect: true,
  //seleniumAddress: 'http://localhost:4444/wd/hub',  
  framework: 'jasmine',
   capabilities: {
        browserName: 'internet explorer'

    },
    specs: ['./specs/calculator.js'],
    jasmineNodeOpts: {
        defaultTimeoutInterval: 30000
    }
    //not modified
    //seleniumAddress: 'http://localhost:4444/wd/hub',
    // You could set no globals to true to avoid jQuery '$' and protractor '$'
    // collisions on the global namespace.
};

**Comment by praveenngp15** [comment]
Started InternetExplorerDriver server (32-bit)
3.141.5.0
Listening on port 5555
Only local connections are allowed

**Comment by cnishina** [comment]
You'll need to start up the selenium standalone server with the iedriver. In the current configuration, you can only start Chrome and Firefox (this is defined in the driverProvider local.ts)

I would start with `webdriver-manager start --ie`  and use `seleniumAddress: 'http://localhost:4444/wd/hub'`.

Closing this issue as resolved. If you still run into this issue, please ask support questions on  [StackOverflow](http://stackoverflow.com/questions/tagged/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by upendraprakash** [comment]
i want to configure it on jenkins where after executing webdriver-manager start --ie  , we are not unable to execute  protractor test case config.js file , because both need to run in separate  windows:
please provide proper solution .

**Comment by dubilyer** [comment]
> i want to configure it on jenkins where after executing webdriver-manager start --ie , we are not unable to execute protractor test case config.js file , because both need to run in separate windows:
> please provide proper solution .

You can use --detach key. It will run selenium server in background.
