### ISSUE TITLE
SessionNotCreatedError: session not created from timeout: Timed out receiving message from renderer: 600.000

### ISSUE THREAD

**Issue by gaurabhi1986** [angular/protractor#5194]
I am running my test in parallel on team-city build job, locally they are running fine but in team-city build is failing every time. Its all started after I have upgraded my chrome browser to version 73. 

Bug report
---

- Node Version: v8.11.4
- Protractor Version: 4.0.14
- Angular Version: 1.x
- Browser(s): Chrome 73
- Operating System and Version Windows 10
- Output from running the test:

[22:43:11][Step 9/9] [chrome #01-0] Specs: C:\BuildAgent10-2\work\83588bb4a221d014\Cinema.Web\UIAutomation\1_testLaunchers\desktopTestLauncher.js
[22:43:11][Step 9/9] [chrome #01-0] 
[22:43:11][Step 9/9] [chrome #01-0] (node:6924) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[22:43:11][Step 9/9] [chrome #01-0] [22:32:25] I/direct - Using ChromeDriver directly...
[22:43:11][Step 9/9] [chrome #01-0] 
[22:43:11][Step 9/9] [chrome #01-0] C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:639
[22:43:11][Step 9/9] [chrome #01-0]         throw new ctor(message);
[22:43:11][Step 9/9] [chrome #01-0]               ^
[22:43:11][Step 9/9] [chrome #01-0] SessionNotCreatedError: session not created
[22:43:11][Step 9/9] [chrome #01-0] from timeout: Timed out receiving message from renderer: 600.000
[22:43:11][Step 9/9] [chrome #01-0]   (Session info: chrome=73.0.3683.86)
[22:43:11][Step 9/9] [chrome #01-0]   (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 6.1.7601 SP1 x86_64)
[22:43:11][Step 9/9] [chrome #01-0]     at Object.checkLegacyResponse (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:639:15)
[22:43:11][Step 9/9] [chrome #01-0]     at parseHttpResponse (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:538:13)
[22:43:11][Step 9/9] [chrome #01-0]     at client_.send.then.response (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:472:11)
[22:43:11][Step 9/9] [chrome #01-0]     at ManagedPromise.invokeCallback_ (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379:14)
[22:43:11][Step 9/9] [chrome #01-0]     at TaskQueue.execute_ (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
[22:43:11][Step 9/9] [chrome #01-0]     at TaskQueue.executeNext_ (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
[22:43:11][Step 9/9] [chrome #01-0]     at asyncRun (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2820:25)
[22:43:11][Step 9/9] [chrome #01-0]     at C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
[22:43:11][Step 9/9] [chrome #01-0]     at <anonymous>
[22:43:11][Step 9/9] [chrome #01-0]     at process._tickCallback (internal/process/next_tick.js:188:7)
[22:43:11][Step 9/9] [chrome #01-0] From: Task: WebDriver.createSession()
[22:43:11][Step 9/9] [chrome #01-0]     at Function.createSession (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:329:24)
[22:43:11][Step 9/9] [chrome #01-0]     at new Driver (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:778:38)
[22:43:11][Step 9/9] [chrome #01-0]     at Direct.getNewDriver (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\direct.js:70:26)
[22:43:11][Step 9/9] [chrome #01-0]     at Runner.createBrowser (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\built\runner.js:198:43)
[22:43:11][Step 9/9] [chrome #01-0]     at C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\built\runner.js:277:30
[22:43:11][Step 9/9] [chrome #01-0]     at _fulfilled (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
[22:43:11][Step 9/9] [chrome #01-0]     at self.promiseDispatch.done (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
[22:43:11][Step 9/9] [chrome #01-0]     at Promise.promise.promiseDispatch (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
[22:43:11][Step 9/9] [chrome #01-0]     at C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
[22:43:11][Step 9/9] [chrome #01-0]     at runSingle (C:\Users\teamcity_build\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:137:13)
[22:43:11][Step 9/9] 
[22:43:11][Step 9/9] [22:42:57] I/testLogger -

**Comment by cnishina** [comment]
Possibly update Protractor? You are several versions back. I would update Protractor first. Also there's no example so there is no way to debug this.

**Comment by gaurabhi1986** [comment]
cnishina

**Comment by gaurabhi1986** [comment]
> Possibly update Protractor? You are several versions back. I would update Protractor first. Also there's no example so there is no way to debug this.

But my tests are working fine in local system, its only failing in Build server. Its look like Protractor is not able to create Browser session in build server, I am getting error message on build log "Process exited with code 100 (Step: Run UI Tests (Command Line))". If you see the stack trace issue is related to file "\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:538:13" thats protractor file. If I upgrade my protractor version will it compatible with my code or do I need to modify my UI tests so that it can run with new updated protractor.

**Comment by vinodkumar012** [comment]
I am also facing similar kind of issue by upgrading to chrome 73. My tests also running fine locally. But, failing on team city

**Comment by vinodkumar012** [comment]
@gaurabhi1986 Plaease update here if you find any sollution.

**Comment by ddaughtry333** [comment]
I also am facing the same issue.  

My Teamcity windows build agents were upgraded to Chrome 73 and my e2mock builds using Protractor immediately started failing.   

The google documentation says we should be using a new chromedriver for 73, see the top of the page [here](https://sites.google.com/a/chromium.org/chromedriver/downloads), while also saying down further that chromedriver-2.46 works with 73, so that adds to the confusion.  Regardless, Protractor still resolves that it should pair 73 with chromedriver-2.46.

Running the commands from cli from the same teamcity agent checkout directory works fine using the 73/2.46 combo:

[11:55:28] I/launcher - Running 1 instances of WebDriver
[11:55:28] I/direct - Using ChromeDriver directly...
##teamcity[testSuiteStarted name='about']
##teamcity[testStarted name='should have an accessible about.html page' captureStandardOutput='true']
##teamcity[testFinished name='should have an accessible about.html page' duration='4559']
##teamcity[testSuiteFinished name='about' duration='4575']
...

But when ran via the Teamcity job on the same agent fails to create the session:
[09:49:06][Step 3/3] [10:48:46] I/launcher - Running 1 instances of WebDriver
[09:49:06][Step 3/3] [10:48:46] I/direct - Using ChromeDriver directly...
[09:59:11][Step 3/3] [10:58:50] E/launcher - session not created
[09:59:11][Step 3/3] from timeout: Timed out receiving message from renderer: 600.000
[09:59:11][Step 3/3]   (Session info: chrome=73.0.3683.86)
[09:59:11][Step 3/3]   (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by marcosmainar** [comment]
How did you solve this? I'm also experiencing the same issue with Chrome 73 on TeamCity

**Comment by voropa** [comment]
Probably the problem is in Crome v73?and cromedriver version. Here is the solution: 

webdriver-manager update --versions.chrome 2.46
protractor 5.4.2
"--disable-features=VizDisplayCompositor"
https://stackoverflow.com/questions/55364056/timed-out-receiving-message-from-renderer-10-000-while-capturing-screenshot-usi
