### ISSUE TITLE
"Cannot automatically find webdriver-manager to update" after upgrading to Protractor 6

### ISSUE THREAD

**Issue by FrancescoBorzi** [angular/protractor#5209]
Bug report
---

After upgrading from version `5.4.2` to version `6.0.0`, when I try to run `ng e2e` it fails with the following:

```
Cannot automatically find webdriver-manager to update.
Update webdriver-manager manually and run 'ng e2e --no-webdriver-update' instead.
Error: Cannot automatically find webdriver-manager to update.
Update webdriver-manager manually and run 'ng e2e --no-webdriver-update' instead.
    at ProtractorBuilder._updateWebdriver (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular-devkit/build-angular/src/protractor/index.js:83:23)
    at MergeMapSubscriber.rxjs_1.of.pipe.operators_1.concatMap [as project] (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular-devkit/build-angular/src/protractor/index.js:26:200)
    at MergeMapSubscriber._tryNext (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SafeSubscriber.__tryOrUnsub (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:209:16)
    at SafeSubscriber.next (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:147:22)
    at Subscriber._next (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:90:26)
    at Subscriber.next (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SafeSubscriber.__tryOrUnsub (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:209:16)
    at SafeSubscriber.next (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:147:22)
    at MergeMapSubscriber.notifyNext (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/home/francesco.borzi/sources/ngx-duration-picker/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
```

Switching back to `5.4.2` solves this issue for me.

Here some information about my system:

```
Angular CLI: 7.3.7
Node: 10.15.3
OS: linux x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/cli                      7.3.7
@ngtools/webpack                  7.2.4
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.28.4
```

**Comment by cnishina** [comment]
This is because the Angular CLI does not currently support Protractor 6 yet. I did let one of the maintainers know things were changing.

**Comment by cnishina** [comment]
Blocked. Still need to release a working version of Protractor 6 and coordinate with the CLI team.

**Comment by rklak** [comment]
Any update on this :question:

**Comment by Jimit09** [comment]
Any update on when resolution or workaround?

**Comment by jscharett** [comment]
Any hope of getting this resolved for Angular 7?  I am trying to test an app which uses Material, and it seems that Chrome driver does not work correctly in some situations (angular/components#9755).  The Gecko driver works as expected, however it throws error in ci environment due to angular/webdriver-manager#303.  This appears to have been corrected in version 13.0.0, and is now available in angular/protractor#5209.  I know v7 is in LTS, but would still be nice to get a fix for it.

**Comment by cnishina** [comment]
More info: the Angular team will be responsible for the next release of Protractor. It will be published when they are ready.

**Comment by tymfear** [comment]
@cnishina any info on the approximate release date?

**Comment by cnishina** [comment]
I do not. I'm still working on cleaning up webdriver-manager and there is one outstanding bug + documentation for Protractor. This isn't my main focus so it's difficult to tend to these things on my free time.

**Comment by tymfear** [comment]
@cnishina, thank you. And thank you for the work you do.

**Comment by jscharett** [comment]
Is it possible to release the webmanager v13 as part of Protractor v5 so we can take advantage of it now?

**Comment by TamaraTorresVM** [comment]
Hi I'm using 5.4.2 and my tests were working till yesterday! there is some walkaround? @cnishina

**Comment by FrancescoBorzi** [comment]
I've just given a try again and the problem is still there. Are there any news on this?

```
Angular CLI: 9.0.0-rc.5
Node: 10.16.1
OS: darwin x64

Angular: 9.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.5
@angular-devkit/build-angular     0.900.0-rc.5
@angular-devkit/build-optimizer   0.900.0-rc.5
@angular-devkit/build-webpack     0.900.0-rc.5
@angular-devkit/core              9.0.0-rc.5
@angular-devkit/schematics        9.0.0-rc.5
@ngtools/webpack                  9.0.0-rc.5
@schematics/angular               9.0.0-rc.5
@schematics/update                0.900.0-rc.5
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
```

**Comment by yktoo** [comment]
Had the same error message during `ng e2e`, turned out you need to add Protractor to the `devDependencies`:

```bash
npm add --save-dev protractor
```
