### ISSUE TITLE
Can someone help provide proper configuration to have protractor run in firefox, and compatible version of firefox

### ISSUE THREAD

**Issue by snowtans** [angular/protractor#5219]
I am using the following configuration for protractor :
    "protractor": "^5.4.2",
    "should": "^7.1.1",
    "webdriver-manager": "^12.1.1",
    "webpack": "^1.12.6"
 [11:06:02] I/status - selenium standalone version available: 3.141.59 [last]
[11:06:02] I/status - chromedriver versions available: 2.45, 2.46 [last]
[11:06:02] I/status - geckodriver versions available: v0.13.0, v0.17.0 [last], v0.21.0, v0.24.0
[11:06:02] I/status - android-sdk is not present
[11:06:02] I/status - appium is not present
config file 👍
 capabilities: {
      browserName: 'firefox',
      marionette: false,
      firefoxOptions: {
         args: ['--headless']
      },
      'moz:firefoxOptions': {
         args: ['--headless']
      }
   }

firefox version currently is 56.0.2. Because i wanted to run headless and i read that it is only supported in 55+, but the tests wont run with this set up -->

[09:15:39] I/launcher - Running 1 instances of WebDriver
[09:15:39] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[09:16:24] E/launcher - Timed out waiting 45 seconds for Firefox to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
[10:58:36] E/launcher - WebDriverError: Timed out waiting 45 seconds for Firefox to start.
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (/home/Development/lrp-protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/Development/lrp-protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/Development/lrp-protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/Development/lrp-protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/home/Development/lrp-protractor/node_modules/selenium-webdriver/firefox/index.js:521:41)
    at createDriver (/home/Development/lrp-protractor/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/home/Development/lrp-protractor/node_modules/selenium-webdriver/index.js:632:16)
    at Hosted.getNewDriver (/home/Development/lrp-protractor/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/home/Development/lrp-protractor/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/home/Development/lrp-protractor/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/home/Development/lrp-protractor/node_modules/q/q.js:834:54)
    at /home/Development/lrp-protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/home/Development/lrp-protractor/node_modules/q/q.js:796:13

Can run the test in chrome however without any issues. I tried older version of firefox (47) it works and runs the test but fails because it is not full screen and i tried running in headless, but still opens up the browser. I am fairly new to set up and configuration. Great if someone could provide info.

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor) or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
