### ISSUE TITLE
Linux Jenkins Protractor +Cucumber Error

### ISSUE THREAD

**Issue by skAutomation12** [angular/protractor#5220]
+ mv node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone-3.4.0.jar node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone.jar
+ set +x
(node:30448) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[17:01:41] I/direct - Using ChromeDriver directly...
[17:01:41] I/launcher - Running 1 instances of WebDriver
[17:01:41] E/launcher - Server terminated early with status 1
[17:01:41] E/launcher - Error: Server terminated early with status 1
    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:242:20
    at ManagedPromise.invokeCallback_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2775:27)
    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Driver (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:778:38)
    at Direct.getNewDriver (/usr/lib/node_modules/protractor/built/driverProviders/direct.js:68:26)
    at Runner.createBrowser (/usr/lib/node_modules/protractor/built/runner.js:197:43)
    at /usr/lib/node_modules/protractor/built/runner.js:276:30
    at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/lib/node_modules/protractor/node_modules/q/q.js:137:13)
[17:01:41] E/launcher - Process exited with error code 199
Build step 'Execute shell' marked build as failure
[CucumberReportPublisher] Compiling Cucumber Html Reports ...

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
