### ISSUE TITLE
Protracotor 5.4.2 - Unable to download geckodriver with webdriver-manager update command

### ISSUE THREAD

**Issue by ManikDhar** [angular/protractor#5229]
- Node Version: `v10.15.3`
- Protractor Version: `5.4.2`
- Browser(s): `firef0x`
- Operating System and Version `windowns 7`

**Package.json file :**
```
  "dependencies": {
    "protractor": "^5.4.2",
    "jasmine": "^3.3.1",
    "protractor-beautiful-reporter": "^1.2.7"
  },
  "scripts": {
    "pretest": "npm install && webdriver-manager update --ignore_ssl = true",
    "test": "protractor config.js"
  },
```
When running command **npm test** , gecko driver is not downloading in "node_modules\protractor\node_modules\webdriver-manager\selenium" and as a result getting the below error:
```
[12:35:43] I/file_manager - creating folder C:\GIT-BGT-3\BGT-E2E\node_modules\protractor\node_modules\webdriver-manager\selenium
[12:35:43] I/http_utils - ignoring SSL certificate
[12:35:43] I/config_source - curl -ok C:\GIT-BGT-3\BGT-E2E\node_modules\protractor\node_modules\webdriver-manager\selenium\standalone-response.xml https://selenium-release.storage.googleapis.com/
[12:35:43] I/http_utils - ignoring SSL certificate
[12:35:43] I/config_source - curl -ok C:\GIT-BGT-3\BGT-E2E\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
[12:35:43] I/http_utils - ignoring SSL certificate
**[12:35:43] I/config_source - curl -ok C:\GIT-BGT-3\BGT-E2E\node_modules\protractor\node_modules\webdriver-manager\selenium\gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
(node:15028) UnhandledPromiseRejectionWarning: Error: response status code is not 200.  It was 403_
    at Request.req.on.response (C:\GIT-BGT-3\BGT-E2E\node_modules\protractor\node_modules\webdriver-manager\built\lib\binaries\config_source.js:181:28)**
    at Request.emit (events.js:189:13)
    at Request.onRequestResponse (C:\GIT-BGT-3\BGT-E2E\node_modules\request\request.js:1066:10)
    at ClientRequest.emit (events.js:194:15)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
(node:15028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12:35:44] I/http_utils - ignoring SSL certificate
[12:35:44] I/http_utils - ignoring SSL certificate
[12:35:44] I/downloader - curl -ok C:\GIT-BGT-3\BGT-E2E\node_modules\protractor\node_modules\webdriver-manager\selenium/chromedriver_74.0.3729.6.zip https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_win32.zip
[12:35:45] I/downloader - curl -ok C:\GIT-BGT-3\BGT-E2E\node_modules\protractor\node_modules\webdriver-manager\selenium/selenium-server-standalone-3.141.59.jar https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
[12:35:46] I/update - chromedriver: unzipping chromedriver_74.0.3729.6.zip
```
```
> protractorbgt@1.0.0 test C:\GIT-BGT-3\BGT-E2E
> protractor config.js

[12:35:49] I/launcher - Running 1 instances of WebDriver
[12:35:49] E/local - Error code: 135
**_[12:35:49] E/local - Error message: No update-config.json found. Run 'webdriver-manager update' to download binaries._
[12:35:49] E/local - Error: No update-config.json found. Run 'webdriver-manager update' to download binaries.**
    at Local.addDefaultBinaryLocs_ (C:\GIT-BGT-3\BGT-E2E\node_modules\protractor\built\driverProviders\local.js:39:23)
    at Local.setupDriverEnv (C:\GIT-BGT-3\BGT-E2E\node_modules\protractor\built\driverProviders\local.js:105:14)
    at Local.setupEnv (C:\GIT-BGT-3\BGT-E2E\node_modules\protractor\built\driverProviders\driverProvider.js:111:34)
    at q.then (C:\GIT-BGT-3\BGT-E2E\node_modules\protractor\built\runner.js:335:41)
    at _fulfilled (C:\GIT-BGT-3\BGT-E2E\node_modules\q\q.js:834:54)
    at C:\GIT-BGT-3\BGT-E2E\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\GIT-BGT-3\BGT-E2E\node_modules\q\q.js:796:13)
    at C:\GIT-BGT-3\BGT-E2E\node_modules\q\q.js:857:14
    at runSingle (C:\GIT-BGT-3\BGT-E2E\node_modules\q\q.js:137:13)
    at flush (C:\GIT-BGT-3\BGT-E2E\node_modules\q\q.js:125:13)
[12:35:49] E/launcher - Process exited with error code 135
npm ERR! Test failed.  See above for more details.
```
--------------------------------------------------------------------------------------------------------------

in "node_modules\protractor\node_modules\webdriver-manager\selenium" folder the following are installed:
```
chromedriver_74.0.3729.6 - Application
chromedriver_74.0.3729.6 - WinZip file
chrome-response - XML document
selenium-server-standalone-3.141.59.jar - jar file
standalone-response - XML document
```

----------------------------------------------------------------------
```
C:\GIT-BGT-3\BGT-E2E>**webdriver-manager status**
[12:51:08] I/status - selenium standalone version available: 3.141.59
[12:51:08] I/status - chromedriver version available: 74.0.3729.6
[12:51:08] I/status - geckodriver is not present
[12:51:08] I/status - IEDriverServer is not present
[12:51:08] I/status - android-sdk is not present
[12:51:08] I/status - appium is not present

```

Note: I am not using any global installation except node

**Comment by cnishina** [comment]
I am not sure because it works when I use ignore_ssl. Why do you need this flag?
```
npx webdriver-manager update --ignore_ssl = true
[14:10:31] I/http_utils - ignoring SSL certificate
[14:10:31] I/config_source - curl -ok /usr/local/google/home/cnishina/src/test_for_protractor/node_modules/protractor/node_modules/webdriver-manager/selenium/standalone-response.xml https://selenium-release.storage.googleapis.com/
[14:10:31] I/http_utils - ignoring SSL certificate
[14:10:31] I/config_source - curl -ok /usr/local/google/home/cnishina/src/test_for_protractor/node_modules/protractor/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
[14:10:31] I/http_utils - ignoring SSL certificate
[14:10:31] I/config_source - curl -ok /usr/local/google/home/cnishina/src/test_for_protractor/node_modules/protractor/node_modules/webdriver-manager/selenium/gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
[14:10:31] I/http_utils - ignoring SSL certificate
[14:10:31] I/http_utils - ignoring SSL certificate
[14:10:31] I/downloader - curl -ok /usr/local/google/home/cnishina/src/test_for_protractor/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_74.0.3729.6.zip https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
[14:10:32] I/downloader - curl -ok /usr/local/google/home/cnishina/src/test_for_protractor/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
[14:10:32] I/update - chromedriver: unzipping chromedriver_74.0.3729.6.zip
[14:10:32] I/update - chromedriver: setting permissions to 0755 for /usr/local/google/home/cnishina/src/test_for_protractor/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_74.0.3729.6
[14:10:32] I/http_utils - ignoring SSL certificate
[14:10:33] I/downloader - curl -ok /usr/local/google/home/cnishina/src/test_for_protractor/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
[14:10:33] I/update - geckodriver: unzipping geckodriver-v0.24.0.tar.gz
[14:10:33] I/update - geckodriver: setting permissions to 0755 for /usr/local/google/home/cnishina/src/test_for_protractor/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0
```

```
npx webdriver-manager status
[14:11:04] I/status - selenium standalone version available: 3.141.59 [last]
[14:11:04] I/status - chromedriver version available: 74.0.3729.6 [last]
[14:11:04] I/status - geckodriver version available: v0.24.0 [last]
[14:11:04] I/status - android-sdk is not present
[14:11:04] I/status - appium is not present
```

**Comment by ManikDhar** [comment]
Hi,

The issue was occurring due to proxy issue , I am able to resolve the proxy and now able to download the gecko driver from webdriver-manager update command.

Thank you, I am closing the ticket.

**Comment by baruhut** [comment]
> Hi,
> 
> The issue was occurring due to proxy issue , I am able to resolve the proxy and now able to download the gecko driver from webdriver-manager update command.
> 
> Thank you, I am closing the ticket.

Hi, 
What is the issue? And how did you resolve it? I also worked behind issue. Somehow webriver-manager update --ignore_ssl --proxy http://username:pass@my.proxy.net:port only download chromedriver and selenium standalone driver

**Comment by ManikDhar** [comment]
Hi,

If you are trying to download the dependencies please try in open network like (home) and see whether you are able to download the same. If yes then its a proxy issue when you are getting the issue in company network.

--ignore_ssl should work but if not then please consult with your network team. 

If you are facing issue with geckodriver then please see the logs and you will be able to understand if its a proxy issue or something else.

Please paste the logs here so that I can help you further.
