### ISSUE TITLE
Unable to Start webdriver-manager start getting events.js:170

### ISSUE THREAD

**Issue by bhushan921** [angular/protractor#5243]
![Error_170](https://user-images.githubusercontent.com/49754911/57925826-32588d80-78c7-11e9-9a2a-4e5d588fe265.PNG)

C:\Users\bharat.bh>webdriver-manager start
[17:12:33] I/config_source - curl -oC:\Users\bharat.bh\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
[17:12:33] I/config_source - curl -oC:\Users\bharat.bh\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 216.58.196.208:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
Emitted 'error' event at:
    at Request.onRequestError (C:\Users\bharat.bh\AppData\Roaming\npm\node_modules\protractor\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:198:15)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

Also, how can i setup proxy?

**Comment by Agoni1** [comment]
I had the same problem

**Comment by cnishina** [comment]
What version of webdriver-manager are you using? webdriver-manager start making a curl call hasn't been a thing for a year or two.
