### ISSUE TITLE
Protractor Error updating Sauce pass/fail status

### ISSUE THREAD

**Issue by Vamshi-Muniganti** [angular/protractor#5246]
Bug report
---

- Node Version: `v11.10.1`
- Protractor Version: `5.4.2`
- Angular Version: ``
- Browser(s): `Chrome and FF`
- Operating System and Version `Windows 10`
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug

All our tests are running fine but the status of tests pass/fail is not updated back to Saucelabs

ERROR:
[firefox latest Windows 10 #11] 19 steps (19 passed)
[firefox latest Windows 10 #11] 2m57.855s
[firefox latest Windows 10 #11] [11:30:23] I/sauce - SauceLabs results available at http://saucelabs.com/jobs/8cd7d4457eb2415580de95328939da08
[firefox latest Windows 10 #11] 
[firefox latest Windows 10 #11] /opt/jenkins/workspace/ightly_RPA_rpa-jui-webapp_master/node_modules/protractor/built/driverProviders/sauce.js:35
[firefox latest Windows 10 #11]                         throw new Error('Error updating Sauce pass/fail status: ' + util.inspect(err));
[firefox latest Windows 10 #11]                               ^
[firefox latest Windows 10 #11] Error: Error updating Sauce pass/fail status: 'Could not parse response: Not found'
[firefox latest Windows 10 #11]     at sauceServer_.updateJob (/opt/jenkins/workspace/ightly_RPA_rpa-jui-webapp_master/node_modules/protractor/built/driverProviders/sauce.js:35:31)
[firefox latest Windows 10 #11]     at IncomingMessage.<anonymous> (/opt/jenkins/workspace/ightly_RPA_rpa-jui-webapp_master/node_modules/saucelabs/lib/SauceLabs.js:321:13)
[firefox latest Windows 10 #11]     at emitNone (events.js:111:20)
[firefox latest Windows 10 #11]     at IncomingMessage.emit (events.js:208:7)
[firefox latest Windows 10 #11]     at endReadableNT (_stream_readable.js:1064:12)
[firefox latest Windows 10 #11]     at _combinedTickCallback (internal/process/next_tick.js:139:11)
[firefox latest Windows 10 #11]     at process._tickCallback (internal/process/next_tick.js:181:9)

- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by cnishina** [comment]
This appears to work for our sauce lab tests. Could you provide more info?

**Comment by coolboy0961** [comment]
I faced the same problem. You crossed max sessions that you can execute in same time.
I fixed it like this:
add `maxSessions: 1` above `multiCapabilities`.
