### ISSUE TITLE
browser.manage().logs().get(logging.Type.BROWSER) fails in Firefox

### ISSUE THREAD

**Issue by ovk** [angular/protractor#5263]
Bug report
---

- Node Version: `v12.4.0`
- Protractor Version: `5.4.2`
- Angular Version: `8.0.2`
- Browser(s): `Firefox 67.0.2 (64-bit)`
- Operating System and Version `Windows 10 / Debian Stretch`

Doing `browser.manage().logs().get(logging.Type.BROWSER)` in `afterEach` works successfully in Chrome but fails in Firefox:

```
[firefox #01]   workspace-project App
[firefox #01]     × should navigate to dashboard by default
[firefox #01]       - Failed: POST /session/38d9a7cc-6fd0-4ed9-af1c-6bb82f5cab2f/log did not match a known command
[firefox #01]           at Object.throwDecodedError (C:\Projects\src\node_modules\selenium-webdriver\lib\error.js:514:15)
[firefox #01]           at parseHttpResponse (C:\Projects\src\node_modules\selenium-webdriver\lib\http.js:519:13)
[firefox #01]           at C:\Projects\src\node_modules\selenium-webdriver\lib\http.js:441:30
[firefox #01]           at processTicksAndRejections (internal/process/task_queues.js:89:5)
[firefox #01]       From: Task: WebDriver.manage().logs().get(browser)
[firefox #01]           at Driver.schedule (C:\Projects\src\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
[firefox #01]           at Logs.get (C:\Projects\src\node_modules\selenium-webdriver\lib\webdriver.js:1731:25)
[firefox #01]           at Object.<anonymous> (C:\Projects\src\e2e\src\app.e2e-spec.ts:19:29)
[firefox #01]           at step (C:\Projects\src\node_modules\tslib\tslib.js:136:27)
[firefox #01]           at Object.next (C:\Projects\src\node_modules\tslib\tslib.js:117:57)
[firefox #01]           at C:\Projects\src\node_modules\tslib\tslib.js:110:75
[firefox #01]           at new Promise (<anonymous>)
[firefox #01]           at Object.__awaiter (C:\Projects\src\node_modules\tslib\tslib.js:106:16)
[firefox #01]           at UserContext.<anonymous> (C:\Projects\src\e2e\src\app.e2e-spec.ts:17:13)
[firefox #01]       From: Task: Run afterEach in control flow
[firefox #01]           at ControlFlow.emit (C:\Projects\src\node_modules\selenium-webdriver\lib\events.js:62:21)
[firefox #01]           at ControlFlow.shutdown_ (C:\Projects\src\node_modules\selenium-webdriver\lib\promise.js:2674:10)
[firefox #01]           at C:\Projects\src\node_modules\selenium-webdriver\lib\promise.js:2599:53
[firefox #01]       From asynchronous test:
[firefox #01]       Error:
[firefox #01]           at Suite.<anonymous> (C:\Projects\src\e2e\src\app.e2e-spec.ts:17:3)
[firefox #01]           at Object.<anonymous> (C:\Projects\src\e2e\src\app.e2e-spec.ts:4:1)
[firefox #01]           at Module._compile (internal/modules/cjs/loader.js:774:30)
[firefox #01]           at Module.m._compile (C:\Projects\src\node_modules\ts-node\src\index.ts:439:23)
[firefox #01]           at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
[firefox #01]           at Object.require.extensions.<computed> [as .ts] (C:\Projects\src\node_modules\ts-node\src\index.ts:442:12)
[firefox #01]
[firefox #01] **************************************************
[firefox #01] *                    Failures                    *
[firefox #01] **************************************************
[firefox #01]
[firefox #01] 1) workspace-project App should navigate to dashboard by default
[firefox #01]   - Failed: POST /session/38d9a7cc-6fd0-4ed9-af1c-6bb82f5cab2f/log did not match a known command
```

**Comment by JosephBittman** [comment]
My understanding is that the logging (optional) specification outlined in webdriver is currently only implemented by the chromedriver. Last I read, there were no other browsers that implemented this optional feature.
