### ISSUE TITLE
events.js:174 throw er; -> Error: write EPIPE

### ISSUE THREAD

**Issue by peterqt95** [angular/protractor#5283]
Hi, I was recently updated to Windows 10 so I'm not entirely sure what changed between Win7 -> Win10 that caused my protractor tests to stop working. I was hoping someone could help me figure out or where to look to help debug this issue!

Bug report
---

- Node Version: `v10.16.0`
- Protractor Version: `5.4.2`
- Angular Version: `7.1.4`
- Browser(s): `Firefox`
- Operating System and Version: `Win10 x64 bit`
- Your protractor configuration file:

```
exports.config = {
  allScriptsTimeout: 120000,
  specs: [
    './e2e/**/*.e2e-spec.ts'
  ],
  suites: {
    homepage: './e2e/homepage/**/*.e2e-spec.ts',
    createProposal: './e2e/create-proposal/**/*.e2e-spec.ts',
    updateProposal: './e2e/update-proposal/**/*.e2e-spec.ts',
    summaryProposal: './e2e/summary-proposal/**/*.e2e-spec.ts',
    costEstimator: './e2e/cost-estimator/**/*.e2e-spec.ts'
  },
  capabilities: {
    // 'browserName': 'chrome'
    browserName: 'firefox',
    marionette: true,
    acceptInsecureCerts : true,
  },
  SELENIUM_PROMISE_MANAGER: false,
  getPageTimeOut: 30000,
  directConnect: true,
  baseUrl: 'http://localhost:8080/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 9999999,
    print: function() {}
  },
  onPrepare() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
  }
};
```

- A relevant example test: `ng e2e`
- Output from running the test:

```
[10:53:46] E/downloader - undefined
[10:53:46] I/update - chromedriver: file exists C:\Infrastructure\Angular\idl-cost-diff\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_75.0.3770.140.zip
[10:53:46] I/update - chromedriver: unzipping chromedriver_75.0.3770.140.zip
[10:53:46] I/update - chromedriver: chromedriver_75.0.3770.140.exe up to date
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:762:20)
    at ChildProcess.target.send (internal/child_process.js:634:19)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (C:\Infrastructure\Angular\idl-cost-diff\node_modules\@angular-devkit\build-angular\src\utils\run-module-as-observable-fork.js:57:23)
    at Observable._trySubscribe (C:\Infrastructure\Angular\idl-cost-diff\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\Infrastructure\Angular\idl-cost-diff\node_modules\rxjs\internal\Observable.js:30:22)
    at C:\Infrastructure\Angular\idl-cost-diff\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult (C:\Infrastructure\Angular\idl-cost-diff\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at MergeMapSubscriber._innerSub (C:\Infrastructure\Angular\idl-cost-diff\node_modules\rxjs\internal\operators\mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (C:\Infrastructure\Angular\idl-cost-diff\node_modules\rxjs\internal\operators\mergeMap.js:76:14)
    at MergeMapSubscriber._next (C:\Infrastructure\Angular\idl-cost-diff\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\Infrastructure\Angular\idl-cost-diff\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (C:\Infrastructure\Angular\idl-cost-diff\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (C:\Infrastructure\Angular\idl-cost-diff\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (C:\Infrastructure\Angular\idl-cost-diff\node_modules\rxjs\internal\Subscriber.js:67:18)
    at C:\Infrastructure\Angular\idl-cost-diff\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:766:39)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by mijatovicmile** [comment]
I got the same error on Node.js 10.16.0, downgrading to 10.14.1 worked for me. 

Reference:
#https://github.com/angular/angular-cli/issues/13113

**Comment by peterqt95** [comment]
> 
> 
> @peterqt95, I got the same error on Node.js 10.16.0, downgrading to 10.14.1 worked for me.
> 
> Reference:
> #[angular/angular-cli#13113](https://github.com/angular/angular-cli/issues/13113)

Hey @mijatovicmile thanks for the reply! Downgrading back to 10.14.1 worked for me.

For those of you trying, I tried uninstalling 10.16.0 and then reinstalling 10.14.1 but that didn't work out. I had to run the command:

`npm install node@10.14.1` 

to downgrade my node version.

**Comment by jkuek** [comment]
I recently had the same problem, was trying to use 10.16.3 and 'ng e2e' failed in the same way.
Downgraded to 10.14.1 and everything is fine.

**Comment by RetinaInc** [comment]
Yes downgrading to 10.14.1. But downgrading is not a solution. What if I have to use newer node version? I faced this problem with 10.16.x. Did protractor fix it in new version? If so from which version it is working?

thank you.

**Comment by jkuek** [comment]
I just tried node 12.13.0 and it has the same issue

**Comment by Sathishchary** [comment]
I am also getting the same issue with v12.16.1.

**Comment by Garcia-JuanLuis** [comment]
Hello all, it's been almost a year since the last comment on this thread.  Anyone knows if Protractor addressed this?
I tried using Node 14.13.0 just now and still see the error.  I was just curious today about whether this has been addressed or not.  I have been using Node 10.14.1 as a "solution", ever since I first encountered this issue.
