### ISSUE TITLE
EPROTO with HTTPS seleniumAddress and a HTTP webDriverProxy

### ISSUE THREAD

**Issue by theredfish** [angular/protractor#5301]
Hello,

When webDriverProxy is configured with a HTTP proxy for both HTTP / HTTPS requests, and the seleniumAddress is configured with HTTPS, protractor returns a protocol error (EPROTO). There is no more EPROTO error if I configure the selenium address with the http protocol (for test purposes... I can't expose a http selenium grid)

Bug report
---

- Node Version: `10`
- Protractor Version: `^5.4.2`
- Browser(s): `ANY`
- Operating System and Version `ANY`
- Your protractor configuration file :
```javascript
exports.config = {
  seleniumAddress: "https://my-personal-grid/wd/hub",
  webDriverProxy: "http://my-proxy:80",
  specs: ["todo-spec.js"]
};
```
- A relevant example test :
```javascript
describe("angularjs homepage todo list", function() {
  it("should add a todo", function() {
    browser.get("https://angularjs.org");

    element(by.model("todoList.todoText")).sendKeys(
      "write first protractor test"
    );
    element(by.css('[value="add"]')).click();

    var todoList = element.all(by.repeater("todo in todoList.todos"));
    expect(todoList.count()).toEqual(3);
    expect(todoList.get(2).getText()).toEqual("write first protractor test");

    // You wrote your first test, cross it off the list
    todoList
      .get(2)
      .element(by.css("input"))
      .click();
    var completedAmount = element.all(by.css(".done-true"));
    expect(completedAmount.count()).toEqual(2);
  });
});
```
- Output from running the test :
```
[13:20:55] I/launcher - Running 1 instances of WebDriver
[13:20:55] I/hosted - Using the selenium server at https://my-personal-grid/wd/hub
[13:20:55] E/launcher - EPROTO write EPROTO 140064661423936:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

[13:20:55] E/launcher - Error: EPROTO write EPROTO 140064661423936:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at ClientRequest.<anonymous> (/protractor-example/protractor/node_modules/selenium-webdriver/http/index.js:238:15)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at TLSSocket.Socket._destroy (net.js:613:3)
    at TLSSocket.destroy (internal/streams/destroy.js:37:8)
From: Task: WebDriver.createSession()
    at Function.createSession (/protractor-example/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/protractor-example/protractor/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (/protractor-example/protractor/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/protractor-example/protractor/node_modules/selenium-webdriver/index.js:626:16)
    at Hosted.getNewDriver (/protractor-example/protractor/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/protractor-example/protractor/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/protractor-example/protractor/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/protractor-example/protractor/node_modules/q/q.js:834:54)
    at /protractor-example/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/protractor-example/protractor/node_modules/q/q.js:796:13)
[13:20:55] E/launcher - Process exited with error code 199
npm ERR! code ELIFECYCLE
npm ERR! errno 199
```
Check that HTTPS protocol isn't available
---
This command returns an unknown protocol error : 
```
curl --proxy "https://my-proxy:80" "https://www.google.com"
```
Because the proxy isn't configured with https. And in my case it's not something I can change.

Steps to reproduce the bug
---
Use nginx as a reverse proxy - by forwarding the http requests we don't care about the domain of the selenium address.

conf.js :
```javascript
exports.config = {
  seleniumAddress: "http://non-existing-grid-but-important-path/wd/hub",
  webDriverProxy: "http://localhost:80",
  specs: ["todo-spec.js"]
};
```

Nginx conf file :
```
worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass         https://my-real-selenium-hub-host;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
    }
}
```

Nginx Dockerfile:
```
FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
```

Commands to run :
```bash
docker build -t proxy .
docker run -p 80:80 -d proxy
protractor conf.js
```
**Then replace** `http://non-existing-grid-but-important-path/wd/hub` by `https://non-existing-grid-but-important-path/wd/hub` to notice the bug.

**Comment by theredfish** [comment]
And for those who can't update their proxy configuration, the "steps to reproduce the bug" section can be a workaround. A local reverse proxy and a fake selenium hub endpoint both using http.

**Comment by theredfish** [comment]
It seems related to the selenium-webdriver library so I close this issue. You can find the issue here : https://github.com/SeleniumHQ/selenium/issues/7509
