### ISSUE TITLE
E/launcher - Error: Server terminated early with status 1

### ISSUE THREAD

**Issue by theunreal** [angular/protractor#5303]
Bug report
---

- Node Version: `10.16.0`
- Protractor Version: `5.4.2`
- Angular Version: `9.0.0-next.0`
- Browser(s): ``
- Operating System and Version `Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.10 (Santiago)
Release:        6.10
Codename:       Santiago`
- Your protractor configuration file:
```

// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

const { SpecReporter } = require('jasmine-spec-reporter');

exports.config = {
  allScriptsTimeout: 11000,
  baseUrl: 'https://10.56.196.184:8443/',
  specs: [
    './e2e/login.e2e.spec.ts',
    './e2e/analytics.e2e-spec.ts',
    './e2e/cloud.e2e-spec.ts',
    './e2e/ppack.e2e-spec.ts',
    './e2e/connectors.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  framework: 'jasmine2',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
  },
  onPrepare() {
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
    const jasmineReporters = require('jasmine-reporters');
    jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
      consolidateAll: true,
      savePath: './',
      filePrefix: 'xmlresults'
    }))
  },
  onComplete: function() {
    var browserName, browserVersion;
    var capsPromise = browser.getCapabilities();

    capsPromise.then(function (caps) {
      browserName = caps.get('browserName');
      browserVersion = caps.get('version');

      var HTMLReport = require('protractor-html-reporter');

      testConfig = {
        reportTitle: 'Test Execution Report',
        outputPath: './',
        screenshotPath: './screenshots',
        testBrowser: browserName,
        browserVersion: browserVersion,
        modifiedSuiteName: false,
        screenshotsOnlyOnFailure: true
      };
      new HTMLReport().from('xmlresults.xml', testConfig);
    });
  }
};
```
Error when running npm run e2e:
```

> ng e2e --devServerTarget

[13:43:51] I/file_manager - creating folder project-folder/node_modules/protractor/node_modules/webdriver-manager/selenium
[13:43:51] I/config_source - curl -oproject-folder/node_modules/protractor/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
[13:43:52] I/downloader - curl -oproject-folder/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_74.0.3729.6.zip https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
[13:43:53] I/update - chromedriver: unzipping chromedriver_74.0.3729.6.zip
[13:43:53] I/update - chromedriver: setting permissions to 0755 for project-folder/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_74.0.3729.6
[13:43:54] I/launcher - Running 1 instances of WebDriver
[13:43:54] I/direct - Using ChromeDriver directly...
[13:43:54] E/launcher - Server terminated early with status 1
[13:43:54] E/launcher - Error: Server terminated early with status 1
    at earlyTermination.catch.e (project-folder/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:252:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (project-folder/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (project-folder/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:761:15)
    at Direct.getNewDriver (project-folder/node_modules/protractor/built/driverProviders/direct.js:77:33)
    at Runner.createBrowser (project-folder/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (project-folder/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (project-folder/node_modules/q/q.js:834:54)
    at project-folder/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (project-folder/node_modules/q/q.js:796:13)
    at project-folder/node_modules/q/q.js:556:49
    at runSingle (project-folder/node_modules/q/q.js:137:13)
[13:43:54] E/launcher - Process exited with error code 199
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dashboard@1.0.0 e2e: `ng e2e --devServerTarget`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sd-avc-dashboard@1.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /users/pqembb/.npm/_logs/2019-08-18T10_43_54_484Z-debug.log


```

**Comment by vaishalisoni1093** [comment]
How did you resolved it ?
