### ISSUE TITLE
Protractor not running in Chrome browser, only Firefox

### ISSUE THREAD

**Issue by DeathFenix** [angular/protractor#5335]
I need a help please.

I'm trying to run my tests and is occurring this error, If i change the browser to firefox it's run normally.
My tests was running at last week.
I already updated all tools but the error continue, only in chrome using directConnect, but if a use the local server, the same error occur. Could help me? Thanks!!

Bug report
---

- Node Version: `12.9.0`
- Protractor Version: `5.4.2`
- Angular Version: `6.0`
- Browser(s): `77.3865.120`
- Operating System and Version `Win 10 x64`
- Your protractor configuration file--------------------------------------------------------------

//------ PARÂMETROS
var date = new Date();
var Jasmine2HtmlCliReporter = require('protractor-jasmine2-html-cli-reporter');
var CONSTANTES = require('./constantes.js');
var estoria = 'Testes Regressão';                                                                                  // <----- alterar a cada teste                                                                         
var diretorio = '../../Evidencias/' + estoria + '/' + date.getFullYear() + ( date.getMonth() + 1 ) + date.getDate() + date.getHours() + date.getMinutes() + '/';

//------ CONFIGURAÇÕES
exports.config = {

    allScriptsTimeout: 90000,
    specs: [CONSTANTES.DIR_CHECKLIST_ELETRONICO_F1 + '*.js' ],
    framework: 'jasmine2',
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 300000
    },
    capabilities: {
        browserName: 'chrome', 
        
    },
    
    //------ CONFIG PRÉ TESTE
    onPrepare: function() {
        browser.manage().window().maximize();
        jasmine.getEnv().addReporter(new Jasmine2HtmlCliReporter({
            savePath: diretorio,
            screenshotsFolder: 'image'
            })
        );
        
    }//end onPrepare
    
}
- A relevant example test
Anyone

- Output from running the test ----------------------------------------------------------------

C:\workspace\transformation-automationtest\E9404 - Service Transformation>protractor protractor.config.js
[13:27:57] I/launcher - Running 1 instances of WebDriver
[13:27:57] I/direct - Using ChromeDriver directly...
[13:27:59] E/launcher - Server terminated early with status 3221225477
[13:27:59] E/launcher - Error: Server terminated early with status 3221225477
    at C:\Users\aleandr1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\remote\index.js:252:52
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\aleandr1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\aleandr1\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:761:15)
    at Direct.getNewDriver (C:\Users\aleandr1\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\direct.js:77:33)
    at Runner.createBrowser (C:\Users\aleandr1\AppData\Roaming\npm\node_modules\protractor\built\runner.js:195:43)
    at C:\Users\aleandr1\AppData\Roaming\npm\node_modules\protractor\built\runner.js:339:29
    at _fulfilled (C:\Users\aleandr1\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at C:\Users\aleandr1\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\aleandr1\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\aleandr1\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\Users\aleandr1\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:137:13)
[13:27:59] E/launcher - Process exited with error code 199

**Comment by typhoon2099** [comment]
This is related to angular/webdriver-manager#420

**Comment by DeathFenix** [comment]
I found the problem in my case. 
I had installed ANSICON 1.31 to showning coloured output in CMD, I don't know why it was cousing a problem to webdriver.

I just delete the ansicon files and the problem was solved.

Thanks for help.
