### ISSUE TITLE
Process exited with error code 199 just after install chrome v78

### ISSUE THREAD

**Issue by wupaz** [angular/protractor#5341]
Bug report

HI,

As soon I update my chrome to 78 I got this error.

- I clean all node_module 
- webdriver-manager update
Like 20 times nothing work... just before I update to 78 all work fine.

I run out of idea

Dump Error

`[07:37:12] I/update - chromedriver: file exists C:\DevOps\Gustav\Fusion\Fusion\node_modules\webdriver-manager\selenium\chromedriver_78.0.3904.70.zip
[07:37:12] I/update - chromedriver: unzipping chromedriver_78.0.3904.70.zip
[07:37:12] I/update - chromedriver: chromedriver_78.0.3904.70.exe up to date
[07:37:13] I/launcher - Running 1 instances of WebDriver
[07:37:13] I/direct - Using ChromeDriver directly...`

`DevTools listening on ws://127.0.0.1:12672/devtools/browser/b109baf5-5552-437b-83a2-d1c0a653ef3c
[07:37:14] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 76
  (Driver info: chromedriver=76.0.3809.12 (220b19a666554bdcac56dff9ffd44c300842c933-refs/branch-heads/3809@{#83}),platform=Windows NT 10.0.18362 x86_64)
[07:37:14] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 76
  (Driver info: chromedriver=76.0.3809.12 (220b19a666554bdcac56dff9ffd44c300842c933-refs/branch-heads/3809@{#83}),platform=Windows NT 10.0.18362 x86_64)
    at Object.checkLegacyResponse (C:\DevOps\Gustav\Fusion\Fusion\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\DevOps\Gustav\Fusion\Fusion\node_modules\selenium-webdriver\lib\http.js:509:13)
    at C:\DevOps\Gustav\Fusion\Fusion\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\DevOps\Gustav\Fusion\Fusion\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\DevOps\Gustav\Fusion\Fusion\node_modules\selenium-webdriver\chrome.js:761:15)
    at Direct.getNewDriver (C:\DevOps\Gustav\Fusion\Fusion\node_modules\protractor\built\driverProviders\direct.js:77:33)
    at Runner.createBrowser (C:\DevOps\Gustav\Fusion\Fusion\node_modules\protractor\built\runner.js:195:43)
    at C:\DevOps\Gustav\Fusion\Fusion\node_modules\protractor\built\runner.js:339:29
    at _fulfilled (C:\DevOps\Gustav\Fusion\Fusion\node_modules\q\q.js:834:54)
    at C:\DevOps\Gustav\Fusion\Fusion\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\DevOps\Gustav\Fusion\Fusion\node_modules\q\q.js:796:13)
    at C:\DevOps\Gustav\Fusion\Fusion\node_modules\q\q.js:556:49
    at runSingle (C:\DevOps\Gustav\Fusion\Fusion\node_modules\q\q.js:137:13)
[07:37:14] E/launcher - Process exited with error code 199`
`

Info From webdriver status
[07:35:58] I/status - selenium standalone version available: 3.141.59 [last]
[07:35:58] I/status - chromedriver version available: 78.0.3904.70 [last]
[07:35:58] I/status - geckodriver version available: v0.26.0 [last]

- Node Version: 12.3.1
- Protractor Version: 5.4.2
- Angular Version: 8.2
- Browser(s): Chrome 78.0.3904.70 (Official Build) (64-bit)
- Operating System and Version Windows 10 Pro
- Your protractor configuration file
[protractor.conf.zip](https://github.com/angular/protractor/files/3767333/protractor.conf.zip)

Eric Julien

**Comment by tmburnell** [comment]
I spent several hours on this until i upgraded Protractor. 
When you run `webdriver-manager update` does it say `76` or `78`?

**Comment by pawelusfr** [comment]
@wupaz you have to update your chromedriver. Might be that you're locked in an older version of webdriver-manager that doesn't download chromedriver 78 for you. Doing `npm install -f protractor` should help for that.

**Comment by wupaz** [comment]
OMG Thanks a lot @pawelusfr  !

**Comment by nlahouel** [comment]
@wupaz Worked for me also!! After updating angular, ng e2e stopped working. This was the reason I think. Thanks a lot.
