### ISSUE TITLE
Npm failed with return code: 199 E/launcher - unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by AnaPena** [angular/protractor#5350]
I'm Getting error when running protractor on azure devops build. Same configuration and commands work well on localhost, npm install and webdriver-manager update tasks are completed with success

Protractor configuration:

    directConnect: true,
    capabilities: {
      'browserName': 'chrome',
      'binary': 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'
    },

Error:

2019-11-06T14:08:18.4772316Z [15:08:18] E/launcher - unknown error: cannot find Chrome binary
2019-11-06T14:08:18.4772386Z   (Driver info: chromedriver=78.0.3904.11 (eaaae9de6b8999773fa33f92ce1e1bbe294437cf-refs/branch-heads/3904@{#86}),platform=Windows NT 6.3.9600 x86_64)
2019-11-06T14:08:18.4772455Z [15:08:18] E/launcher - WebDriverError: unknown error: cannot find Chrome binary
2019-11-06T14:08:18.4772521Z   (Driver info: chromedriver=78.0.3904.11 (eaaae9de6b8999773fa33f92ce1e1bbe294437cf-refs/branch-heads/3904@{#86}),platform=Windows NT 6.3.9600 x86_64)
2019-11-06T14:08:18.4772577Z     at Object.checkLegacyResponse (C:\Build_Agents\1\_work\159\s\test-suite\node_modules\selenium-webdriver\lib\error.js:546:15)
2019-11-06T14:08:18.4772651Z     at parseHttpResponse (C:\Build_Agents\1\_work\159\s\test-suite\node_modules\selenium-webdriver\lib\http.js:509:13)
2019-11-06T14:08:18.4772712Z     at doSend.then.response (C:\Build_Agents\1\_work\159\s\test-suite\node_modules\selenium-webdriver\lib\http.js:441:30)
2019-11-06T14:08:18.4772772Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-11-06T14:08:18.4773736Z From: Task: WebDriver.createSession()
2019-11-06T14:08:18.4773796Z     at Function.createSession (C:\Build_Agents\1\_work\159\s\test-suite\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
2019-11-06T14:08:18.4773857Z     at Function.createSession (C:\Build_Agents\1\_work\159\s\test-suite\node_modules\selenium-webdriver\chrome.js:761:15)
2019-11-06T14:08:18.4773940Z     at Direct.getNewDriver (C:\Build_Agents\1\_work\159\s\test-suite\node_modules\protractor\built\driverProviders\direct.js:77:33)
2019-11-06T14:08:18.4774001Z     at Runner.createBrowser (C:\Build_Agents\1\_work\159\s\test-suite\node_modules\protractor\built\runner.js:195:43)
2019-11-06T14:08:18.4774071Z     at q.then.then (C:\Build_Agents\1\_work\159\s\test-suite\node_modules\protractor\built\runner.js:339:29)
2019-11-06T14:08:18.4774522Z     at _fulfilled (C:\Build_Agents\1\_work\159\s\test-suite\node_modules\q\q.js:834:54)
2019-11-06T14:08:18.4774615Z     at C:\Build_Agents\1\_work\159\s\test-suite\node_modules\q\q.js:863:30
2019-11-06T14:08:18.4774676Z     at Promise.promise.promiseDispatch (C:\Build_Agents\1\_work\159\s\test-suite\node_modules\q\q.js:796:13)
2019-11-06T14:08:18.4774746Z     at C:\Build_Agents\1\_work\159\s\test-suite\node_modules\q\q.js:556:49
2019-11-06T14:08:18.4774806Z     at runSingle (C:\Build_Agents\1\_work\159\s\test-suite\node_modules\q\q.js:137:13)
2019-11-06T14:08:18.4774899Z [15:08:18] E/launcher - Process exited with error code 199
2019-11-06T14:08:18.5552247Z 13 verbose stack Exit status 199

**Comment by NicoForce** [comment]
Share your configuration file and the complete logs for the process including the npm install and webdriver update, to help identify the issue.

**Comment by AnaPena** [comment]
complete logs and config attached.
[config.txt](https://github.com/angular/protractor/files/3820171/config.txt)
[logs.txt](https://github.com/angular/protractor/files/3820173/logs.txt)

**Comment by NicoForce** [comment]
Try removing the **binary** option from the capabilities. It might not work locally. But let's see how it does on the Azure Cloud.

**Comment by AnaPena** [comment]
> Try removing the **binary** option from the capabilities. It might not work locally. But let's see how it does on the Azure Cloud.

I have the same result when running the tests:
2019-11-07T14:57:32.4566375Z Generating script.
2019-11-07T14:57:32.4890325Z Script contents:
2019-11-07T14:57:32.4898522Z npm run tests
2019-11-07T14:57:32.5194974Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "C:\Build_Agents\1\_work\_temp\9fd8d3ec-884a-4f6b-b031-165fbdbec29d.cmd""
2019-11-07T14:57:33.6329423Z 
2019-11-07T14:57:33.6331043Z > tests@1.0.0 tests C:\Build_Agents\1\_work\159\s\tests
2019-11-07T14:57:33.6332430Z > protractor conf/conf.js
2019-11-07T14:57:33.6333756Z 
2019-11-07T14:57:37.5464706Z [15:57:37] E/launcher - unknown error: cannot find Chrome binary
2019-11-07T14:57:37.5593446Z   (Driver info: chromedriver=78.0.3904.11 (eaaae9de6b8999773fa33f92ce1e1bbe294437cf-refs/branch-heads/3904@{#86}),platform=Windows NT 6.3.9600 x86_64)
2019-11-07T14:57:37.5594204Z [15:57:37] E/launcher - WebDriverError: unknown error: cannot find Chrome binary
2019-11-07T14:57:37.5594479Z   (Driver info: chromedriver=78.0.3904.11 (eaaae9de6b8999773fa33f92ce1e1bbe294437cf-refs/branch-heads/3904@{#86}),platform=Windows NT 6.3.9600 x86_64)
2019-11-07T14:57:37.5594712Z     at Object.checkLegacyResponse (C:\Build_Agents\1\_work\159\s\tests\node_modules\selenium-webdriver\lib\error.js:546:15)
2019-11-07T14:57:37.5594986Z     at parseHttpResponse (C:\Build_Agents\1\_work\159\s\tests\node_modules\selenium-webdriver\lib\http.js:509:13)
2019-11-07T14:57:37.5595242Z     at doSend.then.response (C:\Build_Agents\1\_work\159\s\tests\node_modules\selenium-webdriver\lib\http.js:441:30)
2019-11-07T14:57:37.5595489Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-11-07T14:57:37.5596043Z From: Task: WebDriver.createSession()
2019-11-07T14:57:37.5596276Z     at Function.createSession (C:\Build_Agents\1\_work\159\s\tests\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
2019-11-07T14:57:37.5596532Z     at Function.createSession (C:\Build_Agents\1\_work\159\s\tests\node_modules\selenium-webdriver\chrome.js:761:15)
2019-11-07T14:57:37.5596765Z     at Direct.getNewDriver (C:\Build_Agents\1\_work\159\s\tests\node_modules\protractor\built\driverProviders\direct.js:77:33)
2019-11-07T14:57:37.5596988Z     at Runner.createBrowser (C:\Build_Agents\1\_work\159\s\tests\node_modules\protractor\built\runner.js:195:43)
2019-11-07T14:57:37.5597514Z     at q.then.then (C:\Build_Agents\1\_work\159\s\tests\node_modules\protractor\built\runner.js:339:29)
2019-11-07T14:57:37.5597747Z     at _fulfilled (C:\Build_Agents\1\_work\159\s\tests\node_modules\q\q.js:834:54)
2019-11-07T14:57:37.5597993Z     at C:\Build_Agents\1\_work\159\s\tests\node_modules\q\q.js:863:30
2019-11-07T14:57:37.5598240Z     at Promise.promise.promiseDispatch (C:\Build_Agents\1\_work\159\s\tests\node_modules\q\q.js:796:13)
2019-11-07T14:57:37.5598468Z     at C:\Build_Agents\1\_work\159\s\tests\node_modules\q\q.js:556:49
2019-11-07T14:57:37.5598710Z     at runSingle (C:\Build_Agents\1\_work\159\s\tests\node_modules\q\q.js:137:13)
2019-11-07T14:57:37.5598924Z [15:57:37] E/launcher - Process exited with error code 199
2019-11-07T14:57:37.5722417Z npm ERR! code ELIFECYCLE
2019-11-07T14:57:37.5722961Z npm ERR! errno 199
2019-11-07T14:57:37.5724637Z npm ERR! tests@1.0.0 tests: `protractor conf/conf.js`
2019-11-07T14:57:37.5724805Z npm ERR! Exit status 199
2019-11-07T14:57:37.5725363Z npm ERR! 
2019-11-07T14:57:37.5725484Z npm ERR! Failed at the tests@1.0.0 tests script.
2019-11-07T14:57:37.5726243Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-11-07T14:57:37.5795960Z 
2019-11-07T14:57:37.5856275Z npm ERR! A complete log of this run can be found in:
2019-11-07T14:57:37.5857039Z npm ERR!     C:\Users\tfsservice\AppData\Roaming\npm-cache\_logs\2019-11-07T14_57_37_558Z-debug.log
2019-11-07T14:57:37.7002846Z ##[error]Cmd.exe exited with code '199'.

**Comment by NicoForce** [comment]
How does your devops build work. What os are you trying to automate on. Is it a docker image or something?, is chrome even installed in the machine that you are trying to test on?
