### ISSUE TITLE
ETIMEDOUT connect ETIMEDOUT

### ISSUE THREAD

**Issue by jake-lai** [angular/protractor#5363]
Hi there!
We are seeing this ETIMEDOUT connect ETIMEDOUT issue on our nightly automation run, it happens quite frequently but not consistenly, we are running our automation on selenium docker

"
Error: ETIMEDOUT connect ETIMEDOUT 52.44.154.9:443
    at ClientRequest.(anonymous) (/home/jenkins/workspace/rerun_2019-R2-lightning-enhancement_b-onDemand/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:238:15)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9"

This is the issue we are seeing

- Node Version: `6.0.46`
- Protractor Version: `5.4.2`
- Browser(s): `Chrome 76`
- Operating System and Version `macOS`
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

@smfontevan

**Comment by Jayasankar-m** [comment]
@jake-lai 

you may try out this patch.. seems to be a similar issue
https://github.com/angular/protractor/issues/4706#issuecomment-393004887
