### ISSUE TITLE
My {Protractor script is timeout with angular web application. 

### ISSUE THREAD

**Issue by nileshraval** [angular/protractor#5364]
I am new in protractor I have run script and getting below error due to my application test ability is not  true.  I have also try ng12hybrid = true. but it seem to failed. could u please look in to this issue and I hope this issue is solved in next release.
**spec file**
describe('angularjs homepage todo list', function() {
  it('should add a todo', function() {
//browser.waitForAngularEnabled(false);
	  // browser.ignoreSynchronization = true;
	  browser.get('https://uat.flourishsoftware.com').then(function() {
	  
		  
	  browser.manage().window().maximize();	
      browser.manage().timeouts().implicitlyWait(60000);	
      element(by.id('username')).click();
      element(by.id('username')).sendKeys('jgarcia_demo@flourishsoftware.com');
        element(by.id('password')).sendKeys('abc!');
        element(by.xpath("(//span[contains(text(),'Log In')])[2]")).click();
});

**config file**

exports.config = {
   directConnect: true,     
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['todo-spec.js'],
  
  
  jasmineNodeOpts: {
	defaultTimeoutInterval: 120000
	
	
  
  },
  useAllAngular2AppRoots:true,	
};

errors:
Failed: script timeout
      (Session info: chrome=78.0.3904.108)
      (Driver info: chromedriver=77.0.3865.10 (bc3579f611bbc73331171afe020ec7a45e6ccc55-refs/branch-heads/3865@{#93}),platform=Windows NT 10.0.14393 x86_64)[0m
  Stack:
    ScriptTimeoutError: script timeout
      (Session info: chrome=78.0.3904.108)
      (Driver info: chromedriver=77.0.3865.10 (bc3579f611bbc73331171afe020ec7a45e6ccc55-refs/branch-heads/3865@{#93}),platform=Windows NT 10.0.14393 x86_64)
        at Object.checkLegacyResponse (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
        at parseHttpResponse (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
        at doSend.then.response (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    From: Task: Protractor.waitForAngular() - Locator: By(css selector, *[id="username"])
        at Driver.schedule (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
        at ProtractorBrowser.executeAsyncScript_ (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\built\browser.js:425:28)
        at angularAppRoot.then (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\built\browser.js:456:33)
        at ManagedPromise.invokeCallback_ (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
        at TaskQueue.execute_ (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at asyncRun (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
        at C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
        at process._tickCallback (internal/process/next_tick.js:68:7)Error
        at ElementArrayFinder.applyAction_ (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
        at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
        at ElementFinder.(anonymous function).args [as click] (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
        at C:\Users\DELL\Protractor-Testing\protractordemo\todo-spec.js:10:34
        at ManagedPromise.invokeCallback_ (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
        at TaskQueue.execute_ (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
        at TaskQueue.executeNext_ (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
        at asyncRun (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
        at C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
        at process._tickCallback (internal/process/next_tick.js:68:7)
    From: Task: Run it("should add a todo") in control flow
        at UserContext.<anonymous> (C:\Users\DELL\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (C:\Users\DELL\Protractor-Testing\protractordemo\todo-spec.js:2:3)
        at Object.<anonymous> (C:\Users\DELL\Protractor-Testing\protractordemo\todo-spec.js:1:1)
        at Module._compile (internal/modules/cjs/loader.js:778:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by IgorSasovets** [comment]
Hi, @nileshraval ! Did you try to enable `browser.ignoreSynchronization = true;` command and rerun the tests? Also, please update your driver using the `webdriver-manager update` command

**Comment by nileshraval** [comment]
Hi, i have tried both waitforangular and ignoresynchnization in this case it is working but this will use for non angular components





---- On Fri, 29 Nov 2019 15:44:42 +0530 notifications@github.com wrote ----



Hi, @nileshraval ! Did you try to enable browser.ignoreSynchronization = true; command and rerun the tests? Also, please update your driver using the webdriver-manager update command

**Comment by IgorSasovets** [comment]
I also experienced a lot of issues when was working on tests suites for Angular 4+ and `ignoreSynchronization` option helped me to successfully resolve the issues. Protractor offers many different waiters, also you can define your own to handle synchronization issues.

**Comment by prashanth-sams** [comment]
You've to set the `allScriptsTimeout` to achieve; the actual solution is the fix on application level. Please read here for more info.
https://stackoverflow.com/a/64857681/1482709
