### ISSUE TITLE
Getting error while starting webdriver and running protractor command.

### ISSUE THREAD

**Issue by SinghRajKr** [angular/protractor#5395]
[16:10:07] I/launcher - Running 1 instances of WebDriver
[16:10:07] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[16:10:08] E/launcher - **session not created: This version of ChromeDriver only supports Chrome version 80**
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-XXXX', ip: 'X.X.X.X', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
**Driver info: driver.version: unknown**
remote stacktrace: Backtrace:
        Ordinal0 [0x00520AE3+1706723]
        Ordinal0 [0x004868C1+1075393]
        Ordinal0 [0x003FDFA9+516009]
        Ordinal0 [0x00390554+66900]
        Ordinal0 [0x0038CCE2+52450]
        Ordinal0 [0x003ABFD7+180183]
        Ordinal0 [0x003ABDDD+179677]
        Ordinal0 [0x003A9D4B+171339]
        Ordinal0 [0x00391D4A+73034]
        Ordinal0 [0x00392DC0+77248]
        Ordinal0 [0x00392D59+77145]
        Ordinal0 [0x0049BB37+1162039]
        GetHandleVerifier [0x005BA7C6+508998]
        GetHandleVerifier [0x005BA504+508292]
        GetHandleVerifier [0x005CF617+594583]
        GetHandleVerifier [0x005BB036+511158]
        Ordinal0 [0x00493FFC+1130492]
        Ordinal0 [0x0049D49B+1168539]
        Ordinal0 [0x0049D603+1168899]
        Ordinal0 [0x004B5B05+1268485]
        BaseThreadInitThunk [0x77156359+25]
        RtlGetAppContainerNamedObjectPath [0x77E97B74+228]
        RtlGetAppContainerNamedObjectPath [0x77E97B44+180]

 

[16:10:08] E/launcher - **SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 80**
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'DESKTOP-XXXX', ip: 'X.X.X.X', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
**Driver info: driver.version: unknown**
remote stacktrace: Backtrace:
        Ordinal0 [0x00520AE3+1706723]
        Ordinal0 [0x004868C1+1075393]
        Ordinal0 [0x003FDFA9+516009]
        Ordinal0 [0x00390554+66900]
        Ordinal0 [0x0038CCE2+52450]
        Ordinal0 [0x003ABFD7+180183]
        Ordinal0 [0x003ABDDD+179677]
        Ordinal0 [0x003A9D4B+171339]
        Ordinal0 [0x00391D4A+73034]
        Ordinal0 [0x00392DC0+77248]
        Ordinal0 [0x00392D59+77145]
        Ordinal0 [0x0049BB37+1162039]
        GetHandleVerifier [0x005BA7C6+508998]
        GetHandleVerifier [0x005BA504+508292]
        GetHandleVerifier [0x005CF617+594583]
        GetHandleVerifier [0x005BB036+511158]
        Ordinal0 [0x00493FFC+1130492]
        Ordinal0 [0x0049D49B+1168539]
        Ordinal0 [0x0049D603+1168899]
        Ordinal0 [0x004B5B05+1268485]
        BaseThreadInitThunk [0x77156359+25]
        RtlGetAppContainerNamedObjectPath [0x77E97B74+228]
        RtlGetAppContainerNamedObjectPath [0x77E97B44+180]

 

    at Object.checkLegacyResponse (C:\Users\B Priyanka\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\B Priyanka\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at C:\Users\B Priyanka\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

> From: Task: WebDriver.createSession()

    at Function.createSession (C:\Users\B Priyanka\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\B Priyanka\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:761:15)
    at createDriver (C:\Users\B Priyanka\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\B Priyanka\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:626:16)
    at Hosted.getNewDriver (C:\Users\B Priyanka\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\B Priyanka\AppData\Roaming\npm\node_modules\protractor\built\runner.js:195:43)
    at C:\Users\B Priyanka\AppData\Roaming\npm\node_modules\protractor\built\runner.js:339:29
    at _fulfilled (C:\Users\B Priyanka\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at C:\Users\B Priyanka\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Users\B Priyanka\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
[16:10:08] E/launcher - Process exited with error code 199

**Comment by Harsha509** [comment]
Seems like issue with capabilities. Can you please ping your capabilities here

**Comment by SinghRajKr** [comment]
@Harsha509  with the same capabilities it was working from the last few months.

**Comment by Harsha509** [comment]
Yes it will work. from chrome 76+ there are few changes in javascript in each chromedrivers as chrome now purely listens to webdriver protocols and few legacy protocols are deprecated.

**Comment by Harsha509** [comment]
okay. apologies i have overlooked. which version of chrome youre using ? if you are using 80 have you done webdriver-manager update

**Comment by SinghRajKr** [comment]
Yes, I am updating and starting webdriver-manager.

**Comment by Harsha509** [comment]
Okay. if u update and start the webdriver-manager i would like to look into logs from webdriver-manager start. can you please provide ?

**Comment by SinghRajKr** [comment]
After updating protractor I can run the test suite now.

**Comment by Harsha509** [comment]
Great.
