### ISSUE TITLE
Cannot run protractor with nodejs 14

### ISSUE THREAD

**Issue by tschumann** [angular/protractor#5463]
Bug report
---

- Node Version: `14.7.0`
- Protractor Version: `7.0.0`
- Angular Version: `9.1.0`

When I run `node node_modules/.bin/protractor dist/out-tsc/e2e/config/protractor.conf.js --verbose` I get the following:
```
[05:03:39] E/configParser - Error code: 105
[05:03:39] E/configParser - Error message: failed loading configuration file dist/out-tsc/e2e/config/protractor.conf.js
[05:03:39] E/configParser - Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/src/project/dist/out-tsc/e2e/config/protractor.conf.js
require() of ES modules is not supported.
require() of /usr/src/project/dist/out-tsc/e2e/config/protractor.conf.js from /usr/src/project/node_modules/protractor/built/configParser.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename protractor.conf.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/src/project/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:13)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at ConfigParser.addFileConfig (/usr/src/project/node_modules/protractor/built/configParser.js:135:26)
    at Object.initFn [as init] (/usr/src/project/node_modules/protractor/built/launcher.js:93:22)
    at Object.<anonymous> (/usr/src/project/node_modules/protractor/built/cli.js:227:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

This seems to be because configParser.js uses require but my protractor.conf.js uses import - is this setup just not supported?
I do not get this error with nodejs 10 but I do get it with nodejs 12.

**Comment by andredesousa** [comment]
Try to use:

    {
      "extends": "../tsconfig.json",
      "compilerOptions": {
        "baseUrl": "./",
        "module": "commonjs",
        "outDir": "./dist/out-tsc",
        "target": "es5",
        "typeRoots": [
          "node_modules/@types"
        ]
      }
    }

It´s works for me. I have Angular 9.1.4 and Node 14.15.0.
However, I think that Protractor doesn't support Node 14. It´s random but I have the next problem:

    Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:52810
