### ISSUE TITLE
if element.isPresent() returns false , protractor hangs inside then() block and jasmine spec times out

### ISSUE THREAD

**Issue by alirezadarban** [angular/protractor#5485]
Hi there!

Scenario:
In my page, there is a welcome modal that covers the navbar. I want to test the navbar functionality so I should close the modal first to be able to click on the navbar. 
1 - The protractor runs the first test: `cancel-icon(close button)` exist in the DOM > isPresent() returns `true` > Protractor clicks on it and close the modal. Everything is OK.
2 - It runs the 2nd test and the browser gets the page again. This time `cancel-icon(close button)` doesn't exist in the DOM >  isPresent() should return false but it hangs and return nothing till the Jasmine spec times out > The test fails.

This is my code:
```
describe(My test', function () { 
    beforeEach(function () {
        browser.get(url);
    });

    it('The user clicks on `Discover` in navbar, app-feed-discover should be displayed.', async function () {
        let result = await element(by.id('cancel-icon')).isPresent();
        if (result) await element(by.id('cancel-icon')).click();
        await element(by.css('app-feed-item-component:nth-of-type(1) > div')).click();
        expect(element(by.css('app-feed-discover')).isPresent()).toBeTruthy();
    });

    it('The user clicks on `Products` in navbar, app-products-discover should be displayed.', async function () {
        let result = await element(by.id('cancel-icon')).isPresent();
        if (result) await element(by.id('cancel-icon')).click();
        await element(by.css('app-feed-item-component:nth-of-type(2) > div')).click();
        expect(element(by.css('app-products-discover')).isPresent()).toBeTruthy();
    });
```
I got this error:
```
[11:21:18] I/launcher - Running 1 instances of WebDriver
[11:21:18] I/local - Starting selenium standalone server...
[11:21:19] I/local - Selenium standalone server started at http://192.168.5.199:50919/wd/hub
Started
.FA Jasmine spec timed out. Resetting the WebDriver Control Flow.


Failures:
1) My test The user clicks on `Products` in navbar, app-products-discover should be displayed.
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at listOnTimeout (internal/timers.js:554:17)
        at processTimers (internal/timers.js:497:7)

2 specs, 1 failure
Finished in 247.172 seconds

[11:25:28] I/local - Shutting down selenium standalone server.
[11:25:28] I/launcher - 0 instance(s) of WebDriver still running
[11:25:28] I/launcher - chrome #01 failed 1 test(s)
[11:25:28] I/launcher - overall: 1 failed spec(s)
[11:25:28] E/launcher - Process exited with error code 1
```
It's my conf.js
```
exports.config = {
    framework: 'jasmine',
    specs: ['final.js'],
    getPageTimeout: 30000,
    allScriptsTimeout: 30000,
    jasmineNodeOpts: {
        defaultTimeoutInterval: 30000
    },
    onPrepare: function () {
        browser.manage().timeouts().implicitlyWait(30000);
    }
    ,
    multiCapabilities: [
        {browserName: 'chrome'}
    ]
}
```

- Node Version: `v14.15.3`
- Protractor Version: `v7.0.0`
- Angular Version: `v10.0.3`
- Browser(s): `Chrome`
- Operating System and Version `MacOS Catalina v10.15.7`

**Comment by alirezadarban** [comment]
While isPresent() doesn’t work properly if an element doesn’t exist (it hangs), we can use browser.executeScript instead. It works fine!

```let result = await browser.executeScript(`return document.getElementById("some-id")`);```
