### ISSUE TITLE
Protractor fail to launch chrome-driver on local mac machine

### ISSUE THREAD

**Issue by surajsalunkhe** [angular/protractor#5501]
Bug report
---

- Node Version: `v15.12.0`
- Protractor Version: `7.0.0`
- Angular Version: `CLI-11.2.6`
- Browser(s): `89.0.4389.90`
- Operating System and Version `mac OS Catalina 10.15.7`
#### Your protractor configuration file
```
- exports.config = {
  //directConnect: true,
  seleniumAddress: 'http://localhost:4444/wd/hub',

  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'chrome'
  },

  // Framework to use. Jasmine is recommended.
  framework: 'jasmine',

  // Spec patterns are relative to the current working directory when
  // protractor is called.
  specs: ['example_spec.js'],

  // Options to be passed to Jasmine.
  jasmineNodeOpts: {
    defaultTimeoutInterval: 30000
  }
};
```
### A relevant example test
```
- describe('angularjs homepage', function() {
  it('should greet the named user', function() {
    browser.get('http://www.angularjs.org');

    element(by.model('yourName')).sendKeys('Julie');

    var greeting = element(by.binding('yourName'));

    expect(greeting.getText()).toEqual('Hello Julie!');
  });

  describe('todo list', function() {
    var todoList;

    beforeEach(function() {
      browser.get('http://www.angularjs.org');

      todoList = element.all(by.repeater('todo in todoList.todos'));
    });

    it('should list todos', function() {
      expect(todoList.count()).toEqual(2);
      expect(todoList.get(1).getText()).toEqual('build an AngularJS app');
    });

    it('should add a todo', function() {
      var addTodo = element(by.model('todoList.todoText'));
      var addButton = element(by.css('[value="add"]'));

      addTodo.sendKeys('write a protractor test');
      addButton.click();

      expect(todoList.count()).toEqual(3);
      expect(todoList.get(2).getText()).toEqual('write a protractor test');
    });
  });
});

```

- Output from running the test
[19:40:41] I/launcher - Running 1 instances of WebDriver
[19:40:41] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[19:41:01] E/launcher - Timed out waiting for driver server to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'Surajs-MacBook-Pro.local', ip: 'XXX', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_261'
Driver info: driver.version: unknown
[19:41:01] E/launcher - WebDriverError: Timed out waiting for driver server to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'Surajs-MacBook-Pro.local', ip: 'XXXX', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '1.8.0_261'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:761:15)
    at createDriver (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:626:16)
    at Hosted.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:195:43)
    at /usr/local/lib/node_modules/protractor/built/runner.js:339:29
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
[19:41:01] E/launcher - Process exited with error code 199
- Steps to reproduce the bug
- Naviagte to folder and protractor conf.js
- The URL you are running your tests against (if relevant)
(Note: It's working for firefox browser if set capabilities>'browserName': 'firefox')
Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by andredesousa** [comment]
Try running `webdriver-manager update` to update the version of your chromedriver.

Also, you can see my configuration:
https://github.com/andredesousa/essential-angular-scaffold/blob/main/e2e/protractor.conf.js

**Comment by duydnguyen07** [comment]
I have the same issue and I think this might be related to the webdriver-manager version that protractor uses. https://github.com/angular/webdriver-manager/commit/9fd6294517cdcd7fcf87994b84792db994d19003

Is it possible to update protractor's dependency?

**Comment by fbaldo31** [comment]
You can call the file directly like `node node_modules/protractor/bin/webdriver-manager update`
