### ISSUE TITLE
Compatibility Issue between ChromeDriver and Chrome Browser Versions in Protractor E2E Tests

### ISSUE THREAD

**Issue by SathishkumarG3** [angular/protractor#5568]
**Issue Summary:**
Encountered an error while attempting to run End-to-End (E2E) tests using Protractor. The error indicates an inability to start a WebDriver session due to a version mismatch between ChromeDriver and the Chrome browser.

**Environment Details:**
- Node Version: v16.14.0
- Protractor Version: 7.0.0
- Angular Version: v16.14.0
- Browser(s): Chrome Version 125.0.6422.113 (Official Build) (64-bit)
- Operating System: Windows 11

**Error Details:**
```
* Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


√ Compiled successfully.
[21:07:41] I/launcher - Running 1 instances of WebDriver
[21:07:41] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:49610/devtools/browser/952cf12d-795b-47ef-9cb4-878a7c1f795d
[21:07:43] E/runner - Unable to start a WebDriver session.
[21:07:43] E/launcher - Error: SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 125.0.6422.113 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
  (Driver info: chromedriver=114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}),platform=Windows NT 10.0.22621 x86_64)
    at Object.checkLegacyResponse (C:\Users\SathishkumarG\Documents\GitHub\LSCConsumerApp\node_modules\selenium-webdriver\lib\error.js:546:15)       
    at parseHttpResponse (C:\Users\SathishkumarG\Documents\GitHub\LSCConsumerApp\node_modules\selenium-webdriver\lib\http.js:509:13)
    at C:\Users\SathishkumarG\Documents\GitHub\LSCConsumerApp\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[21:07:43] E/launcher - Process exited with error code 100
```

**Resolution Steps Attempted:**
- Checked compatibility between ChromeDriver and Chrome browser versions.
- Verified the installed versions of Node.js, Protractor, and Angular.

**Request:**
Please advise on how to resolve this compatibility issue between ChromeDriver and Chrome browser versions. Should I update ChromeDriver to support Chrome version 125.0.6422.113, or are there alternative solutions available?

---

**Comment by SathishkumarG3** [comment]
Please prioritize this as we are still facing the same issue. If any channels are available, please provide updates
