### ISSUE TITLE
clear() or sendKeys('') not working on input types: date, time, datetime-local, month, or week

### ISSUE THREAD

**Issue by benlesh** [angular/protractor#562]
This directly relates to the documentation tests on a pull request on the Angular.js project: https://github.com/angular/angular.js/pull/5864

For now I'm going to work around it, I guess. But the issue seems to be that due to the custom controls in browsers like Chrome, protractor simply doesn't know what to do to interact with them in order to clear them. It's sort of late, and I haven't dug any further into than that for now.

I did, however see a few StackOverflow questions that seemed to relate, although none of the workarounds I found there worked.

http://stackoverflow.com/questions/15360362/clear-date-input-fails-on-chromewebdriver

Also possibly related?  

http://stackoverflow.com/questions/21295314/how-to-set-html5-type-date-input-fields-e-g-in-chrome-using-selenium-protra

**Comment by FilipZawada** [comment]
@mcalthrop
> Note: I've used lodash, cos I'm lazy – and I also added a test for the length of the existing text in the input, so that the number of backspaces sent is exact.

Then I'd suggest this:

```
function clear(elem) {
  elem.getAttribute('value').then(function (text) {
    var len = text.length
    var backspaceSeries = Array(len+1).join(protractor.Key.BACK_SPACE);
    elem.sendKeys(backspaceSeries);
  })
}
```

**Comment by srajagopalan1712** [comment]
Not good at js. Can someone tell me how the workaround will work for me? I am also using protractor to a non-angular page here, so guess I do not have to worry about the model validation here

I do not have an id for my dtepicker, hence I cannot do the workaround    browser.executeScript("document.getElementById('someElem').value = '2011-11-11';"); 
I can lookup the element using the css selector like
element(by.css('.mySubSection .dateInput > input')). 
Please help!!

**Comment by nehaw07** [comment]
I have protractor 2.2.0. The clear() function does not work on input of type number. I have tried most of the solutions given here. Please help me. Below is my code:
element(by.model('lineup.voltage_limit')).click().clear().sendKeys(value);

I have tried to even resolve the promise from clear() like below 
element(by.model('lineup.voltage_limit')).click().clear().then(function(){
		element(by.model('lineup.voltage_limit')).sendKeys(value); 
	});

clear() just does not seem to work! It just keeps on appending to the text in the input box.

**Comment by kayhadrin** [comment]
Why not injecting a "browser script command" to just set the field value to
zero?

**Comment by nehaw07** [comment]
@kayhadrin I was able to clear the existing numerical text from the input box using executeScript but then it does not clear the text it inserts a 0 if I say 
browser.executeScript("document.getElementById('lineup_voltage_limit').value = ' ';");
I want to clear the value which somehow I am unable to do.

**Comment by kayhadrin** [comment]
I'm testing this kind of numerical input field with a value as "" and it
shows effectively nothing in it.
So what's the HTML of your input field atm?
And what browser version are you using?

e.g. `<input id="test" value="" type="number">`

**Comment by juliemr** [comment]
@cnishina we need to confirm whether this is still a problem and file an appropriate webdriver bug if so.

**Comment by edzius** [comment]
I am facing similar issue on Chromium Version 49.0.2623.108, however Firefox (45.0.2) works fine.

protractor version 3.3.0
selenium standalone versions available: 2.52.0 [default]
chromedriver versions available: 2.21 [default]

Also checked with newes selenium (2.53.1) chromedriver (2.22) versions -- result is the same.

...

Input clear problem occurs when i start entering invalid values (like "e") to the number input. Furthermore when entered invalid value getAttibute('value') returns empty string and i have a feeling that those two issues are related.

Here is a yet another workaround:
```
input.sendKeys(protractor.Key.chord(protractor.Key.CONTROL, 'a'));
input.sendKeys(protractor.Key.DELETE);
```

**Comment by cnishina** [comment]
Sending keys appears to work:
```
    let tab = protractor.Key.TAB;
    element(by.css('.myform-date')).sendKeys('01/01/1970');
    element(by.css('.myform-time')).sendKeys('02:30PM');
    element(by.css('.myform-datetime')).sendKeys('01/01/1970 ' + tab + '02:30AM');
    element(by.css('.myform-month')).sendKeys('January' + tab + '2016');
    element(by.css('.myform-week')).sendKeys('51 2017');
```

Clearing the input field throws an error:

```
Started
F

Failures:
1) date form should do this
  Message:
    Failed: invalid element state: Element must be user-editable in order to clear it.
      (Session info: chrome=55.0.2883.95)
      (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.2 x86_64)
  Stack:
    InvalidElementStateError: invalid element state: Element must be user-editable in order to clear it.
      (Session info: chrome=55.0.2883.95)
      (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.2 x86_64)
        at WebDriverError (/Users/cnishina/src/protractor-cookbook/protractor-forms/node_modules/selenium-webdriver/lib/error.js:27:5)
        at InvalidElementStateError (/Users/cnishina/src/protractor-cookbook/protractor-forms/node_modules/selenium-webdriver/lib/error.js:138:5)
        at Object.checkLegacyResponse (/Users/cnishina/src/protractor-cookbook/protractor-forms/node_modules/selenium-webdriver/lib/error.js:639:15)
        at parseHttpResponse (/Users/cnishina/src/protractor-cookbook/protractor-forms/node_modules/selenium-webdriver/http/index.js:538:13)
        at client_.send.then.response (/Users/cnishina/src/protractor-cookbook/protractor-forms/node_modules/selenium-webdriver/http/index.js:472:11)
        at ManagedPromise.invokeCallback_ (/Users/cnishina/src/protractor-cookbook/protractor-forms/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/Users/cnishina/src/protractor-cookbook/protractor-forms/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/cnishina/src/protractor-cookbook/protractor-forms/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/cnishina/src/protractor-cookbook/protractor-forms/node_modules/selenium-webdriver/lib/promise.js:2820:25)
        at /Users/cnishina/src/protractor-cookbook/protractor-forms/node_modules/selenium-webdriver/lib/promise.js:639:7
    From: Task: WebElement.clear()
        at Driver.schedule (/Users/cnishina/src/protractor-cookbook/protractor-forms/node_modules/selenium-webdriver/lib/webdriver.js:377:17)
        at WebElement.schedule_ (/Users/cnishina/src/protractor-cookbook/protractor-forms/node_modules/selenium-webdriver/lib/webdriver.js:1744:25)
        at WebElement.clear (/Users/cnishina/src/protractor-cookbook/protractor-forms/node_modules/selenium-webdriver/lib/webdriver.js:2099:17)
```

My proposal is before we run the command `.clear`, we would check the attribute `type` of the input and if it is one of these, we send the right amount of back spaces and tabs to clear the field out. So for `type="date"` or `type="time"`, we would:

```
.sendKeys(protractor.Key.BACK_SPACE + protractor.Key.TAB + protractor.Key.BACK_SPACE + protractor.Key.TAB + protractor.Key.BACK_SPACE);
```

**Comment by cnishina** [comment]
On second thought, let's not do that PR...this bug has been filed.

https://bugs.chromium.org/p/chromedriver/issues/detail?id=1319&q=clear&colspec=ID%20Status%20Pri%20Owner%20Summary

**Comment by tonybranfort** [comment]
Added `clearByBs` function to [ngpo](https://www.npmjs.com/package/ngpo) if you're using that for Protractor page objects.  See [How to append custom fns](https://www.npmjs.com/package/ngpo#custom-fns) for example to clear a date field.  Thanks @FilipZawada for your [code](https://github.com/angular/protractor/issues/562#issuecomment-70309066).

**Comment by Arunadani** [comment]
Try this

```
await element(By.css('#someId')).sendKeys('', protractor.Key.HOME);
await element(By.css('#someId')).sendKeys('123123123');
```
