### ISSUE TITLE
Against IE10 browser, base url is not getting set

### ISSUE THREAD

**Issue by pareshmahajan** [angular/protractor#582]
Here is the snippet of my protractor.conf.js

seleniumArgs: ['-Dwebdriver.ie.driver=node_modules/protractor/selenium/IEDriverServer.exe'],

```
 capabilities: {
    'browserName': 'internet explorer',
    'version':'10',
  },

  baseUrl: 'http://10.37.1.97:60',

 // ----- Options to be passed to minijasminenode -----
  jasmineNodeOpts: {
    // onComplete will be called just before the driver quits.
    onComplete: null,
    // If true, display spec names.
    isVerbose: false,
    // If true, print colors to the terminal.
    showColors: true,
    // If true, include stack traces in failures.
    includeStackTrace: true,
    // Default time to wait in ms before a test fails.
    defaultTimeoutInterval: 10000
  }
```

My script works well for chrome browser. I mean, it opens the browser, sets the base url correctly and do as expected.

However, when I execute the same script against IE10 browser, it opens the IE10(maximized zoom level 100%), 
it launches the browser, webdriver sets the url like http://localhost:41276/ 

![image](https://f.cloud.github.com/assets/6871999/2344331/7ea6d04c-a51f-11e3-9407-fdce0d032bed.png)

and then sets the url to 'about:blank' like:
![image](https://f.cloud.github.com/assets/6871999/2344353/1c5205b4-a520-11e3-9c5a-78e6c25217a0.png)

 I expect my baseURL should be set instead.

Any further pointers here will be appreciated.

---

Here is the stracktrace that I am getting on the cmd:

   Stacktrace:
     UnknownError: JavaScript error (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 46 milliseconds
Build info: version: '2.39.0', revision: 'ff23eac', time: '2013-12-16 16:11:15'
System info: host: 'SL-PN-LT-0065', ip: '10.37.1.117', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.6.0_26'
Session ID: 61712d0b-1d6b-4756-b5be-5e79ddb4ea3a
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, enablePersistentHover=true, ignoreZoomSetting=false, ie.ensureCleanSession=false, browse
rName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=10, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtec
tedModeSettings=false, requireWindowFocus=false, handlesAlerts=true, initialBrowserUrl=http://localhost:22319/, ie.forceCreateProcessApi=false, nativeEvents=true, browser
AttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
    at new bot.Error (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:109:18)
    at Object.bot.response.checkResponse (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\response.js:106:9)
    at D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:275:20
    at D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1178:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1438:20)
    at notify (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:328:12)
    at notifyAll (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:297:7)
    at fulfill (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:402:7)
    at D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1305:10
    at D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1178:15
==== async task ====
WebDriver.executeScript()
    at webdriver.WebDriver.schedule (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:266:15)
    at webdriver.WebDriver.executeScript (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:415:15)
    at Protractor.get (D:\AmFamLCT\LctWebApp\node_modules\protractor\lib\protractor.js:508:15)
    at Fn.go (D:\AmFamLCT\LctWebApp\node_modules\astrolabe\lib\astrolabe\page.js:15:18)
    at null.<anonymous> (D:\AmFamLCT\LctWebApp\test\e2e\19 As a LC Pro I want to be able to see all service plans assigned to me for the current year.js:75:27)
    at D:\AmFamLCT\LctWebApp\node_modules\protractor\jasminewd\index.js:54:12
    at webdriver.promise.ControlFlow.runInNewFrame_ (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1438:20)
    at webdriver.promise.ControlFlow.runEventLoop_ (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1303:8)
    at wrapper [as _onTimeout](timers.js:252:14)
==== async task ====
    at null.<anonymous> (D:\AmFamLCT\LctWebApp\node_modules\protractor\jasminewd\index.js:53:12)
    at null.<anonymous> (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\minijasminenode\lib\async-callback.js:45:37)
    at jasmine.Block.execute (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:1168:17)
    at jasmine.Queue.next_ (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2200:31)
    at jasmine.Queue.start (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2153:8)
    at jasmine.Spec.execute (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2481:14)
    at jasmine.Queue.next_ (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2200:31)
    at onComplete (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2196:18)
    at jasmine.Spec.finish (D:\AmFamLCT\LctWebApp\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2455:5)

Finished in 3.782 seconds

**Comment by aieng09** [comment]
I have the same issue but I can't get to work.

**Comment by aieng09** [comment]
I get the following error message: I can't get it to work. I get the following error message 

1) Protractor Demo App should have a title

Message:

UnknownError: JavaScript error (WARNING: The server did not provide any sta

trace information)

mmand duration or timeout: 31 milliseconds

ild info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'

stem info: host: 'WIN-QHM5RV0OEL5', ip: '10.151.2.133', os.name: 'Windows Serv

2012', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_45'

iver info: org.openqa.selenium.ie.InternetExplorerDriver

pabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreat

rocessApi=false, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handles

erts=true, version=10, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSess

n=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindo

ocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:

929/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSetting

false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAle

Behaviour=dismiss}]

ssion ID: c7d8b815-5f03-4797-aa21-bb1b1ebc31d4

**Comment by aieng09** [comment]
And I am using protractor version 2.1.0 with the latest webdriver 2.45.0

**Comment by pmahajan-ee** [comment]
Hi,
I can see ignoreProtectedModeSetting = false
set it to true instead.
