### ISSUE TITLE
Suite argument has no effect.

### ISSUE THREAD

**Issue by tjworks** [angular/protractor#602]
Just installed latest version (0.20.1). My setup:

```
test/prot.conf.js
test/admin/client-spec.js
test/admin/dash-spec.js
```

Contents of prot.conf.js:

```
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',

  capabilities: {
    'browserName': 'chrome'
  },

  // Spec patterns are relative to the location of the spec file. They may
  // include glob patterns.
    specs: ['**/*spec.js'],

    // suites is not working
    suites: {
        dash: 'admin/dash-spec.js',
        client: ['admin/*client*.js'],
    },
  // Options to be passed to Jasmine-node.
  jasmineNodeOpts: {
    showColors: true, // Use colors in the command line report.
  },
}
```

When I tried to run `protractor ./test/prot.conf.js --suite=dash` it runs all the tests. If I remove the line `specs:['**/*spec.js']` then it throws this error:

```
Error: Spec patterns did not match any files.
  at Runner.run (/usr/local/lib/node_modules/protractor/lib/runner.js:329:11)
  at process.<anonymous>    (/usr/local/lib/node_modules/protractor/lib/runFromLauncher.js:32:14)
  at process.EventEmitter.emit (events.js:98:17)
  at handleMessage (child_process.js:318:10)
  at Pipe.channel.onread (child_process.js:345:11)
[launcher] Runner Process Exited With Error Code: 8
```

Expected: should run only the specified tests only.

**Comment by thephilwells** [comment]
Did this ever make the cut? I'm still seeing the same issue described exactly as above.
