### ISSUE TITLE
Can someone paste the conf.js file with internet explorer as browsername

### ISSUE THREAD

**Issue by ghost** [angular/protractor#669]
Hi All,

About to run my protractor scripts on IE, downloaded the IE driver, but not able to set the required config in conf.js, 

thanks in advance,
Mahesh

**Comment by rahul2983** [comment]
@elgalu - great post on configuring protractor against IE11. I do have a question on step 7. Where do you find the host file on your machine? Can I get a better path to /etc/hosts ?

**Comment by elgalu** [comment]
Linux or OSX: /etc/hosts
Windows: %SystemRoot%\system32\drivers\etc\hosts

**Comment by Venks88** [comment]
Hi @elgalu  I tried the technique you had provided for running a protractor test from a MAC to a Windows VM, specifically to run it on IE 11.


I ended up getting the following:

Jiangs-iMac:ui_automation_test Venkata$ protractor conf.js
Using the selenium server at http://ie11.dev:4444/wd/hub
[launcher] Running 1 instances of WebDriver

/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145
      callback(new Error(message));
               ^
Error: ETIMEDOUT connect ETIMEDOUT
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145:16)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:155:22)
    at Function.webdriver.WebDriver.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:129:30)
    at [object Object].Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:416:22)
    at [object Object].DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/usr/local/lib/node_modules/protractor/lib/runner.js:180:37)
    at /usr/local/lib/node_modules/protractor/lib/runner.js:268:21
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:759:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:573:44
[launcher] Process exited with error code 1


It basically halts for about 10 seconds and then gives me the above error, message.
Any help would be awesome.

**Comment by miriamstub** [comment]
Venks88 I get a similar error, do you remember how to manage it?
thanks in advance

**Comment by rajaexp** [comment]
exports.config = {
defaultTimeoutInterval: 100000
}

**Comment by Vasundhara-vasu** [comment]
Hello ,
 I am using Protractor and trying to  run in IE Browsers 
 
code 
exports.config = {
    capabilities: {
        'browserName': 'internet explorer',
        'platform': 'ANY',
        'version': '11'
    },
}; 
and I am not left with any errors but  IE  browser is not now running  , can any 1 help

**Comment by nayanr9** [comment]
@here anyone is having the options/capabilities for IE, Please paste here.
I tried `'ignoreZoomSetting': true,` which is not working.

**Comment by ManishkumarGupta-Mediware** [comment]
You can try with  'ignoreProtectedModeSettings': true,
