### ISSUE TITLE
Switch off Stacktrace output

### ISSUE THREAD

**Issue by nitrovolnovka** [angular/protractor#696]
Is there way to switch off the Stacktrace output into console on failures?
e.g. 
Current behavior:

``` Shell
Failures:

  1) Components.js Validate Tag Component tutorial on frontend page Element tag
component number 1 has item Text234234
   Message:
     Expected 0 to be greater than 0.
   Stacktrace:
     Error: Expected 0 to be greater than 0.
    at new jasmine.ExpectationResult (c:\Users\dyaroshenko\AppData\Roaming\npm\n
ode_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:137:32)

    at null.toBeGreaterThan (c:\Users\dyaroshenko\AppData\Roaming\npm\node_modul
es\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:1339:29)
    at d:\work\wmg\js-framework-examples\bower_components\factory-testing-framew
ork\modules\helper.js:63:32
    at c:\Users\dyaroshenko\AppData\Roaming\npm\node_modules\protractor\node_mod
ules\selenium-webdriver\lib\goog\base.js:1178:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (c:\Users\dyaroshenko\AppDat
a\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdri
ver\promise.js:1598:20)
    at notify (c:\Users\dyaroshenko\AppData\Roaming\npm\node_modules\protractor\
node_modules\selenium-webdriver\lib\webdriver\promise.js:428:12)
    at notifyAll (c:\Users\dyaroshenko\AppData\Roaming\npm\node_modules\protract
or\node_modules\selenium-webdriver\lib\webdriver\promise.js:397:7)
    at resolve (c:\Users\dyaroshenko\AppData\Roaming\npm\node_modules\protractor
\node_modules\selenium-webdriver\lib\webdriver\promise.js:375:7)
    at fulfill (c:\Users\dyaroshenko\AppData\Roaming\npm\node_modules\protractor
\node_modules\selenium-webdriver\lib\webdriver\promise.js:493:5)
    at Object.webdriver.promise.asap (c:\Users\dyaroshenko\AppData\Roaming\npm\n
ode_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:
732:5)

  2) Components.js Validate Tag Component tutorial on frontend page Element tag
component number 2 has item Lisa Simpson
   Message:
     Expected 0 to be greater than 0.
   Stacktrace:
     Error: Expected 0 to be greater than 0.
    at new jasmine.ExpectationResult (c:\Users\dyaroshenko\AppData\Roaming\npm\n
ode_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:137:32)

    at null.toBeGreaterThan (c:\Users\dyaroshenko\AppData\Roaming\npm\node_modul
es\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:1339:29)
    at d:\work\wmg\js-framework-examples\bower_components\factory-testing-framew
ork\modules\helper.js:63:32
    at c:\Users\dyaroshenko\AppData\Roaming\npm\node_modules\protractor\node_mod
ules\selenium-webdriver\lib\goog\base.js:1178:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (c:\Users\dyaroshenko\AppDat
a\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdri
ver\promise.js:1598:20)
    at notify (c:\Users\dyaroshenko\AppData\Roaming\npm\node_modules\protractor\
node_modules\selenium-webdriver\lib\webdriver\promise.js:428:12)
    at notifyAll (c:\Users\dyaroshenko\AppData\Roaming\npm\node_modules\protract
or\node_modules\selenium-webdriver\lib\webdriver\promise.js:397:7)
    at resolve (c:\Users\dyaroshenko\AppData\Roaming\npm\node_modules\protractor
\node_modules\selenium-webdriver\lib\webdriver\promise.js:375:7)
    at fulfill (c:\Users\dyaroshenko\AppData\Roaming\npm\node_modules\protractor
\node_modules\selenium-webdriver\lib\webdriver\promise.js:493:5)
    at Object.webdriver.promise.asap (c:\Users\dyaroshenko\AppData\Roaming\npm\n
ode_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:
732:5)

Finished in 23.552 seconds
7 tests, 3 assertions, 2 failures
```

Expected behavior:

``` Shell
Failures:

  1) Components.js Validate Tag Component tutorial on frontend page Element tag
component number 1 has item Text234234
   Message:
     Expected 0 to be greater than 0.

  2) Components.js Validate Tag Component tutorial on frontend page Element tag
component number 2 has item Lisa Simpson
   Message:
     Expected 0 to be greater than 0.

Finished in 23.552 seconds
7 tests, 3 assertions, 2 failures
```

Investigated a bit.

Found that `--stackTrace false` CLI argument seems not to work

protractor-conf.js options don't work too:

``` js
exports.config = {
    ...
    jasmineNodeOpts: {
        ...
        includeStackTrace: false,
        ...
    }
    ...
};
```

Thanks in advance

**Comment by Shirish2015** [comment]
@juliemr.I am facing the following  issue when I'm running my test
script at the time of validation.
Message:
     Expected false to be true.
   Stacktrace:
     Error: Expected false to be true.
    at WebdriverIO.<anonymous> (/Users/skumar/projects/reports/test/functional/jasmine-specs/testSuiteSpec.js:33:59)
    at WebdriverIO.<anonymous> (/Users/skumar/projects/func-kit/node_modules/webdriverio/lib/utils/PromiseHandler.js:152:26)
    at /Users/skumar/projects/func-kit/node_modules/webdriverio/node_modules/chainit/index.js:137:22
    at /Users/skumar/projects/func-kit/node_modules/webdriverio/lib/commands/getAttribute.js:93:9
    at /Users/skumar/projects/func-kit/node_modules/webdriverio/node_modules/async/lib/async.js:154:25
    at WebdriverIO.<anonymous> (/Users/skumar/projects/func-kit/node_modules/webdriverio/lib/commands/getAttribute.js:64:21)
    at WebdriverIO.<anonymous> (/Users/skumar/projects/func-kit/node_modules/webdriverio/lib/utils/PromiseHandler.js:152:26)
    at /Users/skumar/projects/func-kit/node_modules/webdriverio/node_modules/chainit/index.js:137:22
