### ISSUE TITLE
Protractor cant acquire session (Ubuntu)

### ISSUE THREAD

**Issue by ldeavila** [angular/protractor#723]
Trying to get protractor to run on Ubuntu. I found this issue that seems similar. (https://github.com/angular/protractor/issues/387) . I tried the suggested fixes and they did not resolve the issue. Any guidance would be appreciated. Thanks!

1) ran both 
`npm install -g protractor` and `npm install protractor`
2) ran both `webdriver-manager update` and `./node_modules/protractor/bin/webdriver-manager update`
3) ran `protractor protractor.conf.js` and `protractor --browser googlechrome --seleniumServerJar node_modules/protractor/selenium/selenium-server-standalone-2.40.0.jar --specs tests/e2e/campaigns-pages/campaigns-pages_test.js`

Also, chrome is installed in `/usr/bin/google-chrome`.

In all instances I get the error down below:

``` js
/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1702
      throw error;
            ^
UnknownError: null
    at new bot.Error (/usr/lib/node_modules/protractor/node_modules/    )
    at Object.bot.response.checkResponse (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:134:24
    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1178:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1598:20)
    at notify (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:428:12)
    at notifyAll (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:397:7)
    at resolve (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:375:7)
    at fulfill (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:493:5)
    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1178:15
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:49)
    at Function.webdriver.WebDriver.createSession (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:111:30)
    at Builder.build (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:106:20)
    at LocalDriverProvider.getDriver (/usr/lib/node_modules/protractor/lib/driverProviders/local.dp.js:121:9)
    at /usr/lib/node_modules/protractor/lib/runner.js:379:35
    at _fulfilled (/usr/lib/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/protractor/node_modules/q/q.js:759:13)
    at /usr/lib/node_modules/protractor/node_modules/q/q.js:573:44
```

This is my protractor config

``` js
exports.config = {

    multiCapabilities: [
        {'browserName': 'chrome'}
        //, {'browserName': 'firefox'}
    ],

    jasmineNodeOpts: {
        showColors: false,
        defaultTimeoutInterval: 30000
    },

    specs: [
        './tests/e2e/**/*.js'
    ],
    baseUrl: 'http://foo.bar.com'
}
```

**Comment by toupeira** [comment]
For others running into similar problems: try running `chromedriver` directly from `./node_modules/grunt-protractor-runner/node_modules/protractor/selenium/chromedriver` (where `webdriver-manager` puts it) and see what error you get. In my case I got a message about a missing libgconf-something, so after installing the relevant package it started to work.
