### ISSUE TITLE
IE stability issue - occasional Javascript errors

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#841]
Example: 

```
     UnknownError: JavaScript error (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 129 milliseconds
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32'
System info: host: 'WIN-8LIIH1BGM1D', ip: '172.20.42.188', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.6.0_38'
Session ID: ce12158e-4456-4529-8cc9-b8171739c296
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, elementScrollBehavior=0, javascriptEnabled=true, enablePersistentHover=true, ignoreZoomSetting=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=11, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, allowAsynchronousJavaScript=false, initialBrowserUrl=, handlesAlerts=true, nativeEvents=true, takesScreenshot=true}]
   Stacktrace:
     UnknownError: JavaScript error (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 129 milliseconds
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32'
System info: host: 'WIN-8LIIH1BGM1D', ip: '172.20.42.188', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.6.0_38'
Session ID: ce12158e-4456-4529-8cc9-b8171739c296
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, elementScrollBehavior=0, javascriptEnabled=true, enablePersistentHover=true, ignoreZoomSetting=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=11, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, allowAsynchronousJavaScript=false, initialBrowserUrl=, handlesAlerts=true, nativeEvents=true, takesScreenshot=true}]
==== async task ====
WebDriver.executeScript()
==== async task ====
Timed out waiting for page to load
    at null.<anonymous> (/Users/ralphj/protractor/spec/basic/findelements_spec.js:580:13)
==== async task ====
Asynchronous test function: it()
Error
    at verifyMethodsAdded (/Users/ralphj/protractor/spec/basic/findelements_spec.js:575:3)
    at Object.<anonymous> (/Users/ralphj/protractor/spec/basic/findelements_spec.js:462:1)
```

These happen during the wait for the page to load about 1% of the time.

**Comment by kaililleby** [comment]
I'm getting err.code 17 on windows 10 / explorer 11 - seemingly the same cause? The messages logged are the same as described in this issue.. should `if (err.code == 13)` be changed to `if (err.code == 13 || err.code == 17)`  ?

**Comment by yimothy** [comment]
This error occurs almost 100% of the time in IE11 when there are adjacent `browser.get()` calls. See https://github.com/angular/protractor/issues/4268. 

It seems like the Javascript error does not get ignored in this case. A quick solution for this is to just use `browser.driver.get()` instead of the `browser.get()`.
