### ISSUE TITLE
"Detected a page unload event" error in phantom.js

### ISSUE THREAD

**Issue by alexgorbatchev** [angular/protractor#85]
Trying to run "onMocha.js" example with phantomjs or chromedriver doesn't seem to work. 

Here's the code, I only changed `webdriver.Capabilities.chrome()` to `webdriver.Capabilities.phantomjs()` and `expect.js` to `chai`

```
/**
 * This example shows how to use the protractor library in a Mocha test.
 * It assumes that a selenium server is running at localhost:4444.
 * Run this test with:
 *   mocha onMocha.js
 */

var util = require('util');
var expect = require('chai').expect;
var webdriver = require('selenium-webdriver');
var protractor = require('../lib/protractor.js');

describe('angularjs.org homepage', function() {
  this.timeout(80000);

  var driver, ptor;

  before(function() {
    driver = new webdriver.Builder().
        withCapabilities(webdriver.Capabilities.phantomjs()).build();

    driver.manage().timeouts().setScriptTimeout(10000);
    ptor = protractor.wrapDriver(driver);
  });

  after(function(done) {
    driver.quit().then(function() {done()});
  })

  it('should greet using binding', function(done) {
    ptor.get('http://www.angularjs.org');

    ptor.findElement(protractor.By.input('yourName')).sendKeys('Julie');

    ptor.findElement(protractor.By.binding('{{yourName}}')).
        getText().then(function(text) {
          expect(text).to.eql('Hello Julie!');
          done();
        });
  });

  ... snip
});
```

Here's the error

```
Uncaught UnknownError: Error Message => 'Detected a page unload event; asynchronous script execution does not work across page loads.'
 caused by Request => {"headers":{"Accept":"application/json; charset=utf-8","Connection":"keep-alive","Content-Length":"425","Content-Type":"application/json;charset=UTF-8","Host":"192.168.128.240:56087"},"httpVersion":"1.1","method":"POST","post":"{\"script\":\"return (function () {\\n  var attempts = arguments[0];\\n  var callback = arguments[arguments.length - 1];\\n  var check = function(n) {\\n    if (window.angular && window.angular.resumeBootstrap) {\\n      callback(true);\\n    } else if (n < 1) {\\n      callback(false);\\n    } else {\\n      window.setTimeout(function() {check(n - 1)}, 1000);\\n    }\\n  };\\n  check(attempts);\\n}).apply(null, arguments);\",\"args\":[10]}","url":"/execute_async","urlParsed":{"anchor":"","query":"","file":"execute_async","directory":"/","path":"/execute_async","relative":"/execute_async","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/execute_async","queryKey":{},"chunks":["execute_async"]},"urlOriginal":"/session/e2dbebc0-1b3f-11e3-84c0-67b730e3988e/execute_async"}
      at new bot.Error (./node_modules/selenium-webdriver/lib/atoms/error.js:109:18)
      at Object.bot.response.checkResponse (./node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
      at ./node_modules/selenium-webdriver/lib/webdriver/webdriver.js:275:20
      at ./node_modules/selenium-webdriver/lib/goog/base.js:1178:15
      at webdriver.promise.ControlFlow.runInNewFrame_ (./node_modules/selenium-webdriver/lib/webdriver/promise.js:1438:20)
      at notify (./node_modules/selenium-webdriver/lib/webdriver/promise.js:328:12)
      at notifyAll (./node_modules/selenium-webdriver/lib/webdriver/promise.js:297:7)
      at fulfill (./node_modules/selenium-webdriver/lib/webdriver/promise.js:402:7)
      at ./node_modules/selenium-webdriver/lib/webdriver/promise.js:1305:10
      at ./node_modules/selenium-webdriver/lib/goog/base.js:1178:15
      at webdriver.promise.ControlFlow.runInNewFrame_ (./node_modules/selenium-webdriver/lib/webdriver/promise.js:1438:20)
      at notify (./node_modules/selenium-webdriver/lib/webdriver/promise.js:328:12)
      at notifyAll (./node_modules/selenium-webdriver/lib/webdriver/promise.js:297:7)
      at fulfill (./node_modules/selenium-webdriver/lib/webdriver/promise.js:402:7)
      at ./node_modules/selenium-webdriver/lib/goog/base.js:1178:15
      at webdriver.promise.ControlFlow.runInNewFrame_ (./node_modules/selenium-webdriver/lib/webdriver/promise.js:1438:20)
      at notify (./node_modules/selenium-webdriver/lib/webdriver/promise.js:328:12)
      at notifyAll (./node_modules/selenium-webdriver/lib/webdriver/promise.js:297:7)
      at fulfill (./node_modules/selenium-webdriver/lib/webdriver/promise.js:402:7)
      at ./node_modules/selenium-webdriver/lib/webdriver/promise.js:607:51
      at ./node_modules/selenium-webdriver/lib/webdriver/http/http.js:96:5
      at IncomingMessage.<anonymous> (./node_modules/selenium-webdriver/http/index.js:113:7)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:895:16
      at process._tickCallback (node.js:415:13)
  ==== async task ====
  WebDriver.executeScript()
      at webdriver.WebDriver.schedule (./node_modules/selenium-webdriver/lib/webdriver/webdriver.js:266:15)
      at webdriver.WebDriver.executeAsyncScript (./node_modules/selenium-webdriver/lib/webdriver/webdriver.js:506:15)
      at Protractor.get (./node_modules/protractor/lib/protractor.js:556:15)
      at Context.<anonymous> (./node_modules/protractor/example/onMocha.js:32:10)
      at Test.Runnable.run (./node_modules/protractor/node_modules/mocha/lib/runnable.js:194:15)
      at Runner.runTest (./node_modules/protractor/node_modules/mocha/lib/runner.js:355:10)
      at ./node_modules/protractor/node_modules/mocha/lib/runner.js:401:12
      at next (./node_modules/protractor/node_modules/mocha/lib/runner.js:281:14)
      at ./node_modules/protractor/node_modules/mocha/lib/runner.js:290:7
      at next (./node_modules/protractor/node_modules/mocha/lib/runner.js:234:23)
      at Object._onImmediate (./node_modules/protractor/node_modules/mocha/lib/runner.js:258:5)
      at processImmediate [as _immediateCallback] (timers.js:317:15)
```

phantom

```
> phantomjs --version                                                                                                                                                                                            
1.9.1
```

**Comment by lpicquet** [comment]
This issue needs to be re-open. The problem still exists

Uncaught exception: Error while running testForAngular: {"errorMessage":"Detected a page unload event; asynchronous script execution does not work across page loads.","request":{"headers":{"Accept-Enc
oding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"856","Content-Type":"application/json; charset=utf-8","Host":"localhost:26497","User-Agent":"Apache-HttpClient/4.3.2 (java 1.5)"},"htt
pVersion":"1.1","method":"POST","post":"{\"args\":[5],\"script\":\"try { return (function (attempts, asyncCallback) {\\r\\n  var callback = function(args) {\\r\\n    setTimeout(function() {\\r\\n
 asyncCallback(args);\\r\\n    }, 0);\\r\\n  };\\r\\n  var check = function(n) {\\r\\n    try {\\r\\n      if (window.angular && window.angular.resumeBootstrap) {\\r\\n        callback([true, null]);\
\r\\n      } else if (n < 1) {\\r\\n        if (window.angular) {\\r\\n          callback([false, 'angular never provided resumeBootstrap']);\\r\\n        } else {\\r\\n          callback([false, 'ret
ries looking for angular exceeded']);\\r\\n        }\\r\\n      } else {\\r\\n        window.setTimeout(function() {check(n - 1);}, 1000);\\r\\n      }\\r\\n    } catch (e) {\\r\\n      callback([fals
e, e]);\\r\\n    }\\r\\n  };\\r\\n  check(attempts);\\r\\n}).apply(this, arguments); }\\ncatch(e) { throw (e instanceof Error) ? e : new Error(e); }\"}","url":"/execute_async","urlParsed":{"anchor":""
,"query":"","file":"execute_async","directory":"/","path":"/execute_async","relative":"/execute_async","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"
/execute_async","queryKey":{},"chunks":["execute_async"]},"urlOriginal":"/session/680a9110-ddf0-11e4-922a-a7c8111b32ce/execute_async"}}
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:03'
System info: os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_25'
Driver info: driver.version: unknown
[launcher] Process exited with error code 1

**Comment by RodolpheGohard** [comment]
I confirm the issue still exists

```
$ protractor --version
Version 2.0.0

$ ./phantomjs --version
2.0.1-development
```

Here is the error:
```
Using the selenium server at http://localhost:4444
[launcher] Running 1 instances of WebDriver
F

Failures:

  1) RMC2 login page should have input fields
   Message:
     Error while running testForAngular: {"errorMessage":"Detected a page unload event; asynchronous script execution does not work across page loads.","request":{"headers":{"Accept":"application/json; charset=utf-8","Connection":"keep-alive","Content-Length":"809","Content-Type":"application/json;charset=UTF-8","Host":"localhost:4444"},"httpVersion":"1.1","method":"POST","post":"{\"script\":\"try { return (function (attempts, asyncCallback) {\\n  var callback = function(args) {\\n    setTimeout(function() {\\n      asyncCallback(args);\\n    }, 0);\\n  };\\n  var check = function(n) {\\n    try {\\n      if (window.angular && window.angular.resumeBootstrap) {\\n        callback([true, null]);\\n      } else if (n < 1) {\\n        if (window.angular) {\\n          callback([false, 'angular never provided resumeBootstrap']);\\n        } else {\\n          callback([false, 'retries looking for angular exceeded']);\\n        }\\n      } else {\\n        window.setTimeout(function() {check(n - 1);}, 1000);\\n      }\\n    } catch (e) {\\n      callback([false, e]);\\n    }\\n  };\\n  check(attempts);\\n}).apply(this, arguments); }\\ncatch(e) { throw (e instanceof Error) ? e : new Error(e); }\",\"args\":[10]}","url":"/execute_async","urlParsed":{"anchor":"","query":"","file":"execute_async","directory":"/","path":"/execute_async","relative":"/execute_async","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/execute_async","queryKey":{},"chunks":["execute_async"]},"urlOriginal":"/session/225b28f0-e9cb-11e4-ad75-8faceda3cfa1/execute_async"}}
   Stacktrace:
     undefined

Finished in 0.175 seconds
1 test, 1 assertion, 1 failure

[launcher] 0 instance(s) of WebDriver still running
[launcher] phantomjs #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```

**Comment by moattarwork** [comment]
Still is not working correctly when you have windows authentication or NTLM in place. 

The http://username:password@dns is working using PhantomJs but from Protractor it raise the same error.

**Comment by carlos-granados** [comment]
I submitted a Pull request to solve this in the latest versions of Angular
