### ISSUE TITLE
Cucumber-JS stops on failure

### ISSUE THREAD

**Issue by stejanse** [angular/protractor#876]
Since 0.23.0, Cucumber-JS stops after a failing step in Protractor. Before 0.23.0 it continues executing other scenario's and reporting the final results. This appears to be a bug in Protractor.

**0.23.0:**

``` cucumber
Feature: some feature

  Scenario: some scenario
   When some step
   Then some FAILURE
```

**before:**

``` cucumber
Feature: some feature

  Scenario: some scenario
   When some step
   Then some FAILURE

  Scenario: other scenario
    When ...

xx scenarios (1 failed)
xx steps (1 failed, xx passed)
```

**Comment by jlin412** [comment]
@jbpros I try cuke-tractor with the latest protractor 2.0.0 and cucumber.js 0.4.8.
It seems that it is failing again for the following test case:
```
 this.Then(/^I click on a bad locator$/, function (next) {
    $('bad_css_path').click().then(next);
  });
```

**Comment by jbpros** [comment]
@jlin412 :cry: did you try to find the cause of that new breakage?

**Comment by jlin412** [comment]
I haven't pinpointed which commit.  I just know that the last working build
is 1.8.0.  I will test it today or tomorrow.

**Comment by jlin412** [comment]
@jbpros I update https://github.com/jlin412/cuke-tractor
With latest 2.1.0, failure case is different.
Original failure in 2.0.0 is passing now.
``` javascript
 this.Then(/^I click on a bad locator$/, function (next) {
    $('bad_css_path').click().then(next);
  });
```
but the following two cases inside *then* block are failing:
```
  this.When(/^something fails via exception in then function$/, function (callback) {
    $('css_bad_path').isPresent().then(function(isElmentPresent) {
      throw new Error('#FAIL via exception');
      callback();
    });
  });

  this.When(/^failed inside then call$/, function (callback) {
    $('css_bad_path').isPresent().then(function(isElmentPresent) {
      expect(isElmentPresent).to.equal(true);
      callback();
    });
  });
```
I have uploaded my test cases in my fork of cuke-tractor.
https://github.com/jlin412/cuke-tractor

**Comment by aluzardo** [comment]
I am getting the same error if I use a promise inside my step definition.

This is the promise

this.waitUrl = function (urlRegex, time) {
        return browser.wait(function() {
            return browser.getCurrentUrl().then(function(url) {
                return urlRegex.test(url);
            });
        }, time, "url has not changed to "+urlRegex);
    };


If the promise and the test passed there is no problem and everything works pretty good. The problem is when the promise timeout, the testing process stop and others test won't run.

Any idea to keep the process running? This test will fail but the other could pass.

For example: 
```
[10:54:33] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[10:54:33] I/launcher - Running 1 instances of WebDriver
Feature: xxx login
    As a user of xxx login
    I should be able to login in xxx using an existent user
  @critical
  Scenario: Check xxx login
    Given The xxx login page is open
    Then The title should contain "xxx"
[10:54:57] E/launcher - url has not changed to /lobby/
Wait timed out after 10020ms
[10:54:57] E/launcher - Error: url has not changed to /lobby/
Wait timed out after 10020ms
    at /Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/node_modules/selenium-webdriver/lib/promise.js:2364:22
    at ManagedPromise.invokeCallback_ (/Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at /Users/adolfocabrera/Mavrix/xxx/Selenium/xxx/node_modules/selenium-webdriver/lib/promise.js:2775:27
    at /Users/adolfocabrera/Mavrixxxx/Selenium/xxx/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: url has not changed to /lobby/
    at ControlFlow.wait (/Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/node_modules/selenium-webdriver/lib/promise.js:2352:17)
    at WebDriver.wait (/Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/node_modules/selenium-webdriver/lib/webdriver.js:712:29)
    at ProtractorBrowser.to.(anonymous function) [as wait] (/Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/node_modules/protractor/built/browser.js:68:29)
    at waitForUrlToChangeTo (/Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/features/utils/wait.utils.js:19:32)
    at ManagedPromise.invokeCallback_ (/Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at /Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/node_modules/selenium-webdriver/lib/promise.js:2775:27
    at /Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
[10:54:57] E/launcher - Process exited with error code 199

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/adolfocabrera/.nvm/versions/node/v5.11.1/bin/node" "/Users/adolfocabrera/.nvm/versions/node/v5.11.1/bin/npm" "run" "test-desktop-local"
npm ERR! node v5.11.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! protractor-cucumber-tests@1.0.0 test-desktop-local: `protractor conf.js --seleniumAddress 'http://localhost:4444/wd/hub'`
npm ERR! Exit status 199
npm ERR! 
npm ERR! Failed at the protractor-cucumber-tests@1.0.0 test-desktop-local script 'protractor conf.js --seleniumAddress 'http://localhost:4444/wd/hub''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the protractor-cucumber-tests package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor conf.js --seleniumAddress 'http://localhost:4444/wd/hub'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protractor-cucumber-tests
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls protractor-cucumber-tests
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adolfocabrera/xxx/QA-testing/Selenium/xxx/npm-debug.log

```
