### ISSUE TITLE
[Appium] Failed with Responding to client that a method is not implemented

### ISSUE THREAD

**Issue by raycheung** [angular/protractor#882]
Setting up Protractor with Appium `1.1.0` with the following config to test an hybrid app:

      capabilities: {
        browserName: '',
        platformName: 'Android',
        platformVersion: '4.4',
        deviceName: 'Android Emulator',
        app: '/Users/ray/my-app/platforms/android/ant-build/MyApp-debug.apk',
        appPackage: 'com.ionicframework.starter',
        appActivity: 'MyApp'
      },

And Appium immediately failed with:

    GET /wd/hub/session/6a295263-1c7f-4940-b998-c1d08c9cd6d7 200 1ms - 915b
    debug: Appium request initiated at /wd/hub/session/6a295263-1c7f-4940-b998-c1d08c9cd6d7/timeouts/async_script
    debug: Request received with params: {"ms":11000}
    info: Responding to client that a method is not implemented
    POST /wd/hub/session/6a295263-1c7f-4940-b998-c1d08c9cd6d7/timeouts/async_script 501 2ms - 180b

Which was caused by `lib/runner.js`:

    driver.manage().timeouts().setScriptTimeout(self.config_.allScriptsTimeout);

**Comment by juliemr** [comment]
I believe this is addressed with https://github.com/sebv/wd-bridge/blob/master/README.md as documented on http://angular.github.io/protractor/#/browser-setup

**Comment by Harbhawan** [comment]
I am getting the issue "Responding to client that a method is not implemented"

Appium version: 1.3.5
Node version: v0.10.36
Protractor version: Version 1.6.1

Appium server log:
---------------
/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: Not yet implemented. Please help us: http://appium.io/get-involved.html
    at new bot.Error (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:362:20
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at [object Object].fulfill (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1520:10
----------------
