### ISSUE TITLE
Protractor test is not starting on Firefox

### ISSUE THREAD

**Issue by acostaf** [angular/protractor#886]
I have got a set of test that run fine on chrome but when I change the capabilities browserName  from chrome to firefox don't even get a  error info

Before
 capabilities: {
        'browserName': 'chrome',
        'chromeOptions': { args: ['--test-type', 'show-fps-counter=true'] }
    },

//After
capabilities: {
    'browserName': 'firefox'
},

**Comment by nareshsurya** [comment]
When I run my protractor scripts on Firefox, firefox window is opened but failed to open the target URL and getting the following error:
sing FirefoxDriver directly...
[launcher] Running 1 instances of WebDriver

c:\node_modules\protractor\node_modules\selenium-webdriver\http\util.js:89
          Error('Timed out waiting for the WebDriver server at ' + url));
          ^
Error: Timed out waiting for the WebDriver server at http://127.0.0.1:49587/hub
    at Error (native)
    at onResponse (c:\node_modules\protractor\node_modules\selenium-webdriver\http\util.js:89:11)
    at c:\node_modules\protractor\node_modules\selenium-webdriver\http\util.js:44:21
    at c:\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\http\http.js:140:5
    at ClientRequest.<anonymous> (c:\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:174:7)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:258:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (c:\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (c:\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:131:30)
    at new Driver (c:\node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js:278:36)
    at [object Object].DirectDriverProvider.getNewDriver (c:\node_modules\protractor\lib\driverProviders\direct.js:74:16)
    at [object Object].Runner.createBrowser (c:\node_modules\protractor\lib\runner.js:190:37)
    at c:\node_modules\protractor\lib\runner.js:280:21
    at _fulfilled (c:\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (c:\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (c:\node_modules\protractor\node_modules\q\q.js:796:13)
    at c:\node_modules\protractor\node_modules\q\q.js:556:49
[launcher] Process exited with error code 1

Process finished with exit code 1


Can someone please help me out with this?

Regards,
Naresh Surya

**Comment by b-mcrae** [comment]
Hi @nareshsurya!

I recently encountered the same error as you. The quick fix solution for me was to uninstall Firefox 47 and downgrade to Firefox 36. You can find older versions of Firefox here: `https://ftp.mozilla.org/pub/firefox/releases/`

I'm using selenium-webdriver 2.47.0. I'm not sure what's the latest version of Firefox we can use, but just wanted to give you a quick fix at the moment! Perhaps someone can expand upon this!

**Comment by freakaziod210** [comment]
@b-mcrae I love you!! I have been stumped on this for a few hours. My tests were working fine yesterday but when I ran them today they weren't. I guess Firefox updated somewhere in between.

**Comment by ahmed-abdulmoniem** [comment]
Any solution to the last error? I am experiencing the same!

**Comment by m-ajitabh** [comment]
**Protractor is running on Firefox**

I am using FireFox v44.01, with following settings
capabilities: {
    'browserName': 'chrome',
	chromeOptions: {
            args: ['disable-extensions']
        }
		 ,
	"browserName": "firefox",
	"firefox_binary": "C:/Program Files/Mozilla Firefox/firefox",
	"binary_": "C:/Program Files/Mozilla Firefox/firefox" 
  },

and its running fine with Firefox.
**before starting with Firefox, disable the auto update of Firefox.**

**Comment by kathy-ems** [comment]
What would be the equivalent of this on a mac?

```
"browserName": "firefox",
"firefox_binary": "C:/Program Files/Mozilla Firefox/firefox",
"binary_": "C:/Program Files/Mozilla Firefox/firefox" 
```

I tried, but it didn't work

```
    firefox_binary: '../../../../../Applications/firefox_v34',
    binary_: '../../../../../Applications/firefox_v34',
```

**Comment by m-ajitabh** [comment]
Locate where an executable of firefox is coming from the filesystem and write the fullpath.
The way you wrote the path, it seems fuzzy. So search on internet for the binary location of firefox on mac
and fix your problem.

**Comment by 7stud** [comment]
Mac OSX 10.10.5
Firefox 50.1

I'm having the same problem with Firefox not running any tests and timing out.  I'm following the [protractor tutorial](http://www.protractortest.org/#/tutorial), and [Step 3](http://www.protractortest.org/#/tutorial#step-3-changing-the-configuration) asks me to add Firefox to conf.js:
```
// conf.js
exports.config = {
  framework: 'jasmine',
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['spec.js'],
  capabilities: {
    browserName: 'firefox'
  }
}
```
Here is the output when I do `$ webdriver-manager start`:

```
~/protractor_programs$ webdriver-manager start
[06:39:49] I/start - java -Dwebdriver.chrome.driver=/Users/7stud/.nvm/versions/node/v7.4.0/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.26 -Dwebdriver.gecko.driver=/Users/7stud/.nvm/versions/node/v7.4.0/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.12.0 -jar /Users/7stud/.nvm/versions/node/v7.4.0/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar -port 4444
[06:39:49] I/start - seleniumProcess.pid: 63927
06:39:49.859 INFO - Launching a standalone Selenium Server
06:39:49.892 INFO - Java: Oracle Corporation 25.40-b25
06:39:49.893 INFO - OS: Mac OS X 10.10.5 x86_64
06:39:49.903 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
06:39:49.977 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
06:39:49.978 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
06:39:49.978 INFO - Driver class not found: com.opera.core.systems.OperaDriver
06:39:49.978 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
06:39:49.980 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
06:39:49.980 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
06:39:50.045 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
06:39:50.045 INFO - Selenium Server is up and running
```

**Comment by m-ajitabh** [comment]
Guys, I have clearly mentioned above Firefox browser v44.01.
Currently, Protractor supports Firefox browser till v44.0.1, do not use above version.
My test environment is Windows not MAC, so guys above settings are for Windows environment.

**Comment by m-ajitabh** [comment]
First install Firefox browser v44
Currently, Protractor supports Firefox browser till v44, do not use above
version.
My test environment is Windows not MAC, so guys above settings are for
Windows environment.

Might this will help as I don't have a MAC, I can support you theoretically.

  framework: 'jasmine',
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['spec.js'],

  capabilities: {
    browserName: 'firefox',
    platform: 'MAC',
    firefox_binary: '/Applications/Firefox.app/Contents/MacOS/firefox'
  }
}








Thanks
Ajitabh Ranjan
Mob: 9430331985

**Comment by m-ajitabh** [comment]
First install Firefox browser v44
Currently, Protractor supports Firefox browser till v44, do not use above
version.
My test environment is Windows not MAC, so guys above settings are for
Windows environment.


Thanks
Ajitabh Ranjan
Mob: 9430331985

**Comment by mgiambalvo** [comment]
This is an ancient issue, and unrelated to the Firefox woes of the modern era. Please see #3823.

The underlying issue is the version of Selenium that Protractor uses. Protractor 4 uses selenium 2.53, and only supports Firefox 47 or older.

Protractor 5 can work with Firefox 50, but only with selenium 3.0.0-beta4. Also, Firefox 50 has a bug that might affect Protractor testing, so using the 51 beta is recommended. Protractor 5.1 will support using Firefox 51 with `directConnect`.

**Comment by m-ajitabh** [comment]
Guys,

Running automation in firefox has some issues with the different versions
of different framework.
I am running my automation on chrome and it works perfect.

I have also executed my automation suites on firefox, but having older
version of firefox there are some bugs with the design of angular js app
which I was executing.

I setup the chrome as a base and now I am happy.

I do manual testing on firefox for further test.


Thanks
Ajitabh Ranjan
Mob: 9430331985

**Comment by rahulmr** [comment]
Hello All,

I am having same issue with latest Firefox version 52.0 32bit when I give directConnect: true nothing works seems like 2 firefox tabs are opened and test fails.
```

[09:54:22] Using gulpfile D:\projects\GIT hub\gulp-protractor fork\example\gulpfile.js
[09:54:22] Starting 'webdriver_update'...
[09:54:24] I/update - chromedriver: file exists D:\projects\GIT hub\gulp-protractor fork\node_modules\protractor\node_modules\webdriver
-manager\selenium\chromedriver_2.28.zip
[09:54:24] I/update - chromedriver: unzipping chromedriver_2.28.zip
[09:54:24] I/update - chromedriver: chromedriver_2.28.exe up to date
[09:54:24] I/update - selenium standalone: file exists D:\projects\GIT hub\gulp-protractor fork\node_modules\protractor\node_modules\we
bdriver-manager\selenium\selenium-server-standalone-3.3.1.jar
[09:54:24] I/update - selenium standalone: selenium-server-standalone-3.3.1.jar up to date
[09:54:26] I/update - geckodriver: file exists D:\projects\GIT hub\gulp-protractor fork\node_modules\protractor\node_modules\webdriver-
manager\selenium\geckodriver-v0.15.0.zip
[09:54:26] I/update - geckodriver: unzipping geckodriver-v0.15.0.zip
[09:54:26] I/update - geckodriver: geckodriver-v0.15.0.exe up to date
[09:54:26] Finished 'webdriver_update' after 3.91 s
[09:54:26] Starting 'protractor'...
[09:54:27] W/driverProviders - Using driver provider directConnect, but also found extra driver provider parameter(s): seleniumAddress
[09:54:27] I/launcher - Running 1 instances of WebDriver
[09:54:27] I/direct - Using FirefoxDriver directly...
[09:54:34] E/launcher - Unable to parse new session response: {"value": {"sessionId":"2ae0d0d4-bd6e-4683-bcd7-adccf83e66dd","value":{"a
cceptInsecureCerts":false,"browserName":"firefox","browserVersion":"52.0","moz:accessibilityChecks":false,"moz:processID":31788,"moz:pr
ofile":"C:\\Users\\Rahul\\AppData\\Local\\Temp\\rust_mozprofile.nMy4w0qmOZqL","pageLoadStrategy":"normal","platformName":"windows_nt","
platformVersion":"10.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"page load":300000,"script":30000}}}}
[09:54:34] E/launcher - WebDriverError: Unable to parse new session response: {"value": {"sessionId":"2ae0d0d4-bd6e-4683-bcd7-adccf83e6
6dd","value":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"52.0","moz:accessibilityChecks":false,"moz:processI
D":31788,"moz:profile":"C:\\Users\\Rahul\\AppData\\Local\\Temp\\rust_mozprofile.nMy4w0qmOZqL","pageLoadStrategy":"normal","platformName
":"windows_nt","platformVersion":"10.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"page load":300000,"script":3
0000}}}}
    at WebDriverError (D:\projects\GIT hub\gulp-protractor fork\node_modules\selenium-webdriver\lib\error.js:27:5)
    at doSend.then.response (D:\projects\GIT hub\gulp-protractor fork\node_modules\selenium-webdriver\lib\http.js:445:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()

    at Function.createSession (D:\projects\GIT hub\gulp-protractor fork\node_modules\selenium-webdriver\lib\webdriver.js:777:24)
    at Function.createSession (D:\projects\GIT hub\gulp-protractor fork\node_modules\selenium-webdriver\firefox\index.js:640:55)
    at Direct.getNewDriver (D:\projects\GIT hub\gulp-protractor fork\node_modules\protractor\lib\driverProviders\direct.ts:112:25)
    at Runner.createBrowser (D:\projects\GIT hub\gulp-protractor fork\node_modules\protractor\lib\runner.ts:225:39)
    at q.then.then (D:\projects\GIT hub\gulp-protractor fork\node_modules\protractor\lib\runner.ts:391:27)
    at _fulfilled (D:\projects\GIT hub\gulp-protractor fork\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (D:\projects\GIT hub\gulp-protractor fork\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\projects\GIT hub\gulp-protractor fork\node_modules\q\q.js:796:13)
    at D:\projects\GIT hub\gulp-protractor fork\node_modules\q\q.js:556:49
    at runSingle (D:\projects\GIT hub\gulp-protractor fork\node_modules\q\q.js:137:13)
[09:54:34] E/launcher - Process exited with error code 199
{ [Error: protractor exited with code 199]
  message: 'protractor exited with code 199',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-protractor',
  __safety: { toString: [Function: bound ] } }
```
But when I start selenium standalone server with gecko driver location and remove directConnect then it works fine.

**Comment by m-ajitabh** [comment]
Update your protractor and try again.


Thanks
Ajitabh Ranjan
Mob: 9430331985

**Comment by rahulmr** [comment]
It is latest one 5.1.1

**Comment by m-ajitabh** [comment]
I am not using the gulp to run the protector.
I am using the protractor directly with firefox configuration and it is
running.
How have you configured firefox????

**Comment by makwanaparth94** [comment]
Not able to Run Protractor Test on Firefox browser
Failed:
[INFO] Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
[INFO] System info: host: 'MC0XSZYC', ip: '10.87.197.153', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
[INFO] Driver info: driver.version:

Eclipse raised these issue while running test on firefox

![image](https://user-images.githubusercontent.com/28529639/30109854-86ed7510-9325-11e7-983c-a5eb2176b708.png)

**Comment by wswebcreation** [comment]
@makwanaparth94 

Can you provide more info, like which version:

- protractor
- firefox
- the firefox driver you are using

**Comment by makwanaparth94** [comment]
Yeah sure!
I am using Protractor v5.1,Firefox 55.0.3 and geckodriver: 0.18.0

**Comment by kangaro0** [comment]
@makwanaparth94 I ran into this issue while testing with protractor too. The problem was that firefox lost focus, because of me fiddeling around while protractor was running. When I left it do its thing everything went well.
