### ISSUE TITLE
Cannot launch Chrome: OSX 10.9.3, Selenium 2.42.0, chromedriver 2.10

### ISSUE THREAD

**Issue by ldeavila** [angular/protractor#954]
Trying to run protractor tests on OSX. We get the error below. Have tried a variety of fixes suggested. I think we're running the latest stand-alone server and chrome driver. Thoughts?

```
/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:109
 var template = new Error(this.message);
                ^
UnknownError: null
   at new bot.Error (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:109:18)
   at Object.bot.response.checkResponse (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
   at /Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:134:24
   at /Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1243:15
   at webdriver.promise.ControlFlow.runInNewFrame_ (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1531:20)
   at notify (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:354:12)
   at notifyAll (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:323:7)
   at resolve (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:301:7)
   at fulfill (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:421:5)
   at /Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1243:15
==== async task ====
WebDriver.createSession()
   at Function.webdriver.WebDriver.acquireSession_ (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:49)
   at Function.webdriver.WebDriver.createSession (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:111:30)
   at Builder.build (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/builder.js:106:20)
   at HostedDriverProvider.getDriver (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/lib/driverProviders/hosted.js:54:9)
   at /Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/lib/runner.js:207:35
   at _fulfilled (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:797:54)
   at self.promiseDispatch.done (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:826:30)
   at Promise.promise.promiseDispatch (/Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:759:13)
   at /Users/riley/dash.frontend/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:525:49
```

**Comment by lopesc** [comment]
Does anybody know how the issue here was fixed:
https://groups.google.com/forum/#!topic/angular-dev/kXk4bkHdY5A

You'll note that build 402 fails with the same error we are getting and then build 403 is fine.  It might be indicating that something was misconfigured on the machine, since there were no changes in the repository between those two builds.

Date: Mon, 28 Jul 2014 14:13:55 -0700

**Comment by lopesc** [comment]
Apologies for the late reply.  It turns out that the version of Chrome on the machine was out of date.  Chrome driver 2.10 supports versions 33-36.  Upgrading to one of those resolve issue for me.

--- Original Message ---

**Comment by abhishek402** [comment]
Even i downgraded from 2.10 to 2.9 its working properly.

**Comment by yesobo** [comment]
I Downgraded from 2.10 to 2.9 as coderigo said and it solved the problem. I'm on chrome v 40.

**Comment by c0debreaker** [comment]
Ok, I'm going to try downgrading to 2.9 too. I'll let you know later

**Comment by arun0009** [comment]
I downgraded my chromedriver to 2.9 in /usr/bin location and /usr/local/lib/node_modules/protractor/selenium/ location (from 2.15) and it started working as expected.
